deployment/ansible/roles/raster-foundry.app/tasks/static-files.yml, scripts/bundle.sh, src/rf/.eslintrc, src/rf/apps/home/templates/home/home.html, src/rf/bundle.sh, src/rf/js/src/main.js, src/rf/npm-shrinkwrap.json, src/rf/package.json
Copied from MMW with modifications to support React.
Connects #22
=> Add bundle.sh with React support

src/rf/apps/home/templates/base.html, src/rf/apps/home/urls.py, src/rf/js/src/app.js, src/rf/js/src/core/setup.js, src/rf/js/src/core/utils.js, src/rf/js/src/home/controllers.js, src/rf/js/src/home/views.js, src/rf/js/src/main.js, src/rf/js/src/router.js, src/rf/js/src/routes.js
This demonstrates how to wire up JSX and navigate between different
routes in the application.
Connects #17
Depends on #32
=> Convert login page prototype to JSX

src/rf/apps/core/admin.py, src/rf/apps/core/enums.py, src/rf/apps/core/migrations/0001_initial.py, src/rf/apps/core/migrations/0002_auto_20150817_1235.py, src/rf/apps/core/models.py
Stub out Django models based on prototype.
Connects #13
=> Stub out Django models

src/rf/npm-shrinkwrap.json, src/rf/package.json
=> Remove leaflet draw.

prototype/assets/sass/pages/_login.scss, src/rf/apps/home/urls.py, src/rf/apps/user/views.py, src/rf/js/src/app.js, src/rf/js/src/home/components/library.js, src/rf/js/src/home/components/login.js, src/rf/js/src/home/controllers.js, src/rf/js/src/main.js, src/rf/js/src/settings.js, src/rf/js/src/user/models.js, src/rf/rf/urls.py, src/rf/sass/pages/_login.scss
To test: 
* create a user using `createsuperuser`
* Go to `/` and try logging in with invalid credentials. You should see an error message.
* Try again with valid credentials which should lead to the library view
* Hit reload and you should go straight to the library view instead of having to login
* Hit logout which should lead to the login screen
Known issues I'm currently working on: 
* the size of the login div changes when the error message appears
* 'guest' should be changed to 'not_logged_in' since we don't have guest functionality in RF
Connects #49
=> Login and logout

src/rf/js/src/home/components/library.js
We do not have support for projects yet.
=> Remove projects from menu dropdown

deployment/ansible/group_vars/test, scripts/test.sh, src/rf/apps/core/decorators.py, src/rf/apps/core/exceptions.py, src/rf/apps/core/migrations/0009_auto_20150908_1326.py, src/rf/apps/core/models.py, src/rf/apps/home/forms.py, src/rf/apps/home/tests.py, src/rf/apps/home/urls.py, src/rf/apps/home/views.py, src/rf/apps/user/tests.py, src/rf/apps/user/urls.py, src/rf/apps/user/views.py, src/rf/requirements/base.txt
Enables unit tests to run during CI.
Includes code fixups and refactorings to make all tests pass.
Connects #56
=> Fix unit tests

scripts/check.sh, scripts/test.sh, src/rf/apps/home/urls.py, src/rf/js/src/home/components/library.js, src/rf/js/src/home/components/menu.js, src/rf/js/src/routes.js, src/rf/js/src/user/components.js, src/rf/js/src/user/controllers.js
Migrate account screens from prototype and make the menu more dynamic.
Connects #21
=> Add account screens

src/rf/js/src/home/components/library.js, src/rf/js/src/home/controllers.js, src/rf/js/src/layer/models.js
Populate layer selector components with actual data.
Easier to test with #91.
=> Wire up endpoints to layer selector

src/rf/js/src/home/components/library.js
This was copied from the prototype.
Before:
After:
=> Enable scrolling in layer selector component

src/rf/apps/core/models.py, src/rf/js/src/core/models.js, src/rf/js/src/home/components/library.js, src/rf/js/src/home/controllers.js
Click the checkbox next to each layer to add a new tile layer to the
map.
For testing purposes, this is wired up to use test tiles that I uploaded
manually to S3.
Connects #82
Depends on #95
**Note:** The tiles should appear near Nepal.
=> Enable toggling tile layers

src/rf/js/src/user/models.js
=> Consider anystring@anystring.anystring a valid email

src/rf/apps/core/models.py, src/rf/apps/home/views.py, src/rf/js/src/core/models.js, src/rf/js/src/home/components/library.js
You should now be able to favorite and un-favorite a layer by clicking
the star in the layer selector.
Depends on #96
=> Enable saving/loading layer favorites

src/rf/apps/core/decorators.py, src/rf/apps/core/enums.py, src/rf/apps/core/migrations/0010_auto_20150915_1421.py, src/rf/apps/core/migrations/0011_auto_20150923_1057.py, src/rf/apps/core/migrations/0012_auto_20150923_1246.py, src/rf/apps/core/models.py, src/rf/apps/home/forms.py, src/rf/apps/home/tests.py, src/rf/apps/home/views.py, src/rf/bundle.sh, src/rf/js/src/home/components/modals.js, src/rf/js/src/settings.js, src/rf/js/src/user/models.js, src/rf/npm-shrinkwrap.json, src/rf/package.json
Run `npm.sh install`, `bundle.sh --vendor` and `manage.sh migrate`
* Create a new import. Upon success, the modal should be hidden. Check that the database is updated correctly for all fields. Try out different options of dropdowns. 
* After clicking the import button after a successful submission, all fields should be clear.
* After closing the import modal before a successful submission, and then opening it, the fields should retain their values.
* Try to hit all client-side and server-side error conditions using the validation functions as a guide. When using an existing layer name for a user, you should be brought back to Pane-2 and the error message will persist until changing the layer name.
* Make sure that back buttons work.
* The following inputs need further guidance from …
=> Wire up import modal

src/rf/sass/main.scss, src/rf/sass/vendors/_bootstrap-tagsinput.scss
=> fixed tags field appearance, fixes #122

src/rf/apps/core/migrations/0013_auto_20150929_1449.py, src/rf/apps/core/migrations/0015_merge.py, src/rf/apps/core/migrations/0018_merge.py, src/rf/apps/core/models.py, src/rf/js/src/core/models.js, src/rf/js/src/home/components/library.js, src/rf/js/src/home/mixins.js
=> Wire up layer detail and image meta data panels

src/rf/js/src/home/components/library.js, src/rf/js/src/home/components/modals.js, src/rf/js/src/user/components.js
Hiding these options for now until they are ready to be implemented. The
text has also been updated to be more accurate.
=> Remove unused options and update text

src/rf/js/src/home/components/menu.js
When clicking Logout, a dialog box should appear if any uploads are in progress. Clicking Ok should logout, and Cancel should abort the logout attempt.
Connects #152
=> Confirm logout if uploading

src/rf/apps/user/views.py, src/rf/js/src/user/components.js, src/rf/sass/pages/_login.scss
=> Hide activation, forgot, and agreed checkbox

deployment/ansible/roles/raster-foundry.worker/templates/upstart-worker.conf.j2, src/rf/apps/workers/management/commands/poll.py
To test, provision the worker and then import a layer. A checkmark should appear next to Uploading in the processing block.
Connects #198
=> Start worker process during provisioning

Vagrantfile, src/rf/apps/core/enums.py, src/rf/apps/core/migrations/0023_update_thumbs_status.py, src/rf/apps/core/models.py, src/rf/apps/workers/process.py, src/rf/apps/workers/thumbnail.py, src/rf/requirements/base.txt
Creates thumbnails on the worker VM for Layers and LayerImages.
* Reload and provision the worker to add more memory and run pip.
* Clear your SQS queue
* Start up the worker polling
* Import a new layer. Try using a small file first, and then a large TIF. This will probably only be visible with the large file, but you should see the checkmark next to uploaded before the thumbnail is visible.
* With the large sample TIFs, I noticed there is a black band on the side of the thumbnails. I'd like to fix this in a separate PR.
Connects #161 
Connects #188
=> Create thumbnails 

src/rf/apps/workers/management/commands/poll.py, src/rf/apps/workers/process.py, src/rf/apps/workers/sqs_manager.py, src/rf/rf/settings/base.py, src/rf/rf/settings/development.py
Upgrade to boto3 so all major application components are using the same
AWS library.
The name of the fields saved to SQS have been renamed to make things
less ambiguous.
One unexpected (but notable) benefit to upgrading is that SQS messages are
no longer base64 encoded.
Connects #210
=> Upgrade queue processor to boto3

deployment/ansible/roles/raster-foundry.app/tasks/static-files.yml, src/rf/rf/settings/base.py
Since this setting is a non-empty string the value is always truthy.
Casting to boolean corrects this mistake.
=> Cast AWS_EMR_DEBUG to boolean

src/rf/apps/core/migrations/0028_allow_null.py, src/rf/apps/core/models.py, src/rf/apps/home/forms.py, src/rf/apps/home/tests.py, src/rf/js/src/core/uploads.js, src/rf/js/src/home/components/modals.js
* Client only allows importing tifs
* Import accepts S3 URI instead of bucket/key
* Change validation so most fields are optional
Connects #253
=> Improve validation

src/rf/apps/core/enums.py, src/rf/apps/core/migrations/0029_add_statuses.py, src/rf/apps/workers/process.py
Test by manually adding messages to the queue and check the status in the DB.
ex: 
{
"jobId": 17,
"stage": "mosaic",
"status": "FINISHED"
}
=> Update status during EMR steps

scripts/poll.sh
This runs the poll service on the worker VM.
=> Add scripts/poll.sh 

src/rf/apps/workers/image_validator.py, src/rf/apps/workers/process.py, src/rf/apps/workers/thumbnail.py
Fixes an issue where GeoTIFFs with headers beyond the first 1000 bytes
of the file would fail to validate.
Connects #209
=> Use vsicurl to validate images

src/rf/apps/workers/process.py, src/rf/js/src/home/components/modals.js
This adds support for other S3 URI formats.
Connects #275
=> Add support for S3 HTTPS URI

src/rf/apps/workers/thumbnail.py
Ensure layer is saved after assigning thumbnail key.
Connects #303
=> Save layer thumbnail

src/rf/apps/workers/process.py
=> Delete validation job when successful

src/rf/js/src/core/models.js, src/rf/js/src/home/components/modals.js, src/rf/js/src/home/components/processing-block.js
To test, import a new layer. The processing block should expand automatically and the new layer should be at the top of the list.
Connects #244 
Connects #312
=> Order layers and expand processing block

src/rf/apps/workers/process.py, src/rf/apps/workers/status_updates.py, src/rf/apps/workers/thumbnail.py
For each layer, a separate job is queued for thumbnailing each image as well as a job for thumbnailing the layer itself. This will enable more parallelism. To test, submit a layer and check that separate jobs are created in the log, and that all thumbnails are actually created.
Connects #262
=> Split up thumbnail job

src/rf/apps/core/decorators.py, src/rf/apps/home/static/swagger.yaml
Minor updates to swagger file as part of #331.
Connects #331
=> Minor updates to swagger.yaml 

src/rf/js/src/core/views.js
=> Add transparent "no data" layer

doc/architecture/adr-0003-testing-philosophy.md
Architecture Decision Record for choosing when to include tests,
targeting how to avoid worthless tests, how to retire tests that
become worthless, what sorts of changes require tests, and what
this means for how we manage work in Raster Foundry.
=> Add testing philosophy ADR

docs/architecture/adr-0002-api-documentation.md
Depends on #373 
Adds ADR for choosing an API design/documentation framework.
=> ADR - API Design/Documentation Framework

docs/architecture/adr-0009-ci-server.md
Adds an ADR for choosing a CI server
=> Add ADR for CI server

.gitignore, README.md, app-frontend/config/webpack/environments/development.js, app-server/app/src/main/scala/Router.scala, app-server/app/src/main/scala/healthcheck/package.scala, app-server/app/src/main/scala/user/Routes.scala, app-server/app/src/main/scala/user/User.scala, app-server/app/src/main/scala/user/package.scala
Users endpoint:
/users/ - GET : list all users
/users/ - POST : Create new user
/users/{UUID} - GET : get user with UUID={UUID}
/users/{UUID} - PUT : update user with UUID={UUID}
every request which specifies user information must have every field:
when creating a new user, timestamp and id fields must be set to null
API status codes match those specified in docs/swagger/spec.yml
Change frontend dev server port from 9090 -> 9091
Add .ensime file to gitignore
=> Add users endpoint

.gitignore, deployment/ansible/group_vars/all, deployment/ansible/raster-foundry-jenkins.yml, deployment/ansible/roles.yml, deployment/ansible/roles/raster-foundry.aws-cli/meta/main.yml, deployment/ansible/roles/raster-foundry.aws-cli/tasks/main.yml, deployment/ansible/roles/raster-foundry.docker/defaults/main.yml, deployment/ansible/roles/raster-foundry.docker/meta/main.yml, deployment/ansible/roles/raster-foundry.docker/tasks/main.yml, deployment/ansible/roles/raster-foundry.jenkins/tasks/main.yml, deployment/ansible/roles/raster-foundry.shellcheck/tasks/main.yml
Ensure that Docker, Docker Compose, Shellcheck, and the AWS CLI are all installed alongside Jenkins.
---
**Testing**
Ensure that the `raster-foundry-jenkins.yml` playbook applies cleanly against the Jenkins instance.
```bash
$ ssh-add ~/.ssh/raster-foundry-stg.pem
$ ansible-playbook -i deployment/ansible/inventory/jenkins \
deployment/ansible/raster-foundry-jenkins.yml
```
=> Add Jenkins build dependencies

Jenkinsfile, app-server/app/.dockerignore, app-server/app/Dockerfile, docker-compose.test.yml, docker-compose.yml, nginx/Dockerfile, scripts/cibuild, scripts/setup, scripts/test
Create a `Jenkinsfile` that uses a `cibuild.sh` script to automatically build docker images. 
Ensure that this job runs fully, and that `docker images` lists `raster-foundry-{service}:{GIT_COMMIT}` images, tagged with a git commit SHA.
<pre><code>
$ docker images
REPOSITORY                  TAG                      IMAGE ID            CREATED             SIZE
<b>raster-foundry-nginx        2f49953</b>                  0703301d0ac0        35 minutes ago      206.9 MB
<b>raster-foundry-app-server   2f49953</b>                  2db426d400b4        35 minutes ago      142.6 MB
<b>raster-foundry-airflow      2f49953</b>                  c951d062a8ac        35 minutes ago      946.7 MB
</code></pre>
=> WIP: Create Jenkins Pipeline Part 1 - CIBuild

app-server/app/src/main/scala/user/Routes.scala, app-server/app/src/main/scala/user/User.scala, app-server/app/src/main/scala/user/package.scala
Make date fields read-only
Don't require all fields for user creation
=> Hide fields in API

scripts/setup
Provision and watch the log output. If you have already initialized migrations, you should see a message "Migrations already initialized", otherwise it will initialize the db for migrations. Then if you don't have up-to-date migrations, you should see the migrations being applied.
I tested this with a fresh database, as well as one already initialized with migrations.
=> Run migrations on setup

app-server/app/src/main/scala/RfJsonProtocols.scala, app-server/app/src/main/scala/Router.scala, app-server/app/src/main/scala/healthcheck/Routes.scala, app-server/app/src/main/scala/organization/Organization.scala, app-server/app/src/main/scala/organization/Routes.scala, app-server/app/src/main/scala/organization/package.scala, app-server/app/src/main/scala/user/Routes.scala, app-server/app/src/main/scala/user/User.scala, app-server/app/src/main/scala/user/UserRoles.scala, app-server/app/src/main/scala/user/package.scala, app-server/app/src/main/scala/utils/Exceptions.scala, app-server/app/src/test/scala/organization/OrganizationSpec.scala, docs/swagger/spec.yml
Move Exceptions and Exception Handlers to Util
Create RfJsonProtocols trait for common Mashallers and extend for each
domain
Update swagger spec
Rename Roles to UserRoles (scalastyle warning)
=> Add Organizations endpoint

app-server/app/src/main/scala/organization/Routes.scala, app-server/app/src/test/scala/AuthUtils.scala, app-server/app/src/test/scala/auth/AuthSpec.scala, app-server/app/src/test/scala/healthcheck/HealthCheckSpec.scala, app-server/app/src/test/scala/organization/OrganizationSpec.scala, app-server/app/src/test/scala/user/UserSpec.scala, app-server/app/src/test/scala/utils/PGUtilsSpec.scala
Create tests for Authentication directives
=> Create tests for all existing endpoints

Jenkinsfile
Usage of `stage` within a `Jenkinsfile` without a block has been deprecated and results in the following build log message:
>  Using the ‘stage’ step without a block argument is deprecated
---
**Testing**
Inspect the Jenkins output of the following jobs to ensure that the build stages are still executing correctly:
- http://jenkins.staging.rasterfoundry.com/job/raster-foundry/job/raster-foundry/job/feature%252Fhmc%252Fstage-block/
- http://jenkins.staging.rasterfoundry.com/job/raster-foundry/job/raster-foundry/job/PR-473/
=> Use Groovy block syntax in Jenkinsfile for stages

docs/architecture/adr-0010-domain-layout.md
In addition to describing the domain layout, this ADR discusses technologies chosen for the landing page and blog.
Resolves https://github.com/azavea/raster-foundry/issues/499
See:
- https://github.com/azavea/raster-foundry-website
- https://blog.rasterfoundry.com/
=> Add ADR for domain layout

app-server/app/src/test/scala/scene/SceneSpec.scala, docker-compose.yml, scripts/cibuild
We are running into some build issues with the front-end that so far seems to be tied to the node version being used, this fixes it
=> Bump the node version

app-backend/.dockerignore, app-backend/Dockerfile, docker-compose.test.yml, scripts/cibuild, scripts/cipublish
Adds an SBT container so that we can run migrations
* Go to `app-backend`
* Run `docker build -t sbt-test .`
* Run `docker run sbt-test` and mess in the sbt shell (run `update`, `compile`, things should generally work)
=> Add sbt container

app-frontend/src/app/components/leafletMap/leafletMap.controller.js, app-frontend/src/app/components/navBar/navBar.html, app-frontend/src/app/components/sceneItem/sceneItem.html, app-frontend/src/app/pages/browse/browse.html, app-frontend/src/app/pages/settings/profile/profile.html, docker-compose.test.yml, docker-compose.yml, nginx/etc/nginx/conf.d/default.conf, scripts/cibuild, scripts/cipublish, scripts/server, scripts/setup, scripts/test
Changes consist of:
- Making sure all external references use HTTPS
- Fix Nginx upstreams
- Fix Nginx web root for Angular application
Depends on https://github.com/azavea/raster-foundry-deployment/pull/6
Most of these changes have already been applied to get the staging environment into a working state. If merged as it, the Nginx container image will be left in a broken state because its upstream setting will reference a non-existent container (`app-server` vs. `app-backend`).
I think we need to settle on one or the other, and whatever we settle on should remain consistent across ECS task definitions and Docker Compose YAMLs.
=> Make changes required for ECS deployment

docs/deployment/MIGRATIONS.md
Add documentation explaining how to run migration commands on the ECS cluster.
N/A
N/A
Follow the instructions in `MIGRATIONS.md` to run a migration in the staging environment; check logs output to ensure the migrations ran successfully.
Connects #560
=> Add migrations documentation

app-backend/app/src/main/scala/bucket/Routes.scala, app-backend/app/src/test/scala/bucket/BucketSceneSpec.scala, app-backend/database/src/main/scala/com/azavea/rf/database/tables/Buckets.scala, app-frontend/src/app/components/bucketAddModal/bucketAddModal.controller.js, app-frontend/src/app/core/services/bucket.service.js, app-frontend/src/app/pages/library/buckets/detail/bucketScenes/bucketScenes.controller.js
Batch add and remove bucket scenes
- Start and open frontend
- Open browser dev tools
- On the browse and library/scenes views, add select scenes and add them to a bucket
- Check that there is only one request sent per bucket
- On the library/bucket view, remove scenes from a bucket
- Check that only one request is made for the delete
Fixes #530
=> Batch add/remove bucket scenes

.github/PULL_REQUEST_TEMPLATE.md, Vagrantfile, docs/swagger/spec.yml, scripts/server
This pull request updates the swagger specification to be more in line with where the API has migrated to and updates it in anticipation of starting work on the model catalog.
A few API endpoints have been edited since the swagger spec was
written. The goal of this commit is to get the spec more in line with
how the API has been implemented and also eliminated some
inconsistencies.
Summary of endpoints updated:
- Added Authentication tag and removed Organization
- Removed boundaries model
- Changed references to boundary to scene
- Added band model
- Added endpoints for tokens
- Updated buckets endpoints to reflect bulk API implementation
Endpoints added to support model catalog
- model endpoint for geoprocessing models
- model tags endpoint to store tags
- model category endpoints to …
=> Update Swagger Specification and Add Model Catalog

deployment/ansible/group_vars/all
See: https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#079-november-4-2016
Execute the following command from within the `deployment` directory:
```bash
$ ansible-playbook -i ansible/inventory/jenkins ansible/raster-foundry-jenkins.yml
```
The recap should result in zero tasks changed:
```
PLAY RECAP *********************************************************************
jenkins_master             : ok=39   changed=0    unreachable=0    failed=0
```
=> Bump Terraform to version 0.7.9

docs/swagger/spec.yml
Add spec for scene-grids
Add SceneGrid object definition
Connects #653
=> Add spec for /scene-grids/

README.md, Vagrantfile, app-backend/.dockerignore, app-backend/build.sbt, app-backend/project/Dependencies.scala, app-backend/project/Version.scala, app-backend/tile/Dockerfile, app-backend/tile/build.sbt, app-backend/tile/src/main/resources/application.conf, app-backend/tile/src/main/resources/logback.xml, app-backend/tile/src/main/scala/Config.scala, app-backend/tile/src/main/scala/LayerCache.scala, app-backend/tile/src/main/scala/Main.scala, app-backend/tile/src/main/scala/Routes.scala, app-backend/tile/src/main/scala/image/ImageParams.scala, app-backend/tile/src/main/scala/image/Render.scala, app-backend/tile/src/main/scala/model/ModelParams.scala, app-backend/tile/src/main/scala/model/NDVI.scala, app-backend/tile/src/main/scala/model/NDWI.scala, docker-compose.test.yml, docker-compose.yml, scripts/cibuild, scripts/cipublish, scripts/server
Introduces a `tile-server` project which currently is able to render single multi-band layer from S3. 
`export TILESERVER_BUCKET=geotrellis-test`
`sbt "project tileserver" "runMain com.azavea.rf.tileserver.Main"`
`http://localhost:9090/tiles/landsat-rgb-1/8436f7e9-b7f7-4d4f-bda8-76b32c356bff/ndvi/11/1822/805?bands=1,3`
`http://localhost:9090/tiles/landsat-rgb-1/8436f7e9-b7f7-4d4f-bda8-76b32c356bff/rgb/11/1822/805`
Connects https://github.com/azavea/raster-foundry/issues/663
Connects https://github.com/azavea/raster-foundry/issues/666
=> Tile Server [WIP]

scripts/test
Remove test which depends on jar build prior to running.
=> Remove ingest test

app-backend/tile/src/main/scala/Config.scala, app-backend/tile/src/main/scala/LayerCache.scala, app-backend/tile/src/main/scala/Main.scala, app-backend/tile/src/main/scala/RfLayerId.scala, app-backend/tile/src/main/scala/Routes.scala, app-backend/tile/src/main/scala/StitchLayer.scala, app-backend/tile/src/main/scala/image/ColorCorrect.scala, app-backend/tile/src/main/scala/image/Mosaic.scala
This implements mosaic tiler endpoint.
Requires: https://github.com/azavea/raster-foundry/pull/719
```bash
export AWS_PROFILE=raster-foundry
export TILE_SERVER_BUCKET=rasterfoundry-staging-catalogs-us-east-1
sbt tile/run
```
```
http://localhost:9900/tiles/dfac6307-b5ef-43f7-beda-b9f208bb7726/rf_airflow-user/mosaic/{z}/{x}/{y}?redBand=3&greenBand=2&blueBand=1&scene=0b326643-6082-4a0d-81ed-0bff0dfbd173&scene=0b5b7404-60b0-4589-a60d-53273bea638d&scene=26eade49-108a-49cb-a338-01ead6d219b3&scene=29deea03-8e1c-4216-a777-f050a52142b8&scene=2a6636d4-6048-45d6-884e-a6829d474157&scene=2b3fcf11-66ef-4c26-90bf-9df4f6c726a9&scene=34f86dde-74c1-4758-928b-49332f9cbba2&scene=3644d02a-a0fb-4027-9eec-e0650c9bde8f&scene=3954b172-7a57-45e3-8a38-6cc3cb01bfb9&scene=415db9f2-159f-476f-beaa-ac6acdd10f4c&scene=4b …
```
=> Mosaic ColorCorrecting Tiler

docs/architecture/adr-0012-map-component-api.md
ADR for the leaflet map component
=> Add ADR 0012 Map Component Api

docs/architecture/adr-0012-spark-execution-environment.md
See contents of ADR-0012 for more details.
Resolves #718
=> Add ADR for Spark execution environment

app-backend/migrations/src_migrations/main/scala/33.scala
=> Add migration to provide 3 sample tools

docker-compose.yml, scripts/bootstrap
Add a Memcached service to Docker Composer and link it to the tile server at `tile-cache.service.rasterfoundry.internal`.
Execute `./scripts/server` to bring up all of the services referenced in `docker-compose.yml`, then login to the `tiler-server`, install `telnet`, and interact with the Memcached instance:
```bash
vagrant@vagrant-ubuntu-trusty-64:/opt/raster-foundry$ docker-compose exec tile-server /bin/bash
root@2fcbdd0fc2a9:/opt/raster-foundry/app-backend# apt-get update && apt-get install telnet              
root@2fcbdd0fc2a9:/opt/raster-foundry/app-backend# telnet tile-cache.service.rasterfoundry.internal 11211
Trying 172.18.0.4...
Connected to tile-cache.service.rasterfoundry.internal.
Escape character is '^]'.
stats
STAT pid 1
STAT uptime 384
STAT time 1483044408
STAT version …
```
=> Add Memcached service to Docker Compose

app-frontend/src/app/components/colorCorrectPane/colorCorrectPane.controller.js
When in color correction, shows the resultant histogram of ALL scenes being corrected.
This can be slow with a large number of scenes due to concurrent request limits (would not be an issue with HTTP/2). Also has a flag to smooth the resultant histogram by removing 0 value bins.
This updates the histogram as the requests are processed and does not wait for all histograms to load (aiming for the histogram to be useful as quickly as possible).
This may benefit from an improved method of handling loading errors.
* Select multiple scenes to color correct
* See that histograms are combined (compare with single scenes)
Connects #828
=> Add experimental histogram summation for color correction

app-frontend/package.json, app-frontend/src/app/components/colorCorrectPane/colorCorrectPane.html, app-frontend/src/app/components/filterPane/filterPane.html, app-frontend/src/app/components/maskItem/maskItem.html, app-frontend/src/app/components/mosaicMask/mosaicMask.html, app-frontend/src/app/components/mosaicMask/mosaicMask.state.html, app-frontend/src/app/components/mosaicParameters/mosaicScenesParameters.html, app-frontend/src/app/components/mosaicScenes/mosaicScenes.html, app-frontend/src/app/components/projectAddModal/projectAddModal.html, app-frontend/src/app/components/publishModal/publishModal.html, app-frontend/src/app/core/services/gridLayer.service.js, app-frontend/src/app/index.routes.js, app-frontend/src/app/pages/browse/browse.html, app-frontend/src/app/pages/editor/project/projectEdit.html, app-frontend/src/app/pages/library/projects/detail/projectScenes/projectScenes.html, app-frontend/src/app/pages/library/scenes/detail/detail.html, app-frontend/src/assets/styles/sass/_shame.scss, app-frontend/src/assets/styles/sass/app.scss, app-frontend/src/assets/styles/sass/components/_form.scss
There are far too many minor style changes to document them all. All style changes are put in a temporary `_shame.scss` file. Eventually all of these styles will be refactored and reorganized. 
Changes made to `/browse` `/editor` `/library...` 
=> Cleanup of the app for the demo

app-frontend/src/app/pages/library/scenes/list/list.html
Removes lorem copy and adds copy similar to that on the website.
* Read the new copy and ensure it makes sense
Connects #835
=> Clean up copy on library scene list

app-backend/build.sbt, app-backend/project/Version.scala, app-backend/tile/src/main/scala/LayerCache.scala, app-backend/tile/src/main/scala/Router.scala
This pull request bumps the GeoTrellis version to its 1.0 release and removes unnecessary resolvers.
Connects #806
=> Bump geotrellis to 1.0 release

app-frontend/src/tpl-index.html
Adds google fonts to template, these were not getting loaded by webpack
=> Add google fonts to template

app-frontend/src/app/pages/library/scenes/detail/detail.controller.js, app-frontend/src/app/pages/library/scenes/detail/detail.html
"Add to Project" Link didn't do anything
* Verify that adding scenes to projects from the scene detail view functions as expected
=> Add project modal to scene detail page

app-frontend/.eslintrc, app-frontend/src/app/components/diagramContainer/diagramContainer.controller.js, app-frontend/src/app/components/diagramContainer/toolJson.js, app-frontend/src/app/pages/lab/run/run.controller.js, app-frontend/src/app/pages/lab/run/run.html
This PR uses the example JSON shown in #1046 (slightly modified) structure to generate a diagram. The main JSON structure used in this PR:
```
{
"apply": "-",
"tag": "final",
"label": "Vegetation Difference",
"args": [
{
"label": "Detect Vegetation - Before",
"tag": "class0",
"apply": "reclassify",
"args": {
"breaks": {
"type": "class-breaks"
},
"layer": {
"label": "Vegetation Index - Before",
"tag": "ndvi0",
"apply": "ndvi",
"args": [{
"type": "layer",
"label": "Area of Interest - Before",
"tag": "input_0"
}]
}
}
},
{
"apply": "reclassify",
"label": "Detect Vegetation - After",
"tag": "class1",
"args": {
"breaks": {
"type": "class-breaks"
},
"layer": {
"label": "Vegetation Index - After",
"tag": "ndvi1",
"apply": "ndvi",
"args": [{
"type": "layer",
"label": "Area of Interest - After", …
```
=> Build diagram from tool JSON

app-frontend/src/app/components/mosaicMask/mosaicMask.scss, app-frontend/src/app/pages/lab/lab.scss, app-frontend/src/app/pages/settings/tokens/tokens.html, app-frontend/src/assets/styles/sass/_shame.scss, app-frontend/src/assets/styles/sass/base/_helpers.scss, app-frontend/src/assets/styles/sass/components/_form.scss, app-frontend/src/assets/styles/sass/components/_list-group.scss, app-frontend/src/assets/styles/sass/components/_map.scss, app-frontend/src/assets/styles/sass/components/_modal.scss, app-frontend/src/assets/styles/sass/components/_slider.scss, app-frontend/src/assets/styles/sass/layout/_container.scss, app-frontend/src/assets/styles/sass/layout/_main.scss, app-frontend/src/assets/styles/sass/layout/_sidebar.scss
This PR takes care of browser compatibility issues across firefox (latest), IE11, safari, opera and edge. Additionally IE10 is 99% working. There is a strange horizontal scrolling in the browse page sidebar that is caused by the browser ignoring a text-overflow. 
* Testing can be done locally and using our browserstack.com account. 
Connects #620
=> fixed majority of current known browser issues

app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/ColorCorrect.scala
If there is no difference between the `oldMax` and the `oldMin` values for `normalizeAndClamp`, normalization is meaningless (and throws for division by 0). This PR includes a small fix which should prevent such an error from being thrown while still 'clamping' values to the space defined by `newMax` and `newMin`.
=> Avoid division by 0 in color correction

app-backend/project/Dependencies.scala, app-backend/project/Version.scala
Akka-HTTP is now on its on release cycle. This PR upgrades the various akka-http packages and gives them a separately tracked version number. 
* Run tests
* Run the app-server and ensure the app works as expected
Connects #1075
=> Upgrade akka-http

app-backend/tile/src/main/scala/LayerCache.scala, app-backend/tile/src/main/scala/image/Mosaic.scala, app-backend/tile/src/main/scala/routes/MosaicRoutes.scala
This adds the ability to fetch tiles using a bounding box and zoom level instead of the standard z/x/y url params
Generated image (use own token / project id for this): 
http://localhost:9100/tiles/4ddd5d00-a378-4807-a41e-dcf9ae2a749a/10/-122.20779418945314,36.954281585675965,-120.12039184570312,37.97234987199528/?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL3Jhc3Rlci1mb3VuZHJ5LWRldi5hdXRoMC5jb20vIiwic3ViIjoiZ29vZ2xlLW9hdXRoMnwxMTY3NTM5NDM3OTkxOTgwMjc4NjkiLCJhdWQiOiI1NDRDejFWOHRxZXpNQ2J5TjhtTkptbHpPcGQ4SDRleCIsImV4cCI6MTQ4NzY2NjY0NCwiaWF0IjoxNDg3NjMwNjQ0fQ.WowFLseajeJUKUA0RmDTp5wt1xLFiwOxAg6s-Ci9mq4
For zoom levels higher than 10, the endpoint times …
=> Add ability for tiler to use bounding box instead of tile coordinate

scripts/cipublish
Merge conflict resolution error app => tile here
Minor change - merging to fix develop build
=> Fix typo in sbt clean command

docker-compose.test.yml
Fixes a typo in docker-compose.test.yml.
=> Fix docker-compose typo

docs/architecture/adr-0014-api-documentation-revisited.md
First pass at an ADR for how we should address API documentation
Closes #1142
=> ADR 0014 Revisiting api documentation

app-tasks/dags/ingest/ingest_project_scenes.py, app-tasks/dags/landsat8/import_landsat8_scenes.py, app-tasks/dags/sentinel2/find_sentinel2_scenes.py, app-tasks/rf/src/rf/ingest/landsat8_ingest.py, app-tasks/rf/src/rf/ingest/models/ingest.py
Remove default values for ingest env vars
This should be merged after https://github.com/azavea/raster-foundry-deployment/pull/32
* Verify that all variables in https://github.com/azavea/raster-foundry/issues/1172 no longer have defaults
Closes #1172
=> Remove default values for ingest env vars

app-backend/api/src/main/scala/token/Token.scala
This PR allows the deletion of API token (again) by ensuring the proper management token is 
* Create a token via the UI
* Delete the token
* Ensure that the token actually is removed and no errors are thrown
Connects #1163
=> Fix token deletion

app-backend/common/src/main/scala/Rollbar.scala
Send full stack trace to rollbar in the correct format, so it shows up someplace other than the occurrence 
See https://rollbar.com/Azavea/RasterFoundry/items/156/
Based on code from [rollbar-scala](https://github.com/storecove/rollbar-scala/blob/master/src/main/scala/com/storecove/rollbar/RollbarNotifierImpl.scala#L59-L128) 
* Throw an exception somewhere that will be caught by the user error handler EG:
```diff
modified   app-backend/api/src/main/scala/scene/Routes.scala
@@ -39,6 +39,7 @@ trait SceneRoutes extends Authentication
def listScenes: Route = authenticate { user =>
(withPagination & sceneQueryParameters) { …
```
=> Print full stack trace for rollbar

docs/architecture/adr-0015-refactor-testing.md
We need to figure out how to make our testing better, so that we can fully test our API instead of mostly testing our API. This PR adds a plan for how we can do that.
=> Add ADR on refactoring tests for convenience

docs/architecture/adr-0016-imports.md
This PR is to add an ADR for initially supporting uploads. This was written a while ago, but was never migrated from google docs, so I'm going to add it as is and we can write new ADRs if we need to revise our thinking here.
=> Add ADR for initial upload/import support

LICENSE
Updated year and copyright owning entity.
Fixes #402
=> Update license copyright

app-frontend/package.json, app-frontend/src/app/components/diagramContainer/diagramContainer.controller.js, app-frontend/src/app/components/diagramContainer/diagramContainer.html, app-frontend/src/app/components/diagramContainer/diagramContainer.scss, app-frontend/src/app/index.vendor.js, app-frontend/yarn.lock
This PR adds panning and zooming to the lab diagram UI.
~This is [WIP] in that I'm looking for some feedback on things that could be improved. The main issue I've noticed is the context menu behavior.~
* Make sure packages are updated (`yarn install`)
* Test panning and zooming
* Test that buttons for zoom and fit/center work
* Test that context menu is hidden on zoom
Connects #1197
=> Add panning and zooming to lab UI

app-frontend/.eslintrc, app-frontend/src/app/components/createProjectModal/createProjectModal.controller.js, app-frontend/src/app/components/publishModal/publishModal.controller.js, app-frontend/src/app/components/publishModal/publishModal.html, app-frontend/src/app/components/tokenItem/tokenItem.controller.js, app-frontend/src/app/components/tokenItem/tokenItem.html, app-frontend/src/app/core/services/project.service.js, app-frontend/src/app/core/services/token.service.js, app-frontend/src/app/pages/settings/settings.html, app-frontend/src/app/pages/settings/tokens/map/map.html, app-frontend/src/app/pages/settings/tokens/tokens.html
This simplifies the token UI a little to make it less onerous on users to share maps. This isn't the final version of the UI, but should make it easier to share.
* Go through the token UI/sharing and verify it works as expected
=> Update Map Token UI

app-frontend/src/app/components/tokenItem/tokenItem.controller.js, app-frontend/src/app/pages/settings/tokens/api/api.html
Fixes the API token component handling of deletion.
* Make sure you can now delete API tokens
Closes #1273
=> Fix deletion handling on api token component

README.md
Update bucket names to latest.
=> Update README: Fix Environment Variables

app-frontend/src/app/components/navBar/navBar.html, app-frontend/src/app/core/services/map.service.js, app-frontend/src/app/pages/home/home.html, app-frontend/src/app/pages/lab/lab.html, app-frontend/src/app/pages/settings/settings.html, app-frontend/src/assets/styles/sass/base/_grid.scss, app-frontend/src/assets/styles/sass/components/_dropdown.scss
This PR removes various parts of the UI which were not yet implemented. This includes:
- 'Find Places' and 'Basemap' in the map controls
- The 'Account' section of the settings area
- The 'help' and 'notifications' icons from the navbar
- The 'Build' link within the lab
This also adjusts the navbar styling a bit to compensate for the missing elements, which were keeping things vertically centered. With the elements missing, the username and main menu area were mis-aligned.
This also fixes the 'Manage API Tokens' link on the home page.
* Make sure the things I claim I removed are actually removed
* Make sure the …
=> Remove unused UI elements

app-frontend/src/app/components/callToActionItem/callToAction.scss, app-frontend/src/app/components/callToActionItem/callToActionItem.html, app-frontend/src/app/pages/home/home.html, app-frontend/src/assets/styles/sass/base/_base.scss, app-frontend/src/assets/styles/sass/base/_grid.scss, app-frontend/src/assets/styles/sass/base/_helpers.scss, app-frontend/src/assets/styles/sass/base/_list.scss, app-frontend/src/assets/styles/sass/components/_button.scss, app-frontend/src/assets/styles/sass/components/_panel.scss, app-frontend/src/assets/styles/sass/components/_spacing.scss, app-frontend/src/assets/styles/sass/layout/_container.scss, app-frontend/src/assets/styles/sass/utils/_variables.scss
Clean up the front end for the new home page dashboard.
Connects #1291
=> cleans up the new home page

app-frontend/src/app/core/services/auth.service.js, app-frontend/src/app/core/services/intercom.service.js, app-frontend/src/app/index.run.js
Add checks around intercom instantiation
Fix bad rollbar service eference
* Verify that there are no intercom errors when:
* Loading the app while not logged in
* Loading the app when logged in with an expired token
* Loading the app when logged in with a valid token
* Verify that there are no rollbar related errors when logging into the app
Closes #1369
=> Fix rollbar and Intercom instantiation errors

app-frontend/src/app/components/filterPane/filterPane.controller.js
Clear datasource filters when clicking the "Clear all filters" button
* In the browse view, filter by a datasource
* Verify that clicking "Clear all filters" clears the datasource filters as well
Closes #1349
=> Fix datasource filter clearing

app-frontend/src/app/components/filterPane/filterPane.controller.js
Remove unused var
Trivial, merging immediately
=> Fix unused import

app-frontend/package.json, app-frontend/src/app/core/services/auth.service.js, app-frontend/src/app/index.config.js, app-frontend/src/app/index.module.js, app-frontend/src/app/index.vendor.js, app-frontend/src/app/pages/error/error.controller.js
Fix error page not showing when config request fails
Remove angular-lock wrapper library
* Access the frontend without starting the api server
* Verify that all routes redirect to the error page
* Verify that the error page makes requests for the config url
* start the api server
* Verify that once the server responds with a non-error status on the config url, the page reloads (1)
(1) I can't test this, because soft reloading the app in dev mode on my machine 99% of the time causes angular not to initialize, and I can't figure out how to serve the files statically.
Closes #1159 
Closes #576
=> Fix config error page not showing

.github/PULL_REQUEST_TEMPLATE.md
This will close associated issues and move issues to the
done column
=> Add "closes" in PR template

app-frontend/src/app/components/importModal/importModal.controller.js
This fixes a typo in the init logic of the upload process that caused the datasource to not be available for the upload process.
* Go to the detail page of a datasource and go through the import process, there shouldn't be any console errors.
Closes #1465
=> Fix bug in datasource init for uploads

app-backend/build.sbt, app-backend/export/Dockerfile, app-backend/export/build.sbt, app-backend/export/src/main/resources/log4j.properties, app-backend/export/src/main/scala/com/azavea/rf/export/CommandLine.scala, app-backend/export/src/main/scala/com/azavea/rf/export/Export.scala, app-backend/export/src/main/scala/com/azavea/rf/export/SparkJob.scala, app-backend/export/src/main/scala/com/azavea/rf/export/model/ExportDefinition.scala, app-backend/export/src/main/scala/com/azavea/rf/export/model/ExportLayerDefinition.scala, app-backend/export/src/main/scala/com/azavea/rf/export/model/InputDefinition.scala, app-backend/export/src/main/scala/com/azavea/rf/export/model/OutputDefinition.scala, app-backend/export/src/main/scala/com/azavea/rf/export/model/Render.scala, app-backend/export/src/main/scala/com/azavea/rf/export/model/package.scala, app-backend/export/src/main/scala/com/azavea/rf/export/package.scala, app-backend/export/src/main/scala/com/azavea/rf/export/util/HadoopConfiguration.scala, app-backend/export/src/main/scala/com/azavea/rf/export/util/S3.scala, app-backend/export/src/main/scala/com/azavea/rf/export/util/Validation.scala, app-backend/export/src/main/scala/com/azavea/rf/export/util/package.scala, app-backend/export/src/test/resources/localJob.json, app-backend/export/src/test/resources/testFileJob.json, app-backend/export/src/test/resources/testJob.json, app-backend/export/src/test/scala/com/azavea/rf/export/model/ExportDefinitionSpec.scala, app-backend/project/Version.scala, docker-compose.spark.yml, docker-compose.test.yml, scripts/cipublish
Project export as GeoTiffs
```
docker-compose -f docker-compose.spark.yml run spark-driver \
--driver-memory 2G \
/opt/rf/jars/rf-export.jar -j file:///opt/rf/export-test-resources/testFileJob.json
```
* It's still in WIP, as not tested 100% (it's in process).
* Probably it makes sense to merge `export` and `ingest` projects into some `jobs` project, as there are lot's of duplications and similarities in these both projects.
* See Demo section
Connects #1338
Connects #1314
Connects #1333
Connects #1334
=> Project GeoTiff export

app-frontend/src/app/components/mapContainer/mapContainer.html, app-frontend/src/app/components/projectItem/projectItem.controller.js, app-frontend/src/app/components/projectItem/projectItem.html, app-frontend/src/app/components/sceneItem/sceneItem.component.js, app-frontend/src/app/components/sceneItem/sceneItem.html, app-frontend/src/app/components/staticMap/staticMap.component.js, app-frontend/src/app/components/staticMap/staticMap.controller.js, app-frontend/src/app/components/staticMap/staticMap.html, app-frontend/src/app/components/staticMap/staticMap.module.js, app-frontend/src/app/components/staticMap/staticMap.scss, app-frontend/src/app/core/services/map.service.js, app-frontend/src/app/core/services/mapUtils.service.js, app-frontend/src/app/core/services/token.service.js, app-frontend/src/app/index.components.js, app-frontend/src/app/pages/home/home.html, app-frontend/src/app/pages/imports/imports.html, app-frontend/src/app/pages/library/projects/detail/projectScenes/projectScenes.controller.js, app-frontend/src/app/pages/library/projects/detail/projectScenes/projectScenes.html, app-frontend/src/app/pages/library/projects/list/list.html, app-frontend/src/assets/styles/sass/_shame.scss, app-frontend/src/assets/styles/sass/layout/_container.scss, app-frontend/src/assets/styles/sass/pages/_library.scss
This PR updates the project item component and adds a static map component for simple creation of...static maps.
Edit: this also includes a new project detail page
We'll need to decide if the 'View' button should go to the details page or the editor.
* Make sure your ingested scene projects have nice previews.
* Make sure that any projects without scenes don't show a map
* Try each of the dropdown options and see that they work as expected.
Closes #1444
=> New project item component

app-frontend/src/app/components/projectItem/projectItem.html, app-frontend/src/app/pages/projects/detail/detail.controller.js, app-frontend/src/app/pages/projects/detail/detail.html
Fix Project detail page
Fix links going to project scenes instead of browse when linking "Add Scenes"
* Verify that the detail page is formatted correctly
Closes #1510
=> Fix project detail page

docs/swagger/spec.yml
Add swagger spec vendor extensions & some brief copy
* Verify that the spec is valid
* Pull https://github.com/azavea/raster-foundry-docs/tree/feature/lk/update-spec and run the docsite (it has the same spec)
* Verify that all endpoints show up in the generated page. Note that body parameters are not yet implemented, so will not properly show up.
Closes #1433
=> Add swagger vendor extensions

app-backend/api/src/main/scala/Router.scala, app-backend/api/src/main/scala/aoi/Routes.scala, app-backend/api/src/main/scala/project/Routes.scala, app-backend/api/src/main/scala/utils/QueryParameters.scala, app-backend/api/src/test/scala/aoi/AoiSpec.scala, app-backend/database/src/main/scala/com/azavea/rf/database/QueryParameters.scala, app-backend/database/src/main/scala/com/azavea/rf/database/tables/AOIs.scala, app-backend/database/src/main/scala/com/azavea/rf/database/tables/AoisToProjects.scala, app-backend/database/src/main/scala/com/azavea/rf/database/tables/Projects.scala, app-backend/database/src/main/scala/com/azavea/rf/database/tables/ScenesToProjects.scala, app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/AOI.scala, docs/swagger/spec.yml
This updates the Swagger spec and implements Akka HTTP endpoints for the Area of Interest feature.
* How to test this PR
* Prefer bulleted description
* Start after checking out this branch
* Include any setup required, such as bundling scripts, restarting services, etc.
* Include test case, and expected output
~~This builds off PR #1395 , which should be merged before this.~~ Done.
Connects #1335 #1381
=> AOI Swagger and Endpoints

app-frontend/src/app/components/projectItem/projectItem.controller.js, app-frontend/src/app/pages/projects/edit/colormode/colormode.html, app-frontend/src/app/pages/projects/edit/edit.html, app-frontend/src/app/pages/projects/list/list.html
This PR goes through and removes some unimplemented feature prompts.
- Removes the custom color composite controls
- Removes the project search bar
- Removes the scene ordering and masking buttons from the project editor
This also fixes the scene-item component to properly handle deletion.
* See that the things I said I removed are actually removed
* See that deleting a project from the project list actually works now
Closes #1547 
Closes #1524
Closes #1522 
Closes #1532 
Closes #1533
=> Remove unused items and fix project deletion

app-backend/tool/src/main/scala/ast/ClassBreaks.scala, app-backend/tool/src/main/scala/ast/MapAlgebraAST.scala, app-backend/tool/src/main/scala/ast/RFMLRaster.scala, app-backend/tool/src/main/scala/ast/codec/MapAlgebraOperationCodecs.scala, app-backend/tool/src/main/scala/ast/package.scala, app-backend/tool/src/main/scala/eval/Interpreter.scala, app-backend/tool/src/main/scala/eval/InterpreterError.scala, app-backend/tool/src/main/scala/eval/LazyTile.scala
Casual commits made during a code dive.
=> [AST] Code dive

app-backend/api/src/main/scala/tools/Routes.scala, app-backend/build.sbt, app-backend/tile/src/main/scala/routes/ToolRoutes.scala, app-backend/tile/src/main/scala/tool/TileSources.scala, app-backend/tool/src/main/scala/ast/MapAlgebraAST.scala
All main files and tests for all subprojects now compile when you run `compile` from the root project.
=> Root project should build all subprojects

app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/Scene.scala
This PR changes how we construct `Scene.WithRelated` objects from database records. Instead of grouping the records by distinct scenes, it groups the records by distinct scene IDs and makes other necessary changes to accomodate this.
This doesn't fix the underlying cause of the problem, which is that somehow, after doing the whole
`Scenes.filter(...).joinWithRelated` thing for scenes created by the scala Landsat 8 importer, the `Scene` case class in each returned record isn't the same in some way, which makes basically no sense. I talked to @pomadchin and we're going to figure out why (logged as #1672).
* Run the landsat 8 …
=> Group by IDs to construct Scene.WithRelateds instead of by scenes

scripts/bootstrap, scripts/deploy-docs
Remove reference from setup script and references to the app-clients spec. Instead, use the spec inside of docs/swagger.
N/A
=> Remove remaining references to app-clients

app-backend/batch/src/main/scala/com/azavea/rf/batch/ingest/spark/Ingest.scala, app-backend/database/src/main/scala/com/azavea/rf/database/tables/Datasources.scala, app-frontend/src/app/core/services/project.service.js, app-frontend/src/app/pages/projects/edit/edit.controller.js, app-frontend/src/app/pages/projects/edit/edit.html, app-tasks/dags/export/find_exports.py, app-tasks/dags/ingest/ingest_project_scenes.py, app-tasks/rf/src/rf/ingest/geotiff_ingest.py
Fixes three bugs:
- public datasource filtering
- setting export status incorrectly
- requesting too many export jobs
* Start server and log in with a non-root account in a non-default org
* Go to filter and look for datasources
* Try to export a project - ensure it gets picked up correctly in the airflow ui
=> Few Small Bugfixes

app-frontend/src/app/components/createProjectModal/createProjectModal.controller.js, app-frontend/src/app/components/createProjectModal/createProjectModal.html, app-frontend/src/app/components/filterPane/filterPane.controller.js, app-frontend/src/app/pages/home/home.html, app-frontend/src/app/pages/projects/edit/browse/browse.controller.js, app-frontend/src/app/pages/projects/edit/browse/browse.html, app-frontend/src/app/pages/projects/edit/scenes/scenes.controller.js, app-frontend/src/app/pages/projects/edit/scenes/scenes.html
This PR addresses several UI issues:
- *Project create process redirected users to the wrong route when choosing to add public imagery*. This was fixed by redirecting the user to the add/remove scenes route.
- *Thumbnails of scenes that were previewed were removed (even if selected)*. Thumbnails for selected scenes are now persisted when previewing the scene.   
- *When a user exited browse mode, selected scenes that were no longer in view (scrolled away for example) would be stuck on the map*. This was fixed by removing all _selected_ scenes rather than all _visible_ scenes in our cleanup method. This one is complex to reproduce:
- open a project in the editor
- browse for imagery to add
- select a few scenes
- immediately exit the browse mode (use the '< Scenes' button)
- the thumbnails …
=> Frontend fixes

app-tasks/Dockerfile
=> Copy plugins into airflow webserver when building

app-frontend/src/app/core/services/layer.service.js, app-tasks/dags/ingest_project_scenes.py, app-tasks/rf/src/rf/ingest/geotiff_ingest.py
- Fix setting ingest status by removing comments
- Bump max zoom level for leaflet so we can view high res imagery
- Bump allowed ingest resolution to 2 cm
* Start up servers and airflow
* Run ingest on some sample imagery
* Verify it works
Closes #1711
=> Fix Ingest Status Update

app-backend/api/src/main/resources/application.conf, app-backend/build.sbt, app-backend/project/Dependencies.scala, app-backend/project/Version.scala
Adds dropbox dependency and updates development `.env` to add key/secret
* Pull down latest `.env` file with `./scripts/bootstrap`
* Open an SBT console with `./scripts/console api-server ./sbt` and get a shell in the `api` app
* Try to import the dropbox dependency `import com.dropbox.core.v2.DbxClientV2`
Closes #1647
=> Add Dropbox Setup

app-backend/tile/src/main/scala/image/Mosaic.scala, app-backend/tile/src/main/scala/routes/MosaicRoutes.scala
The tile export is meant for requesting small areas at reasonable zoom
levels. Previously it was possible to request a PNG for these areas,
but it was not possible to request a geotiff with original values for
an area. This commit adds the ability to request PNGs and geotiffs,
with or without color correction.
Sample png from requests described in testing
Sample tif generated from requests described in testing
Setting `colorCorrect` to false for `image/png` will cause an error since the range of values will exceed what can be rendered for a PNG. I'm not sure what the best option here is. I can think of two things:
1. …
=> Add tiff as option for tile export

app-frontend/src/app/pages/projects/edit/edit.html, app-frontend/src/assets/styles/sass/components/_tags.scss
Quick fix to aoi project tag
* How to test this PR
* Prefer bulleted description
* Start after checking out this branch
* Include any setup required, such as bundling scripts, restarting services, etc.
* Include test case, and expected output
Closes #XXX
=> fixes styling for aoi tag

app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/ColorCorrect.scala
This PR refactors the RGB channel clipping, so that it clips based on actual min/max of a given layer, and also so that user-specified color corrections are applied after other transformations.
"Natural" color mode, staging (i.e. no initial clipping):
"Natural" color mode, no user-specified corrections:
With `greenMax:150` and `blueMin:50`:
With `redMax:100`, `greenMax:150`:
"Urban" color mode, with `greenMax:150` and `blueMax:150`:
* bounce the server and open a project with the app
* sample a handful of color modes to ensure that tiles render, compare them to staging to ensure that the colors are clipped …
=> Refactor RGB clipping

docs/swagger/spec.yml
This is the same as #1758, but with the correct changes. Somehow the commit in #1758 was just @alkamin 's changes to add pending.
* Compare to https://github.com/azavea/raster-foundry-python-client/pull/4/commits/0c2071c7f52c0a47fb2ed53a0b87018c95046b69
=> Apply spec diff from azavea/raster-foundry-python-client#4

docs/swagger/spec.yml
Almost all of this was done by @jmorrison1847, I made sure it worked and made a few slight changes. 
Updates some copy on the swagger specification to make it more consistent and clear.
For some reason using `#/definitions/Upload` for the `PUT` spec for uploads caused the docs site to stop rendering, I'm not sure why.
* Copy swagger spec to `assets/swagger.yml` in the docs repository and start server, inspect that things work
Closes #1678
=> Update swagger Spec Copy

app-frontend/src/app/pages/projects/edit/advancedcolor/adjust/adjust.html
Delay updating on text input until enter is pressed or the field loses focus
* Verify that the corrections are not updated until enter is pressed or the field loses focus
* Verify that the up and down arrows still work, as to pressing the up and down arrow keys 
Closes #1802
=> Update color corrections on field blur, make debounce longer

app-backend/api/src/test/scala/datasource/DatasourceSpec.scala, app-backend/api/src/test/scala/project/ProjectSceneSpec.scala, app-backend/batch/src/test/resources/export/localJob.json, app-backend/batch/src/test/resources/export/testFileJob.json, app-backend/batch/src/test/resources/export/testJob.json, app-backend/batch/src/test/scala/com/azavea/rf/batch/export/model/ExportDefinitionSpec.scala, app-backend/database/src/main/scala/com/azavea/rf/database/tables/Projects.scala, app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/ColorCorrect.scala, app-backend/tile/src/main/scala/image/Mosaic.scala, app-backend/tile/src/main/scala/package.scala, docs/swagger/spec.yml
This PR implements the auto white-balance technique detailed [here](https://web.stanford.edu/%7Esujason/ColorBalancing/robustawb.html).
This implementation appears to be in working order for the most part. There are some color correction combinations that result in strange images if balanced, as shown in the third pair of demo images below. Since the auto-balancing is applied early in the sequence of operations, after equalization and normalization, it seems likely that the source of error is a certain set of operations.
The manner in which the bug appears, with specific rows of an image being colored incorrectly, leads me to think that certain pixels or …
=> Implement Robust Auto White-Balance

app-frontend/src/app/pages/projects/edit/advancedcolor/adjust/adjust.html
=> Fix Alex's merge conflict

app-backend/tile/src/main/scala/image/Mosaic.scala
Lots of `java.lang.UnsupportedOperationException: empty.reduceLeft` errors are being thrown from within `Mosaic.scala`. `reduce` assumes a non-empty list because the zero-case isn't provided (as it is, say, in `reduceLeft`.
This PR guards against that issue. I've also taken the opportunity to DRY out/clean up some of the code within `Mosaic.scala`.
Closes #1817
=> Avoid reducing over empty list

app-backend/batch/src/main/resources/application.conf, app-backend/batch/src/main/scala/com/azavea/rf/batch/Main.scala, app-backend/batch/src/main/scala/com/azavea/rf/batch/dropbox/Implicits.scala, app-backend/batch/src/main/scala/com/azavea/rf/batch/dropbox/package.scala, app-backend/batch/src/main/scala/com/azavea/rf/batch/export/airflow/DropboxCopy.scala, app-backend/batch/src/main/scala/com/azavea/rf/batch/export/spark/Export.scala, app-backend/batch/src/main/scala/com/azavea/rf/batch/util/conf/Config.scala, app-backend/batch/src/test/scala/com/azavea/rf/batch/export/model/ExportDefinitionSpec.scala, app-backend/database/src/main/scala/com/azavea/rf/database/tables/Exports.scala, app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/OutputDefinition.scala, docs/swagger/spec.yml
This PR introduces S3 to copy jobs and direct export into Dropbox folder
```
java -cp rf-batch.jar com.azavea.rf.batch.Main dropbox-copy s3://bucket/prefix/ /test token
java -cp rf-batch.jar com.azavea.rf.batch.Main dropbox-copy s3://bucket/prefix/ dropbox:///test token
```
Or do a usual export, with dropboxCredentials setup and with export path URI: ```dropbox:/some/path/```
It's discussable how to modify export job: 
- Modify export definition to accept credentials (current version)
- To pass AccessToken as a sep batch job parameter
Closes #1649
Depends on #1799
=> Dropbox export

app-tasks/dags/ingest_project_scenes.py
Closes #1848, pretty minor - going to merge
=> Fix method call to get ingest status

app-tasks/dags/ingest_project_scenes.py
Fixes a typo in the logger that prevents successful airflow tasks
=> Fix typo in logger (infoi => info)

app-backend/api/src/main/scala/exports/Routes.scala
This PR updates the `api/exports` endpoint so that `POST`ed `exportOptions` are successfully decoded into an `ExportOptions` instance before written to the database.
As part of this, I also checked several other parts of the codebase to determine if the problem described in #1588 appeared likely. I didn't find any standout cases that mirrored the specific problem; `ColorCorrect.Params`, `AOI` filters, and `Tool` definitions all had validation elsewhere in the service layer that would have made any check in `api` unnecessary.
* `POST` to `api/exports/` with a bogus `exportOptions` value, e.g. 
``` …
```
=> Check JSON parameters before writing them to DB

app-backend/database/src/main/scala/com/azavea/rf/database/tables/Projects.scala, app-tasks/dags/ingest_project_scenes.py
Closes #1861
* Start all the servers + airflow
* Upload a small tif
* Verify it loads once ingested
Closes #1861
=> Update ingest location when updating scenes

app-backend/batch/src/main/resources/application.conf, app-backend/batch/src/main/scala/com/azavea/rf/batch/landsat8/airflow/ImportLandsat8.scala, app-backend/batch/src/main/scala/com/azavea/rf/batch/landsat8/airflow/ImportLandsat8C1.scala, app-backend/batch/src/main/scala/com/azavea/rf/batch/sentinel2/airflow/ImportSentinel2.scala, app-backend/batch/src/test/scala/com/azavea/rf/batch/sentinel2/TileInfoSpec.scala
- Fixes Sentinel2 geometry target projections and urls.
- Improves Landsat8 import.
=> Sentinel2 & Landsat8 minor fixes

app-backend/batch/src/main/scala/com/azavea/rf/batch/landsat8/airflow/ImportLandsat8.scala, app-backend/batch/src/main/scala/com/azavea/rf/batch/landsat8/airflow/ImportLandsat8C1.scala
=> Fix Landsat8 thumbnail paths again

app-backend/batch/src/main/resources/application.conf, app-backend/batch/src/main/scala/com/azavea/rf/batch/export/airflow/CreateExportDef.scala, app-backend/batch/src/main/scala/com/azavea/rf/batch/util/S3.scala
A couple of export fixes.
- Adds better error logging
- Default AWS region is taken from env
- Updated rf-batch name (probably is not necessary)
=> Export jobs improvements

docs/dev/database.md
Document what's in the dev database
=> Add documentation for dev database

docs/swagger/spec.yml
=> Link AoI endpoint to Project

app-backend/batch/src/main/scala/com/azavea/rf/batch/ast/package.scala
This adds two new cases, enabling the use of min and max in AST Exports.
=> Add Min/Max support in RDD AST exports

app-frontend/src/app/core/services/auth.service.js
- Checks for user token expiration on initial page load and presents a login window if the token has expired.
- On initial login, sets a timeout for a function to present the user with a login window 5 minutes before their session is expected to expire.
This doesn't address all of the issues raised in #1775 and #1370 ; specifically, the user will still get redirected to the home-page after re-authenticating, and it will not automatically acquire refresh tokens if the user is actively using the app. I'm going to open a new issue to deal specifically with login redirection once this is merged.
* Log into the web app and open up the web inspector so you can see and edit local storage.
* Grab `id_token` from local storage and put it into the [jwt.io](https://jwt.io) debugger so you can edit …
=> User session improvements

app-tasks/rf/src/rf/uploads/geotiff/create_footprints.py
Fleshes out work by @jisantuc to get the `process_upload` task to correctly handle tiffs that have no CRS defined.
There are still problems with some tiffs due to #1930 , but this gets many more tiffs working correctly.
* Bring up `./scripts/server --with-airflow`
* Upload a tiff that doesn't have a CRS defined (let me know if you need an example)
* Confirm that `process_upload` completes successfully.
* For most tiffs, `ingest_scene` should also complete.
=> Tolerate missing EPSG code

app-frontend/src/app/components/scenes/sceneImportModal/sceneImportModal.component.js
Fix it
* bring up import modal
=> Fix import modal

app-tasks/dags/aoi-monitoring/find_aoi_projects_to_update.py, app-tasks/dags/aoi-monitoring/update_aoi_projects.py
* bounce the API server (with airflow): `./scripts/server --with-airflow`
* create and AOI project
* `POST` AOI parameters to `api/projects/[id]/areas-of-interest/`
* in the database, `update projects set aois_last_checked='2016-01-01' where is_aoi_project=TRUE` to force an AOI update; alternatively, upload new scenes
* check that airflow picks up the task and runs it
* check that some set of scenes is added to the project in DB and/or the UI 
Connects #1875
=> Airflow AOI task revisions

app-frontend/src/app/pages/home/home.html
Update working links to homepage.
The help links linking to the raster foundry help site might need to be updated at some point if Radiant wants their own doc.
* Go to the homepage
* Test the following links: 
* `Getting started with Projects`
* `Getting started with Tools`
* `Intro to the API`
* `Raster Foundry guide`
* `Raster Foundry API Documentation`
Closes #1718
=> Update working links to homepage

app-backend/tile/src/main/scala/routes/MosaicRoutes.scala, app-backend/tile/src/main/scala/routes/SceneRoutes.scala
This adds basic logging on tile server routes that had lacked any.
The description in the original issue wasn't specific in the sense that there were no concrete examples of `500` status requests that should have been logged in some capacity. As a start, adding logging at the endpoints seemed the easiest route with the biggest "payoff" such that there would be fewer silent failures or mysterious `500` responses, but by the same token there may be omissions. If there are specific workflows or whatever that come to mind, that would be helpful to determine whether exceptions are being logged.
* bounce the tile …
=> Add logging to tile server routes

app-backend/database/src/main/scala/com/azavea/rf/database/tables/AOIs.scala, app-backend/database/src/main/scala/com/azavea/rf/database/tables/Projects.scala
This PR fixes a couple bugs found while testing the AOI workflow; it also fixes an AOI-related bug that prevents projects with existing AOIs from being deleted.
I noticed that after deleting an AOI after it has been processed by the Airflow task (i.e. after scenes had been added to a project per the AOI parameters), the scenes were still attached to the project. This didn't seem particularly worrisome, but rather something worth noting in case users notice or the AOI workflow needs to be changed in future.
* bounce the API server, and then ensure that there is at least one non-AOI project and one AOI project …
=> AOI Database & Endpoint fixes

app-backend/batch/src/main/scala/com/azavea/rf/batch/export/airflow/CreateExportDef.scala
=> Use EitherT instead of OptionT to catch Airflow errors

app-frontend/src/app/core/services/auth.service.js, app-frontend/src/app/core/services/project.service.js, app-frontend/src/app/core/services/tool.service.js, app-frontend/src/app/core/services/user.service.js, app-frontend/src/app/pages/settings/connections/connections.controller.js
Add user organization to heap user properties
Add "Logged In" heap event property on login
* Delete the if statement in `tpl-index.html` wrapping the heap js import (restart webpack to see changes)
* Log into your user and do some stuff
* Log into heap and verify that the new properties are visible on the user and events
Closes #1721
=> Add heap properties to user log-in

app-backend/api/src/main/scala/exports/Routes.scala, app-backend/api/src/main/scala/exports/package.scala, app-backend/api/src/test/scala/exports/ExportSpecHelper.scala, app-backend/build.sbt, app-backend/common/src/main/scala/S3.scala, app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/ExportOptions.scala, app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/User.scala, app-backend/project/Dependencies.scala
This PR adds creation default S3 export path for users, in case it wasn't passed during export creation
This PR is a cherry picked https://github.com/azavea/raster-foundry/pull/1976/commits/23511aa7a7e9d73caf69686d8d0cfdbe9bc4ebe0
Closes #1977
=> Add default exports output location during creation

app-backend/batch/src/main/resources/application.conf, app-backend/batch/src/main/scala/com/azavea/rf/batch/Main.scala, app-backend/batch/src/main/scala/com/azavea/rf/batch/export/CommandLine.scala, app-backend/batch/src/main/scala/com/azavea/rf/batch/export/airflow/CheckExportStatus.scala, app-backend/batch/src/main/scala/com/azavea/rf/batch/export/airflow/CreateExportDef.scala, app-backend/batch/src/main/scala/com/azavea/rf/batch/export/json/S3ExportStatus.scala, app-backend/batch/src/main/scala/com/azavea/rf/batch/export/spark/Export.scala, app-backend/batch/src/main/scala/com/azavea/rf/batch/ingest/json/S3IngestStatus.scala, app-backend/batch/src/main/scala/com/azavea/rf/batch/ingest/spark/Ingest.scala, app-backend/batch/src/main/scala/com/azavea/rf/batch/package.scala, app-tasks/dags/aoi-monitoring/find_aoi_projects_to_update.py, app-tasks/dags/export_project.py
PR introduces S3 usage for Export statuses, improvement logging (thx to @fosskers additions).
**create_export_definition:**
**wait_for_status:**
* Run export job (for example create new export through UI)
Closes #1966 
Closes #1964
=> Use S3 to track export status jobs 

app-frontend/src/app/components/scenes/sceneImportModal/sceneImportModal.controller.js, app-frontend/src/app/core/services/datasource.service.js
Fix datasource creation
* Create a datasource from the frontend
Closes #2004
=> Replace userService with authservice in datasourceService

app-backend/batch/src/main/resources/application.conf, app-backend/batch/src/main/scala/com/azavea/rf/batch/export/spark/Export.scala, app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/ExportOptions.scala, app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/OutputDefinition.scala, app-tasks/dags/export_project.py
Fixes Airflow export DAG exit codes
Related to https://github.com/azavea/raster-foundry/issues/1964
=> Fix airflow export exit codes

app-backend/batch/src/main/scala/com/azavea/rf/batch/ingest/spark/Ingest.scala, app-tasks/dags/ingest_project_scenes.py
Fixed validation logic, updated jar name.
Closes #2021
=> Ingests Fix

app-backend/batch/src/main/scala/com/azavea/rf/batch/landsat8/airflow/ImportLandsat8.scala
Fixes base url usage during the old style landsat import
=> Thumbnail base url typo fix

app-frontend/src/app/components/projects/projectItem/projectItem.controller.js, app-frontend/src/app/components/projects/projectItem/projectItem.html, app-frontend/src/app/components/scenes/sceneItem/sceneItem.html, app-frontend/src/app/pages/projects/list/list.html, app-frontend/src/assets/images/transparent.svg, app-frontend/src/assets/styles/sass/_shame.scss, app-frontend/src/assets/styles/sass/base/_grid.scss, app-frontend/src/assets/styles/sass/base/_typography.scss, app-frontend/src/assets/styles/sass/components/_list-group.scss, app-frontend/src/assets/styles/sass/components/_tags.scss, app-frontend/src/assets/styles/sass/pages/_dashboard.scss
- makes the roject page a two column layout.
- updates the scene status css a bit
- adds better thumbnail placeholder
* go to project list
* make a projct with a lonnngggg title.
* refresh and hover over title name with long title
* make sure thumbnail logic works
=> updates the project page layout

app-frontend/src/assets/styles/sass/_shame.scss
Trivial. Will merge right away.
=> Fix bad css merge

app-frontend/src/app/components/common/navBar/navBar.html
Clicking on the logo will take you to the home page - similar to clicking on the "Home" tab.
* On any page, click the top left logo.
* It will take you to the home page - same as clicking the "Home" tab.
Closes #2052
=> Link logo to home page

app-frontend/src/app/components/scenes/sceneImportModal/sceneImportModal.controller.js
Prevent user from closing modal / window accidentally during upload process
* Try to close the window during a window
* Try to go to a different url while uploading
* Try going back in browser history
* Try closing the modal in any way 
Closes #2079
=> Prompt before closing window while in upload

app-frontend/src/app/pages/projects/navbar/navbar.html
see title
* Throttle your connection in the network tab of chrome dev tools
* Go to the project edit view, and observe that the dropdown button isn't visible until the project loads
Closes #1953
=> Hide project navbar while project is loading

app-backend/common/src/main/scala/ast/package.scala, app-backend/database/src/main/scala/com/azavea/rf/database/tables/Exports.scala, app-backend/tile/src/main/scala/LayerCache.scala, app-backend/tool/src/main/scala/ast/package.scala
Tool references weren't implemented for Exports. This PR adds the necessary logic.
The logic here is used across multiple projects within RF and, therefore, complicates matters a bit. The `database` project is depended on by almost everything (even `common`) and as a result can be hard to share logic with - to work around this, I leaned pretty heavily on closures to prevent projects from having to make sense of types they can't understand.
=> Add tool refs within exports

app-backend/batch/src/main/scala/com/azavea/rf/batch/ingest/model/package.scala, app-backend/common/src/main/resources/reference.conf, app-backend/common/src/main/scala/Config.scala, app-backend/common/src/main/scala/cache/HeapBackedMemcachedClient.scala, app-backend/tile/src/main/resources/application.conf, app-backend/tile/src/main/scala/Config.scala, app-backend/tile/src/main/scala/KamonTrace.scala, app-backend/tile/src/main/scala/KamonTraceDirectives.scala, app-backend/tile/src/main/scala/LayerCache.scala, app-backend/tile/src/main/scala/StitchLayer.scala, app-backend/tile/src/main/scala/image/GlobalSummary.scala, app-backend/tile/src/main/scala/image/Mosaic.scala, app-backend/tile/src/main/scala/package.scala, app-backend/tile/src/main/scala/routes/MosaicRoutes.scala, app-backend/tile/src/main/scala/routes/SceneRoutes.scala, app-backend/tile/src/main/scala/routes/ToolRoutes.scala
This PR:
- Adds cache enable / disable flags (one for in memory caching, second for memcached)
- Added trace segments support
- Added counters for all trace and trace segments calls to count method calls
- Introduces two env vars: `MEMCACHED_ENABLED` (false by default), `TILESERVER_CACHE_ENABLED` (true by default)
=> Improved metrics and caching

app-backend/common/src/main/resources/reference.conf, app-backend/common/src/main/scala/Config.scala, app-backend/common/src/main/scala/cache/HeapBackedMemcachedClient.scala
Adds an additional env var:
* `MEMCACHED_HEAP_ENABLED` (false by default) // memcached client heap
=> Flag to disable memcached heap

app-backend/tile/src/main/scala/directives/TileAuthentication.scala
The ordering of directives is to be most efficient, but thinking through this takes some time. This additional comment aims to provide the necessary train of thought for understanding how it is the most efficient combination.
=> Explain directive combination ordering

app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/ColorCorrect.scala
Current ColorCorrection ignores enabled / disabled flag, this PR fixes it.
=> Fix sigmoidal contrast correction application

app-frontend/src/app/components/projects/projectItem/projectItem.controller.js
=> Fix undefined $log

app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/package.scala, app-frontend/src/app/components/aoiFilterPane/aoiFilterPane.component.js, app-frontend/src/app/components/aoiFilterPane/aoiFilterPane.controller.js, app-frontend/src/app/components/aoiFilterPane/aoiFilterPane.html, app-frontend/src/app/pages/projects/edit/aoi-parameters/aoi-parameters.controller.js, app-frontend/src/app/pages/projects/edit/aoi-parameters/aoi-parameters.html, app-frontend/src/assets/styles/sass/_shame.scss
Fix AOI creation
To compile batch/assembly, you may need to take the dockerfile changes from https://github.com/azavea/raster-foundry/pull/2308 and rebuild your airflow worker
* Set up a new AOI project
* Create an AOI shape, and set some filters.
* Verify that clicking "Start AOI Monitoring" sends the correct payloads: 2 requests, one to project, one to create AOI with filters and area.
* Verify that you can change the shape and filters, and the changes persist
* Verify that force checking the AOI functions without errors, as described in the issue: https://github.com/azavea/raster-foundry-clients/issues/64
* Verify …
=> Fix AOI Updates

app-frontend/config/webpack/global.js
Re-enables aerial basemaps
* Start server, switch to aerial maps
Closes #2357
=> Re-enable aerial basemaps

app-frontend/src/app/index.routes.js, app-frontend/src/app/index.run.js
* Verify that you can see the route identifiers in your browser history / tab title
Closes #2406
=> Add page titles for routes to make navigation easier

app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/ColorCorrect.scala
Fix broken color corrections where gammas get set to 0 and applied even when disabled
It appears that I broke the link between overall min/max and the individual colors when updating the histogram, so changing the rgb min/max doesn't do anything. Individual colors still work. I'll fix it in my next histogram pr
* Verify that changing clipping values does not cause color corrections to always return a blank tile if gamma correction is disabled.
Closes #2416
=> Correctly handle disabled gamma and saturation options in API

app-backend/api/src/main/scala/Router.scala
This is to support skinned apps making PUT, POST, OPTIONS,
and DELETE requests
* Copy `overrides.js.template` to `overrides.js` and set the API host to `localhost:9100` which is nginx
* Start all servers
* Try to make `DELETE` and other requests
=> Update CORS to allow requests from other domains

README.md, Vagrantfile, scripts/load_development_data, scripts/rsync-back, scripts/setup, scripts/update
Use the `rsync` shared folder type to speed up development within the VM.
- Update `Vagrantfile` to use rsync shared folders
- Add a script that extracts generated files from the VM using `rsync`
- Rename `scripts/setup` to `scripts/update`
- `scripts/setup` installs `vagrant-gatling-rsync` prior to provisioning the VM
N/a
- See [#1577](https://github.com/raster-foundry/raster-foundry/issues/1577#issuecomment-321841637) for an explanation of why I decided to use `vagrant-gatling-rsync` instead of `vagrant-rsync-auto`
- The issue also discusses using `vagrant-rsync-back` to extract generated files _from_ the VM _into_ the host. One issue with using `vagrant-rsync-back` is that it respects the same `rsync__excludes` as the shared folder, so any files in an excluded folder are inaccessible …
=> [WIP] Use Rsync shared folders

app-frontend/src/app/components/scenes/sceneFilterPane/sceneFilterPane.controller.js
Fix undefined datasource js error in filter pane
* Verify that the described issue no longer occurs
Closes #2431
=> Fix undefined datasource js error in filter pane

app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/package.scala, app-backend/tile/src/main/scala/LayerCache.scala, app-backend/tile/src/main/scala/image/package.scala, app-backend/tile/src/main/scala/routes/MosaicRoutes.scala, app-backend/tile/src/main/scala/routes/ToolRoutes.scala, app-backend/tile/src/test/scala/RenderDefinitionSpec.scala, app-backend/tool/src/main/scala/RenderDefinition.scala, app-backend/tool/src/main/scala/ast/NodeMetadata.scala, app-backend/tool/src/main/scala/package.scala, docs/swagger/spec.yml
This PR provides support for truly continuous rendering of tile values in accordance with the new UI.
No clipping, left clipping, right clipping and clipping both sides of a continuous rendering definition
=> Support new rendering definition on the backend

app-frontend/src/app/components/tools/classifyNode/classifyNode.component.js, app-frontend/src/app/components/tools/classifyNode/classifyNode.controller.js, app-frontend/src/app/components/tools/classifyNode/classifyNode.html, app-frontend/src/app/components/tools/classifyNode/classifyNode.module.js, app-frontend/src/app/components/tools/diagramContainer/diagramContainer.controller.js, app-frontend/src/app/components/tools/diagramNodeHeader/diagramNodeHeader.controller.js, app-frontend/src/app/components/tools/diagramNodeHeader/diagramNodeHeader.html, app-frontend/src/app/index.components.js, app-frontend/src/app/services/services.module.js, app-frontend/src/app/services/tools/labUtils.service.js, app-frontend/src/app/services/tools/reclassify.service.js, app-frontend/src/app/services/vendor/rollbarWrapper.service.js, app-frontend/src/assets/styles/sass/_shame.scss
This PR adds a classify node to the lab interface
- This is based on a previous PR, once that is merged I'll rebase
- The button is not hooked up
* Open/create a tool with a classify node in it
* Make sure the displayed classes are what you would expect
Closes #2445
Closes #2309
=> Implement `classify` node in lab UI

app-backend/common/src/main/scala/Rollbar.scala
When an exception is thrown inside of the exception handling block of a batch job, the exception is raised, but the Akka system is never terminated. This leads to batch processes that hang indefinitely.
/cc @pomadchin 
From within the Vagrant virtual machine, and after building the batch JAR with `sbt batch/assembly`:
```bash
vagrant@vagrant-ubuntu-trusty-64:/opt/raster-foundry$ ./scripts/console airflow-worker /bin/bash
airflow@3c3e93e8323a:/usr/local/airflow$ java -cp /opt/raster-foundry/jars/rf-batch.jar com.azavea.rf.batch.Main import_landsat8 1985-03-31
```
This should lead to an exception, but terminate properly. Without the changes introduced here, it hangs indefinitely.
Closes https://github.com/azavea/raster-foundry-platform/issues/107
=> Fix batch job exception handling

app-frontend/src/app/components/scenes/sceneItem/sceneItem.controller.js, app-frontend/src/app/components/scenes/sceneItem/sceneItem.html, app-frontend/src/app/pages/home/home.controller.js, app-frontend/src/app/pages/home/home.html
Use acquisitionDate instead of createdAt if available on scene
* Verify that scenes are listed by acquisition date if it's available
* Verify that the create tool button on the home page works
* Verify that all existing links on the home page work 
Closes #1893
=> Use acquisitionDate instead of createdAt if available on scene

app-backend/database/src/main/scala/com/azavea/rf/database/tables/Uploads.scala
Makes the Uploads API act the same way as the Scenes API, which is that it filters only to items owned by the requesting user. Previously, it filtered to 
(I didn't actually have to update the Swagger spec because it claimed that this was how the endpoint already worked: "All user uploads are private to that user." :eyes: )
* Check out develop
* Log in to your local development machine with an account you don't normally use (probably a Google account). Grab your token and use it to make a GET request to `http://localhost:9091/api/uploads`. You should see a bunch of uploads.
* Check out this branch, relaunch `/scripts/server`, and hit the same endpoint again.
* You should see fewer / no uploads
Closes https://github.com/azavea/raster-foundry-platform/issues/132
=> Limit Uploads API responses to the requesting user

docs/architecture/adr-0006-workflow-manager.md, docs/architecture/adr-0019-workflow-manager.md
See the contents of ADR-0019 for details.
N/A
Closes https://github.com/azavea/raster-foundry-platform/issues/103
=> ADR-00019: Replace Airflow with AWS Batch

app-frontend/src/app/components/histogram/histogramBreakpoint/histogramBreakpoint.html, app-frontend/src/app/components/histogram/nodeHistogram/nodeHistogram.component.js, app-frontend/src/app/components/histogram/nodeHistogram/nodeHistogram.controller.js, app-frontend/src/app/components/histogram/nodeHistogram/nodeHistogram.html, app-frontend/src/app/components/tools/diagramContainer/diagramContainer.component.js, app-frontend/src/app/components/tools/diagramContainer/diagramContainer.controller.js, app-frontend/src/app/pages/lab/run/run.controller.js, app-frontend/src/app/pages/lab/run/run.html, app-frontend/src/app/services/services.module.js, app-frontend/src/app/services/tools/histogram.service.js, app-frontend/src/app/services/tools/labUtils.service.js
Scale color map to histogram on first preview in lab.
It still acts weird if you open the histogram then preview, but we decided that it is not worth fixing until all the AST stuff is done.
* Open a tool run 
* Enter all inputs with a landsat 8 band, hit apply
* without opening a histogram, click preview and verify that the color map is scaled to the correct range.
Closes #2529
=> Scale color map to histogram on first preview in lab

app-tasks/rf/src/rf/ingest/models/ingest.py
=> Fix typo in Boto3 S3 delet call

app-frontend/src/app/pages/projects/edit/advancedcolor/adjust/adjust.controller.js, app-frontend/src/app/pages/projects/edit/color/color.controller.js, app-frontend/src/app/pages/projects/edit/colormode/colormode.html, app-frontend/src/app/pages/projects/edit/edit.controller.js, app-frontend/src/app/pages/projects/edit/scenes/scenes.controller.js, app-frontend/src/app/services/projects/histogram.service.js
Fixes a few minor things with:
- advanced color correction not working
- back button in color correction not working
- corrections displayed during single band mode
- import modal not showing up
- missing histogram
Closes #2555 
Closes #2554
=> Minor Frontend Fixups after Design Refactor

app-backend/database/src/main/scala/com/azavea/rf/database/tables/Scenes.scala
Filter scenes inside Scenes.JoinQuery.page instead
* Enable debug logging on the api server, and verify that when filtering the scene list, the executed query filters and pages on the scene side of the <scene, sceneWithRelated> join 
Before (with key aliases renamed and collapsed for readability): 
``` sql
SELECT (scenes_images_bands_thumbnails.'scenes_id',
scenes_images_bands_thumbnails.'scenes_created_at',
...)
FROM   (SELECT ("datasource" AS 'small_scenes_datasource',
"created_at" AS 'small_scenes_created_at',
"id"         AS 'small_scenes_id')
FROM   "scenes"
WHERE  ( true
AND ( "datasource" = …
```
=> Fix join of filtered scenes to paged scenes

app-frontend/config/webpack/global.js
=> Replace old HERE codes with up-to-date ones

app-tasks/Dockerfile
This is necessary for thumbnail generation
Trivial, merging
=> Install imagemagick in batch container

app-frontend/src/app/services/tools/labUtils.service.js
This PR makes a small change to work around the node ordering problem.
* Test that nodes are now displayed top-to-bottom rather than bottom-to-top
Closes #2587
=> Lab UI - Fix node ordering

app-backend/batch/src/main/scala/com/azavea/rf/batch/sentinel2/ImportSentinel2.scala
- Removes unnecessary data size retrieval
- Makes error handling more robust by moving to a higher level
```18:42:12.969 [INFO ] c.a.r.b.s.ImportSentinel2 - Finished importing scene(name: S2 tiles/37/W/EU/2017/3/10/0, id: 6160cf14-bc24-4bc7-867b-e32f7d44e05b
18:42:12.971 [ERROR] c.a.r.b.s.ImportSentinel2 - spray.json.DeserializationException: Polygon geometry expected
at geotrellis.vector.io.json.GeometryFormats$PolygonFormat$.read(GeometryFormats.scala:107)
at geotrellis.vector.io.json.GeometryFormats$PolygonFormat$.read(GeometryFormats.scala:101)
at spray.json.JsValue.convertTo(JsValue.scala:31)
at …
```
=> Make Sentinel Import More Robust

app-frontend/src/app/components/colorComposites/colorSchemeDropdown/colorSchemeDropdown.controller.js, app-frontend/src/app/components/projects/projectItem/projectItem.controller.js, app-frontend/src/app/components/projects/projectPublishModal/projectPublishModal.controller.js, app-frontend/src/app/components/projects/projectPublishModal/projectPublishModal.html, app-frontend/src/app/pages/lab/run/run.controller.js, app-frontend/src/app/pages/projects/detail/detail.controller.js, app-frontend/src/app/pages/projects/edit/edit.controller.js, app-frontend/src/app/pages/share/share.controller.js, app-frontend/src/app/services/auth/token.service.js, app-frontend/src/app/services/projects/project.service.js
Builds on https://github.com/raster-foundry/raster-foundry/pull/2590 with a few minor edits to allow sharing tool nodes and updating the modal.
- Go to tool run page and set node parameters
- Apply the changes and share the nodes and check if the modal appears similar to the demo/what you expected.
Closes #2546
=> Add tool share modal

app-frontend/src/app/components/common/navBar/navBar.html, app-frontend/src/app/pages/home/home.html
Remove feature flag for tools
Doesn't remove feature flag from database, since that would affect forked frontends
* Verify that an account without tools enabled can see tools now
Closes #2604
=> Remove feature flag for tools

app-frontend/src/app/components/map/labMap/labMap.controller.js, app-frontend/src/app/components/map/mapContainer/mapContainer.controller.js, app-frontend/src/app/components/map/mapContainer/mapContainer.html, app-frontend/src/app/components/map/measurementPopup/measurementPopup.component.js, app-frontend/src/app/components/map/measurementPopup/measurementPopup.controller.js, app-frontend/src/app/components/map/measurementPopup/measurementPopup.html, app-frontend/src/app/components/map/measurementPopup/measurementPopup.module.js, app-frontend/src/app/components/tools/nodeStatistics/nodeStatistics.controller.js, app-frontend/src/app/components/tools/nodeStatistics/nodeStatistics.html, app-frontend/src/app/index.components.js, app-frontend/src/app/pages/lab/run/run.controller.js, app-frontend/src/app/pages/projects/edit/advancedcolor/advancedcolor.controller.js, app-frontend/src/app/pages/projects/edit/color/color.controller.js, app-frontend/src/app/pages/projects/edit/colormode/colormode.controller.js, app-frontend/src/app/pages/projects/navbar/navbar.controller.js, app-frontend/src/app/pages/projects/navbar/navbar.html, app-frontend/src/app/services/auth/token.service.js, app-frontend/src/app/services/common/decimal.filter.js, app-frontend/src/app/services/projects/edit.service.js, app-frontend/src/app/services/projects/project.service.js, app-frontend/src/app/services/services.module.js, app-frontend/src/assets/styles/sass/_shame.scss, docs/style/angular.md
* Fix bugs around changing project name
* Refactor projectService and projectEditService for better functionality boundaries
* Exclude DataCells from Lab Node Stats tab
* Improve readability of measurement output in lab
* Move measurement output to a component
* Dynamically choose meters / km based on magnitude of measurement
* Format numbers using angular number filter
* Remove loading notification on project edit map
* Verify that loading icon doesn't appear on maps
* Verify that measurement popup works and doesn't have weird edge cases
* Verify that Data Cells is removed from the stats tab on lab nodes, and …
=> Misc project and lab usability fixes

app-frontend/src/app/components/tools/diagramContainer/diagramContainer.controller.js, app-frontend/src/app/components/tools/diagramContainer/diagramContainer.html, app-frontend/src/app/components/tools/inputNode/inputNode.controller.js, app-frontend/src/app/pages/lab/run/run.html, app-frontend/src/assets/styles/sass/_shame.scss
Fix comparing nodes in lab
Fix broken init in lab when loading existing tool run
Allow clicking node anywhere instead of just header
* Verify that you can compare lab nodes
* Verify that you can compare by clicking any part of the node instead of just the header
Closes #2564
=> Fix comparing lab nodes

app-backend/common/src/main/scala/Rollbar.scala, app-backend/common/src/main/scala/cache/CacheClient.scala, app-backend/tile/src/main/scala/LayerCache.scala, app-backend/tile/src/main/scala/image/Mosaic.scala, app-backend/tile/src/main/scala/routes/ToolRoutes.scala
Adds logging support for cache errors that we were only logging as "INFO"
Trivial - merging to test something once Jenkins is OK with it
=> Add rollbar support for cache errors

app-frontend/src/app/services/map/imageOverlay.service.js
Switch to d3 from konva for displaying thumbnails on map
Pros:
* doesn't crash the browser at high zoom levels
* Much simpler
* No memory usage issues, since it uses browser image elements and they're
cached correctly, as opposed to storing them twice in js as is required for
canvas approaches
Cons:
* Still has some performance issues at high zoom levels, but so does
everything else
* Stops showing SVG once you zoom in past 24 on Chrome and 23 on Firefox. At
that point, you're only able to see a single pixel value anyways
Thumbnail at zoom level 23:
memory usage:
No lag with this many scenes on the map:
* Verify that …
=> Optimize thumbnails on map

app-frontend/src/app/index.routes.js
=> Fix template file reference for lint

app-backend/Dockerfile, app-backend/build.sbt
Removes unecessary dependency and amount of required dependencies for running migrations
=> Reduce build requirements for migrations container

app-tasks/rf/src/rf/ingest/sentinel2_ingest.py
Prior to this commit, ingests for some Sentinel 2 scenes failed with index out
of bounds exceptions when cutting tiles. There have been other areas where we
recognized that ingesting non-web mercator imagery caused other exceptions. To
verify that this fixes the issue I uploaded reprojected tifs manually and a
previously failed ingest could now succeed.
- Start VM
- Ensure recent version of batch container is build (`docker-compose build batch`)
- Start batch container `./scripts/console batch bash`
- Run ingest process command on sentinel scene, ensuring that it successfully reprojects data: `rf ingest-scene …
=> Reproject sentinel 2 tifs to Web Mercator before ingest

app-backend/database/src/main/scala/com/azavea/rf/database/tables/Tools.scala, app-frontend/src/app/components/tools/toolItem/toolItem.html, app-frontend/src/app/pages/lab/browse/templates/templates.html, app-frontend/src/app/pages/lab/browse/templates/templates.js
Tool Runs still aren't sorted. 
* Verify that the api now sorts by title, modifiedAt, or createdAt (asc / desc)
Closes #2515
=> Fix tool sorting

app-backend/migrations/src_migrations/main/scala/85.scala
=> Fix migration 85

app-frontend/src/app/components/aoiFilterPane/aoiFilterPane.component.js, app-frontend/src/app/components/aoiFilterPane/aoiFilterPane.controller.js, app-frontend/src/app/components/aoiFilterPane/aoiFilterPane.html, app-frontend/src/app/components/aoiFilterPane/aoiFilterPane.module.js, app-frontend/src/app/components/aoiFilterPane/aoiFilterPane.scss, app-frontend/src/app/pages/projects/edit/aoi-parameters/aoi-parameters.controller.js, app-frontend/src/app/pages/projects/edit/aoi-parameters/aoi-parameters.html
This PR fixes issues on the AOI scene filter pane: data source, reset filters, close button, styling.
@designmatty please find minor css additions are in `aoiFilterPane.scss` in the same directory of this component.
* Go to AOI parameter page
* Expand the AOI scene filter pane
* Check if the styling is expected
* Check if data source, reset, close button work as intended
Closes #2353
=> Fix AOI filter's data source, reset, close button, styling issues

app-frontend/src/app/components/scenes/sceneList/sceneList.controller.js, app-frontend/src/app/components/scenes/sceneList/sceneList.html, app-frontend/src/assets/styles/sass/components/_list-group.scss
Remove dropdown menu
Click to preview
Small style fix
* Verify that clicking imports previews them
* Verify that the download and delete buttons work as expected
Closes #2680
=> Add click to preview imports

app-frontend/src/app/components/map/nodeSelector/nodeSelector.html, app-frontend/src/app/components/map/nodeSelector/nodeSelector.module.js, app-frontend/src/app/components/tools/diagramContainer/diagramContainer.html, app-frontend/src/app/components/tools/diagramContainer/diagramContainer.module.js, app-frontend/src/app/components/tools/toolNode/toolNode.html, app-frontend/src/app/components/tools/toolNode/toolNode.module.js, app-frontend/src/app/pages/lab/tool/tool.html, app-frontend/src/app/pages/lab/tool/tool.js, app-frontend/src/app/redux/actions/node-actions.js, app-frontend/src/app/redux/reducers.js, app-frontend/src/app/redux/reducers/node-reducer.js, app-frontend/src/assets/styles/sass/_shame.scss
Add preview and compare buttons to left action toolbar in lab
Redefine actions for previewing and comparing
* Verify that preview / comparing elsewhere in the lab still works as expected
* Verify that the new preview and compare buttons work in a way that makes sense
* Verify that the action toolbar does not show when creating a tool from a template (save button / name field show instead)
Closes #2662 
Depends on #2690
=> Add lab action toolbar with preview and compare buttons

app-frontend/src/assets/styles/sass/theme/high-contrast/app.scss, app-frontend/src/assets/styles/sass/theme/high-contrast/pages/_login.scss
Add styles to the high contrast theme to style the auth0 login pages.
=> Add Auth0 Login Theme Support

app-frontend/src/app/services/map/map.service.js
Fixes scene items not deleting footprint from map on mouse leave
Feel free to merge immediately once you approve it
* On a project with a single scene, mouse over a scene, then move your mouse off it. The footprint for the scene should be placed on the map, then removed after your mouse leaves
=> Fix setting geojson layer not overwriting

app-backend/tile/src/main/scala/image/Mosaic.scala
Fixes the raw export functionality of the tile-server's export endpoint. When the `colorCorrect` query parameter is set to false, the endpoint returns the raw project mosaic.
* the export endpoint is used on the project list page, so open up the front-end and copy the request URL of one of the previews
* add the `colorCorrect` query parameter and see that it works as expected when set to `true` and `false`
* change the color-mode of the project and make sure that the export is consistent when `colorCorrect` is false, no matter what the color mode of the project is
Closes #2716
=> Fix tile-server non-color-corrected exports

app-frontend/src/app/services/map/mapUtils.service.js, app-frontend/src/app/services/projects/export.service.js, app-frontend/src/app/services/settings/status.service.js
This PR fixes the listing of an export's files. It also modifies the export status text to better reflect the export process.
We may want to adjust the export process to provide better granularity re: export status: #2078
* On a project with completed exports (may need to point to staging for this), try downloading an export and check that the modal opens and lists the various files
=> Fix export file listing

app-frontend/src/app/components/scenes/sceneImportModal/sceneImportModal.html
Adds some text to the import modal to indicate drag and drop capability.
Trivial, merging once CI is green.
Closes #2298
=> Add text to indicate drag and drop upload

app-frontend/src/assets/styles/sass/components/_login.scss
Fixes styles on login styles to better accommodate various Auth0 login scenarios.
Closes #2773
=> Fix squished login header

app-frontend/src/app/components/colorComposites/colorSchemeDropdown/colorSchemeDropdown.html, app-frontend/src/app/components/colorComposites/colorSchemeDropdown/colorSchemeDropdown.module.js, app-frontend/src/app/components/histogram/histogramBreakpoint/histogramBreakpoint.html, app-frontend/src/app/components/histogram/histogramBreakpoint/histogramBreakpoint.module.js, app-frontend/src/app/components/histogram/nodeHistogram/nodeHistogram.html, app-frontend/src/app/components/histogram/nodeHistogram/nodeHistogram.module.js, app-frontend/src/app/components/lab/labNode/labNode.html, app-frontend/src/assets/styles/sass/_shame.scss, app-frontend/src/assets/styles/sass/components/_form.scss
Input nodes now show histogram and statistics
Depends on #2768 
* Verify that the histogram looks correct, and is not interactable
* Verify that the stats node view works as expected
Closes https://github.com/raster-foundry/raster-foundry/issues/2712
=> Show histogram and stats on inputs

app-frontend/src/app/components/lab/labNode/labNode.html, app-frontend/src/app/components/lab/labNode/labNode.module.js, app-frontend/src/app/services/auth/token.service.js
This PR adds a sharing button to shareable nodes (sources, operations).
* Open an analysis and share some nodes
Closes #2778
=> Re-add lab node share

app-backend/api/src/main/scala/token/Token.scala, docs/swagger/spec.yml
We need to return the ID token and changes the request to be more in line with
how we use refresh tokens in other environments.
Once CI is happy going to merge
Closes https://github.com/raster-foundry/raster-foundry/issues/2784
=> Fix support for handling refresh tokens

.gitignore, app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/package.scala, app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/stac/Asset.scala, app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/stac/Band.scala, app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/stac/Feature.scala, app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/stac/Link.scala, app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/stac/Product.scala, app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/stac/Properties.scala, app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/stac/package.scala
Create STAC datamodels for use in imports later
* Verify that the following decodes correctly 
```scala
./scripts/console api-server ./sbt
> project api
> console
import com.azavea.rf.datamodels.stac
import io.circe.parser.decode
decode[Feature]("""{"id":"IPR201411271156491862N07128W","links":[{"type":"self","href":"/home/cbrown/Projects/sample-imagery/radiant/iserv-catalog/IPR201411271156491862N07128W.json"},{"type":"thumbnail","href":"IPR201411271156491862N07128W.png"}],"properties":{"start":"2017-12-04T11:56:49Z","end":"2017-12-04T11:56:49Z","provider":"NASA, …
```
=> Create stac datamodels

app-frontend/src/app/components/lab/diagramNodeHeader/diagramNodeHeader.html, app-frontend/src/app/components/lab/diagramNodeHeader/diagramNodeHeader.module.js, app-frontend/src/assets/styles/sass/_shame.scss, app-frontend/src/assets/styles/sass/theme/high-contrast/components/_lab-node.scss
This is based on: #2829. It's rebased and adds a single commit to get this ready to merge.
Closes #2792
=> Allow renaming of nodes in the lab

app-frontend/src/app/services/projects/export.service.js, app-frontend/src/app/services/scenes/datasource.service.js, app-frontend/src/app/services/scenes/scene.service.js
This PR makes sure we use API_HOST everywhere.
Closes #2899
=> Use `API_HOST` in all API url construction

app-backend/common/src/main/scala/cache/CacheClient.scala, app-backend/project/build.properties
Updates SBT to get around an issue with SBT runner in 1.0.x and class loading. Also adds a few logging and error reporting changes so that issues like this are surfaced more quickly.
* Rebuild servers and start them
* Make requests to the tile server and see how subsequent requests (e.g. change color mode) happen much more quickly
Closes #2912
=> Fix Development Caching

app-frontend/src/app/pages/lab/browse/analyses/analyses.html, app-frontend/src/app/pages/lab/browse/analyses/analyses.js, app-frontend/src/assets/styles/sass/_shame.scss
Set constant column width for analysis modified date and deletion
Use checkbox and delete selected button instead of individual delete buttons
* Verify that long analysis names don't change the column widths in the analysis list view
* Verify that the delete checkbox / button work as expected
Closes #2819
=> Set constant column width for analysis modified date and deletion

app-frontend/src/app/components/scenes/importList/importList.module.js, app-frontend/src/app/pages/projects/edit/scenes/scenes.module.js
Pass repository into scene modal
* Verify that scene detail modal opens in project scene list view and in import view
Closes #2959
=> Fix scene modal

app-frontend/src/app/components/settings/organizationModal/organizationModal.html, app-frontend/src/app/components/settings/organizationModal/organizationModal.module.js, app-frontend/src/app/components/settings/teamModal/teamModal.html, app-frontend/src/app/components/settings/teamModal/teamModal.module.js, app-frontend/src/app/components/settings/userModal/userModal.html, app-frontend/src/app/components/settings/userModal/userModal.module.js, app-frontend/src/app/index.components.js, app-frontend/src/app/index.module.js, app-frontend/src/app/index.routes.js, app-frontend/src/app/pages/settings/organizations/organizations.html, app-frontend/src/app/pages/settings/organizations/organizations.module.js, app-frontend/src/assets/styles/sass/components/_modal.scss
Add placeholder organizations view under settings for testing modals.
Modals are not hooked up to anything yet.
* Enable the profile-org-edit feature flag
* go to the organizations settings view
* test each of the modals (return value is posted to the dev console)
Closes #2966
=> Create modals for adding users, teams, and organizations

app-frontend/src/app/components/filters/searchSelectFilter/searchSelectFilter.html, app-frontend/src/app/components/scenes/sceneDetailModal/sceneDetailModal.html, app-frontend/src/app/components/scenes/sceneDetailModal/sceneDetailModal.module.js, app-frontend/src/app/components/scenes/sceneItem/sceneItem.html, app-frontend/src/app/components/scenes/sceneItem/sceneItem.module.js, app-frontend/src/app/services/map/map.service.js, app-frontend/src/app/services/scenes/cmrRepository.service.js, app-frontend/src/app/services/scenes/planetRepository.service.js, app-frontend/src/app/services/scenes/rasterFoundryRepository.service.js, app-frontend/src/assets/styles/sass/components/_button.scss, app-frontend/src/assets/styles/sass/components/_searchselect.scss
Datasources are edited using the same workflow as scene metadata
* Verify that changing datasources works
* Verify that the style changes don't affect selectors in other parts of the app
* Verify that the scene in the sidebar reflects the new datasource
Closes #2920
=> Allow changing datasource in scene detail modal

app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/License.scala
This PR creates a JSON interface in the license data model for datasource licenses.
Closes #2970
=> Create a JSON interface for datasource licenses.

app-backend/batch/src/main/scala/com/azavea/rf/batch/export/spark/Export.scala
This PR makes it so that `astExport` will `regrid` the `Tile`s of the layer to the desired size before being saved off as `GeoTiff`s. In addition, the logic in `multibandExport` has been fixed such that the layer will be `regrid`ed even if the source and target `CRS` are the same.
I don't have the development environment setup in order to run this PR.
Running the preexisting tests for this feature should cover this PR.
=> Regriding and Logic Fix for GeoTiff Exporting

app-backend/build.sbt
This PR refers to the solution [here](https://github.com/sbt/sbt/issues/3750) to solve the issue where it gives dependency NPE error when bringing a new development environment up.
Closes #2990
=> Resolve dependency NPE error

app-frontend/src/app/pages/settings/settings.html, app-frontend/src/assets/styles/sass/_shame.scss, app-frontend/src/assets/styles/sass/components/_form.scss, app-frontend/src/assets/styles/sass/components/_list-group.scss, app-frontend/src/assets/styles/sass/components/_modal.scss, app-frontend/src/assets/styles/sass/layout/_navbar.scss
- Multiple browsers Lab view/compare selection dropdown too small
**Preview:**
**Fix:** `_shame.scss` between `lines 2014 - 2048`
---
- ie11 Settings subpages inaccessible
**Preview:**
**After fix:** Not perfect but works
**Fix:** all changes on `app-frontend/src/app/pages/settings/settings.html`
---
- ie 11 color mode expands broken in project editing:
**Preview:**
**After fix:**
**Fix:** changes on `app-frontend/src/assets/styles/sass/components/_list-group.scss`
---
- ie11 Data page subnav off canvas
**Preview:**
**Fix:** changes on `app-frontend/src/assets/styles/sass/layout/_navbar.scss`
---
- ie11 Massive sidebar buttons and in node squashed buttons
**Preview:**
**Fix massive buttons:** `_shame.scss` on `line 933`
**Fix squashed buttons:** `_shame.scss` on `line 1615`
---
- ie11 …
=> fixed several browser issues for both themes

app-frontend/src/assets/styles/sass/components/_filter.scss, app-frontend/src/assets/styles/sass/components/_modal.scss, app-frontend/src/assets/styles/sass/components/_searchselect.scss
Fix styling on search dropdowns
* Verify that datasource dropdowns in the browse filter work as expected
* Verify that the datasource dropdown in the scene detail modal now is correctly sized and shows up
Closes #2992
=> Fix dropdown filter styling

docs/architecture/adr-0020-access-control-and-organizations.md
[Rendered](https://github.com/raster-foundry/raster-foundry/blob/feature/ak/ac-adr/docs/architecture/adr-0020-access-control-and-organizations.md)
May be some formatting things I need to adjust.
=> [WIP] ADR - Permissions and Architecture for Organizations

docs/swagger/spec.yml
This PR adds swagger spec for the endpoint of getting raw analyses in lab rendered as single band tiffs
Closes #2980
=> Add swagger spec for raw analyses render endpoint

app-frontend/src/app/components/lab/diagramContainer/diagramContainer.module.js, app-frontend/src/app/services/analysis/labUtils.service.js
Fix node ordering in lab
* Verify that inputs to nodes are now ordered from top to bottom, instead of bottom to top
Closes #2944
=> Fix node ordering in lab

app-frontend/src/app/pages/projects/edit/edit.module.js
This PR fixes the bug that caused scene delete failure and scene display failure (after being added from scene browse).
* Go to a project
* Add new scenes, delete scenes, and see if it behaves as you expected
* Manipulate scenes in other ways and see if they behave as you'd expect
Closes #3053 
Closes #3054
=> Fix scene delete and scene display after being added issues

app-frontend/src/app/services/auth/auth.service.js
Delete all tokens when logging out
* Verify that logging out works
Closes #2996
=> Fix broken logout button

app-frontend/src/app/pages/projects/edit/colormode/colormode.controller.js, app-frontend/src/app/pages/projects/edit/edit.module.js
Bug-fix that will make color-modes work again.
=> Fix colormodes

app-backend/api/src/main/scala/organization/Routes.scala, app-backend/datamodel/src/test/scala/com/azavea/rf/datamodel/implicits/Generators.scala, app-backend/db/src/main/scala/com/azavea/rf/database/OrganizationDao.scala, app-backend/db/src/test/scala/com/azavea/rf/database/OrganizationDaoSpec.scala
* `testOnly com.azavea.rf.database.OrganizationDaoSpec`
=> Add property tests for OrganizationDao interactions

app-backend/datamodel/src/test/scala/com/azavea/rf/datamodel/implicits/Generators.scala, app-backend/db/src/main/scala/com/azavea/rf/database/AnnotationDao.scala, app-backend/db/src/test/scala/com/azavea/rf/database/AnnotationDaoSpec.scala, app-backend/db/src/test/scala/com/azavea/rf/database/PropTestHelpers.scala
=> Add AnnotationDao property tests

app-backend/datamodel/src/test/scala/com/azavea/rf/datamodel/implicits/Generators.scala, app-backend/db/src/main/scala/com/azavea/rf/database/DatasourceDao.scala, app-backend/db/src/test/scala/com/azavea/rf/database/DataSourceDaoSpec.scala, app-backend/db/src/test/scala/com/azavea/rf/database/PropTestHelpers.scala, docs/style/scala.md
This PR adds property tests for datasource dao.
* CI
=> Add property tests for datasource dao

app-backend/datamodel/src/test/scala/com/azavea/rf/datamodel/implicits/Generators.scala, app-backend/db/src/main/scala/com/azavea/rf/database/UploadDao.scala, app-backend/db/src/test/scala/com/azavea/rf/database/PropTestHelpers.scala, app-backend/db/src/test/scala/com/azavea/rf/database/UploadDaoSpec.scala
This PR adds property tests to the UploadDao
* CI
=> Add property tests for UploadDao

app-frontend/src/app/redux/reducers/annotation-reducer.js
Trivial, will merge once CI is happy.
Closes #3181
=> Update `annotation-reducer.js` to handle GeoJSON

app-backend/api/src/main/scala/scene/Routes.scala
This PR fixes the scene download endpoint.
* Hit the scene download endpoint and see that it returns urls to the download items
Closes #3184
=> Fix scene downloads endpoint

app-frontend/src/app/components/vectors/vectorNameModal/vectorNameModal.module.js
This PR saves drawn multiple polygonal shape filters as `MultiPolygon`
* Turn off the feature flag on shapes/vectors
* Go to a project and browse scenes
* Use shape filter drop down and select draw shape
* Draw one polygon or multiple polygons and save
* Check if all polygons are displayed on the map and are applied as filters; see if these shapes are correctly created in your list of vectors. 
Closes #3146
=> Save multiple drawn polygons as MultiPolygon for shape filter

app-frontend/src/app/components/common/search/search.html, app-frontend/src/app/components/common/search/search.js, app-frontend/src/app/components/lab/nodeCreateSidebar/nodeCreateSidebar.html, app-frontend/src/app/components/lab/nodeCreateSidebar/nodeCreateSidebar.js, app-frontend/src/app/components/projects/projectSelectModal/projectSelectModal.controller.js, app-frontend/src/app/pages/lab/browse/templates/templates.js, app-frontend/src/app/pages/lab/browse/workspaces/workspaces.html, app-frontend/src/app/pages/lab/browse/workspaces/workspaces.js, app-frontend/src/assets/styles/sass/components/_form.scss, app-frontend/src/assets/styles/sass/components/_lab-sidebar.scss
This PR updates frontend to support text search using pattern matching endpoint in the following places in lab:
* Workspace
* Template
* Input node (Project)
* Project selection modal
* Functions/operations
* Formula
Test the search feature contained within the following page routes:
* `/lab/browse/workspaces`
* `/lab/browse/templates`
* `/lab/workspace/<workspace id>`:
- Input
- Function
- Formula
- Template 
Closes #3172
=> Enable text search in workspace, template, project and function in Lab

app-backend/common/src/main/scala/Authentication.scala
See title
* Reset your database
* Log in as any user
* Verify that the email, name, and profile_image_uri fields are updated in the database
Closes https://github.com/raster-foundry/raster-foundry/issues/3277
=> Update user email, name, and profileImageUri fields when they log in

app-backend/api/src/main/scala/scene/Routes.scala, app-backend/db/src/main/scala/com/azavea/rf/database/Dao.scala, app-backend/db/src/main/scala/com/azavea/rf/database/SceneDao.scala, app-backend/db/src/main/scala/com/azavea/rf/database/SceneWithRelatedDao.scala
This PR:
- removes owner and visibility checks on scene routes, `sceneDao` and `sceneWithRelatedDao`, since we manage those with access control rules now
- adds authorizations to scene endpoints
- updates sql for authorization in `Dao`
* run migrations if neccessary
* add below records in your dev db for testing purposes:
```sql
INSERT INTO teams VALUES (
'f53a67bb-2b0d-484a-90d9-115b78a2cd28',
NOW(),
'default',
NOW(),
'default',
'dfac6307-b5ef-43f7-beda-b9f208bb7726',
'Test team',
'{}'
);
INSERT INTO …
```
=> Add authorization to scene endpoints

app-tasks/rf/src/rf/utils/io.py
This PR adds a helper function to create a Landsat 4, 5, or 7 path in Google Cloud Storage
from an ID.
* get a Landast 4, 5, or 7 id. Here are some, if you feel like using them:
* `LE70010562000338CUB00`
* `LM50010161995140PAC00`
* `LM40010101988065AAA03`
* `from rf.utils.io import gcs_path_for_landsat_id`
* `wget <that path>/<the id>_B1.TIF`
* open in QGIS
Closes #3319
=> Add Landsat 4, 5, and 7 gcs path construction util

app-backend/api/src/main/scala/user/Routes.scala, app-frontend/src/app/components/common/navBar/navBar.html, app-frontend/src/app/pages/admin/admin.html, app-frontend/src/app/pages/admin/admin.module.js, app-frontend/src/app/pages/admin/platform/organizations/organizations.html, app-frontend/src/app/pages/admin/platform/organizations/organizations.module.js, app-frontend/src/app/pages/admin/platform/users/users.html, app-frontend/src/app/pages/admin/platform/users/users.module.js, app-frontend/src/app/services/auth/auth.service.js, app-frontend/src/app/services/auth/organization.service.js, app-frontend/src/app/services/auth/platform.service.js, app-frontend/src/app/services/auth/team.service.js, app-frontend/src/app/services/services.module.js
Add a `users/me/roles` endpoint
Add services for platform, organization, and team
Update initial admin page to list platforms and organizations that the user is an admin of
Populate platform users and organizations lists from API with pagination and search
Search and pagination not guaranteed to work until other PRs are merged - this just implements the frontend.
* Add a platform admin role to your user
* Verify that a new admin button shows up when you click the user button on the upper right hand corner of the page
* Verify that the platform shows up correctly
* Click manage on the …
=> Hook up platform admin organization/user views

app-backend/api/src/main/scala/shape/Routes.scala, app-backend/api/src/main/scala/toolrun/Routes.scala, app-backend/api/src/main/scala/tools/Routes.scala
This PR adds row-level auth to the tool/template, tool-run/analysis, and shape endpoints.
Currently it's the case that you can see analyses for templates that you don't have access to. I _think_
that's good and desirable -- for example, someone might want to share an analysis with `View` only
permissions, without giving someone else the ability to use the underlying template to create their own.
* bring up ur server and frontend
* log in with google
* note that you don't see any templates or analyses (unless you own some with your local google user -- I didn't)
* create a template
* create an analysis from it
* log in with the dev user
* verify that you can't see either of the things you just created
* create view and edit ACRs for the template you created for everyone
* or for bonus …
=> Add authorization to remaining first-class auth objects

.github/PULL_REQUEST_TEMPLATE.md
Add a testing requirement to our checklist
~- [ ] If not merging to an anchor PR, any new DAO functions have tests~
=> Add requirement for DAO tests

app-tasks/rf/src/rf/uploads/modis/factories.py
=> Remove errant debugging argument for get_tempdir

app-backend/db/src/main/scala/com/azavea/rf/database/AccessControlRuleDao.scala
This PR uses the TeamDao to check if teams exist.
* Try to create an ACR targeting a team
* Note that it is possible
=> Use TeamDao to check team existence

app-backend/batch/src/main/scala/com/azavea/rf/batch/landsat8/ImportLandsat8C1.scala, app-backend/batch/src/main/scala/com/azavea/rf/batch/sentinel2/ImportSentinel2.scala
This PR create access control rules allowing everyone to view scenes for Sentinel-2 and
Landsat 8 scenes when they're imported.
* Fire up a psql shell
* `select count(1) from access_control_rules;`
* `./scripts/console api-server ./sbt`
* `project batch`
* `console`
* run the sentinel 2 import job for a little bit:
```scala
import com.azavea.rf.batch.sentinel2.ImportSentinel2
import com.azavea.rf.database.util.RFTransactor.xa
ImportSentinel2().run
```
* `watch the counts increase for access control rules in the database
* kill the sentinel 2 import
* get the most recent scene id: `select id from scenes order by created_at desc limit 1;`
* fire up your server and get a token for the dev user
* send a GET to `/api/scenes/<the most recent scene's id>/` with your token and confirm that you …
=> Create AccessControlRules on public scene import

app-backend/db/src/main/scala/com/azavea/rf/database/UserGroupRoleDao.scala
This PR uses platform admin roles in addition to `superuser` status
to determine when private users should be visible in a user search.
There isn't currently filtering to ensure that the platform the user is an admin of
"contains" (for lack of a better word) the group they're trying to list. I wasn't sure
what a good way to do that would be, so I left it off for now. Traveling through the
UI/through the API, there's no way to get to orgs/teams outside the platform that
I'm aware of, so I don't think that matters yet, and I omitted it to keep complexity
down.
* Create an admin role for your dev user
* Try to search some users
* Observe that you see publicly visible users
Closes azavea/raster-foundry-platform#340
=> Fix platform admin user search

app-frontend/src/app/pages/admin/admin.html, app-frontend/src/app/pages/admin/organization/organization.html, app-frontend/src/app/pages/admin/organization/teams/teams.html, app-frontend/src/app/pages/admin/organization/users/users.html, app-frontend/src/app/pages/admin/platform/organizations/organizations.html, app-frontend/src/app/pages/admin/platform/platform.html, app-frontend/src/app/pages/admin/platform/users/users.html, app-frontend/src/app/pages/admin/team/team.html, app-frontend/src/app/pages/admin/team/users/users.html, app-frontend/src/assets/styles/sass/pages/_admin.scss
This PR begins to apply styling to the Raster Foundry organization management features. Right now, this is focused on the table view that seems finished. I will work on other views as they are completed.
I'll be waiting until more features are closer to completion before I continue styling, to avoid additional merge conflicts.
* Look at that table view and make sure it seems okay
* Test on RF theme and Radiant theme
* I had to fix a few merge conflicts; could you take a look at that and make sure I didn't accidentally remove anything?
=> Apply visual design to admin views

app-backend/db/src/main/scala/com/azavea/rf/database/OrganizationDao.scala, app-frontend/src/app/components/settings/addPhotoModal/addPhotoModal.html, app-frontend/src/app/components/settings/addPhotoModal/addPhotoModal.module.js, app-frontend/src/app/index.components.js, app-frontend/src/app/pages/admin/organization/organization.html, app-frontend/src/app/pages/admin/organization/organization.module.js, app-frontend/src/app/services/auth/organization.service.js, app-frontend/src/assets/styles/sass/pages/_admin.scss
This PR adds frontend support for organization admins or super users to add organization logo.
* A logo should be in `.png` format with less than 512x512 pixels.
* Set the dev user as the public organization's admin or a super user.
* Navigate to admin -> organization page.
* Hover on the organization avatar and click to trigger the logo change modal.
* Go through the process and see if it behaves as you expect.
* Switch dev user's role to an organization's `MEMBER` or …
=> Frontend support for admin adding org logo

app-backend/api/src/main/scala/platform/Routes.scala, app-backend/common/src/main/scala/Authentication.scala, app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/ActiveStatus.scala, app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/User.scala, app-backend/db/src/main/scala/com/azavea/rf/database/OrganizationDao.scala, app-backend/db/src/main/scala/com/azavea/rf/database/PlatformDao.scala, app-backend/db/src/main/scala/com/azavea/rf/database/UserDao.scala, app-backend/db/src/test/scala/com/azavea/rf/database/UserDaoSpec.scala, app-frontend/src/app/pages/admin/organization/users/users.html, app-frontend/src/app/pages/admin/platform/organizations/organizations.html, app-frontend/src/app/pages/admin/platform/organizations/organizations.module.js, app-frontend/src/app/pages/admin/platform/users/users.html, app-frontend/src/app/services/auth/organization.service.js, app-frontend/src/app/services/auth/platform.service.js
Prevent users in a disabled org or platform from logging in
* Make sure the dev system user is in your database and specified in your .env file
* Create a new user and log in
* Log out, then log in on a platform admin
* Create a new org, add the new user to it
* Disable the new org
* Try to log in with the new user - requests should return a 403
* Enable the org using an admin
* Log in with the new user again
Closes #3282
=> Add organization and platform enabling/disabling endpoints

app-backend/api/src/main/scala/organization/Routes.scala, app-backend/api/src/main/scala/uploads/Routes.scala, app-backend/api/src/main/scala/user/Routes.scala, app-backend/common/src/main/scala/Authentication.scala, app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/User.scala, app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/package.scala, app-backend/db/src/main/scala/com/azavea/rf/database/Dao.scala, app-backend/db/src/main/scala/com/azavea/rf/database/util/Ownership.scala, app-tasks/rf/src/rf/commands/process_upload.py, app-tasks/rf/src/rf/models/base.py, app-tasks/rf/src/rf/models/scene.py, app-tasks/rf/src/rf/uploads/modis/factories.py
Fixes the following issues:
- MODIS scene creation in upload processing
- Updates of scenes after ingest
- Fixes/Adjusts check of owner to superuser
=> Various Auth/Ingest Fixes

app-backend/common/src/main/scala/Authentication.scala
Return a 401 instead of a 501
Log error to papertrail so we can address the user manually
* Delete the platform and organization roles for a user and try to log in. The user should get a 401 response when they try to log in
Closes https://github.com/raster-foundry/raster-foundry/issues/3472
=> Handle case where user tries to log in without a platform or an org

app-backend/build.sbt, app-backend/project/Version.scala
This PR bumps up MAML version to resolve a Lab issue that could happen during evaluation of non square tiles.
* Use the following COG `conus-precip-cog.tif` 
* Perform NDVI
* The result should not fail and should look like this:
Closes #3409
=> Bump up MAML version

app-frontend/src/app/pages/admin/organization/organization.html, app-frontend/src/app/pages/admin/platform/platform.html
Trivial. Merging once CI passes.
=> Show placeholder when no org logo present

app-backend/api/src/main/scala/platform/Routes.scala, app-frontend/src/app/pages/admin/organization/organization.html, app-frontend/src/app/pages/admin/organization/organization.module.js, app-frontend/src/app/pages/admin/organization/teams/teams.html, app-frontend/src/app/pages/admin/organization/users/users.html, app-frontend/src/app/pages/admin/organization/users/users.module.js, app-frontend/src/app/pages/admin/platform/organizations/organizations.html, app-frontend/src/app/pages/admin/platform/platform.module.js, app-frontend/src/app/pages/admin/platform/users/users.html, app-frontend/src/app/pages/admin/platform/users/users.module.js, app-frontend/src/app/pages/admin/team/users/users.html, app-frontend/src/app/services/auth/platform.service.js, app-frontend/src/assets/styles/sass/_shame.scss
Trivial. Merging once CI passes.
Makes progress on  #3503
=> Allow organization admins to add and modify roles for that organization

app-frontend/src/app/index.module.js, app-frontend/src/app/index.routes.js, app-frontend/src/app/pages/admin/platform/platform.html, app-frontend/src/app/pages/admin/platform/platform.module.js, app-frontend/src/app/pages/admin/platform/settings/email/email.html, app-frontend/src/app/pages/admin/platform/settings/email/email.module.js, app-frontend/src/app/pages/admin/platform/settings/settings.html, app-frontend/src/app/pages/admin/platform/settings/settings.module.js, app-frontend/src/app/pages/admin/platform/users/users.module.js, app-frontend/src/app/services/auth/auth.service.js, app-frontend/src/app/services/auth/platform.service.js, app-frontend/src/assets/styles/sass/_shame.scss, app-frontend/src/assets/styles/sass/layout/_container.scss, app-frontend/src/assets/styles/sass/layout/_sidebar.scss, app-frontend/src/assets/styles/sass/pages/_admin.scss
This PR adds frontend support to let super users or platform admins set platform email info and notification preferences.
* Log in as a platform admin user
* Navigate to admin -> platform -> settings -> email notifications
* Make sure it works as you expect
Closes #3442
=> Platform email notification settings frontend

app-frontend/src/app/pages/projects/list/list.controller.js
This is temporary until the design/filter options are updated for the frontend
=> Restrict Projects to Owners for Frontend

app-backend/batch/src/main/scala/com/azavea/rf/batch/aoi/UpdateAOIProject.scala
This PR cleans up the scene queries in `UpdateAOIProject` to be more like scene queries elsewhere.
More specifically, it:
- does away with some complicated nested flatmaps, some of which were repetitive
- remembers to update `aois_last_checked` in projects, which wasn't happening before even though we had a `ConnectionIO` for it
- does away with ad hoc filtering with `fr"foo = ${bar}`, since we already had `Filterables` for everything we wanted to filter by for scenes
- uses the `authViewQuery` for scenes instead of the `authQuery`, so we can get `Public` scenes in
addition to scenes owned by the querying user
Demoed in pairing.
* Import some scenes
* Create an AOI project with an area covering their area and a start date from before their acquisition date
* Run `UpdateAOIProject` for …
=> Use authViewQuery for AOI scenes

app-frontend/src/app/services/auth/auth.service.js
Fixes where the redirect goes, backend settings in Auth0 have already been updated
Pretty trivial, going to merge away
=> Fix redirect to token page

app-backend/api/src/main/scala/project/Routes.scala, app-backend/batch/src/main/scala/com/azavea/rf/batch/aoi/UpdateAOIProject.scala, app-backend/db/src/main/scala/com/azavea/rf/database/ProjectDao.scala, app-backend/db/src/main/scala/com/azavea/rf/database/SceneToProjectDao.scala, app-backend/db/src/main/scala/com/azavea/rf/database/SceneWithRelatedDao.scala, app-backend/db/src/test/scala/com/azavea/rf/database/ProjectDaoSpec.scala, app-backend/db/src/test/scala/com/azavea/rf/database/SceneToProjectDaoSpec.scala, app-frontend/src/app/components/common/navBar/navBar.controller.js, app-frontend/src/app/pages/projects/edit/aoi-approve/aoi-approve.controller.js, app-frontend/src/app/pages/projects/edit/aoi-approve/aoi-approve.html, app-frontend/src/app/pages/projects/edit/aoi-parameters/aoi-parameters.controller.js, app-frontend/src/app/pages/projects/edit/aoi-parameters/aoi-parameters.html, app-frontend/src/app/pages/projects/edit/browse/browse.module.js, app-frontend/src/app/pages/projects/edit/edit.module.js, app-frontend/src/app/services/auth/auth.service.js, app-frontend/src/app/services/projects/project.service.js, app-frontend/src/assets/styles/sass/_shame.scss
This PR fixes AOI update and approval so that for AOI projects scenes will not be accepted until the users approve so on the frontend.
* Create an AOI project, set some parameters on the frontend (suggested start date may be some time in 2017 for dev DB), and start monitoring
* `java -cp /opt/raster-foundry/jars/rf-batch.jar com.azavea.rf.batch.Main "update_aoi_project"  "<AOI project ID>"`
* Go to AOI project frontend. Approve and reject some scenes. See if it reacts as you expect.
Closes #3302
=> Fix AOI update and approval bug

app-frontend/src/app/components/scenes/sceneFilterPane/sceneFilterPane.html, app-frontend/src/app/pages/projects/edit/browse/browse.module.js
Closes https://github.com/azavea/raster-foundry-platform/issues/386
=> Use BUILDCONFIG.APP_NAME as base repository label

app-backend/tile/src/main/scala/image/GlobalSummary.scala
This PR adds a fallthrough to the attempt to get zooms and extents for projects.
* You need a project with ingested _and_ uningested scenes to test this
* That's a drag
* So instead:
* Think about what a `MatchError` means and verify that this addresses the match error we got
* Test in staging or somewhere else where we know such a project exists
Closes #3366
=> Add fallthrough mosaic match to extent and zoom fetch

app-backend/api/src/main/scala/scene/Routes.scala, app-backend/api/src/main/scala/scene/ThumbnailQueryParameters.scala, app-backend/common/src/main/scala/utils/CogUtils.scala, app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/QueryParameters.scala, app-frontend/src/app/components/scenes/sceneItem/sceneItem.module.js, app-frontend/src/app/services/scenes/scene.service.js
This PR fixes rendering of MODIS thumbnails. More generally, it fixes a problem we would have
had generating thumbnails from any COG that didn't start off as three or four bands.
Thanks to @lossyrob, @pomadchin, and @moradology for some geotrellis help
* add a modis scene to a project
* process its upload
* query for its thumbnails with some different query parameters
* add a single band COG to a project
* view scenes for that project
* confirm its thumbnail succeeds
* view the Vermont tif as a COG in a project
* verify that its thumbnail succeeds
Closes #3682
=> Fix MODIS thumbnails

deployment/ansible/group_vars/all.yml, deployment/ansible/group_vars/jenkins.yml, deployment/ansible/roles/raster-foundry.jenkins/tasks/main.yml
* Add weekly NPM cleanup cron task
* Add weekly Maven cleanup cron task
* Add weekly Ivy cleanup cron task
* Bump Java version in Ansible to match what's installed on Jenkins instance
* Bump Docker engine version to match what's installed on Jenkins instance
Resolves azavea/raster-foundry-platform#348
From the context of the Vagrant VM:
```bash
vagrant@vagrant:/opt/raster-foundry$ eval $(ssh-agent)
Agent pid 29287
vagrant@vagrant:/opt/raster-foundry$ ssh-add raster-foundry-stg.pem
Identity added: raster-foundry-stg.pem (raster-foundry-stg.pem)
vagrant@vagrant:/opt/raster-foundry$ ansible-playbook -vv  -i deployment/ansible/inventory deployment/ansible/raster-foundry-jenkins.yml
```
Ensure the playbook completes successfully.
```bash
vagrant@vagrant:/opt/raster-foundry$ ssh …
```
=>  Add cron tasks to clean up Jenkins cache, bump versions 

app-backend/db/src/main/scala/com/azavea/rf/database/Dao.scala, app-backend/db/src/main/scala/com/azavea/rf/database/OrganizationDao.scala, app-backend/db/src/main/scala/com/azavea/rf/database/PlatformDao.scala, app-backend/db/src/main/scala/com/azavea/rf/database/SceneWithRelatedDao.scala
- Lets platform admins see user emails in platform
- Fixes pagination for organization listing in platforms
Going to merge because @alkamin and I worked on this yesterday together
=> Minor Admin Fixes

app-backend/api/src/main/scala/datasource/Routes.scala, app-backend/api/src/main/scala/uploads/QueryParameters.scala, app-backend/api/src/main/scala/utils/QueryParameters.scala, app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/QueryParameters.scala, app-backend/db/src/main/scala/com/azavea/rf/database/Dao.scala, app-backend/db/src/main/scala/com/azavea/rf/database/DatasourceDao.scala, app-backend/db/src/main/scala/com/azavea/rf/database/UploadDao.scala, app-backend/db/src/main/scala/com/azavea/rf/database/filters/Filterables.scala, app-frontend/src/app/components/datasources/datasourceDeleteModal/datasourceDeleteModal.html, app-frontend/src/app/components/datasources/datasourceDeleteModal/datasourceDeleteModal.module.js, app-frontend/src/app/components/datasources/datasourceItem/datasourceItem.html, app-frontend/src/app/components/datasources/datasourceItem/datasourceItem.module.js, app-frontend/src/app/index.components.js, app-frontend/src/app/pages/imports/datasources/list/list.controller.js, app-frontend/src/app/services/scenes/datasource.service.js, app-frontend/src/app/services/scenes/upload.service.js, app-frontend/src/assets/styles/sass/pages/_datasources.scss
This PR enables deleting datasources along with their related scenes and uploads when the following three criteria are all satisfied:
- acting user is the owner of a datasource
- no matching ACR record for such datasource
- no upload in progress is using this datasource
It also adds `Global`, `Private`, `Sharing`, `Shared` tags on datasource items on the frontend to display and differentiate datasource statuses based on ownership and access control rules.
It fixes a bug in `authTableF` method of `Dao.scala` to filter out inactive ACRs.
- ~Any content changes are properly templated …
=> Enable deleting datasources with related scenes and uploads

app-backend/datamodel/src/test/scala/com/azavea/rf/datamodel/implicits/Generators.scala, app-frontend/src/app/components/filters/shapeFilter/shapeFilter.module.js, app-frontend/src/app/pages/imports/imports.html, app-frontend/src/app/pages/projects/edit/aoi-parameters/aoi-parameters.html, app-frontend/src/app/pages/projects/edit/aoi-parameters/aoi-parameters.module.js, app-frontend/src/assets/styles/sass/components/_filter.scss, app-frontend/src/assets/styles/sass/components/_shapefilter.scss
Allow selecting existing shapes using the same component as the browse view
* Verify that you can create and select AOIs
* Verify that the shapes show up correctly on the map
* verify that saving aoi's works
Closes #3769
=> Select shapes from the aoi parameters panel

app-frontend/src/app/pages/imports/vector/vector.html
We can add them back later once we have documentation
* Verify that broken links are removed
Closes #3842
=> Remove broken links on vector page

app-backend/db/src/main/scala/com/azavea/rf/database/SceneDao.scala
Allow getMosaicDefinition to return an empty seq instead of throwing an exception when the polygon filter on scenes returns nothing
* I'm not really sure how to test this - I wasn't able to reproduce the issue, but this should fix the described problem.
Closes https://github.com/raster-foundry/raster-foundry/issues/3733
=> Handle case where polygon filter returns no scenes for mosaic

app-backend/backsplash/src/main/scala/nodes/ProjectNode.scala, app-backend/backsplash/src/main/scala/parameters/PathParameters.scala, app-backend/backsplash/src/main/scala/services/MultibandMosaicService.scala
This PR adds band query parameters for color correction without being able to update the
persisted color correction.
mooooooooooooooooooooooooooob
* make some tile requests
* copy them with different `redBand=`, `greenBand=`, `blueBand=` parameters
* watch the colors change
Closes #3902
=> Add band query parameters

app-frontend/src/app/pages/projects/edit/aoi-parameters/aoi-parameters.html, app-frontend/src/app/pages/projects/edit/aoi-parameters/aoi-parameters.module.js, app-frontend/src/app/pages/projects/edit/scenes/scenes.module.js, app-tasks/rf/src/rf/ingest/io.py, app-tasks/rf/src/rf/uploads/geotiff/utils.py, app-tasks/rf/src/rf/uploads/landsat_historical/factories.py, app-tasks/rf/src/rf/uploads/modis/create_geotiff.py
This PR makes it possible for users to pause AOIs from the UI.
This also includes a bunch of removal of INTERLEAVE=BAND and INTERLEAVE_OVERVIEW=BAND gdal options. We think maybe that's bad actually. @notthatbreezy said to throw it in here. I flychecked the python files and didn't change any other programmatic logic, so should be fine.
I'm not sure where users should have information about whether their AOIs are active, now that it's actually possible to turn something off and forget and then get confused about why you're not getting new scenes. I think that's a broader AOI UX discussion though, so :man_shrugging: 
* Create an AOI
* Watch the button pop up once the AOI exists
* Toggle it off
* Save it
* Refresh -- state should be the same
* Toggle it back on
* Save it
* Refresh -- state …
=> Add option to pause AOIs

app-backend/backsplash/src/main/scala/services/MultibandMosaicService.scala
Breaks the authIO/result out of a tupled state, so any auth errors can be handled first, before any tiles are requested.
~~- [ ] [Swagger specification](https://github.com/raster-foundry/raster-foundry-api-spec) updated~~
~~- [ ] Any content changes are properly templated using `BUILDCONFIG.APP_NAME`~~
~~- [ ] Any new SQL strings have tests~~
I made several attempts to accomplish this with the `EitherT` monad transformer, but couldn't quite get it to work out. I'd be up for pairing to flesh that out if it seems that strategy would make the code significantly cleaner.
* Create a new project, add a scene, and grab the UUID, a good X/Y/Z, and your token
* Issue a GET …
=> Unparallelize tupled auth / tile IO

app-backend/db/src/main/scala/com/azavea/rf/database/notification/templates/UploadSuccess.scala
Now that we support COG imports for MODIS and Landsat 4/5/7 the notification email text has been updated to make more sense.
Output with project:
```
api-server_1   | [info] ..........subject.............
api-server_1   | [info] A new scene has been added to your project "Another project"
api-server_1   | [info] ..........plain body..........
api-server_1   | [info]  A scene has successfully been added to your project at …
```
=> Refactor import notification copy

app-tasks/rf/src/rf/ingest/io.py, app-tasks/rf/src/rf/uploads/modis/create_geotiff.py, app-tasks/rf/src/rf/uploads/modis/factories.py, app-tasks/rf/src/rf/utils/cog.py
This PR uses common COG handling for MODIS scenes as well to obtain a higher base resolution.
Landsat 4/5/7 weren't modified, since I confirmed they're already performing as expected, modulo our
off-by-one overview error.
It's not obvious why, but we're still not getting to the actual minimum resolution available. According
to [wikipedia](https://en.wikipedia.org/wiki/Moderate_Resolution_Imaging_Spectroradiometer#MODIS_bands)
the finest resolution MODIS bands have a resolution of 250m. Our old process produced bands with about a 690m resolution. Now we're getting to about 450m. Why 450? I don't know.
* add a MODIS scene to a project
* `rf process-upload` the most recent upload
* measure the cell size at high zoom level in the lab -- should be about 900m
Closes #3996
=> Polish COG creation for MODIS

app-backend/db/src/main/scala/com/azavea/rf/database/notification/templates/UploadSuccess.scala, app-frontend/src/app/pages/projects/list/list.html
=> Fix path to project in success email

app-frontend/src/app/pages/projects/edit/aoi-approve/aoi-approve.controller.js
Pretty self-explanatory. Going to merge this once CI passes since it's trivial.
=> Filter actual list of AOI scenes to approve instead of response object

app-frontend/src/app/components/aoiFilterPane/aoiFilterPane.controller.js, app-frontend/src/app/components/aoiFilterPane/aoiFilterPane.html, app-frontend/src/app/pages/projects/list/list.controller.js, app-frontend/src/app/pages/projects/list/list.html, app-frontend/src/app/pages/user/projects/projects.html, app-frontend/src/app/pages/user/projects/projects.js
This PR:
- fixes empty project list view's html bug
- substitutes the AOI datasource filter with a component we use in browsing scenes
- fixes "Getting started with project" links on empty project list views
* Log in an account with no projects
* Go to project list view: check the styling; check that the "Getting started with project" works
* Go to account settings -> projects tab, check that the "Getting started with project" works
* Create an AOI project; adjust filters; …
=> Staging frontend fix: project list, AOI datasource filter, links

app-frontend/package.json, app-frontend/src/app/pages/projects/edit/scenes/scenes.html
This PR makes scene re-ordering work again!
Honestly, I don't know why removing this makes it work as it was previously needed to make it work... 🤷‍♂️ 
* Reorder scenes in many ways
Closes #4088
=> Fix scene re-ordering again

app-backend/backsplash/src/main/scala/nodes/ProjectNode.scala
This PR adds in missing cropping of avro tiles when the zoom level is beyond the max zoom of the source data. Without cropping tiles we were repeatedly displaying the highest resolution tile at the spatial key.
We still have an issue at zoom levels higher than 22 that is causing 400s from backsplash
* Find a nice avro landsat scene and zoom in past level 14 and notice that there are no kaleidoscope-like visualizations
Closes #3912
=> Crop over-zoomed avro tiles

app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/package.scala
This PR updates timestamp string parsing for the timestamps sent from python client.
* CI
* Pull it down to local and test this one: https://github.com/raster-foundry/raster-foundry-python-client/pull/67
=> Update timestamp string parsing

app-frontend/src/app/index.routes.js, app-frontend/src/app/pages/projects/edit/advancedcolor/advancedcolor.controller.js, app-frontend/src/app/pages/projects/edit/advancedcolor/advancedcolor.html, app-frontend/src/app/pages/projects/edit/browse/browse.module.js, app-frontend/src/app/pages/projects/edit/colormode/colormode.controller.js, app-frontend/src/app/pages/projects/edit/colormode/colormode.html, app-frontend/src/app/pages/projects/edit/edit.module.js, app-frontend/src/app/pages/projects/edit/scenes/scenes.html, app-frontend/src/app/pages/projects/edit/scenes/scenes.module.js, app-frontend/src/app/redux/reducers/project-reducer.js, app-frontend/src/app/services/projects/project.service.js, app-frontend/yarn.lock
Move some state management around and prevent ui-router from reloading the
project edit controller when changing sub-views
* Load RF and go to a project.
* Go back to the project list page and load another project with annotations
* Edit an annotation
Closes #4110
=> Fix annotation editing

CHANGELOG.md, app-tasks/rf/src/rf/uploads/planet/factories.py
Adds support for specifying which asset is desired when adding Planet imagery. This is to support some custom API work that is in progress.
- Build batch container: `docker-compose build batch`
- Update TILE\_SERVER\_LOCATION: `TILE_SERVER_LOCATION=http://localhost:9101`
- Create a project ("New Analytic Project"), import planet scene, run process upload
```
./scripts/console batch "rf process-upload <upload-id>
```
- Verify that output includes line about choosing analytic type:
```
INFO:rf.uploads.planet.factories:Requesting asset from Planet: 20180829_182546_1025, PSScene4Band
INFO:rf.uploads.planet.factories:Determining Analytics Asset Type
INFO:rf.uploads.planet.factories:Found acceptable type: analytic
INFO:rf.uploads.planet.factories:Activating asset for 20180829_182546_1025
```
- …
=> Add custom asset support to planet processing

CHANGELOG.md, app-frontend/src/app/pages/imports/raster/raster.html
Changed some text on the Imports page
=> Minor Imports page text change

CHANGELOG.md, app-frontend/src/app/pages/home/home.html
* Go to the RF home page
* Verify that the button works as expected
Closes https://github.com/azavea/raster-foundry-platform/issues/437
=> Change button from 'Create a new Template' to 'Analysis'

app-frontend/src/app/components/common/paginationCount/paginationCount.html, app-frontend/src/app/components/projects/projectItem/projectItem.html, app-frontend/src/app/components/projects/projectSelectModal/projectSelectModal.html, app-frontend/src/app/components/projects/projectSelectModal/projectSelectModal.module.js, app-frontend/src/assets/styles/sass/components/_form.scss, app-frontend/src/assets/styles/sass/components/_modal.scss, app-frontend/src/assets/styles/sass/components/_pagination.scss, app-frontend/src/assets/styles/sass/pages/_admin.scss
Restyled the project selection of the analysis project selection modals
This handles everything from issue #4314 except for filtering on ownership which I would need support on.
* open an analysis
* select a project
Closes #4314
=> updates analysis modal project selection design

CHANGELOG.md
I forgot to update the changelog on #4324
=> Update change-log for lab project select modal

CHANGELOG.md, app-backend/.dockerignore, app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/BacksplashImage.scala, app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/error/Error.scala, app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/AnalysisService.scala, app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Authorizers.scala, app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Error.scala, app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Main.scala, app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/MamlAdapter.scala, app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/MosaicService.scala, app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/ProjectStoreImplicits.scala, app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/ToolStoreImplicits.scala, app-backend/batch/src/test/scala/com/azavea/rf/batch/export/model/ExportDefinitionSpec.scala, app-backend/build.sbt, app-backend/datamodel/src/main/scala/MosaicDefinition.scala, app-backend/datamodel/src/main/scala/SceneToProject.scala, app-backend/db/src/main/scala/SceneDao.scala, app-backend/db/src/main/scala/SceneToProjectDao.scala, app-backend/db/src/main/scala/ToolRunDao.scala
This is the same as #4390, but I'm trying to help Jenkins out by giving it a fresh workspace.
* make some requests without tokens and with tokens for projects that don't exist
* they should return the expected statuses
=> Restore authentication, authorization, and error-handling

app-tasks/rf/src/rf/commands/reprocess_sentinel.py
=> Fix scoping issue for scene reprocess

app-tasks/rf/src/rf/commands/reprocess_sentinel.py
Trivial, merging. Hope this is the last one...
=> Remove trailing comma in reprocess script

CHANGELOG.md, docker-compose.test.yml, gatling/src/test/scala/MosaicTmsSimulation.scala, scripts/cigatling
This avoids permissions issues. Also, syncs the results directly to S3
for viewing once they are complete.
* Run a test in CI with default build parameters
=> Use docker-compose for running gatling tests in CI

CHANGELOG.md, app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/BacksplashImage.scala, app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/BacksplashMosaic.scala, app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/HistogramStore.scala, app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/MosaicImplicits.scala, app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/color/ColorCorrect.scala, app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/color/ColorRampMosaic.scala, app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/HistogramStoreImplicits.scala, app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/MosaicService.scala, app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/ProjectStoreImplicits.scala, app-backend/db/src/main/scala/LayerAttributeDao.scala
First pass at fixing single band color mosaics, still very much a WIP and just really testing at this point.
=> Fix Single Band Mosaics

CHANGELOG.md, app-backend/backsplash-core/src/main/resources/reference.conf, app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/Cache.scala, app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/Config.scala, app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/MosaicImplicits.scala, app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/ProjectStoreImplicits.scala, app-backend/build.sbt
Switches to using memcached for tile caching.
=> Add memcached support

CHANGELOG.md, app-backend/api/src/main/scala/project/Routes.scala, app-frontend/package-lock.json
This PR adds the following endpoints:
- Get Layer Mosaic Definition                                                                                                                                                                                      
- Get Scene Layer Color Corrections                                                                                                                                                                                
- Update Scene Layer Color Corrections                                                                                                                                                                             
- Bulk Update Scene Layer Color Corrections …
=> Add project layer mosaic endpoints

app-frontend/src/app/components/common/search/search.html, app-frontend/src/app/components/permissions/permissionModal/permissionModal.html, app-frontend/src/app/components/permissions/permissionModal/permissionModal.js
This PR closes some div tags that were causing parts of the modal not to be displayed
* Ensure you can now use the permissions modal to grant permissions
Closes #4559
=> Fix unclosed div tags in permissions modal

app-backend/api/src/main/scala/project/Routes.scala, app-backend/db/src/main/scala/ProjectLayerDao.scala, app-frontend/src/app/components/lab/labNode/labNode.module.js, app-frontend/src/app/components/pages/index.js, app-frontend/src/app/components/pages/project/index.js, app-frontend/src/app/components/pages/project/layers/index.html, app-frontend/src/app/components/pages/project/layers/index.js, app-frontend/src/app/components/pages/project/project/index.html, app-frontend/src/app/components/pages/project/project/index.js, app-frontend/src/app/components/projects/index.js, app-frontend/src/app/components/projects/layerItem/index.html, app-frontend/src/app/components/projects/layerItem/index.js, app-frontend/src/app/components/projects/projectItem/projectItem.module.js, app-frontend/src/app/components/settings/tokenItem/tokenItem.module.js, app-frontend/src/app/index.components.js, app-frontend/src/app/index.routes.js, app-frontend/src/app/pages/lab/analysis/analysis.js, app-frontend/src/app/pages/projects/edit/edit.html, app-frontend/src/app/pages/projects/edit/edit.module.js, app-frontend/src/app/pages/projects/edit/sharing/sharing.module.js, app-frontend/src/app/pages/share/share.controller.js, app-frontend/src/app/services/projects/project.service.js, app-frontend/src/assets/styles/sass/_shame.scss, app-frontend/src/assets/styles/sass/layout/_container.scss, app-frontend/src/assets/styles/sass/layout/_navbar.scss
Add a project layer list view
Paginated project layer list endpoint
- ~Description of PR is in an appropriate section of the [changelog](https://github.com/raster-foundry/raster-foundry/blob/develop/CHANGELOG.md) and grouped with similar changes if possible~ Changelog will be updated when we swap from the old routes to the new routes
- ~[Swagger specification](https://github.com/raster-foundry/raster-foundry-api-spec) updated~ No swagger spec for project layers endpoints yet
- ~Any new SQL strings have tests~ There are no tests in ProjectDaoSpec for these methods and ProjectLayerDoaSpec doesn't exist …
=> Add project layer list view

app-lambda/rflambda/landsat8/new_landsat8_event.py, scripts/load_development_data
- Fixes reliance on `postgres` user to setup development environment
- Fixes parsing of SNS Landsat 8 event
* Remove docker images and containers for postgres (to force it to redownload)
* Rerun `./scripts/load_development_data`
Lambda is harder to test here, the screenshot above shows that it worked against a test event now though.
=> Minor Development + Lambda Fixes

app-tasks/rf/src/rf/commands/export.py, docker-compose.yml
Fix the path used for the jar in the path of the CLI
=> Update path in `rf` CLI for jar path

CHANGELOG.md, app-backend/api/src/main/scala/toolrun/Routes.scala, app-backend/common/src/main/scala/datamodel/ToolRun.scala, app-backend/db/src/main/scala/ObjectPermissions.scala, app-backend/db/src/main/scala/ToolRunDao.scala, app-backend/db/src/test/scala/com/azavea/rf/database/ToolRunDaoSpec.scala, app-frontend/src/app/components/pages/project/analyses/analyses/index.html, app-frontend/src/app/components/pages/project/analyses/analyses/index.js, app-frontend/src/app/components/pages/project/layers/index.html, app-frontend/src/app/components/pages/project/layers/index.js, app-frontend/src/app/components/projects/layerItem/index.html, app-frontend/src/app/components/projects/layerItem/index.js, app-frontend/src/app/services/analysis/analysis.service.js, app-frontend/src/app/services/projects/project.service.js, app-frontend/src/assets/styles/sass/_shame.scss
This PR:
- adds project analysis list UI
- updates analysis list endpoint to return analysis info with related project layer info and template info if `projectId` QP is passed in
- updates `ToolRunDao` and added property tests for new sql
For features in the actions list -- only the delete action is fully implemented. The settings actions redirects to a link, which does not have page content yet.
* Go to lab
* Create an analysis named with `<projectLayerName - Date>` (or not, this is just to mock an analysis …
=> Add project analyses list view

app-backend/db/src/main/scala/ExportDao.scala
Fixes a bug where we were not generating enough parameters when we had a single project using multiple bands.
Old export definition
```
{
"id": "ac0b2e7a-084d-4836-b595-0e00d46f18e4",
"src": {
"zoom": 9,
"area": {
"type": "MultiPolygon",
"coordinates": [
[
[
[
-14.436457,
25.467531
],
[
-14.436457,
26.470093999999996
],
[
-13.494374999999998,
26.470093999999996
],
[
-13.494374999999998,
25.467531
],
[
-14.436457,
25.467531
]
]
]
]
},
"ast": {
"args": [
{
"args": [
{
"name": "631a99a0-c43f-4c3f-80ca-0d5df7359b5a_4",
"symbol": "rasterV"
},
{
"name": "631a99a0-c43f-4c3f-80ca-0d5df7359b5a_3",
"symbol": "rasterV"
}
],
"symbol": "-"
},
{
"args": [
{
"name": "631a99a0-c43f-4c3f-80ca-0d5df7359b5a_4",
"symbol": "rasterV"
},
{
"name": "631a99a0-c43f-4c3f-80ca-0d5df7359b5a_3",
"symbol": "rasterV"
} …
```
=> Fix Analysis Export Definition Creation

app-backend/backsplash-server/src/main/resources/application.conf, app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Config.scala, docker-compose.java.yml
@notthatbreezy said we're not using it any longer and the metrics code has been removed.
See CI checks pass.
=> Remove graphite

CHANGELOG.md, app-backend/api/src/main/scala/exports/QueryParameters.scala, app-backend/common/src/main/scala/datamodel/QueryParameters.scala, app-backend/db/src/main/scala/filters/Filterables.scala, app-backend/migrations/src/main/scala/migrations/167.scala, app-backend/migrations/src/main/scala/migrations/Summary.scala, app-backend/migrations/src_migrations/main/scala/167.scala, app-frontend/src/app/components/pages/project/layer/exports/index.html, app-frontend/src/app/components/pages/project/layer/exports/index.js, app-frontend/src/app/components/projects/layerItem/index.html, app-frontend/src/app/components/projects/layerItem/index.js, app-frontend/src/app/components/projects/projectLayerSecondaryNavbar/index.html, app-frontend/src/app/components/projects/selectedActionsBar/index.html, app-frontend/src/app/index.routes.js, app-frontend/src/app/pages/projects/edit/exports/exports.controller.js, app-frontend/src/app/services/projects/export.service.js, app-frontend/src/app/services/projects/project.service.js, app-frontend/src/assets/styles/sass/_shame.scss
This PR:
- adds a migration to populate `project_layer_id` field of `exports` table using corresponding project's default layer id
- adds a `layer` QP to export list endpoint
- modifies v1 project export list UI so that it passes project default layer id in addition to project id to get exports from the default layer
- adds v2 project export list UI and enables:
* export download
* export deletion
* view export's AOI
* Run migrations
* `./scripts/console sbt` and then `api/assembly`, `batch/assembly`, `backsplash-server/assembly`
* `docker-compose build batch`
* Go to v1 UI and create some exports
* Go to v2 UI …
=> Add layer export list UI

app-tasks/rf/requirements.txt
=> Add explicit six dependency

CHANGELOG.md, app-backend/api/src/main/scala/project/ProjectLayerRoutes.scala, app-backend/api/src/main/scala/project/Routes.scala, app-frontend/src/app/components/pages/project/layer/colormode/index.html, app-frontend/src/app/components/pages/project/layer/colormode/index.js, app-frontend/src/app/services/projects/colorCorrect.service.js, app-frontend/src/app/services/projects/project.service.js, app-frontend/src/assets/styles/sass/_shame.scss, app-frontend/src/assets/styles/sass/layout/_sidebar.scss
This PR implements the project layer color mode UI.
Until #4510 is complete, the single-band color mode option is not enabled.
In order to save the color mode, an endpoint for project layer color modes was also implemented.
This PR is probably best reviewed with each commit individually.
There are three other issues very relevant to this PR:
#4510 - moving singleband options to layers
#4704 - completing the project layer color correction UI
#4705 - enabling the singleband color-mode within the UI
Change the color mode of a scene. Try this with a few different datasources. Ensure that the color modes of different layers within the project are independent.
Closes #4538
=> Project layer color mode UI

CHANGELOG.md, app-frontend/src/app/components/pages/project/layer/aoi/index.html, app-frontend/src/app/components/pages/project/layer/aoi/index.js, app-frontend/src/app/components/pages/project/layers/index.html, app-frontend/src/app/components/pages/project/layers/index.js, app-frontend/src/app/components/projects/aoiDrawToolbar/index.html, app-frontend/src/app/components/projects/aoiDrawToolbar/index.js, app-frontend/src/app/components/projects/index.js, app-frontend/src/app/components/projects/layerItem/index.html, app-frontend/src/app/components/projects/layerItem/index.js, app-frontend/src/app/services/projects/project.service.js, app-frontend/src/assets/styles/sass/_shame.scss, app-frontend/src/assets/styles/sass/layout/_navbar.scss
~**Added WIP tag to fix the known bugs**~
This PR adds AOI creation UI and a reusable component with a secondary bar that has map draw and edit handlers along with confirm and cancel buttons, so that, together, they enable:
- draw, edit, delete AOIs
- view, edit, apply existing AOIs of other layers in the same project, or AOIs stored in user's vector data
- save AOI as vector data for later use in the app
1. Create an AOI
2. Modify an AOI
3. Redraw and AOI
3. Choose an AOI …
=> Add AOI create UI and component

app-frontend/src/app/components/pages/project/analyses/analyses/index.html, app-frontend/src/assets/styles/sass/base/_helpers.scss
This PR removes the css conflicts for the css `disabled-overlay` class which caused disabled color-correction filters to be displayed incorrectly.
=> Remove css conflicts for disabled-overlay

CHANGELOG.md, app-frontend/src/app/components/lab/diagramContainer/diagramContainer.module.js, app-frontend/src/app/components/lab/inputNode/inputNode.html, app-frontend/src/app/components/lab/inputNode/inputNode.module.js, app-frontend/src/app/components/lab/labNode/labNode.html, app-frontend/src/app/components/lab/labNode/labNode.module.js, app-frontend/src/app/components/projects/index.js, app-frontend/src/app/components/projects/projectItem/projectItem.html, app-frontend/src/app/components/projects/projectItem/projectItem.module.js, app-frontend/src/app/components/projects/projectLayerItem/index.html, app-frontend/src/app/components/projects/projectLayerItem/index.js, app-frontend/src/app/components/projects/projectLayerSelectModal/index.html, app-frontend/src/app/components/projects/projectLayerSelectModal/index.js, app-frontend/src/app/components/projects/projectSelectModal/projectSelectModal.html, app-frontend/src/app/components/projects/projectSelectModal/projectSelectModal.module.js, app-frontend/src/app/pages/admin/organization/projects/projects.html, app-frontend/src/app/pages/admin/platform/projects/projects.html, app-frontend/src/app/pages/admin/team/projects/projects.html, app-frontend/src/app/pages/projects/list/list.html, app-frontend/src/app/pages/user/projects/projects.html, app-frontend/src/app/services/analysis/labUtils.service.js, app-frontend/src/app/services/map/mapUtils.service.js, app-frontend/src/app/services/projects/project.service.js, app-frontend/src/assets/styles/sass/_shame.scss
This PR:
- enables layer selection in lab
- updates lab node display to include nodes with type `layerSrc`
- reuses project select modal to allow users to select a layer after selecting a project
- updates project item component to map project layers as well
- updates project service to include getting layer scene statuses
A fresh analysis:
Select project layer based on project selection:
View results generated from picked projects, layers, and bands:
* Create a project with …
=> Enable lab layer selection

app-backend/common/src/test/scala/com/azavea/rf/datamodel/implicits/Generators.scala, app-backend/db/src/main/scala/ProjectDao.scala, app-backend/db/src/main/scala/ProjectLayerScenesDao.scala, app-backend/db/src/test/scala/com/azavea/rf/database/AnnotationDaoSpec.scala, app-backend/db/src/test/scala/com/azavea/rf/database/AnnotationGroupDaoSpec.scala, app-backend/db/src/test/scala/com/azavea/rf/database/AoiDaoSpec.scala, app-backend/db/src/test/scala/com/azavea/rf/database/DBTestConfig.scala, app-backend/db/src/test/scala/com/azavea/rf/database/DatasourceDaoSpec.scala, app-backend/db/src/test/scala/com/azavea/rf/database/ImageDaoSpec.scala, app-backend/db/src/test/scala/com/azavea/rf/database/OrganizationDaoSpec.scala, app-backend/db/src/test/scala/com/azavea/rf/database/PlatformDaoSpec.scala, app-backend/db/src/test/scala/com/azavea/rf/database/ProjectDaoSpec.scala, app-backend/db/src/test/scala/com/azavea/rf/database/ProjectDatasourcesDaoSpec.scala, app-backend/db/src/test/scala/com/azavea/rf/database/ProjectLayerDaoSpec.scala, app-backend/db/src/test/scala/com/azavea/rf/database/ProjectLayerDatasourceDaoSpec.scala, app-backend/db/src/test/scala/com/azavea/rf/database/ProjectLayerScenesDaoSpec.scala, app-backend/db/src/test/scala/com/azavea/rf/database/ProjectScenesDaoSpec.scala, app-backend/db/src/test/scala/com/azavea/rf/database/PropTestHelpers.scala, app-backend/db/src/test/scala/com/azavea/rf/database/SceneDaoSpec.scala, app-backend/db/src/test/scala/com/azavea/rf/database/SceneToLayerDaoSpec.scala, app-backend/db/src/test/scala/com/azavea/rf/database/SceneToProjectDaoSpec.scala, app-backend/db/src/test/scala/com/azavea/rf/database/SceneWithRelatedDaoSpec.scala, app-backend/db/src/test/scala/com/azavea/rf/database/ShapeDaoSpec.scala, app-backend/db/src/test/scala/com/azavea/rf/database/TeamDaoSpec.scala, app-backend/db/src/test/scala/com/azavea/rf/database/ThumbnailDaoSpec.scala, app-backend/db/src/test/scala/com/azavea/rf/database/ToolDaoSpec.scala, app-backend/db/src/test/scala/com/azavea/rf/database/ToolRunDaoSpec.scala, app-backend/db/src/test/scala/com/azavea/rf/database/UserDaoSpec.scala, app-backend/db/src/test/scala/com/azavea/rf/database/UserGroupRoleDaoSpec.scala
This PR makes platforms not come from some mysterious source loaded up from `load_development_data` and untangles the unholy maze of flatmaps. It does not fix deadlocks in any consistent way.
none of these apply
At least now when we stare at tests with no idea what's causing random deadlocks, we'll be able to read more of the code without glaring lasers back in time at past me. Separate issue opened for my best guess about next steps.
* run ci like a hundred times
Closes #4249 
Closes #4610
=> Make tests more readable and explicit

CHANGELOG.md, app-frontend/src/app/components/common/listItemWidgets/listItemActions/index.html, app-frontend/src/app/components/common/listItemWidgets/listItemActions/index.js, app-frontend/src/app/components/common/listItemWidgets/listItemSelector/index.html, app-frontend/src/app/components/common/listItemWidgets/listItemSelector/index.js, app-frontend/src/app/components/histogram/histogramBreakpoint/histogramBreakpoint.html, app-frontend/src/app/components/histogram/histogramBreakpoint/histogramBreakpoint.module.js, app-frontend/src/app/components/histogram/index.js, app-frontend/src/app/components/histogram/nodeHistogram/nodeHistogram.module.js, app-frontend/src/app/components/histogram/quickEditHistogram/index.html, app-frontend/src/app/components/histogram/quickEditHistogram/index.js, app-frontend/src/app/components/pages/project/analyses/analyses/index.html, app-frontend/src/app/components/pages/project/analyses/analyses/index.js, app-frontend/src/app/components/pages/project/analyses/index.js, app-frontend/src/app/components/pages/project/analyses/quickedit/index.html, app-frontend/src/app/components/pages/project/analyses/quickedit/index.js, app-frontend/src/app/components/pages/project/createAnalysis/index.js, app-frontend/src/app/components/pages/project/layers/index.js, app-frontend/src/app/components/pages/project/project/index.html, app-frontend/src/app/components/projects/analysisEditModal/index.html, app-frontend/src/app/components/projects/analysisEditModal/index.js, app-frontend/src/app/components/scenes/sceneImportModal/sceneImportModal.controller.js, app-frontend/src/app/index.components.js, app-frontend/src/app/index.routes.js, app-frontend/src/app/services/analysis/analysis.service.js, app-frontend/src/app/services/common/graph.service.js, app-frontend/src/assets/styles/sass/_shame.scss, app-frontend/src/assets/styles/sass/base/_helpers.scss, app-frontend/src/assets/styles/sass/components/_button.scss, app-frontend/src/assets/styles/sass/layout/_main.scss
Allow clicking an analysis in the project analyses view to adjust color maps on a histogram and view more details about the parameter types.
* Create a new analysis from the project layers view
* Go to the project analyses page and click the analysis you just created
* Verify that there is an error shown on the histogram
* Adjust the parameters and verify that the histogram now shows and is accurate
* Verify that you can input numbers outside the range of the histogram to …
=> Click to select analysis and edit histogram, input parameters

app-frontend/src/app/components/projects/projectPublishModal/projectPublishModal.html, app-frontend/src/assets/styles/sass/_shame.scss, app-frontend/src/assets/styles/sass/components/_form.scss
**Before**
**After**
- Open project publishing modal from projects list page
Closes #4725
=> fix radio button visual regression

CHANGELOG.md, app-frontend/.prettierrc, app-frontend/src/app/components/pages/project/analyses/analyses/index.html, app-frontend/src/app/components/pages/project/createAnalysis/index.html, app-frontend/src/app/components/pages/project/createAnalysis/index.js, app-frontend/src/app/components/pages/project/layer/annotations/index.html, app-frontend/src/app/components/pages/project/layer/aoi/index.html, app-frontend/src/app/components/pages/project/layer/aoi/index.js, app-frontend/src/app/components/pages/project/layer/colormode/index.html, app-frontend/src/app/components/pages/project/layer/corrections/index.html, app-frontend/src/app/components/pages/project/layer/export/index.js, app-frontend/src/app/components/pages/project/layer/exports/index.html, app-frontend/src/app/components/pages/project/layer/scenes/browse/index.html, app-frontend/src/app/components/pages/project/layer/scenes/scenes/index.html, app-frontend/src/app/components/pages/project/layers/index.html, app-frontend/src/app/components/pages/project/settings/embed/index.html, app-frontend/src/app/components/pages/project/settings/publishing/index.html, app-frontend/src/app/components/pages/share/layers/index.html, app-frontend/src/app/components/projects/aoiDrawToolbar/index.html, app-frontend/src/app/components/projects/aoiDrawToolbar/index.js, app-frontend/src/app/pages/projects/edit/advancedcolor/advancedcolor.html, app-frontend/src/assets/styles/sass/_shame.scss, app-frontend/src/assets/styles/sass/components/_button.scss, app-frontend/src/assets/styles/sass/components/_form.scss, app-frontend/src/assets/styles/sass/layout/_navbar.scss, app-frontend/src/assets/styles/sass/layout/_sidebar.scss
This PR cleans up the project-layer UI in a few ways:
Styling the project layer analysis creation page
Using layer start and end dates where available otherwise not showing a date on layer items
Fixing style of the list action header to be more visibly separated from a list of things when scrolling and unifies button size usage within:
Allows clicking on project-layer names to go to the layer:
Updates the layer AOI UI to require less clicks:
Added a new button class `btn-lightest` which uses existing color variables, so it is theme-safe.
Testing this is a little hard, because it is mostly about trying to find style regressions.
* Click around the v2 front-end and make sure there are no noticeably broken styles
* Try clicking on the name of project layers to go to the layer
* Create an …
=> Project layer UI cleanup

docs/architecture/adr-0025-user-access-scopes.md
[Rendered](https://github.com/raster-foundry/raster-foundry/blob/50e35994b975ad364a99a6fc0bcfe13e602bdf19/docs/architecture/adr-0025-user-access-scopes.md)
Open for comments.
Closes #4912
=> ADR-0025 - User Access Scopes

app-backend/api/src/main/scala/utils/QueryParameters.scala, app-backend/datamodel/src/main/scala/QueryParameters.scala
Fixes a typo in the task query parameters.
CI should be sufficient for testing.
=> Fix lockedBy query parameter type

app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/implicits/OgcImplicits.scala
This PR adds parallelism to the places where it was missing in the rendering pipeline for OGC tile endpoints. It turns out we'd already added it in one of the places mentioned, and there's nowhere else to add it after the other two.
~I'm working on better testing instructions with visualvm (I got this nice new :hammer:, so...), though this will then depend on #5056~
I'm interpreting the Visual VM observations below as evidence that we're more efficiently using the available threads. That might be a reach? I don't know. It's sort of tough to tell with this sort of thing. I'm opening a separate issue to add wms to the load test... which we still need to fix. raster-foundry/load-testing#5, raster-foundry/load-testing#6
- set `ENABLE_GDAL` to false in docker-compose for backsplash
- assemble …
=> Make mosaic raster source construction more parallel

CHANGELOG.md, app-backend/batch/src/main/scala/Main.scala, app-backend/batch/src/main/scala/package.scala, app-backend/batch/src/main/scala/stacExport/ContentBundle.scala, app-backend/batch/src/main/scala/stacExport/LabelCollectionBuilder.scala, app-backend/batch/src/main/scala/stacExport/LayerCollectionBuilder.scala, app-backend/batch/src/main/scala/stacExport/SceneCollectionBuilder.scala, app-backend/batch/src/main/scala/stacExport/StacCatalogBuilder.scala, app-backend/batch/src/main/scala/stacExport/StacExtent.scala, app-backend/batch/src/main/scala/stacExport/StacItemBuilder.scala, app-backend/batch/src/main/scala/stacExport/WriteStacCatalog.scala, app-backend/batch/src/main/scala/stacImport/ReadStacFeature.scala, app-backend/build.sbt, app-backend/common/src/test/scala/com/implicits/Generators.scala, app-backend/datamodel/src/main/scala/Annotation.scala, app-backend/datamodel/src/main/scala/StacExport.scala, app-backend/datamodel/src/main/scala/StacLabelItemProperties.scala, app-backend/datamodel/src/main/scala/Task.scala, app-backend/db/src/main/resources/migrations/V12__Add_stac_export_table.sql, app-backend/db/src/main/scala/AnnotationDao.scala, app-backend/db/src/main/scala/ProjectDao.scala, app-backend/db/src/main/scala/ProjectLayerDao.scala, app-backend/db/src/main/scala/ProjectLayerScenesDao.scala, app-backend/db/src/main/scala/StacExportDao.scala, app-backend/db/src/main/scala/TaskDao.scala, app-backend/db/src/test/scala/com/azavea/rf/database/AnnotationDaoSpec.scala, app-backend/db/src/test/scala/com/azavea/rf/database/StacExportDaoSpec.scala
This branch contains the work in progress batch job
- How to test this PR
- Prefer bulleted description
- Start after checking out this branch
- Include any setup required, such as bundling scripts, restarting services, etc.
- Include test case, and expected output
Closes #5057 
Closes #5086
=> Add STAC Export Builder in Batch

CHANGELOG.md, app-backend/api/src/main/scala/stac/Routes.scala, app-backend/common/src/main/resources/reference.conf, app-backend/common/src/main/scala/AWSBatch.scala, app-backend/common/src/main/scala/Config.scala
This PR enables kicking off STAC export job when an export record is created through the `POST` endpoint.
There are two lines of `println`s in `AWSBatch` trait, since debug level logging did not work for me locally. I will remove these two `println`s before merging.
- Pull down the `.env` file from S3, which is updated with `BATCH_JOB_NAME_STAC_EXPORT=jobStagingStacExport`
- Assemble api jar
- `POST` to `/api/stac` with the following:
```json
{
"name": "AL project test",
"layerDefinitions": [
{
"projectId": "7e584c31-f5d1-4a02-9428-e83006642375",
"layerId": …
```
=> Kick off label STAC export

CHANGELOG.md
Forgot to update it in the last PR
=> Update changelog from pr 5187

CHANGELOG.md, app-backend/common/src/main/scala/com/rasterfoundry/common/SceneToLayer.scala, app-backend/db/src/main/scala/ProjectDao.scala, app-backend/db/src/main/scala/ProjectLayerDao.scala, app-backend/db/src/main/scala/SceneDao.scala, app-backend/db/src/main/scala/SceneToLayerDao.scala, app-backend/db/src/main/scala/util/Cache.scala
One of the most common DB queries we perform during a tile request is to get the `MosaicDefinition` - a list of scenes filtered optionally by a subset of IDs, polygon, and ingest status. This PR adjust the logic for this query to push the polygon and scene subset portion of the filters to the application and caches essentially _all_ the scenes in a project layer rather than hit the database for every tile request. The hope is this significantly reduces the load on the database and eliminates one of the most common slow queries we see under high load.
I would prefer to bust the cache key when there are  updates to the mosaic definition -- but I couldn't come up with a good strategy. So for now I added deletes of the cache keys everywhere I could think of through testing.
- Get a JWT Token …
=> Add MosaicDefinition Cache to SceneToLayerDao

app-backend/datamodel/src/main/scala/AnnotationProjectStatus.scala, app-tasks/rf/src/rf/commands/process_upload.py
see title
Changed "status" to "progressStage" inside the status object, since `status: {"status": ...}` is silly
- Verify it builds
- Verify that processing uploads works like we should have tested in https://github.com/raster-foundry/raster-foundry/pull/5350
=> Fix annotation project deserializer and process_upload.py

app-backend/build.sbt, app-backend/project/Dependencies.scala, app-backend/project/ci/repositories, app-backend/project/development/repositories
Upgrades GeoTrellis to fix a bug related to seams showing on higher zoom levels beyond native resolution
- Open up some imagery, zoom in a bit - there shouldn't be any seams
Closes #5441
=> Upgrade GeoTrellis

CHANGELOG.md, Jenkinsfile, app-backend/api/src/main/scala/scene/Routes.scala, app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/BacksplashGeotiffReader.scala, app-backend/batch/src/main/scala/cogMetadata/HistogramBackfill.scala, app-backend/build.sbt, app-backend/common/src/main/scala/utils/CogUtils.scala
- How to test this PR
- Prefer bulleted description
- Start after checking out this branch
- Include any setup required, such as bundling scripts, restarting services, etc.
- Include test case, and expected output
Closes #XXX
=> Improve metadata gathering on scenes POST

CHANGELOG.md
I forgot to commit this in #5477 
Closes #XXX
I'll merge post-CI
=> Include missing changelog entry

CHANGELOG.md, app-backend/api/src/main/scala/annotation-project/AnnotationProjectTaskRoutes.scala, app-backend/api/src/main/scala/annotation-project/Routes.scala
This endpoint replicates previous behavior and does not delete labels like the PUT version of these endpoints do
1. Get a bearer token and export it to the environment variable `JWT_AUTH_TOKEN`: `export JWT_AUTH_TOKEN=<bearer>`
2. Request the labels for a task in an annotation project and count the number of labels:
`http :9000/api/annotation-projects/6e35b51e-4d67-4cb0-bf23-ca265ef49b24/tasks/389efee3-7e4b-43c9-9fd7-a3a62b0c4751/labels --auth-type=jwt | jq length`
3. Add a label to the annotation project task via a `POST`:
`echo '{"type":"FeatureCollection","features":[{"geometry":{"coordinates":[[[-87.67115299999999,34.769519],[-87.671085,34.769523],[-87.671086,34.76949799999999],[-87.67115399999999,34.769494999999985],[-87.67115299999999,34.769519]]],"type":"Polygon"},"id":"ff4d95d1-8b4 …
=> Add POST endpoint for adding/validating labels

CHANGELOG.md, Jenkinsfile, app-backend/http4s-util/src/main/resources/reference.conf, app-backend/http4s-util/src/main/scala/com/rasterfoundry/http4s/Config.scala, app-backend/http4s-util/src/main/scala/com/rasterfoundry/http4s/xray/Segment.scala, app-backend/http4s-util/src/main/scala/com/rasterfoundry/http4s/xray/UdpClient.scala, app-backend/http4s-util/src/main/scala/com/rasterfoundry/http4s/xray/XRayTracingContext.scala, app-backend/project/Dependencies.scala, app-backend/sbt
Add `XRAY_HOST` environment variable in the `http4s-util` subproject and use it to parameterize the X-Ray daemon address in `UdpClient`.
Also, conditionally add the EC2 metadata to tracing segments.
Connects https://github.com/azavea/raster-foundry-platform/issues/1139
Mess around with the staging site and see that Backsplash traces are available in the X-Ray console with ECS metadata.
=> Support X-Ray on Fargate

CHANGELOG.md, app-backend/db/src/main/scala/CampaignDao.scala
This PR fixes a bug in the campaign label class summary endpoint so that it does not return 500 error when no image is attached to the campaign.
- Assemble api server jar, spin up servers, and grab a token
- Run the following to create a campaign with no annotation projects attached:
```
curl --location --request POST 'http://localhost:9091/api/campaigns' \
--header 'Authorization: Bearer <token>' \
--data-raw '{
"name": "test campaign",
"campaignType": …
```
=> Fix campaign label class summary endpoint

CHANGELOG.md, app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/BacksplashImage.scala, app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/MosaicImplicits.scala, app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/Parameters.scala, app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/RenderableStore.scala, app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/MamlAdapter.scala, app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/implicits/RenderableStoreImplicits.scala, app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/services/MosaicService.scala, app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/services/SceneService.scala, app-backend/common/src/main/scala/com/rasterfoundry/common/color/ColorCorrect.scala
This PR:
- updates the default color clipping bounds for the auto color correction
- exposes params to set the min/max bounds of color correction on scene rendering
Should we do something special to the decoder of the QPs so that they can only be in range `[0, 99]`? Looks like numbers out of this range can return 500 errors: https://azavea.slack.com/archives/C089LBS6S/p1617742515025900
- Push a `test` branch up
- Grab a spacenet image's S3 location (but can be any image, taking spacenet here as an …
=> Update default color space clipping and expose QPs for tuning

CHANGELOG.md, app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Main.scala, app-backend/db/src/main/scala/TaskDao.scala
This PR adds some additional logging to the task unlocker that will help us figure out when locked task unlocking isn't cooperating.
- no test needed, just look at the new log and confirm it would help you debug issues with stuck tasks if it was present
Closes azavea/raster-foundry-platform#1303
=> Log stuck locked tasks in task unlocker

CHANGELOG.md, app-backend/db/src/main/resources/migrations/V79__add_missing_user_fk_indices.sql
This PR adds indices for all user foreign key relationships. I think this should help with the big user delete in progress. I think.
If it doesn't, and this is just a long costly thing, then that's ok, but it wasn't super difficult to go through and find the missing ones and maybe it will be helpful someday in the future for other reasons. 🤷🏻‍♂️
The list of references to the users table is like this:
```
Referenced by:
TABLE "access_control_rules" CONSTRAINT "access_control_rules_created_by_fkey" FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
TABLE "annotation_groups" CONSTRAINT "annotation_groups_created_by_fkey" FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
TABLE "annotation_labels" CONSTRAINT "annotation_labels_created_by_fkey" FOREIGN KEY …
```
=> Create indices for all user fk relationships

CHANGELOG.md, app-backend/api/src/main/scala/annotation-project/AnnotationProjectTaskRoutes.scala, app-backend/api/src/main/scala/hitl-jobs/Routes.scala, app-backend/api/src/main/scala/utils/QueryParameters.scala, app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/services/AnnotationProjectMVTService.scala, app-backend/common/src/test/scala/com/implicits/Generators.scala, app-backend/datamodel/src/main/scala/AnnotationLabel.scala, app-backend/datamodel/src/main/scala/QueryParameters.scala, app-backend/db/src/main/resources/migrations/V84__Add_hitl_version_id_to_labels.sql, app-backend/db/src/main/scala/AnnotationLabelDao.scala, app-backend/db/src/main/scala/HITLJobDao.scala, app-backend/db/src/main/scala/MVTLayerDao.scala, app-backend/db/src/main/scala/TaskSessionDao.scala, app-backend/db/src/test/scala/com/azavea/rf/database/AnnotationLabelDaoSpec.scala, scripts/cipublish
This PR:
- add `hitl_version_id` to `annotation_labels`
- updates the related data models and dao methods
- updates and add MVT endpoints
- Will go through this in pairing
Closes https://github.com/azavea/foss4g-2022-hitl-groundwork-rastervision/issues/5
Closes https://github.com/azavea/foss4g-2022-hitl-groundwork-rastervision/issues/6
=> Add HITL version to Annotation Label

CHANGELOG.md, app-hitl/hitl/src/hitl/commands/run_hitl.py, app-hitl/hitl/src/hitl/utils/merge_labels.py, app-hitl/hitl/src/hitl/utils/persist_hitl_output.py, app-hitl/hitl/src/hitl/utils/post_process.py
Adds postprocessing steps to the `run_hitl` command
- create a hitl project, get the ID
- rebuild the container `docker compose build batch-hitl`
- run the hitl command `docker-compose run batch-hitl hitl run {hitl project id}`
=> Add hitl postprocessing
