raster-foundry/raster-foundry

- scripts/test.sh
- scripts/vagrant-up.sh
- src/rf/rf/settings/test.py
The following changes were made in order to fix the Jenkins build:
- Remove reference to sbo_selenium
- Remove reference to worker VM in Jenkins wrapper script
- Add stub test.sh that always passes
> Fix Jenkins build

- src/rf/apps/core/context_processors.py
- src/rf/apps/home/templates/base.html
- src/rf/apps/home/views.py
- src/rf/js/src/app.js
- src/rf/js/src/home/controllers.js
- src/rf/js/src/user/controllers.js
- src/rf/rf/settings/base.py
This removes the user fetch request that occurs every time you switch
between views. The delayed fetch would sometimes cause a noticable
"flash" as the Library would load for a split second before being
replaced by the login screen (if not authenticated).
The user model is bootstrapped with data embedded in the HTML harness.
> Remove user ping

- src/rf/js/src/home/components/modals.js
To test, try adding a some files and then hitting continue. This should make the files upload. Then close the modal, and try it again.
Connects #85
> Make upload work by preventing default action

- src/rf/apps/home/views.py
This should fix the problem with not being able to make AJAX requests after deleting the CSRF token cookie.
> Send CSRF token on app reload

- src/rf/apps/home/urls.py
- src/rf/apps/user/urls.py
- src/rf/apps/user/views.py
- src/rf/js/src/routes.js
- src/rf/js/src/user/components.js
- src/rf/js/src/user/controllers.js
- src/rf/js/src/user/models.js
- src/rf/templates/registration/password_reset_email.html
Originally, I was going to just style the templates that come with registration redux. Instead, I created a REST endpoint to reset the password and added a React component ResetPassword screen. It seemed like it would be the same amount of work, and was more consistent with the other account screens.
* Get URL to reset password by going through the Forgot? screen. 
* Go to that URL with an extra character at the end. Enter passwords that match and submit, which should lead to an error about the URL being invalid (technically, the token won't be correct).
* Enter the real URL and try entering passwords that don't match, testing validation.
* Enter the real URL and enter passwords that do match, which should reset the password.
Connects #67
> Style password screen

- Vagrantfile
- deployment/ansible/app-servers.yml
- deployment/ansible/roles/raster-foundry.mock-geoprocessing/defaults/main.yml
- deployment/ansible/roles/raster-foundry.mock-geoprocessing/handlers/main.yml
- deployment/ansible/roles/raster-foundry.mock-geoprocessing/meta/main.yml
- deployment/ansible/roles/raster-foundry.mock-geoprocessing/tasks/configuration.yml
- deployment/ansible/roles/raster-foundry.mock-geoprocessing/tasks/main.yml
- deployment/ansible/roles/raster-foundry.mock-geoprocessing/templates/upstart-rf-mock-geoprocessing.conf.j2
- src/mock-geoprocessing/server.js
This PR adds a service that listens for posts on port 9500. It takes the layer_id in the post body, waits 3 secs, and then posts to the /update-status endpoint on the app server, resulting in the status of that layer changing to complete.
* Run migrations and provision the app VM.
* Get the id of a layer in the DB.
* Then run `vagrant ssh app` and `curl --data "layer_id=<layer_id>" http://localhost:9500`. 
* Check that the status changes to complete.
Connects #50
> Add mock-geoprocessing service

- src/rf/js/src/user/components.js
- src/rf/js/src/user/controllers.js
React will re-render the entire DOM node if you pass in a new kind of
React component, even if they generate nearly identical markup. This is
problematic because of the way our components were using composition to
share common markup.
The solution is to invert the common React components so that only the
inner content is re-rendered for each transition.
After refactoring out `UserScreen` from all these components I started
to receive the following error:
> Invariant Violation: ReactMount: Two valid but unequal nodes with the same `data-reactid`
I think this is triggered by components that return a different kind of
root node depending on the circumstances (ex. sometimes all content is
wrapped in `<div>` and other times `<form>`). I solved this by adding a
wrapper around each component …
> Fix background video reset on login screens

- src/rf/npm-shrinkwrap.json
- src/rf/package.json
This lets you inject CSS changes into the page directly without having
to do a page refresh.
The LiveReload browser extension is required for this to work.
To test, run then following commands:
`./scripts/bundle.sh --watch`
`./scripts/npm.sh run livereload`
Then edit any SASS file.
> Add better support for livereload

- src/rf/apps/core/context_processors.py
- src/rf/apps/core/models.py
- src/rf/apps/home/views.py
- src/rf/apps/user/views.py
- src/rf/js/src/core/models.js
- src/rf/js/src/home/components/library.js
- src/rf/js/src/user/models.js
Fixes a bug where favorited layers that were authored by other
users would not appear as favorited.
This inconsistency was caused by erroneous logic that was used to
populate the `favorite` property on layer models. After reflecting on
this issue, I realized that it was a mistake to add this propery to the
layer model. Instead, we now define a list of favorites on the user
model.
The best way to test this is by running the sample data generation
script. On develop, you should see that there are some layers on the
Favorites panel where the star is not illuminated. Switching to this PR
should correctly highlight all favorited layers on this panel,
regardless of the layer author.
Connects #150
> Fix favorited layers not appearing as favorited

- src/rf/apps/home/forms.py
When saving tags from the front end we were getting leading and or trailing
spaces as a result of the UI separating the tags. This removes these for
easier filtering in other locations.
Connects #111 
* Create a new layer with several tags. (```this, that, the other, some tag```)
* Attempt to search for the tag by name in the database. (`SELECT * FROM core_layertag WHERE NAME = 'some tag';`)
* Ensure that the result is found.
* Prior to this change you should have to search for ' some tag'.
> Strip whitespace from tags.

- Vagrantfile
- deployment/ansible/group_vars/all
- deployment/ansible/group_vars/development
- deployment/ansible/group_vars/packer
- deployment/ansible/group_vars/test
- deployment/ansible/roles/raster-foundry.app/handlers/main.yml
- deployment/ansible/roles/raster-foundry.app/tasks/configuration.yml
- deployment/ansible/roles/raster-foundry.app/tasks/dependencies.yml
- deployment/ansible/roles/raster-foundry.app/templates/upstart-app.conf.j2
- deployment/ansible/roles/raster-foundry.base/defaults/main.yml
- deployment/ansible/roles/raster-foundry.base/handlers/main.yml
- deployment/ansible/roles/raster-foundry.base/tasks/configuration.yml
- deployment/ansible/roles/raster-foundry.base/tasks/main.yml
- deployment/ansible/roles/raster-foundry.base/tasks/vagrant-mounted.yml
- deployment/ansible/roles/raster-foundry.base/templates/vagrant.conf.j2
- deployment/ansible/roles/raster-foundry.worker/defaults/main.yml
- deployment/ansible/roles/raster-foundry.worker/handlers/main.yml
- deployment/ansible/roles/raster-foundry.worker/tasks/configuration.yml
- deployment/ansible/roles/raster-foundry.worker/tasks/dependencies.yml
- deployment/ansible/roles/raster-foundry.worker/templates/upstart-worker.conf.j2
- scripts/create-aws-resources.sh
- src/rf/create-aws-resources.py
- src/rf/requirements/base.txt
- src/rf/rf/settings/base.py
Provisioning the app now creates RF_SQS, RF_SQS_DEAD_LETTER, and RF_S3_BUCKET in /etc/rf.d/env based on the USER, and runs a script to create an SQS queue, an SQS dead letter queue, and an S3 bucket with names specified by these environment variables. The frontend should get the new bucket name and upload there, which should result in messages in the queue.
Connects #116
> Script creation of S3 and SQS resources

- src/rf/apps/core/decorators.py
- src/rf/apps/core/migrations/0019_layerimage_file_extension.py
- src/rf/apps/core/migrations/0020_layerimage_bucket_name.py
- src/rf/apps/core/models.py
- src/rf/apps/home/forms.py
- src/rf/apps/home/tests.py
- src/rf/apps/home/views.py
- src/rf/js/src/core/uploads.js
- src/rf/js/src/home/components/modals.js
- src/rf/js/src/settings.js
In preparation for #161, this PR sends image data over when posting layers, switches to using a content type of 'application/json' for the body of the request, and gets PUT requests to work properly.
To test, after importing a layer, check that LayerImage models were added to the DB with the correct source_uri and file_name. You can verify this using pgweb, looking in the network tab, and in the layer details panel.
Built on top of #102 (so, ignore first 3 commits)
Connects #162
> Send images when posting layers

- src/rf/apps/core/migrations/0021_remove_layerimage_source_uri.py
- src/rf/apps/core/models.py
- src/rf/apps/home/tests.py
- src/rf/js/src/core/uploads.js
Also, remove source_uri field which is no longer used.
To test, make sure that the filename in S3 looks correct for an uploaded file and also check that fields in the LayerImage table look right.
> Remove extra dot in s3 file name

- src/rf/apps/home/filters.py
- src/rf/js/src/app.js
- src/rf/js/src/core/models.js
- src/rf/js/src/home/components/processing-block.js
If the layer has failed since hitting refresh on the page, show a failure icon in the processing block.
Test by changing status of a layer to Failed in the admin view. Check that polling stops and no alert is shown when exiting (assuming there's only one layer pending and it has failed).
Builds on #173 
Connects #153
> Show error for failed layer

- deployment/ansible/group_vars/all
- deployment/ansible/roles/raster-foundry.base/defaults/main.yml
- deployment/ansible/roles/raster-foundry.base/tasks/dev-and-test-dependencies.yml
- src/rf/rf/settings/base.py
Our application may need to generate temporary files. In EC2 we will have
automatic access to a mounted ephemeral drive. We create a matching directory
for dev and test and supply the directory path as a variable name to django.
Connects #174 
* Provision app and worker vms
* SSH to the machines and check that the folder /media/ephemeral0 exists and is owned and group owned by rf.
* Permission should be 755.
> Use known EC2 location as temp dir.

- src/rf/js/src/core/models.js
- src/rf/js/src/home/components/library.js
Clicking the delete button for a layer deletes it on the backend and from the frontend LayerCollections (including pendingLayers).
Connects #132
> Click to delete layer

- README.md
- Vagrantfile
- deployment/ansible/filter_plugins/custom_filters.py
- deployment/ansible/group_vars/all
- deployment/ansible/group_vars/development
- deployment/ansible/group_vars/test
- deployment/ansible/roles.txt
- deployment/ansible/roles/raster-foundry.app/tasks/main.yml
- deployment/ansible/roles/raster-foundry.app/tasks/migrate.yml
- deployment/ansible/roles/raster-foundry.base/defaults/main.yml
- deployment/ansible/services.yml
- scripts/aws/setupdb.sh
- src/rf/requirements/base.txt
- src/rf/rf/settings/base.py
Connects #193 
This relies on work done by @hectcastro in d49a599a213a438d4919af659e36cc9d903046bf.
We do not want to manage Redis for Django caching at this time. Database
caching will be fast enough and reliable enough and requires less effort to
provision.
* Remove redis as a dependency.
* Change cache setting in base.py to use database cache.
* It is probably best to start from scratch and delete your current VMs as this does not actually remove redis.
* Provision VMs
* Check that redis is not installed on any of the machines (`which rediscli` or `netstat -natp` and make sure nothing is on the redis port) 
* Run the management command to generate cache tables.
* `python manage.py createcachetable`
* Navigate around the site.
* Check the cache tables in the DB. Hopefully you will find …
> Remove redis & change django cache to Postgres.

- .gitignore
- deployment/README.md
- deployment/cfn/stacks.py
- deployment/cfn/utils/cfn.py
- deployment/cfn/utils/constants.py
- deployment/cfn/vpc.py
- deployment/default.yml.example
- deployment/rf_stack.py
Add `launch-stacks` subcommand to `rf-stack.py` with supporting CloudFormation templates for an Amazon VPC with a VPC endpoint for S3.
---
**Testing**
Ensure that `default.yml` has at least the following contents:
```yaml
[staging]
Region: 'us-east-1'
StackType: 'Staging'
KeyName: 'rf-stg'
IPAccess: '216.158.51.82/32'
AvailabilityZones: 'us-east-1a,us-east-1b'
NATInstanceType: 't2.micro'
BastionHostInstanceType: 't2.micro'
```
Then, run the following command:
```bash
$ ./rf_stack.py launch-stacks --aws-profile rf-stg --rf-config-path default.yml --rf-profile staging
```
**Note**: This process makes use of the `rf-stg` API keys, which is different than the API keys associated with `rf-dev`. You can find the `rf-stg` keys on the file share.
> Add VPC CloudFormation stack

- deployment/ansible/roles/raster-foundry.app/tasks/dependencies.yml
- src/rf/apps/core/migrations/0025_add_bucket_key.py
- src/rf/apps/core/migrations/0026_bucket_key_null.py
- src/rf/apps/core/models.py
- src/rf/apps/home/forms.py
- src/rf/apps/home/tests.py
- src/rf/apps/home/views.py
- src/rf/apps/workers/copy_images.py
- src/rf/apps/workers/process.py
- src/rf/js/src/app.js
- src/rf/js/src/core/models.js
- src/rf/js/src/core/uploads.js
- src/rf/js/src/home/components/modals.js
- src/rf/js/src/home/components/processing-block.js
Allows users to import images from publicly-accessible S3 buckets.
* Try importing from a syntactically invalid bucket/key to test frontend validation (eg. `bkbo-tohu`)
* Try importing from a syntactically valid, but non-existent bucket/key to test backend validation (eg. `sample-tiffs/blah.tif`). Note that the submit button becomes disabled while submit is in progress.
* Import from `sample-tiffs/test.png` which should result in an image validation error
* Import from `sample-tiffs/356f564e3a0dc9d15553c17cf4583f21-7.tif` which should work. Change status to `complete` via `/admin/` to see the generated thumbnails.
* Imported file names (from file system or S3) need to have extensions. This is because we need to send the extension to the backend, and there's no way to extract the file type …
> S3 imports

- src/rf/sass/base/_form.scss
Connects #167 
The combination of line-height and height for the text boxes was causing the
placeholder text to show up near the button of the input box on Safari.
Removing a forced height resolves this.
* Open uploader modal in safari
* Check that placeholder text is visible.
> Fix placeholder text issue on Safari.

- src/rf/apps/core/migrations/0027_source_allow_blank.py
- src/rf/apps/core/models.py
We need to allow blanks to use the admin interface.
> Allow blank on source_s3_bucket_key

- deployment/cfn/data_plane.py
There is no need to spread RDS across multiple AZs for this demonstration.
> Disable MultiAZ Amazon RDS

- src/rf/js/src/core/uploads.js
Uploaded files will be processed by EMR workers and will use curl-like
commands to access the files. This will require the resources to be publicly
readable. When uploading files from the front end set the ACL header to
'public-readonly'.
* upload an image via the UI
* Log in to the AWS panel and check the resource in your S3 bucket.
* Look at properties and check that it it does not have a lock icon and the permissions mark it as "Everyone - Open/Download"
> Make working files public-read only.

- deployment/ec2/amis.py
- deployment/rf_stack.py
Going through the process of wiring up an AMI builder in Jenkins, which requires support for some level of AMI pruning.
---
**Testing**
Can be tested using the following command, but it'll only work if there are more than one AMIs present:
```bash
$ ./rf_stack.py prune-ami --aws-profile rf-stg --rf-profile staging --keep 1 --machine-type rf-app rf-worker
```
Here is an example of it successfully completing from my machine:
```bash
$ ./rf_stack.py prune-ami --aws-profile rf-stg --rf-profile staging --keep 1 --machine-type rf-app rf-worker
Identified that [ami-a9085fcc] is eligible to be pruned..
Deregistered [ami-a9085fcc] and snapshot [snap-20dd716a]..
Identified that [ami-55095a30] is eligible to be pruned..
Deregistered [ami-55095a30] and snapshot [snap-c527a98b]..
Identified that …
```
> Add support for AMI pruning

- deployment/cfn/application.py
- src/rf/apps/monitoring/urls.py
- src/rf/apps/monitoring/views.py
- src/rf/rf/settings/base.py
- src/rf/rf/urls.py
Connects #212 
To help us keep track of service interruptions we add a monitoring endpoint
that lets us know if the application stack and database are working properly.
We currently will only have a single app server, we return 200 OK for the
apps since be default of the fact that our endpoint code is running, the
application server must be ok.
We return a 200 for the database if we can connect to is. Currently we have
and expect to have only one database as well.
Worker servers are not monitored currently.
* visit /health-check/
* ensure you see the follow JSON response
```json
{"apps": [{"default": {"ok": true}}], "databases": [{"default": {"ok": true}}]}
```
> Add monitoring endpoint.

- deployment/ansible/group_vars/packer
The bucket `raster-foundry` has already been taken, so I renamed the bucket to `raster-foundry-uploads`.
Attempts to resolve #211.
> Change S3 bucket name for AWS deployments

- src/rf/apps/workers/process.py
- src/rf/rf/settings/development.py
Sets the default (development) logging level to INFO and adds helpful
logging messages.
The polling log should now display simple output like this:
Connects #216
> Add more INFO logging messages

- deployment/cfn/application.py
- deployment/cfn/stacks.py
- deployment/cfn/worker.py
- deployment/rf_stack.py
- scripts/aws/setupdb.sh
- scripts/aws/staging-deployment.sh
- src/rf/rf/settings/base.py
Now each application and worker stack is namespaced by color. In addition, a subcommand was added to `rf_stacks.py` to remove an entire stack by color.
Lastly, a staging deployment script was added to make use of all of the changes to alternate colors during Jenkins deployments.
---
**Testing**
Ensure that `default.yml` has at least the following contents:
```yaml
[staging]
Region: 'us-east-1'
StackType: 'Staging'
KeyName: 'rf-stg'
IPAccess: '216.158.51.82/32'
AvailabilityZones: 'us-east-1a,us-east-1b'
NATInstanceType: 't2.micro'
BastionHostInstanceType: 't2.micro'
PublicHostedZoneName: 'rf.azavea.com'
PrivateHostedZoneName: 'rf.internal'
RDSDbName: 'rasterfoundry'
RDSUsername: 'rasterfoundry'
RDSPassword: 'secretsecret'
GlobalNotificationsARN: 'arn:aws:sns:...'
AppServerInstanceType: …
```
> Add support for launching stacks namespaced by color

- src/rf/apps/workers/thumbnail.py
Previously, the thumbnail for 356f564e3a0dc9d15553c17cf4583f21-9.tif had a black boundary on the right side, despite the original not containing any boundary. With this PR, the thumbnails should no longer have any spurious boundaries.
Connects #229
> Remove dark boundary on thumbnails

- src/rf/apps/workers/process.py
This fixes an issue where the validation step was saving a `LayerImage`
status on a `Layer` record. On `develop`, the layer status briefly
appears as `---------` (unknown) in the Django admin after the
validation step completes.
To test:
1. Upload layer
2. Observe layer status in Django admin
> Use correct layer status

- src/rf/apps/workers/process.py
This alters the workflow to launch the cluster and generate thumbnails in
parallel when there are multiple workers available.
> Queue EMR handoff and thumbnail job at same time

- src/rf/apps/core/enums.py
- src/rf/apps/core/migrations/0030_processing_status.py
- src/rf/apps/workers/thumbnail.py
To test, stop rf-worker, and manually run two workers in separate tabs, and then submit a layer. Each worker should generate thumbnails without any errors.
Connects #263
> Prevent job conflicts

- src/rf/apps/core/management/commands/createawsresources.py
- src/rf/js/src/core/uploads.js
To test, import from s3 (eg. s3://sample-tiffs/356f564e3a0dc9d15553c17cf4583f21-7.tif) and a local file and check that the copied files are publicly accessible in the AWS console.
Connects #266
> Make copied images public-read

- src/rf/apps/workers/process.py
Fixes a bug where the timeout would continue to run even after layer
processing had completed.
Connects #257
To test:
1. Set log level to DEBUG
2. Upload layer
3. After the timeout job has been queued, mark the layer as FAILED or COMPLETED in the Django admin
4. You should see the "Ending timeout" debug message in the polling logs and the timeout job will not run again for that layer
You can reduce the `TIMEOUT_DELAY` variable to speed things up.
> Kill timeout if layer has finished processing

- src/rf/apps/core/admin.py
- src/rf/apps/core/migrations/0032_add_dismissed.py
- src/rf/apps/core/models.py
- src/rf/apps/home/filters.py
- src/rf/apps/home/views.py
- src/rf/js/src/core/models.js
- src/rf/js/src/home/components/processing-block.js
- src/rf/sass/components/_processing-block.scss
Fixes a bug where dismissed layers were reappearing after polling for pending layers. The design of the pending filter was also simplified and is no longer based on a timestamp coming from the frontend.
To test, click Dismiss on a layer that is complete.  It should disappear and not come back in the processing block, although it should be in the imports list. Clicking on a failed layer should remove it from the processing block and it shouldn't show up in the imports list. These changes should persist after refreshing the browser.
Connects #282
> Fix dismiss

- src/rf/js/src/core/views.js
Avoid mixed content warnings on staging site (which is behind an SSL cert) by
using the HTTPS tiles from cartodb.
* Build front end.
* View network tab and ensure tiles come over SSL.
> Switch basemap to HTTPS endpoints.

- src/rf/apps/core/context_processors.py
- src/rf/js/src/core/uploads.js
Fixes a bug on staging where client-side uploads to S3 fail due to not
providing the long session token in the upload request headers.
Test by uploading a file on staging.
Connects #289
> Use AWS session security token for S3 upload requests

- src/rf/rf/settings/production.py
This fixes a bug where user registration throws an Internal Server
Error on staging. The fix is to temporarily disable the SMTP email
backend until we have configured it properly on AWS.
Test by successfully creating a user on staging and logging in as that
user.
Connects #287
> Temporarily disable SMTP email backend on staging/production

- src/rf/apps/workers/process.py
This log message will allow us to determine the duration of the
thumbnail job.
> Add logging message

- src/rf/requirements/base.txt
Pillow > 3.0.0 has improved its support for dealing with TIFFs, but their latest official release is 3.0.0. This uses a Git SHA of their current `master` (as of today) to install version 3.1.0.dev0.
Attempts to resolve #278.
---
**Testing**
Attempt to process [this](https://s3.amazonaws.com/sample-tiffs/LC81410412014277LGN00_bands_432.TIF) TIFF that was failing with `Pillow==3.0.0`
> Install Pillow 3.1.0.dev0

- deployment/cfn/utils/constants.py
This is the lowest `m3` family instance type with ephemeral storage.
> Add m3.medium to EC2 instance types

- deployment/cfn/worker.py
Ensures that any available instance storage associated with the `ephemeral0` block device mapping be mounted at `/media/ephemeral0`. After the mounting is complete, give user and group ownership to `rf`.
Builds upon #299.
Attempts to resolve #300.
> Setup EC2 instance store for thumbnail processing

- src/rf/apps/core/models.py
- src/rf/apps/home/urls.py
- src/rf/apps/home/views.py
- src/rf/apps/workers/process.py
- src/rf/apps/workers/thumbnail.py
- src/rf/js/src/core/models.js
- src/rf/js/src/home/components/processing-block.js
- src/rf/sass/components/_processing-block.scss
Adds a retry link to layers that failed.
To test, find or construct a layer that has failed. Click the retry button which should roll things back to the transfer stage for layers with copied images, and the validation stage for layers with only uploaded images.
Connects #220
> Add Retry link for failed layers

- src/rf/js/src/home/components/library.js
- src/rf/sass/main.scss
Helps avoid mixed content warning messages in the browser.
> Serve placeholder and fonts over HTTPS

- src/rf/apps/home/views.py
- src/rf/js/src/home/components/processing-block.js
Fixes a bug where the "pending" layer criteria in `_get_layer_models`
prevented users from dismissing their own layers.
I solved this by moving the "pending" criteria, which is only relevant
for a single endpoint, to the appropriate view function.
Connects #304
> Allow user to dismiss own layers

- src/rf/apps/core/models.py
- src/rf/apps/workers/process.py
This fixes a bug where the validation job could be handled more than
once which could result in a duplicate EMR cluster spinning up for the
same layer.
Connects #318
> Only validate images once

- src/rf/apps/workers/process.py
- src/rf/apps/workers/thumbnail.py
This fixes a bug where certain TIFFs were not able to be thumbnailed by
Pillow. I solved this by using `gdal_translate` to produce a PNG which
is then used to generate each thumbnail.
I also discovered a utility function called `fit` in the PIL library
which I have decided to add since it is more succinct and also gives us
the ability to center align thumbnail images.
Connects #333
Connects #340
> Fix IOError during thumbnail phase

- src/rf/js/src/home/components/library.js
This fixes the column alignment on the layer detail panel by providing a
default value instead of an empty space.
Connects #326
> Fix column alignment on layer detail panel

- src/rf/apps/workers/emr.py
This fix allows us to swap create_cluster with add_steps so that we can
reuse EMR clusters during development.
Connects #265
> Fix EMR add_steps function

- .gitignore
- README.md
- Vagrantfile
- app-server/src/main/resources/application.conf
- app-server/src/test/resources/application.conf
- deployment/ansible/raster-foundry.yml
- deployment/ansible/roles/raster-foundry.aws-cli/meta/main.yml
- deployment/ansible/roles/raster-foundry.aws-cli/tasks/main.yml
- docker-compose.yml
- scripts/bootstrap
This commit adds support for using Auth0 settings in the application:
- client id: used to authenticate against a certain application in
Auth0
- domain: domain to use for sending requests to Auth0 for
authenticatino
- secret: secret used to verify signature of JWT
In this case the client secret is only the secret for the development
environment. Because this accesses an external service it still needs to
be kept secret. To accomplish this environment settings/files are placed
in an S3 bucket that is pulled down during provisioning. This requires
that developers have access to the AWS account.
1. Go through the additional steps in the README to add an AWS profile
2. Provision the application
3. Verify you can start the application `./scripts/server` and visit the …
> Add initial Auth0 settings to application

- docs/swagger/spec.yml
Adds a spec for interacting with layers and some of their associated tasks. I didn't flesh out the bigger GeoTrellis import task because I don't have a good idea of exactly what that would look like, but I added thumbnail and raster boundary tasks which provide a template that could be reused once we know more about what the bigger task will return.
The task interaction is inspired by promises, and I'm envisioning it would look something like this:
1) POST -> `/layers/`. Status 202
```
{
"uuid": "<layer-uuid>",
...
"thumbnail": {
"dataType": "ThumbnailPromise",
"promise": "https://raster-foundry.com/api/layers/<layer-uuid>/tasks/<task-uuid>"
},
...
}
```
A GET -> `/layers/<layer-uuid>/` at this point would return the same thing.
2) GET -> `/layers/<layer-uuid>/tasks/<task-uuid>/`, Status …
> Add layers API spec

- .gitignore
- README.md
- Vagrantfile
- app-frontend/.eslintrc
- app-frontend/config/webpack/environments/development.js
- app-frontend/package.json
- docker-compose.yml
- nginx/etc/nginx/conf.d/default.conf
- nginx/etc/nginx/nginx.conf
- scripts/server
- scripts/setup
- scripts/test
This commit adds additional setup for frontend development in the
following ways:
- adds an nginx container that serves static assets and proxies to
application server/api/healthcheck
- installs frontend dependencies and caches them in a ./node_modules
directory so that tests and static assets can be build
- adds a docker-compose configuration to run frontend commands and run
builds and tests inside the container
- adds development instructions for frontend development
- adds running of frontend tests to `./scripts/test`
- Provision vagrant VM (either `vagrant provision` or `vagrant up --provision`)
- SSH into vm and start server (`./scripts/server`)
- Outside the VM start `webpack-dev-server` from the `app-frontend` directory (`npm start`)
- Browse to …
> Add development setup for front-end

- .gitignore
- README.md
- Vagrantfile
- app-tasks/Dockerfile
- app-tasks/README.md
- app-tasks/dags/import_tif_image.py
- app-tasks/requirements.txt
- app-tasks/rf/.gitignore
- app-tasks/rf/MANIFEST.in
- app-tasks/rf/setup.cfg
- app-tasks/rf/setup.py
- app-tasks/rf/src/rf/__init__.py
- app-tasks/rf/src/rf/uploads/geotiff/__init__.py
- app-tasks/rf/src/rf/uploads/geotiff/create_thumbnail.py
- app-tasks/rf/src/rf/uploads/geotiff/extract_footprint.py
- app-tasks/rf/src/rf/uploads/geotiff/extract_metadata.py
- app-tasks/rf/src/rf/utils/io.py
- app-tasks/rf/tests/test_rf.py
- app-tasks/usr/local/airflow/airflow.cfg
- docker-compose.yml
- docs/architecture/adr-0006-workflow-manager.md
- scripts/bootstrap
- scripts/server
- scripts/setup
- scripts/test
This commit adds a prototype for using airflow for task management. A
simple DAG is added to simulate an import of a single geotiff that would
cause 3 tasks to be kicked off:
- metadata extraction
- footprint extraction
- thumbnail generation
Airflow itself has a web UI that this commit adds for opening up on
port 8080. Flower is used for monitoring celery workers, which the
airflow worker uses for parallelization of tasks. A redis instance is
added as a broker for the celery workers.
There may be a few minor things that need to be cleaned up if we wanted to go with this, but I think this is most of the way there.
1. Restart your VM and provision: `vagrant reload --provision`
2. Start server `./scripts/server`
3. Log output shouldn't show any failures. After the web server starts you …
> Add initial airflow scaffolding

- app-server/app/src/main/scala/Main.scala
- app-server/app/src/main/scala/Router.scala
- app-server/app/src/main/scala/auth/Authentication.scala
- app-server/app/src/main/scala/healthcheck/Routes.scala
- app-server/app/src/main/scala/user/Routes.scala
- app-server/app/src/main/scala/user/User.scala
- app-server/app/src/main/scala/utils/Config.scala
- app-server/build.sbt
- app-server/project/Dependencies.scala
- app-server/project/Version.scala
- app-server/project/plugins.sbt
This commit adds a directive to handle authentication. Authentication is
handled in the following way.
If a JSON web token provided in the Authorization header then one of
three things can happen:
1. Token Valid and User in Database: request proceeds
2. Token Valid and User _not_ in Database: rejected
3. Token Invalid: rejected
If no Authentication is provided then an anonymous user is attached to
the request.
Also slightly cleans up the routes by converting them to traits.
We still need to do some work on `Authorization`, creating users if they are not in the database yet, and also determining what endpoints should allow anonymous users and not.
1. Start up a development environment, running `vagrant up --provision` after switching to this branch
2. Start up the webpack server and log in …
> Add authentication directive to authenticate users

- Jenkinsfile
- README.md
- scripts/cipublish
Adds a `cipublish` script responsible for authenticating with, and pushing container images to Amazon Container Registry (ECR).
Depends on https://github.com/azavea/raster-foundry/pull/431
---
**Testing**
Inspect the output of a successful job run [here](http://jenkins.staging.rasterfoundry.com/job/raster-foundry/job/raster-foundry/job/feature%252Fhmc%252Fcipublish/16/). Successful run is a bit artificial. Because the build is currently broken, I had to build container images manually on the server so that the images could be pushed to ECR.
> Add support for publishing container images to ECR

- Jenkinsfile
- deployment/ansible/group_vars/all
- deployment/ansible/raster-foundry-jenkins.yml
- deployment/ansible/roles.yml
First, add Terraform to the Ansible playbook for Jenkins. Then, add steps to execute `infra` from within the `raster-foundry` workspace on Jenkins.
Also, a bunch of logic was added to the `Jenkinsfile` to support more specific Slack messages (PR titles, build status, etc.). Overall, the message format was borrowed from Buildkite.
---
**Testing**
Attempt to execute the Terraform installation changes on Jenkins:
```bash
❯ ansible-galaxy install -r deployment/ansible/roles.yml -p deployment/ansible/roles
❯ ansible-playbook -i deployment/ansible/inventory/jenkins deployment/ansible/raster-foundry-jenkins.yml
```
Then, review the execution in [this](http://jenkins.staging.rasterfoundry.com/job/raster-foundry/job/raster-foundry/job/feature%252Fhmc%252Finfra/13/) Jenkins job to ensure that …
> Add support for infrastructure management via Jenkinsfile

- README.md
- docker-compose.yml
- docs/swagger/index.js
- nginx/etc/nginx/conf.d/default.conf
- scripts/bootstrap
- scripts/cibuild
This reverts an attempt to add swagger documentation to the nginx
container with the application code until we have time to devote to
fixing issues with permissions and other problems.
- provision machine
- start server: `./scripts/server`
- ensure the swagger UI shows up at `localhost:9999`
> Remove swagger UI from nginx config

- app-server/app/src/main/resources/application.conf
- app-server/app/src/main/resources/logback.xml
- app-server/app/src/main/scala/Main.scala
- app-server/app/src/main/scala/healthcheck/Healthcheck.scala
- app-server/app/src/main/scala/organization/Organization.scala
- app-server/app/src/main/scala/user/User.scala
- app-server/build.sbt
This commit:
1. changes logging dependencies from basic `slf4j` to akka's special
`akka-slf4j` plus `logback`
2. logs the sql that Akka plans to execute at the `users` and
`healthcheck` endpoints at the debug level. It logs into a file in the
`app-server/app` directory.
It borrows logging setup heavily from the [GeoWave/GeoMesa comparative
analysis](https://github.com/azavea/gwgm-ca-performance-tests-server)
tests server but with a little more logging config in
`src/main/resources` and redirection to a log file, which I don't think
is present in the GWGM repo.
Fixes #394
> Add logging to existing endpoints

- app-server/app/src/test/scala/thumbnail/ThumbnailSpec.scala
- app-server/app/src/test/scala/utils/PGUtilsSpec.scala
Mixing in `PGUtilsSpec` caused database setup and teardown to happen
twice, which probabilistically killed the Jenkins build. Now PGUtilsSpec
is final so that's impossible. Changes to `ThumbnailsSpec` are also
included since that was the offender.
> Make PGUtilsSpec unmixable

- deployment/ansible/group_vars/all
The terraform state file for raster-foundry was created with terraform `0.7.3`, which is ahead of the version on Jenkins (`0.7.2`). This creates an error when trying to `terraform apply` infrastructure changes during CI. This PR bumps the terraform version to `0.7.4`.
View the Jenkins output for this PR build
> Bump terraform version to 0.7.4

- app-frontend/src/app/components/leafletMap/leafletMap.component.js
- app-frontend/src/app/components/leafletMap/leafletMap.controller.js
- app-frontend/src/app/components/sceneDetail/sceneDetail.component.js
- app-frontend/src/app/components/sceneDetail/sceneDetail.controller.js
- app-frontend/src/app/components/sceneDetail/sceneDetail.module.js
- app-frontend/src/app/components/sceneItem/sceneItem.component.js
- app-frontend/src/app/components/sceneItem/sceneItem.controller.js
- app-frontend/src/app/components/sceneItem/sceneItem.html
- app-frontend/src/app/index.routes.js
- app-frontend/src/app/pages/browse/browse.controller.js
- app-frontend/src/app/pages/browse/browse.html
- app-frontend/src/app/pages/library/scenes/detail/detail.html
- app-frontend/src/app/pages/library/scenes/list/list.controller.js
- app-frontend/src/app/pages/library/scenes/list/list.html
- app-frontend/src/app/pages/library/scenes/scenes.controller.js
- app-frontend/src/assets/styles/sass/app.scss
- app-frontend/src/assets/styles/sass/layout/_embedded.scss
- app-frontend/src/assets/styles/sass/layout/_library.scss
- app-server/app/src/main/scala/scene/package.scala
Refactor scene selection - Use callbacks instead of 2 way bindings
Output scene footprint in lat-lng instead of web-Mercator for leaflet
Selecting scene when page is loaded into a browse detail view  
Library scene list + detail interaction  
New stuff:  
* browse/{:id} now allows you to select a scene when the initial page load is into the detail view
* library/scenes allows selection, moving into detail view / between pages will preserve selections
* library/scenes/{:id} is a detail view for the scene with a static non-interactive map containing the footprint of the scene. This will be updated once the importer is upgraded to include thumbnail coordinates
> Add embedded map w/ geojson to library/scenes/{id}

- app-server/build.sbt
The jar built with SBT assembly includes signatures from dependencies that prevent the jar from being used with `java -jar`
* Build an assembly jar manually
```
./scripts/console app-server "./sbt app/assembly"
```
* Build a test image for the jar and run it
```
cd app-server/app
docker build -t rf-server .
docker run rf-server
```
* Exceptions will be thrown because the database is not available, but the security exception that causes the JVM to exit immediately will no longer be a problem. (In practice the database problem isn't an issue, this is just to confirm that the security problem is solved).
Connects #510
> Exclude signatures of signed jars during assembly

- app-frontend/config/webpack/environments/development.js
- app-frontend/config/webpack/environments/production.js
- app-frontend/config/webpack/environments/test.js
- app-frontend/config/webpack/global.js
- app-frontend/package.json
- app-frontend/src/app/components/navBar/navBar.controller.js
- app-frontend/src/app/components/navBar/navBar.html
- app-frontend/src/app/core/core.module.js
- app-frontend/src/app/core/services/config.provider.js
- app-frontend/src/app/core/services/scene.service.js
- app-frontend/src/app/index.bootstrap.js
- app-frontend/src/app/index.config.js
- app-frontend/src/app/index.module.js
- app-frontend/src/app/index.routes.js
- app-frontend/src/app/index.run.js
- app-frontend/src/app/pages/browse/browse.controller.js
- app-frontend/src/app/pages/error/error.controller.js
- app-frontend/src/app/pages/error/error.html
- app-frontend/src/app/pages/error/error.module.js
- app-server/app/src/main/resources/application.conf
- app-server/app/src/main/scala/Router.scala
- app-server/app/src/main/scala/config/Config.scala
- app-server/app/src/main/scala/config/Routes.scala
- app-server/app/src/main/scala/config/package.scala
- app-server/app/src/main/scala/utils/Config.scala
- nginx/etc/nginx/conf.d/default.conf
Remove hard coded urls from the frontend application so we can have different URLS depending on the environment
I've created a config service and provider, which we can use to encapsulate all similar configuration
Upgrade leaflet from 1.0.0-rc2 to 1.0.0
* Verify that no bare urls exist in the frontend part of the application
* Start the frontend with `npm start`, navigate to [the root url](http://localhost:9091/) , [library/scenes](http://localhost:9091/#/library/scenes/list?page=1) , and [library/scenes/detail](http://localhost:9091/#/library/scenes/detail/1d8706eb-0895-4169-ac6d-90ed8304ee0f) to verify that the urls still work
* Verify that the maps on the above pages still function as expected
* Controls should be on the [browse page](http://localhost:9091/), but not on the …
> Create config service / provider

- app-frontend/config/webpack/environments/production.js
- app-frontend/package.json
- app-frontend/src/app/index.vendor.js
This is possibly temporary, but uglify is blocking staging right now
because builds never complete -- this removes it until we can dedicate
time to fixing it.
* In VM run `./scripts/console app-server bash`
* Run `npm run build`
> Remove uglifyjs from production

- .gitignore
- deployment/ansible/roles/raster-foundry.jenkins/defaults/main.yml
- deployment/ansible/roles/raster-foundry.jenkins/files/config.xml
- deployment/ansible/roles/raster-foundry.jenkins/meta/main.yml
- deployment/ansible/roles/raster-foundry.jenkins/molecule-playbook.yml
- deployment/ansible/roles/raster-foundry.jenkins/molecule-requirements.yml
- deployment/ansible/roles/raster-foundry.jenkins/molecule.cfg
- deployment/ansible/roles/raster-foundry.jenkins/molecule.yml
- deployment/ansible/roles/raster-foundry.jenkins/tasks/main.yml
- deployment/ansible/roles/raster-foundry.jenkins/tests/test_jenkins.py
Jenkins branch indexing hangs as described in https://issues.jenkins-ci.org/browse/JENKINS-36724 and #492 .
There doesn't seem to be a fix to this issue besides restarting Jenkins. This PR installs the Jenkins CLI and sets a cronjob to restart Jenkins every few hours.
* Login to `jenkins.staging.rasterfoundry.com`
* Ensure `/var/lib/jenkins/jenkins-cli.jar` exists
* Ensure `/var/spool/crontabs/jenkins` exists and contains an entry to run the restart command every 3 hours as described in the [cli documentation](http://jenkins.staging.rasterfoundry.com/cli/command/restart).
Solves #492
> Restart Jenkins every 3 hours to stop branch indexing

- deployment/ansible/group_vars/all
- deployment/ansible/roles.yml
Bump `terraform` version to `0.7.6`, `azavea.terraform` role version to `0.3.1`
* SSH into jenkins.staging.rasterfoundry.com.
* Do `terraform -v`, ensure output is `Terraform v0.7.6`
> Bump terraform install version and azavea.terraform role version

- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/User.scala
This commit removes the owner role and replaces it back with the user
role, which was accidentally removed during a refactor. This also aligns
the datamodel with the enum constraints currently in the database.
* run `./scripts/load_development_data/`
* start server: `./scripts/server`
* start frontend: `npm start`
* Log in, get JWT and make an authenticated request to the users endpoint with the JWT supplied. No 500s should be shown
> Remove owner role and replace with user

- app-backend/app/src/main/resources/application.conf
- app-backend/app/src/main/scala/Router.scala
- app-backend/app/src/main/scala/token/Auth0ErrorHandler.scala
- app-backend/app/src/main/scala/token/Auth0Exception.scala
- app-backend/app/src/main/scala/token/Routes.scala
- app-backend/app/src/main/scala/token/Token.scala
- app-backend/app/src/main/scala/token/package.scala
- app-backend/app/src/main/scala/utils/Config.scala
- app-backend/app/src/main/scala/utils/RfStackTrace.scala
Refresh tokens are useful for CLIs, mobile devices, and other long-lived clients of the API. The idea is to generate a token tied to the client that allows the user to not have to specify their username and password every time.
The workflow for the user will be as follows:
1. Generate a Refresh Token from Auth0
2. Use the Refresh Token to get a JWT by POSTing the Refresh Token to `/api/tokens`
{
"refresh_token": "eyJ..."
}
3. Use the JWT in all their subsequent requests
Each Refresh Token has two pieces of metadata: an `id` and a `device_name`. The `id` is for uniquely identify the token, for the purpose of deletion. The `device_name` is a friendly name the user chooses when creating a Refresh Token, to help them remember which device it was for. Once generated, the actual Refresh Token …
> Support Refresh Tokens

- app-tasks/dags/landsat8/import_landsat8_scenes.py
- app-tasks/dags/sentinel2/find_sentinel2_scenes.py
- app-tasks/dags/sentinel2/import_sentinel2_scenes.py
- app-tasks/rf/src/rf/uploads/landsat8/create_images.py
- app-tasks/rf/src/rf/uploads/landsat8/create_scenes.py
- app-tasks/rf/src/rf/uploads/landsat8/settings.py
- app-tasks/rf/src/rf/uploads/sentinel2/create_images.py
- app-tasks/rf/src/rf/uploads/sentinel2/settings.py
- app-tasks/rf/src/rf/utils/io.py
This PR adds a (currently unscheduled) DAG to import Landsat 8 scenes and their associated images, thumbnails, and footprints. We need it so that we can import Landsat 8 scenes
...none yet
Includes #521 as well, since the ingest with images depends on the DAG being present.
* `vagrant ssh`, `./scripts/server`
* Navigate to the airflow ui at `localhost:8080`
* Create a DAG run as follows:
* Click "None" under the `find_landsat8_scenes` schedule field to create a scheduled run
* Click "Create" 
* Create some runs for some time in the past, like so:
* Click "Save"
* Navigate bag to the DAGs home (`localhost:8080`) and click on the light green "Running" circle:
* Scroll all the way to the right and click on the log
* Observe! Your DAG is running and if you wait patiently you will see some …
> Add images on Landsat 8 scene creation

- Vagrantfile
- docker-compose.spark.yml
- docs/spark/README.md
- worker-tasks/.dockerignore
- worker-tasks/Dockerfile
- worker-tasks/build.sbt
- worker-tasks/src/main/scala/com/rasterfoundry/worker/SparkPi.scala
Add the components required for a local Spark Standalone cluster housed within Docker containers. In addition, add scaffolding required for a test `SparkPi` job.
Lastly, start assembling a `README` to document specifics about the Spark environment so that we have a concise reference as we move toward the EC2 based deployment.
---
**Testing**
Please see the included `README`.
I think it would be great if the reviewer could get the Spark Standalone cluster running locally and submit the `SparkPi` job to it. It would also great to kill the `spark-master` while `SparkPi` is running and then bring it back up to see if it still recalls the previous cluster state (most easily viewable via the Spark UI).
Lastly, please suggest corrections to the README where things seem inaccurate or unclear.
> Add Spark Standalone cluster with README

- deployment/ansible/roles.yml
- deployment/ansible/roles/raster-foundry.jenkins/molecule-playbook.yml
- deployment/ansible/roles/raster-foundry.jenkins/molecule.yml
- deployment/ansible/roles/raster-foundry.jenkins/tasks/main.yml
- deployment/ansible/roles/raster-foundry.jenkins/tests/test_jenkins.py
- scripts/cipublish
Remove the restart-jenkins crontask, and add `jenkins` user to `sudoers` to alleviate branch-indexing issues.
* change `hosts: jenkins` to `hosts:all` in `raster-foundry-jenkins.yml`
* run `molecule test`, ensure all tests pass.
* ssh into jenkins.staging.rasterfoundry.com and ensure `jenkins` is in the `sudo`, `docker`, `adm` groups.
> Remove `restart-jenkins` cronjob, add Jenkins user to sudoers

- app-tasks/Dockerfile
Don't use the wheels provided by `pycparser` because they are inconsistent with the source.
See:
- https://github.com/eliben/pycparser/issues/148
- https://github.com/pyca/cryptography/issues/3187
Execute the following commands within the supplied virtual machine and ensure that `raster-foundry-airflow` completes successfully.
```bash
$ docker rmi -f raster-foundry-airflow
$ docker-compose build airflow-webserver
```
> Fix pycparser installation

- Jenkinsfile
Add comments for each stage of the `Jenkinsfile` build process and limit Slack messages to failures.
* Review Jenkins file and see if the comments make sense
* Take a look at the [job output](http://jenkins.staging.rasterfoundry.com/job/raster-foundry/job/raster-foundry/job/feature%252Fhmc%252Fshhh-jenkins/) to ensure that it looks correct
> Add comments to Jenkinsfile; limit Slack messages to errors

- app-frontend/package.json
- app-frontend/src/app/components/filterPane/filterPane.component.js
- app-frontend/src/app/components/filterPane/filterPane.controller.js
- app-frontend/src/app/components/filterPane/filterPane.html
- app-frontend/src/app/components/filterPane/filterPane.module.js
- app-frontend/src/app/components/leafletMap/leafletMap.controller.js
- app-frontend/src/app/components/navBar/navBar.controller.js
- app-frontend/src/app/index.components.js
- app-frontend/src/app/index.routes.js
- app-frontend/src/app/pages/browse/browse.controller.js
- app-frontend/src/app/pages/browse/browse.html
- app-frontend/src/assets/styles/sass/app.scss
- app-frontend/src/assets/styles/sass/components/_slider.scss
- app-frontend/src/assets/styles/sass/layout/_sidebar.scss
Hook up the browse filter to the sidebar queries and url
Add angularjs-sliders to handle sliders in a way that's easy to style
Basic interaction
Drag select on months / sources and clearing filters
Map based filters will be implemented when on a different card
Currently no way to fetch the correct filter value ranges for the year filter and source filter from the API - this will have to be part of a filter enhancement later on which will probably add the histogram visuals from the original prototype
* Open the app to the /browse page
* Click on the filter button
* Modify each filter value and verify:
* the state is tracked in the url using query parameters
* The scene list updates with every filter change
* Only one query runs at a time
* If a filter changes while a scene query is in …
> Add filter pane component and hook up to browse view

- Jenkinsfile
- scripts/cibuild
Docker Compose creates networks within the context of Docker in order to provide a communication mechanism between services. Because Docker Compose was responsible for creating the network initially, it should also be used to tear it down. 
See: https://github.com/docker/docker/issues/23971
Inspect the output of the Jenkins job for this PR and ensure that the `docker-compose down` step completes successfully.
> Use Docker Compose to bring down services

- Vagrantfile
- docker-compose.yml
- scripts/psql
We don't want to forward port 5432 from the VM because it causes problems if the host happens to have a postgres client running locally. However, we still want to have a way to connect to the database without having to type a long `docker-compose` command. This PR wraps the long `docker-compose` command into a script in `scripts/psql` and kills the port forwarding to host.
* Pull down the branch
* `vagrant up && vagrant ssh`
* `./scripts/psql`
Closes #547
> Not forward 5432 and add a psql helper script

- Jenkinsfile
As JENKINS-26100 notes, the GIT_COMMIT environment variable does not
exist in a Jenkins Pipeline. In order to populate it for the downstream
deployment stages, use the shell wrapper to execute the Git CLI and
return the current revision.
See: https://issues.jenkins-ci.org/browse/JENKINS-26100
Easiest way may be to merge this PR and inspect the output of the `develop` Jenkins job.
> Manually set GIT_COMMIT in Jenkinsfile

- .github/PULL_REQUEST_TEMPLATE.md
- docs/style/scala.md
This PR adds an initial style guide for scala code in Raster Foundry. The focus in this first pass
is on existing issues that address style (#475, #562); things we've probably done wrong
(superindented blocks of with statements, as in our [table definitions](https://github.com/azavea/raster-foundry/blob/d50d9fa05d6d8b67137c64781b8bf7fe15798ca7/app-backend/database/src/main/scala/com/azavea/rf/database/tables/Organizations.scala#L20-L21); and a
planned departure from the Scaladoc style in how we do multi-line comments.
This PR is needed to provide a place for documenting our style and to begin documenting.
Closes #472, closes #475
> Add an initial style guide and update PR template

- app-backend/app/src/main/scala/bucket/Routes.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Buckets.scala
Adds support for adding and removing scenes from buckets in bulk. See commit messages for details.
The original issue asks for changes to the UI as well. I'm putting this up to get early feedback. We can then decide if we want to do the frontend changes as part of this or in a separate PR.
~~Test upserting values by POSTing to `/api/buckets/:bucketId/scenes` a JSON like this:~~
~~Test deleting values by POSTing something like this:~~
Ensure you have an account, a JWT, and a bucket to your name.
Test adding scenes to your bucket:
```bash
$ echo '["1ac24024-963a-4a50-b234-3dc411e7917c","6ae1495d-3fee-4038-a493-059f8efb334d","3777e8b2-4dfe-484c-a696-fcc104be53d3","ca179a10-2058-490f-9130-862f423b02d6","4dbe9d6e-f479-4a41-8dba-83510e04386c","68b50942-650c-414f-ab0b-7dd69c5db608","50dc6a9e-52a5 …
```
> Bulk Scene Operations

- app-frontend/package.json
- app-frontend/src/app/index.vendor.js
- app-frontend/src/assets/styles/sass/components/_map.scss
- app-frontend/src/assets/styles/sass/components/_slider.scss
Fix filter slider styling
Fix leaflet map control position
Both issues were caused by the sass not being specific enough - when unbundled, sass takes priority over equal depth css, but not when bundled.
Removed the `npm run serve-static` command since it doesn't work anymore, and we use nginx for that purpose. Added an `npm run build-nginx` command which builds then copies the files into the correct nginx folder for it to serve.
* build static using `npm run build`
* copy assets to `/opt/raster-foundry/nginx/srv/dist` from `/opt/raster-foundry/app-frontend/dist` in the vagrant machine
* Open http://localhost:9100 and verify that both style issues are fixed
Fixes #571
> Make slider css more specific

- app-backend/app/src/main/scala/token/Routes.scala
- app-backend/app/src/main/scala/token/Token.scala
- app-backend/app/src/main/scala/utils/UserErrorHandler.scala
Previously we would return a 500 for every Auth0 API error. But there is a use case when the user sends an invalid refresh token and Auth0 returns a 401 with an `invalid_refresh_token` error. Since this is a legitimate user error, we now inspect the Auth0 response and send back a 400 if this is the case.
We also add the UserErrorHandler trait and respective exception handler to the token route so it can translate an `IllegalArgumentException` to an error 400. Also update the logging code so now it prints the full stack trace for every error.
```http
> http :9000/api/tokens refresh_token=TOTALLY_NOT_A_REFRESH_TOKEN
HTTP/1.1 400 Bad Argument
Content-Length: 28
Content-Type: text/plain; charset=UTF-8
Date: Wed, 19 Oct 2016 23:03:05 GMT
Server: akka-http/2.4.11
Refresh token not recognized …
```
> Return 400, not 500 for invalid tokens

- deployment/ansible/group_vars/all
See: https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#077-october-18-2016
From within the `raster-foundry-deployment` project, execute the following command. There should be no changes:
```bash
$ GIT_COMMIT="19897d9" AWS_PROFILE=raster-foundry RF_SETTINGS_BUCKET=rasterfoundry-staging-config-us-east-1 ./scripts/infra plan
```
**Note**: The value of `GIT_COMMIT` needs to reference the most recent commit SHA from `develop`, or else the ECS resources will show up as changed.
> Bump Terraform to version 0.7.7

- app-backend/app/src/main/scala/utils/PGUtils.scala
Increases the timeout set for copying the database in tests because this was causing test suites to be aborted.
* run `./scripts/test` and verify that tests pass
> Increase database copy timeout

- app-backend/app/src/main/scala/Router.scala
- app-backend/app/src/main/scala/auth/Authentication.scala
- app-backend/app/src/main/scala/bucket/Routes.scala
- app-backend/app/src/main/scala/config/Routes.scala
- app-backend/app/src/main/scala/healthcheck/Routes.scala
- app-backend/app/src/main/scala/image/Routes.scala
- app-backend/app/src/main/scala/organization/Routes.scala
- app-backend/app/src/main/scala/scene/Routes.scala
- app-backend/app/src/main/scala/thumbnail/Routes.scala
- app-backend/app/src/main/scala/token/Routes.scala
- app-backend/app/src/main/scala/user/Routes.scala
- app-backend/app/src/test/scala/auth/AuthSpec.scala
- app-backend/app/src/test/scala/bucket/BucketSceneSpec.scala
- app-backend/app/src/test/scala/bucket/BucketSpec.scala
- app-backend/app/src/test/scala/healthcheck/HealthCheckSpec.scala
- app-backend/app/src/test/scala/image/ImageSpec.scala
- app-backend/app/src/test/scala/organization/OrganizationSpec.scala
- app-backend/app/src/test/scala/scene/SceneSpec.scala
- app-backend/app/src/test/scala/thumbnail/ThumbnailSpec.scala
- app-backend/app/src/test/scala/user/UserSpec.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Buckets.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Organizations.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Scenes.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Thumbnails.scala
~~**NOTE** This is a preview of the route style I'm going with. I'd love to get feedback so we can zero in on a format we like. I'm going to continue updating the other routes to this style until I get feedback.~~
Update routes to ensure the right order of operations. The style is like:
```scala
routes: Route = {
pathPrefix("api" / "route") {
pathEndOrSingleSlash {
get { listHandler } ~
post { createHandler } 
} ~
pathPrefix(JavaUUID) { id =>
pathEndOrSingleSlash {
get { getHandler(id) } ~
put { updateHandler(id) } ~
delete { deleteHandler(id) }
} ~
pathPrefix("subroute") {
pathEndOrSingleSlash {
get { listSubHandler(id) } ~
post { createSubHandler(id) }
} ~
pathPrefix(JavaUUID) { subid => 
pathEndOrSingleSlash {
get { getSubHandler(id, subid) } ~
put { updateSubHandler(id, subid) } ~ …
```
> Update Route Ordering

- deployment/ansible/roles/raster-foundry.jenkins/tasks/main.yml
Instead of using backreference group numbers directly, use the `\g<NUMBER>` syntax to remove ambiguity if the characters following a backreference need to be numbers as well.
See: https://docs.python.org/2.7/library/re.html
Resolves https://github.com/azavea/raster-foundry/issues/593
Execute the Jenkins role and ensure that none of the `raster-foundry.jenkins` tasks are marked as `changed`:
```bash
~/Projects/raster-foundry feature/hmc/fix-jenkins-exec-reset 34s
❯ ansible-playbook -i deployment/ansible/inventory/jenkins deployment/ansible/raster-foundry-jenkins.yml
```
Also, wait until no Jenkins jobs are in progress and restart the service. Afterwards, confirm that the executor count is still `1` within **Configure System**.
> Fix Jenkins executor reset when running Ansible

- app-backend/app/src/main/scala/image/QueryParams.scala
- app-backend/app/src/main/scala/scene/QueryParameters.scala
- app-backend/app/src/test/scala/scene/SceneSpec.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/query.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Images.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Scenes.scala
Since #588, the `resolutionMeters` field has been moved from scenes to images. However, we would still like to filter scenes by resolution. Rather than adding filtering by only one field, I added a mechanism to filter all scenes by image parameters. The general approach is as follows:
1. Add `min` and `max` resolution filtering to the image endpoint
2. Update `SceneQueryParameterDirective` to also extend `ImageQueryParametersDirective`
3. If image query parameters are specified, find all images that satisfy them and restrict to only scenes that contain these images
Thus, we can now use not just resolution by any parameters that are used for filtering images.
It is important to note that we are filtering for _Scenes_, not _Images_. For example, consider the following setup:
* Scene S1 with …
> Filter Scenes by resolution (and other image parameters)

- app-backend/migrations/src/main/resources/logback.xml
Previously the testing output would be very verbose on local dev environments and Jenkins, making the result difficult to parse. By setting Slick's logging level to INFO, we reduce most of the noise.
We set the logging level for Slick as a whole. If instead we would like to be more selective, a full list of loggers can be found here: http://slick.lightbend.com/doc/3.2.0-M1/config.html#logging
I tried extensively to turn off logging only for Unit tests, but preserve it for runtime, using guides like these: https://engineering.sharethrough.com/blog/2015/06/04/suppressing-slf4j-logs-during-tests-in-sbt/, but was ultimately unsuccessful.
* Check out the PR
* Run the tests from your machine:
$ vagrant ssh -c 'cd /opt/raster-foundry && ./scripts/console app-server "./sbt test"'
* Ensure you …
> Reduce Slick Logging

- README.md
- app-tasks/rf/src/rf/models/footprint.py
- app-tasks/rf/src/rf/uploads/landsat8/create_footprint.py
- app-tasks/rf/src/rf/uploads/sentinel2/create_footprint.py
- scripts/console
The API has been updated to accept lat/lon coordinates for footprints rather than WebMercator; this updates the landsat8 and sentinel2 importers to match.
This also updates some README and example text to match what appeared to be the current state of things.
Additionally, the JSON format being used by the importers is currently not what the API expects, so this includes an update to fix the structure used for footprints. However, there appear to be other areas where the importer JSON format doesn't match the API; I've opened #614 to track these.
* `vagrant ssh`
* `./scripts/console airflow-worker bash`
* `root@6119306149ef:/usr/local/airflow# ipython`
* `from rf.uploads.sentinel2.create_scenes import create_sentinel2_scenes`
* `s1, s2, s3 = …
> Use latitude / longitude coordinates in footprints

- app-frontend/src/app/components/downloadModal/downloadModal.component.js
- app-frontend/src/app/components/downloadModal/downloadModal.controller.js
- app-frontend/src/app/components/downloadModal/downloadModal.html
- app-frontend/src/app/components/downloadModal/downloadModal.module.js
- app-frontend/src/app/index.components.js
- app-frontend/src/app/pages/library/buckets/detail/bucketScenes/bucketScenes.controller.js
- app-frontend/src/app/pages/library/buckets/detail/bucketScenes/bucketScenes.html
- app-frontend/src/app/pages/library/buckets/detail/scene/scene.controller.js
- app-frontend/src/app/pages/library/buckets/detail/scene/scene.html
- app-frontend/src/app/pages/library/scenes/detail/detail.controller.js
- app-frontend/src/app/pages/library/scenes/detail/detail.html
- app-frontend/src/assets/styles/sass/components/_badge.scss
- app-frontend/src/assets/styles/sass/components/_list-group.scss
Add download modal to bucket/scenes and scenes/detail views
No metadata (only images):  
Layout with metadata on images and scene with example metadata files
Styling is kind of iffy. @designmatty probably will want to create better styles for nested lists such as this modal tends to create (It's basically exposing a file/folder structure that's at most 2 deep).  We may want to add toggles at the image level instead of always displaying metadata as well.
* in the Bucket/scenes view, select a couple scenes and click download. Examine the http request that fetched the scenes and verify that all images show up.
* Modify the javascript in `buckeScenes.controller.js` to inject metadata or add metadata to scenes on the backend to verify that the modal shows them.
> Add download modal component

- app-backend/app/src/main/resources/application.conf
- app-tasks/usr/local/airflow/airflow.cfg
- docker-compose.spark.yml
- docker-compose.yml
- docs/spark/README.md
Whenever we reference an internal endpoint for external services (database, cache), use a consistent domain structure. Namely, `*.service.rasterfoundry.internal`.
Spin up the development environment and ensure that all of the services that need to interact with the database and cache still can:
- `app-server`
- `airflow-webserver`
- `airflow-flower`
- `airflow-scheduler`
- `airflow-worker`
Using `./scripts/server` is a pretty good test. All of these services will complain on start if they can't connect to the database. Airflow connections to Redis will complain right away too. Mostly, `airflow-flower`.
> Standardize on internal database and cache hostname

- app-tasks/Dockerfile
Update Airflow `Dockerfile` so that DAGs are added to the image at build time.
Builds off of https://github.com/azavea/raster-foundry/pull/638. Only the last 4 commits are relevant.
Because this is so closely tied to https://github.com/azavea/raster-foundry-deployment/pull/12, view the Airflow UI on staging and ensure that the DAGs show up correctly.
> Add Airflow DAGs at container image build time

- app-backend/app/src/main/scala/utils/PGUtils.scala
- app-backend/app/src/test/scala/DBSpec.scala
This commit changes how migrations are applied when running
tests. Before this change migrations would run against a test template
database and then each test suite would run create a database from the
template and run its suite. Subsequent runs would not need to run
migrations if no new migrations were present.
This created a problem when the database was persisted across branches
if those branches had conflicts for migrations because those conflicting
migrations would not run.
This commit changes that behavior by recreating the test template before
each database run. Migrations still run against the template and are
copied; however, that template is _not_ persisted between runs.
This increases test run time somewhere between 15-30 seconds in my testing (`time ./sbt test`), but the …
> Run migrations for every test run

- app-tasks/usr/local/airflow/airflow.cfg
- docker-compose.yml
- nginx/Dockerfile
- nginx/etc/nginx/conf.d/airflow.conf
- nginx/etc/nginx/conf.d/app.conf
In order to easily handle HTTP and HTTPS traffic in ECS, reverse proxy the Airflow web server with Nginx. Using Nginx virtual hosts allows us to reuse the existing Nginx container image, instead of building a new one just for Airflow.
Also, make use of the `AIRFLOW_BASE_URL` environment variable to override the Airflow `base_url` web server configuration setting. This provides a way to override it when Airflow is running in different environments with different URLs.
Since the Airflow `base_url` setting mostly involves outbound emails, I don't really have a good way to test it. For now, I think it would be OK to let it slide until we actually setup outbound email.
To test the Nginx configuration changes, login to the ensure that `./scripts/server` is running. Then use execute the …
> Airflow reverse proxy and base URL override

- app-tasks/usr/local/airflow/airflow.cfg
- docker-compose.yml
- nginx/etc/nginx/conf.d/airflow.conf
Add support for setting the following Airflow settings via environment variables:
- `core.parallelism`
- `core.fernet_key`
- `webserver.secret_key`
- `webserver.workers`
- `celery.celeryd_concurrency`
Also, remove all Mesos configuration settings because we're not using it, and add a virtual host to the Nginx configuration for the Flower service.
Resolves:
- https://github.com/azavea/raster-foundry/issues/586
- https://github.com/azavea/raster-foundry/issues/607
Using `./scripts/server`, start all of the Airflow components and ensure that they don't complain about any of the passed-through settings changes.
The Flower reverse proxy changes can be tested via https://github.com/azavea/raster-foundry-deployment/pull/13.
> Update Airflow configuration; add Flower reverse proxy

- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/Scene.scala
- docker-compose.yml
This commit optimizes the server side join in the case where the set of
scenes returned from the database includes duplicate rows for scenes,
thumbnails, bands, and images. The original code seemed to be doing some
duplicate grouping and flattening that can be done slightly more
concisely.
* Import some scenes with airflow to ensure that the scenes have bands
* Try to hit `/api/scenes/` and also start the server and browse the application
* Endpoints/servers should not crash
> Optimize server side grouping of scenes

- app-tasks/README.md
- app-tasks/dags/landsat8/import_landsat8_scenes.py
- app-tasks/dags/sentinel2/find_sentinel2_scenes.py
- app-tasks/dags/sentinel2/import_sentinel2_scenes.py
- app-tasks/rf/src/rf/uploads/landsat8/create_scenes.py
- docker-compose.yml
Adds an explanation to `app-tasks/README.md` for how to get backfills going for scene creation.
Additionally, sets DAG concurrency using the .env configuration file
downloaded from S3 and adds scheduling to the two existing import processes.
As noted in #611, it takes a lot of attention to get imports running. That's not great since we all want to have scenes in our local databases, and we should be able to get to that state using our importers.
To test that the scheduling works as described in the first paragraph of the `app-tasks/README.md` diff:
* `vagrant ssh`
* `./scripts/bootstrap` to pull in the concurrency setting
* `./scripts/console airflow-scheduler bash` --> `airflow resetdb` to clear out any existing task runs you may have in your airflow db
* `docker-compose stop` <-- the …
> Add instructions for backfilling DAG runs and DAG schedules

- app-frontend/src/app/components/filterPane/filterPane.controller.js
Trivial fix - datasource name needs to be `Landsat 8` not `Landsat-8` on the frontend to match the datasource
Trivial - Merging
> Change 'Landsat-8' to 'Landsat 8' on the frontend

- app-tasks/usr/local/airflow/airflow.cfg
- docker-compose.yml
Use environment variables to configuration the `remote_base_log_folder` and `remote_log_conn_id` Airflow settings. Default to having the settings unset locally.
Using `./scripts/server`, start all of the Airflow components and ensure that they don't complain about any of the passed-through settings changes.
The actual Airflow remote logging can be tested via https://github.com/azavea/raster-foundry-deployment/pull/14.
> Add Airflow remote log configuration via environment

- app-tasks/Dockerfile
- app-tasks/requirements.txt
- docker-compose.yml
- scripts/bootstrap
- scripts/load_development_data
- scripts/test
Create an `airflow` user that is responsible for running the various Airflow daemons. Ensure that its GID is `1000` so that it can read the AWS credentials in the development environment. Also, change the volume definition for the AWS credentials so that they map to the `airflow` user's home directory.
Resolves https://github.com/azavea/raster-foundry/issues/639 and #678
From within the virtual machine, remove the current `.env` file:
```bash
vagrant@vagrant-ubuntu-trusty-64:/opt/raster-foundry$ rm .env
```
Then, execute `bootstrap` and ensure that the file exists again:
```bash
vagrant@vagrant-ubuntu-trusty-64:/opt/raster-foundry$ ./scripts/bootstrap
vagrant@vagrant-ubuntu-trusty-64:/opt/raster-foundry$ ls -la | grep env
-rw-r--r-- 1 vagrant vagrant   860 Nov 14 19:36 .env
```
Lastly, …
> Ensure that Airflow doesn't run as root

- app-backend/app/src/main/scala/scene/QueryParameters.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/query.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Buckets.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Scenes.scala
- docs/swagger/spec.yml
Add a bucket filter parameter to scenes
For /bucket/scenes, delegate filtering by injecting the bucket parameter into the CombinedSceneQueryParams
Without sort:
With sort:
* Follow reproduction steps in #675 
* Verify that the same steps work in the scene endpoint
Fixes https://github.com/azavea/raster-foundry/issues/675
> Add bucket filtering to scene specific query params

- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Buckets.scala
Bad filter was causing issues when adding a set of scenes to a bucket when some of them were already in it
* Create a bucket and add a scene to it
* Check to make sure that the scene was added
* Add another scene, as well as the first scene to the bucket
* Check that the new scene was added
Fixes #670
> Fix re-adding scenes to buckets

- app-frontend/src/app/pages/browse/browse.controller.js
Loading the page triggers a request to scenes, which doesn't work when we're not authenticated.
This PR adds a watcher to the browser controller that requests scenes once the logged in state is
`true`.
(both not necessary)
No error in the scenes list:
* Start the front-end
* Note that there's no error
* Log in
* Note that a scenes request occurs and the list populates
* Log out
* Refresh the page and note that there's still no error even though state didn't change
Closes #692
> Wait for login before requesting scenes

- app-backend/app/src/main/scala/bucket/Routes.scala
- app-backend/app/src/main/scala/image/Routes.scala
- app-backend/app/src/main/scala/scene/Routes.scala
- app-backend/app/src/main/scala/thumbnail/Routes.scala
- app-backend/app/src/test/scala/bucket/BucketSceneSpec.scala
- app-backend/app/src/test/scala/bucket/BucketSpec.scala
- app-backend/app/src/test/scala/image/ImageSpec.scala
- app-backend/app/src/test/scala/organization/OrganizationSpec.scala
- app-backend/app/src/test/scala/scene/SceneSpec.scala
- app-backend/app/src/test/scala/tags/ModelTagSpec.scala
- app-backend/app/src/test/scala/thumbnail/ThumbnailSpec.scala
- app-backend/app/src/test/scala/user/UserSpec.scala
Users should only be able to access public resources or resources they have access to.
To implement authorization, we first need authentication everywhere, and so:
_This is Auth Nation
Pledge your allegiance
Get y'all auth tees on
All auth everything
Auth cards, auth cars
All auth everything_
except `tokens`, `healthcheck`, and `config` as specified in #695 
\- [Jay-Z, kind of](https://play.spotify.com/track/2a8CtZyPdd8w2csZh7oxpc)
- `./scripts/console app-server ./sbt`
- `project app`
- `test`
Closes #695
> Authenticate everything except insecure endpoints

- README.md
- app-backend/app/src/main/scala/bucket/Routes.scala
- app-backend/app/src/main/scala/image/Routes.scala
- app-backend/app/src/main/scala/scene/Routes.scala
- app-backend/app/src/test/scala/bucket/BucketSpec.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/fields/UserFkFields.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/fields/VisibilityField.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Buckets.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Images.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Scenes.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Thumbnails.scala
Previously, the Bucket and Scenes endpoints would return all objects regardless of their owner, so all users could see each others' content. This adds automatic filtering to the Scene, Bucket, and Image list endpoints so that they only return items that are either marked `PUBLIC` or are owned by the user making the request.
Staging bucket library (no filtering):
Local bucket library (with filtering):
There is quite a bit that this PR does not do, namely:
* It doesn't create a comprehensive authorization solution, so there is currently no concept of read-only access; if a user can get the UUID of a resource, they can edit or delete it. Doing full-scale authorization is a larger task that probably requires some significant planning and refactoring (see the next item).
* It isn't as …
> Limit API lists to public / owned items

- app-backend/tile/src/main/scala/Main.scala
- docker-compose.yml
- nginx/Dockerfile
- nginx/etc/nginx/conf.d/airflow.conf
- nginx/etc/nginx/conf.d/app.conf
- nginx/etc/nginx/includes/security-headers.conf
- nginx/etc/nginx/nginx.conf
Puts the tile server service behind Nginx at `/tiles`. Also, consolidates the necessary security headers into an include that gets reused where needed.
Lastly, adds a stub health check to the tiler server so that ALB target groups can mark the service as healthy. This should be updated to better communicate the health of the tile service.
Resolves part of https://github.com/azavea/raster-foundry/issues/686
Bring up the `nginx` services, which will ensure that the `tile-server` is up as well. Then, interact with the `tile-server` health check through Nginx.
Bring services up:
```bash
vagrant@vagrant-ubuntu-trusty-64:/opt/raster-foundry$ ./scripts/bootstrap
vagrant@vagrant-ubuntu-trusty-64:/opt/raster-foundry$ docker-compose up nginx
rasterfoundry_redis_1 is up-to-date
Recreating …
```
> Reverse proxy to tiler from Nginx; add stub service health check

- .gitignore
- app-backend/tile/src/main/scala/Config.scala
- app-backend/tile/src/main/scala/LayerCache.scala
- app-backend/tile/src/main/scala/RfLayerId.scala
- app-backend/tile/src/main/scala/Routes.scala
- app-backend/tile/src/main/scala/StitchLayer.scala
- app-backend/tile/src/main/scala/image/ColorCorrect.scala
- app-backend/tile/src/main/scala/image/ColorCorrectParams.scala
- Add `rgb/histogram`endpoint to generate a color corrected histogram
- This endpoint takes the same params as the `rgb/{z}/{x}/{y}` endpoint
- Add `rgb/thumbnail` endpoint to generate a color corrected layer thumbnail
- This endpoint takes the same params as the `rgb/{z}/{x}/{y}` endpoint
- Can generate large thumbnails with arbitrary limit of `4096` pixels per side
- Adds tile caching before the rendering step, speeding up color correction responsiveness
- Changes URL structure to include organization and user id
- ex: `http://localhost:9900/tiles/<org_id>/<user_id>/<scene_id>/rgb/thumbnail?size=128&min=1000&max=50000&redBand=4&greenBand=3&blueBand=2`
- Renames `Render` to `ColorCorrect` forced by the fact that I need the tile before it gets turned to PNG. This appears to be a better …
> Add histogram and thumbnail endpoints in tiler app

- app-backend/ingest/src/main/scala/com/azavea/rf/ingest/Ingest.scala
- app-backend/ingest/src/main/scala/com/azavea/rf/ingest/model/OutputDefinition.scala
- app-backend/ingest/src/main/scala/com/azavea/rf/ingest/model/SourceDefinition.scala
- app-backend/ingest/src/main/scala/com/azavea/rf/ingest/model/package.scala
- app-backend/ingest/src/test/resources/awsJob.json
- app-backend/ingest/src/test/resources/localJob.json
- docs/ingest/README.md
This PR adds some missing parameters (overlooked and underspecified before).
We decided not to support this right now. Do not use `output.native`
Ingest specifications have been updated so that `cibuild` and `citest` scripts continue to work and exercise the functionality provided by this PR
Connects #697 
Connects #698
> Add Ingest Parameters

- app-frontend/src/app/core/services/project.service.js
- app-frontend/src/app/pages/library/projects/detail/projectScenes/projectScenes.controller.js
- app-frontend/src/app/pages/library/projects/detail/projectScenes/projectScenes.html
Adds the ability for a user to change the name of a project from the 'Library.Project.Scenes' page.
I don't know if the UX is optimal. For example, it would be nice to have the input field receive focus once the user clicks the edit button.
* Create a project or ensure that projects already exist
* Go to 'My Library' -> 'Projects'
* Click on a project
* Click the edit button next to the Project name and enter a new value for the project name, and click the check button (or hit enter)
* Click the edit button, make changes, and then click the 'x' instead of the check
Connects #742
> Add project name editing

- app-frontend/src/app/pages/browse/browse.controller.js
Filter scene requests using the `maxCreateDatetime` query parameter to ensure scenes ingested after the initial scene list is loaded do not create paging offset issues.
The timestamp that is used is created whenever the scene list is refreshed (i.e. any map extent change). This could be more useful for long sessions rather than creating a single time-stamp on page load.
* Monitor outgoing requests to ensure timestamp is being updated when scene list is refreshed.
* Directly set the timestamp with the `browse.controller.js` and analyze response to ensure that no later scenes are loaded.
Connects #743
> Filter scene query by createdAt

- docs/architecture/adr-0011-framework-for-tool-ui.md
Adds an ADR for the selection of a framework to build the Tool UI on top of. The chosen framework is JointJS, which was the [recommendation](https://github.com/azavea/modellab/issues/2) that was made in the ML project. Most of the legwork was done in the linked issue. I've re-evaluated the candidate libraries that were presented there, however, there haven't been significant changes to them since the initial research was completed (other than vis.js losing maintainers).
Feedback on this is greatly appreciated. In particular:
- I think I have a grasp of the context, but would like it to be reviewed and edited by those more familiar with Raster Foundry as a whole
- I am unsure as to the level of detail that would be preferred
@designmatty, could you verify that JointJS would be viable in …
> Write ADR for Tool UI framework

- app-frontend/src/app/components/leafletMap/leafletMap.controller.js
- app-frontend/src/app/pages/browse/browse.controller.js
- app-frontend/src/app/pages/browse/browse.html
App load causes one erroneous requests (wrong bounds) and then two duplicate requests (correct bounds).
Zoom events also cause duplicate events.
- Leaflet's `moveend` event is triggered by any map view change, including zoom related changes. Listening to the `zoomend` event becomes superfluous.
* Open up dev tools and filter down to only requests to the `scenes` endpoint
* Reload the app, ensure only one request to the scenes endpoint is issued
* Pan the map, ensure only one request to the scenes endpoint is issued
* Zoom the map, ensure only one request to the scenes endpoint is issued
Connects #745
> Eliminate extra and duplicate requests

- app-frontend/src/app/components/leafletMap/leafletMap.component.js
- app-frontend/src/app/components/leafletMap/leafletMap.controller.js
- app-frontend/src/app/pages/browse/browse.controller.js
- app-frontend/src/app/pages/browse/browse.html
For the browse and color correction scene lists, show the hovered scene's footprint on the map. This also adds a `bypassFitBounds` bound attribute that when `true` will skip changing the map extent to fit the footprint extent.
Waiting for some other work to be completed (#733) to do this for the color correction page.
* Hover over the scenes on the browse page and ensure the footprints are being displayed.
* Hover over the scenes on the color correction page and ensure the footprints are being displayed.
Connects #728
> WIP: Showing scene footprint on hover

- app-frontend/package.json
NVD3 is dependent on v3.4.4, not v4 of d3
Trivial, merging immediately
* Open color correction view and verify that nvd3 histogram renders
> Revert d3 dep to v3.4.4

- app-frontend/src/app/components/projectAddModal/projectAddModal.controller.js
Once you add scenes to a project, navigates to a page where you can see the results: either the project list if you added the scenes to multiple projects, or the project detail if you added it to 1
* In the `browse` or `library/scenes` view, add scenes to a single project. Clicking "add scenes" should navigate to the correct project once the operation is complete
* In the `browse` or `library/scenes` view, add scenes to multiple projects. Clicking "add scenes" should navigate to the project list
> Redirect from add-to-project modal to project list/detail

- app-tasks/rf/src/rf/ingest/ingest.py
- app-tasks/rf/src/rf/ingest/layer.py
- app-tasks/rf/src/rf/ingest/source.py
- app-tasks/rf/src/rf/models/base.py
- app-tasks/rf/src/rf/models/scene.py
Given a scene ID, will return a dict that can be serialized to a JSON ingest job definition.
Attached is a sample of the serialized output.
- Unsure if the file naming/location is ideal.
- Unsure of how to properly handle scenes that contain images with varying resolutions (being that the ingest definition is defining a cell-size at the layer level rather than the source level). For now, we are using the resolution of the first image within a scene.
- Unsure of how the URI of the layer will be handled, it is currently hard-coded
- There was no example I could find of `bandMaps` for images with multiple bands, so some assumptions were made.
* vagrant ssh into the dev VM
* `./scripts/server`
Separately:
* `docker-compose exec airflow-worker bash`
* `cd /opt/raster-foundry/app-tasks/rf/src/` …
> Create ingest definition from scene ID

- app-frontend/src/app/components/colorCorrectScenes/colorCorrectScenes.component.js
- app-frontend/src/app/components/colorCorrectScenes/colorCorrectScenes.controller.js
- app-frontend/src/app/components/colorCorrectScenes/colorCorrectScenes.html
- app-frontend/src/app/components/colorCorrectScenes/colorCorrectScenes.state.html
- app-frontend/src/app/pages/editor/project/projectEdit.controller.js
- app-frontend/src/app/pages/editor/project/projectEdit.html
The second half to resolve #728. For the project editing scene list, show the hovered scene's data footprint on the map.
Testing this is difficult until #774 is resolved. Once the map hits some errors, the footprints will not display.
Unlike the scene browser, there is no guarantee that the hovered scene is within the current map extent. As such, the user could hover over a scene and not see the footprint.
* Edit a project that can be successfully displayed on the edit page
* Hover over a scene in the scene list and see if footprint is visible.
Connects #728
> Display scene footprints on hover for color correction

- app-frontend/src/app/pages/library/projects/detail/projectScenes/projectScenes.html
- app-frontend/src/app/pages/library/projects/list/list.html
- app-frontend/src/app/pages/library/scenes/list/list.html
Using the page size returned by the server, hide the pagination controls when the result count does not exceed the page size.
* When having a number of projects or scenes that is less than the page size (10), see that the pagination does not appear.
Resolves #720.
> Hide pagination on editor lists when appropriate

- app-frontend/src/app/pages/library/projects/detail/projectScenes/projectScenes.html
- app-frontend/src/assets/styles/sass/components/_form.scss
- app-frontend/src/assets/styles/sass/pages/_library.scss
Cleans up the Project scene list view UI. Makes the title editor aligned better. Makes the scene selection tools appear in correct fashion. Moves scene download button into the scene selection toolbar.
> cleaned up project scene list ui

- app-frontend/src/app/components/channelHistogram/channelHistogram.controller.js
- app-frontend/src/app/components/colorCorrectAdjust/colorCorrectAdjust.controller.js
- app-frontend/src/app/components/colorCorrectPane/colorCorrectPane.controller.js
- app-frontend/src/app/components/colorCorrectPane/colorCorrectPane.html
- app-frontend/src/app/components/colorCorrectScenes/colorCorrectScenes.html
- app-frontend/src/app/core/services/layer.service.js
Hooks up histogram to endpoints to display real histogram of selected scenes with color corrections applied.
Color correction sliders start at their minimum, so any initial adjustment to the sliders throws off the color correction values.
Would also be beneficial to enforce some min-height of the histogram containing `div` so that loading would not be so jarring.
* Select scenes to color correct
* Enter color correction
* See that histogram loads
* Adjust sliders and ensure histogram updates
> Render actual histogram for first scene in cc

- app-frontend/src/app/components/colorCorrectScenes/colorCorrectScenes.component.js
- app-frontend/src/app/components/colorCorrectScenes/colorCorrectScenes.controller.js
- app-frontend/src/app/components/colorCorrectScenes/colorCorrectScenes.module.js
- app-frontend/src/app/components/colorCorrectScenes/colorCorrectScenes.scss
- app-frontend/src/app/components/colorCorrectScenes/colorCorrectScenes.state.html
- app-frontend/src/app/components/leafletMap/leafletMap.component.js
- app-frontend/src/app/components/leafletMap/leafletMap.controller.js
- app-frontend/src/app/components/mosaicScenes/mosaicScenes.controller.js
- app-frontend/src/app/core/services/project.service.js
- app-frontend/src/app/pages/editor/project/projectEdit.controller.js
- app-frontend/src/app/pages/editor/project/projectEdit.html
- app-frontend/src/app/pages/library/projects/list/list.controller.js
This implements part of the color correction wireframes which show an interface for selecting scenes by clicking grid cells displayed on the map. Because we don't need to show a count of scenes like we do on the browse page, I was able to get away with generating the grid by drawing a border around the Leaflet tiles.
There is also some general cleanup, including removing an unused hook from the `colorCorrectScenes` component, moving the logic for getting all of a Project's Scenes into the Project service, and fixing an incorrect query parameter in the `getProjectSceneCount` method that was causing it to unnecessarily return a full page of results. 
* Navigate to the color correction interface for a project containing the Egypt scenes.
* Zoom in until the scenes are spread across more than …
> Allow selecting scenes to color correct by grid

- app-frontend/src/app/components/channelHistogram/channelHistogram.controller.js
- app-frontend/src/app/components/colorCorrectAdjust/colorCorrectAdjust.html
- app-frontend/src/app/components/colorCorrectPane/colorCorrectPane.html
- app-frontend/src/app/components/colorCorrectPane/colorCorrectPane.state.html
- app-frontend/src/app/components/colorCorrectScenes/colorCorrectScenes.html
- app-frontend/src/app/components/colorCorrectScenes/colorCorrectScenes.state.html
- app-frontend/src/app/components/mosaicScenes/mosaicScenes.html
- app-frontend/src/app/components/mosaicScenes/mosaicScenes.state.html
- app-frontend/src/app/index.routes.js
- app-frontend/src/app/pages/editor/project/projectEdit.html
- app-frontend/src/assets/styles/sass/app.scss
- app-frontend/src/assets/styles/sass/base/_base.scss
- app-frontend/src/assets/styles/sass/base/_helpers.scss
- app-frontend/src/assets/styles/sass/components/_button.scss
- app-frontend/src/assets/styles/sass/components/_color-correct.scss
- app-frontend/src/assets/styles/sass/components/_dropdown.scss
- app-frontend/src/assets/styles/sass/layout/_container.scss
- app-frontend/src/assets/styles/sass/layout/_sidebar.scss
- app-frontend/src/assets/styles/sass/pages/_editor.scss
The color correction ui had many styling issues which made working with it very difficult.
- Fixes issue where number of scenes affected height of map
- Entire page no longer scrolls.
- Moves color correct button into actions dropdown, as its an action.
- Update styling of dropdowns within sidebar
- Cleaned up color correction histogram panel
- Additionally, applied same fixes as checkbox 1 and 2 to mosaic UI.
**Height of map no longer controlled by scene total**
**Cleaned up dropdowns & moved color correct action into actions dropdown**
**Cleaned up color correction panel**
This PR does not attempt to address the bulk of Mosaic issues. This is purely focused on Color Correction UI.
fixes #774
> cleaned up the color correction UI

- app-frontend/package.json
- app-frontend/src/app/components/leafletMap/leafletMap.component.js
- app-frontend/src/app/components/leafletMap/leafletMap.controller.js
- app-frontend/src/app/components/leafletMap/leafletMap.module.js
- app-frontend/src/app/components/maskItem/maskItem.component.js
- app-frontend/src/app/components/maskItem/maskItem.controller.js
- app-frontend/src/app/components/maskItem/maskItem.html
- app-frontend/src/app/components/maskItem/maskItem.module.js
- app-frontend/src/app/components/mosaicMask/mosaicMask.component.js
- app-frontend/src/app/components/mosaicMask/mosaicMask.controller.js
- app-frontend/src/app/components/mosaicMask/mosaicMask.html
- app-frontend/src/app/components/mosaicMask/mosaicMask.module.js
- app-frontend/src/app/components/mosaicMask/mosaicMask.scss
- app-frontend/src/app/components/mosaicMask/mosaicMask.state.html
- app-frontend/src/app/components/mosaicScenes/mosaicScenes.component.js
- app-frontend/src/app/components/mosaicScenes/mosaicScenes.controller.js
- app-frontend/src/app/components/mosaicScenes/mosaicScenes.html
- app-frontend/src/app/components/mosaicScenes/mosaicScenes.state.html
- app-frontend/src/app/components/sceneItem/sceneItem.component.js
- app-frontend/src/app/components/sceneItem/sceneItem.controller.js
- app-frontend/src/app/components/sceneItem/sceneItem.html
- app-frontend/src/app/index.components.js
- app-frontend/src/app/index.routes.js
- app-frontend/src/app/pages/browse/browse.controller.js
- app-frontend/src/app/pages/editor/project/projectEdit.controller.js
- app-frontend/src/app/pages/editor/project/projectEdit.html
Add a mosaic masking view.
There is currently no way to save / actually use the generated polygons / opacity slider
@designmatty I included a mosaicMask.scss file at `/app-frontend/src/app/components/mosaicMask/mosaicMask.scss` which can be deleted once you figure out how you want to do things there. 
* On the frontend, navigate to a project and click "edit"
* click "mosaic"
* click any scene to go to the masking view.  Its polygon should stay on the map
* Click the "Draw Mask" button in the sidebar to enable the drawing toolbar
* Draw some masks, and delete / edit them.  You should be able to delete them from both the toolbar and the side panel.  Masks …
> Add mosaic mask view

- app-frontend/src/app/components/colorCorrectPane/colorCorrectPane.controller.js
- app-frontend/src/app/pages/editor/project/projectEdit.controller.js
- app-frontend/src/app/pages/editor/project/projectEdit.html
Fits the map to the scenes being color-corrected. This will also cache the z-order of the layers, and then bring the scenes being color-corrected to the front. After editing is complete, the scenes are returned to their original z-order.
If layers previously have the same z-index param, their rendering order determined their 'actual' z-order. This 'actual' z-order is not maintained as the rendering order does not actual alter the `options.zIndex` property of the layer. In this case, the 'actual' z-order may change throughout the process of entering and exiting color-correction.
* Select a project that contains the Egypt scenes and go into edit mode
* Select a scene(s) and enter color correction
* Ensure the map alters its bounds to fit the scenes being editing
* Ensure the scenes being …
> Fit map to scenes being color-corrected

- app-backend/app/src/test/scala/tools/ToolSpec.scala
For whatever reason, the test suite was failing repeatedly when I run it locally after spinning up a fresh environment. Increasing the timeout to 3 seconds allowed all tests to pass repeatedly without issues.
Below is an example of the trace I was seeing before:
```
[info] /api/tools/
[info] - should reject creating tools without authentication
[info] - should create a tool with authorization *** FAILED ***
[info]   Request was neither completed nor rejected within 1 second (DynamicVariable.scala:58)
[info] - should require authentication for list
14:50:01.518 [com-azavea-rf-tooltag-ToolTagSpec-akka.actor.default-dispatcher-3] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
[ERROR] [12/20/2016 14:50:01.544] [com-azavea-rf-tool-ToolSpec-akka.actor.default-dispatcher-13] …
```
> Increase route test timeout to 3 seconds

- app-frontend/src/app/components/colorCorrectAdjust/colorCorrectAdjust.controller.js
Fix the min/max clipping slider
@designmatty Looks like the styling needs to be cleaned up a little here.  Also note that the animation for the min/max slider causes the dark portions of the slider bar to move with the mouse, while the actual marker lags behind.
* Open the project/edit view on a set of pre-processed egypt scenes
* Verify that the min/max clipping slider functions and affects the output image.
> Fix min/max slider in project/edit

- app-frontend/src/app/components/sceneDetail/sceneDetail.component.js
- app-frontend/src/app/components/sceneDetail/sceneDetail.html
- app-frontend/src/app/core/services/map.service.js
- app-frontend/src/app/pages/browse/browse.controller.js
- app-frontend/src/app/pages/browse/browse.html
- app-frontend/src/app/pages/editor/project/projectEdit.controller.js
- app-frontend/src/app/pages/library/projects/detail/scene/scene.controller.js
- app-frontend/src/app/pages/library/projects/detail/scene/scene.html
- app-frontend/src/app/pages/library/scenes/detail/detail.controller.js
- app-frontend/src/app/pages/library/scenes/detail/detail.html
Show the scene thumbnail on a map instead of using data footprints etc.
* Verify that you've loaded scene that contain tile footprints
* Navigate to a scene with a tile footprint in the scene browser / project scene list
* Verify that the thumbnail displays on the map (if no tile footprint is found, nothing will show)
* In the browse view, mouse over a scene and verify that the thumbnail shows on the map
* In a browse detail view, verify that the scene thumbnail is displayed on the map.
*  For scenes with multiple thumbnails, the highest resolution one should be displayed in the browse view, and the lower resolution one in the scene/detail view
Connects #683
> Show scene thumbnails on map instead of data footprint

- app-frontend/config/webpack/global.js
- app-frontend/package.json
- app-frontend/src/app/components/diagramContainer/diagramContainer.component.js
- app-frontend/src/app/components/diagramContainer/diagramContainer.controller.js
- app-frontend/src/app/components/diagramContainer/diagramContainer.module.js
- app-frontend/src/app/components/navBar/navBar.html
- app-frontend/src/app/index.components.js
- app-frontend/src/app/index.module.js
- app-frontend/src/app/index.routes.js
- app-frontend/src/app/index.vendor.js
- app-frontend/src/app/pages/lab/edit/edit.component.js
- app-frontend/src/app/pages/lab/edit/edit.controller.js
- app-frontend/src/app/pages/lab/edit/edit.html
- app-frontend/src/app/pages/lab/edit/edit.module.js
- app-frontend/src/app/pages/lab/lab.controller.js
- app-frontend/src/app/pages/lab/lab.html
- app-frontend/src/app/pages/lab/lab.module.js
- app-frontend/src/app/pages/lab/lab.scss
- app-frontend/src/app/pages/lab/run/run.component.js
- app-frontend/src/app/pages/lab/run/run.controller.js
- app-frontend/src/app/pages/lab/run/run.html
- app-frontend/src/app/pages/lab/run/run.module.js
Adds routes and pages for building and running models.
Only addresses the UI of the model building page.
Uses JointJS to demonstrate possible interaction at a shallow level as full JointJS integration is beyond the scope of this PR.
When you click the diagram element, the input pane is shown. Clicking on the diagram surface but not the diagram element will close the pane.
This PR adds pages for ModelLab (or whatever it is that we will end up calling it).
It adds the following routes:
- `/lab/run`
- `/lab/edit` (the default route for the Model lab link)
- Implementing a grid background and a colored background will require additional work, as the grid functionality in JointJS creates an svg and uses that as a background image, which overwrites any background color applied with styling. For …
> Add model builder page with example UI

- app-frontend/config/webpack/global.js
This commit fixes the production build styling by switching to the
extract text plugin for styles during production builds. There may be a
small performance penalty, but this solves the styling issue by ensuring
that all the styling is concatenated together into a single file. The
project's styles are applied last (the next sass style loader) so our
overrides will be preserved.
The problem was caused because the CSS styles for vendor assets were
being inlined and/or loaded via javascript based on our loader usage.
Development style assets maintained (inlined/called by javascript):
Production style assets:
* Start VM
* Run: `./scripts/console app-frontend "npm run build"`
* Start server: …
> Fix production build styling

- app-frontend/src/app/components/projectAddModal/projectAddModal.html
On the modal that allows a user to add selected scenes to a project, show the pagination only when appropriate (item count > page size).
* Ensure the pagination controls are not present with project item count below the page threshold
Connects #832
> Hide pagination on adding scenes to project modal

- app-frontend/src/app/components/mosaicParameters/mosaicScenesParameters.component.js
- app-frontend/src/app/components/mosaicParameters/mosaicScenesParameters.controller.js
- app-frontend/src/app/components/mosaicParameters/mosaicScenesParameters.html
- app-frontend/src/app/components/mosaicParameters/mosaicScenesParameters.module.js
- app-frontend/src/app/index.components.js
This commit adds the mosaic parameters page, unstyled.
Users should be able to do the following:
- choose between manual and automatic scene prioritization
- re-order scene prioritization strategies
- choose between project extent and manually drawing an extent
- draw extent
* Navigate to the mosaic page for a project
* Choose "Parameters"
* Exercise different parameter options (manual/automatic, re-arrange sorting parameters, drawing/deleting mask)
* Verify back button works as expected
> Add mosaic parameters page

- app-backend/app/src/main/resources/application.conf
- app-frontend/src/app/components/colorCorrectPane/colorCorrectPane.html
Uses a feature flag to hide the 'make source histogram' link within the color correction (just below the histogram). Defaults to hidden.
* Go to color correct and ensure the 'make source histogram' link is hidden (would be visible below the histogram).
* Go to the user accounts settings (`settings/account`) page and switch the feature flag for 'Show make source histogram link' to 'on'.
* Go back to color correction and ensure the link is now visible.
Resolves #827
> Add feature flag for 'make source histogram' in color correction

- app-backend/app/src/main/resources/application.conf
- app-frontend/src/app/components/toolItem/toolItem.html
- app-frontend/src/app/components/toolSearch/toolSearch.controller.js
- app-frontend/src/app/components/toolSearch/toolSearch.html
- app-frontend/src/app/core/core.module.js
- app-frontend/src/app/core/services/tool.service.js
- app-frontend/src/app/core/services/toolCategory.service.js
- app-frontend/src/app/core/services/toolTag.service.js
- app-frontend/src/app/index.routes.js
- app-frontend/src/app/pages/market/market.controller.js
- app-frontend/src/app/pages/market/market.html
- app-frontend/src/app/pages/market/search/search.controller.js
- app-frontend/src/app/pages/market/search/search.html
- app-frontend/src/app/pages/market/tool/tool.controller.js
- app-frontend/src/app/pages/market/tool/tool.html
- app-frontend/src/app/pages/market/tool/tool.module.js
- app-frontend/src/app/pages/market/tool/tool.scss
Adds functioning market search and tool details pages.
- the search page builds the proper url and requests, but the `tool` endpoint does not take these params into account, thus, all tools are returned no matter what the search is.
- the API also lacks previews and thumbnails for tools, so placeholders remain in certain spots
- there is no straightforward way of retrieving the related tools and categories of a given tool -- the tool and category area of the detail page is blank
- the backend model for tags does not include a slug (as the category does), yet we allow spaces and caps (according to the mock-ups) as the tag value. Because of this, we need an alternate delimiter that is not a space. I've made it a variable that can be altered, but it is currently a pipe. For consistency, both …
> Connect model market to API

- app-backend/database/src/main/scala/com/azavea/rf/database/tables/ToolCategories.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Tools.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/ToolCategory.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/ToolTag.scala
- app-frontend/src/app/components/navBar/navBar.html
- app-frontend/src/app/pages/market/tool/tool.html
- docs/swagger/spec.yml
Renames 'Model Lab' to 'Lab and 'Model Market' to 'Tool Catalog'.
Also adds a nav-bar link to 'Editor'.
The resulting order of the navigation links is:
- Scene Browser
- Editor
- Tool Catalog
- Lab
The `/editor` route is currently abstract. Clicking the link will take the user to the browse page. This would be addressed with #837.
* Ensure the updated nav links are as expected
Resolves #833
> Rename to 'Tool Catalog' and 'Lab'

- app-frontend/src/app/components/colorCorrectPane/colorCorrectPane.controller.js
- app-frontend/src/app/components/colorCorrectPane/colorCorrectPane.html
- app-frontend/src/app/components/colorCorrectPane/colorCorrectPane.module.js
- app-frontend/src/app/components/colorCorrectPane/colorCorrectPane.scss
Adds a loading indicator to the histogram container.
Maintains height of histogram container to minimize UI impact.
* Switch on dev tools network throttling if desired
* Enter color correction mode and ensure a loading indicator is shown before the histogram is displayed
Connects #829
> Add loading indicator to color correct histogram

- app-frontend/src/app/pages/browse/browse.controller.js
- app-frontend/src/app/pages/browse/browse.html
- app-frontend/src/assets/styles/sass/components/_button.scss
This PR implements a currently non-functioning select all button in the scene browser. 
I need dev support in making the button work. It should function exactly the same way as the select all button in the editor.
The button does not yet function. Developer support needed.
* Go the scene browser
* Select all button should appear in the footer of the sidebar next to selected scenes button.
Connects #836
> WIP: added nonfunctioning select all btn to scene browser

- app-frontend/src/app/pages/library/projects/detail/projectScenes/projectScenes.html
- app-frontend/src/app/pages/library/scenes/list/list.html
This is the front-end portion of the fixes for #865.
The back-end portion has proved to be more complex than anticipated. See that issue for more information.
* Once the webpack server is running, access the library/scenes/list route and ensure the scenes are loaded
* Log out and then reload the page
* Log in (there should be an error message with a 'Try Again' link)
* Click the 'Try Again' link and ensure the scene list is now loaded.
Connects #705
> Fix page param for 'try again' requests

- deployment/ansible/group_vars/jenkins
Ensure that we're at the most current version before attempting to update the VPC address range.
See: https://www.terraform.io/upgrade-guides/0-8.html
Review the output of [this](http://jenkins.staging.rasterfoundry.com/job/raster-foundry/job/raster-foundry/job/develop/138/) Jenkins job to ensure that is completed successfully.
Also, you can SSH into the Jenkins box and inspect the Terraform version:
```bash
$ ssh -l ubuntu jenkins.staging.rasterfoundry.com
ubuntu@ip-172-31-52-80:~$ terraform -v
Terraform v0.8.2
```
Connects:
- #799 
- #798
> Bump Terraform version to 0.8.2

- app-frontend/src/app/components/publishModal/publishModal.component.js
- app-frontend/src/app/components/publishModal/publishModal.controller.js
- app-frontend/src/app/components/publishModal/publishModal.html
- app-frontend/src/app/components/publishModal/publishModal.module.js
- app-frontend/src/app/components/publishModal/publishModal.scss
- app-frontend/src/app/index.components.js
- app-frontend/src/app/pages/editor/project/projectEdit.controller.js
- app-frontend/src/app/pages/editor/project/projectEdit.html
- app-frontend/src/app/pages/library/projects/detail/projectScenes/projectScenes.controller.js
- app-frontend/src/app/pages/library/projects/detail/projectScenes/projectScenes.html
Adds the publish modal and links to access it from both the project details page and the project edit page.
Does not actually implement any project publishing, just UI
- Some styling fixes are needed to provide vertically centered buttons within the editor nav-bar (as seen in the second screen shot)
- We may need a new icon for publish (if there is one, I didn't see it)
- I added a publish link to project details as that seems like a logical place for it as well
- @designmatty I added a stylesheet with some small fixes to improve the look and feel of the modal a bit (over mis-using current styles)
- We have to now load the project on the editor page, which we were not currently doing. There is no error feedback if this fails (the error message service will come into play) but the publish …
> Add publish modal to project details and editor

- app-backend/app/src/test/scala/project/ProjectSceneSpec.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/ScenesToProjects.scala
- app-frontend/src/app/components/colorCorrectAdjust/colorCorrectAdjust.controller.js
- app-frontend/src/app/components/colorCorrectAdjust/colorCorrectAdjust.html
- app-frontend/src/app/components/colorCorrectPane/colorCorrectPane.controller.js
- app-frontend/src/app/components/colorCorrectScenes/colorCorrectScenes.controller.js
- app-frontend/src/app/core/core.module.js
- app-frontend/src/app/core/services/colorCorrect.service.js
- app-frontend/src/app/core/services/layer.service.js
- app-frontend/src/app/pages/editor/project/projectEdit.controller.js
This PR persists and retrieves color corrections from the API. When a user loads a project, default color corrections are loaded if none can be retrieved. Changes to the RGB bands are synced with the API and the tiles are refreshed on demand. 
Most of the work was spent refactoring existing functions to use promises and cache changes where appropriate. Suggestions for how to improve this are welcome, I'm not entirely satisfied with it, but it works. 
I had to change the API slightly to get things to work, but I think a fair amount of work needs to be done in #880 to get this to match up with the existing API and semantics of the other endpoints. I didn't want to have this get too large, but this …
> Persist & Retrieve Color Corrections

- app-backend/database/src/main/scala/com/azavea/rf/database/fields/UserFkFields.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/fields/UserFkVisibleFields.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Images.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Projects.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Scenes.scala
This commit replaces the previous implementation of using a union of two
select statements with a filter that uses an OR condition to filter
records according to if the record is labeled as `PUBLIC` or is created by
the user making the API request.
A new trait is added that combines the user foreign key trait with the visibility one that
can be used for tables that have both a visibility field and foreign key for users.
Using the following request:
```
time curl 'http://localhost:9091/api/scenes?bbox=-127.26562500000001,-46.195042108660154,37.35351562500001,61.56457388515458&maxCloudCover=10&maxCreateDatetime=2017-01-06T03:57:28.361Z&minCloudCover=0&pageSize=20&sort=createdAt,desc' -H …
```
> Replace union with or filter for user visibility

- app-backend/app/build.sbt
- app-backend/app/src/main/resources/application.conf
- app-backend/app/src/main/scala/Main.scala
- app-backend/app/src/main/scala/utils/Config.scala
- app-backend/app/src/test/scala/DBSpec.scala
- app-backend/app/src/test/scala/utils/PGUtilsSpec.scala
- app-backend/build.sbt
- app-backend/database/src/main/resources/reference.conf
- app-backend/database/src/main/scala/com/azavea/rf/database/Config.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/Database.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/ColorCorrect.scala
- app-backend/migrations/src/main/resources/application.conf
- app-backend/tile/src/main/scala/Main.scala
- app-backend/tile/src/main/scala/Routes.scala
- app-backend/tile/src/main/scala/image/Mosaic.scala
- docker-compose.yml
Replaces the prototype multi-layer tiler with project mosaic tiler that pulls the `MosaicDefinition` from the DB.
Because database configurations are now used by `tiler` and `app` projects the slick related configurations have been moved to `database` project and one may now get a database instance using `Database.DEFAULT`.
Since we need to hit the DB, which is a semi-precious resource we must cache `ProjectId => MosaicDefinition` lookups, but they also may change rapidly based on user input. To handle this there is an optional `tag` URL parameter to mosaic endpoint that will be included in the cache lookup. This `tag` should be changed after the UI changes and the database is updated to force a cache refresh. Having some mechanism to trigger this refresh allows the cache to stay live for …
> Project Mosaic Tiler

- app-backend/build.sbt
GeoTrellis includes an old version of postgresql for its slick
extensions. Raster Foundry uses a newer version and when the two are
combined an assembly fails due to conflicts.
I favored this over a merge strategy solution because it allows ensuring
a more specific exclusion.
* Enter an `sbt` shell (`./scripts/console app-server bash`) and run assembly
> Exclude transitive postgresql dependency

- app-frontend/src/app/components/mapContainer/mapContainer.controller.js
- app-frontend/src/app/core/services/map.service.js
- app-frontend/src/app/pages/browse/browse.controller.js
Per #824, we need the option for dark basemaps so users with light image overlays can have nice looking labels
This doesn't do anything to style the control. I'm assuming @designmatty will work his magic on the basemap controls similar to what he did with the zoom controls, since this was added in the same pattern.
Also it turned out this is pretty easy, but that we've implemented a custom version in other places for style purposes.
* Bring up your front- and backends
* Switch basemaps a few times
* Add some scenes to the map and switch basemaps a few more times
Connects #824
> Add light vs dark basemap control to map

- app-frontend/src/app/components/navBar/navBar.html
- app-frontend/src/app/components/selectProjectModal/selectProjectModal.component.js
- app-frontend/src/app/components/selectProjectModal/selectProjectModal.controller.js
- app-frontend/src/app/components/selectProjectModal/selectProjectModal.html
- app-frontend/src/app/components/selectProjectModal/selectProjectModal.module.js
- app-frontend/src/app/index.components.js
- app-frontend/src/app/index.routes.js
- app-frontend/src/app/pages/editor/project/projectEdit.controller.js
Adds a modal that, when the user enters the editor from the top-level link, allows a user to select a project to edit.
We may want to consider providing a way for a user to switch projects more intuitively, such as a switch project button within the editor interface. Right now, when in the editor, the user must navigate back to their library, to the projects, view the project, then click edit.
* Enter the editor from the top-level link and ensure you are prompted to select a project.
* Ensure the modal does not reappear while actively editing a project
Connects #837
> Add project select modal to editor

- app-backend/app/src/test/scala/scene/SceneSpec.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/QueryParameters.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Scenes.scala
- app-frontend/src/app/core/services/gridLayer.service.js
- app-frontend/src/app/pages/browse/browse.controller.js
- docs/swagger/spec.yml
This adds a click interaction to the scene grid cells. When the user clicks an unselected grid cell, it is selected asthe active bbox filter. If the user holds `ctrl`, multiple grid cells can be selected.
We are beginning to have many use-cases for drawing polygons on the map. It may be time to start changing their color from the default leaflet blue into more meaningful colors depending on the context.
* Go the to scene browse page
* Click a scene grid cell and see that the scene list is updated
* Hold `ctrl` and click another cell, see that both cells are now selected and that the scene list is refetched. Repeat a few times.
* While still holding `ctrl`, click an already selected cell, see that it is deselected while maintaining the other selections and that the scene list is update
* …
> Add grid filter to scene browse

- app-backend/build.sbt
- app-backend/project/Dependencies.scala
- app-backend/project/Version.scala
- app-backend/project/plugins.sbt
- app-backend/tile/src/main/resources/application.conf
- app-backend/tile/src/main/scala/Config.scala
- app-backend/tile/src/main/scala/LayerCache.scala
- app-backend/tile/src/main/scala/StitchLayer.scala
- app-backend/tile/src/main/scala/image/Mosaic.scala
This introduces the use of memcached in the tile server. This requires a switch from scaffine caching library to scalacache. We bring in the elasticache aware memcache client: https://github.com/awslabs/aws-elasticache-cluster-client-memcached-for-java
Introduces new environment variables:
- `MEMCACHED_HOST`: default to `tile-cache.service.rasterfoundry.internal`
- `MEMCACHED_PORT`: default to `11211`
We still require caffine, which is now used through scalacache in order to perform in-memory caching for the tile readers and attribute stores. The story with attribute stores is a little strange because they maintain internal cache for the layer metadata attributes. This can be made less strange by writing a GeoTrellis AttributeStore mixin that does the caching in memcached.
The default …
> Use memcached in tile server

- app-frontend/src/app/components/diagramContainer/diagramContainer.component.js
- app-frontend/src/app/components/diagramContainer/diagramContainer.controller.js
- app-frontend/src/app/components/selectToolModal/selectToolModal.component.js
- app-frontend/src/app/components/selectToolModal/selectToolModal.controller.js
- app-frontend/src/app/components/selectToolModal/selectToolModal.html
- app-frontend/src/app/components/selectToolModal/selectToolModal.module.js
- app-frontend/src/app/core/services/gridLayer.service.js
- app-frontend/src/app/core/services/layer.service.js
- app-frontend/src/app/index.components.js
- app-frontend/src/app/index.routes.js
- app-frontend/src/app/pages/lab/edit/edit.controller.js
- app-frontend/src/app/pages/lab/edit/edit.html
- app-frontend/src/app/pages/lab/lab.controller.js
- app-frontend/src/app/pages/lab/lab.html
- app-frontend/src/app/pages/lab/run/run.controller.js
- app-frontend/src/app/pages/lab/run/run.html
- app-frontend/src/app/pages/lab/run/run.module.js
- app-frontend/src/app/pages/lab/run/run.scss
- app-frontend/src/app/pages/market/tool/tool.html
This adds a functioning NDVI tool.
- This only works on scenes that can also be color corrected as the proper endpoint is not yet ready
- The JointJS diagram is still naively implemented
- Using any band > 6 causes a 400 for the tiles. I don't think it is worth the time to catch the errors and display a message since this is a temporary implementation.
- The returned tiles are transparent, which causes some visual issues when the tiles overlap (very apparent in the screen shots)
- I added an 'Apply' button to the tool controls to reduce load on the tile server.
Developing this made me think that we may want to consider making the active project a top-level concept rather than a parameter of routes further down the route tree. We have several spots where we select and maintain an active …
> Implement shallow NDVI tool

- app-frontend/src/app/core/services/map.service.js
Adds a check to ensure controls are only added once per map.
* Ensure no map (the editor map specifically) has only one set of controls
Connects #898
> Prevent duplicate controls on map

- app-frontend/src/app/components/colorCorrectScenes/colorCorrectScenes.controller.js
- app-frontend/src/app/components/colorCorrectScenes/colorCorrectScenes.html
- app-frontend/src/app/components/colorCorrectScenes/colorCorrectScenes.scss
Utilized an `L.gridLayer` to achieve a finer selection resolution (16x).
Also implements multiple grid selection to match browse scene grid filter.
Scenes cannot be selected until the scene tiles have finished loading (parallel request limit) as we depend on server-side filtering of scenes by bbox.
* Select a project of 'Egypt' scenes
* Go to the editor
* Check that you can select one grid cell
* Check that by holding `ctrl` you can select multiple grid cells
* Check that clicking an already selected grid cell will deselect the grid cell
* Check that when you enter color-correction adjustment, the selection polygons are removed from the map
Connects #849, #851, #852
> Make color correction selection grid finer

- app-frontend/src/app/components/colorCorrectScenes/colorCorrectScenes.controller.js
- app-frontend/src/app/components/filterPane/filterPane.component.js
- app-frontend/src/app/components/filterPane/filterPane.controller.js
- app-frontend/src/app/components/filterPane/filterPane.html
- app-frontend/src/app/pages/browse/browse.controller.js
- app-frontend/src/app/pages/browse/browse.html
Fixes bbox not being retained between reloads. Also makes the filter pane 'close' button work and fixes some missed JSDoc params.
* Zoom into a spot on the browse map, reload, and ensure you are returned to the same spot
* Open the filter pane and ensure it can now close via the 'close' button.
Connects #912
> Retain bbox query parameter and tiny fixes

- app-backend/tile/src/main/resources/logback.xml
- app-frontend/src/app/components/filterPane/filterPane.html
- app-frontend/src/app/core/core.module.js
- app-frontend/src/app/core/services/imageOverlay.service.js
- app-frontend/src/app/core/services/map.service.js
This PR includes functionality to clip thumbnails to nearly include _just_ the data and exclude no data areas for thumbnails based on the geometry of the data footprint.
This is done by extending the existing [Leaflet Image Overlay] layer and replacing the tile drawing functions with a custom one. This custom layer uses canvas to draw a shape using the data footprint geometry and then uses the thumbnail as a fill image for the drawn canvas polygon. Almost all the areas that are no data should be excluded as a result.
Also fixes styling for filters when none are clicked.
Selected scenes on this branch:
Clipping nodata from thumbnails does not quite line up and the  problem appears to get worse …
> Approximately Clip Thumbnails to Data Footprint

- app-frontend/src/app/components/selectedScenesModal/selectedScenesModal.controller.js
- app-frontend/src/app/components/selectedScenesModal/selectedScenesModal.html
- app-frontend/src/app/core/services/map.service.js
- app-frontend/src/app/pages/browse/browse.controller.js
This fixes some thumbnail bugs, such as thumbnails remaining on the map after their scene is selected and then the select all button is used, or thumbnails persisting on the map after the respective scene is de-selected from the modal.
* Hover over scenes on the browse page and ensure thumbnails are displayed
* Select a scene, ensure its thumbnail is displayed and persisted when the mouse leaves the scene's element
* Click the select all button, ensure all thumbnails are displayed
* Click the select all button again, ensure no thumbnails are displayed
* Select some scenes, then click the selected scene button to open the modal
* De-select some scenes from there, make sure those changes are persisted to the browse page and the the thumbnails are removed
* Select more scenes again, open the …
> Fix browse scene thumbnail persistence

- app-frontend/src/app/components/diagramContainer/diagramContainer.controller.js
This lays out the diagram for the NDVI change process. It contains some lightweight abstractions to make diagram generation easier, and includes the automatic layout function.
* Open up the lab and check that the diagram is drawn as expected.
This is replacing the NDVI tool diagram. We may want to add a migration for this tool so that we at least have a logical path to get to it.
> Add diagram for NDVI Change

- app-frontend/src/app/pages/library/library.html
Removes the 'mosaics' and the 'tool outputs' links from the library menu. Also renames 'My Scenes' to 'Scenes' to match the rest of the interface verbiage.
Before:
After:
* Look at the library...
> Remove unused links in library

- app-frontend/src/app/components/navBar/navBar.controller.js
- app-frontend/src/app/components/navBar/navBar.html
- app-frontend/src/app/components/selectProjectModal/selectProjectModal.controller.js
- app-frontend/src/app/components/selectProjectModal/selectProjectModal.html
- app-frontend/src/app/components/selectToolModal/selectToolModal.controller.js
- app-frontend/src/app/components/selectToolModal/selectToolModal.html
- app-frontend/src/app/pages/editor/project/projectEdit.controller.js
- app-frontend/src/app/pages/lab/lab.controller.js
Refactors how transitions to the lab and editor handled getting required user input: selecting the current tool and selecting the current project, respectively. Now, when normally navigating through the app, the modals that get the required input from the user occur on the current page so that the user can exit the modal, which was before un-allowed.
These operations might ideally integrated into the UI better (not a modal).
I retained the dead-end functionality if the user _somehow_ gets to a certain route (changing the URL manually) without a required entity being selected. This should almost never occur.
* Click the `Editor` link and check that you are not forced to select something and can exit the modal
* Click the `Lab` link and check that you are not forced to select something and …
> Refactor dead-end modals to lab and editor

- app-frontend/src/app/components/diagramContainer/diagramContainer.component.js
- app-frontend/src/app/components/diagramContainer/diagramContainer.controller.js
- app-frontend/src/app/components/diagramContainer/diagramContainer.html
- app-frontend/src/app/components/diagramContainer/diagramContainer.module.js
- app-frontend/src/app/components/diagramContainer/diagramContainer.scss
Add context menus to each diagram cell. Context menus can be individually defined for any cell, or can be set to a default context menu. Each context menu item can define a callback. Only one context menu is shown at a time.
Didn't do anything to handle cases where a cell would not have a context menu. Best way to handle this in the future would be to specifically set the context menu for that cell id to `false` and adjust context menu display to handle the `false` value.
The context menus have been tested to properly execute their callbacks, but for now, the default callbacks are empty.
* Go to the lab and click on diagram nodes, see that the context menu appears when you click a cell.
* Click outside of any cell to deselect it and hide it's context menu.
* Click the 'NDVI - Before' cell …
> Add context menus and selected cell to diagram

- app-frontend/src/app/components/colorCorrectPane/colorCorrectPane.component.js
- app-frontend/src/app/components/colorCorrectPane/colorCorrectPane.controller.js
- app-frontend/src/app/components/colorCorrectScenes/colorCorrectScenes.component.js
- app-frontend/src/app/components/colorCorrectScenes/colorCorrectScenes.controller.js
- app-frontend/src/app/core/services/layer.service.js
- app-frontend/src/app/core/services/project.service.js
- app-frontend/src/app/pages/editor/project/projectEdit.controller.js
This PR requests a mosaic of all scenes in a project from the tile server instead of requesting each scene individually. As a result we only add one layer to the map for the scenes in a project instead of one per scene.
No gifs because they looked terrible after fuzzing and I didn't want to upload 80mb images
* Bring up your front- and backends
* Open dev tools and start recording network activity
* Go to the editor for a project on the correctable Egypt scenes
* Select some scenes and then color correct them
* Verify that the mosaic redraws with color correction changes and that the requests are going to `/tiles/`
Connects #825
> use mosaic tile server

- app-frontend/src/app/components/diagramContainer/diagramContainer.controller.js
- app-frontend/src/app/components/diagramContainer/diagramContainer.scss
- app-frontend/src/app/components/projectItem/projectItem.html
- app-frontend/src/app/components/selectProjectModal/selectProjectModal.html
- app-frontend/src/app/pages/lab/edit/edit.controller.js
- app-frontend/src/app/pages/lab/edit/edit.html
- app-frontend/src/app/pages/lab/lab.scss
Adds an input parameters side-bar to the lab
I decided to hide the band selection controls until after a 'valid' input project is selected as they are sequential and one depends on the other. I used this as an opportunity to present the requirements of the tool. Once an initial project is selected, the UI matches the mockups fairly closely.
* Go to the 'Lab' and select the NDVI tool
* See that a sidebar is now visible
* Test that a project can be selected
* Test that a project can be changed
> Create input parameters sidebar

- README.md
- app-frontend/src/app/components/colorCorrectPane/colorCorrectPane.component.js
- app-frontend/src/app/components/colorCorrectPane/colorCorrectPane.controller.js
- app-frontend/src/app/components/colorCorrectPane/colorCorrectPane.state.html
- app-frontend/src/app/components/colorCorrectScenes/colorCorrectScenes.controller.js
- app-frontend/src/app/core/services/scene.service.js
Our belief that the color-correction's "zoom to selected" functionality was broken seems to have stemmed from UX; because the whole scene list doesn't fit on the screen at the same time, it was easy to unwittingly select multiple scenes using the grid-select functionality, which would then give the impression that the map wasn't zoomed in enough, or zoomed out too far. This adds functionality to persist the footprints of any selected scenes on the map so that the area covered by the selected scenes is clearer.
- ~WIP because I still need to remove the footprints when switching to the Mosaic pane.~
* Start up `yarn run start` and `./scripts/server`
* Navigate to the color correction interface for the Egypt scenes
* Select and deselect scenes through various methods (grid select, select-all …
> Persist Scene footprints when selected for color correction

- app-backend/app/build.sbt
- app-backend/app/src/main/scala/healthcheck/Routes.scala
- app-backend/app/src/main/scala/utils/Rollbar.scala
- app-backend/app/src/main/scala/utils/UserErrorHandler.scala
This PR adds rollbar support to the app server so we can see errors that occur in staging while we're not paying attention to them
This is sort of minimal for now but is designed to be extensible when we want more. We may want routing-aware `Exception` classes that know different things about the contexts in which they occur than what the base exception classes know (like the URL endpoints where they occur, for example
* Get the development `.env` file from S3
* Go to `healthCheckRoutes` and throw an error on purpose, e.g., replace `healthCheckRoutes = ...` with
```scala
val healthCheckRoutes = handleExceptions(healthCheckExceptionHandler) {
pathEndOrSingleSlash {
get {
throw new Exception("words …
```
> Add rollbar to app-server

- app-frontend/config/webpack/global.js
- app-frontend/src/app/core/services/auth.service.js
- app-frontend/src/tpl-index.html
This change adds a heap loading string to the application's <HEAD> tag that
connects the app either to the production or dev heap event tracking dashboard.
What it does: add heap
Why we need it: creepily specific tracking data about our users
~I tried adding a `heap.identify` call to the `auth-service` so we'd have nicer user IDs, but there's something about webpack + es6 + asynchronous library loads maybe that made that not work, at least if it's like this [Raygun issue](https://raygun.com/forums/thread/56624) in IE11 (??).~
Just kidding it totally works I don't know why webpack kept complaining
* Get the heap user/pass info from me
* Start up your front- and backends
* Log in and do some stuff
* …
> Add heap to app-frontend

- app-backend/database/src/main/scala/com/azavea/rf/database/Database.scala
The connection timeout for our database connection pool was initially set too low, which in conjunction with the number of threads allocated for Slick, caused many of the Slick threads to spin in a parked state while eating up all of the available CPU.
These changes reduce the overall number of threads to 5 ((2 * CPU Cores) + 1) and remove the explicit 2000ms connection timeout in favor of the 30s default.
This will hopefully go away:
- Login to staging
- Go into the editor of a project with the scenes from Egypt
- Color correct them in any way you like
- Interact with the map tiles (zoom in/out, pan around)
- Note holes in the map or slow load times (with 1 tiler instance, requests can take 3-4 seconds, but they don't hang indefinitely)
> Fix tiler deadlocks when interacting with the database

- app-frontend/src/app/components/filterPane/filterPane.controller.js
- app-frontend/src/app/components/filterPane/filterPane.html
- app-frontend/src/app/index.routes.js
Adds a day-of-month range filter to the front-end.
This does not add the backend code to actually get a set of scenes within the range, this only sends and persists the query params.
* Open the filter pane on the browse page
* Adjust the day-of-month filter
* Verify that the params have been added to the url
> Add day-of-month range filter

- app-frontend/src/app/components/colorCorrectAdjust/colorCorrectAdjust.controller.js
- app-frontend/src/app/components/colorCorrectAdjust/colorCorrectAdjust.html
- app-frontend/src/app/components/colorCorrectAdjust/colorCorrectAdjust.module.js
- app-frontend/src/app/components/colorCorrectAdjust/colorCorrectAdjust.scss
- app-frontend/src/app/components/toggle/toggle.component.js
- app-frontend/src/app/components/toggle/toggle.controller.js
- app-frontend/src/app/components/toggle/toggle.html
- app-frontend/src/app/components/toggle/toggle.module.js
- app-frontend/src/app/components/toggle/toggle.scss
- app-frontend/src/app/index.components.js
Add toggles to color correction to enable/disable types of filters
Some styling is needed
@designmatty I added `src/components/colorCorrectAdjust/colorCorrectAdjust.scss` to position the toggles, and `src/components/toggle/toggle.scss` for the toggle styling.
I think that it will be a lot more clear when things are toggled off once the sliders change color correctly
* Select some scene and go to the color correct page
* Open the network tab of your browser's dev tools
* Toggle a section
* Verify that the post request sent for each scene has the correct values set to null
> Add toggles to disable color correction filters by group

- app-frontend/package.json
- app-frontend/src/app/components/diagramContainer/diagramContainer.component.js
- app-frontend/src/app/components/diagramContainer/diagramContainer.controller.js
- app-frontend/src/app/components/diagramContainer/diagramContainer.html
- app-frontend/src/app/components/diagramContainer/diagramContainer.scss
- app-frontend/src/app/components/mapContainer/leaflet-side-by-side.js
- app-frontend/src/app/components/mapContainer/mapContainer.module.js
- app-frontend/src/app/components/navBar/navBar.controller.js
- app-frontend/src/app/core/core.module.js
- app-frontend/src/app/core/services/mousetip.service.js
- app-frontend/src/app/pages/lab/edit/edit.controller.js
- app-frontend/src/app/pages/lab/edit/edit.html
- app-frontend/src/app/pages/lab/edit/edit.module.js
- app-frontend/src/app/pages/lab/edit/edit.scss
- app-frontend/src/app/pages/lab/lab.html
- app-frontend/src/app/pages/lab/run/run.controller.js
- app-frontend/src/app/pages/lab/run/run.html
- app-frontend/src/app/pages/lab/run/run.module.js
- app-frontend/src/app/pages/lab/run/run.scss
- app-frontend/yarn.lock
This PR does many things:
- Refactors context menu code to render correctly in spite of angular's attempts to do the opposite
- Adds the side-by-side leaflet control (see notes)
- Adds a mousetip (a tooltip but travels with mouse) service
- Adds a preview map that will show a single node's output or compare two nodes' output
The leaflet side-by-side control is developed to be used with browserify and attempting to use that within the webpack context blew up leaflet. The only way I managed to get the control to cooperate was to use a special build of the side-by-side control and put it directly into the codebase. It's ugly, but it works.
@designmatty, the preview slider is not styled, but can be if we strip out the stylesheet injected by the `leaflet-side-by-side.js` file. Also, the …
> WIP: Add diagram node preview and comparison

- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/Scene.scala
Join was causing image links to be duplicated
* Start server
* Open a landsat scene and verify that it only has 11 images, instead of 22
Connects #957
> Fix duplicated image links by adding "distinct" to query

- app-backend/tile/src/main/scala/image/Mosaic.scala
- app-frontend/src/app/core/services/layer.service.js
Tile server wasn't using tags correctly to determine whether to cache
Mosaic.raw no longer caches by default - this code will be ripped out at some point anyways later on.
Currently, the frontend will use the time that the color correction settings were last changed in the cache key. This can be changed to something else, like a publish key if needed.
* Go to the project editor using a project with ingested scenes.
* Edit the color correction settings
* wait for about half of the tiles to load
* change the settings
* Previously, it would start loading the new settings alongside the old tiles, then refresh and cause some inconsistencies.  With the new caching behaviour, it should instead continue …
> Use tag for caching mosaicDefinition, default to none

- app-frontend/src/app/components/colorCorrectScenes/colorCorrectScenes.controller.js
- app-frontend/src/app/components/colorCorrectScenes/colorCorrectScenes.html
- app-frontend/src/app/core/services/layer.service.js
- app-frontend/src/app/pages/editor/project/projectEdit.controller.js
- app-frontend/src/assets/styles/sass/components/_dropdown.scss
Show which false color composite is in use
The selection does not update until the layer has switched to the new one - it reflects what's on the map
@designmatty I added a `.active` class selector in `app-frontend/src/assets/styles/sass/components/_dropdown.scss` for selected menu items
* Go to the the color correction page
* Click the dropdown menu and verify that it initializes to the correct one (may need to wait for layer to load)
* Click another composite, and wait for the map to update. The highlighted menu item should be changed as soon as the new tiles start to load.
Closes #973
> Show selected false color composite in dropdown

- app-frontend/src/app/components/filterPane/filterPane.controller.js
- app-frontend/src/app/components/filterPane/filterPane.html
This PR first adds a single year filtering mode to the browse page. 
As shown in the demos below, this introduces a concept of year filtering modes, starting with 'single' and 'range'. Only one mode can be active at a time.  I've attempted to create an intuitive flow from range to single. The switching flow is:
Switching from 'range' to 'single':
- The range's minimum value is cached
- The range's maximum year is set as the single active filtering year
Switching from 'single' to 'range':
- If there is a minimum value cached, we bring it back as the range min
- The current single year value is used as the max
There are edge cases that don't follow these rules, but I think they are handled logically:
- When the single year is set at the minimum allowable
- When the single year is set as …
> Add initial filter values and single year filter mode

- app-backend/build.sbt
- app-backend/tile/src/main/scala/Main.scala
- app-backend/tile/src/main/scala/Router.scala
- app-backend/tile/src/test/scala/auth/AuthSpec.scala
Brings back authentication to the Tile Server.
I'm looking into adding a test for this.
* Bring up / restart `./scripts/server`
* navigate to a page for an ingested dataset (Yosemite works well) that displays tiles (Share, Color Correction, etc.).
* Use the web inspector to copy a `curl` link for one of the tiles that is loaded.
* Open a terminal and paste in the copied link; I recommend redirecting to a file (`... > tile.png`) so that you don't get a bunch of binary garbage in your terminal.
* Edit the `curl` command to remove the `?token=` parameter and confirm that you get an error message about the token parameter being required.
* Edit the `curl` command to add the `?token=` parameter but with an invalid token and confirm you get an error message about the token being invalid.
* Open …
> Fix Tile Authentication

- app-frontend/src/app/components/filterPane/filterPane.controller.js
- app-frontend/src/app/components/navBar/navBar.html
- app-frontend/src/app/components/publishModal/publishModal.controller.js
- app-frontend/src/app/components/publishModal/publishModal.html
- app-frontend/src/app/core/services/project.service.js
- app-frontend/src/app/index.module.js
- app-frontend/src/app/index.routes.js
- app-frontend/src/app/pages/editor/project/projectEdit.controller.js
- app-frontend/src/app/pages/lab/run/run.scss
- app-frontend/src/app/pages/library/projects/detail/projectScenes/projectScenes.controller.js
- app-frontend/src/app/pages/share/share.controller.js
- app-frontend/src/app/pages/share/share.html
- app-frontend/src/app/pages/share/share.module.js
This PR adds a share page that will display the most recent output of a project. It also updates the publish modal to provide links to the share page.
This PR also wraps a small CSS adjustment to make sure the zoom control buttons work on the lab run map.
In order to better simulate what the share page looks like non-registered users, there is a flag called `testNoAuth` within the share page controller.
* Ensure you have a project containing ingested scenes (the yosemite scenes work well)
* From the project editor, with your ingested scene project active, click the 'Publish' button
* Check that the modal appears, and has the correct URLs
* Click the 'Preview Your Published Project' button, and ensure you are taken to the share page
* Access the project through the library, and click the …
> Add share page

- docker-compose.swagger.yml
- docker-compose.yml
- scripts/console
- scripts/server
Move the `swagger-editor` and `swagger-ui` services into their own Docker Compose configuration file. In addition, update the `console` and `server` scripts to work with those changes.
Resolves #964
Within one SSH session into the virtual machine, run `server` with no arguments:
```bash
vagrant@vagrant-ubuntu-trusty-64:/opt/raster-foundry$ ./scripts/server
```
In another session, run `docker ps` to confirm that the Swagger services are not running:
```bash
vagrant@vagrant-ubuntu-trusty-64:/opt/raster-foundry$ docker ps --format 'table {{.Names}}'
NAMES
rasterfoundry_nginx_1
rasterfoundry_tile-server_1
rasterfoundry_app-server_1
rasterfoundry_app-frontend_1
rasterfoundry_memcached_1
rasterfoundry_postgres_1
```
Go through the same process again, except this time append the `--with-swagger` …
> Split Swagger services out into their own Docker Compose config

- app-frontend/src/app/pages/lab/run/run.controller.js
Appends token to tile query requests. This broke once tile authentication was fixed, but only noticed once that fix got merged.
* Load yosemite scenes in lab and verify that all node comparisons/views work
> Add token param to tile requests in lab

- app-frontend/package.json
Add `--bail` option to the `webpack` command executed within `cibuild` so that the first failure it encounters causes the entire build process to fail.
In addition, remove the `--progress` flag because it leads to too much noise in the build output.
Resolves #967 
Use `console` to strategically remove a directory (the same from the Jenkins build failure logs) from within the `node_modules` directory and then attempt a static bundle build. Ensure that the exist status returned is not zero.
```bash
vagrant@vagrant-ubuntu-trusty-64:/opt/raster-foundry$ ./scripts/console app-frontend /bin/bash
root@dd016d8ac87d:/opt/raster-foundry/app-frontend# rm -rf /opt/raster-foundry/app-frontend/node_modules/node-sass/vendor/
root@dd016d8ac87d:/opt/raster-foundry/app-frontend# exit …
```
> Instruct Webpack to halt and report failures as soon as they occur

- deployment/ansible/group_vars/all
- deployment/ansible/roles.yml
The newest Amazon ECS AMI adds support for Docker 1.12 and these changes are to keep our development environment inline.
In addition, Docker Compose has been upgraded to version 1.9.0, which shouldn't impact the way we use Compose. However, it does open up the possibility of upgrading our `docker-compose.yml` spec to version 2.1, which would opt us in to newer functionality.
Provision the Vagrant virtual machine using this branch and ensure that new versions of Docker and Docker Compose are installed. Also, ensure that all of the services still come up properly:
```bash
$ vagrant up --provision
$ vagrant ssh
vagrant@vagrant-ubuntu-trusty-64:/opt/raster-foundry$ docker --version
Docker version 1.12.6, build 78d1802
vagrant@vagrant-ubuntu-trusty-64:/opt/raster-foundry$ docker-compose …
```
> Bump versions of Docker Engine and Compose

- app-backend/database/src/main/scala/com/azavea/rf/database/Database.scala
Sets a `leakDetectionThreshold` for the database connection pool. This will alert us to any potential connection leaks as they happen.
- Add this line to `Database.scala`
```diff
diff --git a/app-backend/database/src/main/scala/com/azavea/rf/database/Database.scala b/app-backend/database/src/main/scala/com/azavea/rf/database/Database.scala
index eeaaab2..d1d73ce 100644
--- a/app-backend/database/src/main/scala/com/azavea/rf/database/Database.scala
+++ b/app-backend/database/src/main/scala/com/azavea/rf/database/Database.scala
@@ -41,4 +41,5 @@ class Database(jdbcUrl: String, dbUser: String, dbPassword: String) {
object Database extends Config {
def DEFAULT = new Database(jdbcUrl, dbUser, dbPassword)
+ …
```
> Set leakDetectionThreshold

- app-backend/build.sbt
- app-backend/tile/src/main/scala/LayerCache.scala
- app-backend/tile/src/main/scala/RfLayerId.scala
- app-backend/tile/src/main/scala/Router.scala
- app-backend/tile/src/main/scala/StitchLayer.scala
- app-backend/tile/src/main/scala/directives/TileErrorHandler.scala
- app-backend/tile/src/main/scala/image/Mosaic.scala
- app-backend/tile/src/main/scala/routes/MosaicRoutes.scala
- app-backend/tile/src/main/scala/routes/SceneRoutes.scala
- app-backend/tile/src/main/scala/routes/ToolRoutes.scala
- app-frontend/src/app/core/services/layer.service.js
- app-frontend/src/app/core/services/project.service.js
- app-tasks/Dockerfile
Formerly, layer data was organized on S3 based on the username and organization of the user owning the layer; the username and organization ID were included in each tile URL in order to allow the tiler to determine the S3 location of the layer data. However, this had several drawbacks, including prohibiting non-URL-safe usernames and potentially causing duplication of layer data ingested by different users. This removes the organization ID and the Username from tile URLs and relies on the `ingestLocation` field on the Scenes object in order to find the location on S3 of the layer data.
* Fire up the server and head to color correction for any Project which is ingested (e.g. Yosemite).
* You should not see any tiles; this is because none of the existing Scenes in the database have values …
> Simplify tiler URLs

- app-backend/app/src/main/scala/scene/QueryParameters.scala
- app-backend/app/src/test/scala/scene/SceneSpec.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/QueryParameters.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Scenes.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/IngestStatus.scala
- docs/swagger/spec.yml
Allow filtering scenes on one or multiple ingest statuses
* Run `./scripts/test` and verify that the filter on ingests tests run and pass
* Run `./scripts/psql` and set the ingest status of a couple scenes like this: `update scenes set (ingest_status) = ('INGESTED') where id = {uuid};` so you have something to filter on
* Make a request to the scenes endpoint with a `ingestStatus=INGESTED` query param defined and verify that the scenes you've changed are returned
Closes #983
> Create scene filter for ingestStatus

- app-frontend/src/app/pages/editor/project/projectEdit.controller.js
- app-frontend/src/app/pages/editor/project/projectEdit.html
This PR adds a functioning project select modal to the project dropdown.
It feels like the wording should be 'Switch Project' instead of 'Open Project'. Open made me think 
it might be intended to open the project details page.
* Go to the editor
* Open the dropdown by clicking on the current project name
* Ensure you can change project after clicking 'Open Project'
* Check that the current project appears selected
> Add project select modal in editor

- app-frontend/src/app/pages/editor/project/projectEdit.controller.js
Fixes a linting error that prevented the build from completing successfully
* Verify that project switching works correctly in editor and webpack does not complain about boolean checking
> Remove redundant boolean check in editor

- app-tasks/dags/ingest/ingest_project_scenes.py
- docker-compose.airflow.yml
This is a stubbed out Airflow DAG for ingesting Scenes that have been added to Projects.
Successful run:
Failed run:
This is structured as a single DAG that submits a single Spark job to ingest all necessary Scenes. That seemed to fit my understanding of how ingests work, but if I misunderstood something or if things change, then it might be better to use a structure more like the Sentinel2 import, which has one DAG to discover Sentinel2 data that in turn kicks off a series of DAGs to do the actual importing.
I had to make some changes to the `docker-compose.yml` files in order to get Airflow working because the Redis server isn't currently being treated as a hard dependency of anything and therefore wasn't launching with `./scripts/server`.
* Launch the Airflow stack with …
> Add stubbed DAG for ingesting Scenes

- app-backend/app/src/main/resources/application.conf
- app-backend/app/src/main/scala/Router.scala
- app-backend/app/src/main/scala/thumbnail/Routes.scala
- app-backend/app/src/main/scala/utils/Config.scala
- app-backend/build.sbt
- app-backend/common/src/main/scala/S3.scala
- nginx/etc/nginx/conf.d/app.conf
- ~~adds a `common` subproject (this is the first commit and will be dropped in favor of #1025)~~
- adds an endpoint (`thumbnails`) that, with a proper auth token, will allow users to access thumbnails that are stored on S3
~~As mentioned above, once #1025 is merged, the `common` subproject commit will be dropped and this will be rebased.~~
* Retrieve a valid token param (can go to a tiling page, such as the editor, and inspect the requests)
* Make sure you have the latest `.env` and restart your dev environment
* Using something like Postman (so you can see the image instead of binary data), send a request to `/thumbnails/4b46eecb-9dd9-45e3-b0fb-a7b5f1b5f2b5.jpg?token=<token>`. You should get the thumbnail back. (Note: this is a test thumbnail)
* Change a portion …
> Private thumbnail proxy

- app-backend/build.sbt
- app-backend/ingest/src/main/scala/com/azavea/rf/ingest/CommandLine.scala
- app-backend/ingest/src/main/scala/com/azavea/rf/ingest/Ingest.scala
- app-backend/ingest/src/main/scala/com/azavea/rf/ingest/util/Testing.scala
Layer deletion prior to ingest is a desirable feature in cases where prior ingests may have been incorrectly specified. This PR adds the `--overwrite` flag to the ingest subproject's command line arguments and wires said flag into the ingest process so that layer deletion is carried out when it is provided.
See the `docs` directory for instructions on trying out an ingest. Simply add the `--overwrite` flag to exhibit layer deletion behavior.
Connects #1036
> Allow layers to be overwritten on ingest

- app-backend/build.sbt
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/ScenesToProjects.scala
- app-backend/project/Dependencies.scala
- app-backend/tile/src/main/resources/application.conf
- app-backend/tile/src/main/scala/LayerCache.scala
- app-backend/tile/src/main/scala/image/Mosaic.scala
- app-backend/tile/src/main/scala/package.scala
- app-backend/tile/src/main/scala/routes/ToolRoutes.scala
At the moment, n-simultaneous requests to memcached which miss will kick off the expensive fallback logic n-times. Instead, we should keep a weak reference to the futures produced in such requests and check that prior to querying memcached. This PR makes single-machine memcached requests atomic for `MosaicDefinition`s, `MultibandTile`s, and `Histogram`s.
A more permanent solution is in the pipeline, but this PR should improve performance on some of the most sluggish parts of the application while we solve this problem in a DRYer way.
Connects #961
> Prevent duplication of effort on expensive cache misses

- app-backend/app/src/test/scala/auth/AuthSpec.scala
- app-backend/app/src/test/scala/datasource/DatasourceSpec.scala
- app-backend/app/src/test/scala/healthcheck/HealthCheckSpec.scala
- app-backend/app/src/test/scala/image/ImageSpec.scala
- app-backend/app/src/test/scala/organization/OrganizationSpec.scala
- app-backend/app/src/test/scala/project/ProjectSceneSpec.scala
- app-backend/app/src/test/scala/project/ProjectSpec.scala
- app-backend/app/src/test/scala/scene/SceneSpec.scala
- app-backend/app/src/test/scala/tags/ToolTagSpec.scala
- app-backend/app/src/test/scala/thumbnail/ThumbnailSpec.scala
- app-backend/app/src/test/scala/tools/ToolSpec.scala
- app-backend/app/src/test/scala/user/UserSpec.scala
Taking the timeouts from 3s to 5s.
Watch the build output for this pull request. Ensure that none of the tests fail with:
> Request was neither completed nor rejected within N seconds
See: http://jenkins.staging.rasterfoundry.com/blue/organizations/jenkins/raster-foundry%2Fraster-foundry/detail/PR-1056/1/pipeline
> Increase RouteTestTimeout to 5s for all specs

- app-tasks/rf/src/rf/uploads/geotiff/__init__.py
- app-tasks/rf/src/rf/uploads/geotiff/create_scenes.py
- app-tasks/rf/src/rf/uploads/geotiff/create_thumbnail.py
- app-tasks/rf/src/rf/uploads/geotiff/create_thumbnails.py
- app-tasks/rf/src/rf/uploads/geotiff/io.py
Adds thumbnail creation and upload to S3 when creating scene objects from geotiffs.
* Ensure that your `.env` has a `THUMBNAIL_BUCKET` defined. You can set it to a test bucket if it is not defined
* Download a kayak geotiff and move it into a mounted or copied directory of the `airflow-worker` (`app-tasks/rf` worked well for me)
* Inside the vagrant machine open bash `./scripts/console airflow-worker bash`
* CD to wherever you put the test geotiff
* Open ipython
* `from rf.uploads.geotiff.create_thumbnails import create_thumbnails`
* `create_thumbnails(<path_to_geotiff>, '1234', 'abcd')`
* Check that thumbnails are uploaded to the S3 bucket
Connects #944
> Add thumbnail creation to geotiff processing

- app-tasks/rf/src/rf/models/scene.py
- app-tasks/rf/src/rf/uploads/geotiff/__init__.py
- app-tasks/rf/src/rf/uploads/geotiff/create_footprints.py
- app-tasks/rf/src/rf/uploads/geotiff/create_scenes.py
- app-tasks/rf/src/rf/uploads/geotiff/extract_footprint.py
- app-tasks/rf/src/rf/uploads/landsat8/create_scenes.py
- app-tasks/rf/src/rf/uploads/sentinel2/create_scenes.py
- app-tasks/rf/src/rf/utils/io.py
This commit adds support for extracting footprints for both the data and tile of a geotiff.
With this particular initial dataset it is assumed that `nodata` is represented by values of `255` in the near-infrared band. This will likely not hold for future geotiffs, but seems like the best option for this initial set of data received.
* Download a kayak geotiff and move it into a mounted or copied directory of the `airflow-worker` (e.g. `app-tasks/rf`)
* Inside the vagrant machine open bash `./scripts/console airflow-worker bash`
* CD to wherever you put the test geotiff
* Open ipython and run the following code (you must set path):
```python
from rf.uploads.geotiff.create_scenes import load_example …
```
> Add footprint generation from geotiffs

- app-tasks/Dockerfile
- docker-compose.airflow.yml
In order to prevent various home directory files from leaking into the local file system, move the `airflow` user's home directory to `/var/lib/airflow`, but keep Airflow's location of `AIRFLOW_HOME` the way it was.
Fixes https://github.com/azavea/raster-foundry/issues/1021
Use the `server` script to launch the default set services, along with the Airflow services, and ensure that none of them blow up with errors indicating that they cannot locate an AWS profile:
```bash
vagrant@vagrant-ubuntu-trusty-64:/opt/raster-foundry$ ./scripts/server --with-airflow
```
Next, use `console` to get into an Airflow worker, launch `ipython`, and ensure that the associated dotfiles are not on the local file system:
```bash
vagrant@vagrant-ubuntu-trusty-64:/opt/raster-foundry$ ./scripts/console …
```
> Move home directory of Airflow user

- app-frontend/src/app/components/filterPane/filterPane.controller.js
- app-frontend/src/app/components/filterPane/filterPane.html
- app-frontend/src/app/components/sceneDetail/sceneDetail.component.js
- app-frontend/src/app/components/sceneDetail/sceneDetail.controller.js
- app-frontend/src/app/components/sceneDetail/sceneDetail.html
- app-frontend/src/app/components/sceneItem/sceneItem.controller.js
- app-frontend/src/app/components/sceneItem/sceneItem.html
- app-frontend/src/app/core/core.module.js
- app-frontend/src/app/core/services/datasource.service.js
- app-frontend/src/app/core/services/map.service.js
- app-frontend/src/app/pages/browse/browse.html
This PR adjusts the front-end to better match the addition of a separate datasource model.
More specifically, this PR:
- adds a datasource service
- changes the datasource filter on the browse page to be dynamically built from existing datasource models
- queries for the relevant datasource when necessary in various areas (attributions, detail pages, etc)
The datasource filter currently is composed of two sets of filters: static and dynamic.
The static filters are intended to allow the users to filter down to datasources that match a set of criteria (i.e. owned by the user & private).
The dynamic filters are populated straight from the database.
The datasource endpoint does not currently filter on attributes such as visibility or ownership. As a result, the static filters do not work yet. …
> Update datasource filter and references

- app-frontend/src/app/components/sceneDetail/sceneDetail.html
Fix missing fields in Scene Detail views
* Go to a scene detail view and verify that filter and status fields show up
Fixes #1058
> Fix missing fields in Scene Detail views

- README.md
- docker-compose.airflow.yml
- docker-compose.spark.yml
- docker-compose.swagger.yml
- docker-compose.test.yml
- docker-compose.yml
- scripts/cibuild
- scripts/console
- scripts/setup
- scripts/test
*This change makes it so that frontend development can only happen from outside of the virtual machine, via the instructions outlined in the `README`.*
In order to continue supporting static bundle creation, move the `app-frontend` service configuration to `docker-compose.test.yml` and change its default command to `yarn run build`.
In addition, upgrade the Docker Compose configuration file format so that we can take advantage of default environment variables, which help suppress warning messages when using `console` with `app-frontend`.
Fixes https://github.com/azavea/raster-foundry/issues/882
Execute the following scripts within the virtual machine and ensure that they complete successfully:
- `setup`
- `cibuild` (this exercises `test`)
For `console`, use the following command to get a …
> Move app-frontend service to test Docker Compose config

- app-frontend/src/app/components/sceneDetail/sceneDetail.html
- app-frontend/src/app/components/sceneItem/sceneItem.html
- app-frontend/src/app/core/services/imageOverlay.service.js
- app-frontend/src/app/core/services/map.service.js
- app-frontend/src/app/core/services/thumbnail.service.js
Add token parameter to thumbnail urls that start with '/'
* Load a view that displays a scene thumbnail
* Verify that for urls that start with '/', a token gets added to the request
* If you don't have any scenes with thumnails that start with '/', set a breakpoint in thumnail.service on the if statement, and set the url to something like '/thumnail/url/123' and resume. You can check the network tab in chrome to verify that the parameter is set correctly.
Closes #1059
> Add token parameter to thumbnail urls that start with '/'

- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Scenes.scala
- app-frontend/src/app/components/filterPane/filterPane.controller.js
Make scene filters inclusive
Filtered to scenes with exactly 0 cloud coverage:
This allows sitting min / max to the same value to achieve an exact match filter, so I've enabled the same on the frontend. It's a little harder to test stuff like sun elevation/azimuth using the frontend, so use a curl or ARC request to filter down to a scene you know exists
* Verify that when filtering by cloudCover, the filter is inclusive (shows scenes with 0 cloud cover)
*  Verify that the aquisitionDate filter is inclusive
* Verify that the sunAzimuth filter is inclusive
* Verify that the sunElevation filter is inclusive
Fixes #1069
> Make Scene filters inclusive

- .github/PULL_REQUEST_TEMPLATE.md
- app-backend/migrations/src/main/scala/migrations/41.scala
The symlink for the 41st migration was no good. This fixes it.
> Create symlink for migration 41

- app-frontend/src/app/pages/library/scenes/list/list.controller.js
Filter library scenes to scenes which are created by user
This will break once we switch users from auth0 id to uuid in requests. It will be a simple fix once that gets done though: either way, the logged in user profile should be accessed through the authService.
* Set the created_by field on a couple scenes to your user
* Go to the library scene list view and verify that the only scenes which show up are the ones created by your user
Closes #1078
> Filter library scenes to scenes which are created by user

- app-tasks/Dockerfile
Previously, the `AIRFLOW_HOME` directory was being created by the `adduser` command, which created it and ensured that the `airflow` user was given correct permissions.
Because of the new disconnect between `airflow` user `HOME` and `AIRFLOW_HOME`, the `AIRFLOW_HOME` directory needs to be created (before `COPY`) and the `airflow` user granted proper permissions.
First, execute the `bootstrap` script to ensure that your local container image for Airflow is built using the changes in this branch. From there, apply the following diff to `docker-compose.airflow.yml`:
```diff
diff --git a/docker-compose.airflow.yml b/docker-compose.airflow.yml
index 29fec0f4..2fc0f44e 100644
--- a/docker-compose.airflow.yml
+++ b/docker-compose.airflow.yml
@@ -6,10 +6,10 @@ services:
airflow-webserver:
image: …
```
> Create and alter permissions on AIRFLOW_HOME

- app-frontend/src/app/core/services/gridLayer.service.js
This PR adjusts the scene grid service to ensure that bad Landsat8 imports (cloudcover < 0) are not counted in the scene grid, just as they are not counted in the scene list.
* On the browse page, use the scene-grid to filter to a single grid-cell (this is the only time the list is guaranteed to match the numbers on the grid)
* Check that for any single grid-cell, the number displayed in the cell matches the result total shown in the scene list
Connects #1055
> Fix scene grid param mismatch

- app-frontend/src/app/components/filterPane/filterPane.component.js
- app-frontend/src/app/components/filterPane/filterPane.controller.js
- app-frontend/src/app/pages/browse/browse.controller.js
- app-frontend/src/app/pages/browse/browse.html
Prevent filters and grid layer from initializing when not logged in
Re-initialize filters/grid layer after every login event (IE when changing users
without reloading)
Re-render filter sliders when opening to prevent weird initializations
* Verify that when opening the filter bar, the sliders initialize correctly
The first time you open it, the sliders may adjust themselves slightly - this means the fix is working.
* Load the page while not logged in. Verify that no unauthorized requests are made for the grid-layer or filter pane
Fixes #909
Fixes #755
> Prevent filters and grid layer from initializing before login

- app-frontend/package.json
- app-frontend/src/app/components/publishModal/publishModal.component.js
- app-frontend/src/app/components/publishModal/publishModal.controller.js
- app-frontend/src/app/components/publishModal/publishModal.html
- app-frontend/src/app/components/publishModal/publishModal.module.js
- app-frontend/src/app/components/publishModal/publishModal.scss
- app-frontend/src/app/index.module.js
- app-frontend/src/app/index.vendor.js
- app-frontend/yarn.lock
This PR adds some structure to enable adding multiple tile URL formats to the publish modal.
Currently there are two formats:
- Standard
- ArcGIS
This PR also includes some other improvements:
- The share preview page now opens in a new tab
- The tileUrl copy button now actually copies the url to the clipboard
* Open an ingested project in the library or editor, click the publish button
* Check that the 'Standard' URL is default
* Check that switching URL formats actually changes the URL
* Check that the copy works for each URL
* Click the 'Preview Your Published Project' button and see that the page opens in a new …
> Add custom tile URL format to publish modal

- app-frontend/src/app/components/projectAddModal/projectAddModal.controller.js
- app-frontend/src/app/components/projectAddModal/projectAddModal.html
- app-frontend/src/app/pages/library/projects/list/list.controller.js
- app-frontend/src/app/pages/library/projects/list/list.html
- app-frontend/src/app/pages/settings/settings.html
This PR adds client-side validation to the project create forms found within modals and on the library project list.
I've also tacked on the removal of the 'notifications' and 'billing' links within the user settings.
* From the browse page, select a scene and click the 'x scenes selected button'
* Click the 'Add to project' button
* Try to create a project without entering a name (it shouldn't work, and there should be an error message)
* Check that no request was sent
* Go to the library project list page and do the same test
* Go to your user settings and check that the 'notifications' and 'billing' links are not …
> Add validation to project create forms

- app-tasks/rf/src/rf/uploads/landsat8/create_footprint.py
This PR ensures that footprints are properly imported by explicitly casting all coordinates to floats (rather than allowing them to be strings) before they are compared to determine min and max coordinates.
~This PR also ensures that min and max coordinates will be properly selected even if they cross the anti-meridian.~
* Inside the VM, open bash within an airflow container `./scripts/console airflow-worker bash`
* CD to `app-tasks/rf/src/rf/uploads`
* Open an ipython session
* `from landsat8.create_footprint import create_footprints`
* Set separate vars to the dicts shown below
* pass each var into …
> Fix landsat8 tile footprint computation

- app-frontend/src/app/components/diagramContainer/diagramContainer.component.js
- app-frontend/src/app/components/diagramContainer/diagramContainer.controller.js
- app-frontend/src/app/components/publishModal/publishModal.html
- app-frontend/src/app/pages/lab/run/run.controller.js
- app-frontend/src/app/pages/lab/run/run.html
This PR adds a 'Share' option to the context menu for nodes within the lab diagram.
This PR also modifies the `publishModal` to handle cases where a `shareUrl` has not be passed into it and in this case it does not display the publishing options. This is useful since for node previews we are not yet allowing users to create a shareable page (once `tools` and `toolRuns` are more substantially implemented this will change).
- Should the wording of the option be 'Publish' or 'Share'?
- Proper disabling of options will be something we can better accomplish when the tool running backend is implemented since we need to be …
> Add share option to diagram context menu

- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Projects.scala
- app-tasks/dags/ingest/find_scenes_to_ingest.py
- app-tasks/rf/src/rf/models/base.py
- app-tasks/rf/src/rf/utils/io.py
This commit adds a DAG to check if scenes need to be ingested and kicks
off an ingest _per_ scene to be ingested.
A few notes:
- Decided against using a sensor here because of issues with the
semantics for a sensor. A sensor can run on a schedule and continues
poking until it reaches a true status. Which in our case is not quite
what we want -- instead we want this to run at a regular interval and
at most 1 running per time.
- Subsequent PRs will address kicking off ingests actually, for now
this kicks off the dummy DAG for ingests
- `max_active_runs` is set to 1 to prevent us from DDOSing ourselves
- DAG is set to run every two minutes, this might need to be adjusted
down later
~- [ ] Symlinks …
> Add Scene Ingest Trigger

- app-backend/app/src/main/scala/project/Routes.scala
- app-backend/app/src/test/scala/project/ProjectHelpers.scala
- app-backend/app/src/test/scala/project/ProjectSceneSpec.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/QueryParameterJsonFormat.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/QueryParameters.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Projects.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Scenes.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/SceneSerialization.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/SerializationUtils.scala
- docs/swagger/spec.yml
This PR enables adding scenes to a project based on a query for scenes. We need to do this because even scrolling through the list of scenes and clicking select all over and over again isn't convenient for adding large numbers of scenes, and users who know what they want should be able to add those scenes to a project.
This could maybe use more thorough testing, but there are about 25 total fields to check "should filter by x correctly" for, and scene filtering is well tested in a number of other places, so I thought probably it's fine.
We should abandon `spray` for [`circe`](https://circe.github.io/circe/), or at least I believe this because I am easily marketable to …
> Bulk add scenes to a project based on a query

- app-tasks/rf/src/rf/uploads/sentinel2/create_scenes.py
This ensures the metadataFile urls generated by the importer are fully qualified and will not result in relative linking client-side.
* Inside the VM, open bash within an airflow container `./scripts/console airflow-worker bash`
* CD to `/opt/raster-foundry/app-tasks/rf/src/rf/uploads`
* Open an ipython session
* `from sentinel2.create_scenes import create_scenes`
* `scene = create_sentinel2_scene('tiles/10/U/DC/2017/2/8/0')[0]`
* Check that the output of `scene.metadatFiles` is a list of fully defined urls (with the https)
Connects #740
> Fix metadata urls in sentinel2 import

- app-backend/app/src/main/scala/Router.scala
- app-backend/app/src/main/scala/toolrun/Routes.scala
- app-backend/app/src/main/scala/toolrun/package.scala
- app-backend/app/src/test/scala/toolruns/ToolRunSpec.scala
- docs/swagger/spec.yml
Adds a CRUD API for interacting with ToolRun objects
I _think_ the new swagger documentation is correct but it is raising errors on one set of lines that I added. However, all the other errors in the file are making it hard to tell if that is a real error or fallout from something else. I've added a comment on those lines; perhaps a second set of eyes can catch a typo I've missed.
Also, the structure of the `Routes.scala` is a bit different than our usual pattern. This is because the existing `ToolRuns` `TableQuery` returns `DBIO` objects rather than `Future`s. I assumed this was done as an improvement over previous iterations in that it decouples the API by pushing what is essentially API presentation logic up into the Routing level. If that wasn't the intent then it's easy enough to …
> ToolRun API

- app-tasks/dags/geotiff/find_geotiff_scenes.py
- app-tasks/dags/geotiff/import_geotiff_scenes.py
- app-tasks/rf/src/rf/models/base.py
- app-tasks/rf/src/rf/models/scene.py
- app-tasks/rf/src/rf/uploads/geotiff/create_images.py
- app-tasks/rf/src/rf/uploads/geotiff/create_scenes.py
* Create DAGS: find_geotiff_scenes and import_geotiff_scenes
* Modify base model so that calling create() checks for a response code of 409 before throwing an error. This will cause the DAGs to skip any scenes that already exist
Currently, the geotiff import requires a massive amount of memory to expand the geotiff. 
I've only been able to get a single scene to index at a time before it runs out of memory, but you might not be able to even get that far.
* Start the server with airflow: `./scripts/server --with-airflow`
* start PSQL: `./scripts/psql`
* create a datasource (make sure to insert a user id): `insert into …
> Kayak Geotiff import DAG

- app-frontend/src/app/core/services/auth.service.js
- app-frontend/src/app/index.module.js
- app-frontend/src/app/index.routes.js
- app-frontend/src/app/index.run.js
- app-frontend/src/app/pages/login/login.controller.js
- app-frontend/src/app/pages/login/login.html
- app-frontend/src/app/pages/login/login.module.js
- app-frontend/src/app/pages/login/login.scss
- app-frontend/src/app/pages/root/root.html
- app-frontend/src/tpl-index.html
Add login page and route
Add redirects when not logged in
* Verify that:
* loading raster foundry while not logged in redirects to the login view
* you cannot change to another view from the login view
* logging in goes to the browse view
* Logging out goes to the login page
* every view still functions normally (no style issues, etc)
* the login view redirects to the browse view if you are logged in
Closes #995
> Add login page

- app-backend/app/src/main/resources/application.conf
- app-backend/app/src/main/scala/token/Token.scala
- app-backend/app/src/main/scala/token/package.scala
- app-backend/app/src/main/scala/utils/Config.scala
- app-backend/build.sbt
This commit alters the approach to obtaining a bearer token that granted access to the auth0 management api. We utilize the management api to create device_tokens which we leveraged when created user's api tokens.
Auth0 moved to a more secure token implementation which adopts a 24-hour lifetime token rather than the long-lived token used previously. As a result, we can no longer set an environment variable with the token and use that when doing device_token CRUD operations.
See the following links for more details:
- [https://auth0.com/docs/api/management/v2/tokens-flows]
- [https://auth0.com/docs/api/management/v2/tokens]
This commit uses an async-cache with a 12-hour expiration time (adjustable) to handle getting and storing the current management bearer token.
~- [ ] Styleguide …
> Fix auth0 management tokens

- app-frontend/package.json
- app-frontend/src/app/components/navBar/navBar.controller.js
- app-frontend/src/app/core/core.module.js
- app-frontend/src/app/core/services/auth.service.js
- app-frontend/src/app/core/services/featureFlagOverrides.service.js
- app-frontend/src/app/core/services/storage.service.js
- app-frontend/src/app/index.module.js
- app-frontend/src/app/index.run.js
- app-frontend/src/app/index.vendor.js
- app-frontend/src/app/pages/browse/browse.controller.js
Add localStorage and sessionStorage services
Remove angular-storage library (doesn't support multiple storage sources)
I removed angular-storage because it doesn't support multiple storage sources.
After evaluating other libraries, I just wrote simple wrapper services since it's simple and doesn't run into issues w/ regard to caching / flexibility that I observed in the available libraries.
* Change a filter on the browse view
* Go to a different view
* Go back to the browse view by clicking the browse scenes link at the top of the page
* Verify that the filters are persisted
* Verify that reloading the page doesn't …
> Add Session storage of map filters

- app-frontend/src/app/core/core.module.js
- app-frontend/src/app/core/services/map.service.js
- app-frontend/src/app/core/services/mapUtils.service.js
- app-frontend/src/app/pages/editor/project/projectEdit.controller.js
- app-frontend/src/app/pages/lab/edit/edit.controller.js
- app-frontend/src/app/pages/lab/run/run.controller.js
- app-frontend/src/app/pages/share/share.controller.js
- app-frontend/src/app/pages/share/share.html
This PR leverages the server-side computed project extent to remove async project extent calculations on the front-end.
These calculations were previously being done for the editor, the share page, and any tool output visualizations.
* Run the server
* On any page that utilizes the tile-server, check that the map is fit to the project bounds (share page, editor, lab)
Connects #1141
> Utilize server computed project extent

- deployment/ansible/group_vars/jenkins
Terraform state is current at 0.8.5 and we have 0.8.2 defined in Ansible. This updates us to the most recent patch release, 0.8.7.
See:
https://github.com/hashicorp/terraform/blob/master/CHANGELOG.md#087-february-15-2017
These changes are currently running on staging:
```bash
athena Projects/raster-foundry ‹feature/hmc/terraform-0.8.7› » ssh -l ubuntu -i ~/.ssh/raster-foundry-stg.pem jenkins.staging.rasterfoundry.com
Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-110-generic x86_64)
* Documentation:  https://help.ubuntu.com/
System information as of Fri Feb 24 18:22:38 EST 2017
System load:                    0.05
Usage of /:                     70.3% of 251.84GB
Memory usage:                   22%
Swap usage:                     0%
Processes:                      131
Users logged in: …
```
> Bump Terraform version to 0.8.7

- app-frontend/src/app/components/colorCorrectScenes/colorCorrectScenes.controller.js
- app-frontend/src/app/components/colorCorrectScenes/colorCorrectScenes.html
- app-frontend/src/app/pages/editor/project/projectEdit.controller.js
This PR uses the composites fields defined on a datasource to populate the color mode dropdown.
In order to handle multiple datasources, the dropdown is populated only by the color composites that are common to all datasources. This does not handle the actual correction of scenes from different datasources.
We may want to consider how we will handle the case of scenes from multiple datasources in a single project and how, in these cases, we would handle composite matching since our composites are loosely defined as JSON.
* View an ingested scene in the editor
* Verify that the color mode dropdown is populated
* …
> Populate color mode dropdown from API

- app-frontend/src/app/components/colorCorrectPane/colorCorrectPane.controller.js
- app-frontend/src/app/core/services/layer.service.js
- app-frontend/src/app/core/services/project.service.js
- app-frontend/src/app/index.run.js
- app-frontend/src/app/pages/editor/project/projectEdit.controller.js
- app-frontend/src/app/pages/lab/edit/edit.controller.js
This PR reduces the minimum number of requests for scenes on color correction from 4 to 1. To do this, we eliminate extraneous requests to determine bounds and alter the page parsing strategy to use the `count` property of the first page, rather than sending a separate request to get the record count.
This also fixes a color correction bug (fitting selected scenes when color correcting now works again) and cleans some lint.
* Go to color correct for a project with less than 30 scenes
* Monitor requests and check that only a single request was made for a scenes page
* Go to color correct for a project with greater than …
> Streamline requests for color-correction

- scripts/console
Currently, the `app-frontend` service is defined in docker-compose.test.yml. This configuration requires `scripts/server` and `scripts/console` to include docker-compose.test.yml in commands, which in turn builds/runs production-ready containers instead of the versions we use in development. This PR moves `app-frontend` to docker-compose.yml, allowing `scripts/console` and `scripts/server` to build the development versions of each service container.
* Ensure …
> Move app-frontend to docker-compose.yml

- nginx/etc/nginx/nginx.conf
The CIDR ranges listed in this change are used for our public subnets across VPCs. Updating them allows Nginx to properly log the client IP address that initialed the request.
Fixes https://github.com/azavea/raster-foundry/issues/1041
I packaged these changes into a set of container images and pushed them into the staging environment. See the Papertrail logs here that have the correct remote client IP address:
- https://papertrailapp.com/groups/4082193/events?focus=773379959438848017&selected=773379959438848017
> Update Nginx set_real_ip_from for public subnets

- app-backend/app/src/main/scala/project/Routes.scala
- app-backend/app/src/test/scala/project/ProjectHelpers.scala
- app-backend/app/src/test/scala/project/ProjectSceneSpec.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Projects.scala
This PR ensures the API consumer is not performing unauthorized actions when adding scenes to a project. This really boils down to two checks:
1) Is the user the owner of the project in question?
2) Are all of the scenes in question public?
When either of these conditions is false, we stop processing the request and throw an exception with a relevant message.
We could possibly handle point 2 differently, and allow the request to proceed if at least one scene is public and filter the unauthorized scenes out before adding them rather than a wholesale failure. That being said, it is unlikely that such an action would be unintentional.
~- [ ] Symlinks from new migrations present or corrected for any …
> Authorization logic for adding scenes to a project

- app-frontend/config/webpack/environments/production.js
- app-frontend/package.json
- app-frontend/yarn.lock
Webpack returns 0 after every run, even if the static asset bundle build fails. As a result, Jenkins jobs will pass and deploy broken javascript to staging. This PR forces Webpack to return 1 when building static files fails.
This is a bug in webpack 1.x, documented in webpack/webpack#708. They have no intention on fixing it in this major version, but it's been fixed in webpack 2.x. Upgrading webpack may be a cleaner solution in the long run.
* Add an error to a javascript file:
```diff
diff --git a/app-frontend/src/app/pages/editor/editor.controller.js b/app-frontend/src/app/pages/editor/editor.controller.js …
```
> Return error code when webpack build fails

- app-tasks/dags/ingest/ingest_project_scenes.py
This PR ensures airflow has sufficient knowledge of scenes when exceptions are hit. Allows airflow to properly handle failure.
* Run server with airflow
* Add a sentinel scene to a project
* After a little bit, check ingest status and see that it is 'FAILED'
> Improve failed ingest handling

- app-tasks/dags/landsat8/import_landsat8_scenes.py
- app-tasks/dags/sentinel2/find_sentinel2_scenes.py
- app-tasks/rf/src/rf/models/base.py
- app-tasks/rf/src/rf/uploads/landsat8/create_footprint.py
- app-tasks/rf/src/rf/uploads/sentinel2/create_footprint.py
- scripts/cipublish
This PR fixes a bug that prevented successfully importing metadata for sentinel and landsat imagery.
Also makes development of airflow tasks easier by setting the schedule interval to `None` when in development. 
* Go to the airflow UI at `localhost:8080`, go to Dag Runs, and click create
* Kick off a Landsat 8 metadata import
* Kick off a Sentinel 2 metadata import
* Go back to main page and observe that imports are proceeding without errors
Closes #1174
> Update Metadata Imports

- app-backend/ingest/src/main/scala/com/azavea/rf/ingest/model/SourceDefinition.scala
- app-backend/ingest/src/test/scala/com/azavea/rf/ingest/model/IngestDefinitionSpec.scala
This PR fixes the construction of sources in an ingest definition. Previously, each source's `extentCrs` was being passed as the `crs` and vice versa. There have been some explicit tests added as well.
* Console into the ingest project (`./scripts/console app-server ./sbt` and `project ingest`)
* Run tests (`test`)
* You could flip the lines changed in `SourceDefinition.scala` back to the way they were and see that the tests fails
Connects #1167
> Fix ingest definition parsing and add tests

- app-backend/api/src/main/scala/RfJsonProtocols.scala
- app-backend/api/src/main/scala/token/Routes.scala
- app-backend/api/src/main/scala/token/Token.scala
- app-backend/api/src/main/scala/token/package.scala
- app-backend/api/src/main/scala/user/Auth0User.scala
- app-backend/api/src/main/scala/user/Routes.scala
- app-backend/api/src/main/scala/user/package.scala
- app-backend/api/src/main/scala/utils/Auth0ErrorHandler.scala
- app-backend/api/src/main/scala/utils/Auth0Exception.scala
- app-backend/api/src/main/scala/utils/Auth0Util.scala
- app-frontend/src/app/components/navBar/navBar.html
- app-frontend/src/app/core/services/auth.service.js
- app-frontend/src/app/core/services/user.service.js
- app-frontend/src/app/pages/settings/account/account.controller.js
- app-frontend/src/app/pages/settings/account/account.html
- app-frontend/src/app/pages/settings/profile/profile.controller.js
- app-frontend/src/app/pages/settings/profile/profile.html
- app-frontend/src/app/pages/settings/profile/profile.module.js
- app-frontend/src/app/pages/settings/profile/profile.scss
- app-frontend/src/assets/styles/sass/components/_login.scss
- docs/swagger/spec.yml
Allow updating user profile and password from frontend and api
* Add password change button to profile
* Add users/me endpoint to get auth0 user from api
* Add user/me patch endpoint to update user data
* Allow updating user_metadata from profile page
* Misc other profile related updates
Not all user fields on users/me are helpful to the user. Keeping them commented as documentation of their existence
TODO: Embed the user info inside a rasterfoundry user object
* On a non-oauth account, change your password from the profile/account view
* Verify that the change password button doesn't show for oauth accounts
* Add a user_metadata field to your user by making a patch …
> Allow updating user profile and password from frontend

- app-frontend/src/app/components/mapContainer/mapContainer.component.js
- app-frontend/src/app/components/mapContainer/mapContainer.controller.js
- app-frontend/src/app/components/mapContainer/mapContainer.html
- app-frontend/src/app/components/mapContainer/mapContainer.scss
- app-frontend/src/app/core/services/map.service.js
This PR adds a tile loading and loading error indicator to the map component. We want to be able to provide feedback to the user while tiles are loading rather than presenting them with an empty map. In addition, we'd like to provide error feedback when some tiles cannot be loaded.
This indicator is automatically wired up to any tile layers that are added via the map service's `addLayer` method. Layers added directly via Leaflet will not send events to the indicator.
Indicating loading errors is currently disabled (via a comment). See notes for more info on this.
@designmatty We'll definitely need some styling here. …
> Add loading indicator to map component

- app-backend/ingest/src/main/scala/com/azavea/rf/ingest/Ingest.scala
- app-backend/ingest/src/main/scala/com/azavea/rf/ingest/util/Validation.scala
- app-backend/ingest/src/test/resources/awsJob.json
This PR works around a couple of issues encountered when attempting to use the `S3LayerDeleter`. 
1. A failed ingest will have metadata with no related tile information - this causes malformed XML to be sent to AWS and prevents successful clobbering of failed ingest directories.
2. If metadata cannot be located for a given layer, no further deletion logic is attempted despite the fact that we should be able to delete `_attributes` data even if we can't magically remove a layer's associated tiles (which it won't have anyway if the ingest fails).
A PR is being crafted for GT's 1.0.1 release which will resolve this in a cleaner way. The solution implemented in the meantime is just to catch exceptions on attempted deletion and manually fall back on deleting `_attributes` data we can find. …
> Work around layer deletion bug in GT

- app-backend/tile/src/main/scala/image/Mosaic.scala
- app-backend/tile/src/main/scala/routes/MosaicRoutes.scala
- app-frontend/src/app/components/mapContainer/mapContainer.controller.js
This PR alters the way in which the tile server handles returning tiles for areas outside of the extent of the scenes tiles are being generated for. Previously, the tiler returned empty responses of type `text/plain` for these areas. It now returns an empty png of the proper size.
The motivations for this center around how tile loading errors are detected with Leaflet. Empty responses are treated as errors. We can expect some consumers of the api would be using Leaflet or services built on top of Leaflet, so we should handle this accordingly.
* With a project consisting only of ingested scenes, go to a mosiaced page …
> Return empty png rather than empty response

- docker-compose.yml
Increase memcached max object size to match production and staging.
Start `memcached` (detached), then login to a shell
* `docker-compose up -d memcached`
* `docker-compose exec memcached /bin/sh`
Create a file ~100B smaller than the max file size, and try to insert it into memcache.
```bash
/ $ cd ~
~ $ for i in $(seq 1 5242700); do printf "1"  >> out.txt; done
~ $ ls -l
total 5120
-rw-r--r--    1 memcache memcache   5242700 Mar  6 20:13 out.txt
~ $ printf "set test_key 0 120 5242700 \r\n$(cat out.txt)\r\n" | nc localhost 11211
STORED
```
This same option should fail on a bigger file.
```bash
~ rm out.txt
~ $ for i in $(seq 1 5242881); do printf …
```
> Increase memcached max object size in development

- docs/swagger/spec.yml
This PR clean up the swagger spec to reduce errors and warnings that show in the Swagger editor but do not cause the spec to fail validation.
* Make sure swagger validation still passes (`./scripts/test`)
* Open the spec in the swagger editor, check that only warnings refer to the unused `Polygon` definition -- we will be using this in the future
> Fixup swagger spec

- app-backend/api/src/main/scala/project/Routes.scala
- app-backend/api/src/test/scala/project/ProjectSceneSpec.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/ScenesToProjects.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/MosaicDefinition.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/PaginatedResponse.scala
- app-backend/tile/src/main/scala/image/Mosaic.scala
- app-frontend/src/app/core/services/colorCorrect.service.js
- app-frontend/src/app/core/services/layer.service.js
- app-frontend/src/app/pages/editor/project/projectEdit.controller.js
- docs/swagger/spec.yml
This updates the color correction/mosaic API to be slightly more user friendly.
A few changes were made:
- updates the JSON format for mosaic definition (this required updating the case class/etc) so we probably need to scratch the cache after this is deployed
- removes POST options for order/color correction -- both are defined already when a scene is added to a project, so additional updates are PUT requests now that return the normal response of empty content/204
- removes additional requests/promises from front-end code to get updated color corrections
Note two requests on staging when color correcting a single scene:
After this PR only one request:
* Go to color …
> Update Color Correct API

- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Tools.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/Tool.scala
- docs/swagger/spec.yml
This PR seeks to minimize the number of requests needed to get a full representation of a tool.
When we display a list of tools we would like to be able to show the tool's tags, categories, owning organization, and possibly event the name of the user that created the tool (see note). Previously, our strategy to handle related items was to return the ids of these items. This would require many subsequent requests to get the data needed for display.
Rather than return ids, this PR adds fully embedded records of those related items (sans user) into the representation of a tool returned by the API.
Trimmed response:
```
{
"count": 4,
"pageSize": 30,
"hasPrevious": false, …
```
> Include related items in tool response

- app-tasks/dags/ingest/find_scenes_to_ingest.py
This commit removes the call to get a JWT from the "find scenes to
ingest" DAG. This caused an error in the airflow scheduler because the
airflow scheduler does not have the Auth0 client token injected into its
environment. Instead, this commit moves the creation of a session inside
a function to ensure it only gets called when run inside an Airflow worker.
There isn't a great way to test this that I could come up with. It might be easier to deploy, I think the logic is pretty straightforward though. The main problem was that the scheduler was running code, which we should try to minimize in the future.
Closes #1221
> Remove call to get JWT in airflow scheduler

- docs/swagger/spec.yml
Adds an endpoint definition, resources, and parameters to support adding map tokens. This is to support more fully sharing of maps with external users that may not have accounts in Raster Foundry.
Closes #1202
* Verify that required functionality is added by inspecting swagger spec
> Add spec for map token to swagger

- app-frontend/src/app/components/callToActionItem/callToAction.scss
- app-frontend/src/app/components/callToActionItem/callToActionItem.component.js
- app-frontend/src/app/components/callToActionItem/callToActionItem.controller.js
- app-frontend/src/app/components/callToActionItem/callToActionItem.html
- app-frontend/src/app/components/callToActionItem/callToActionItem.module.js
- app-frontend/src/app/index.components.js
- app-frontend/src/app/index.module.js
- app-frontend/src/app/index.routes.js
- app-frontend/src/app/pages/home/home.controller.js
- app-frontend/src/app/pages/home/home.html
- app-frontend/src/app/pages/home/home.module.js
- app-frontend/src/app/pages/home/home.scss
This PR adds a home page and an `rf-call-to-action-item` component.
The page can be found at `/home` and needs to be manually routed to.
The secondary buttons refer to actions we don't do yet directly (such as creating a tool or project). They are not currently functional.
* Manually go to the `/home` route.
* See that the layout matches the mockups
* Test primary buttons to ensure they navigate to the right place.
* Test resizing the window to ensure that the call-to-actions stack on narrow viewports
Connects #1213 
Connects #1215
> Create home page for updated UI

- app-frontend/src/app/core/services/auth.service.js
- app-frontend/src/app/index.config.js
- app-frontend/src/app/pages/login/login.controller.js
Redirect to login page on a 401 response
This only redirects for requests to urls that start with '/api' so that if for example, the user makes a request
to an S3 URL using an expired token, it shouldn't log them out.
* Log into the frontend
* In chrome dev tools, change your auth token to an invalid one / delete it
* Make a request by fetching more scenes / anything else really
* Verify that you get redirected to the login view, and tokens/profile are deleted
* Verify that 404's and other errors do not cause the same redirect
Closes #1212
> Redirect to login page on 401

- .mention-bot
An instance of mention-bot was setup for Azavea usage. This configuration file provides project specific settings for mention-bot's behavior.
See: https://github.com/facebook/mention-bot#configuration
Open a pull request with changes, and determine if @azaveaci comments on it with recommended reviewers.
> Add Facebook mention-bot configuration

- app-frontend/src/app/components/publishModal/publishModal.controller.js
- app-frontend/src/app/components/publishModal/publishModal.html
Add Tile Visibility field selection to share modal
Copy needs improvement, but I think we can leave that for later
* Open a project in the project editor
* Click the "share" button
* Verify that changing the Tile Visibility selector will make requests to change the model and persist through 
reloads
Connects #1207
> Add share policy to project share modal

- app-backend/api/src/main/scala/tools/Routes.scala
- app-backend/api/src/main/scala/tools/package.scala
- app-backend/api/src/test/scala/tools/ToolSpec.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/ExtendedPostgresDriver.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Tools.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/Tool.scala
- app-backend/tool/src/main/scala/ast/MapAlgebraAST.scala
- app-backend/tool/src/main/scala/ast/codec/MapAlgebraCodec.scala
- app-backend/tool/src/main/scala/ast/codec/MapAlgebraSourceCodecs.scala
- app-backend/tool/src/main/scala/ast/codec/MapAlgebraUtilityCodecs.scala
In light of the desire to upload putative tool definitions without errors being thrown in the case of incorrectly structured JSON, this PR removes any attempts to parse the a tool definition's JSON AST into a Map Algebra AST from the API. The changes in this PR, therefore, largely consist in reversion of features from PR #1192
Thinking through when, precisely, JSON should be parsed can likely be avoided until more work is done to flesh out how we will apply a Map Algebra AST as a GeoTrellis operation.
> Delay parsing of putative ASTs

- .bintray/.credentials
- docker-compose.yml
Removes distracting bintray warning.
Before:
```
$ ./scripts/console api-server './sbt'
Starting vagrant_postgres_1
[info] Loading project definition from /opt/raster-foundry/app-backend/project
Missing bintray credentials /root/.bintray/.credentials. Some bintray features depend on this.
Missing bintray credentials /root/.bintray/.credentials. Some bintray features depend on this.
Missing bintray credentials /root/.bintray/.credentials. Some bintray features depend on this.
Missing bintray credentials /root/.bintray/.credentials. Some bintray features depend on this.
Missing bintray credentials /root/.bintray/.credentials. Some bintray features depend on this.
Missing bintray credentials /root/.bintray/.credentials. Some bintray features depend on this.
Missing bintray credentials …
```
> Remove bintray warning

- app-backend/database/src/main/scala/com/azavea/rf/database/tables/MapTokens.scala
Follow up to #1243 -- only realized the filtering based on projects, others was broken. This was due to using the wrong value for the filters (each filter started with a new table query) so only the last filter was used.
* Add map tokens for two different projects
* Make a request using no project filter and make one with one
> Fix filtering for map tokens by project ID

- app-frontend/src/app/components/publishModal/publishModal.controller.js
- app-frontend/src/app/components/publishModal/publishModal.html
- app-frontend/src/app/components/sceneItem/sceneItem.module.js
- app-frontend/src/app/components/tokenItem/tokenItem.component.js
- app-frontend/src/app/components/tokenItem/tokenItem.controller.js
- app-frontend/src/app/components/tokenItem/tokenItem.html
- app-frontend/src/app/components/tokenItem/tokenItem.module.js
- app-frontend/src/app/core/services/auth.service.js
- app-frontend/src/app/core/services/token.service.js
- app-frontend/src/app/index.components.js
- app-frontend/src/app/index.module.js
- app-frontend/src/app/index.routes.js
- app-frontend/src/app/pages/settings/settings.controller.js
- app-frontend/src/app/pages/settings/settings.html
- app-frontend/src/app/pages/settings/tokens/api/api.controller.js
- app-frontend/src/app/pages/settings/tokens/api/api.html
- app-frontend/src/app/pages/settings/tokens/api/api.module.js
- app-frontend/src/app/pages/settings/tokens/map/map.controller.js
- app-frontend/src/app/pages/settings/tokens/map/map.html
- app-frontend/src/app/pages/settings/tokens/map/map.module.js
- app-frontend/src/app/pages/settings/tokens/tokens.controller.js
- app-frontend/src/app/pages/settings/tokens/tokens.html
- app-frontend/src/app/pages/settings/tokens/tokens.module.js
- app-frontend/src/app/pages/settings/tokens/tokens.scss
- app-frontend/src/assets/styles/sass/components/_login.scss
* Change Token resource to ApiToken, add MapToken $resource to tokenService 
* Add ability to create, view, and edit project tokens in publish modal (project filter is broken right now)
* Add ability to view and edit all map tokens in the map tokens tab
Disabled org tile visibility option on the frontend b/c we don't really have orgs atm
@designmatty 
* Added `app-frontend/src/app/pages/settings/tokens/tokens.scss` for the tokens view styles. 
* Added a minor fix in `app-frontend/src/assets/styles/sass/components/_login.scss` for the login pages (styles weren't applied to one login modal). Is there a way to just …
> Map Token management views

- app-backend/api/src/main/scala/Router.scala
- app-backend/api/src/main/scala/feed/Routes.scala
- app-backend/api/src/main/scala/feed/package.scala
- app-frontend/src/app/core/core.module.js
- app-frontend/src/app/core/services/feed.service.js
- app-frontend/src/app/pages/home/home.controller.js
- app-frontend/src/app/pages/home/home.html
- docs/swagger/spec.yml
Populate blog posts on the homepage from the rss feed
I had to proxy the requests through our backend to get around CORs. This does let us cache it though, which is nice since their api tends to be inconsistent (250ms - 3000ms in my testing)
* Load the homepage and verify that blog posts appear once they load
Closes #1247
> Populate blog posts on homepage

- app-backend/api/src/main/scala/user/Auth0User.scala
- docs/swagger/spec.yml
Include db and auth0 info in the /me endpoint
```json
{
"user": {
"id": "google-oauth2|116753943799198027869",
"organizations": [
{
"id": "dfac6307-b5ef-43f7-beda-b9f208bb7726",
"name": "Public",
"role": "Viewer"
}
]
},
"oauth": {
"name": "Lucien Knechtli",
"user_metadata": {
"1": {
"label": "Label goes here",
"value": "Value goes here"
}
},
"email_verified": true,
"email": "lknechtli@azavea.com",
"family_name": "Knechtli",
"user_id": "google-oauth2|116753943799198027869",
"identities": [
{
"provider": "google-oauth2",
"user_id": "116753943799198027869",
"connection": "google-oauth2",
"isSocial": true
}
],
"picture": …
```
> Include both database and auth0 users in /me endpoint

- app-backend/common/src/main/scala/Authentication.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/ActionRunner.scala
- app-backend/tile/src/main/scala/Router.scala
- app-backend/tile/src/main/scala/directives/Authentication.scala
- app-backend/tile/src/main/scala/routes/MosaicRoutes.scala
This expands tile request authorization to include map tokens and tile visibility settings.
When a request comes in, we first check if it has a `token` parameter. This corresponds to the current method of specifying JWT in the query string, and is present for backward compatibility. This is also checked first since JWT authentication doesn't require a database call, and may potentially be quicker. If the request contains a `mapToken` parameter, we check to see if that corresponds with the `projectId` in the path. Finally, if neither is specified, we check to see if the project's `tileVisibility` is set to `Public`. If none of these conditions are satisfied, we reject the request with a `403`.
Authorization is evaluated in the order of: `token` JWT, `mapToken`, `project.tileVisibility`. …
> Authorize Tile Access with Map Tokens

- docs/swagger/spec.yml
This PR adds endpoints and models to track uploads of files to Raster Foundry. Additionally, the swagger UI is removed from the project and the specification itself is moved to a folder where it can serve itself to power Raster Foundry's documentation pages.
Swagger spec is served to external site via nginx
This removes the swagger UI since we don't really need it any longer, the swagger editor satisfies most requirements for viewing/editing the spec file.
* Review the added models and endpoints to verify it covers #1264
* Verify that swagger spec is served from `localhost:9100` (nginx) when running `./scripts/server`
Closes #1264
> Add `uploads` to Swagger Spec

- .env.template
- Jenkinsfile
- README.md
- Vagrantfile
- app-tasks/dags/ingest/ingest_project_scenes.py
- deployment/ansible/raster-foundry.yml
- scripts/bootstrap
- scripts/cibuild
- scripts/cipublish
- scripts/load_development_data
This PR is to improve the provisioning of Raster Foundry for developers that do not have access to AWS resources. It replaces areas where resource names are hardcoded with configurable resource names via environment variables.
I think this hits a nice medium ground between easing development for non-Azaveans while ensuring that setup is not particularly difficult. Some experience with AWS is assumed, but I think if there are blind spots in the documentation that can be remedied.
* Provision from this branch
* Ensure the application runs as expected
* Verify instructions …
> Improve Non-Azavea Provisioning

- app-backend/tool/src/main/scala/Parse.scala
- app-frontend/src/assets/styles/sass/components/_modal.scss
- app-frontend/src/assets/styles/sass/layout/_container.scss
- docs/swagger/swagger-ui.js
- prototype/app/assets/sass/components/_modal.scss
Remove any instances of foul language based on the outputs of the `alex` command line tool.
See: https://github.com/wooorm/alex
I ran the following commands against the repository to identify possibly infractions based on the rules encoded into `alex`. From there, I evaluated the output and manually removed a subset of the detected infractions:
```bash
$ find . -name "*.js" -type f | xargs alex
$ find . -name "*.scala" -type f | xargs alex
$ find . -name "*.py" -type f | xargs alex
$ find . -name "*.scss" -type f | xargs alex
```
> Remove foul language from project source code

- deployment/ansible/group_vars/jenkins
Upgrade the version of Terraform used on Jenkins to 0.9.1. This change coincides with the Terraform configuration changes in https://github.com/azavea/raster-foundry-deployment/pull/35.
After SSHing into the Jenkins host, execute the following command and ensure that 0.9.1 is the reported version:
```bash
ubuntu@ip-172-31-52-80:~$ terraform -v
Terraform v0.9.1
```
> Bump Terraform version on Jenkins to 0.9.1

- app-frontend/src/app/components/createProjectModal/createProjectModal.controller.js
- app-frontend/src/app/components/navBar/navBar.controller.js
- app-frontend/src/app/components/navBar/navBar.html
- app-frontend/src/app/components/selectProjectModal/selectProjectModal.component.js
- app-frontend/src/app/components/selectProjectModal/selectProjectModal.controller.js
- app-frontend/src/app/components/selectProjectModal/selectProjectModal.html
- app-frontend/src/app/components/selectProjectModal/selectProjectModal.module.js
- app-frontend/src/app/components/selectedScenesModal/selectedScenesModal.controller.js
- app-frontend/src/app/components/selectedScenesModal/selectedScenesModal.html
- app-frontend/src/app/core/services/project.service.js
- app-frontend/src/app/index.components.js
- app-frontend/src/app/index.routes.js
- app-frontend/src/app/pages/browse/browse.controller.js
- app-frontend/src/app/pages/editor/project/projectEdit.controller.js
- app-frontend/src/app/pages/editor/project/projectEdit.html
- app-frontend/src/app/pages/library/projects/detail/projectScenes/projectScenes.html
This PR adds a dropdown to the nav-bar (in between 'Home' and 'Projects') that displays the currently active project (a concept we are introducing here) and options associated with that project. The dropdown also provides a quick way for a user to switch projects while not leaving the editor/browser.
The browse page now takes a route parameter, `projectid`, that will help handle this change. The current route structure is now `/browse/:projectid/:sceneid?`
To further facilitate this change, the `selectedScenesModal` modal has been modified reflect the single active project concept. After selecting scenes and clicking the button at the bottom of the scenes list, the user is presented with the list of scenes, and from there, they can add those scenes to the currently active project in a …
> Add top-level project dropdown

- docs/swagger/spec.yml
Standardize Swagger spec's `allOf` usage to the following pattern:
```yml
MapToken:
allOf:
- $ref: '#/definitions/BaseModel'
- $ref: '#/definitions/TimeModelMixin'
- $ref: '#/definitions/UserTrackingMixin'
- type: object
properties:
name:
type: string
description: Human friendly label for map token
project:
type: object
properties:
id:
type: string
format: UUID
name:
type: string
```
according to the example here: http://swagger.io/specification/#models-with-polymorphism-support-91
- ~~[ ] Styleguide updated, if necessary~~
- ~~[ ] Symlinks from new migrations present or corrected for any new migrations~~
Validation works using the command line validator:
```bash
$ swagger validate ./docs/swagger/spec.yml
./docs/swagger/spec.yml is valid
```
but not using the online validator: …
> Standardize Swagger spec

- app-frontend/src/app/index.run.js
This PR adds some extra logic to the `app.run` function that ensures we handle situations where the cache is empty by redirecting to the login page. Without this handling, navigating to the app (unless you go right to the login page) transitions to the `/home` route with a blank page.
* Using dev tools, clear all application data (in chrome, you can use the 'Application' tab, then there is a tab on the left for 'Clear Storage')
* Manually navigate to the root URL ('localhost:9091'), and you should get redirected to the login page
* It may be helpful to do this on develop first to see that you can reproduce the problem …
> Handle app boot without cache

- app-frontend/src/app/core/services/auth.service.js
This PR ensures that navigation post-login in delayed until the profile information from Auth0 is loaded into the cache.
This fixes a bug that occurred when the login page attempted to redirect before the cache was available, and as a result, the user was prevented from navigating away, resulting in a blank purple page after logging in. A refresh would then take the user to the home page.
* Log out
* Log in and make sure you are taken to the home page
> Fix login redirect

- app-tasks/rf/src/rf/utils/exception_reporting.py
Rollbar was being initialized multiple times because its initialization was happening inside the decorator code. This moves it into the module code so that it only gets run the first time the module is imported.
* If you want, prior to checking out this branch, run `./scripts/server --with-airflow | grep Rollbar` to confirm that the problem still exists.
* Check out this branch and re-run the previous command, and confirm that the error message disappears.
* Edit a DAG (I used `import_geotiff_scenes`) and add an exception (`raise Exception('test exception')`). Re-run the above command a third time and confirm that your exception appears in Rollbar (make sure you're using a DAG that is being automatically executed, or trigger a run manually).
Closes #1219
> Initialize Rollbar only once in Airflow

- app-backend/build.sbt
- app-backend/common/src/main/scala/S3.scala
- app-backend/ingest/src/main/scala/com/azavea/rf/ingest/CommandLine.scala
- app-backend/ingest/src/main/scala/com/azavea/rf/ingest/Ingest.scala
- app-backend/ingest/src/main/scala/com/azavea/rf/ingest/util/S3.scala
- app-backend/ingest/src/main/scala/com/azavea/rf/ingest/util/UrlRangeReader.scala
- app-backend/ingest/src/main/scala/com/azavea/rf/ingest/util/package.scala
- app-backend/project/Dependencies.scala
- app-backend/project/Version.scala
- app-backend/project/plugins.sbt
Uses windowed GeoTiff reading during ingest to improve parallelism and reduce memory usage.
So far testing shows that we can keep memory usage reasonable during ingest.
`spark-submit --master 'local[*]' ingest/target/scala-2.11/rf-ingest.jar -j file:/Users/eugene/tmp/kayak/test.json -windowSize 512 --overwrite -partitionsPerFile 4`
Connects #1115
Closes #807 
Requires: https://github.com/locationtech/geotrellis/pull/1905
> Windowed GeoTiff Ingest

- app-backend/build.sbt
- app-backend/common/src/main/scala/cache/HeapBackedMemcachedClient.scala
- app-backend/common/src/main/scala/cache/MemcachedClientMethods.scala
- app-backend/project/Dependencies.scala
- app-backend/project/Version.scala
- app-backend/tile/src/main/scala/LayerCache.scala
- app-backend/tile/src/main/scala/StitchLayer.scala
- app-backend/tile/src/main/scala/image/Mosaic.scala
- app-backend/tile/src/main/scala/routes/MosaicRoutes.scala
- app-backend/tile/src/main/scala/routes/SceneRoutes.scala
- app-backend/tile/src/main/scala/routes/ToolRoutes.scala
Addressing the initial issue it became clear that default return type for all IO lookups needs to be `Future[Option[T]]` because any lookup may fail either due to error, missing record, corrupted store. As issue points out failed futures don't compose, so a single failed scene breaks the mosaic.
The next problem is that nested types like `Future[Option[T]]` are difficult to work with, requiring to unwrap first the `Future` and then the `Option`, leading to both lots of opportunity to make an error and temptation to find a shortcut.
The previous implementation of `def attributeStore(bucket: String, prefix: Option[String])` is an example of both of those things.
This PR proposes to standardize around the `cats.data.OptionT` monad transformer which allows `flatMap` and `map` to "drill down" …
> Tiler handle missing Histogram, Ingest Location (introduces OptionT usage)

- deployment/ansible/raster-foundry.yml
Update the `when` clauses so that they use the same variable name we intend to template into `/etc/environment`.
Fixes https://github.com/azavea/raster-foundry/issues/1350
Provision the Vagrant virtual machine with this branch:
```bash
$ vagrant provision
```
Then, SSH in and run the following commands to inspect the environment:
```bash
$ vagrant ssh
vagrant@vagrant-ubuntu-trusty-64:/opt/raster-foundry$ env | egrep "^RF_"
RF_SETTINGS_BUCKET=rasterfoundry-development-config-us-east-1
RF_ARTIFACTS_BUCKET=rasterfoundry-global-artifacts-us-east-1
RF_HOST_USER=hector
vagrant@vagrant-ubuntu-trusty-64:/opt/raster-foundry$ cat /etc/environment
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
AWS_PROFILE=raster-foundry
RF_HOST_USER=hector …
```
> Set environment variables within the VM

- app-backend/api/src/main/resources/application.conf
- app-frontend/src/app/components/navBar/navBar.html
- app-frontend/src/app/pages/home/home.html
Puts the Tools interfaces behind a feature flag so that we can turn them on and off as needed.
- This is currently set to `true` so that the interface continues to show up in staging. #1305 will need to be closed before we can toggle this independently in staging and production.
* Edit `app-backend/api/src/main/resources/application.conf` and set `active = false` for the `tools-ui` feature flag.
* Restart the server and confirm that the Tools interface elements disappear.
Closes #1290
> Add feature flag for displaying Tools

- app-backend/api/src/main/resources/application.conf
- app-backend/api/src/main/scala/uploads/Credentials.scala
- app-backend/api/src/main/scala/uploads/Routes.scala
- app-backend/api/src/main/scala/utils/Config.scala
- docs/swagger/spec.yml
Builds on top of #1323 and #1330. This should actually target `develop`, but am targeting #1330 to reduce diff noise. Will rebase this after that has been merged.
Adds an endpoint which gets temporary credentials to an S3 folder, allowing the front-end to upload files from the user's machine to S3. These credentials use Auth0's [`delegation`](https://auth0.com/docs/api/authentication#delegation) API call, along with AWS's STS configuration, about which more can be learned in #1323. This grants the user permission to list, read, write, and delete files in `s3://${RF_DATA_BUCKET}/user-uploads/<user-id>/`.
While the permissions are for the entire user folder, we return a `bucketPath` that appends the `uploadId` to the above path. This path can be used by the front-end to upload files. The …
> Scoped S3 Credentials

- docs/swagger/spec.yml
This PR revises the swagger API spec to add an endpoint at `/projects/{uuid}/mosaic/batched-corrections/` that will allow sending multiple scene/parameter sets in one request.
* review the updated spec for correctness and fitness with respect to #1354 
Connects #1353
> Add batched correction to API spec

- app-backend/migrations/src/main/scala/migrations/50.scala
I broke the build by forgetting to make my new migration's symlink relative :man_facepalming: . This PR undoes my previous evils.
* don't
* this was dumb
* i am ashamed
* :man_facepalming:
> Make migration link relative

- app-frontend/config/webpack/global.js
- app-frontend/package.json
- app-frontend/src/app/components/filterPane/filterPane.controller.js
- app-frontend/src/app/components/filterPane/filterPane.html
- app-frontend/src/app/index.module.js
- app-frontend/src/app/index.vendor.js
- app-frontend/src/assets/styles/sass/_shame.scss
- app-frontend/yarn.lock
Use a date range picker to filter on date in the browse view
We don't have a way to create open-ended filters right now
* Run "yarn" to install the new libraries before starting the frontend with "yarn dev"
* Go to the browse view
* Verify that the date range picker picker works as expected.
* Verify that disabling the picker removes the filter
* Verify that the picker still persists its filter within the same browser session (nav to another view and back)
Connects #996
> Use date range picker instead of year / month filters

- app-frontend/src/app/index.routes.js
Trailing slashes cause routes not to match
* Navigate to a non-home view with a `/` at the end of the url.
* Verify that it does not redirect to the home view and preserves the trailing slash
Connects #1373
> Don't enforce strict url matching

- app-backend/common/src/main/scala/UserErrorHandler.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Projects.scala
- app-backend/tile/src/main/scala/directives/TileErrorHandler.scala
This attempts to reduce the noise in Rollbar by not notifying client errors. These errors will still be logged for development purposes.
Of the individual errors mentioned in #1233, there are three categories:
* `InvalidParameterExceptions` like https://rollbar.com/Azavea/RasterFoundry/items/152/. We fix this by not reporting any client exceptions, with the exception of `IllegalStateException` and the catch all `Exception`.
* Authentication errors like https://rollbar.com/Azavea/RasterFoundry/items/109/ and https://rollbar.com/Azavea/RasterFoundry/items/110/. These were internally raised as `IllegalStateException`s. We fix them by raising the appropriate `403` or `404` `ClientError` in a new `IllegalRequestException`, which is handled by passing through the status code and error message …
> Remove Client Error Notifications from Rollbar

- app-backend/database/src/main/scala/com/azavea/rf/database/QueryParameters.scala
- app-tasks/dags/geotiff/find_geotiff_scenes.py
- app-tasks/dags/geotiff/import_geotiff_scenes.py
- app-tasks/rf/src/rf/models/base.py
- app-tasks/rf/src/rf/uploads/geotiff/__init__.py
- app-tasks/rf/src/rf/uploads/geotiff/create_bands.py
- app-tasks/rf/src/rf/uploads/geotiff/create_footprints.py
- app-tasks/rf/src/rf/uploads/geotiff/create_scenes.py
- app-tasks/rf/src/rf/uploads/geotiff/factories.py
- app-tasks/rf/src/rf/uploads/geotiff/io.py
This added two TODOs, captured as #1386 and #1387
- You may want to reset your airflow db before you do this. To do that, `./scripts/console airflow-worker bash`, then `airflow resetdb`, `airflow initdb` (as long as the scheduler isn't up no tasks should start)
- From the api project's console, create the same upload from #1371, but add a file (`:paste` this):
```scala
/** Prepare a bunch of values */
val user = Await.result(Users.getUserById("default"), 3 seconds).get
val orgId = Await.result(database.db.run(Organizations.take(1).result), 3 seconds).head.id
val datasourceId = Await.result(database.db.run(Datasources.filter(_.visibility === (Visibility.Public:Rep[Visibility])).take(1).result), 3 seconds).head.id
val …
```
> Use uploads API for scene imports

- app-backend/api/src/main/scala/datasource/Routes.scala
- app-backend/api/src/main/scala/image/Routes.scala
- app-backend/api/src/main/scala/maptoken/Routes.scala
- app-backend/api/src/main/scala/project/Routes.scala
- app-backend/api/src/main/scala/scene/Routes.scala
- app-backend/api/src/main/scala/tags/Routes.scala
- app-backend/api/src/main/scala/thumbnail/Routes.scala
- app-backend/api/src/main/scala/toolrun/Routes.scala
- app-backend/api/src/main/scala/tools/Routes.scala
- app-backend/api/src/main/scala/uploads/Routes.scala
- app-backend/api/src/test/scala/thumbnail/ThumbnailSpec.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/fields/OrganizationFkFields.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/fields/UserFkFields.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Datasources.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Images.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/MapTokens.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Projects.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Scenes.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Thumbnails.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/ToolRuns.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/ToolTags.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Tools.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Uploads.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/User.scala
- app-backend/tile/src/main/scala/LayerCache.scala
- app-backend/tile/src/main/scala/directives/TileAuthentication.scala
Any user that is a member of the [root organization](https://github.com/azavea/raster-foundry/blob/13ac14022fc9d9ce07c096968d2be57d440ef20d/app-backend/migrations/src_migrations/main/scala/2.scala#L13) is a _super user_. Super users have access to everything and can make all API calls. Regular users can only access datasources, images, maptokens, projects, scenes, tags, thumbnails, toolruns, tools, and uploads that belong to the same organization as the users themselves.
The `User` class has been augmented with two methods: `isInRootOrganization` and `isInRootOrSameOrganizationAs(target)`. The first returns true for super users, and the second for super users as well as members of `target`'s organization.
All _create_ and _update_ routes have been decorated with AKKA HTTP's `authorize` …
> Add Authorize Directive, Limit Access to Members and Super Users

- app-backend/api/src/main/scala/project/Routes.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/ScenesToProjects.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/SceneToProject.scala
This PR adds an endpoint at `/projects/{uuid}/mosaic/bulk-update-color-corrections/` that adds color-correction parameters to project/scene combinations in bulk, which either succeed or fail together. It is intended to fix a bug that resulted in inconsistent application of parameters to tiles.
* revise `ScenesToProjects.scala` to introduce random failures; I used this -->
```
def setColorCorrectParams(projectId: UUID, sceneId: UUID, colorCorrectParams: ColorCorrect.Params)(implicit database: DB) = {
val r = new Random()
val draw = r.nextInt(4)
println(draw)
draw match {
case 1 =>
throw new IllegalStateException( …
```
> Add batch color-correction endpoint

- app-backend/api/src/main/scala/datasource/Routes.scala
- app-backend/api/src/main/scala/image/Routes.scala
- app-backend/api/src/main/scala/maptoken/Routes.scala
- app-backend/api/src/main/scala/organization/Routes.scala
- app-backend/api/src/main/scala/project/Routes.scala
- app-backend/api/src/main/scala/scene/Routes.scala
- app-backend/api/src/main/scala/tags/Routes.scala
- app-backend/api/src/main/scala/thumbnail/Routes.scala
- app-backend/api/src/main/scala/toolrun/Routes.scala
- app-backend/api/src/main/scala/tools/Routes.scala
- app-backend/api/src/main/scala/uploads/Routes.scala
- app-backend/api/src/main/scala/user/Routes.scala
- app-backend/api/src/test/scala/organization/OrganizationSpec.scala
- app-backend/api/src/test/scala/user/UserSpec.scala
- app-backend/common/src/main/scala/Authentication.scala
- app-backend/common/src/main/scala/CommonHandlers.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Organizations.scala
Builds on top of #1358. There are two commits: the first makes it so only members of the root organization can list, create, and update organizations and users. We do not allow deleting organizations or users to anyone. Members of an organization can view their own organization. Users can view themselves, and edit their Auth0 profile.
The second standardizes behavior of all update and delete endpoints, each of which should result in a single record being affected. In this case, we return a `204 No Content`. In case no rows were affected, we return a `404 Not Found`. In all other cases, we raise an exception which eventually returns a `400 Bad Request`.
I've targeted this to #1358 to keep the diff minimal. Will not merge this until that is in, then will rebase on top of `develop` and …
> Directives Follow Up: Limit to Root Members, Single Result

- app-frontend/src/app/components/colorCorrectAdjust/colorCorrectAdjust.controller.js
- app-frontend/src/app/components/colorCorrectAdjust/colorCorrectAdjust.html
- app-frontend/src/assets/styles/sass/_shame.scss
- app-frontend/src/assets/styles/sass/components/_filter.scss
Add toggleable linking of gamma sliders
@designmatty Made a slight style edit - the filter separator (formerly a border-bottom on the filter) is now a separate div element, so it can be adjusted to allow for items on the actual divider such as buttons. New styles have been placed in `_shame.scss` as usual.
To test with greyscale tiles, set the color correction of a scene to have the green, red, and blue band set to the same value
* Go to the color correction pane in a project
* Verify that the linking starts out enabled if gamma values are loaded as the same
* Verify that linked gamma values move together
* Verify …
> Add gamma correction linking

- app-tasks/rf/src/rf/models/upload.py
- app-tasks/rf/src/rf/uploads/geotiff/create_thumbnails.py
- app-tasks/rf/src/rf/uploads/geotiff/factories.py
This PR adds `visibility` to the python `Upload` model and coerces footprint dimensions for scenes from raw geotiffs to `int`. With raw geotiffs, it's possible that the scale factor * the starting dimensions results in a float value, which circe reasonably refuses to decode as an int (ain't type safety grand).
It isn't obvious to me whether this should be `int(...)` or `ceil(...)`, but that's a future 0 point change if this introduces 1px seams.
Also, I figured out how to turn (non-nested, though nesting isn't too tricky to imagine with recursion and a little extra formatting) python dicts into potentially decodable circe `JsonObject`s. I found this useful for testing without having to go through http requests all the time.
```python
def asJson(x):
if isinstance(x, basestring):
return …
```
> Ensure thumbnail creation works for raw geotiff import

- Jenkinsfile
- scripts/cibuild
- scripts/cipublish
- scripts/deploy-docs
This PR adds `scripts/deploy-docs` to sync documentation to an S3 bucket. 
See [spec.staging.rasterfoundry.com](https://spec.staging.rasterfoundry.com) and [Jenkins Output](http://jenkins.staging.rasterfoundry.com/job/raster-foundry/job/raster-foundry/view/change-requests/job/PR-1402/8/)
Connects #1272 , depends on azavea/raster-foundry-deployment#41
> Add deployment for Swagger spec

- app-frontend/src/app/components/createProjectModal/createProjectModal.controller.js
- app-frontend/src/app/components/importModal/importModal.controller.js
- app-frontend/src/app/components/importModal/importModal.html
This PR fixes the project creation process to allow for doing an upload right after project creation.
Between the project creation process and the standard import process it adds a datasource selection step. The datasource selection is built into the import modal, so that anytime the modal is opened but a datasource isn't specified, the selection step is presented.
This also adjusts the code to set the `files` of an upload to a list of fully qualified s3 resource URIs rather than just filenames. This addresses #1446.
This does not actually link the upload to the project, as that connection does not yet exist.
* Create …
> Allow import from project creation

- app-backend/api/src/main/resources/application.conf
- app-backend/api/src/main/scala/config/Config.scala
- app-backend/api/src/main/scala/utils/Config.scala
- app-frontend/src/app/core/services/rollbarWrapper.service.js
- app-frontend/src/app/index.config.js
This PR passes through the environment variable `ENVIRONMENT` to the front-end via the `/config` endpoint so that the front-end has a way to determine what environment it is running in aside from the `process.env.NODE_ENV`, which is not reliable for this use.
This should allow Rollbar to properly funnel client-side errors in Staging to the proper Rollbar environment.
There shouldn't be any changes to the deployment scripts as `ENVIRONMENT` is already set.
This one is a bit difficult to test.
* See that the environment is being provided to the front-end in the `/config` response
Connects #1394
> Remove use of NODE_ENV where possible

- app-frontend/src/app/components/colorCorrectPane/colorCorrectPane.controller.js
- app-frontend/src/app/core/services/colorCorrect.service.js
This PR updates the color correction logic to use the new bulk color-correction endpoint.
We probably should look into either removing the 'Reset Changes' option or making it work in an expected manner, because as it is now, the button sets the color-correction to an arbitrary set of corrections that don't make sense.
* Go into color correction for a project with multiple ingested scenes
* Select multiple scenes, monitor network traffic and see that there is a single request for color-correction changes
* Make sure single scene correction works correctly
Closes #1355
> Use bulk color-correction endpoint

- app-tasks/dags/landsat8/import_landsat8_scenes.py
This PR requests scenes from the day prior to the task execution date. This will prevent the task from failing when trying to get scenes for the current day.
* Manually kick of the `find_landsat8_scenes` task in the airflow UI and set the execution date for the current day
* Check the task instances and see your new task in the list, verify the execution date is today
* View the task logs, and see that the logs indicate the task is searching for scenes from the previous day
Closes #1227
> Request previous day's landsat scenes

- app-backend/database/src/main/scala/com/azavea/rf/database/fields/UserFkVisibleFields.scala
- app-tasks/dags/ingest/ingest_project_scenes.py
- app-tasks/rf/src/rf/ingest/__init__.py
- app-tasks/rf/src/rf/ingest/geotiff_ingest.py
- app-tasks/rf/src/rf/ingest/models/source.py
- app-tasks/rf/src/rf/uploads/geotiff/create_footprints.py
- app-tasks/rf/src/rf/uploads/geotiff/create_thumbnails.py
Updates ingest definition creation to support more than Landsat data. Any multiband geotiff should work from the import to ingest and succeed on the whole pipeline.
Additional problems uncovered during testing are fixed here as well:
- Use rasterio's built in dataset mask functionality for footprints
- Add convert command to do basic balancing of thumbnails
- Disables user FK visibility filter for admin org
- Encode URIs for tiff location
Opened https://github.com/azavea/raster-foundry/issues/1462 because this PR uncovered an issue where users cannot view scenes that they imported.
- Obtain test tiff to import
- Start …
> Refactor Ingest Definition Creation

- app-backend/api/src/main/scala/Main.scala
- app-backend/common/src/main/scala/MalformedContentRejectionHandler.scala
This PR transforms the messages associated with `MalformedRequestContentRejection`s from ugly and not user-friendly to pretty and user-friendly.
If you're a cool kid with `httpie`, set an `RF_TOKEN` env variable, and:
```
http :9000/api/scenes/ Authorization: $RF_TOKEN foo=bar
http :9000/api/projects/ Authorization: $RF_TOKEN foo=bar
http :9000/api/thumbnails/ Authorization: $RF_TOKEN foo=bar
```
Setting up an implicit `RejectionHandler` where `bindAndHandle` is called is the [recommended way to implement custom rejection handling](http://doc.akka.io/docs/akka-http/10.0.1/scala/http/routing-dsl/rejections.html). I'm pretty sure we could do the same thing with the `UserErrorHandler` and not have to extend it in every `FooRoutes` trait.
If we do that, I think we throw both custom handlers …
> Add a custom rejection handler for malformed requests

- app-backend/api/src/main/resources/application.conf
- app-backend/api/src/main/scala/config/Config.scala
- app-backend/api/src/main/scala/utils/Config.scala
- app-frontend/src/app/core/services/layer.service.js
- app-frontend/src/app/core/services/project.service.js
- nginx/etc/nginx/conf.d/api.conf
- nginx/etc/nginx/conf.d/tiler.conf
This commit adds support for splitting the tile server from the api server on both the backend and frontend. On the backend, the tile server location is injected via an environment variable that is returned via the `/config` endpoint.
On the frontend, the response in `/config` is used when constructing tile requests.
Config response
Publish URLs
Tiles Load Correctly
- Download most recent `.env` file and start server
- Start development frontend server
- Go to `/config` and verify tile server location is returned
- Open a project that has been ingested, ensure that tiles load
- Verify that tile URL is correct for …
> Split Tileserver

- app-frontend/src/app/components/sceneItem/sceneItem.component.js
- app-frontend/src/app/components/sceneItem/sceneItem.controller.js
- app-frontend/src/app/components/sceneItem/sceneItem.html
- app-frontend/src/app/components/sceneList/sceneList.component.js
- app-frontend/src/app/components/sceneList/sceneList.controller.js
- app-frontend/src/app/components/sceneList/sceneList.html
- app-frontend/src/app/components/sceneList/sceneList.module.js
- app-frontend/src/app/index.components.js
- app-frontend/src/app/pages/imports/imports.controller.js
- app-frontend/src/app/pages/imports/imports.html
Reorganizes the Imports page to better match the latest wireframes
- There is some styling that needs to be done on the buttons to solve z-indexing issues (as well as make them match the mockup styling better and add a hamburger icon). @designmatty 
- It's not exactly clear where clicking the "Import Scenes" button should go because right now you need to navigate through the Datasources list in order to start an import. So I've just made it take you to the Datasources list page.
- This adds a `sceneList` component which might be a starting point for a solution to #1468, but doing that full refactor was outside the scope of this card.
* Load up the front end and click "Imports" in the nav bar. You should see a screen similar to the first screenshot above.
* Because there's no way to …
> Reorganize Imports page

- Jenkinsfile
- app-backend/export/Dockerfile
- app-backend/ingest/Dockerfile
- app-tasks/.dockerignore
- app-tasks/Dockerfile
- scripts/cipublish
- worker-tasks/Dockerfile
Try not to reinstall all dependencies if changes are detected by the `Dockerfile` step that copies module source code into the container image. Instead, make it so that dependency reinstallation only occurs when the contents of `requirements.txt` changes.
Also, upgrade Spark container images so that 2.1.x is used.
Part of https://github.com/azavea/raster-foundry/issues/1347
Build Airflow container image, execute the test suite (creates a bunch of files we don't necessarily care about), and build container image again. The second time, it should skip over all of the dependency installation steps.
```bash
$ docker-compose -f docker-compose.airflow.yml -f docker-compose.test.yml \
build airflow
$ docker-compose -f docker-compose.airflow.yml -f docker-compose.test.yml \
run --rm --entrypoint …
```
> Minimize Airflow container rebuilds; upgrade Spark container images

- app-backend/api/src/main/scala/uploads/QueryParameters.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/QueryParameters.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Uploads.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/UploadStatus.scala
- docs/swagger/spec.yml
This PR implement a status filter for Uploads.
* (assuming there are `upload` records)
* send a `GET` request to `api/uploads?uploadStatus=BOGUS` endpoint and check that an error is returned
*  `GET` `/api/uploads?uploadStatus=[status with some records]` such that the `uploadStatus` argument should return something, check that the results are expected
* `GET /api/uploads?uploadStatus=[status with no records]` such that no results are expected, check that the result is a `200` response with an empty `results` field
* check the swagger docs for accuracy of the added query parameter
Closes #1386
> Add status-filter for Uploads

- app-backend/api/src/main/scala/config/Routes.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/OrgFeatureFlags.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/OrgFeatureFlags.scala
This PR implements the service-layer changes needed to support organization-level feature overrides.
To facilitate testing, I added a route at `config/organization/{UUID}`. This may be removed or re- purposed as part of #1410.
* add a record to `organization_features`, e.g.
```
insert into organization_features (organization, feature_flag, active)
VALUES ('9e2bef18-3f46-426b-a5bd-9913ee1ff840','68144a5a-bf71-4925-b2f6-94893333c88d',FALSE);
```
* `GET` `http://localhost:9000/config/organization/9e2bef18-3f46-426b-a5bd-9913ee1ff840` and check that the response agrees with the added record(s)
* `GET …
> Service-layer implementation of organization overrides for feature flags

- app-tasks/dags/aoi-monitoring/find_aoi_projects_to_update.py
- app-tasks/dags/aoi-monitoring/update_aoi_projects.py
This PR adds stubbed DAGs for area of interest monitoring. The stubbing is based on stubs in #1042.
1. Because we don't have a schedule frequency determined or a minimum value for cadences (AFAIK), the `run_id`s for the `DAG` that does all the work includes time data down to seconds. We could relax this with a minimum cadence or if we knew what the schedule was going to be.
2. I _think_ the last update time should be updated independent of whether there are scenes to update. This creates a race condition though, where:
1. The project is found as a project that needs to update
2. The DAG to update the project gets scheduled
3. The …
> Add stub dags for area of interest monitoring

- app-backend/api/src/main/scala/Router.scala
- app-backend/api/src/main/scala/config/Routes.scala
- app-backend/api/src/main/scala/featureflags/Routes.scala
- app-backend/api/src/main/scala/featureflags/package.scala
This PR adds an API endpoint at `/organizations/{ID|/ff-overrides/` that lists all feature overrides for a specified organization.
* add a record to organization_features, e.g.
```
insert into organization_features (organization, feature_flag, active)
VALUES ('{organization ID}','{feature_flag ID}',TRUE);
```
* GET http://localhost:9000/feature-flags and check that the response agrees with the added record(s)
Closes #1410
> Add API endpoint for organization feature overrides

- app-tasks/Dockerfile
Effectively reverts `a15ced` and adds java back
See https://github.com/azavea/raster-foundry/commit/a15ced453f9cb45aece5a1c1c08c7a8c8f04a5d3
Still a WIP - haven't had a chance to test fully.
* Build airflow worker: `docker-compose -f docker-compose.airflow.yml  build airflow-worker`
* Get a shell in docker container: `./scripts/console airflow-worker bash`
* Check java version: `java -version`
Closes #1447
> Add java dependency back to airflow

- app-frontend/src/app/core/services/auth.service.js
- app-frontend/src/app/core/services/featureFlags.provider.js
- app-frontend/src/app/index.run.js
- nginx/etc/nginx/conf.d/api.conf
This modifies the front-end to use the new authenticated `/feature-flags` endpoint to allow per-user feature flag determination (though on the backend it is only per-organization at the moment).
This was more complicated than it needed to be due to the way our application is initialized and because the existing feature flags service doesn't return promises. The core issue is that there is no single point after we confirm that the user is authenticated (either via login or page reload) where we can block the rest of the application's initialization while we wait for the per-user feature-flags to be populated. The need for this could be alleviated by making the feature-flags service return promises, but that would have been a much bigger refactor than this card anticipated. I've put in a …
> Use per-user feature flags on the frontend

- app-frontend/src/app/pages/projects/edit/browse/browse.controller.js
Fixes bug where scene grid is not always interact-able via click.
The `registerClick` variable is used to disable canvas interactions when drag-panning.
*Before checking out this branch (bug reproduction):*
- open a project with ingested scenes within the scene browser (where the grid is visible)
- reload the window
- navigate back to the scene list via the '< Scenes' button, then return to the scene add page using the 'Browse Scenes to Add` button
- notice that the grid doesn't respond to click until you trigger a map move event of some sort (pan, zoom)
*Testing this fix:*
- do the same thing as above, except you …
> Initialize `registerClick` flag in browse

- app-frontend/src/app/components/sceneDetailModal/sceneDetailModal.component.js
- app-frontend/src/app/components/sceneDetailModal/sceneDetailModal.controller.js
- app-frontend/src/app/components/sceneDetailModal/sceneDetailModal.html
- app-frontend/src/app/components/sceneDetailModal/sceneDetailModal.module.js
- app-frontend/src/app/components/sceneItem/sceneItem.html
- app-frontend/src/app/index.components.js
- app-frontend/src/app/pages/projects/detail/detail.controller.js
- app-frontend/src/app/pages/projects/detail/detail.html
- app-frontend/src/assets/styles/sass/_shame.scss
- app-frontend/src/assets/styles/sass/components/_modal.scss
This PR adds a scene detail modal to replace our previous scene detail implmentation (side-panel + overlay).
The modal width is not ideal.
* Go to a projects detail page and click on a scene; see that the modal opens
* Click the download button and check that this works as expected
Closes #1454
> Scene detail modal

- .gitignore
- app-tasks/Dockerfile
- docker-compose.airflow.yml
- scripts/cibuild
- scripts/cipublish
Adding the batch jar to our airflow worker is necessary so that
we can run `java -jar` (non-spark) jobs to do various batch tasks within an
airflow worker
* Create an assembly jar of the batch project:
```bash
./scripts/console api-server "./sbt batch/assembly"
```
* Get a console in an `airflow-worker` and check that the assembly jar is added
```bash
./scripts/console airflow-worker "ls -lah /opt/raster-foundry/jars"
```
* Build a new airflow docker container and verify that the jar has been added to the built container
```bash
GIT_COMMIT=batch docker-compose -f docker-compose.test.yml build airflow
docker run -it …
```
> Add batch jar to airflow

- app-backend/build.sbt
- app-backend/project/Version.scala
- app-backend/project/build.properties
- app-backend/project/plugins.sbt
1. Fixes a problem with using our shapeless dependency which seemed to be overridden in the class path without shading. I'm not sure if there is a definite way to determine that, but [this](http://stackoverflow.com/a/42658876) SO post suggests a similar problem.
2. Updates our scala dependency to 2.1.0 -- this wasn't included in our assembly jar, but helps ensure we are compiling against the version we are running in.
* On this branch, run `./scripts/console api-server "./sbt batch/assembly"` to create a new assembly jar
* Upload assembly to S3 and give it your own unique name in the …
> Fix shapeless EMR error

- app-tasks/dags/ingest/ingest_project_scenes.py
- app-tasks/requirements.txt
This PR sends ingest jobs to EMR instead of to AWS Batch.
This doesn't get us all the way to ingests _running_ on EMR, just to airflow successfully kicking them off. For some reason, though copy/pasting the command from the EMR steps to the cluster master "works" fine (in the sense that spark-submit attempts to run the application), something kills it in EMR before it reaches that point, failing with the ever-cryptic "Local file does not exist." (_which_ local file, you punk???)
These are long and torturous. :(
* Fire up your server and your airflow and your frontend
* Add a scene to a project so airflow will find it
* Wait a bit …
> Use the EMR step API for ingests instead of batch

- app-frontend/src/app/components/exportModal/exportModal.component.js
- app-frontend/src/app/components/exportModal/exportModal.controller.js
- app-frontend/src/app/components/exportModal/exportModal.html
- app-frontend/src/app/components/exportModal/exportModal.module.js
- app-frontend/src/app/components/sceneItem/sceneItem.component.js
- app-frontend/src/app/core/services/project.service.js
- app-frontend/src/app/index.components.js
- app-frontend/src/app/pages/projects/edit/edit.controller.js
- app-frontend/src/app/pages/projects/edit/edit.html
- docs/swagger/spec.yml
This PR adds an export modal that allows the user to select the zoom level at which they would like to export a selected project.
This uses a slider to select the zoom level as it seems like the most clear way to indicate min/max zoom levels and removes the need for more complex validation logic.
The swagger spec in regards to the export statuses seemed to not match what the endpoint was actually expecting, so I updated it to match.
We want to specify zoom level, but it's not clear how we expect that to be provided in the request. `rasterSize` seemed like the closest option.
This hardcodes some assumed defaults for now:
- visibility of `PRIVATE`
- export type of `S3`
- …
> Project export modal

- app-frontend/src/app/pages/projects/edit/advancedcolor/adjust/adjust.controller.js
- app-frontend/src/app/pages/projects/edit/advancedcolor/adjust/adjust.html
This PR adds a saturation slider to the advanced color correct panel.
Intended to ease the debugging of backend saturation filter development.
This PR is based on a non-merged PR (#1578) so it should not be merged before that one.
(The values here were from different adjustments, they do match in actual usage)
We'll need to decide on a default value.
WIP
Closes #1527
> Saturation slider

- app-backend/batch/src/main/scala/com/azavea/rf/batch/landsat8/ImportLandsat8.scala
- app-tasks/dags/landsat8/import_landsat8_scenes.py
This PR introduces batch job usage instead of old python code to write metadata, changes a bit import job behaviour, exits with status code != 0 when no scenes were ingested (means bad data, not in cases when it already existed in the db).
Run this DAG through UI
Closes #1519
> Import landsat8 dag to use jar

- app-backend/api/src/test/scala/datasource/DatasourceSpec.scala
- app-backend/api/src/test/scala/project/ProjectSceneSpec.scala
- app-backend/batch/src/test/resources/export/localJob.json
- app-backend/batch/src/test/scala/com/azavea/rf/batch/export/model/ExportDefinitionSpec.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Projects.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/ColorCorrect.scala
- app-backend/tile/src/main/scala/package.scala
- docs/swagger/spec.yml
This adds Saturation correction to the color correct endpoint. The HSV / HSL Wikipedia page has a lot of useful info explaining what's going on: https://en.wikipedia.org/wiki/HSL_and_HSV
- ~This is not ready to merge -- it currently causes rampant out-of-memory errors from `memcached` on my VM when saturation correction is enabled.~
- ~This also seems to exacerbate or separately suffer from a strange and difficult-to-reproduce bug I've encountered previously where the tile server would start returning patches of NoData in certain areas (you can see that in the white patches in the screenshot above). It now happens all the time, which is also a blocker for merging this. Because I've seen the behavior before I suspect that it may be an interaction with some other part of the code that is …
> Add Saturation parameter to color correction

- app-backend/.dockerignore
Our dockerignore file was a little out of date and was leading to
a long `copy` step in our docker file as context was gathered.
Trivial, merging
> Update scala dockerignore to include new subprojects

- app-tasks/rf/src/rf/ingest/geotiff_ingest.py
- app-tasks/rf/src/rf/ingest/landsat8_ingest.py
This commit fixes the reversal of extent crs and crs in creating an
ingest definition.
In some ways, this mirrors
https://github.com/azavea/raster-foundry/pull/1184 but on the "client"
side that is generating the ingest definition.
I'm inclined not to write a test case here as we transition away from
using the python library for this sort of thing (for this very reason)
it does not seem very worthwhile.
* Start server and wait for API to start working
* Log into an airflow worker and open an ipython shell
```
./scripts/console airflow-worker bash
ipython
```
* In an `ipython` shell request a landsat scene, create an …
> Fix reversal of `crs` and `extent_crs`

- app-frontend/src/app/pages/lab/run/run.controller.js
This fixes a bug where the correct tile server location is not
used when requesting tiles in the Lab UI.
Closes #1654
> Fix tile server location in lab UI

- app-backend/batch/src/main/resources/application.conf
- app-backend/batch/src/main/scala/com/azavea/rf/batch/Main.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/SparkJob.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/airflow/export/CreateExportDef.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/util/S3.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/util/conf/Config.scala
- app-backend/build.sbt
- app-backend/project/Dependencies.scala
- app-backend/project/Version.scala
- app-tasks/dags/export/do_export.py
- app-tasks/dags/export/find_exports.py
This PR adds to the `app-backend/batch` project so that export jobs may be kicked off. It also adds Airflow DAGs to the same effect.
There are a couple remaining points that should be eventually clarified about a couple implementation details; whether actually *addressing* them takes place as part of this PR or deferred in favor of a future one should probably depend on the difficulty.
Specifically:
* The Route 53 ID is provided literally in `CreateExportDef`; this should be config-derived but the manner of doing so wasn't immediately obvious.
* The airflow DAG doesn't really check the status of the job, and …
> Implement export workflow

- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Scenes.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Tools.scala
- app-backend/tile/build.sbt
- app-tasks/rf/src/rf/uploads/geotiff/create_bands.py
- app-tasks/rf/src/rf/uploads/geotiff/create_footprints.py
- app-tasks/rf/src/rf/uploads/geotiff/create_thumbnails.py
A few minor fixes to allow imports and ingests to process successfully.
1. Allows root users to update any scene, this manifested itself in a bunch of `400` errors on staging
2. Check bands before generating thumbnails
3. Adds resampling before footprint generation
4. Adds a few convenience imports for the tile subproject
5. Fixes filtering for tools
* Start servers and airflow, limit airflow to finding geotiffs to import and the import geotiff dags
* Upload a singleband geotiff
* Ensure that it gets processed successfully
* Go to Tools UI - ensure that you can see tools now
> Add support for single band raster import

- app-frontend/src/app/components/createProjectModal/createProjectModal.controller.js
- app-frontend/src/app/components/createProjectModal/createProjectModal.html
- app-frontend/src/app/pages/projects/list/list.controller.js
This PR makes a change to the project creation modal and project list page that triggers a reload of the project list if a new project has been created.
Previously, when creating a project within the modal sequence and then choosing to import your own imagery would eventually result in the user being back on the project list page which would not show the project they just created.
I made a small change to a method that I've implemented on several modals: `closeWithData`. Previously, this method would take a single argument that would be passed on as the resolved value of the modal. In this modal, I instead created an …
> Make project list reload when project created

- app-backend/api/src/test/scala/datasource/DatasourceSpec.scala
- app-backend/api/src/test/scala/project/ProjectSceneSpec.scala
- app-backend/batch/src/test/resources/export/localJob.json
- app-backend/batch/src/test/resources/export/testFileJob.json
- app-backend/batch/src/test/resources/export/testJob.json
- app-backend/batch/src/test/scala/com/azavea/rf/batch/export/model/ExportDefinitionSpec.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Projects.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/ColorCorrect.scala
- app-backend/tile/src/main/scala/package.scala
- docs/swagger/spec.yml
This PR implements individual clipping for RGB bands as part of the set of `ColorCorrection` parameters.
With color correction settings:
```
{"items":[{"sceneId":"63b15316-2b28-4280-8eb5-c98de4adffab","params":{"redBand":4,"greenBand":3,"blueBand":2,"redGamma":null,"blueGamma":null,"greenGamma":null,"brightness":-6,"contrast":0,"alpha":null,"beta":null,"min":null,"max":null,"equalize":false,"redMax":null,"greenMax":null,"blueMax":null,"redMin":null,"greenMin":null,"blueMin":null,"saturation":null}}]}
```
Unmodified:
With `redMax:20000` `redMin:500`:
As above, plus `greenMax:30000`:
As above, plus `blueMax:1000` & `blueMin:300`:
As above, plus `min:10000` (which …
> Implement individual RGB color channel clipping

- app-frontend/src/app/components/projectItem/projectItem.controller.js
- app-frontend/src/app/components/projectItem/projectItem.html
- app-frontend/src/app/components/sceneItem/sceneItem.html
- app-frontend/src/app/components/statusTag/statusTag.component.js
- app-frontend/src/app/components/statusTag/statusTag.controller.js
- app-frontend/src/app/components/statusTag/statusTag.html
- app-frontend/src/app/components/statusTag/statusTag.module.js
- app-frontend/src/app/components/statusTag/statusTag.scss
- app-frontend/src/app/core/core.module.js
- app-frontend/src/app/core/services/project.service.js
- app-frontend/src/app/core/services/status.service.js
- app-frontend/src/app/index.components.js
This PR adds the display of statuses to the UI through tags.
There are a few parts to this which each have their own commit.
1) **Adds a `statusService` service and `statusTag` component** - the `statusService` maintains the map of entity-types (project, scene, import, etc) to the various statuses and their user-facing label and color. The `statusTag` component uses this service and can display any status that is defined in the service. The `statusTag` component takes an `entity-type` (i.e. 'project', 'scene', etc.) and a `status` ('INGESTING', 'FAILURE', etc.).
2) **Adds the status tag to scenes using `scene.statusFields.ingestStatus`**
3) **Adds a method to compute project status to the `projectService`** - this method gets the statuses of all scenes within a project and determines the …
> Add state tags to various UI items

- app-backend/tile/src/main/scala/routes/MosaicRoutes.scala
Adds a histogram endpoint that is designed to power the color-correction histogram. If provided a Project ID and a list of Scene IDs, returns an array of histograms for those Scenes after color correction from the Project has been applied.
* This doesn't currently include a summary histogram, even though it's in the wireframes. That can either be computed on the front end or this endpoint can be updated to include one (in which case the response format should probably be updated to differentiate per-band histograms from the summary histogram). I wasn't sure which approach would make the most sense, so I left it out, but it should be straightforward to add if necessary.
* The Scenes are currently getting resampled down to 64x64 pixels for the histogram calculation; anything significantly …
> Add per-scenes histogram endpoint

- app-backend/batch/src/main/scala/com/azavea/rf/batch/Main.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/aoi/airflow/FindAOIProjects.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/aoi/airflow/UpdateAOIProject.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/export/airflow/CreateExportDef.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/landsat8/airflow/ImportLandsat8.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/sentinel2/airflow/ImportSentinel2.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Projects.scala
- app-tasks/dags/aoi-monitoring/find_aoi_projects_to_update.py
- app-tasks/dags/aoi-monitoring/update_aoi_projects.py
Implements batch jobs to updated AOI and AOI DAGs to use batch.jar
The format of printing found AOI projects UUIDs is arguable and any comments are appreciated (currently just a println message in the stdout). However it can be discussed after updating Airflow DAGs in a separate PR.
**find_aoi_projects_to_update**
**find_aoi_projects_to_update**
**update_aoi_projects**
To test Scala part:
To do the commands below, it's necessary to have an AOI project with AOI and AoiToProject relation.
```bash
java -cp rf-batch.jar com.azavea.rf.batch.Main find_aoi_projects
java -cp rf-batch.jar com.azavea.rf.batch.Main update_aoi_project <UUID>
```
To test Airflow part:
Run this DAG through UI
Be careful with run times, as it generates run_ids basing on the DAG run time, it can cause collisions: …
> AOI Scala airflow jobs implementation

- app-frontend/src/app/components/aoiFilterPane/aoiFilterPane.component.js
- app-frontend/src/app/components/aoiFilterPane/aoiFilterPane.controller.js
- app-frontend/src/app/components/aoiFilterPane/aoiFilterPane.html
- app-frontend/src/app/components/aoiFilterPane/aoiFilterPane.module.js
- app-frontend/src/app/components/statusTag/statusTag.html
- app-frontend/src/app/components/statusTag/statusTag.scss
- app-frontend/src/app/core/services/status.service.js
- app-frontend/src/app/index.components.js
- app-frontend/src/app/index.module.js
- app-frontend/src/app/index.routes.js
- app-frontend/src/app/pages/projects/edit/aoi-approve/aoi-approve.controller.js
- app-frontend/src/app/pages/projects/edit/aoi-approve/aoi-approve.html
- app-frontend/src/app/pages/projects/edit/aoi-approve/aoi-approve.module.js
- app-frontend/src/app/pages/projects/edit/aoi-parameters/aoi-parameters.controller.js
- app-frontend/src/app/pages/projects/edit/aoi-parameters/aoi-parameters.html
- app-frontend/src/app/pages/projects/edit/aoi-parameters/aoi-parameters.module.js
- app-frontend/src/app/pages/projects/edit/browse/browse.html
- app-frontend/src/app/pages/projects/edit/edit.html
- app-frontend/src/app/pages/projects/edit/scenes/scenes.html
- app-frontend/src/assets/styles/sass/_shame.scss
- app-frontend/src/assets/styles/sass/components/_button.scss
This PR adds an initial UI for Area of Interest projects.
The main `projects/{projectid}/edit` page has been adjusted to handle an AOI project (see demo below).
This adds two routes and corresponding templates:
- `projects/edit/{projectid}/aoi-parameters` - houses the page to adjust AOI parameters (filters, frequency, etc.)
- `projects/edit/{projectid}/aoi-approve` - houses the page to approve AOI scenes when an AOI project is set to require manual approval for scene addition
This PR also updates the style of several sidepanels to match new mockups.
Most of the front-end is non-functional.
The …
> Add initial UI for Area of Interest projects

- app-backend/api/src/main/scala/scene/QueryParameters.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/QueryParameters.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Scenes.scala
- docs/swagger/spec.yml
This PR adds a `pending` query parameter to the `project/scenes` endpoint.
It filters against the value of `scenes_to_projects.accepted`.
The filtering for this only kicks in if a `project_id` is also specified (which it is for this endpoint).
* Set `accepted=false` on some `scenes_to_projects` for a certain project.
* Hit the `projects/{uuid}/scenes` endpoint and get a scene count
* Hit  `projects/{uuid}/scenes?pending=false` and `projects/{uuid}/scenes?pending=false`...the number of results from both should add up to the count above
Closes #1740
> Add `pending` boolean query parameter to project scenes endpoint

- app-backend/api/src/main/scala/toolrun/Routes.scala
- app-backend/build.sbt
- app-backend/common/src/main/scala/CommonHandlers.scala
- app-backend/common/src/main/scala/InterpreterExceptionHandler.scala
- app-backend/common/src/main/scala/package.scala
- app-backend/project/Dependencies.scala
- app-backend/project/Version.scala
- app-backend/tile/src/main/scala/LayerCache.scala
- app-backend/tile/src/main/scala/Router.scala
- app-backend/tile/src/main/scala/routes/ToolRoutes.scala
- app-backend/tool/src/main/scala/ast/ClassMap.scala
- app-backend/tool/src/main/scala/ast/MapAlgebraAST.scala
- app-backend/tool/src/main/scala/ast/NodeMetadata.scala
- app-backend/tool/src/main/scala/ast/RFMLRaster.scala
- app-backend/tool/src/main/scala/ast/codec/MapAlgebraOperationCodecs.scala
- app-backend/tool/src/main/scala/ast/codec/MapAlgebraUtilityCodecs.scala
- app-backend/tool/src/main/scala/ast/package.scala
- app-backend/tool/src/main/scala/eval/Interpreter.scala
- app-backend/tool/src/main/scala/params/EvalParams.scala
- app-backend/tool/src/test/scala/Generators.scala
- app-backend/tool/src/test/scala/eval/InterpreterSpec.scala
- app-backend/tool/src/test/scala/eval/LazyTileSpec.scala
- app-backend/tool/src/test/scala/params/EvalParamsSpec.scala
This PR adds the `NodeMetadata` type, which will serve as an (optional) means of specifying preferences vis-a-vis rendering tiles and labelling/describing the semantics of AST nodes.
I ended up running into some difficulties due to the serialization of ASTs and ToolRuns (essentially, they weren't round-tripping without loss and overriding values storied in the database could under certain circumstances lead to loss of data integrity). In response to this, I added some property based testing to ensure the validity of our `Encoder`/`Decoder` pairs.
* Create a Tool and ToolRun in the database. Here are some example POST bodies (note that the `ToolRun` refers to the `Tool` and that the `ToolRun`'s 'sources' block consists of mappings from IDs which specify nodes of the referent AST to a scene …
> Tool Metadata + ToolRun Overrides

- docs/swagger/spec.yml
The swagger spec didn't reflect what the backend was actually doing. That was causing problems for the the python client when it couldn't pass "page" as a query parameter and when it tried to deserialize "project" as a dict instead of a string.
* Compare changes to changes in azavea/raster-foundry-python-client#4
> Update swagger spec

- app-frontend/src/app/components/filterPane/filterPane.controller.js
- app-frontend/src/app/components/filterPane/filterPane.html
- app-frontend/src/app/index.routes.js
Add a scene owner filter to the browse view
Remove old static filter code
Decided that a separate filter section with a multi-button made more sense than a checkbox in the existing datasource filter, since it's a different field that has a different intention behind it 
* Change the owner field of a scene to your user
* Search for the scene using the new filter
* Verify that the filter works as expected
* Verify that the filter is persisted in the URL like all the other filters
Closes #1663
> Add a scene owner filter to the browse view

- app-backend/tool/src/main/scala/ast/MapAlgebraAST.scala
- app-backend/tool/src/main/scala/ast/codec/MapAlgebraOperationCodecs.scala
- app-backend/tool/src/main/scala/ast/package.scala
- app-backend/tool/src/main/scala/eval/Interpreter.scala
- app-backend/tool/src/main/scala/eval/LazyTile.scala
- app-backend/tool/src/test/scala/Generators.scala
- app-backend/tool/src/test/scala/ast/MapAlgebraASTSpec.scala
- app-backend/tool/src/test/scala/eval/LazyTileSpec.scala
ModelLab tools lack Min/Max local operations. This PR adds them.
Run tests in project `tool`
Closes #1618
> Add min/max tool operations

- deployment/ansible/roles/raster-foundry.jenkins/tasks/main.yml
By default, Docker will not remove an image if it is tagged in multiple repositories (which happens when we re-tag images for pushing to ECR).
See: https://github.com/spotify/docker-gc#forcing-deletion-of-images-that-have-multiple-tags
Fixes https://github.com/azavea/operations/issues/34
From the Jenkins machine, build a dummy container image and then tag it with another name:
```bash
ubuntu@ip-172-31-52-80:~$ cat Dockerfile 
FROM python:3
ubuntu@ip-172-31-52-80:~$ docker build -t test .
Sending build context to Docker daemon 783.4 kB
Step 1 : FROM python:3
3: Pulling from library/python
10a267c67f42: Already exists 
fb5937da9414: Already exists 
9021b2326a1e: Pull complete 
dbed9b09434e: Pull complete 
ea8a37f15161: Pull complete 
9fb634154ace: Pull complete 
6df6941e6752: Pull complete …
```
> Force deletion of images that have multiple tags

- app-backend/common/src/main/scala/InterpreterExceptionHandler.scala
200s Were previously returned for interpreter errors. 400s are more appropriate.
Mess up a request that involves the interpretation of some AST and be dazzled by the 400
Closes #1783
> Respond with 400 for interpreter errors

- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Datasources.scala
- app-frontend/src/app/components/projectItem/projectItem.controller.js
- app-frontend/src/app/components/projectItem/projectItem.html
- app-frontend/src/app/core/services/project.service.js
- app-frontend/src/app/pages/projects/edit/advancedcolor/adjust/adjust.controller.js
- app-frontend/src/app/pages/projects/edit/advancedcolor/adjust/adjust.html
Uses thumbnail for project lists instead of using a leaflet map. This should reduce load on the tile server and the problem of cascading errors.
Two other fixes are incorporated as well:
1. Adjust datasource permissions for detail requests so that public datasources can be used
2. Adjust parameters for color correction until we get a handle on the source of problems/issues there
It is not clear if this is going to scale well -- I attempted to test a wide variety of maps -- including a Landsat, Planet, small drone area, and large manned aerial imagery. The heuristic applied in determining the zoom level is based on the …
> Use thumbnails in project list

- app-tasks/requirements.txt
- app-tasks/rf/src/rf/uploads/geotiff/create_footprints.py
- app-tasks/rf/src/rf/uploads/geotiff/create_thumbnails.py
In debugging how a 12 gb upload failed to process I came across the following issues and fixed them:
- switched to `gdal_translate` for all resampling -- it's faster and produces more consistent outputs for deriving polygons from the source image
- resampled down to `512` width for incoming images when generating footprints (still produces good footprints)
- add more logging so we can identify the location of problems more easily
- updates rasterio
- adds `sieve` to footprint generation
This doesn't quite get large ingests working -- the ingest code fails when GeoTrellis tries to read a `BIGTIFF` from S3 right now.
* …
> Various Upload Processing Fixes

- app-frontend/src/app/components/colorCorrectPane/colorCorrectPane.controller.js
- app-frontend/src/app/core/services/layer.service.js
- app-frontend/src/app/pages/projects/edit/advancedcolor/advancedcolor.controller.js
- app-frontend/src/app/pages/projects/edit/colormode/colormode.controller.js
- app-frontend/src/app/pages/projects/edit/edit.controller.js
This PR standardizes how we redraw the mosaic. We had three implementations --
1. in the edit controller
2. in the color mode controller
3. in the advanced color correction controller
Even though all of these had the same task -- redraw the project layer when things change.
Meanwhile, none of them actually worked. The only place the color correction changes were
consistently reflected was on the project detail page, so I stole that implementation, threw it
into the edit controller, and used it everywhere.
This did not fix #1805, and I also discovered another route to the issue in #1805, documented there.
* edit a project with ingested scenes
* change color correction somehow
* get back to the page from some other route. some suggestions:
* refresh
* navigate elsewhere in the app, then …
> Use bulk-update for color mode changes

- app-backend/api/src/main/scala/grid/QueryParameters.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/QueryParameters.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Scenes.scala
- docs/swagger/spec.yml
This PR updates the way the `ingested` scene filter is handled on the backend. Rather than using `ingestLocation`, it now uses the ingest status. When a value of `true` is passed as the `ingested` query parameter, only scenes _with_ a status of `INGESTED` will be returned. If the query parameter is `false` only scenes _without_ a status of `INGESTED` will be retuned.
In addition, I updated the filters for the scene-grid so that they match the scenes endpoint.
* Manually set the `ingestStatus` of a particular scene to `INGESTED`.
* Fire up the front-end and in the scene-browser, set your filter to 'Ingested scenes only' *_or_* use the API and the `ingested=true` query param
* …
> Change `ingested` filters to use`scene.ingestStatus`

- app-backend/batch/src/main/scala/com/azavea/rf/batch/Main.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/export/CommandLine.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/export/airflow/CreateExportDef.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/export/airflow/S3Copy.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/landsat8/airflow/ImportLandsat8.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/sentinel2/airflow/ImportSentinel2.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/util/S3.scala
This PR: 
- Adds s3 copy job
Adds S3Copy job, to copy files between the two S3 buckets.
Modifies S3Export job to allow user defined credentials, to do export directly into user bucket.
```
java -cp rf-batch.jar com.azavea.rf.batch.Main s3_copy s3://sBucket/sPrefix s3://tBucket/tPrefix targetRegion
```
`targetRegion` is an optional field.
The format of credentials is arguable, probably it makes sense to provide it somehow different.
In the export job case it makes sense to make it a part of the `ExportDefinition`.
Closes #1650
> Add support for external S3 export

- app-backend/tile/src/main/scala/LayerCache.scala
- app-backend/tile/src/main/scala/image/Mosaic.scala
- app-backend/tile/src/main/scala/tool/TileSources.scala
- app-backend/tool/src/main/scala/eval/Interpreter.scala
This PR avoids a projection-related issue involving the resolution of global imagery for `Project`s (as opposed to `Scene`s). It also prevents empty (0x0) tiles from being used to generate histograms.
Use a `ToolRun` that specifies a `Project` source. Tiles should be calculated appropriately.
> Add function to get raw tile for extent

- app-backend/api/src/main/scala/tools/Routes.scala
- app-backend/tile/src/main/scala/LayerCache.scala
- app-backend/tile/src/main/scala/image/Mosaic.scala
- app-backend/tile/src/main/scala/tool/TileSources.scala
- app-backend/tool/src/main/scala/ast/MapAlgebraAST.scala
- app-backend/tool/src/main/scala/eval/Interpreter.scala
We need to be able to see which IDs in a tool will require source definitions to carry out a tool run. This PR provides an endpoint which returns that.
> Tool source endpoint

- app-backend/batch/src/main/scala/com/azavea/rf/batch/ingest/CommandLine.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/ingest/spark/Ingest.scala
- app-backend/build.sbt
- app-backend/common/src/main/scala/S3.scala
- app-tasks/dags/ingest_project_scenes.py
- app-tasks/rf/src/rf/ingest/models/ingest.py
- app-tasks/rf/src/rf/utils/io.py
This PR changes status monitoring to look for a file on S3, which is put there in the
batch jar when ingest completes.
* `batch/assembly` from `sbt` -- you're gonna want to do this outside the vm so it takes a minute instead of an hour (not joking)
* upload a small sample scene to kick off the upload / ingest workflow (I can send you one if you need it)
* wait
* after the ingest finishes (takes a few minutes), there should be a file in `s3://rasterfoundry-dataproc-ingest-status-us-east-1/` with your `ingest_id` as the key, and that file's existence should clue airflow in that it can update the scene status
Closes #1746
> Make parallel ingest cooperate

- app-frontend/src/app/components/importModal/importModal.html
This PR adds `*.tiff` to the acceptable file patterns in the upload modal.
* Upload a two-f `tiff`
* Verify that network traffic happens and that airflow starts processing your upload
Closes #1826
> Add tiffs to acceptable file patterns

- app-tasks/rf/src/rf/uploads/geotiff/create_footprints.py
This PR addresses bad arrays coming out of our effort to deal with degenerate geotiffs.
`sieve` was doing what it's supposed to do sort of -- it merged small regions into regions
with their higher-valued neighbors. It didn't care about what the values were though, so
our assertion about geometry values failed.
There may be some `rasterio` magic you can do to accomplish the change below, but it
seems hardly worth it, and updates on `ndarray`s from boolean filters are fast.
* Get some sample tiffs -- ask where those can be found
* Bring up the server and airflow
* Upload them
* Processing the upload shouldn't fail
> Set data value explicitly

- app-frontend/src/app/pages/projects/edit/browse/browse.html
- app-frontend/src/app/pages/projects/edit/edit.html
- app-frontend/src/app/pages/projects/edit/scenes/scenes.html
- app-frontend/src/app/pages/projects/navbar/navbar.html
- app-frontend/src/assets/styles/sass/_shame.scss
- app-frontend/src/assets/styles/sass/app.scss
- app-frontend/src/assets/styles/sass/base/_grid.scss
- app-frontend/src/assets/styles/sass/components/_alert.scss
- app-frontend/src/assets/styles/sass/components/_button.scss
- app-frontend/src/assets/styles/sass/components/_list-group.scss
- app-frontend/src/assets/styles/sass/layout/_navbar.scss
- app-frontend/src/assets/styles/sass/layout/_sidebar.scss
The primary focus for this PR is the main project edit page but not the subsequent edit pages (color mode, etc).
- New alert element
- cleans up the project navbar to more closely mimic vizzuality layout.
- adds some FAQ to the `_shame.scss` for clarity to outside Azavea followers.
- adds a new ghost-button type. Used in the new alert element.
- adds a new `.nogutter` class for columns
- removal of some css that is not being used anywhere.
~### Checklist~
Some pages beyond the edit page have changes. This is due to reworking elements/markup that existed on the edit page and other pages. For example, the scene alert …
> Cleans up main project edit page

- app-frontend/src/app/pages/projects/list/list.controller.js
This PR makes a small fix that introduces a check for an undefined variable being returned from a modal. Very minor. This is an error that shows up in rollbar occasionally.
> Handle possible undefined return from project create modal

- app-frontend/src/app/components/publishModal/publishModal.controller.js
- app-frontend/src/app/components/publishModal/publishModal.html
Copy token instead of object to clipboard
Fix style on the open button
* Copy a map token to your clipboard using the button in the share modal and verify that it doesn't copy an `[Object object]`
Closes #1732
> Fix object copied to clipboard in share modal

- app-backend/batch/src/main/resources/application.conf
- app-backend/batch/src/main/scala/com/azavea/rf/batch/Main.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/landsat8/airflow/ImportLandsat8C1.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/util/conf/Config.scala
New landsat8 md import on Scala.
```scala
java -cp rf-batch.jar com.azavea.rf.batch.Main import_landsat8_c1 YYYY-MM-DD
```
I called it ~~`NewImportLandsat8`~~ `ImportLandsat8C1` ~~, but in the future it makes sense to delete old import and to rename this into `ImportLandsat8`~~. In fact it's a copy paste of the old one with a few changes, makes sense to copy paste in order to allow stress-less migration. 
\+ for old db entries (already ingested / imported scenes) it makes sense to write smth like a migration from old style into a new one (in the future the new collection should have 100% coverage of the old one).
Closes #1586
> C1 Scala Landsat8 import 

- app-frontend/src/app/pages/projects/edit/colormode/colormode.controller.js
- app-frontend/src/app/pages/projects/edit/colormode/colormode.html
- app-frontend/src/app/pages/projects/edit/edit.controller.js
- app-frontend/src/app/pages/projects/edit/edit.html
- app-frontend/src/assets/styles/sass/components/_list-group.scss
This PR updates the styling of the color-mode page to match the rest of the editor. It also fixes a bug that caused the map to load 'new' tiles before changes had been persisted to the DB.
* Try out the color-mode switching and make sure you're getting what you asked for
> Update/fix color-mode selection

- app-tasks/dags/ingest_project_scenes.py
- app-tasks/rf/src/rf/utils/io.py
This commit removes an unnecessary from_string method
that has proven to be error prone. It is not necessary
because the status from the status object is already in
the exact form that we need it.
Trivial - merging
> Remove unecessary from_string method

- deployment/ansible/group_vars/jenkins
Upgrade the version of Terraform used on Jenkins to 0.9.6.
See that http://jenkins.staging.rasterfoundry.com/job/raster-foundry/job/raster-foundry/job/hotfix%252F0.9.1/1/ completed successfully.
> Bump Terraform version on Jenkins to 0.9.6

- nginx/etc/nginx/nginx.conf
Ensure that the connect-src attribute of the content security policy allows HTTPS connections, as well as those directed at the Intercom websocket endpoints. This allows interactive chat to work via the website.
- Start a message thread via the staging website
- Respond via the Intercom web application
- Ensure that the response is visible in the Intercom chat window on the site
Closes https://github.com/azavea/raster-foundry/issues/1864
> Add Intercom websocket endpoints to content security policy

- app-frontend/src/app/core/services/map.service.js
Fix max zoom level on map to 30
I'm not sure why we were able to zoom past zoom level 19 before, since this fixed it.
* Verify that you can zoom past zoom level 19 to zoom level 30
Closes #1856
> Fix max zoom level

- app-frontend/src/app/core/services/colorCorrect.service.js
This PR removes caching from the color-correction GET method in the `colorCorrect.service`. This caching was causing the front-end to hold on to outdated color-corrections.
~[ ] Styleguide updated, if necessary~
~[ ] Swagger specification updated, if necessary~
~[ ] Symlinks from new migrations present or corrected for any new migrations~
*Bug Reproduction:*
- change the color mode of a project, notice the tiles change
- exit the color-mode selection
- go back into color-mode selection
- notice that the tiles are still the same but the color-mode _appears_ to be back to what it was before
To test the fix, do the above and see that the color-mode does not go back to what it was before.
Closes #1869
> Don't cache color-corrections

- app-backend/api/src/main/scala/exports/Routes.scala
- app-backend/api/src/main/scala/exports/package.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/export/airflow/DropboxCopy.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/util/S3.scala
- app-backend/common/src/main/scala/S3.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Exports.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/Export.scala
- docs/swagger/spec.yml
PR Adds API route with a list of signed S3 urls
- PR Adds API route with a list of signed S3 urls
- Modifies listing function behaviour in a Dropbox copy object.
- Adds a part of functions into batch S3 object (preparation to the S3 objects refactor)
The easies way is just to test get signed urls function: 
```scala
scala> val uri = new URI(uriString)
// uri: java.net.URI = s3://bucket/prefix/
scala> S3.getSignedUrls(uri)
// res0: List[java.net.URL] = List(..)
```
Otherwise, export entry should be created in the exports table, after that url can be tested.
Refactor of S3 objects (we have in batch and in commons projects S3 object and more over GeoTrellis S3) probably should be done in a separate project. There is a question, can raster-foundry commons depend on `geotrellis-s3`?
Closes …
> Allow downloading of completed exports

- app-backend/batch/src/main/scala/com/azavea/rf/batch/Job.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/landsat8/airflow/ImportLandsat8.scala
Updates `ImportLandsat8` to use `ImportLandsat8C1` if the request date is > than 30.04.2017
PR allows a soft migration on a new import. Probably we need to consider migration of the old metadata in the future.
Related to #1586
Related to #1750
> Update old ImportLandsat8

- app-frontend/src/app/components/exportModal/exportModal.controller.js
- app-frontend/src/app/core/services/layer.service.js
- app-frontend/src/app/pages/projects/edit/edit.controller.js
Fix tile layer options not being set in project edit controller
* Verify that the frontend tries to load project mosaic tiles at zoom levels up to 30
Closes #1856
> Set max zoom level to 30 instead of leaving undefined

- app-frontend/src/app/components/toggle/toggle.component.js
- app-frontend/src/app/components/toggle/toggle.controller.js
- app-frontend/src/app/components/toggle/toggle.html
- app-frontend/src/app/pages/projects/edit/colormode/colormode.html
This adds a `value` attribute to the toggle component which is is one-way binding. This allows for using toggles when the toggle state is derived from various inputs. If both `model` and `value` attributes are provided, prefer `value`.
When the component is using the two-way binding style, the value of the toggle is changed internally.
This also adjusts the color-mode page to utilize this one-way binding
* Test the color-mode page to ensure it works as expected (aside from any known bugs)
* Test some other spots where we use the `model` attribute and check that the toggle works as expected (the scene browser is always …
> Add one-way binding to toggle

- app-backend/batch/src/main/scala/com/azavea/rf/batch/landsat8/airflow/ImportLandsat8.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/landsat8/airflow/ImportLandsat8C1.scala
This PR fixes thumbnail urls
```bash
java -cp batch/target/scala-2.11/rf-batch.jar com.azavea.rf.batch.Main import_landsat8 2017-05-01
java -cp batch/target/scala-2.11/rf-batch.jar com.azavea.rf.batch.Main import_landsat8_c1 2017-05-01
```
I decided to go through all the significant parts of the import, and doublechecked all urls.
```bash
rasterfoundry=# select url from thumbnails where scene = '0a3c5a42-f307-4252-9da9-9ec7c3f60492';
url
------------------------------------------------------------------------------------------------------------------------------------------------------
http://landsat-pds.s3.amazonaws.com/c1/L8/097/012/LC08_L1TP_097012_20170501_20170515_01_T1/LC08_L1TP_097012_20170501_20170515_01_T1_thumb_large.jpg} …
```
> Fix bad Thumbnail urls in LC8 Imports

- app-frontend/src/app/components/createProjectModal/createProjectModal.controller.js
- app-frontend/src/app/components/publishModal/publishModal.controller.js
- app-frontend/src/app/components/publishModal/publishModal.html
This PR does two things (since they are small):
- redirects the user to the AOI parameters page if the user creates an AOI project.
- shows both ZXY and ArcGIS tile layer urls for copying and removes the button to switch between them
* Create and AOI project and choose to add public imagery, you should be taken to the aoi-parameters page
* Share a project and both the ZXY and ArcGIS tile layer urls should be visible and copyable.
* Switch the share policy and check that the token is removed from the URLs when the project is public.
Closes #1873 
Closes #1891
> Change AOI redirect. Show both tile url formats

- app-frontend/src/app/components/filterPane/filterPane.html
- app-frontend/src/app/pages/projects/edit/advancedcolor/adjust/adjust.html
- app-frontend/src/assets/styles/sass/_shame.scss
This PR makes a slight change to the `sidebar-header` class and adds a `dark` subclass that can be applied to an element: `sidebar-header dark`. This fixes the broken layout on our dark panels.
* Make sure the sidebar headers look right (inlcuding the dark sidebars: filter pane and color-correct adjust page)
Closes #1852
> Fix sidebar headers

- README.md
- app-frontend/src/assets/styles/sass/_shame.scss
- app-frontend/src/assets/styles/sass/app.scss
- app-frontend/src/assets/styles/sass/base/_base.scss
- app-frontend/src/assets/styles/sass/base/_typography.scss
- app-frontend/src/assets/styles/sass/settings/_variables.scss
- app-frontend/src/assets/styles/sass/theme/settings/_variables.scss
- Update the README to walkthrough using the theme files. **Note:** this will need to be updated as we introduce the branding config file.
- Replaces hard decorations of font families with variables which can be changed in the theme file.
~### Checklist~
> adds readme section on theming and font family variables

- app-backend/tile/src/main/scala/Router.scala
- app-backend/tile/src/main/scala/routes/HealthCheckRoute.scala
Add information about the number of threads in the default `ForkJoinPool` underlying `scala.concurrent.ExecutionContext.Implicits.global` to the healthcheck endpoint.
An exemplary response:
```json
{
"service": "tile",
"status": "OK",
"active threads": "10"
}
```
* Go to /tiles/healthcheck
* See the number of currently running threads
Closes #715
> Add thread count on tile healthcheck

- app-backend/api/src/main/scala/project/Routes.scala
- docs/swagger/spec.yml
This PR adds an endpoint at `api/projects/{uuid}/scenes/accept` that will accept all scenes in the `POST`ed body.
* with a project that has multiple scenes, change the DB values to `false` if they aren't already --> `update scenes_to_projects set accepted=FALSE where project_id={uuid}::uuid;`
* `POST` a subset of the scenes to the new endpoint, and check that the scenes are correctly updated
* check that the existing, single-scene endpoint works as it previously has
* check that the swagger doc is correct
Closes #1757
> Add multi-scene accept endpoint

- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Projects.scala
This PR adds a couple AoI field to the `Project` type's DB update handler, so that they will be persisted.
* bounce the API server
* `PUT` to `api/projects/[project id]` with new values in the `aoiCadenceMillis` and `aoiLastChecked` fields
* check that the request ends with a `204` response and that the DB reflects the change in values
Closes #1816
> Update projects AoI fields

- app-frontend/src/app/components/selectedScenesModal/selectedScenesModal.controller.js
- app-frontend/src/app/pages/projects/edit/scenes/scenes.controller.js
This PR fixes the bug that caused the thumbnails of scenes added to a project to remain on the map. The bug was caused by the modal mutating the list of selected scenes before the browse controller has a chance to use that list to remove the thumbnails.
EDIT:
Because it was a tiny fix, I also addressed a bug that caused a deleted scene's footprint to remain on the map.
We should probably make it a rule of thumb to never modify the data a modal is passed via the `resolve` object and instead pass data back to the calling controller with `close` method. This would put the responsibility of mutating the data on the …
> Remove scene list mutation from scene selection modal

- app-backend/common/src/main/scala/Rollbar.scala
- app-frontend/config/webpack/global.js
- app-frontend/src/app/core/services/rollbarWrapper.service.js
- app-frontend/src/tpl-index.html
This PR disables Rollbar and Heap in our development environment.
Our heap data from staging and production use the same environment because our `NODE_ENV`, which is all we have available at the point of build, does not get a proper `staging` value.
We'll want to figure out how to get our Heap app codes into the ENV so that it is configurable.
* Induce a JS error, see that the error is not sent to Rollbar
* Check that no requests are being sent to Heap
* You can alter the value of `DEVELOPMENT` here: https://github.com/azavea/raster-foundry/compare/feature/ak/disable-third-party-services-in-dev?expand=1#diff-38b5978d33 …
> Disable third party services in dev

- app-backend/api/src/test/scala/exports/ExportSpecHelper.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Exports.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/ExportOptions.scala
- docs/swagger/spec.yml
This PR introduces a RAW export param into `ExportOptions`.
* Create an export with this flag.
* Create Export definition out of this Export
More info about testing can be found in this testing issue: https://github.com/azavea/raster-foundry/issues/1874
Closes #1926
> Allow for RAW exports of data

- app-backend/batch/src/main/scala/com/azavea/rf/batch/util/S3.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/util/package.scala
AWS EMR has some specific settings, which should be used as is. 
Export job (and other jobs) overrided some specific settings provided by environment which caused permissions issues (potentially not export job was effected).
Run it on EMR and locally.
Local test command example (should finish successfully): 
```bash
docker-compose -f docker-compose.spark.yml run spark-driver \
--driver-memory 2G \
--class com.azavea.rf.batch.export.spark.Export \
/opt/rf/jars/rf-batch.jar -j s3://rasterfoundry-development-data-us-east-1/export-definitions/f1911a7a-cba5-4c5e-9f15-61b8ca411791.json
```
Closes #1925
> Permission issues during the export job fix

- app-frontend/package.json
Occasionally, CI builds will fail because`node-sass` is missing the linux binding in the `vendor` directory:
```bash
ModuleBuildError: Module build failed: Error: ENOENT: no such file or directory, scandir '/opt/raster-foundry/app-frontend/node_modules/node-sass/vendor'
at Error (native)
at Object.fs.readdirSync (fs.js:951:18)
at Object.getInstalledBinaries (/opt/raster-foundry/app-frontend/node_modules/node-sass/lib/extensions.js:121:13)
at foundBinariesList (/opt/raster-foundry/app-frontend/node_modules/node-sass/lib/errors.js:20:15)
at foundBinaries (/opt/raster-foundry/app-frontend/node_modules/node-sass/lib/errors.js:15:5)
at Object.module.exports.missingBinary (/opt/raster-foundry/app-frontend/node_modules/node-sass/lib/errors.js:45:5)
at module.exports …
```
> Rebuild node-sass after yarn install

- scripts/deploy-docs
When publishing the API spec, ensure that the target path has a trailing slash so that `spec.yml` gets placed at the root of the path vs. the creation of an object named `spec` at the same level of the `spec/` subdirectory.
Fixes https://github.com/azavea/raster-foundry/issues/1955
First, execute `deploy-docs`, which gets invoked by `cipublish`:
```bash
vagrant@vagrant-ubuntu-trusty-64:/opt/raster-foundry$ RF_DEBUG=1 RF_DOCS_BUCKET="rasterfoundry-staging-docs-site-us-east-1" ./scripts/deploy-docs 
++ dirname ./scripts/deploy-docs
+ DIR=./scripts
+ '[' ./scripts/deploy-docs = ./scripts/deploy-docs ']'
+ '[' '' = --help ']'
+ [[ -n rasterfoundry-staging-docs-site-us-east-1 ]]
+ '[' '' = --dryrun ']'
+ echo 'Syncing docs to rasterfoundry-staging-docs-site-us-east-1'
Syncing docs to …
```
> Fix path for API spec publishing

- app-backend/batch/src/main/scala/com/azavea/rf/batch/ingest/CommandLine.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/ingest/spark/Ingest.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Exports.scala
PR adds logic to get inputs partitions number basing on its size.
Tested on a local RF instance, on jobs launched via airflow on EMR. 
P.S. On a prod / dev systems [this](https://github.com/azavea/raster-foundry/blob/develop/app-tasks/dags/ingest_project_scenes.py#L45) line should be renamed as well.
Closes #1880
> Adjust Ingest Parallelism on Data Size

- app-tasks/dags/ingest_project_scenes.py
This commit adds a timeout to set an upper bound for how long an
ingest can run before it fails. This will help prevent large, failed
ingests from blocking other processes from running.
Generally, ingests should not be taking longer than an hour. The longest task is "wait for status" which is waiting for a job to complete while it's running in EMR. So looking at this graph I think 60 minutes gives us quite a bit of overhead (maybe too much).
* Spin up locally, verify that ingesting a landsat scene in a project still works
> Add dag run timeout to ingest scenes

- README.md
- app-frontend/.gitignore
- app-frontend/config/webpack/environments/development.js
- app-frontend/config/webpack/global.js
- app-frontend/config/webpack/overrides.js.template
- app-frontend/package.json
- app-frontend/src/app/core/services/map.service.js
- app-frontend/webpack.config.js
- app-frontend/yarn.lock
Allow use of an optional overrides.js webpack configuration file which is ignored by git
Replace use of _.merge with more intelligent merging
* Copy `app-frontend/config/webpack/overrides.js.template` into `app-frontend/config/webpackoverrides.js`
* To test overriding, replace the default basemap property in the file and start the file (webpack must be restarted to see changes
Closes https://github.com/azavea/raster-foundry/issues/1885
> Add overrides.js.template for overriding select webpack global vars

- app-backend/common/src/main/scala/cache/HeapBackedMemcachedClient.scala
- app-backend/tile/src/main/scala/LayerCache.scala
- app-backend/tile/src/main/scala/Router.scala
- app-backend/tile/src/main/scala/image/GlobalSummary.scala
- app-backend/tile/src/main/scala/image/Mosaic.scala
- app-backend/tile/src/main/scala/routes/ToolRoutes.scala
- app-backend/tile/src/main/scala/tool/TileSources.scala
Initially, it appeared as though non-landsat imagery was not appearing on tool endpoints. Further investigation indicated that this was a red herring: the small test cases being used to test non-landsat behavior were being retrieved from S3 without trouble, they just failed to be associated with accurate histograms. The problem with histogram generation was related to the fact that, prior to this PR, they were generated from the least resolution zoom level available - a zoom level which, for small datasets, might collapse the entire raster to a single pixel.
This PR sophisticates the search for the appropriate zoom level by iterating up in zoom levels until one which has enough cells is found. 
~- …
> Correctly produce histograms for small projects

- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/ColorCorrect.scala
- app-backend/tile/src/main/scala/tool/TileSources.scala
- app-backend/tool/src/main/scala/eval/LazyTile.scala
@fosskers pointed out that we were using the `bands` function along with an indexed call into the `Vector` it generates rather than `band`, which should just grab the band immediately from the underlying array. This is a free performance improvement.
> Use tile.band function

- app-tasks/usr/local/airflow/airflow.cfg
- docker-compose.airflow.yml
All of the changes to `docker-compose.airflow.yml` pertain only to the development environment. They are mainly aimed at keeping proportions closer to what they are in the default Airflow configuration.
Changes directly to the Airflow configuration file are to better align with the Airflow defaults based on the version we are currently running. The only one that should have a direct impact to AWS environments is `max_threads` for the scheduler. All other changes to resolve this issue were made via configuration settings that get passed through the environment.
Closes #1760 
Navigate to the Flower UI for staging and production. Click through one of the workers and note the **Max concurrency** value. It should be **2**:
- https://flower.staging.rasterfoundry.com/
- …
> Increase Airflow parallelism

- app-frontend/src/app/pages/settings/connections/connections.controller.js
This change omits the trailing port number in the Dropbox authorization workflow `redirect_uri` when served over HTTPS.
Fixes https://github.com/azavea/raster-foundry/issues/1993
I built the static bundle and Nginx container image locally, then pushed it to ECR using the tag that's currently deployed. After cycling the API task instance, the new image went live.
You should not be able to connect Dropbox by navigating to https://app.staging.rasterfoundry.com/settings/connections and completing the authorization workflow.
> Omit port from Dropbox OAuth redirect URL

- Vagrantfile
- deployment/ansible/group_vars/all
- deployment/ansible/raster-foundry.yml
- deployment/ansible/roles.yml
- deployment/ansible/roles/raster-foundry.docker/defaults/main.yml
- deployment/vagrant/ansible_galaxy_helper.rb
This PR installs the necessary resources to follow the new installation instructions for `docker v17`.
Changes:
- Bump Version to `v17`.
- Bump `azavea.docker` version to `4.0.0` (not released yet)
- This requires the addition of the `azavea.python-security` role, which installs python modules necessary to allow Ansible to interact with servers that use have SNI enabled. 
- Bump `docker-compose` version to `1.13.*`.
- Remove the old `docker-py` module, which causes errors when installed alongside `docker-compose`. See docker/docker-py#1395
- Update Ansible to `2.3.1`, and add a check to ensure that the right version is installed.
- Modify `ansible_galaxy_helper.rb` to use the Ansible rolespec `name` attribute if it's available when installing roles. I initially did this for convenience …
> Install Docker v17

- app-frontend/src/app/components/tools/toolItem/toolItem.html
- app-frontend/src/app/components/tools/toolSearch/toolSearch.html
- app-frontend/src/app/pages/market/market.html
- app-frontend/src/app/pages/market/search/search.html
- app-frontend/src/assets/styles/sass/base/_grid.scss
- app-frontend/src/assets/styles/sass/components/_form.scss
- app-frontend/src/assets/styles/sass/components/_image.scss
- app-frontend/src/assets/styles/sass/components/_instructions.scss
- app-frontend/src/assets/styles/sass/components/_modal.scss
- app-frontend/src/assets/styles/sass/components/_pagination.scss
- app-frontend/src/assets/styles/sass/components/_panel.scss
- app-frontend/src/assets/styles/sass/components/_slider.scss
- app-frontend/src/assets/styles/sass/components/_tooltip.scss
- app-frontend/src/assets/styles/sass/layout/_aside.scss
- app-frontend/src/assets/styles/sass/layout/_container.scss
- app-frontend/src/assets/styles/sass/layout/_navbar.scss
- app-frontend/src/assets/styles/sass/pages/_dashboard.scss
The main reason for the PR is to cleanup the tools page. In doing so, I purposefully removed some functionality and also added some placeholder content in order to support an upcoming demo. 
The second reason for this PR is to fix a spelling error on all `border-radius` specifications in the scss. 
**Misc changes:**
- adds new css flavored checkboxes.
- fixes ie11 flex layout issue
I removed the click event that goes to tool details page and added the execute button to the tool itself within the list view. This is a temporary change. The tool detail page remains unstyled and isn't ready to be viewed in demos.
The placeholder content I mentioned are the tags that are visible in the filters.
* go to tools page in navbar.
Closes #1294
> updates tools page, fixes border-radius issue

- app-backend/batch/src/main/resources/application.conf
Uses `https` for base landsat URLs
Note the thumbnail URLs for the most recent imported versions are SSL
* Rebuild batch jar
* Load airflow worker in shell: `./scripts/console airflow-worker bash`
* Load Landsat 8 data for a day: `java -cp /opt/raster-foundry/jars/rf-batch.jar com.azavea.rf.batch.Main import_landsat8 2017-06-13`
* Verify new Landsat 8 thumbnails use `https` in UI after starting scripts server
Closes #1975
> Use https for base of landsat URLs

- docker-compose.yml
- nginx/Dockerfile.airflow
- nginx/Dockerfile.api
- nginx/Dockerfile.tiler
- nginx/etc/nginx/conf.d/airflow.conf
- nginx/etc/nginx/conf.d/api.conf
- nginx/etc/nginx/conf.d/tiler.conf
The Nginx container image comes with a default virtual host configuration at `/etc/nginx/conf.d/default.conf`. Ensure that we overwrite it with our virtual host configuration so that there aren't any unexpected conflicts between them.
Also, in scenarios where we know that we want a set of virtual hosts per Nginx instance, ensure that we set the `default_server` for each port combination. This will cause Nginx to raise an error in the even that multiple virtual hosts define that they are the default within a single instance's configuration.
Within your VM, rebuild the Nginx container images with `bootstrap` and ensure that `server` works:
```bash
vagrant@vagrant-ubuntu-trusty-64:/opt/raster-foundry$ ./scripts/bootstrap
vagrant@vagrant-ubuntu-trusty-64:/opt/raster-foundry$ ./scripts/server …
```
> Fix Nginx HTTP virtual host collision

- app-frontend/src/app/components/projects/projectItem/projectItem.component.js
- app-frontend/src/app/components/projects/projectItem/projectItem.html
- app-frontend/src/app/components/projects/projectSelectModal/projectSelectModal.html
- app-frontend/src/assets/styles/sass/_shame.scss
This PR adds an attribute to the `projectItem` component, `slim`. When slim is set to true, the project item is displayed in a way that is more suitable for use in a list. This PR also utilizes this attribute to improve the display of the projects in the lab project selection modal.
* Open a tool in the lab and test the source selection
> Add compressed project-item

- app-backend/tool/src/main/scala/eval/Interpreter.scala
- app-backend/tool/src/main/scala/eval/InterpreterError.scala
- app-backend/tool/src/test/scala/eval/InterpreterSpec.scala
This builds on #1728 by separating pure and non-pure code in the original interpreters. They should be easier to reason about this way.
> Safer interpreters

- app-tasks/Dockerfile
Make use of the `testing` Debian repository to gain access to newer version of the `gdal-bin` package (and its associated dependencies).
Fixes #1930 
After pulling down this branch, execute the following command to create a new version of the Airflow container image:
```bash
vagrant@vagrant-ubuntu-trusty-64:/opt/raster-foundry$ GIT_COMMIT="latest" docker-compose \
-f docker-compose.yml \
-f docker-compose.airflow.yml \
-f docker-compose.test.yml \
build airflow
```
From there, download a TIF that is known to break GDAL < 2.1 into the root of the project directory and launch an instance of the container image. Once inside, execute the `gdalwarp` command that was previously failing:
```bash
airflow@273b8f34addc:/usr/local/airflow$ gdalwarp --version
GDAL 2.1.2, released 2016/10/24 …
```
> Install GDAL 2.1 in Airflow worker container image

- app-frontend/config/webpack/global.js
Fixes issue where aerial tiles do not load because of CSP problems because the scheme was http
> Use HTTPs for aerial map tiles

- app-tasks/rf/src/rf/uploads/geotiff/create_footprints.py
This PR adds an assertion that should catch a bad shape extraction when generating footprints. This also fixes the unsafe use of a generator which assumed a successful operation.
The rasterio `shapes` generator generates nothing when it cannot successfully extract shapes.  The use of `shapes(...).next()` without catching the possible `StopIteration` exception caused the exception to bubble up to a containing generator, which handles the exception as if it had been raised intentionally. As a result, the airflow task would 'succeed' even in the case of a bad tif.
We probably should not use `next()` like that.
* Ask me …
> Check for bad shape extraction

- app-frontend/config/webpack/environments/production.js
- app-frontend/config/webpack/global.js
The manifest plugin has been the cause for our web-pack crashes numerous times now, specifically whenever we make changes to files that have no changes. It's not something we should need in development. This PR moves the plugin to run on prod only.
* Run the web-pack server locally
* Make sure it starts up
* Save some unchanged files, be sure the server remains running
* Run `./scripts/cibuild` and ensure that it can be run successfully
> Move webpack manifest plugin to prod only

- app-backend/tool/src/main/scala/ast/MapAlgebraAST.scala
- app-backend/tool/src/main/scala/ast/codec/MapAlgebraCodec.scala
- app-backend/tool/src/main/scala/ast/codec/MapAlgebraLeafCodecs.scala
- app-backend/tool/src/main/scala/eval/Interpreter.scala
- app-backend/tool/src/main/scala/eval/LazyTile.scala
- app-backend/tool/src/test/scala/Generators.scala
- app-backend/tool/src/test/scala/eval/InterpreterSpec.scala
Many calculations require specification of constant values to serve as coefficients. Accomplishing this requires the implementation of "tiles" which return a single value regardless of `col` and `row`. `MapAlgebraAST.Constant` in this PR provides this behavior
The issue for this task mentions the need to update these `Constant` values from `ToolRun`s (rather than just tools). This requirement is not being ignored: it is general enough that we're implementing it in such a way that it will handle this and other similar cases
* Run the tests
Closes #2008
> Add Constant LazyTile

- app-backend/batch/src/main/scala/com/azavea/rf/batch/ast/package.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/export/spark/Export.scala
- app-backend/tile/src/main/scala/LayerCache.scala
- app-backend/tile/src/main/scala/routes/ToolRoutes.scala
- app-backend/tool/src/main/scala/ast/codec/MapAlgebraCodec.scala
- app-backend/tool/src/main/scala/eval/Interpreter.scala
- app-backend/tool/src/main/scala/eval/InterpreterError.scala
- app-backend/tool/src/main/scala/params/EvalParams.scala
- app-backend/tool/src/test/scala/eval/InterpreterSpec.scala
- app-backend/tool/src/test/scala/params/EvalParamsSpec.scala
This PR lays the ground work for being able to replace at "run time" the "extra params" of AST `Operation` nodes that have any (like the `breaks` field in `Classification`).
The newly extended form of `EvalParams`, which are embedded in `ToolRun`. Nothing about `ToolRun` itself had to change in this PR.
```json
{
"sources" : {
"ae3d5e1b-6333-4b2c-a365-f58b62ca1b16" : {
"id" : "cd9840de-8806-4dc3-ac78-c9072edf5a02",
"band" : 5,
"type" : "scene"
},
"a4d64cc5-e3d0-48ac-91ea-5f545fa85ac7" : {
"id" : "bce1b792-8bb0-4bf1-92a9-ffcf95506201",
"band" : 5,
"type" : "scene"
},
"e5a58572-4a50-440d-9084-a38e1d2914b1" : {
"id" : "9e0ae12f-5ff0-46e4-b67c-c57b087ab9f4",
"band" : 5,
"type" : "scene"
}
},
"metadata" : {
},
"overrides" : {
"ae3d5e1b-6333-4b2c-a365-f58b62ca1b16" : {
"constant" : 5.0
}, …
```
> AST: Overrides for "extra params"

- app-backend/tile/src/main/scala/LayerCache.scala
- app-backend/tool/src/main/scala/ast/ClassMap.scala
- app-backend/tool/src/main/scala/ast/NodeMetadata.scala
- app-backend/tool/src/test/scala/Generators.scala
- app-backend/tool/src/test/scala/eval/InterpreterSpec.scala
- docs/mapalgebra/colors.md
I added some documentation on the rendering options available when specifying `Tool`s and `ToolRun`s. In the process of actually using these features, it became apparent that in addition to `ColorMap` and `ColorRamp` specification, users would be interested in being able to manually specify only the breaks (leaving the actual selection of colors to the `ColorRamp` + interpolation). Therefore, this PR also implements support for `ColorBreaks` on `NodeMetadata`.
Closes #2016
> Document tool rendering options

- app-tasks/dags/aoi-monitoring/find_aoi_projects_to_update.py
- app-tasks/dags/aoi-monitoring/update_aoi_projects.py
- app-tasks/dags/export_project.py
- app-tasks/dags/import_landsat8_scenes.py
- app-tasks/dags/import_sentinel2_scenes.py
- app-tasks/dags/ingest_project_scenes.py
- app-tasks/dags/process_upload.py
- app-tasks/dags/utils.py
There are a few issues with our Airflow logging that this PR starts to solve:
1. Not every log making it to stdout
2. Lack of contextual/user information in logs when tracking down failures
3. Notifications to Rollbar for failed task instances
The first problem is actually a little tough to solve in an elegant way because Airflow uses the root logger everywhere, so the only solution is to add another handler (stream handler) to the root logger and deal with all the logs now.
The second problem is solved by updating the logs to include additional context, including upload ids, scene ids, and user ids where relevant.
The third problem is solved by adding a failure callback that sends a notification to rollbar in the event of a failed task instance so that an issue can be created and …
> Improve Airflow DAG/Task Logging

- app-frontend/package.json
- app-frontend/yarn.lock
Fix refresh tokens defaulting name to "Browser"
Api was changed and broke the old version of auth0 lock
* Verify that you can now name refresh tokens correctly
* Verify that logging in / password reset etc still work
Closes https://github.com/azavea/raster-foundry/issues/1745
> Fix auth0 issues by upgrading lock library

- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/ColorCorrect.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/WhiteBalance.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/color/functions/Approximations.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/color/functions/SaturationAdjust.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/color/functions/SigmoidalContrast.scala
- app-backend/datamodel/src/test/scala/com/azavea/rf/datamodel/color/functions/ApproximationsSpec.scala
- docker-compose.yml
This PR introduces multiple changes into the tile ColorCorrection function. 
The problem is that ColorCorrection function computation takes 190ms - 360+ms
To resolve this issue were researched two approaches: 
1. through LazyTiles 
2. through reducing cfor loops operations number (every per pixel operation can be done in one loop), reducing `Option` boxing
The first approach didn't work, and / or requires much deeper research, as requires implementation of multiband lazy tiles, as a consequences it was decided to follow through the second approach, as it is more straightforward.
After following the second a problems with slow floating point operations was figured out, standard `math.pow` and `math.exp` are two extremely slow functions. The workaround was to use `commons-math3` library, …
> ColorCorrection improvements

- app-backend/batch/src/main/resources/application.conf
- app-backend/batch/src/main/scala/com/azavea/rf/batch/ingest/spark/Ingest.scala
- app-backend/project/Version.scala
- app-tasks/dags/ingest_project_scenes.py
PR adds an additional buffer (2px sized) around chips, to get rid of seams which could appear during the ingest process.
Includes GeoTrellis update up to 1.1.1.
* Run ingest through the UI
Closes #1735
> Ingest seams fix

- app-backend/batch/src/main/scala/com/azavea/rf/batch/ast/package.scala
- app-backend/batch/src/test/scala/com/azavea/rf/batch/export/model/ExportDefinitionSpec.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Exports.scala
- app-backend/tile/src/main/scala/tool/TileSources.scala
- app-backend/tool/src/main/scala/eval/Interpreter.scala
- app-backend/tool/src/main/scala/params/RFMLRaster.scala
- app-backend/tool/src/test/scala/Generators.scala
- app-backend/tool/src/test/scala/MockInterpreterResources.scala
- app-backend/tool/src/test/scala/eval/InterpreterSpec.scala
We've been seeing nasty (usually purple) boundaries around tiles produced by Model Lab for some time - the culprit is apparently incorrectly specified metadata pertaining to the `NoData` value. The fix (which we already have) is to properly ingest tiles with a manually configured `OutputDefinition` bearing the appropriate `NoData` specification.
That's probably not good enough. Ingesting things can take a long time and people are bound to mess this up which means that we need to offer an escape hatch for such errors. This PR introduced the machinery necessary to interpret any source (`Project` or `Scene`) with the `NoData` value of a user's choosing. Default geotrellis serialization (`toName` and `fromName` are used in the codecs.
~- [ ] Swagger …
> Add nodata specification to ToolRun sources

- app-frontend/src/app/pages/projects/edit/color/color.controller.js
- app-frontend/src/app/pages/projects/edit/color/color.html
- app-frontend/yarn.lock
Enable front end color auto correction.  Turning on "Auto Contrast" will enable "equalize" option of color correction.  Turning on "Auto Color" will enable "autoBalance" option of color correction.
* On the "Editing Project" page
* Click "Correction" button
* Click on checkboxes to select autocorrection types.
* See the imagery changes on the map.
Closes #1889
> Enable front end color auto correction.

- .gitignore
- Vagrantfile
- app-backend/api/Dockerfile
- app-backend/api/src/main/resources/application.conf
- app-backend/api/src/main/scala/Main.scala
- app-backend/api/src/main/scala/grid/Routes.scala
- app-backend/api/src/main/scala/project/Routes.scala
- app-backend/api/src/main/scala/scene/Routes.scala
- app-backend/api/src/main/scala/thumbnail/Routes.scala
- app-backend/api/src/main/scala/tools/Routes.scala
- app-backend/build.sbt
- app-backend/project/Dependencies.scala
- app-backend/project/Version.scala
- app-backend/project/plugins.sbt
- app-backend/tile/Dockerfile
- app-backend/tile/src/main/resources/application.conf
- app-backend/tile/src/main/scala/Main.scala
- app-backend/tile/src/main/scala/routes/MosaicRoutes.scala
- app-backend/tile/src/main/scala/routes/ToolRoutes.scala
- app-tasks/.gitignore
- docker-compose.metrics.yml
- docker-compose.yml
- scripts/server
- statsd/var/lib/statsd/config.js
Adds metric tracking to various API and tile endpoints. Also adds
statsite, graphite, grafana for development purposes to track metrics
and compare results over time.
Some things to fix up before merging and giving this a full review:
- Ensure open up correct ports in Vagrant
- Figure out how to persist development dashboards
- Figure out how to filter out unwanted metrics/be more judicious
Start servers with `./scripts/server --with-metrics`
Open up `localhost:3000` and configure grafana
Make some requests and start testing out grafana and add a dashboard
This was to evaluate Kamon - either we can edit this and make …
> [WIP] Add Kamon metrics tracking

- app-frontend/src/app/pages/projects/detail/scenes/scenes.controller.js
This PR serves as a quick fix to make scene removal from a project from the project details page.
* Make sure you can delete a scene from a project from the scene details page.
Closes #2179
> Fix scene removal from project on project details page

- app-frontend/src/app/core/services/datasource.service.js
- app-frontend/src/app/pages/imports/datasources/detail/detail.controller.js
- app-frontend/src/app/pages/imports/datasources/detail/detail.html
Enable changing datasource visibility on datasource detail page via a checkbox. Default datasources will not have such option exposed though.
The style of the visibility section may need further edits.
* Go to the "Imports" and click "Browse Datasources" button 
* View a default datasource: on its detail page, the visibility section should not show.
* View your own datasource (if none, create one): on its detail page, the visibility section should show.
* Change datasource visibility
* Check XHR if a put request is sent with changed visibility, OR go back and view this page again, OR refresh this page - to see if the …
> Enable changing datasource visibility on datasource detail page

- app-frontend/src/app/core/services/auth.service.js
- app-frontend/src/app/pages/login/login.controller.js
This PR adds handling for Auth0 user impersonation.
Rather than using a redirect route, this handles the impersonation request from the `login` route.
Some combination of Auth0 and angular result in the auth params being sent in as a single hash string rather than query params. This required some manual splitting of the params.
This opens up the possibility of someone setting an invalid `id_token` in the hash string. Try/catches have been added to prevent bad JWT formats from causing errors. Instead, a poorly formatted JWT will now redirect to login.
* Make sure you can login and out normally
* Go into Auth0 and set …
> Allow Auth0 user impersonation

- app-backend/build.sbt
Our tiler tests require the database to be available in order to run, but we
don't want to have that requirement during JAR assembly. This prevents
tests from running during the assembly task, which makes the database no
longer necessary.
* From `develop`, run the command from #1915 (including `--no-deps`). It should run `AuthSpec` tests which will fail because no database is available.
* Check out this branch and re-run the command. Tests from `com.azavea.rf.tile.AuthSpec` should no longer be run and the command should succeed even when the `--no-deps` parameter is included.
Closes #1915
> Disable running tests during assembly

- app-backend/api/src/main/scala/exports/Routes.scala
- app-backend/api/src/main/scala/exports/package.scala
- app-backend/common/src/main/scala/S3.scala
- app-frontend/src/app/components/exports/exportDownloadModal/exportDownloadModal.html
- app-frontend/src/app/core/services/export.service.js
- docs/swagger/spec.yml
- nginx/etc/nginx/conf.d/api.conf
This PR adds redirection and throttling for downloading the imagery resulting from exports. It addresses three areas:
- API server: added endpoint and handling for redirecting an export download to an S3 signed URL via a 302
- Front-end: adjusted the export service and download modal to handle the new scheme for getting the files of an export as well as query param authentication
- NGINX - added rate limiting to the api-server's conf file
The throttle rate is ridiculous right now (1 req/min) and I'll adjust it before we merge once we decide on a reasonable value.
I think the throttling is going to apply across files, so trying to download 2 different files within a …
> Add redirection and throttling for downloads

- app-backend/batch/src/main/scala/com/azavea/rf/batch/ast/package.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/ingest/model/OutputDefinition.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/ingest/model/SourceDefinition.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/ingest/model/package.scala
- app-backend/bridge/build.sbt
- app-backend/bridge/src/main/scala/com/azavea/rf/package.scala
- app-backend/build.sbt
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/AOI.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/ExportOptions.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/InputDefinition.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/OutputDefinition.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/Project.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/Scene.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/package.scala
- app-backend/tile/src/main/scala/LayerCache.scala
- app-backend/tile/src/main/scala/tool/TileSources.scala
- app-backend/tool/src/main/scala/ast/MapAlgebraAST.scala
- app-backend/tool/src/main/scala/ast/codec/MapAlgebraOperationCodecs.scala
- app-backend/tool/src/main/scala/eval/Interpreter.scala
- app-backend/tool/src/main/scala/eval/InterpreterError.scala
- app-backend/tool/src/main/scala/eval/LazyTile.scala
- app-backend/tool/src/main/scala/params/EvalParams.scala
- app-backend/tool/src/test/scala/Generators.scala
- app-backend/tool/src/test/scala/MockInterpreterResources.scala
- app-backend/tool/src/test/scala/ast/MapAlgebraASTSpec.scala
- app-backend/tool/src/test/scala/ast/codec/MapAlgebraASTCodecSpec.scala
- app-backend/tool/src/test/scala/eval/InterpreterSpec.scala
- app-backend/tool/src/test/scala/params/EvalParamsSpec.scala
This PR implements the `Masking` operation in both the Tile server and in AST Exports.
This introduces a new subpackage called `bridge`. It is a common location for orphaned typeclass instances for GeoTrellis types to live, which helps avoid a circular dependency in this PR.
Closes #2050
> AST: Masking

- app-frontend/config/webpack/global.js
- app-frontend/config/webpack/overrides.js.template
- app-frontend/src/app/core/services/aoi.service.js
- app-frontend/src/app/core/services/auth.service.js
- app-frontend/src/app/core/services/colorCorrect.service.js
- app-frontend/src/app/core/services/datasource.service.js
- app-frontend/src/app/core/services/dropbox.service.js
- app-frontend/src/app/core/services/export.service.js
- app-frontend/src/app/core/services/featureFlags.provider.js
- app-frontend/src/app/core/services/feed.service.js
- app-frontend/src/app/core/services/gridLayer.service.js
- app-frontend/src/app/core/services/organization.service.js
- app-frontend/src/app/core/services/project.service.js
- app-frontend/src/app/core/services/scene.service.js
- app-frontend/src/app/core/services/token.service.js
- app-frontend/src/app/core/services/tool.service.js
- app-frontend/src/app/core/services/toolCategory.service.js
- app-frontend/src/app/core/services/toolTag.service.js
- app-frontend/src/app/core/services/upload.service.js
- app-frontend/src/app/index.bootstrap.js
- app-tasks/dags/ingest_project_scenes.py
Still prevents accidentally kicking off the same ingest multiple times
- Start servers with airflow
- Open psql shell: `./scripts/psql`
- Set ingest status to failed for scene:
`UPDATE scenes SET ingest_status = 'FAILED' WHERE id = '57e69503-61e1-4d8a-8dd6-eef465fd502e';`
- Kick off ingest for scene by posting the following json to `http://localhost:8080/api/dag-runs/ingest_scene`:
`{'sceneId': '57e69503-61e1-4d8a-8dd6-eef465fd502e'}`
- Observe that job proceeds as normal
- cp `app-frontend/config/webpack/overrides.js.template` to `app-frontend/config/webpack/overrides.js`
- open up `localhost:9091` and open developer …
> Minor Fixes/Frontend Customization for API Server

- app-backend/batch/src/main/scala/com/azavea/rf/batch/ast/package.scala
- app-backend/tool/src/main/scala/eval/Interpreter.scala
- app-backend/tool/src/main/scala/eval/InterpreterError.scala
- app-backend/tool/src/test/scala/eval/InterpreterSpec.scala
See #2119 .
New AST conditions:
- A full AST must have at least one `Source` leaf
- Subtrees *can* have only `Constant`s as their leaves, unless they are `Unary` operations like `Classification` or `Masking`
Visually:
**Illegal**
**Legal**
**Legal**
**Illegal**
> Account for `Constant` tiles in Export AST evaluation

- app-frontend/src/app/pages/projects/edit/edit.controller.js
This PR addresses a possible undefined project situation on the project edit page. This is an async bug that was caused by referencing `this.project` within the controller without a guarantee that it was defined. The results were that some projects would seemingly not have color-modes defined.
* Go to the project edit page for a project
* Clear cache and hard reload and see that there are no errors and that all color-modes defined for the relevant datasources are shown.
Closes #2117
> Fix possible undefined project state

- app-frontend/src/app/core/services/auth.service.js
This PR pulls impersonation info into Heap if it is available.
It works but it seems to only fully show in heap after log-out.
* This can be confirmed by removing the `if` around the heap script in `tpl-index.html` and then impersonating a user and then logging out.
Closes #2203
> Add impersonation info to Heap

- app-backend/tile/src/main/scala/LayerCache.scala
It is more a workaround rather than a full solution, as a full solution probably should take in account what zoom level do we want to query thumbnails.
The problem happened due to huge thumbnail size (sometimes col x row result was more than 536832).
Closes #1808
> Fix thumbnails caching blow up

- app-frontend/src/app/components/tools/diagramContainer2/diagramContainer.controller.js
- app-frontend/src/app/components/tools/diagramNodeHeader/diagramNodeHeader.component.js
- app-frontend/src/app/components/tools/diagramNodeHeader/diagramNodeHeader.controller.js
- app-frontend/src/app/components/tools/diagramNodeHeader/diagramNodeHeader.html
- app-frontend/src/app/components/tools/diagramNodeHeader/diagramNodeHeader.module.js
- app-frontend/src/app/index.components.js
- app-frontend/src/assets/styles/sass/_shame.scss
- app-frontend/src/assets/styles/sass/settings/_colors.scss
Add a node header component for use in tool runs
At this point, we should have feature parity with  the original tool runs.
The warning icon is currently hardcoded to show on all input nodes, since the body component for them is not implemented yet.
I created `setHeight()` preemptively so when we need to use it, we can. It doesn't cause the graph to re-flow in response.
* Verify that you can drag the nodes by the title bar, but not the body
* Verify that the dropdown menu & all options work as expected
Closes #2157
> Add Node header component

- app-frontend/src/app/core/services/project.service.js
- app-frontend/src/app/pages/projects/edit/export/export.controller.js
- app-frontend/src/app/pages/projects/edit/export/export.html
There are now 3 options for exports: Download, S3 (requires path), and Dropbox
* Verify that the 3 options send the correct payload: type and source should correspond to the selection.
Closes #2176
> Remove extra export options

- app-backend/database/src/main/scala/com/azavea/rf/database/Database.scala
Using the contents of `HikariCPJdbcDataSource` as a starting point, extract what seem like the most important settings, and apply them to our database configuration.
The constant 5 multiplied to slickThreadCount for Hikari pool size mimics the formula used inside of `HikariCPJdbcDataSource`.
Compare settings in this branch against those in [HikariCPJdbcDataSource.scala](https://github.com/slick/slick/blob/3.1.1/slick-hikaricp/src/main/scala/slick/jdbc/hikaricp/HikariCPJdbcDataSource.scala). Also, ensure that `server` still works as expected locally.
> Tune Slick/Hikari database configuration

- app-backend/batch/src/main/scala/com/azavea/rf/batch/ingest/model/SourceDefinition.scala
- app-backend/batch/src/test/scala/com/azavea/rf/batch/ingest/model/IngestDefinitionSpec.scala
- app-tasks/Dockerfile
- app-tasks/rf/src/rf/ingest/geotiff_ingest.py
- app-tasks/rf/src/rf/ingest/landsat8_ingest.py
- app-tasks/rf/src/rf/ingest/models/source.py
- app-tasks/rf/src/rf/uploads/geotiff/factories.py
- app-tasks/rf/src/rf/uploads/geotiff/utils.py
This PR adds support for splitting tifs larger than 1GB. Files are split into
12,000 x 12,000 tiles using the `gdal_retile.py` command. These smaller tifs are
still associated with a single scene.
In the process of doing this sources in the ingest definition now exclude extents,
instead the ingest process now relies on reading tiff tags to get the extent of
incoming files.
Had to update the airflow container dockerfile to install gdal from the `sid` package repositories in order to get the most up to date version of gdal that allowed specifying overlap in the generated tiles.
- Rebuild airflow container …
> Split large uploaded Tif Files

- app-frontend/config/webpack/global.js
Change default basemap to light/positron
* Ctrl-C from yarn
* yarn dev
* Go to a project or create a new one
* Check if the basemap is in light/positron mode
Closes #2174
> Change default basemap to light/positron

- app-frontend/src/app/components/projects/projectItem/projectItem.html
This PR made changes on project list page.  Buttons are "View" instead of "Edit" now. Clicking on project thumbnails will go to project edit page.
* Go to the project list page
* Check if the buttons say "View", and will direct to project edit page
* Click on thumbnails (no scene projects, uningested scene project, or ingested scene project), check if it goes to project edit page
Closes #2251
> Change edit to view on project list and link thumbnails to edit page

- app-frontend/config/webpack/global.js
- app-frontend/src/app/components/map/mapContainer/mapContainer.controller.js
- app-frontend/src/app/components/map/mapContainer/mapContainer.html
- app-frontend/src/app/components/map/mapSearchModal/mapSearchModal.component.js
- app-frontend/src/app/components/map/mapSearchModal/mapSearchModal.controller.js
- app-frontend/src/app/components/map/mapSearchModal/mapSearchModal.html
- app-frontend/src/app/components/map/mapSearchModal/mapSearchModal.module.js
- app-frontend/src/app/core/core.module.js
- app-frontend/src/app/core/services/geocode.service.js
- app-frontend/src/app/index.components.js
- app-frontend/src/assets/styles/sass/_shame.scss
This PR adds a geocoded search to the map controls. We leverage [HERE](here.com)'s geocoding API to take a text based search and return a series of location suggestions and then use the API again to retrieve the bounding box of the selected location.
There are functioning keyboard controls:
- **enter** will select and goto  the currently highlighted location
- **up and down arrows and tab** will cycle through the locations
We had to use the raw jQuery`$get` method to avoid sending a preflight request to the HERE API. The API does not support `OPTION` requests and this preflight response would get a 40x error, which …
> Add geocoded search to map controls

- docs/swagger/spec.yml
This PR includes post body parameters for posting to `/scenes/` and removes
an erroneous `discriminator` on `CombinedSceneQueryParams`. These are necessary
for the docs site to understand what's going on with scenes and for `bravado` to construct
`post_scenes` calls correctly in the python client.
* Tested as azavea/raster-foundry-python-client/pull/13
Closes #2262
> Include scene post body params

- app-tasks/rf/src/rf/uploads/geotiff/create_scenes.py
- app-tasks/rf/src/rf/uploads/geotiff/factories.py
This PR parses `acquisitionDate` and `cloudCover` from upload metadata when creating scenes.
* Bring up all ur stuff (server, airflow, frontend)
* Post the following, filling in a tif in s3, to `/api/uploads/`:
```json
{"files":["s3://<a tif somewhere>"],
"datasource":"c14c8e97-ba85-4677-ac9c-069cfef1f0b1",
"fileType":"GEOTIFF",
"uploadStatus":"UPLOADED",
"visibility":"PUBLIC",
"organizationId":"dfac6307-b5ef-43f7-beda-b9f208bb7726",
"metadata":{"acquisitionDate": null, "cloudCover": 0.1, "garbage": "yeah, garbage"},
"uploadType":"S3",
"projectId": null}
```
* Check the `cloudCover` (and `acquisitionDate`) on the created scene …
> Parse acquisitionDate and cloudCover from upload metadata

- app-backend/api/src/main/scala/scene/Routes.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Scenes.scala
This PR adds logic to the scene creation and update endpoints/methods to ensure ingests are kicked off at appropriate times. This should solve problems we were seeing when importing scenes without adding them to a project.
Namely, the changes make it so that:
- if a scene is created and it's ingest status is `TOBEINGESTED`, the ingest process will be kicked off
- if a scene is updated and it's previous status was not `TOBEINGESTED` but it's new status is `TOBEINGESTED`, the ingest process will be kicked off
We maintain the ingest trigger in the `addProjectScenes` endpoint as there should be not any interference.
* …
> Kickoff ingests for scene creation and updating

- app-frontend/src/app/components/scenes/sceneImportModal/sceneImportModal.controller.js
- app-frontend/src/app/components/scenes/sceneImportModal/sceneImportModal.html
This PR adds a state to uploads to handle attaching metadata to scenes in an upload.
* Bring up all ur stuff
* Create an s3 and a local upload
* Add some metadata to them
* Verify that the `acquisitionDate` and `cloudCover` values are included in the request
Closes #2234
> Send metadata when importing

- app-frontend/src/app/index.module.js
- app-frontend/src/app/index.routes.js
- app-frontend/src/app/pages/projects/edit/annotate/annotate.controller.js
- app-frontend/src/app/pages/projects/edit/annotate/annotate.html
- app-frontend/src/app/pages/projects/edit/annotate/annotate.module.js
- app-frontend/src/app/pages/projects/edit/edit.html
This PR adds an annotation section and button to the project edit page. Clicking the button will go to the annotate page, which currently has: a link to go back to project edit page, placeholder texts about annotating, buttons to import and export geojson annotations (will add functionalities in later PRs).
* Go to a project's edit page.
* Check if there is an "Annotation" section with an "Annotate project" button.
* Click the "Annotate project" button to see if it goes to the annotation page, which should have a link to go back to edit project page, a button group for importing and exporting geojson annotations. …
> Add annotation route and page for projects

- app-backend/api/src/main/scala/datasource/Routes.scala
- app-backend/api/src/main/scala/exports/Routes.scala
- app-backend/api/src/main/scala/image/Routes.scala
- app-backend/api/src/main/scala/maptoken/Routes.scala
- app-backend/api/src/main/scala/uploads/Routes.scala
Some of our create routes returned `200`s for "object created". That doesn't make any sense.
Sometimes this brings the routes into consistency with our spec (like with `Upload`s and `MapToken`s and `Export`s). Other times, it highlighted where the spec was weird. I'm creating issues for the other cases.
* ???
> Include StatusCodes with createFoo routes

- app-frontend/src/app/services/services.module.js
- app-frontend/src/app/services/vendor/planetLabs.service.js
This PR has two commits.  The first one is the angular service for querying the planet labs API in order to filter scenes and get scene thumbnails.  The filters match RF filters.  The second commit is a simple testing UI to make sure the service works as intended.
The service is in charge of sending requests to different planet API endpoints.  Request body should be constructed in the controller (as in the test UI - second commit).  The controller will pass different request bodies to the service to filter scenes based on different criteria.
* Change `YOUR_PLANET_API_KEY`(line 35 of planetlabs.controller.js) to your …
> Angular Service to Query Planet API

- Jenkinsfile
- app-backend/batch/src/main/scala/com/azavea/rf/batch/Main.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/healthcheck/HealthCheck.scala
- app-tasks/Dockerfile
- app-tasks/dags/ingest_project_scenes.py
- docker-compose.test.yml
- scripts/cibuild
- scripts/test
This PR reverts changes to the airflow Dockerfile that downgraded the openjdk version from 1.8 to 1.7. Also it adds logging to `ingest_project_scenes` so that you don't have to construct the metadata storage bash command yourself. _Also_ it adds a test to ci to make sure the batch jar can be run in airflow containers.
* Ingest a scene
* The metadata storage step should not fail
* If jenkins continues to refuse to cooperate, run `cibuild`
Closes #2291
> Install openjdk 8 in airflow containers

- app-tasks/dags/ingest_project_scenes.py
This PR switches from opening a new process to using `subprocess.check_call` to shell out to the metadata scala process when setting layer metadata in the db after ingest. It in the process fixes a typo I introduced that mangled the bash command construction.
Also it decreases the polling delay for the response from EMR for creating the step, since that response is really fast and there's no reason to wait 30 seconds for something that's regularly ready in 3.
* Bring up your server, airflow, and frontend
* Upload a tif
* Ingest shouldn't fail
Closes #2291 (again)
> Improve bash callout when setting layer metadata in ingest

- app-frontend/src/assets/styles/sass/components/_map.scss
See title
* Verify that the loading message is centered
* Verify that the new style doesn't break things on the map
Closes #2095
> Fix map loading text location to be centered on map

- app-frontend/src/app/components/tools/toolCreateModal/toolCreateModal.controller.js
- app-frontend/src/app/components/tools/toolCreateModal/toolCreateModal.html
Adds parsing for all the new operations which have a direct correspondence to math.js operations, which is the most of them.
Thresholding the blue band at all values > 192.
- Many unary operations don't result in visible changes to the map because of the way color ramps are being calculated. Try some trigonometric functions for dramatic results.
- Not all functions have a direct correspondence to math.js functions. It looks like it's possible to define custom functions so this shouldn't be too hard to add.
- We can't add a documentation link for the operators while this is only in staging but we should add one before it is deployed.
* Make lots of new tools
* Confirm they result in expected values.
> Add frontend parsing for many more local ops

- app-backend/common/src/main/resources/reference.conf
- app-backend/common/src/main/scala/Config.scala
- app-backend/common/src/main/scala/cache/kryo/KryoConnectionFactory.scala
Add ability to override Memcached client timeout. The default of 2500ms was being tripped in staging. It now defaults to 3000 ms.
Also, add ability to override Memcached client mode. When set to static, the set of endpoints specified during initialization are used throughout the lifetime of the client object. This is what we want in development because our local Memcached instance does not support auto-discovery.
When set to dynamic (the DefaultConnectionFactory default) the set of cache node endpoints, and any updates to it, are dynamically managed. This is what we want in production because ElastiCache supports auto-discovery.
- Launch the development environment using `server`
- Ensure that no `MemcachedClient` exceptions are thrown (when dynamic mode is enabled, it'll throw)
- …
> Add Memcached timeout and client mode settings

- app-frontend/src/app/components/channelHistogram/channelHistogram.controller.js
Fix histogram initialization with no color correction
* Verify that when opening color correction for the first time on a project, the histogram defaults the min and max rgb values to 0 and 255 respectively, instead of both at 0
Closes #2247
> Set default initial values of rgb clipping to min/max clipping

- app-backend/api/src/main/scala/project/Routes.scala
This PR takes out kicking off ingests a second time from adding scenes to projects. `addScenesToProject` calls `Scenes.update` to set ingest statuses to `TOBEINGESTED`. After that, we were finding all the scenes with statuses equal to `TOBEINGESTED` and kicking off ingest a second time.
* Bring up your server, frontend, airflow
* Upload a scene into a project
* Verify that only one ingest DAG is kicked off
Closes #2343
> Don't kickoff ingests twice

- app-backend/batch/src/main/scala/com/azavea/rf/batch/landsat8/airflow/ImportLandsat8.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/landsat8/airflow/ImportLandsat8C1.scala
The Landsat 8 importers should understand that not every image file for every
scene is always going to be available (human error might happen, or some images
just might not exist). Instead of failing when that occurs, it should return
some signal value that the image wasn't available and get on with the rest of
what it wants to do. This commit sets that signal value to -1 and lets importer
carry on its merry way.
It's unclear how frequently this occurs -- for June 7, 2016, there were three scenes that had missing imagery, and for the date I picked at random in the new period, there were none. Possibly we care about doing some …
> Handle missing images when scenes' images don't exist in s3

- app-frontend/package.json
- app-frontend/src/app/components/map/annotateToolbar/annotateToolbar.component.js
- app-frontend/src/app/components/map/annotateToolbar/annotateToolbar.controller.js
- app-frontend/src/app/components/map/annotateToolbar/annotateToolbar.html
- app-frontend/src/app/components/map/annotateToolbar/annotateToolbar.module.js
- app-frontend/src/app/components/map/annotateToolbar/annotateToolbar.scss
- app-frontend/src/app/index.components.js
- app-frontend/src/app/index.module.js
- app-frontend/src/app/index.vendor.js
- app-frontend/src/app/pages/projects/edit/annotate/annotate.controller.js
- app-frontend/src/app/pages/projects/edit/annotate/annotate.html
- app-frontend/src/app/services/map/map.service.js
- app-frontend/yarn.lock
This PR adds an annotation toolbar component for drawing points, rectangles, and polygons, and for adding their labels through popups.  The label name field in the popup has autocomplete feature based on labels already created.  
Editing and/or deleting labels, shapes, and geometries will be implemented in a future PR - which probably not in this component but on the sidebar
The import button now renders a hard-coded feature collection, which is passed to the component to be combined with other drawn shapes.  Hope this could result in a quicker process when adding the real import feature.
The export button now logs all annotations to the console in geojson format, which is for future developments. …
> Add Annotation Toolbar Component

- .github/PULL_REQUEST_TEMPLATE.md
This PR adds a box to the PR checklist. The box requires the author to check that the name of their PR won't get them shamed in Slack. PR names should be descriptive enough that guessing what they do in the changelog for new releases is easy, but sometimes we're lazy.
> Add vague name shame to PR template

- app-frontend/src/app/components/map/annotateToolbar/annotateToolbar.component.js
- app-frontend/src/app/components/map/annotateToolbar/annotateToolbar.controller.js
- app-frontend/src/app/pages/projects/edit/annotate/annotate.controller.js
- app-frontend/src/app/pages/projects/edit/annotate/annotate.html
- app-frontend/src/assets/styles/sass/_shame.scss
This PR adds annotations created by the annotation tool/imported by the user to the sidebar.  If no annotations created/imported, a notice will display.  The icons representing polygons and points before each label, and the "clone" icon/button are placeholders, which will be replaced once we have them added in the assets.  The clone/edit/delete icon/button functionalities will be implemented in the next PR. The label filter will be added in the PR after the next.
Sun and cloud icons are placeholders for points and polygons respectively.
* The styles are in _shame.scss
* The first commit (annotation toolbar component) …
> Add Annotations to Sidebar

- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/ColorCorrect.scala
Fixes a bug that was causing histogram equalization to return bizarre-looking results. I've verified that the output is now correct by comparing to GraphicsMagick's histogram equalization. However, the results are still...not all that great, although I think they now qualify as somewhat useful rather than completely useless. See notes for further discussion.
The left window is a screenshotted and then GraphicsMagicked version of the scene, while the right window is the output from Raster Foundry's histogram equalization.
- The reason for the bug was that histogram equalization would stretch the image's histogram, but the subsequent normalization and clipping steps were performed using the _original_ image's histogram, which usually had a much smaller range of values than the equalized …
> Correctly implement histogram equalization in color-correction

- docs/swagger/spec.yml
Update swagger spec for single band color correct
I removed the general tileClipping option because we don't need to store both a user set
default and band specific color correct. Band specific is enough. I also made it so that transformations that are specific to a band are stored together in an object (gamma, band #, and clipping)
* Verify that there are no errors in the spec
* Give feedback on proposed formap
Closes #2322
> Update swagger spec for single band color correct

- app-backend/api/src/main/scala/project/Routes.scala
- app-backend/api/src/main/scala/utils/QueryParameters.scala
- app-backend/api/src/test/scala/scene/SceneSpec.scala
- app-frontend/src/app/components/scenes/sceneFilterPane/sceneFilterPane.controller.js
- app-frontend/src/app/components/scenes/sceneFilterPane/sceneFilterPane.html
- app-frontend/src/app/components/scenes/sceneFilterPane/sceneFilterPane.module.js
- app-tasks/rf/src/rf/uploads/planet/factories.py
- docs/swagger/spec.yml
Fixes a few regressions and issues that became apparent after the deploy:
- Date parsing is now more tolerable to compliant ISO-8601 timestamps and less tolerant of improper timestamps
- Swagger spec issues are fixed that made it difficult to query scenes
- Fixes init for filter pane that was causing it to initialize twice
- Fixes issue where planet data could not be imported on first try
- Fixes bug where ingests were not being kicked off when added to a project
Adds autocomplete for drop down on datasource filter.
Going to merge this to test on staging and get it deployed. If there are comments we can add new …
> Clean Up API Spec/Queries/Planet Imports/Autocomplete

- app-backend/api/src/main/scala/tools/Routes.scala
- app-backend/api/src/test/scala/tools/ToolSpec.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/ast/package.scala
- app-backend/common/src/main/scala/ast/InterpreterExceptionHandler.scala
- app-backend/common/src/main/scala/ast/package.scala
- app-backend/tool/src/main/scala/eval/Interpreter.scala
- app-backend/tool/src/main/scala/eval/InterpreterError.scala
- app-backend/tool/src/test/scala/eval/InterpreterSpec.scala
This PR provides an endpoint at `/api/tools/validate` to which json can be posted. That JSON will be returned if it is valid. If not, the errors on the tree that are encountered will be sent back in its place.
Tests have been added to the `api` project. Manual testing requires only that you post putative AST json to `/api/tools/validate`
Closes #2226
> Allow for AST validation w/o toolrun

- app-backend/tile/src/main/scala/Router.scala
- app-backend/tile/src/main/scala/routes/ToolRoutes.scala
- app-backend/tool/src/main/scala/ast/codec/MapAlgebraUtilityCodecs.scala
Global stats (min, max, central tendency) on tool runs are desirable. It is not sensible to calculate these results exactly, but we can give a reasonable estimate using the histograms we generate for automatic coloring. This PR piggybacks on histogram functionality to return a `Statistics` object which serializes like this:
```json
{
"dataCells": 65536,
"mean": 43290.12355041505,
"median": 56568.93128076629,
"mode": 0,
"stddev": 29786.034076076023,
"zmin": 0,
"zmax": 132628
}
```
It would be great to include this on the AST (and that's something we're pursuing) but this should provide the functionality we want in the meantime
* Find a working `tool-run`
* Navigate to `/tiles/tools/<TOOLRUN-ID>/statistics`
* There are your statistics
Closes #2314
> Add global statistics endpoint for tool-runs

- app-tasks/dags/ingest_project_scenes.py
- app-tasks/dags/process_upload.py
- app-tasks/requirements.txt
- app-tasks/rf/src/rf/uploads/geotiff/factories.py
- app-tasks/rf/src/rf/uploads/planet/create_scenes.py
- app-tasks/rf/src/rf/uploads/planet/factories.py
This PR fixes two bugs:
1. Increase and jitter the sleep delay in the `wait_for_status` step of ingests. We set this to exactly 5 seconds previously, so if several `launch_spark_ingest` tasks started at the same time, they'd all query their step statuses at the same time as well, and often. This PR increases the time to 45 seconds as a base and adds between 0 and 30 seconds of jitter.
2. Check for projectId in the `GeoTiffS3SceneFactory`. This PR sets the created scene's ingest status based on whether the upload has a project. If the upload has a project, it sets the status to `NOTINGESTED`, since adding the scene to a project will set its status to `TOBEINGESTED` and kick off an ingest. If the upload doesn't have a project, it sets the scene's status to `TOBEINGESTED`, since uploading …
> Jitter ingest status sleep time and kickoff ingests exactly once for uploads

- app-backend/tile/src/main/scala/LayerCache.scala
- app-backend/tile/src/main/scala/routes/ToolRoutes.scala
- app-backend/tool/src/main/scala/ast/ClassMap.scala
- app-backend/tool/src/main/scala/ast/codec/MapAlgebraUtilityCodecs.scala
Color ramps were no longer being passed through to the cached function which produces color maps. This PR ensures that color ramps are used when provided. Currently supported color ramps: "viridis", "inferno", "magma", "lightYellowToOrange", "classificationBoldLandUse".
Specifying color and associated breaks can still be done, though this is accomplished via the `ToolRun` metadata field. Consider this `Tool` definition:
```json
{
"id": "0cc2aef3-ba7d-4b7a-bccf-ca993ad7d6df",
"args": [
{
"id": "7d9f3b46-12ce-49f2-9912-36badb352b9b",
"type": "src",
"metadata": null
}
],
"apply": "focalMean",
"metadata": null,
"neighborhood": {
"type": "square",
"extent": 1
}
}
```
If we want to specify an alternative color ramp to be used, we can do so in a one-off fashion by providing one of the above …
> Use provided color ramp in tool endpoint

- app-tasks/dags/aoi-monitoring/find_aoi_projects_to_update.py
- app-tasks/dags/aoi-monitoring/update_aoi_projects.py
- app-tasks/dags/export_project.py
- app-tasks/dags/import_landsat8_scenes.py
- app-tasks/dags/import_sentinel2_scenes.py
- app-tasks/dags/ingest_project_scenes.py
- app-tasks/dags/process_upload.py
- app-tasks/requirements.txt
- app-tasks/rf/src/rf/__init__.py
- app-tasks/usr/local/airflow/plugins/rest_api.py
- one big upgrade is the navigability of the UI -- in the screenshot, you can see that the UI home now shows both DAG runs _and_ task instances, which will help us diagnose faster when a DAG run gets created but tasks never get scheduled
- there's a pending deprecation warning about `provide_context=True`, but removing it breaks things :rage:
* rebuild your airflow containers -- `docker-compose -f docker-compose.airflow.yml build`
* bring up your server, frontend, and airflow
* get visibility on the airflow webserver logs -- `docker-compose -f …
> Upgrade airflow to 1.8.1 and decrease boto logging verbosity

- app-tasks/dags/aoi-monitoring/find_aoi_projects_to_update.py
- app-tasks/dags/import_landsat8_scenes.py
- app-tasks/dags/import_sentinel2_scenes.py
This PR sets catchup to `False` for scheduled DAGs so we don't have to care about excessive backfills any time the database gets lit on :fire: for mysterious reasons.
* `./scripts/server --with-airflow`
* Go to the webserver and turn `find_aoi_projects_to_update` on
* Go to DAG runs -- you shouldn't have thousands of them, just the ones for today
Closes #2417
> Set catchup to false for scheduled DAGs

- app-tasks/usr/local/airflow/airflow.cfg
This is mostly to keep explicit configuration settings up-to-date. I only made changes to the following settings:
- `endpoint_url` (new; made it align with `base_url`)
- `worker_refresh_internal` (new; 30s to 60s)
- `print_stats_interval` (new; 30s to 180s)
A diff of the configuration file changes since the last version of Airflow we ran: https://github.com/apache/incubator-airflow/compare/1.7.1.3...1.8.1
May be best to follow James' PR instructions [here](https://github.com/raster-foundry/raster-foundry/pull/2413). But, as long as the services start up (and stay up), I think things will be fine.
> Update Airflow configuration file after 1.8.x upgrade

- .gitignore
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Projects.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/BandDataType.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/ColorRampMosaic.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/SingleBandOptions.scala
- app-backend/tile/src/main/scala/LayerCache.scala
- app-backend/tile/src/main/scala/image/GlobalSummary.scala
- app-backend/tile/src/main/scala/image/Mosaic.scala
- app-backend/tile/src/main/scala/image/MultiBandMosaic.scala
- app-backend/tile/src/main/scala/image/SingleBandMosaic.scala
- app-backend/tile/src/main/scala/routes/MosaicRoutes.scala
- app-frontend/package.json
- app-frontend/src/app/index.vendor.js
- app-frontend/yarn.lock
~- [ ] Fix multi band mosaics~
* Make a single band project, or convert a multi band project to a single band project by setting the `isSingleBand` property and setting options through the api
Closes #2392
> Implement color ramps for single band projects

- app-backend/api/src/main/scala/uploads/package.scala
- app-backend/common/src/main/scala/S3.scala
Assuming the prefix was going to exist caused a bug in which, when there was no
prefix specified, we sent a prefix of "/". Separately, if the s3 path was
specified as "s3://bucket" (no trailing slash), then `getPath.tail` threw an
error.
This PR more delicately handles the cases when we receive trailing slashes or no
trailing slashes and prefixes or no prefixes so that we can successfully find S3
files regardless.
* Fire up your server, airflow, and frontend
* Ask me about my public bucket
* Try the following S3 source paths:
* `s3://<bucket>`
* `s3://<bucket>/`
* `s3://<bucket>/dummy-prefix`
* `s3://<bucket>/dummy-prefix/`
* All …
> Parse s3 prefixes more delicately

- app-backend/common/src/main/scala/S3.scala
Similar to the problem with prefixes, we were making too strong an assumption
about what we'd be able to parse from the user-input bucket. When a bucket
name contains all underscores rather than dashes, the bucket name is available
under uri.getAuthority rather than uri.getHost. Using getHost caused us to make
a request to s3 without telling it which bucket to look in.
* Bring up all ur stuff
* Do an s3 upload from that one bucket that we know breaks (ask me about this if you don't know which one it is)
* watch as it magically succeeds
* anyway the good news is, the …
> Parse bucket more delicately from upload s3 source

- app-frontend/src/app/services/common/thumbnail.service.js
Thumbnail route for local urls now has buildconfig api host included
* Verify that import thumbnail urls are set properly (as a bonus, import thumbnails should work on develop now!)
Closes https://github.com/raster-foundry/raster-foundry/issues/2421
> Fix thumbnails on import page

- app-backend/common/src/main/scala/cache/CacheClient.scala
- app-backend/common/src/main/scala/geotrellis/spark/io/postgres/PostgresAttributeStore.scala
- app-backend/tile/src/main/scala/image/SingleBandMosaic.scala
This PR handles cases where we find a tile and don't find a tile differently for caching. Currently, when we fail to find a tile, we cache the `None` value forever. Instead, with this PR, we cache found tiles forever and `None`s for five minutes.
* Decrease the ttl for `None` tiles from 5 minutes to a minute (or something, your choice) to save yourself some time, and throw a `println(cacheKey)` into `getOrElseUpdate` in `CacheClient.scala`
* Bring up your server, airflow, and frontend
* In another terminal, run `docker-compose logs -f tile-server`
* In yet another terminal, `docker-compose exec tile-server ./sbt`, `tile/console`, …
> Don't cache None tiles forever

- app-frontend/config/webpack/global.js
- app-frontend/config/webpack/overrides.js.template
- app-frontend/src/app/pages/settings/profile/profile.html
- app-frontend/src/app/services/vendor/intercom.service.js
- allows the Intercom `APP_ID` to be overrideable via the `overrides.js` file
- fixes the password change button so that user's logged in with email/password auth through Auth0 can request password change emails
- [:shrug:] PR has a name that won't get you publicly shamed for vagueness
* Try adding an INTERCOM_APP_ID to the overrides file that is senseless ('abc' is a solid choice) and then reload the webpack server
* Ensure the Intercom widget doesn't show up
* Try removing the INTERCOM_APP_ID from the overrides file, reload webpack, and see that the widget works.
* Make sure you are logged …
> Fix password reset button; Allow Intercom APP_ID to be specified in overrides

- app-frontend/config/webpack/global.js
- app-frontend/config/webpack/overrides.js.template
- app-frontend/src/app/index.run.js
- app-frontend/src/tpl-index.html
Before this commit, APP_NAME was not being used to replace the title
in the templated javascript or in the titles for views.
* Copy `overrides.template.js`
* Replace `APP_NAME` with something that is obvious
* Observe that the application name in a chrome tab is replaced with what you used in the previous step
> Add override support for `APP_NAME` in frontend

- CHANGELOG.md
This PR fixes our CHANGELOG, which has some PRs grouped under the wrong release because of skywinder/github-changelog-generator#503.
- Add a docker container that builds a functioning fork of the changelog generator
- Use that container to rebuild the current CHANGELOG.
N/A
- I forked github-changelog-generator because the PR that fixes this issue has been sitting in the main repo for a few months without any movement, even though other changes have been merged in.
* Build the  container, generate a CHANGELOG, ensure no changes are made. Any commits to `develop` since the last release will end up under the `0.21.0` …
> Rebuild CHANGELOG

- app-frontend/src/app/pages/projects/edit/annotate/annotate.controller.js
So it turned out that appending hashes (for the autoscroll to happen) to the url caused the bug. Somehow, right after creating a new project, if you go to the annotation page and you do anything that triggers appending hashes to URL (like creating new shapes, hover or click on shape/sidebar item - all for autoscrolling purpose), the page wants to refresh. It does not happen in an existing project though.
This PR fixes such issue by simply avoiding appending hashes to the URL, and just use `$anchorScroll` alone...
* Create a new project and go to annotation page within this new project
* Create/edit/clone/click/hover …
> Staging Bug Fix - Annotation page refresh upon new shape creation in a new project

- app-frontend/src/app/components/projects/annotateSidebarItem/annotateSidebarItem.controller.js
- app-frontend/src/app/components/projects/annotateSidebarItem/annotateSidebarItem.scss
- app-frontend/src/app/pages/projects/edit/annotate/annotate.controller.js
This PR fixes bugs on staging concerning annotation edit/rotate/resize so that:
* The old annotation rotate handles won't show if pressing "r" key (to rotate) again under the rotate mode. New rotate handles will show for controlling the most current shape.
* The old annotation rotate handles won't show if pressing any arrows keys to move shape around. It will automatically switch to shape edit mode.
* It allows you to switch between rotate and edit modes by pressing "r" and "e" keys respectively whenever there is a red shape (indicating an editable/rotatable shape) on the map.
Rotating/Rescaling is only allowed when …
> Staging Bug Fix - the persistence of annotation rotate handles

- app-tasks/Dockerfile
After some experimentation, it does not appear that the Airflow container image needs the `python-dev` package as a build dependency (or at all). Previous failures with the `python-numpy` package go away once this dependency is removed.
From inside of the Vagrant virtual machine, execute the following command and ensure that it builds the `airflow-webserver` container image properly:
```bash
vagrant@vagrant-ubuntu-trusty-64:/opt/raster-foundry$ docker-compose -f docker-compose.airflow.yml build airflow-webserver
```
For laughs, use the following commands to ensure that important tools are still at the desired versions:
```bash
vagrant@vagrant-ubuntu-trusty-64:/opt/raster-foundry$ docker-compose -f docker-compose.airflow.yml run --rm --entrypoint bash airflow-webserver …
```
> Remove unnecessary python-dev build dependency

- app-frontend/src/app/components/tools/toolCreateModal/toolCreateModal.controller.js
This PR adds support for a `classify` function in *mamlscript*.
Syntactically, this is really a first pass but it is pretty straightforward:
`classify(input_expression, classifications)`
- `input_expression` is any valid *mamlscript* expression. Ex: `A + B + C`
- `classifications` is an object mapping the maximum value of a class (double as string) to an output value (integer). Ex: `{ "0.0": 0, "1.0" : 1}`
Additionally, this PR also adds like-operation merging. Previously, an expression like `A + B + C` would have been parsed into a tree more like `A + (B + C)`. This would stack, so expressions could end up unnecessarily deep (`A + (B + (C + (D + E)))`). This is accomplished in a way that respects parenthetical groupings.
~- [ ] Swagger …
> Add parsing of `classify` function in mamlscript

- app-tasks/dags/ingest_project_scenes.py
Ensure that Scenes are marked "FAILED" if generating an ingest definition fails.
* `./scripts/server --with-airflow`
* Use the UI to upload a tiff that isn't from Landsat, but lie to RF and tell it that it _is_ Landsat.
* Use either the UI or DB to confirm that the scene ingest_status gets set to FAILED, either in the UI or DB.
Closes #2469
> Mark Scene as failed if ingest definition fails

- scripts/setup
This plugin is not needed as the functionality for rsync exists in Vagrant itself.
Execute the following sequence of commands:
```bash
$ vagrant plugin uninstall
$ vagrant plugin list
vagrant-hostmanager (1.8.7)                 
vagrant-share (1.1.9, system)               
$ vagrant rsync-auto
```
If the virtual machine is up, `rsync` based synchronization should continue to work without `vagrant-rsync` installed.
> Remove installation of third-party vagrant-rsync plugin

- deployment/ansible/group_vars/jenkins
- deployment/ansible/raster-foundry-jenkins.yml
- deployment/ansible/roles.yml
Ensure that Packer is installed on Jenkins in order to support building custom AWS Batch AMIs.
Addresses part of https://github.com/azavea/raster-foundry-platform/issues/123
SSH into the Jenkins CI server and ensure that you get the same output as below:
```bash
ubuntu@ip-172-31-52-80:~$ packer -v
1.0.4
```
> Add Packer to Jenkins deployment configuration

- app-frontend/src/app/components/colorComposites/colorSchemeDropdown/colorSchemeDropdown.component.js
- app-frontend/src/app/components/colorComposites/colorSchemeDropdown/colorSchemeDropdown.controller.js
- app-frontend/src/app/components/colorComposites/colorSchemeDropdown/colorSchemeDropdown.html
- app-frontend/src/app/components/colorComposites/colorSchemeDropdown/colorSchemeDropdown.module.js
- app-frontend/src/app/index.components.js
- app-frontend/src/app/pages/projects/edit/colormode/colormode.controller.js
- app-frontend/src/app/pages/projects/edit/colormode/colormode.html
- app-frontend/src/assets/styles/sass/_shame.scss
- app-frontend/src/assets/styles/sass/components/_button.scss
This adds a dropdown component that contains various color-scheme configuration options.
There are some rough edges that we probably won't get ironed out until the backend and some other parts are solidified.
I believe we still need some clarity around how we're handling discrete color-schemes in this context. As a result, there is a bit of hand-waving since the test environment doesn't match the context in which we'll be using the dropdown.
Since angular doesn't play nice with propagating changes to component with an object that is one-way bound, the input to the dropdown is serialized (`angular.toJson` works well for this). 
You'll want to put the dropdown somewhere. Passing it single-band-options isn't necessary to test the base functionality.
```
<li>
<span class="label">Color …
```
> Color scheme dropdown

- app-frontend/src/app/components/map/labMap/labMap.controller.js
- app-frontend/src/app/components/map/mapContainer/mapContainer.controller.js
- app-frontend/src/app/components/map/staticMap/staticMap.controller.js
- app-frontend/src/app/components/projects/projectItem/projectItem.controller.js
- app-frontend/src/app/pages/lab/run/run.controller.js
- app-frontend/src/app/pages/projects/detail/detail.controller.js
- app-frontend/src/app/services/map/layer.service.js
This PR moves setting `maxZoom` from the individual tile layers to the maps. #1940 popped up because each call to `L.tileLayer` needed to set `maxZoom` individually, and we missed one. That's an annoying thing to have to keep doing when they're all going on just a few maps and we always picked 30. Also there was a function that wasn't called anywhere that I deleted.
* Go to each of the map views (tools, share, and project edit)
* On each, verify that you continue to request tiles when you zoom in up to level 30
Closes #1940
> Set maxZoom at map level

- app-frontend/src/app/pages/projects/edit/edit.controller.js
- app-frontend/src/app/services/map/map.service.js
This makes a change to the `addLayer` method of the map service. It now takes an object of options that can override certain default settings (such as initial layer visibility).
* Open a project with some un-ingested scenes in the editor. See that the thumbnails aren't visible by default.
* Using the layer-picker, enable the thumbnails of un-ingested scenes. See that they show up.
Closes #2473
> Do not show uningested scene thumbnails in project edit by default

- app-frontend/src/app/components/tools/toolSearch/toolSearch.controller.js
- app-frontend/src/app/components/tools/toolSearch/toolSearch.html
- app-frontend/src/app/index.routes.js
- app-frontend/src/app/pages/market/search/search.controller.js
- app-frontend/src/app/pages/market/search/search.html
- app-frontend/src/app/services/tools/tool.service.js
- fixes pagination on the tool list
- enables searching on the tool list
The search bypasses pagination as a way to work around the lack of search support in the API. When a search is being done, all tools are requested and then filtered on the front-end.
Eventually, this will not scale.
* Bring up the tool list page, and see that it is paginated as one would expect
* Try searching for some tools that appear on pages other than the first page, and see that they appear
Closes #2486
> Enable pagination and searching for Tools

- app-tasks/requirements.txt
- app-tasks/rf/setup.py
- app-tasks/rf/src/rf/__init__.py
- app-tasks/rf/src/rf/cli.py
- app-tasks/rf/src/rf/commands/__init__.py
- app-tasks/rf/src/rf/commands/export.py
- app-tasks/rf/src/rf/commands/find_aoi_projects.py
- app-tasks/rf/src/rf/commands/ingest_scene.py
- app-tasks/rf/src/rf/commands/process_upload.py
- app-tasks/rf/src/rf/commands/update_aoi_project.py
- app-tasks/rf/src/rf/utils/emr.py
- docker-compose.airflow.yml
This commit represents the initial step to using AWS batch for
all asynchronous processing by converting all Airflow DAGs to
commands.
DAGs that were previously multiple tasks have been converted into
a single command to simplify the logic and avoid unecessarily
complicated workflows in AWS batch.
- This does not include using the `rasterfoundry` python client for API interaction in order to limit the amount of moving parts
- Keeps existing workflows/airflow processes around -- in order to remove airflow completely the API calls from the API server need to be switched to use batch
- Batch job definitions should now be …
> Add `rf` command line client to process asynchronous tasks

- app-tasks/rf/src/rf/commands/find_aoi_projects.py
Rename the parameter for `jobUpdateAoiProject` from `project` to `projectId`.
- [x ] PR has a name that won't get you publicly shamed for vagueness
Ensure that `projectId` is the parameter name for `jobUpdateAoiProject`.
> Rename jobUpdateAoiProject parameter to projectId

- app-tasks/rf/src/rf/commands/find_aoi_projects.py
Previous environment variables prefixed with `AWS_BATCH_` were getting wiped by AWS Batch at job scheduling time. This led to variable values always set to `None`.
[This](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/batch/job;stream=jobStagingFindAoiProjects/default/52529b32-1289-4153-a200-97dd87a5c61f) job should have `AWS_BATCH_JOB_NAME_AOI_UPDATE` set, but it does not. Adding a prefix to the environment variable in [this](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/batch/job;stream=jobStagingFindAoiProjects/default/b39d711b-46df-4dfe-a017-d45b89dfb208) job allowed `T_AWS_BATCH_JOB_NAME_AOI_UPDATE ` to come through.
> Rename Batch environment variables for AoI commands

- app-backend/batch/src/main/resources/application.conf
- app-backend/batch/src/main/scala/com/azavea/rf/batch/ingest/model/BandMapping.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/ingest/model/TargetBand.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/ingest/spark/Ingest.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/sentinel2/airflow/ImportSentinel2.scala
- app-backend/batch/src/test/resources/ingest/awsJob.json
- app-backend/batch/src/test/resources/ingest/localJob.json
- app-backend/batch/src/test/scala/com/azavea/rf/batch/ingest/model/IngestDefinitionSpec.scala
- app-tasks/rf/src/rf/commands/ingest_scene.py
- app-tasks/rf/src/rf/ingest/__init__.py
- app-tasks/rf/src/rf/ingest/geotiff_ingest.py
- app-tasks/rf/src/rf/ingest/landsat8_ingest.py
- app-tasks/rf/src/rf/ingest/sentinel2_ingest.py
- app-tasks/rf/src/rf/models/band.py
- app-tasks/rf/src/rf/models/image.py
- app-tasks/rf/src/rf/uploads/geotiff/io.py
Sentinel-2 images couldn't be ingested for at least two reasons. The files were
in jpeg 2000, rather than geotiff, file format, and the bands didn't have
strictly numeric labels. This commit adds processing to convert jpeg 2000s to
tifs for ingest and expands the BandMaps representation to include a label and
an index-on-write, so we can deal with inconvenient labels for bands like "8A".
It also includes some minor fixups like a typo in `rf/models/band.py`s' `__repr__`
function.
~I'm waiting to remove `WIP` until #2505 is merged, since this will become a part of it~ It's merged
~I think we might also have some of the wavelength …
> Add ingest handling for Sentinel-2 Jpeg2000 images

- app-frontend/src/app/pages/share/share.controller.js
Set max zoom level to 30 again
* Verify that the share page allows high zoom levels again
Closes #2250
> Fix share page zoom levels

- .env.template
Add necessary AWS Batch environment variables. Then, reorganize environment template and remove dead environment variables.
Associated remote `development` and `testing` environment files in S3 were updated as well.
I tested this set of changes locally by running `setup` from outside of the virtual machine and then using `server` within it to bring up the application. From there, I interacted with a few common areas of the UI.
**Note**: If you're trying to ensure that the `.env` file updated, don't forget to check inside of the virtual machine (the one outside won't update thanks to `rsync`).
Resolves https://github.com/azavea/raster-foundry-platform/issues/126
> Update project environment variable template

- app-frontend/src/app/components/histogram/histogramBreakpoint/histogramBreakpoint.component.js
- app-frontend/src/app/components/histogram/nodeHistogram/nodeHistogram.controller.js
- app-frontend/src/app/components/histogram/nodeHistogram/nodeHistogram.html
Hide non-endpoint breakpoints for continuous node color schemes
Categorical color schemes appear to be broken on the backend, I tried `QUALITATIVE[#000000]` as the dataType but it defaults to viridis as when there's an error parsing the color scheme
* Verify that continuous color schemes no longer have intermediary breakpoints
* Verify that categorical color schemes show the intermediary breakpoints
Closes #2527
> Hide non-endpoint breakpoints for continuous node color schemes

- app-frontend/src/app/components/colorComposites/colorSchemeBuilder/colorSchemeBuilder.controller.js
- app-frontend/src/app/components/projects/projectCreateModal/projectCreateModal.html
- app-frontend/src/app/pages/projects/edit/colormode/colormode.controller.js
- app-frontend/src/app/pages/projects/edit/colormode/colormode.html
- app-frontend/src/app/services/projects/colorScheme.defaults.json
- app-frontend/src/assets/styles/sass/_shame.scss
Use color scheme dropdown selector for single band projects
Bins are not implemented, for the same reason that they are not implemented in the node histograms
Categorical color schemes when selected do not show the correct color scheme selected - Not sure it's worth fixing this until we decide how we actually want this part of the app to work.
* Verify that you can now set color schemes for single band projects again.
Closes #2508
> Use color scheme dropdown selector for single band projects

- app-frontend/src/app/components/tools/diagramContainer/diagramContainer.controller.js
- app-frontend/src/app/components/tools/diagramNodeHeader/diagramNodeHeader.html
- app-frontend/src/app/components/tools/nodeStatistics/nodeStatistics.component.js
- app-frontend/src/app/components/tools/nodeStatistics/nodeStatistics.controller.js
- app-frontend/src/app/components/tools/nodeStatistics/nodeStatistics.html
- app-frontend/src/app/components/tools/nodeStatistics/nodeStatistics.module.js
- app-frontend/src/app/index.components.js
- app-frontend/src/app/services/tools/tool.service.js
- app-frontend/src/assets/styles/sass/_shame.scss
This PR adds a control to nodes to display stats about that node.
There is currently a problem with the statistics endpoint in that it is returning a 204 when we expect to get data back. This PR build on the expected behavior and so should 'just work' when the bug is fixed.
We are lacking an icon for stats (could be something like a capital sigma), so I opted to write-out 'stats' for clarity.
* Check that the proper message is displayed when you view stats without having applied changes
* Check that after applying inputs, a different message is displayed (saying that stats aren't available)
* If desired, you can use the `emptyStats` object and set `this.stats` to a stubbed object in the response handling of the `fetchStats` method in the `node-statitistics.controller` (after the reduce) …
> Implement statistics node display in lab UI

- app-tasks/Dockerfile
To pull down images and write them to /tmp, the user in the container
needs to be able to write to the location where /tmp is mounted outside the
container. The airflow user can't do that, but root can. Celery will get mad,
but that's fine.
* Look on my [logs](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logEventViewer:group=/aws/batch/job;stream=jobStagingIngestScene/default/c06be807-e4b7-4fc4-998c-583f3e44befc) ye mighty and despair
> Run airflow container as root instead of airflow

- app-backend/tile/src/main/scala/Router.scala
The stats endpoint was being ignored due to short circuiting of akka-http's URI matching logic. Rearranging the endpoints fixed this.
* Ask for stats on a `ToolRun`
Closes #2543
> Enable ToolRun Statistics

- app-frontend/src/app/components/tools/nodeStatistics/nodeStatistics.controller.js
Now that stats are returned, the UI was not displaying them -- this ensures that they get displayed.
* Load a tool in the UI and check stats
> Add method to enable displaying returned stats in tool node UI

- app-backend/tile/src/main/scala/routes/HealthCheckRoute.scala
This PR more aggressively checks in with other services before letting the tile server
claim to be healthy. It says it's ok... Is it really ok? Is it just telling us it's ok so we'll go away and leave
it alone? _Now we'll know_.
* bring up your tile server
* start a watch from inside your vm on `localhost:9900/tiles/healthcheck` or from outside the vm on whatever nginx makes that available as (`watch http`, `watch curl`, infinite loop with `requests` in a python shell... pick your poison :skull:)
* selectively kill the `memcached` and `postgres` services and watch the response change
* bring the `memcached` and `postgres` …
> Check database and memcached reachability in tile server healthcheck

- app-tasks/Dockerfile
Alpine Linux's build for GDAL was missing an OpenJPEG driver.
covers updating the package so we can switch back to
Alpine at a later date
> Use debian base for raster-foundry-batch image

- app-backend/api/src/main/scala/grid/Routes.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Scenes.scala
Fix grid endpoint returning counts that include ALL scenes, rather than just scenes the user has permission to view
* Create a filter that returns a couple of scenes that are public and uploaded by another user, then change their visibility to PRIVATE. The same filter should no longer show any scenes in the panel or the grid.
> Filter scene grid endpoint on user visibility

- app-tasks/rf/src/rf/commands/export.py
Without the `name` attribute in the @click.command decorator the export command
is not available.
* Run `docker-compose build batch`
* Run `./scripts/console batch rf` and ensure export is listed as an option for commands
> Ensure export command is visible in `rf` command line tool

- Vagrantfile
- deployment/ansible/group_vars/all
- deployment/vagrant/run_ansible_galaxy.rb
- docker-compose.metrics.yml
- docker-compose.spark.yml
- docker-compose.swagger.yml
- docker-compose.test.yml
- docker-compose.yml
- scripts/load_development_data
- scripts/update
Using docker-compose's `healthcheck` configuration option, run `pg_isready` on the `postgres` container to determine if it is healthy before creating databases or loading data. Replaces `check_database` in `scripts/update` and `scripts/bootstrap`. 
Also, install Ansible roles inside of the VM. This gets rid of the `Duplicate Watched Directory` error from Vagrant Rsync.
__Note: this will require you to destroy your database__
- Remove the postgres container (and associated …
> Replace check_database with docker-compose healthcheck

- app-frontend/src/app/components/scenes/sceneDetailModal/sceneDetailModal.controller.js
- app-frontend/src/app/components/scenes/sceneDetailModal/sceneDetailModal.html
- app-frontend/src/app/components/scenes/sceneDetailModal/sceneDetailModal.module.js
- app-frontend/src/app/components/scenes/sceneDetailModal/sceneDetailModal.scss
- app-frontend/src/app/components/scenes/sceneList/sceneList.html
- app-frontend/src/app/services/scenes/scene.service.js
This PR allows you to edit an uploaded scene's properties and metadata within the scene detail modal.
Edit mode:
Date picker:
* `visibility` and `dataSource` are set as not editable at this point. `sunAzimuth` and `sunElevation` can be edited on the frontend but cannot actually be changed through bulk update.
* Some css changes per the design is in the sceneDetailModal directory. @designmatty 
* Go to `/imports`
* Click on "View" of a scene item. If this is your upload, you should see an "Edit Metadata" button.
* Make changes to these fields. After you click "Save Metadata", new changes should be reflected.
* Refresh …
> Allow editing uploaded scene's properties and metadata.

- app-frontend/src/app/pages/lab/run/navbar/navbar.html
- app-frontend/src/app/pages/lab/run/run.controller.js
- app-frontend/src/app/services/projects/project.service.js
- app-frontend/src/app/services/tools/labUtils.service.js
Makes it so that source nodes use project tiles for comparison purposes.
This means that we no longer are comparing the "band" that is the source, but the project. I'm not sure that was a desired feature, to be honest so I don't think it's a loss.
Also, you will have to choose to compare on the preview map rather than selecting nodes because that is broken (see https://github.com/raster-foundry/raster-foundry/issues/2564)
* Start frontend and either point it at staging or a local development environment
* Use a simple tool to load a project
Closes #1949
> Use project tiles to preview node if node is a source

- app-frontend/src/app/components/colorComposites/colorSchemeDropdown/colorSchemeDropdown.controller.js
- app-frontend/src/app/components/colorComposites/colorSchemeDropdown/colorSchemeDropdown.html
- app-frontend/src/app/components/histogram/nodeHistogram/nodeHistogram.controller.js
- app-frontend/src/app/components/histogram/nodeHistogram/nodeHistogram.html
- app-frontend/src/app/components/settings/featureFlagOverrides/featureFlagOverrides.html
- app-frontend/src/app/components/tools/diagramContainer/diagramContainer.controller.js
- app-frontend/src/app/services/auth/auth.service.js
- app-frontend/src/app/services/projects/colorScheme.defaults.json
- app-frontend/src/app/services/projects/colorScheme.service.js
- app-frontend/src/app/services/settings/featureFlagOverrides.service.js
- app-frontend/src/app/services/tools/labUtils.service.js
- app-frontend/src/assets/styles/sass/_shame.scss
Fix categorical breakpoints appearing before selecting categorical color scheme
Save blending mode
Fix random lab initialization errors when reloading page
Adjust logic calling onChange function from dropdown: Only call when the number
of bins is changed on the current scheme, or when the scheme is changed.
Fix webpack lint error
Add Pastel color scheme
Use QUALITATIVE[#xxxxx] instead of CATEGORICAL for renderDef
* There is a bug on the backend with displaying qualitative color schemes - see
#2571 for details
The backend currently doesn't support categorical color schemes per #2571
In the node histogram:
* Verify that …
> Color scheme dropdown qualitative support

- app-frontend/src/app/components/colorComposites/colorSchemeDropdown/colorSchemeDropdown.controller.js
- app-frontend/src/app/components/colorComposites/colorSchemeDropdown/colorSchemeDropdown.html
- app-frontend/src/app/components/histogram/nodeHistogram/nodeHistogram.controller.js
- app-frontend/src/app/services/projects/colorScheme.service.js
- app-frontend/src/app/services/settings/featureFlagOverrides.service.js
- app-frontend/src/assets/styles/sass/_shame.scss
Add button to reverse lab node color schemes
Preserve min/max bounds on breakpoints when switching color schemes
Doesn't do anything for single band options - we'll catch it up later along with the rest of the color scheme dropdown stuff
* Verify that you can reverse color schemes in node histograms
* Verify that breakpoint min/max positions are preserved when switching between color schemes
Depends on #2573
Closes #2581 
Closes #2567
> Add button to reverse lab node color schemes

- app-frontend/package.json
- app-frontend/src/app/components/map/labMap/labMap.controller.js
- app-frontend/src/app/components/map/labMap/labMap.html
- app-frontend/src/app/components/map/labMap/labMap.module.js
- app-frontend/src/app/components/map/labMap/labMap.scss
- app-frontend/yarn.lock
This PR adds a feature to allow measuring length and area in lab map. It uses leaflet draw and brings in two additional methods in turf.js to calculate areas and distances. Results are displayed in metric units via popups. Measurements can be deleted along with their shapes. They will also be deleted after closing the lab map.
The icon of the measurement control is now a placeholder since its icon is pending (issue number: 2548)
* Go to lab map
* Use measurement control to measure area and length
* Check if it behaves as you expected.
Closes #2410
> Add measurement tool to lab map

- Jenkinsfile
Ensure that the `master` branch of the deployment repository is always used for production deployments.
See deployment wiki for associated workflow changes.
The PR build should ensure that syntax in the `Jenkinsfile` is valid. Currently, `master` of the deployment repository reflects the desired state of the infrastructure for our upcoming release.
Closes https://github.com/azavea/raster-foundry-platform/issues/145
> Use deployment repository master branch for production

- app-backend/batch/src/main/scala/com/azavea/rf/batch/sentinel2/ImportSentinel2.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Scenes.scala
When importing Sentinel 2 scenes the importer checks that a scene has not
already been added before adding the scene. Before this commit a database call
would be made for each scene and would produce a heavy load on the database. To
get around this problem, this commit instead retrieves a list of scenes first
and uses that for comparisons when doing the import.
This makes an assumption that there will not be duplicate imports within a single job.
* Run assembly for the batch container:
```
./scripts/console api-server bash
./sbt
project batch
assembly
```
* In the container, kick off an import -- kill it after a few …
> Reduce Database Load during Sentinel 2 Import

- app-frontend/src/app/components/map/annotateToolbar/annotateToolbar.component.js
- app-frontend/src/app/components/map/annotateToolbar/annotateToolbar.controller.js
- app-frontend/src/app/components/map/annotateToolbar/annotateToolbar.html
- app-frontend/src/app/components/projects/annotateSidebarItem/annotateSidebarItem.component.js
- app-frontend/src/app/components/projects/annotateSidebarItem/annotateSidebarItem.controller.js
- app-frontend/src/app/components/projects/annotateSidebarItem/annotateSidebarItem.html
- app-frontend/src/app/pages/projects/edit/annotate/annotate.controller.js
- app-frontend/src/app/pages/projects/edit/annotate/annotate.html
- fixes the navigation interrupt logic to ensure the interrupt is deactivated
- adds a bulk annotation mode that speeds up the annotation process for like objects
We don't have an icon and thus this the 'Bulk Create' link is pretty ugly.
* Create an annotation
* Click 'Bulk Create' on that annotation
* Select the type of shapes you want to create
* Create many annotations
* Make sure hitting the 'Finish' button works as you'd expect
Closes #2608
> Bulk annotation mode and interrupt fix

- app-frontend/src/app/components/histogram/channelHistogram/channelHistogram.html
- app-frontend/src/app/pages/projects/edit/advancedcolor/adjust/adjust.controller.js
- app-frontend/src/app/pages/projects/edit/advancedcolor/advancedcolor.html
- app-frontend/src/app/pages/projects/edit/colormode/colormode.html
Remove ability to apply auto color corrections (keeping component for later)
Remove breakpoints from color correction histogram
* Verify that clicking the corrections button under color mode goes directly to the advanced color mode
* Verify that there are no breakpoints on the color correction histogram
Closes https://github.com/azavea/raster-foundry-platform/issues/151
Closes #2578
> Remove ability to apply auto color corrections

- app-frontend/src/app/components/map/annotateToolbar/annotateToolbar.controller.js
This PR does the checks for the existence of draw handler before canceling them in the annotate toolbar component, which seems to be the issue on the newest develop branch.
* Go to annotate page and open console. There should be no error messages telling you something like 'Cannot read property 'disable' of undefined'.
> Fix annotate draw handler existence issue

- app-frontend/src/app/components/common/dateRangePickerModal/dateRangePickerModal.controller.js
- app-frontend/src/app/components/scenes/sceneFilterPane/sceneFilterPane.controller.js
- app-frontend/src/app/components/scenes/sceneFilterPane/sceneFilterPane.html
This PR fixes date selection button bug on scene filter pane.
* Go to browse scenes and turn on filter pane
* If there is no date range filter, the button should read 'Set Date Filter'. Otherwise, it should read 'Update Date Filter'.
* Click on it to set date or set it to 'None' as no date filter.
Closes #2576
> Fix date selection button bug on scene filter pane.

- Jenkinsfile
Ensure that the `master` branch of the deployment repository is always used for production deployments. Also, ensure the `develop` branch is used otherwise.
The [following](http://jenkins.staging.rasterfoundry.com/job/Raster%20Foundry/job/raster-foundry/job/develop/156/) Jenkins build was executed with the contents of the `Jenkinsfile` in this branch.
> Use correct branch for CI deployment

- app-backend/database/src/main/scala/com/azavea/rf/database/fields/SceneFields.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/sort/SceneFieldsSort.scala
- app-frontend/src/app/pages/projects/edit/browse/browse.controller.js
Fall back to createdAt if acquisitionDate is null
Previewed scene is the bottom one labelled `August 23, 2017`
the two green scenes don't have an acquisition date, and are inserted into the order according to their created time.
* View a list of scenes in the project scene browser
* In psql, change the createdAt time for one of the scenes with an acquisition date in the middle to a very early date. EG: `update scenes set created_at = date '2001-09-28' where id = 'df7d4882-2e47-4559-ada3-c74303ef237e';`
* reload the list and verify that the scene order has not changed
* Verify that scenes with no acquisition date are …
> Sort scenes by acquisition date if available

- app-tasks/rf/src/rf/uploads/geotiff/factories.py
* Create an upload (via the API or UI) and get the ID
* Either adjust the split threshold size in `app-tasks/rf/src/rf/uploads/geotiff/utils.py` (which will require a `vagrant rsync` and then a `docker-compose build batch`) or upload a tif larger than 1gb
* `./scripts/console batch bash`
*  `rf process-upload <upload-id>` and see that the split files are uploaded to an RF bucket
> Upload split files to platform bucket rather than source bucket

- app-backend/tile/src/main/scala/LayerCache.scala
- app-backend/tile/src/main/scala/routes/ToolRoutes.scala
- app-backend/tile/src/main/scala/tool/TileResolver.scala
The build is failing due to a filename being too long. I've been unable to reproduce this locally but have shortened the filename that (we think) is responsible. Hopefully this change will be sufficient, though I don't see how we can test it other than merging to see what happens.
> Shorten RfmlTileResolver

- app-tasks/rf/src/rf/commands/ingest_scene.py
- app-tasks/rf/src/rf/ingest/models/ingest.py
- app-tasks/rf/src/rf/utils/emr.py
Fixes issues when too many jobs were kicked off at once and EMR would return throttling errors that we did not catch.
Closes #2641
> Add retry and backoff to ingest statuses

- app-tasks/rf/src/rf/ingest/sentinel2_ingest.py
Prior to this commit temp directories and files were not being cleaned up.
If/when ingests were run on the same machine then ingests would fail and
sometimes clobber each other. Now files are properly namespaced and quarantined
in addition to being cleaned up between ingests.
> Use context managed temp directory to clean up tempfiles for Sentinel Ingest

- app-frontend/src/app/components/map/annotateToolbar/annotateToolbar.controller.js
- app-frontend/src/app/components/scenes/sceneImportModal/sceneImportModal.controller.js
- app-frontend/src/app/components/scenes/sceneImportModal/sceneImportModal.html
- app-frontend/src/app/components/tools/diagramContainer/diagramContainer.html
- app-frontend/src/app/pages/projects/list/list.html
- app-frontend/src/assets/styles/sass/_shame.scss
Changes 'x of y tools' to 'x of y project' on project list view
Stop creating shapes when user finishes bulk annotation creation
Fix diagram jumping when dragging over lab controls
* Verify that the project list view now says "x of y projects" instead of tools
* Verify that when finishing bulk annotation, it cancels draw mode
* Verify that when panning the lab diagram and your mouse goes over the zoom controls, it no longer causes the view to jump
* Verify aborting / retrying in scene upload modal
- If all uploads complete, move to next modal view. Otherwise, require manual intervention
- Aborting removes a file from …
> UI fixes for project list view, bulk annotations, and lab panning

- app-frontend/src/app/pages/lab/browse/tools/tools.html
Because we use a tool's title to display a link to a tool, if a tool had no title, there was no link to click. This PR displays 'Untitled tool' instead of nothing in this case.
Trivial. Merging.
Closes #2658
> Display 'Untitled tool' on tool page instead of blank

- app-backend/tile/src/it/resources/application.conf
- app-backend/tile/src/main/scala/Router.scala
- app-backend/tile/src/test/scala/auth/AuthSpec.scala
- nginx/etc/nginx/conf.d/tiler.conf
Remove the `/tiles` prefix from tile server routes. Now Tiles are served from the `https://${TILE_SERVER_LOCATION}` as opposed to `https://${TILE_SERVER_LOCATION}/tiles`
N/A
* Run `scripts/update`.
* Start the app and attempt to display a project. Tile requests should fail.
* Change `TILE_SERVER_LOCATION` to `http://localhost:9101` (no trailing `/`)
* Restart the app, load a project, and ensure tiles are being served correctly. 
Closes #1471 
Needs azavea/raster-foundry-deployment# (TBD)
> Serve tiles from service root instead of /tiles

- nginx/etc/nginx/conf.d/tiler.conf
Currently, nginx redirects requests to `/tiles` to `$scheme://$http_host/$request_uri`. This _should_ let tile requests over HTTP and HTTPS be routed using the desired protocol, but on Staging all requests seem to be redirected to use http. To fix, this PR explicitly sets the protocol for the redirect based on `HTTP-X-FORWARDED-PROTO`.
* In development, set the `.env` file's `TILE_SERVER_LOCATION` to `http://localhost:9101/tiles` and run `scripts/server`. Ensure that requests to …
> Redirect requests for /tiles to tile service root

- app-frontend/src/app/pages/projects/edit/exports/new/new.controller.js
On starting an export, we were assuming that a tool was being used. When an export was started while using non-tool processing options (natural-color, raw, and color-corrected) these assumptions caused us to attempt a `null` -> `Object` cast, which results in an error.
Exports for tool-based processing options will not work until #2666 is merged.
* Try to export using a non-tool processing option. It should work.
> Fix project export - don't assume a tool is being used

- app-frontend/src/app/pages/projects/edit/advancedcolor/adjust/adjust.controller.js
- app-frontend/src/app/pages/projects/edit/advancedcolor/adjust/adjust.html
This PR initializes color correction values to sane defaults.
* Go to `projects/edit/projectID/advancedcolor/adjust`
* Turn on "Sigmoidal Contrast", "Color Balance", "Saturation"
* See if the defaults are set as 1 for sliders and input boxes
Closes #2654
> Initialize Color Correction Values to Sane Defaults

- app-frontend/src/app/components/common/navBar/navBar.module.js
- app-frontend/src/app/components/exports/exportDownloadModal/exportDownloadModal.html
- app-frontend/src/app/components/histogram/channelHistogram/channelHistogram.html
- app-frontend/src/app/components/projects/projectSelectModal/projectSelectModal.html
- app-frontend/src/app/components/scenes/sceneList/sceneList.html
- app-frontend/src/app/pages/error/error.html
- app-frontend/src/app/pages/imports/datasources/list/list.html
- app-frontend/src/app/pages/lab/browse/templates/templates.html
- app-frontend/src/app/pages/lab/browse/tools/tools.html
- app-frontend/src/app/pages/projects/detail/detail.html
- app-frontend/src/app/pages/projects/detail/exports/exports.html
- app-frontend/src/app/pages/projects/detail/scenes/scenes.html
- app-frontend/src/app/pages/projects/edit/colormode/colormode.controller.js
- app-frontend/src/app/pages/projects/edit/colormode/colormode.html
- app-frontend/src/app/pages/projects/list/list.html
- app-frontend/src/app/pages/settings/tokens/api/api.html
- app-frontend/src/app/pages/settings/tokens/map/map.html
- app-frontend/src/app/services/projects/colorCorrect.service.js
- app-frontend/src/assets/styles/sass/_shame.scss
Fetch all color corrections for project when loading colormode view, then selectively overwrite just the required properties for each
Disable sidebar while everything is loading
Add animations to all loading icons
* Verify that if you set separate color corrections for each scene in a project, changing the color mode will preserve the separate settings.
* Verify that the sidebar is disabled while loading all color mode info
* Verify that loading icons are now animated
Closes #2653
> Fix colormode overwriting color corrections

- app-frontend/package.json
- app-frontend/src/app/components/projects/annotateSidebarItem/annotateSidebarItem.controller.js
- app-frontend/src/app/components/projects/annotateSidebarItem/annotateSidebarItem.html
- app-frontend/src/app/components/projects/annotateSidebarItem/annotateSidebarItem.scss
- app-frontend/src/app/index.module.js
- app-frontend/src/app/index.vendor.js
- app-frontend/yarn.lock
This PR fixes the annotation name's selection issue during autocomplete, since angucomplete-alt is being a brat when you don't want to select any autocomplete options but it still selects one for you if you hover and click elsewhere.
* Go to annotation page.
* Create annotations, check if it gives autocomplete options correctly and lets you select the options you want.
Closes #2611
> Create new label name autocomplete for annotations

- docs/swagger/spec.yml
@aaronxsu and I paired on this one.
All endpoints return GeoJSON. 
All annotation endpoints are nested under the projects endpoint, as we don't foresee annotations existing outside of the project context.
- `GET` all of the annotations belonging to a project
- `POST` a new annotation
We think this should be paginated (at least by default) as the number of annotations for a single project could be _very_ large. This will require clients to intelligently navigate the paging mechanism to display all annotations, but we think this is preferable to returning an unknown number of annotations.
- `GET` a single annotation
- `PUT` an update of a single annotation
- `DELETE` an annotation
An annotation has the following fields:
- `label`: string
- `description`: string
- `machineGenerated`: boolean …
> Annotation API Spec

- app-frontend/src/app/components/tools/nodeStatistics/nodeStatistics.controller.js
- app-frontend/src/app/components/tools/nodeStatistics/nodeStatistics.html
- app-frontend/src/assets/styles/sass/_shame.scss
This PR:
- makes numbers in node statistics right-aligned
- forces these numbers to have same number of decimal places with no commas
* Go to the lab and configure tool inputs.
* Open the statistics of the function node and check if they are right-aligned and all have 5 decimal places with no commas, no matter integers or decimals
Closes #2651
> Fix node stats number alignment, decimal places, and commas

- app-frontend/src/app/pages/projects/list/list.html
- app-frontend/src/assets/styles/sass/app.scss
- app-frontend/src/assets/styles/sass/components/_result-stats.scss
Adds a dedicated SCSS component for Result Stats ('Showing 1-2 of 2 projects'). This improves the semantics of the markup, which previously treated these as paragraphs. 
Also cleans up an issue where these stats were displayed even when a user had zero projects.
* Navigate to the Projects view
* Remove all of your projects or somehow get an instance with no projects to verify that the `result-stats` don't appear
* Examine markup and SCSS for new result-stats component
> Add result stats component, fix glitch

- app-backend/api/src/main/scala/feed/Routes.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/QueryParameters.scala
- app-frontend/config/webpack/global.js
- app-frontend/config/webpack/overrides.js.template
- app-frontend/src/app/pages/home/home.html
- app-frontend/src/app/services/common/feed.service.js
- docs/swagger/spec.yml
Feed endpoint now takes a source parameter, defaulting to blog.rasterfoundry.com
Feeds must be links to publications - not users.
* Verify that the normal feed works
* Verify that changing the feed in the overrides file to something like `https://brightthemag.com/latest?format=json` works
Closes #2684
> Add source parameter to feed endpoint

- app-backend/database/src/main/scala/com/azavea/rf/database/tables/ToolRuns.scala
Right now we do not have a concept of organizations in Raster Foundry so filtering to organizations means that users can see everyone else's analyses. This PR switches the restriction to "owner" so that only owner tool runs show up.
* Go to the "Tools" section of the UI and you should only see tool runs created by your user
> Restrict tool run query to owners

- app-frontend/config/webpack/global.js
- app-frontend/src/app/pages/home/home.controller.js
- app-frontend/src/app/pages/home/home.html
This PR adds a configuration object to `app-frontend/config/webpack/global.js` to allow customization of help links.
* Try the help links on the home page and make sure they work as intended
* Try overriding these settings or changing them in the global file, restart webpack, and see that the changes are reflected in the UI
Closes #2720
> Add `HELPCONFIG` to allow configuring help links

- app-backend/batch/src/main/scala/com/azavea/rf/batch/export/spark/Export.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/OutputDefinition.scala
- docker-compose.spark.yml
- worker-tasks/Dockerfile
Only prepend slash to url when it's a dropbox export
Make running spark-submit jobs easier / fix permissions error for aws config
```
root@39f5e6c2ecca:/var/lib/spark# spark-submit --class com.azavea.rf.batch.export.spark.Export --driver-memory 2G /opt/rf/jars/rf-batch.jar -j s3://rasterfoundry-development-data-us-east-1/export-definitions/3cf7ac36-059a-4f4d-9b42-6b0ab3024b86.json
2017-11-21 15:13:23,969 [main] WARN  org.apache.hadoop.util.NativeCodeLoader -  Unable to load native-hadoop library for your platform... using builtin-java classeswhere applicable
[Stage 0:> …
```
> Fix s3 exports

- app-backend/batch/src/main/scala/com/azavea/rf/batch/export/spark/Export.scala
Export process was re-projecting to web Mercator, and polygons were already in it.
* Verify that exports clipped using a polygon no longer fail
Example run:
```
docker-compose -f docker-compose.spark.yml build spark-driver && docker-compose -f docker-compose.spark.yml run spark-driver --class com.azavea.rf.batch.export.spark.Export --driver-memory 2G /opt/rf/jars/rf-batch.jar -j s3://rasterfoundry-development-data-us-east-1/export-definitions/0c763dd9-0973-42d8-a316-d0cedf6808d6.json
```
Closes https://github.com/raster-foundry/raster-foundry/issues/2705
> Fix exports clipped using a polygon

- app-backend/api/src/main/resources/application.conf
- app-backend/api/src/main/scala/uploads/Credentials.scala
- app-backend/api/src/main/scala/uploads/Routes.scala
- app-backend/api/src/main/scala/utils/Config.scala
- app-backend/build.sbt
- app-backend/project/Dependencies.scala
- app-backend/project/Version.scala
This PR removes use of the Auth0 delegation endpoint and uses the STS API to retrieve limited scope credentials for interaction with S3.
~- [x] Styleguide updated, if necessary~
~- [x] Swagger specification updated, if necessary~
~- [x] Symlinks from new migrations present or corrected for any new migrations~
* Hit the `/uploads/<uploadid>/credentials` endpoint with a GET and see that credentials are returned as before.
> Use STS to retrieve S3 credentials

- app-backend/api/src/main/scala/uploads/Credentials.scala
- app-backend/api/src/main/scala/uploads/Routes.scala
This bug was introduced when switching over to OIDC for uploads; the auth
parameters should have been extracted from the header and not a query parameter
which is how it was before.
* Spin up development environment and upload a local file through the project creation workflow
> Extract token from header instead of parameter

- app-backend/batch/src/main/resources/application.conf
Fixes issue where edits to the batch jar were not being picked up because the
jar used in spark was hardcoded for export jobs.
Closes #2741
> Use batch jar path environment variable for export jobs

- app-frontend/src/app/services/auth/auth.service.js
Uses window location instead of the API url within the auth service.
* build (`yarn run build`)
* start dev server (`yarn run start`)
* serve from a different URL (you can use https://github.com/indexzero/http-server for this: `http-server dist -P http://localhost:9091 -p 8082`)
* try logging in
> Fix `getBaseUrl` in authService to use current location

- app-backend/common/src/main/scala/cache/CacheClient.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/MapTokens.scala
- app-backend/tile/src/main/scala/directives/TileAuthentication.scala
From the issue:
There is a regularly encountered issue in the cache client where we do not capture all cases in a [match](https://github.com/raster-foundry/raster-foundry/blob/develop/app-backend/common/src/main/scala/cache/CacheClient.scala#L66) statement. Part of this stems from being flippant about when options can be encountered and not. This task is to change the signature and use `Option` everywhere to help ensure every case is accounted for.
It will be hard to verify that this actually resolves the problem since it was not consistent across all environments.
* Get tiles for a project at a bunch of zoom levels …
> Explicitly use options in cache client

- app-backend/api/src/main/scala/toolrun/Routes.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/fields/ToolRunFields.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/sort/ToolRunFieldsSort.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/ToolRuns.scala
- app-frontend/src/app/components/common/sortingHeader/sortingHeader.html
- app-frontend/src/app/components/common/sortingHeader/sortingHeader.js
- app-frontend/src/app/index.components.js
- app-frontend/src/app/pages/lab/browse/tools/tools.html
- app-frontend/src/app/pages/lab/browse/tools/tools.js
- app-frontend/src/app/pages/projects/edit/edit.html
- app-frontend/src/assets/styles/sass/_shame.scss
Adds sorting by `name`, `createdAt`, and `modifiedAt` fields to the tool-run list endpoint (`GET /api/tool-runs`).
This is done via the `sort` query parameter. Ex: `sort=createdAt,asc`
This also adds sorting to the front-end tool-run listing UI.
* Start up the server
* Send an header-authorized request to `http://localhost:9091/api/tool-runs?page=0&pageSize=10&sort=modifiedAt,asc`
* See that the sorting makes sense
* Try some other sorting
* Use the front-end to sort
Closes #2754 
Closes #2637
> Add sorting to tool-runs

- app-frontend/src/app/components/aoiFilterPane/aoiFilterPane.controller.js
- app-frontend/src/app/components/exports/exportItem/exportItem.controller.js
- app-frontend/src/app/components/map/mapContainer/mapContainer.controller.js
- app-frontend/src/app/components/projects/projectCreateModal/projectCreateModal.controller.js
- app-frontend/src/app/components/projects/projectItem/projectItem.controller.js
- app-frontend/src/app/components/projects/projectPublishModal/projectPublishModal.controller.js
- app-frontend/src/app/components/scenes/sceneDetailModal/sceneDetailModal.module.js
- app-frontend/src/app/components/scenes/sceneFilterPane/sceneFilterPane.controller.js
- app-frontend/src/app/components/scenes/sceneList/sceneList.controller.js
- app-frontend/src/app/components/settings/tokenItem/tokenItem.controller.js
- app-frontend/src/app/components/tools/classifyNode/classifyNode.module.js
- app-frontend/src/app/components/tools/inputNode/inputNode.module.js
- app-frontend/src/app/index.run.js
- app-frontend/src/app/pages/home/home.controller.js
- app-frontend/src/app/pages/imports/datasources/detail/detail.controller.js
- app-frontend/src/app/pages/imports/imports.controller.js
- app-frontend/src/app/pages/lab/browse/templates/templates.js
- app-frontend/src/app/pages/lab/navbar/navbar.controller.js
- app-frontend/src/app/pages/lab/tool/tool.js
- app-frontend/src/app/pages/projects/edit/aoi-parameters/aoi-parameters.controller.js
- app-frontend/src/app/pages/projects/edit/browse/browse.controller.js
- app-frontend/src/app/pages/projects/edit/edit.controller.js
- app-frontend/src/app/pages/projects/edit/scenes/scenes.controller.js
- app-frontend/src/app/pages/projects/list/list.controller.js
- app-frontend/src/app/pages/projects/navbar/navbar.controller.js
- app-frontend/src/app/pages/settings/connections/connections.controller.js
- app-frontend/src/app/pages/settings/tokens/api/api.controller.js
- app-frontend/src/app/pages/settings/tokens/map/map.controller.js
- app-frontend/src/app/services/common/modal.service.js
- app-frontend/src/app/services/services.module.js
This PR adds a modal service that manages the state of modals across the application. This allows for some simpler flows when it comes to using modals.
The service has two main methods: `open` and `closeActiveModal`.
**`open(modalConfig, closeActive = true)`**
This is used exactly like the original call to `$uibModal.open`. Calling the method through the service allows the service to keep track of the modal. By default this closes any other active modal. Passing `false` to `closeActive` keeps any currently open modal open.
**`closeActiveModal()`**
This dismisses the active modal.
We can now leverage this service to globally close any modal on location change, which eliminates the remnant modal problems when the user hits back with a modal open, or is forced to logout when a modal is open. …
> Create modal service to centralize modal state

- app-frontend/src/app/pages/lab/browse/tools/tools.html
- app-frontend/src/app/pages/lab/browse/tools/tools.js
This PR uses local storage to persist the sort order of analyses so that user's can have their preferences maintained. The username is included in the key so that the setting won't cross over user accounts if they are using the same browser.
* Change the sorting of the analyses
* Navigate away and then come back to the analysis listing
* Check that the analyses are still sorted in the same way
> Store analysis sort order in local storage

- app-backend/common/src/main/scala/cache/CacheClient.scala
This PR fixes an error that occurred when reading NODATA tiles from the cache (stored in the cache as `None`s).
This will change the format of cached objects will create errors
* Request a tile that should be NODATA within the bounds of the project
> Fix caching to avoid cached NODATA tile errors

- app-backend/api/src/main/scala/project/Routes.scala
- app-backend/common/src/main/scala/AWSBatch.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Projects.scala
* Update modifiedAt date when marking scenes for ingestion
* Re-ingest scenes if they are added to a project, it's been more than a day
since they were last updated, and they are not already ingested
It's not clear why some of our batch submissions are not going through, these logs will let us know if there's an exception being thrown
* verify the stuff compiles
Related to https://github.com/azavea/raster-foundry-platform/issues/189
Closes https://github.com/azavea/raster-foundry-platform/issues/204
> Log errors when batch submitJob fails

- app-backend/batch/src/main/scala/com/azavea/rf/batch/Main.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/stac/ReadStacFeature.scala
Stub out batch jar cli for reading Stac asset
*  build your batch jar `cd app-backend` `./sbt` `batch/assembly`
* run the stubbed command `java -cp batch/target/scala-2.11/rf-batch.jar com.azavea.rf.batch.Main read_stac_feature This is a list of arbitrary arguments that I expect to be returned in a console log`
* verify that the output is as expected
Closes https://github.com/raster-foundry/raster-foundry/issues/2749
> Stub out batch jar cli for reading Stac asset

- app-backend/api/src/main/resources/application.conf
- app-backend/tile/src/main/resources/application.conf
This PR explicitly sets the log-level for the tile-server to `INFO`
* Spin up the server and make some tile requests: there shouldn't be any `DEBUG` level log output
Closes #2794
> Explicitly set tile-server log level to `INFO`

- app-frontend/src/app/pages/projects/edit/browse/browse.controller.js
- app-frontend/src/app/services/map/gridLayer.service.js
This PR adds a param to grid layer creation that will disable the requests to the scene grid endpoints.
This enables us to keep the grid visible for filtering but disable the scene count portion of the functionality.
* Browse for imagery and notice that the grid is present but that no scene totals are requested or displayed.
> Add param to generate empty grid layer

- app-backend/batch/src/main/resources/application.conf
- app-backend/batch/src/main/scala/com/azavea/rf/batch/sentinel2/ImportSentinel2.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/util/conf/Config.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Scenes.scala
Modifies the batch import to handle separating the Sentinel 2A and 2B datasources.
* `batch/assembly` in sbt
* `java -cp /opt/raster-foundry/jars/rf-batch.jar com.azavea.rf.batch.Main import_sentinel2 <YYYY-MM-DD>`
Closes #2786
> Modify importer to separate Sentinel-2A and 2B scenes

- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Scenes.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/ScenesToProjects.scala
Prior to this commit uningested scenes would be added to the mosaic definition
and the tile server would throw an error in response, failing to render tiles
that _were_ ingested but intersected with an uningested scene.
Tiles loaded in PR, no errors in tile server
* Open a project with an uningested scene on develop
* Add an uningested scene in the same project
* Browse over it, observe errors
* Switch to this branch, see that there are no errors, reload page -- observe no errors
Closes #2473
> Use ingest status filter when constructing mosaics

- app-frontend/package.json
- app-frontend/src/app/components/map/mapContainer/mapContainer.controller.js
- app-frontend/src/app/pages/projects/edit/edit.module.js
- app-frontend/src/app/services/map/mapUtils.service.js
- app-frontend/yarn.lock
This PR adjust some of the timing logic around map intialization. It isn't perfect, but it does eliminate the map initialization errors we see (#2797).
This also upgrades our Leaflet version.
We still need to examine this process and try remove the reliance on timeouts.
For the fitting work-around
* Browse to a project within the edit
* Reload the browser and see that the map gets fit properly.
For the Leaflet upgrade
* Use the various maps within the app and see that everything works as expected.
> Workaround for map init timing

- app-frontend/src/app/pages/lab/analysis/analysis.js
- app-frontend/src/app/pages/lab/browse/analyses/analyses.html
- app-frontend/src/app/pages/lab/browse/analyses/analyses.js
- app-frontend/src/app/redux/actions/node-actions.js
- app-frontend/src/app/services/analysis/analysis.service.js
- app-frontend/src/assets/styles/sass/_shame.scss
This PR alters the lab map controls to use redux actions so that changes made with these controls are properly persisted in the redux store.
This PR also adds in a button for each analysis on the listing page (on hover) that allows users to delete a particular analysis.
For the lab map redux actions
* Open an analysis and preview a node
* Using the map controls, start a comparison
* Change an analysis parameter (like band selection) and see that the comparison in maintained.
* Do other things with the lab map controls to ensure they work as expected
For the analysis deletion:
* Make sure you can now delete an analysis …
> Use redux actions for lab map and allow deletion of analyses

- app-backend/api/src/main/scala/project/Routes.scala
Fixes an issue where scenes were only being kicked off sometimes for users when
adding scenes to a project
* Start Server, ensure no errors are thrown when adding scene to a project
Closes #2817 
This is pretty trivial, going to merge once tests pass
> Add new fix for kicking off ingests when new scenes added to project

- app-tasks/Dockerfile
- app-tasks/rf/src/rf/commands/ingest_scene.py
- docker-compose.yml
Adds the ability to ingest scenes with a spark local cluster in development by adding a new option an including spark in the batch docker container.
* Find a scene ID for a local scene in development
* Rebuild the batch container
`docker-compose build batch`
* Ensure that batch assembly jar has been built
```
./scripts/console api-server ./sbt
project batch
assembly
```
* Run local ingest `rf ingest-scene --ignore-previous --local <scene-id>` (don't need to wait for it to finish, but should at least start)
> Add spark local ingest option to `rf`

- app-frontend/src/app/components/scenes/sceneImportModal/sceneImportModal.controller.js
- app-frontend/src/assets/styles/sass/components/_form.scss
This PR fixes the import modal to allow exiting the modal after a Planet import.
This also fixes the styles for checkboxes to use the new iconfont.
We need to adjust the `toggle` component to handle the new iconfont and styling. The checkmarks are appearing next to the boxes. The `toggle-old` component which we are using in some places now works as before.
* Do a planet import and see that you can exit the modal after
* Try out some checkboxes on the scene browser
Closes #2824 
Closes #2801
> Planet import fix, checkbox update for icomoon

- app-tasks/rf/src/rf/commands/ingest_scene.py
- app-tasks/rf/src/rf/uploads/sentinel2/settings.py
Adds Sentinel-2B id to ingest settings and checks against all sentinel ids in ingest processing.
> Check for all sentinel datasource ids in ingest process

- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Projects.scala
Prior to this commit sometimes scenes would not be returned for scenes to insert
because the query would happen before scenes were updated in the database.
I'm not sure this is really testable -- I tried to introduce the race condition using `Thread.sleep` at various spots on develop + this branch and was unable to reproduce the problem. The best example I have is a set of logs from staging that show the problem manifesting itself on develop and not when this branch was deployed to test it out.
This first screenshot shows the number of scenes added vs number of scenes being kicked off for ingest processing to not be …
> Remove race condition for ingest queuing

- app-backend/api/src/main/scala/user/Auth0User.scala
- app-backend/api/src/main/scala/user/Routes.scala
- app-backend/batch/src/main/resources/application.conf
- app-backend/batch/src/main/scala/com/azavea/rf/batch/Main.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/notification/Notification.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/util/conf/Config.scala
- app-backend/build.sbt
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Scenes.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/ScenesToProjects.scala
- app-backend/project/Dependencies.scala
- app-backend/project/Version.scala
- app-tasks/rf/src/rf/commands/ingest_scene.py
This PR adds a step to the ingest process that gathers the consumers and owner of the ingested scene to send notifications to them.
* in the sbt console `batch/assembly`
* find a scene id that is in multiple projects (or just one if you want)
* in the batch container run `java -cp /opt/raster-foundry/jars/rf-batch.jar com.azavea.rf.batch.Main notify_ingest_status <scene id>`
Closes #2659
> Add notification step to ingest process with stubbed notifications

- app-frontend/src/app/components/projects/projectCreateModal/projectCreateModal.controller.js
- app-frontend/src/app/components/scenes/sceneImportModal/sceneImportModal.controller.js
This PR ensures that the `finishUpload` method, which sets the proper upload status and allows interruptions, is called after all types of uploads complete.
This also adjusts the modal parameters to disable the clicking outside of the modal to exit during the import process since I was able to accidentally do this multiple times  (the cancel button still works).
* Make sure dev tools are open to capture requests
* Try each sort of import (local, s3, and planet) and ensure that a PUT request that sets the status to `UPLOADED` is made after the upload/import is completed. Also make sure that you can exit the modal …
> Consistently use upload completion method

- app-frontend/src/app/components/map/annotateToolbar/annotateToolbar.module.js
On the annotation page, this PR allows dragging map when creating polygons without adding new nodes to the polygon.
* Go to annotation page.
* In the middle of creating a polygon, try dragging the map - see if this adds a new node to the map or not.
Closes #2813
> Allow map drag when drawing polygonal annotations w/o adding new nodes

- app-frontend/src/assets/styles/sass/base/_grid.scss
Long project names were breaking the layout on wide screens. This sets a maximum width to ensure the project list items do not extend beyond the page.
* Create a project with a very long name (try 200 characters minimum)
* Set browser width to 1201px or wider
* Check to see if the layout breaks (see screenshot above)
Closes #2812
> Fix project list when project name is long

- app-frontend/src/app/pages/projects/edit/scenes/scenes.html
The trash icon was confusing to users. It suggested that the scene could be permanently deleted from Raster Foundry. We want to be clear that the user will remove the scene from their project.
* Open a project
* Look at the scenes
* Does it look appropriate? "Remove" a good label?
Closes #2827
> Remove 'trash' buttons from Scenes list

- app-frontend/src/app/components/scenes/sceneFilterPane/sceneFilterPane.html
- app-frontend/src/assets/styles/sass/_imports.scss
- app-frontend/src/assets/styles/sass/components/_searchselect.scss
The custom imagery sources dropdown had a few style issues. There was not a caret to incidate a dropdown. The clear button was not a proper circle.
I created a new SCSS component "search-select". It seems like we should move in the different of treating this like a reusable component.
I think there are some other enhancements that are needed. For example, I think it would be more clear if we showed a pointer instead of text cursor on hover. But those changes will require a larger collaboration with a developer. This fixes the immediate issues.
* Go to Browse Scenes view
* Open filter panel
* Take a look at the Imagery sources element
Closes #2650
> Fixes style issues with imagery sources dropdown

- app-frontend/src/app/components/colorComposites/colorSchemeDropdown/colorSchemeDropdown.html
- app-frontend/src/app/pages/projects/edit/colormode/colormode.html
- app-frontend/src/assets/styles/sass/_imports.scss
- app-frontend/src/assets/styles/sass/_shame.scss
- app-frontend/src/assets/styles/sass/base/_base.scss
- app-frontend/src/assets/styles/sass/components/_button.scss
- app-frontend/src/assets/styles/sass/components/_gradient-bar.scss
- app-frontend/src/assets/styles/sass/components/_gradient-dropdown.scss
Some style and frontend cleanup for the gradient dropdown.
I needed to restyle the other dropdowns in the Color Mode view to match to appropriate style for the gradient dropdown. All of the dropdowns were set up as button groups, but they were not using the button group functionality. I simplified these into single buttons.
* Make sure to look at the gradient dropdown on both the Color Mode view and in the lab
Closes #2842
> Clean up gradient dropdown style

- app-frontend/src/app/components/scenes/planetSceneDetailModal/planetSceneDetailModal.controller.js
- app-frontend/src/app/components/scenes/sceneFilterPane/sceneFilterPane.controller.js
- app-frontend/src/app/components/scenes/sceneItem/sceneItem.controller.js
- app-frontend/src/app/components/scenes/sceneItem/sceneItem.html
- app-frontend/src/app/pages/projects/edit/browse/browse.controller.js
This PR fixes issues in [a previous planet related PR](https://github.com/raster-foundry/raster-foundry/pull/2675) in terms of:
- Session storage for planet filters
- Planet scene display in the planet scene detail modal
- Debounce planet API calls
- Known issue 1: The image overlay does not seem to know how to plot a scene with multiple stripes, which corresponds to multipolygon tile footprint
- Known issue 2: planet API will respond 400 if the geometry filter crosses the prime meridian.
- Will rebase the commits in this PR once  [this previous planet related …
> Clean up planet filters and browsing

- .gitignore
- app-backend/batch/src/main/scala/com/azavea/rf/batch/stac/ReadStacFeature.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/util/package.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/fields/SceneFields.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Scenes.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/Scene.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/stac/Asset.scala
- docker-compose.yml
* Read a stac feature as geojson and create a scene from it
* Change scenes etc to use Projected[MultiPolygon] instead of Projected[Geometry]
since it's currently only enforced in the database
product.json: https://gist.github.com/Lknechtli/a176f0658c3d8447da9e51872633cb1d
feature.json: https://gist.github.com/Lknechtli/ea3363168512538935c459834ced6af1
in the api-server container, run
`/sbt batch/assembly && java -cp batch/target/scala-2.11/rf-batch.jar com.azavea.rf.batch.Main read_stac_feature -t --path file:///opt/raster-foundry/app-backend/feature.json --datasource c14c8e97-ba85-4677-ac9c-069cfef1f0b1`
in order to …
> Read stac feature from geojson and output scene

- Jenkinsfile
Use:
```
-f docker-compose.yml -f docker.compose.ci.yml
```
Both need to be specified, but override file is skipped.
See: https://docs.docker.com/compose/extends/
This is an attempt to consolidate some of the directives specified in multiple Docker Compose configuration files.
TBD
Depends on https://github.com/azavea/raster-foundry-deployment/pull/111
> Use combination of 2 Docker Compose configurations for CI

- app-backend/database/src/main/scala/com/azavea/rf/database/fields/ImageFields.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/fields/NameField.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/fields/OrganizationFkFields.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/fields/ProjectFields.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/fields/SceneFields.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/fields/ToolRunFields.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/fields/VisibilityField.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/sort/ImageFieldsSort.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/sort/NameFieldSort.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/sort/OrganizationFkSort.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/sort/ProjectFieldsSort.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/sort/SceneFieldsSort.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/sort/ToolCategoryFieldsSort.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/sort/ToolRunFieldsSort.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/sort/UserFieldSort.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/sort/VisibilitySort.scala
Fix sort order for scenes not being consistent between page requests if a block of scenes have the same acquisition date / created date by falling back to id
* Make a request to the scenes endpoint which results in a decent number of scenes
I used: `http://localhost:9091/api/scenes?bbox=-202.85156250000003,-28.76765910569124,18.808593750000004,67.87554134672945&dataRepo=Raster+Foundry&forProjectId=5801c9b1-1867-457a-a4e1-fd84cbbad289&maxCreateDatetime=2017-12-27T15:49:33.621Z&minCloudCover=0&pageSize=20&projectid=5801c9b1-1867-457a-a4e1-fd84cbbad289&sort=acquisitionDatetime,desc&page=0`
* Make another request for the …
> Fix sort order being indeterminate when objects have the same value

- app-frontend/src/app/services/scenes/datasource.service.js
Caches `get` requests for specific datasources on the frontend to prevent a ton of duplicate requests.
* Fire up server environment + frontend
* Go to browse and verify duplicate requests for the same datasource ID are cached
Closes #2863
> Cache datasource get requests

- app-backend/tile/src/main/scala/Router.scala
- app-backend/tile/src/main/scala/routes/ToolRoutes.scala
Add /tools/{uuid}/raw/?bbox={bbox}&zoom={int}&node={UUID} endpoint.
Bbox and zoom params are required, node is not
* Make a get request to 
`localhost:9101/tools/{{analysis uuid}}/raw/?bbox=-72.74242311716081,44.275545908552274,-72.73984014987947,44.27694396995378&zoom=18&token={token}`
This should return a  single band tif of the analysis with a bounding box that works for the default `Small flight import` project - try ndvi or something
Closes https://github.com/raster-foundry/raster-foundry/issues/2790
> Add a "raw" endpoint to render analyses as single band tifs

- app-frontend/src/assets/styles/sass/base/_grid.scss
- app-frontend/src/assets/styles/sass/components/_content.scss
We had implemented a `max-width` on the `.row` to fix https://github.com/raster-foundry/raster-foundry/issues/2812
While this fixed our layout issue, it introduced an unexpected bug for our **high-contrast theme** referenced here: https://github.com/azavea/raster-foundry-platform/issues/238
This PR removes the `max-width` from `.row` and puts it on our `.content` class. This is a much safer fix due to our limited use of `.content` throughout the app, whereas, `.row` is used in nearly every view of the application. 
**Before:**
**After:**
* Go to …
> Fixed a layout bug in high-contract theme introduced with #2852

- app-frontend/src/app/services/projects/project.service.js
This PR uses `API_HOST` from the build config to create the project export url.
* Make sure that a project export still works
* Override the API_HOST to use staging and see that the export request is POSTed there
> Use `API_HOST` for project export url

- app-frontend/src/app/components/histogram/nodeHistogram/nodeHistogram.html
- app-frontend/src/app/components/histogram/nodeHistogram/nodeHistogram.module.js
- app-frontend/src/app/redux/histogram-utils.js
Hide node histogram breakpoints until they are hovered
* Open the lab and view a non-input histogram
* Verify that the number inputs are hidden until you mouse over the breakpoint bar
Closes #2807
> Hide node histogram breakpoints until they are hovered

- app-tasks/rf/src/rf/uploads/geotiff/create_footprints.py
This commit removes some of the rasterio mask tiff creation that we had
previously been using and more closely mirrors some of the footprint generation
in `pystac`
*NAIP* - still works
*Potsdam* - before (didn't work)
*Potsdam* - after (does work)
* Remove existing batch container: `docker-compose rm batch`
* Rebuild container: `docker-compose build batch`
* Start servers
* Go through project creation process to import scens
* Identify upload id in the logs:
`api-server_1   | [info] 16:15:27.612 [ForkJoinPool-1-worker-1] WARN  com.azavea.rf.api.Main$ - Job Request: …
> Use gdal for footprint extraction

- app-frontend/src/app/pages/projects/edit/annotate/import/import.html
- app-frontend/src/app/pages/projects/edit/annotate/import/import.module.js
Allow selecting a default value when uploading annotations
Coerce description to a string to prevent api from complaining
Hide upload button once file has been selected
* Verify that you can select a default value instead of a geojson property when importing
* Verify that the upload button is hidden, and the import button is disabled instead of hidden when all required fields are not filled out
Closes https://github.com/raster-foundry/raster-foundry/issues/2870
> Handle edge cases when uploading annotations better

- app-backend/api/src/main/scala/datasource/Routes.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Datasources.scala
- app-frontend/package.json
- app-frontend/src/app/components/scenes/sceneFilterPane/sceneFilterPane.controller.js
- app-frontend/src/app/components/scenes/sceneFilterPane/sceneFilterPane.html
- app-frontend/src/app/index.module.js
- app-frontend/src/app/index.vendor.js
- app-frontend/src/assets/styles/sass/components/_filter.scss
- app-frontend/src/assets/styles/sass/components/_searchselect.scss
- app-frontend/yarn.lock
This PR adds the package `ui-select` and uses it to improve our datasource selection component. 
This PR also adds sorting to the datasources endpoint so that the dropdown can display datasources in abc order.
* `yarn install` (to get `ui-select`)
* with server running, try filtering by datasources when browsing
Closes #2855
> Use `ui-select` component for datasource filter on browse page

- app-frontend/src/app/components/common/navBar/navBar.html
- app-frontend/src/assets/styles/sass/theme/high-contrast/layout/_sidebar.scss
Fixes a styling issue in the high-contrast theme. On Project > Export > Output processing there was dark styling left over from the default theme.
* Open a project
* Go to exports
* Click on output processing
Closes #2857
> Styles project export's output sidebar for high-contrast theme

- app-frontend/src/app/pages/imports/datasources/detail/detail.html
- app-frontend/src/app/pages/imports/datasources/detail/detail.module.js
- app-frontend/src/app/pages/imports/imports.html
This PR adds band editing to the datasource details UI.
There is also a fix for the datasources link in the secondary nav-bar not being highlighted when you go to a datasource's detail view.
* Create a new datasource
* Add, remove, edit bands (saving them along the way) and make sure things persist
* Make sure cancelling edits works as expected
* Go to a datasource not owned by your user and make sure you can't edit the bands
Closes #2894
> Add band editing to datasource detail UI

- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/Annotation.scala
- app-frontend/src/app/pages/projects/edit/annotate/annotate.module.js
- app-frontend/src/app/pages/projects/edit/annotate/import/import.module.js
This PR removes the need for providing an `organizationId` when creating annotations. Instead, the owning organization is always assumed to be the same organization as the user.
* With the network tools open create some annotations and notice that they do not have `organizationId` as a property and that the server doesn't complain
Closes #2904
> Determine annotation organization from user

- app-frontend/src/assets/styles/sass/theme/high-contrast/components/_filter.scss
The layout and style of the selectize dropdown were broken in the high-contrast theme. This PR resolves those issues.
* Open a project
* Browse and filter
* Play with the datasources select
Closes #2907
> styling fix for high-contrast theme datasources filter dropdown

- app-backend/batch/src/main/scala/com/azavea/rf/batch/aoi/UpdateAOIProject.scala
Add stub for notifications to project AOI updates
```
root@a4c19aa20b71:/# rf update-aoi-project e3c1ec07-26d8-44f1-b6aa-b1ea8ba2ed99
17:44:02.755 [INFO ] c.z.h.HikariDataSource - HikariPool-1 - Started.
17:44:02.937 [INFO ] c.z.h.p.PoolBase - HikariPool-1 - Driver does not support get/set network timeout for connections. (Method org.postgresql.jdbc.PgConnection.getNetworkTimeout() is not yet implemented.)
17:44:03.191 [INFO ] c.a.r.d.ExtendedPostgresDriver -  >>> binding uuid -> java.util.UUID
17:44:03.192 [INFO ] c.a.r.d.ExtendedPostgresDriver -  >>> binding text -> java.lang.String
17:44:03.192 [INFO ] …
```
> Add notification stub to project AOI updates

- app-frontend/src/app/services/auth/auth.service.js
This should fix the issue where your jwt expires, then the login fails afterward.
In the future, we should redirect back to the page they were on
* Wait until your token expires and see if logging in again without reloading fails.
* not actually. Just merge this if it looks good, it shouldn't make the problem worse 
Closes #2815
> Adjust logout timer

- app-backend/api/src/main/scala/shape/Routes.scala
- app-backend/build.sbt
- app-backend/project/Dependencies.scala
- app-backend/project/Version.scala
- docs/swagger/spec.yml
- nginx/etc/nginx/conf.d/api.conf
This commit adds a new route (/api/shapes/upload/) that accepts a multipart form
upload with a zipfile in the "name" field for processing. This zipfile is
expected to contain a shapefile with at least one geometry. A shape will created
using the filename for the file uploaded. Users will have the opportunity to
adjust the name of the shape after upload if they desire to do so in the UI.
Support in GeoTrellis for parsing OGC WKT projections is not very complete -- currently GeoTrellis attempts to match the WKT string which can be kind of brittle. As a result, the endpoint added here makes the assumption that all uploads are in lat/lng. As GeoTrellis supports WKT parsing …
> Add Shapefile Upload Processing Route for Shapes API

- app-frontend/src/app/components/projects/projectItem/projectItem.html
- app-frontend/src/app/pages/projects/list/list.html
- app-frontend/src/assets/styles/sass/_imports.scss
- app-frontend/src/assets/styles/sass/components/_project-item.scss
- app-frontend/src/assets/styles/sass/pages/_dashboard.scss
- app-frontend/src/assets/styles/sass/theme/high-contrast/app.scss
- app-frontend/src/assets/styles/sass/theme/high-contrast/components/_project-item.scss
The project list page in the dashboard was starting to feel a but outdated with clumsy spacing and unnecessary dropdowns and details. This PR simplifies the project cards by removing superfluous details.
> UI revisions for the project list page

- app-backend/build.sbt
- app-backend/project/plugins.sbt
This follows a fix from other projects that have run into this issue where maven
central says it has the dependency (in this case JAI); however, all the links to
the actual files are incorrect. This fixes the problem by explicitly setting the
resolver order to one where the dependency is known to exist.
Testing this is kind of a pain because downloading dependencies from scratch on a local machine takes a while. The best test might be if the build for this PR succeeds - thus reviewing this PR might be limited to reviewing the code rather than functionality.
_If_ you desire to test this more fully, the best way to …
> Explicitly Order resolvers for Dependencies in `build.sbt`

- app-backend/database/src/main/scala/com/azavea/rf/database/tables/ScenesToProjects.scala
This commit adds more explicit scene ordering for projects. In cases where
`scene_order` was undefined the sort ordering was non-deterministic. This commit
adds an abstract sort method for `ScenesToProjects` queries that sorts by
`sceneOrder` and then the ID of the scene. In cases where `sceneOrder` is
defined then that will be used for sorting still.
* Make a `GET` request to: `http://localhost:9091/api/projects/3bc4ca13-d63e-4d62-ba22-363f28144ed2/order` and note the scene order is sorted alphabetically
* Make a `PUT` request to `http://localhost:9091/api/projects/3bc4ca13-d63e-4d62-ba22-363f28144ed2/order` with the …
> Add shared/consistent sorting for scene ordering in projects

- app-frontend/src/app/components/scenes/sceneItem/sceneItem.html
- app-frontend/src/app/components/scenes/sceneItem/sceneItem.module.js
- app-frontend/src/app/services/scenes/planetRepository.service.js
- app-frontend/src/app/services/scenes/rasterFoundryRepository.service.js
- app-frontend/src/app/services/vendor/planetLabs.service.js
- app-frontend/src/assets/styles/sass/_shame.scss
This PR allows indicating scene permissions on filtered scenes in the browser.
For Planet scenes - if they do not have download permissions, locked:
For Planet scenes - if they have download permissions, not locked:
For RF scenes - not locked:
* Deactivate the feature flags
* Go to scene browser
* Select RF data repo and browse scenes - they should not be locked
* Switch to Planet Labs repo and browse scenes - scenes within California may not be locked as users should have download permissions (per planet terms); scenes in other places may be locked.
Closes #2927
> Indicate Scene Permissions on Results in Browser

- app-tasks/rf/src/rf/uploads/geotiff/create_footprints.py
This PR makes a small change to the processing of the `gdal_polygonize.py` output to handle scenarios where there are multiple NODATA areas.
I tested the new method in a REPL with the output from the `gdal_polygonize` output manually. Not sure if there is a better approach here.
Closes #2975
> Update geotiff tile-footprint generation to handle multiple NODATA areas

- deployment/ansible/group_vars/all.yml
- deployment/ansible/group_vars/jenkins
- deployment/ansible/group_vars/jenkins.yml
- deployment/ansible/inventory/bastion
- deployment/ansible/inventory/jenkins
- deployment/ansible/roles.yml
- deployment/ansible/roles/raster-foundry.jenkins/tasks/main.yml
Instead of depending on `docker-gc`, use the built-in Docker commands for pruning stale containers and container images.
Also, update the AWS CLI, Jenkins (Ansible role), and default executor count.
Fixes https://github.com/azavea/raster-foundry-platform/issues/262
Navigate to the Ansible project directory and execute the following command with Ansible 2.4+:
```bash
$ ansible-playbook -vv -i inventory/jenkins raster-foundry-jenkins.yml
```
It should only cite one change (the `useSecurity` subtask).
> Use built-in Docker subcommands for cleanup

- app-backend/api/src/main/scala/uploads/Credentials.scala
This PR extends upload credential timeout from 15 minutes to an hour (max, restricted for AWS account owners, [read more here](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/securitytoken/model/GetSessionTokenRequest.html)).
Closes #2981
> Extend upload credential timeout to an hour

- deployment/ansible/roles/raster-foundry.jenkins/tasks/main.yml
Configure the docker prune cron job to run daily, instead of hourly. Addresses a race condition where images build in CI get pruned before they can be deployed. 
- [ x ] Styleguide updated, if necessary
- [ x ] Swagger specification updated, if necessary
- [ x ] Symlinks from new migrations present or corrected for any new migrations
- [ x ] PR has a name that won't get you publicly shamed for vagueness
Run `ansible-playbook` against Jenkins, ensure no changes are necessary aside from the `Disable security for login` task.
```bash
$ ansible-playbook -vv  -i deployment/ansible/inventory deployment/ansible/raster-foundry-jenkins.yml
```
Closes #XXX
> Docker cron-task should run daily

- app-backend/batch/src/main/scala/com/azavea/rf/batch/export/spark/Export.scala
This PR sets a default raster size for geotiffs export.
Closes #2931
> Set a default raster size for export

- app-backend/batch/src/main/scala/com/azavea/rf/batch/export/spark/Export.scala
- app-backend/batch/src/main/scala/geotrellis/spark/resample/ZoomResample.scala
This PR allows for overzooming when export `MultibandTileLayerRDD`s as GeoTiffs. With this new feature, it'll allow the exportation of layers even if the desired zoom level is greater than the max level of the layer.
This PR was not tested.
I don't have a testing environment setup, so I'm unable to test to see if this feature works. Someone else will need to test this.
> Overzooming for Multiband Export

- app-backend/api/src/main/scala/exports/package.scala
- app-backend/api/src/main/scala/project/Routes.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/export/spark/Export.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/ingest/spark/Ingest.scala
- app-backend/build.sbt
- app-backend/common/src/main/scala/S3.scala
- app-backend/database/src/main/scala/com/azavea/rf/database/tables/Annotations.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/Annotation.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/User.scala
- app-backend/project/Dependencies.scala
- app-backend/project/Version.scala
- docs/swagger/spec.yml
Add project annotations shapefile endpoint
Endpoint returns a redirect to a signed aws s3 link to a zipped shapefile collection
```
curl -L -X GET \
http://localhost:9100/api/projects/cf78c056-16dc-44fb-9bc9-ad7a276ee3db/annotations/shapefile \
-H 'Authorization: Bearer ${token}' \
-H 'Cache-Control: no-cache' \
--output annotations.zip
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   606  100   606    0     0   1446      0 --:--:-- --:--:-- --:--:--  1446
100  1589  100  1589    0     0   3197      0 --:--:-- --:--:-- --:--:--  3197
```
Discovered …
> Annotation shapefile export

- app-frontend/src/app/components/common/dropdown/dropdown.html
- app-frontend/src/app/components/common/dropdown/dropdown.module.js
- app-frontend/src/app/components/common/navBar/navBar.html
- app-frontend/src/app/components/settings/userModal/userModal.html
- app-frontend/src/app/index.components.js
- app-frontend/src/app/index.module.js
- app-frontend/src/app/index.routes.js
- app-frontend/src/app/pages/organization/metrics/metrics.html
- app-frontend/src/app/pages/organization/metrics/metrics.module.js
- app-frontend/src/app/pages/organization/organization.html
- app-frontend/src/app/pages/organization/organization.module.js
- app-frontend/src/app/pages/organization/settings/settings.html
- app-frontend/src/app/pages/organization/settings/settings.module.js
- app-frontend/src/app/pages/organization/teams/teams.html
- app-frontend/src/app/pages/organization/teams/teams.module.js
- app-frontend/src/app/pages/organization/users/users.html
- app-frontend/src/app/pages/organization/users/users.module.js
- app-frontend/src/assets/styles/sass/_imports.scss
- app-frontend/src/assets/styles/sass/components/_dropdown.scss
- app-frontend/src/assets/styles/sass/pages/_admin.scss
Create organization management routes
Create rough pages with styling for user management and teams
Nothing is hooked up, This is just the rough-in for the various pages and routes
* Verify that the routes work
* Verify that I didn't break dropdowns elsewhere in the app
* Verify that dropdowns for the users / teams work as expected
Closes #2964
> Create admin routes, with user management and team tabs roughed out

- app-frontend/src/app/components/scenes/sceneItem/sceneItem.html
- app-frontend/src/app/components/scenes/sceneItem/sceneItem.module.js
- app-frontend/src/app/index.vendor.js
- app-frontend/src/app/pages/projects/edit/edit.module.js
- app-frontend/src/app/pages/projects/edit/scenes/scenes.html
- app-frontend/src/app/pages/projects/edit/scenes/scenes.module.js
- app-frontend/src/app/services/projects/project.service.js
- app-frontend/src/assets/styles/sass/components/_list-group.scss
- app-frontend/src/assets/styles/sass/components/_tags.scss
This PR updates the following on the scenes page in a project:
- Make the order of scene items on the sidebar respect the real overlay sequence of scenes on the map
- Enable re-ordering of scenes by dragging scene sidebar item handles. The map reflects the new sequence.
The scene overlaid on others was the one in the middle. This reorders the scene so that it comes to the bottom of all scenes.
* Go to a project with overlaying scenes
* Check if the sidebar items reflect the true scene overlay sequence
* Re-order scene items and see if the map gets updated
* Make sure other pages using the scene item component that …
> Enable scene re-ordering in the UI

- app-frontend/config/webpack/global.js
- app-frontend/src/app/components/scenes/importList/importList.html
- app-frontend/src/app/components/scenes/importList/importList.module.js
- app-frontend/src/app/components/scenes/sceneItem/sceneItem.html
- app-frontend/src/app/components/scenes/sceneItem/sceneItem.module.js
- app-frontend/src/app/components/vectors/shapeItem/shapeItem.html
- app-frontend/src/app/components/vectors/shapeItem/shapeItem.module.js
- app-frontend/src/app/pages/projects/edit/advancedcolor/advancedcolor.controller.js
- app-frontend/src/app/pages/projects/edit/advancedcolor/advancedcolor.html
- app-frontend/src/app/pages/projects/edit/aoi-approve/aoi-approve.html
- app-frontend/src/app/pages/projects/edit/browse/browse.html
- app-frontend/src/app/pages/projects/edit/browse/browse.module.js
- app-frontend/src/app/pages/projects/edit/scenes/scenes.html
- app-frontend/src/app/pages/projects/edit/scenes/scenes.module.js
- app-frontend/src/assets/styles/sass/_shame.scss
- app-frontend/src/assets/styles/sass/components/_image.scss
Add previewable attribute to sceneItems
Add clickable attribute to sceneItems (just adds styling)
Fix some webpack path aliases
Adjust styling of sceneItem to make preview action more clear
Fix some classes being conditionally defined outside of an ng-class on the class property
* Verify that hovering scene thumbnails shows "Details" text, and clicking brings up the preview modal
* Verify that clicking the scene item in the views that allow selecting now selects the scene instead of bringing up the modal
* Verify that 
Closes https://github.com/raster-foundry/raster-foundry/issues/3006
> Preview scenes by clicking the thumbnail, select by clicking

- app-frontend/package.json
- app-frontend/src/app/components/scenes/sceneItem/sceneItem.html
- app-frontend/src/app/components/scenes/sceneItem/sceneItem.module.js
- app-frontend/src/app/pages/admin/platform/organizations/detail/detail.module.js
- app-frontend/src/app/services/scenes/planetRepository.service.js
- app-frontend/src/app/services/vendor/planetLabs.service.js
This PR:
- Fixes broken planet thumbnails.
- Deals with larger unit8arrays from planet thumbnail pngs since the resolution now is higher which resulted in `RangeError : Maximum call stack size exceeded` error in some cases using the original unit8arrays to string method.
- Stop click propagation on scene item details.
* Go to a project and browse scenes from planet repository.
* Check if thumbnails are displayed correctly on the sidebar, map, and detail modal map.
* Click on the detail button from scene sidebar, make sure it does not trigger scene selection.
Closes [raster-foundry-platform issue …
> Fix broken planet thumbnails.

- app-frontend/src/app/pages/share/share.controller.js
This PR uses logo in `BUILDCONFIG` on the share page.
* Go to `/share/projectid` and see if it the logo specified in `BUILDCONFIG` shows up (`raster-foundry-logo.svg` in our case)
Closes #3049
> Use BUILDCONFIG logo on share page

- app-frontend/src/app/components/scenes/sceneDetailModal/sceneDetailModal.html
- app-frontend/src/app/components/scenes/sceneDetailModal/sceneDetailModal.module.js
- app-frontend/src/app/components/scenes/sceneItem/sceneItem.html
This PR updates acquisition display to use UTC on scene detail modal and on scene item.
* Go to a project and check if dates on scene item display and scene detail modal match what are returned from the request (all should be in UTC).
Closes #3052
> Change acquisition date display to UTC

- Vagrantfile
- app-backend/db/src/main/scala/com/azavea/rf/database/util/database.scala
This PR reverts a change to the Vagrantfile that increased the number of CPUs to four
and fixes where we get database settings.
* don't
* paired with @alkamin to confirm this works
> Revert unintentional changes to Vagrantfile and db settings

- app-backend/migrations/src/main/resources/application.conf
We accidentally removed some essential configuration for migrations. Somehow we didn't feel the effects of this until someone did a fresh setup thanks to caching.
Is there a cleaner way? Probably.
* Before checking out the PR, clear target directories and attempt `mg update` and `mg apply`. It should not work
* After checking this out and reloading the project, attempt `mg update` and `mg apply` again. It should work.
> Restore unintentionally removed migration config

- app-backend/tile/src/main/scala/image/MultiBandMosaic.scala
Going to merge once this passes, it's a trivial change that _actually_ disables the white-balance. This will resolve the mis-colored individual tiles which occurred after the doobie refactor.
> Disable white-balance correction

- app-backend/common/src/main/resources/reference.conf
- app-backend/common/src/main/scala/Config.scala
- app-backend/common/src/main/scala/cache/CacheClient.scala
- app-backend/tile/src/main/scala/directives/TileAuthentication.scala
This PR adds a quick eviction in-memory cache to the tile-server. This allows us to keep track of expensive operations so that we can prevent duplicate cache lookups from missing and repeating the same operations (at least some of the time).
This local cache sits in front of our memcached client and can be disabled independently.
In addition, this PR fixes an error that was occurring in the doobie refactored tile-authentication process by explicitly casting to the `visibility` PG enum.
There are two variables that may need to be tuned:
- the `AWAIT` time (currently 25ms)
- the eviction time (currently 30s after write) -- we'll need to be careful with this one to avoid a too large cache
~- [ ] …
> Add scaffeine local cache to tile-server to improve cache performance

- deployment/ansible/group_vars/all.yml
AWS templated push commands for ECR require a more recent version of the AWS CLI
than we install currently. To facilitate using the VM and keeping everyone's
versions of things consistent, we should upgrade to a version that understands
the commands in ECR push instructions.
* Try to `sudo pip install awscli=={the updated version}` inside the vm
* Afterward, try the AWS ECR `get-login` command in `View push commands` in ECR
* It shouldn't fail while complaining about not understanding `--no-include-email`
> Upgrade aws-cli version

- app-backend/db/src/main/scala/com/azavea/rf/database/ProjectDao.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/SceneWithRelatedDao.scala
This PR changes the math in calculating `hasNext` to be correct:
Consider a response with 100 results. If we asked for page 4, twenty scenes at a time, then the pages are:
- `0 -> [0, 20)`
- `1 -> [21, 40)`
- `2 -> [41, 60)`
- `3 -> [61, 80)`
- `4 -> [81, 100)`
so we know that there isn't actually a next page. However, `offset * limit + 1 = 4 * 20 + 1 = 81`, which is definitely less than 100, so we would have returned `true` for hasNext. That's a simple math error to fix, so this PR fixes it.
* list some scenes in a small enough area that the count is small (I've found that New Hampshire with default filters is pretty good for …
> Fix hasNext calculations for scenes

- app-frontend/src/app/components/projects/projectPublishModal/projectPublishModal.html
- app-frontend/src/app/components/projects/projectPublishModal/projectPublishModal.module.js
- app-frontend/src/app/pages/projects/edit/sharing/sharing.html
- app-frontend/src/app/pages/projects/edit/sharing/sharing.module.js
- app-frontend/src/assets/styles/sass/_shame.scss
- app-frontend/src/assets/styles/sass/components/_button.scss
- app-frontend/src/assets/styles/sass/theme/high-contrast/components/_button.scss
This PR enables showing a check mark on the copy button when an URL exists and is successfully copied to the clip board.
* Go to the sharing page of a project and copy share links
* Go to the project list page, open the project share modal, copy the share links
Closes #3062
> Enable copy confirmation on sharing buttons

- app-frontend/src/app/services/scenes/rasterFoundryRepository.service.js
This PR enables getting all paginated datasources upon scene browse.
* Go to browse scenes in a project
* Check if all datasources are listed in the filer pane.
Closes #3106
> Get all paginated datasources upon scene browse

- app-backend/api/src/main/scala/Router.scala
- app-backend/api/src/main/scala/team/Routes.scala
- app-backend/api/src/main/scala/team/package.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/Team.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/TeamDao.scala
**This is a PR against the `feature/platforms` branch.**
This PR adds data model, DAO, and routes for teams.
Will write property tests for this PR when pairing on #3077 
**Updates on April 4th:**
SQL snippet for creating the team table for testing purposes:
```sql
CREATE TABLE teams (
id UUID PRIMARY KEY NOT NULL,
created_at TIMESTAMP NOT NULL,
created_by VARCHAR(255) REFERENCES users(id) NOT NULL,
modified_at TIMESTAMP NOT NULL,
modified_by VARCHAR(255) REFERENCES users(id) NOT NULL,
organization_id UUID REFERENCES organizations(id) NOT NULL,
name text NOT NULL,
settings …
```
> [Platforms] Add team datamodel, dao, and routes

- app-backend/build.sbt
- app-backend/datamodel/src/test/scala/com/azavea/rf/datamodel/implicits/Generators.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/BandDao.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/ImageDao.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/SceneDao.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/SceneWithRelatedDao.scala
- app-backend/db/src/test/scala/com/azavea/rf/database/BandDaoSpec.scala
- app-backend/db/src/test/scala/com/azavea/rf/database/ImageDaoSpec.scala
- app-backend/db/src/test/scala/com/azavea/rf/database/PropTestHelpers.scala
- app-backend/db/src/test/scala/com/azavea/rf/database/UserDaoSpec.scala
- app-backend/project/Dependencies.scala
This PR adds property tests for image and band database interactions that aren't tested by inserting scenes (to avoid duplicative testing).
I discovered a few weird behaviors in running these tests that I opened issues for or will just note here:
- `ingestSizeBytes` has a pretty low max because it's just an int (#3137)
- there's no REST API information that would help someone understand why inserting an image without bands would fail (#3136)
- `circe`'s `arbitrary[Json]` generation is garbage and I couldn't figure out how to configure it to make it not produce values that make …
> Add property tests for band and image daos

- app-backend/api/src/main/scala/scene/Routes.scala
- app-backend/api/src/main/scala/uploads/Routes.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/aoi/FindAOIProjects.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/landsat8/ImportLandsat8C1.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/sentinel2/ImportSentinel2.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/BandDao.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/SceneDao.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/SceneWithRelatedDao.scala
- docker-compose.yml
This PR includes changes to Daos to facilitate getting the batch subproject working. On this branch, Landsat 8 import, Sentinel 2 import, ingest, and finding AOI projects are all confirmed working. Processing uploads is untestable locally because something is wrong with fetching temporary AWS credentials. Exports and updating AOI projects are untested for separate reasons, see notes.
The goal of merging this is to get scheduled import jobs functioning again, rather than to be done fixing the batch subproject.
- ~PR has a name that won't get you publicly shamed for vagueness~
This task turned out to be "Track down a bunch of SQL …
> Progress toward working async workflows

- app-backend/api/src/main/scala/Router.scala
- app-backend/api/src/main/scala/platform/Routes.scala
- app-backend/api/src/main/scala/platform/package.scala
- app-backend/common/src/main/scala/CommonHandlers.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/Platform.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/PlatformDao.scala
- app-backend/db/src/test/scala/com/azavea/rf/database/PlatformDaoSpec.scala
Note that this is a PR against the platform branch.
This PR adds a datamodel, DAO, DAO tests, and routes for platforms.
You'll need this sql snippet, which is in place of making a migration. We'll need to formulate a plan to address migrations on our long running feature branches.
```sql
CREATE TABLE platforms (
id UUID PRIMARY KEY NOT NULL,
created_at TIMESTAMP NOT NULL,
created_by VARCHAR(255) REFERENCES users(id) NOT NULL,
modified_at TIMESTAMP NOT NULL,
modified_by VARCHAR(255) REFERENCES users(id) NOT NULL,
name TEXT NOT NULL,
settings JSONB NOT NULL default '{}'
);
```
* Run the above SQL manually
* Make sure it …
> [Platforms] Add platform datamodel, DAO, DAOSpec, and Routes

- app-backend/api/src/main/scala/project/Routes.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/AnnotationDao.scala
- app-frontend/src/app/pages/projects/edit/annotate/export/export.html
- app-frontend/src/app/pages/projects/edit/annotate/export/export.module.js
- app-frontend/src/app/services/projects/project.service.js
This PR:
* updates backend support for annotation export as zipped shapefile
* enables frontend to export project annotations as geojson or zipped shapefile
* fixes a backend bug so that project id filter is applied when getting project specific annotations
~Styleguide updated, if necessary~
~[Swagger specification](https://github.com/raster-foundry/raster-foundry-api-spec) updated~
~Symlinks from new migrations present or corrected for any new migrations~
* Check in your annotation and non-annotation projects and see if annotations are in the correct projects
* In a project with annotations, check to see if you can download them in either geojson or shapefile format, load them in GIS software/tool to make sure the data are correct 
Closes #3117 and #3118
> Annotation export as shapefile and project annotation api bug fix

- app-backend/build.sbt
- app-backend/datamodel/src/test/scala/com/azavea/rf/datamodel/implicits/Generators.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/ProjectDao.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/SceneDao.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/SceneWithRelatedDao.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/UserDao.scala
- app-backend/db/src/test/scala/com/azavea/rf/database/AnnotationDaoSpec.scala
- app-backend/db/src/test/scala/com/azavea/rf/database/AoiDaoSpec.scala
- app-backend/db/src/test/scala/com/azavea/rf/database/DBTestConfig.scala
- app-backend/db/src/test/scala/com/azavea/rf/database/ExportDaoSpec.scala
- app-backend/db/src/test/scala/com/azavea/rf/database/MapTokenDaoSpec.scala
- app-backend/db/src/test/scala/com/azavea/rf/database/ProjectDaoSpec.scala
- app-backend/db/src/test/scala/com/azavea/rf/database/PropTestHelpers.scala
- app-backend/db/src/test/scala/com/azavea/rf/database/ThumbnailDaoSpec.scala
- scripts/test
This PR adds property tests and fixes for bugs discovered while adding property tests for the `ProjectDao`.
There's a `DO NOT MERGE` commit in here for explicitly running migrations before scala tests
execute. I'd like to figure out how to handle that appropriately and have added a checklist item in #3134 
to get rid of or refactor that step. It's included here to prove / verify that ProjectDao tests work in CI.
A separate PR will address unrelated testing failures
* CI
> Add property tests for ProjectDao methods

- app-backend/datamodel/src/test/scala/com/azavea/rf/datamodel/implicits/Generators.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/SceneDao.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/ThumbnailDao.scala
- app-backend/db/src/test/scala/com/azavea/rf/database/PropTestHelpers.scala
- app-backend/db/src/test/scala/com/azavea/rf/database/ThumbnailDaoSpec.scala
This PR adds property tests for the ThumbnailDao
* CI
> Add property tests for ThumbnailDao

- app-backend/datamodel/src/test/scala/com/azavea/rf/datamodel/implicits/Generators.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/SceneDao.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/ShapeDao.scala
- app-backend/db/src/test/scala/com/azavea/rf/database/PropTestHelpers.scala
- app-backend/db/src/test/scala/com/azavea/rf/database/ShapeDaoSpec.scala
This PR adds property tests for the ShapeDao.
I rebased the anchor branch on develop because there were merge conflicts so there are some unrelated changes here -- safe to focus on the ShapeDaoSpec and Generators changes
* CI
> Add property tests for ShapeDao

- app-backend/datamodel/src/test/scala/com/azavea/rf/datamodel/implicits/Generators.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/AoiDao.scala
- app-backend/db/src/test/scala/com/azavea/rf/database/AoiDaoSpec.scala
- app-backend/db/src/test/scala/com/azavea/rf/database/PropTestHelpers.scala
- app-backend/migrations/src_migrations/main/scala/103.scala
This PR adds AoiDao property tests and fixes two bugs -- one was related to deletes, which weren't
filtering to AOIs a user could see. The other was related to creating AOIs, which was failing to thread
through the actual ID of the created AOI properly.
* CI
> Add AoiDao property tests

- Jenkinsfile
When a branch is prefixed with `/test`, treat it similarly to how we treat `develop` now.
In addition, simplify the expressions used to match `release/` and `hotfix/` branches.
Resolves https://github.com/azavea/raster-foundry-platform/issues/250
See: http://jenkins.staging.rasterfoundry.com/job/Raster%20Foundry/job/raster-foundry/job/test%252Fhmc%252Fdeploy-on-test-prefix/2/
Review Jenkins build output and ensure that none of the conditions were altered in the process of condensing multiple conditions into one regular expression.
> Trigger deployment stages of build for branches prefixed with /test

- app-backend/db/src/main/scala/com/azavea/rf/database/SceneDao.scala
- app-backend/db/src/test/resources/logback-test.xml
- app-backend/db/src/test/scala/com/azavea/rf/database/SceneDaoSpec.scala
This PR adds property tests for the SceneDao. It also tells geotrellis vector WKT logging to chill out. It also fixes a bug or two about updating scenes. See the notes.
Update behavior was a little odd. There are three fields that weren't update-able that I feel like at least maybe should be:
- `ingest_location` -- we have to be able to set this. It's necessary. This was definitely a bug.
- `tile_footprint`/`data_footprint` -- we might miscalculate these and want to provide correction later
- `metadata_files` -- I can imagine users wanting to provide this for scenes that they upload …
> Add scene dao tests

- .github/PULL_REQUEST_TEMPLATE.md
Trivial.
Adds an item to our PR checklist to ensure we don't forget to use the `BUILDCONFIG.APP_NAME` variable in our templates.
> Add checklist item to PR template for APP_NAME templating

- app-backend/datamodel/src/test/scala/com/azavea/rf/datamodel/implicits/Generators.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/ProjectDao.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/SceneWithRelatedDao.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/util/Page.scala
- app-backend/db/src/test/scala/com/azavea/rf/database/SceneWithRelatedDaoSpec.scala
This PR adds property tests for the `SceneWithRelatedDao`
I discovered in the process that json aggregation with no results from a related table becomes a `null` rather than an empty array -- I captured fallout from that in #3163 with more description of why that's bad.
I also realized that our return from adding scenes to a project is odd, which I captured in #3170.
* Pay special attention to the logic in the test for scenes to ingest -- I believe that it correctly expresses what we want to happen, and it matches what _does_ happen, but it's the messiest part of the tests
* CI
> Add SceneWithRelatedDao property tests

- app-backend/db/src/main/scala/com/azavea/rf/database/filters/Filterables.scala
This change removes a clause in a filter that allowed users to see anything within their organization.
Better sharing granularity is a concern for the platforms feature.
* Can you list projects that aren't owned by you (you shouldn't be able to)
Closes #3095
> Fix user filter - Don't default to organizational sharing

- app-frontend/src/app/pages/settings/organizations/organizations.module.js
Another module accidentally conflicted with the ProfileController.
Trivial, merging once CI passes.
Closes #3183 
Closes #3068
> Fix accidental angular module conflict - ProfileController

- app-backend/api/src/main/scala/project/Routes.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/AoiDao.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/Dao.scala
- app-backend/db/src/test/scala/com/azavea/rf/database/AoiDaoSpec.scala
This PR adjusts the base Dao `page` method to handle overriding the fragments used for selection and counting which allows more complex queries (such as joins) to be paged.
This method is then used to ensure that project AOIs can be listed and paged.
* Create an AOI project
* Select 'Browse for Imagery'
* See that the controls for AOI parameters are visible
* See that a request to the aoi endpoint resulted in a paged response
Closes #3182
> Fix listing of project AOIs

- app-backend/db/src/main/scala/com/azavea/rf/database/util/Page.scala
This PR makes a small fix for an issue that appears when a page request using a sorting of `DESC`. Our method of combining ordering fragments ended up sending a non-interpolated sql string to the database, so it contained a `?` instead of the interpolated sort direction.
* Hit the 'Data' tab of the UI, the scenes should load
Closes #3199
> Fix page ordering when `DESC`

- app-backend/.jvmopts
- app-backend/project/build.properties
- app-backend/sbt
Attempt to suppress Scapegoat OOM errors by:
- Updating `sbt` to the most recent patch release
- Updating `sbt-extras` script to its most recent version
- Increasing maximum heap size for the `sbt` JVM
When executing the `sbt-extras` script at the root of the top level `app-backend` directory, use `ps` to ensure that its default JVM options are being overridden:
```bash
$ cd app-backend
$ ./sbt compile
```
As that's running, use another terminal session to execute `ps`:
```bash
$ ps aux | grep …
```
> Attempt to suppress Scapegoat OOM errors

- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/AccessControlRule.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/ActionType.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/ObjectType.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/SubjectType.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/AccessControlRuleDao.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/Dao.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/UserGroupRoleDao.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/meta/EnumMeta.scala
- app-backend/db/src/test/scala/com/azavea/rf/database/AccessControlRuleDaoSpac.scala
- app-backend/db/src/test/scala/com/azavea/rf/database/UserGroupRoleDaoSpec.scala
This PR adds data-models for:
- `ObjectType`
- `SubjectType`
- `ActionType`
- `AccessControlRule`
It also adds a DAO and DAO spec for the access control rules.
Necessary SQL (in addition to anchor branch SQL):
```sql
CREATE TYPE object_type AS ENUM ('PROJECT', 'SCENE', 'DATASOURCE', 'SHAPE', 'WORKSPACE', 'TEMPLATE', 'ANALYSIS');
CREATE TYPE subject_type AS ENUM ('ALL', 'PLATFORM', 'ORGANIZATION', 'TEAM', 'USER');
CREATE TYPE action_type AS ENUM ('VIEW', 'EDIT', 'DEACTIVATE', 'DELETE');
CREATE TABLE access_control_rules (
id UUID PRIMARY KEY NOT NULL,
created_at TIMESTAMP NOT NULL,
created_by VARCHAR(255) REFERENCES users(id) NOT NULL,
modified_at TIMESTAMP NOT NULL,
modified_by VARCHAR(255) REFERENCES users(id) NOT NULL,
is_active BOOLEAN DEFAULT true NOT NULL,
object_type object_type NOT …
```
> [Platforms] Add datamodels, DAO, and spec for access-control-rules

- app-tasks/Dockerfile
This assists troubleshooting efforts by including tools like `jmap` and `jstack` directly in the container image. Currently, the JRE does not make these tools available.
The image size difference between the two is roughly 40MB (244MB to 205MB).
Resolves https://github.com/azavea/raster-foundry-platform/issues/290
Ensure that `cibuild` completes successfully.
> Use OpenJDK 8 JDK for Spark tasks

- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/User.scala
- app-backend/datamodel/src/test/scala/com/azavea/rf/datamodel/implicits/Generators.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/meta/CirceJsonbMeta.scala
This PR allows empty strings to be passed as Credentials.
* Run `db/tests` as generators were changed (or check CI)
* PUT a user object with empty credential strings and see that it succeeds -- the easiest way to do this might be through the UI... Settings -> Third Party Connections
Closes #3178
> Fix credential empty string handling

- app-frontend/src/app/components/scenes/sceneDetailModal/sceneDetailModal.module.js
This PR lets the scene detail modal persist under edit mode when acquisition date picker is opened.
* Go to Data -> Raster and view details of one of your uploaded scenes
* Edit the metadata and change the acquisition date -- the scene detail modal should persist after the date modal is opened.
Closes #3139
> Let scene detail modal persist when date picker modal is opened

- app-backend/batch/src/main/resources/log4j.properties
- app-backend/batch/src/main/resources/logback.xml
- app-backend/batch/src/main/scala/com/azavea/rf/batch/notification/Notification.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/LayerAttributeDao.scala
- app-tasks/rf/src/rf/commands/ingest_scene.py
This PR fixes a few miscellaneous bugs that were making ingests fail for different reasons.
- replaced use of `stdout=PIPE` with `Popen(...).communicate()` (usage of `PIPE` is [strongly discouraged](https://docs.python.org/2/library/subprocess.html#using-the-subprocess-module)
- fixed a sql bug in the notification job
- added conflict handling to the sql for writing layer metadata
- suppress some annoying logging
To pick a scene that's small enough to ingest locally, get the id from your database using:
```sql
select scenes.name, scenes.id from (scenes inner join datasources on scenes.datasource = datasources.id) where datasources.name = 'UAV - 3 Band';
```
I think they're both of an acceptably small size
* Give your vm 12gb of RAM
* Rebuild the batch jar
* bring up your server
* console …
> Fix Hanging postgres metadata write

- app-backend/build.sbt
- app-backend/common/src/main/scala/Rollbar.scala
- app-backend/project/Dependencies.scala
- app-backend/project/Version.scala
Instead of maintaining stacktrace assembly and reporting logic, depend on the Rollbar Java SDK to do it for us. Also, attempt to maintain the existing `RollbarNotifier` abstraction—just instantiate the SDK client inside of `RollbarNotifier`.
Update `ROLLBAR_SERVER_TOKEN` in `.env` and attempt to trigger a `sendError()` in the project.
To help make things easier, I generated Rollbar entries using this branch already, which you can inspect at:
- …
> Use Rollbar Java SDK for exception reporting

- scripts/test
This PR run `mg init` separately in testing setup and ignores errors if it fails (e.g., due to
`__migrations__` already existing in the db). The reason for running it separately is shared
`postgres` container state across develop builds, since it's off the same branch, which causes
the build to happen against a database that has already been initialized for forklift. The correct
solution is in #3230 but it's more time-consuming.
CI is pretty much guaranteed to pass on this branch except for unrelated issues, so the real test is against develop -- the testing instructions below replicate the `develop` branch build scenario, where migration initialization runs against an already-initialized database.
* Kill everything in `scripts/test` except updating scala deps, database prep, and running …
> Separately run mg init and ignore errors

- app-backend/datamodel/src/test/scala/com/azavea/rf/datamodel/implicits/Generators.scala
- app-backend/db/src/test/scala/com/azavea/rf/database/CategoryToTemplateDaoSpec.scala
- app-backend/db/src/test/scala/com/azavea/rf/database/DataSourceDaoSpec.scala
- app-backend/db/src/test/scala/com/azavea/rf/database/PropTestHelpers.scala
- app-backend/db/src/test/scala/com/azavea/rf/database/TagDaoSpec.scala
- app-backend/db/src/test/scala/com/azavea/rf/database/WorkspaceDaoSpec.scala
This PR adds property tests for `WorkspaceDao`
* `./scripts/console api-server ./sbt`
* `mg update`
* `mg apply`
* `project db`
* `testOnly *WorkspaceDaoSpec`
Closes #3207
> Add property test for WorkspaceDao

- app-backend/batch/src/main/scala/com/azavea/rf/batch/aoi/FindAOIProjects.scala
- app-tasks/rf/src/rf/commands/find_aoi_projects.py
This PR fixes a bad job submission bug where the python client tries
to submit an empty string as a project id.
The bug came from the refactor of the `find_aoi_projects` job. The specific content of the logging
output turned out to be important since the python client is doing string filtering on what it finds in
stdout, which I didn't notice when I refactored it originally.
* set all of the projects in your dev db to have `is_aoi_project = true`
* run `batch/assembly`
* throw an `info` statement into `find_aoi_projects_to_update`
* rebuild your `batch` container
* console in to your `batch` container
* `rf find-aoi-projects`
> Coordinate doobie output from find aoi projects and cli input

- app-backend/batch/src/main/scala/com/azavea/rf/batch/sentinel2/ImportSentinel2.scala
This PR explicitly stops the `ActorSystem` in both success and failure cases and fixes some
sql bugs in the Sentinel-2 import job.
* add a `.take(5)` to `getSentinel2Products`
* run `assembly` for the `batch` subproject
* count the scenes in your db
* run the the `import_sentinel2` job (the recursive key listing part takes more than a minute but it's necessary) for `2018-10-29` (because you shouldn't already have those dates in your db)
* count the scenes in your db again
* note that there are 5 more
Closes #3243
> Fix sql queries and stop actor system in Sentinel 2 import

- app-backend/api/src/main/scala/project/Routes.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/aoi/UpdateAOIProject.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/ProjectDao.scala
This PR adds ingest kickoffs after adding scenes to projects in updating AOIs and in
adding scenes to a project from a query.
The handling to kickoff ingests when adding scenes from query parameters is a little bit different from
the handling when posting IDs correctly. I _think_ it's the case that we don't want to send a failure
response on adding scenes to a project when we fail to kickoff ingests for those scenes. Possibly we do
though, since it means that users can't add scenes to a project without those scenes also having
ingests kicked off successfully. I'm not sure.
* ???
Closes azavea/raster-foundry-platform#218
> Kickoff ingests after adding scenes to projects everywhere

- app-backend/datamodel/src/test/scala/com/azavea/rf/datamodel/implicits/Generators.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/TeamDao.scala
- app-backend/db/src/test/scala/com/azavea/rf/database/PropTestHelpers.scala
- app-backend/db/src/test/scala/com/azavea/rf/database/TeamDaoSpec.scala
This PR adds property tests for `teamDao`.
* `mg update`, `mg apply`
* `./scripts/console api-server ./sbt`
* `project db`
* `testOnly *TeamDaoSpec`
Closes #3224
> [Platforms] Add property tests for teamDao

- app-backend/db/src/main/scala/com/azavea/rf/database/Dao.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/SceneWithRelatedDao.scala
This PR makes it so that loading the projects page doesn't fire off hundreds of scenes requests per project by default.
* Go to the projects list page
* Observe that you don't make hundreds of scenes requests
Closes #3266
> Fix excessive scene queries from hasNext

- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/Organization.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/UserGroupRole.scala
- app-backend/datamodel/src/test/scala/com/azavea/rf/datamodel/implicits/Generators.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/UserGroupRoleDao.scala
- app-backend/db/src/test/scala/com/azavea/rf/database/OrganizationDaoSpec.scala
- app-backend/db/src/test/scala/com/azavea/rf/database/PropTestHelpers.scala
- app-backend/db/src/test/scala/com/azavea/rf/database/UserGroupRoleDaoSpec.scala
This PR adds a platform to the database before adding an organization in OrganizationDao tests.
It uses that platform to prove we can insert organizations under new platforms.
...I'm not sure what else was supposed to happen here -- there wasn't too much going on that adding
the platform id seems like it would affect. Was there more to this card?
Also there's a commit in here from #3267 since there's stuff in there that I thought might be useful here. I'm not certain that's correct but feel free just to look at 7ce0ea2
* `testOnly *OrganizationDaoSpec`
Closes #3225 
Closes #3267
> Use a fresh platform in OrganizationDao tests

- app-backend/batch/src/main/resources/application.conf
- app-backend/batch/src/main/scala/com/azavea/rf/batch/export/CheckExportStatus.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/export/CommandLine.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/export/CreateExportDef.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/export/spark/Export.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/util/S3.scala
- app-backend/common/src/main/scala/AWSBatch.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/ExportDao.scala
- app-tasks/rf/src/rf/commands/export.py
This commit adjusts how exports are run by no longer relying on a permanent EMR cluster to be running. A few things happen here:
- Code to submit EMR jobs in the batch CLI is removed
- Code to run a local spark job is added to the `rf` client
- Export jobs now run in the "ingest" queue in AWS
- The location of job statuses is made more explicit
Some things are left for later tasks at this point:
- Status JSONs are still used, there is a little bit of infrastructure there that I did not want to …
> Use Spark Local for Exports

- app-backend/batch/src/main/scala/com/azavea/rf/batch/aoi/UpdateAOIProject.scala
- app-tasks/rf/src/rf/commands/update_aoi_project.py
This PR makes `update-aoi-projects` work.
It's probably the case that the python file didn't _need_ to change per se,
but I couldn't really see a reason to use `shell=True` and splitting it into the list
form made it more readable for me when I was making sure I was running the
right java command in testing.
* reassemble your batch jar and rebuild your batch container
* Bring up your server and frontend and make yourself a nice new AOI project
* Get that project's id
* `./scripts/console batch bash`
* `rf update-aoi-project <project id>`
Closes #3271
> Fix sql and bash cmd in update-aoi-projects

- app-backend/db/src/main/scala/com/azavea/rf/database/Dao.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/SceneWithRelatedDao.scala
This PR updates the base `Dao` to include a `ownerVisibilityFilterF` attribute, that filters on
ownership or public visibility.
This makes it so that scenes and datasources both respect public visibility, and so that nothing else
cares (nothing except datasources cared before). Per offline discussion, that's what we want -- everything is locked down basically except those two types of data, and finer-grained permissions
control will continue over on #3130 
* before pulling down this branch, set all of your scenes to private
* browse for some scenes
* observe that you see them, which is bad
* check out this branch
* do the same browse
* note that you don't see scenes anymore
* set all of your scenes to public
* query for some scenes
* ch-ch-ch-check 'em out
Closes #3274
> Fix scene visibility filtering

- app-tasks/Dockerfile
A new debian package release for python-pip seems to have broken the
install due to a missing install of python-requests. This fixes the
problem by explicitly installing requests.
Without this patch the following error is seen when trying to call `pip` at all:
```
Traceback (most recent call last):
File "/usr/bin/pip", line 9, in <module>
from pip import main
File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 21, in <module>
from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
ImportError: No module named requests.packages.urllib3.exceptions
```
~- [ ] Symlinks from new migrations present or corrected for any new …
> Install python-requests via apt to fix broken pip install

- app-backend/batch/src/main/scala/com/azavea/rf/batch/stac/ReadStacFeature.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/util/package.scala
This PR makes the batch jar's `read_stac_feature` command work. The problem with it
previously was that it didn't construct fully-qualified image source URIs, so ingests failed
when we tried to point to a local file.
* reassemble your batch jar
* `./scripts/console batch bash`
* make yourself a nice rgb datasource
* `java -cp /opt/raster-foundry/jars/rf-batch.jar com.azavea.rf.batch.Main read_stac_feature -p <a path in s3 to a stac feature json> -d <the id of the datasource you made>
* from the db, find the id of the scene you just created: `select id, name. created_at from scenes order by created_at desc limit 1;`
* ingest your scene (make sure your server is running): `rf ingest-scene --local --ignore-previous <your scene id>`
* navigate to the area where your scene is -- plopping the …
> Use correct image and thumbnail source uris

- app-backend/batch/src/main/scala/com/azavea/rf/batch/export/CreateExportDef.scala
This PR makes it so that exports know where their files live.
* Rebuild your batch jar
* Create an export
* Get your export id
* Run `rf export <export id>` in your batch jar
* Try to download your export
* Observe that you can
Closes #3293
> Update export definition on an export when we create it

- app-backend/api/src/main/scala/maptoken/Routes.scala
- app-backend/api/src/main/scala/project/Routes.scala
- app-backend/api/src/main/scala/scene/Routes.scala
- app-backend/api/src/main/scala/shape/Routes.scala
- app-backend/api/src/main/scala/tags/Routes.scala
- app-backend/api/src/main/scala/thumbnail/Routes.scala
- app-backend/api/src/main/scala/toolrun/Routes.scala
- app-backend/api/src/main/scala/tools/Routes.scala
- app-backend/api/src/main/scala/uploads/Routes.scala
- app-backend/api/src/main/scala/user/Auth0User.scala
- app-backend/api/src/main/scala/user/Routes.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/export/CreateExportDef.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/landsat8/ImportLandsat8C1.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/notification/Notification.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/AccessControlRuleDao.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/Dao.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/ExportDao.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/ImageDao.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/OrganizationDao.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/PlatformDao.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/ProjectDao.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/TeamDao.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/UserDao.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/UserGroupRoleDao.scala
- app-backend/db/src/test/scala/com/azavea/rf/database/DBTestConfig.scala
- app-backend/tile/src/main/scala/directives/TileAuthentication.scala
This PR does a few things so looking at it by commit would likely be best:
- 36965e7: cleans up our use of fragments in filters. We had a lot of manual ID lookups that could be replaced by the standard `id: UUID` filter. In addition, I added a method to the user DAO to lookup users by id `filterById(id: String)` to streamline user lookups by id.
- 4518be9: adds two authorization filters to the base DAO. One filter is by object type, intended for listing. The other is by object type and id, for verifying authorization of a single object. This commit also adds a convenience function for chaining together the typical sequence of methods for cleaner repeated use.
- 643a9f0: adds authorization checks to all project endpoints. This uses akka's `authorizeAsync` to make a call to the DB to verify …
> Add authorization to all project endpoints

- app-backend/batch/src/main/scala/com/azavea/rf/batch/export/spark/Export.scala
- app-backend/batch/src/main/scala/com/azavea/rf/batch/util/S3.scala
There was an issue with how credentials were being supplied once the
export moved away from EMR. This fixes the problem by using an S3
client directly for writes to S3.
* rebuild batch jar
* Go to project and create a new export
* run export in batch containter `./scripts/console batch "rf export <export-id-from-created-export>"
* Go to project export and file should be properly populated for download
Closes https://github.com/azavea/raster-foundry-platform/issues/302
> Use S3 client instead of hadoop writer for S3 exports

- app-backend/api/src/main/scala/organization/Routes.scala
- app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/UserGroupRole.scala
- app-backend/datamodel/src/test/scala/com/azavea/rf/datamodel/implicits/Generators.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/OrganizationDao.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/PlatformDao.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/TeamDao.scala
- app-backend/db/src/main/scala/com/azavea/rf/database/UserGroupRoleDao.scala
- app-backend/db/src/test/scala/com/azavea/rf/database/OrganizationDaoSpec.scala
- app-backend/db/src/test/scala/com/azavea/rf/database/PlatformDaoSpec.scala
- app-backend/db/src/test/scala/com/azavea/rf/database/TeamDaoSpec.scala
- app-backend/db/src/test/scala/com/azavea/rf/database/UserGroupRoleDaoSpec.scala
Adding a user more than once deactivates any actives roles for that groupId and
creates a new one with the specified role.
Removing a user deactivates any active roles for that groupId
Instead of updating roles, we deactivate the old role and create a new one to preserve an audit trail.
* Stuff should compile
* Verify that the queries make sense
* Verify that tests make sense
Closes #3282 
Closes #3284
> Implement addUser and removeUser dao functions for org and team
