app-backend/api/src/main/scala/datasource/Routes.scala
app-backend/db/src/main/scala/com/azavea/rf/database/DatasourceDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/TeamDaoSpec.scala

This PR:
- adds authorization to datasource endpoints
- deletes owner and visibility checks on datasources since we use access control rules now
- updates one test for `teamDao` since it seemed to fail on local testing
- Frontend may need to be changed a bit
* Run migrations if needed
* SQL to generate records for testing:
```sql
INSERT INTO teams VALUES (
'f53a67bb-2b0d-484a-90d9-115b78a2cd28',
NOW(),
'default',
NOW(),
'default',
'dfac6307-b5ef-43f7-beda-b9f208bb7726',
'Test team',
'{}'
);
INSERT INTO …
```

Add authorization to datasource endpoints

---

app-backend/batch/src/main/scala/com/azavea/rf/batch/ingest/spark/Ingest.scala
app-tasks/rf/src/rf/cli.py

When batch jobs fail without being able to update scene ingest status, they can
leave scenes stuck in ingesting forever. This change makes it so that on the
third attempt, the batch job exits early, before it can get to a state where it
might run out of memory or have some other fatal error.
* confirm the env variable matches the variable from https://docs.aws.amazon.com/batch/latest/userguide/job_retries.html
Closes azavea/raster-foundry-deployment#119
Closes #3176

Use AWS batch job attempt to fail early after retries

---

app-backend/db/src/main/scala/com/azavea/rf/database/SceneDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/SceneDaoSpec.scala

This prevents a scenario where retrying ingests can cause a large
number of jobs to be kicked off because the status was updated to
failed. This change makes it so that in cases where the status is
updated to failed we do not automatically kick off another job and
assume that manual intervention or external retries will handle the
failure.
I think testing should be optional for this because it's pretty small and there is a test to verify behavior ... but if you desire to test this
* Update a …

Disable Failed Retries for Ingests from API

---

app-backend/db/src/main/scala/com/azavea/rf/database/SceneWithRelatedDao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/filters/Filterables.scala

This PR pre-fetches the geometry for a shape ID filter when using shape IDs to filter scenes.
When using a subquery, postgres got confused and didn't know how to use the `data_footprint`
index to run a reasonably quick query. In fact it was not reasonably quick enough that the 
API was timing out :cry:. By pre-fetching the geometry, we help postgres not be confused.
There isn't really a local performance test that proves this will work in the wild. :man_shrugging: 
@notthatbreezy and I `EXPLAIN ANALYZE`d using a geom literal in the prod db to confirm that 
it would make the db use the index.
* draw a shape and use it to filter scenes to prove that I didn't ruin the sql
* CI
Closes #3307

Handle shape filters separately from other scene query params

---

app-tasks/Dockerfile

We previously removed Sid because of a package problem. That seems to have resolved itself on its own (this build should work fine). We didn't press the issue any harder because we were unaware of code that depended on GDAL 2.2.x, but we use new arguments for GDAL polygonize.
* `docker-compose build batch`
* `./scripts/console batch "gdalinfo --version"`
* Verify 2.2.4 is installed

Use Sid repositories for installing GDAL

---

app-backend/api/src/main/scala/project/Routes.scala
app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/AccessControlRule.scala
app-backend/db/src/main/scala/com/azavea/rf/database/AccessControlRuleDao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/ProjectDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/AuthorizationSpec.scala
app-backend/migrations/src_migrations/main/scala/207.scala

This PR adds endpoints for managing access to projects.
ACRs are immutable now :tada:, which also let us simplify the model some.
Here's an example post body you can send and edit for below:
```json
{
"actionType": "VIEW",
"subjectType": "ALL",
"subjectId": null,
"isActive": true
}
```
* login to your frontend and get a token
* find a project id you have access to
* `POST` the ACR above to `/api/projects/<id>/permissions`
* check out the permission that came back and confirm it matches what you created
* log in as a different user
* verify you can see the project
* `POST` another one, but with a different action type
* check out that you get both of them back
* `PUT` only one permission in a json list to the same endpoint
* verify that it's the only thing that comes back
* `GET` the same …

Add sharing endpoints to projects

---

app-backend/api/src/main/scala/platform/Routes.scala
app-backend/db/src/main/scala/com/azavea/rf/database/OrganizationDao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/PlatformDao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/TeamDao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/UserGroupRoleDao.scala

This PR addresses some small issues with the platform routes.
6922c12
This makes `userIsMember` of Team and Organization DAOs take cascading admin roles into account. For example, an admin role in a platform satisfies a check for membership of a child organization.
cb0f85a + 35a0a98
This enforces checks on platform level routes that the platform must exist.
09f292b
This makes listing of users within a group take the `is_active` flag of the `UserGroupRole` into account, only returning users with an active role.
1ec672b
We have not properly implemented delete methods (see issues #3282 and #3379). This removes any functionality that was incorrect in favor of code that will throw.
~- [ ] [Swagger …

Platform route cleanup

---

app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/UploadType.scala
app-frontend/src/app/services/scenes/cmrRepository.service.js

This PR makes mostly front-end changes that allow users to select MODIS scenes through CMR and add them to a project. Previously, only browsing the scenes was possible.
An upload object is created for each scene.
I'd like to get this merged to staging and do some tests there to make sure that datasource IDs are aligned.
* Browse MODIS scenes through the CMR repo
* Select some and add them to scenes
Closes #3318
Closes #3380

Allow adding MODIS scenes to projects

---

.gitignore

This is used with direnv
Trivial.

Update .gitignore to handle .envrc files

---

app-backend/api/build.sbt
app-backend/batch/src/main/scala/com/azavea/rf/batch/sentinel2/ImportSentinel2.scala
app-backend/batch/src/main/scala/com/azavea/rf/batch/util/S3.scala
app-backend/build.sbt
app-backend/project/Dependencies.scala
app-backend/project/Version.scala

This PR uses a `ParSeq` to fan out work for importing sentinel 2 scenes across cores.
This solution makes me kind of sad, but it works. It was supposed to be possible to `IO.shift *> otherIO`
our way to having whatever IO we wanted off the main thread. I was under the impression that that
would also allow us to shift IOs off of the shifted threads. That never really seemed to work. What
happened instead was that, when I shifted off the `main` thread, everything wound up running on the
same shifted thread. I'm not sure why that happened.
It may be time soon to look through Paul Cleary's scala pet store (https://github.com/pauljamescleary/scala-pet-store/blob/master/build.sbt) to get more familiarity with some of the things that work with the
fancier parts of the cats ecosystem, if we ever …

Better parallelize sentinel2 import

---

app-backend/build.sbt

This PR overrides the default max classfile name length for the scala compiler from 255 (probably) to 100. It's necessary for `cipublish` to succeed, probably.
* not really testable except in a develop branch cipublish, but:
* `./scripts/console api-server ./sbt`
* `project db`
* `test:compile`
* check the longest filename under `app-backend/db/target/scala-2.11/test-classes/com/azavea/rf/database/`
* it should be under 100

Set max classfile name length

---

app-backend/api/src/main/scala/platform/Routes.scala
app-backend/db/src/main/scala/com/azavea/rf/database/OrganizationDao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/UserGroupRoleDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/OrganizationDaoSpec.scala
app-frontend/src/app/components/settings/addUserModal/addUserModal.html
app-frontend/src/app/components/settings/addUserModal/addUserModal.module.js
app-frontend/src/app/pages/admin/admin.html
app-frontend/src/app/pages/admin/organization/users/users.html
app-frontend/src/app/pages/admin/organization/users/users.module.js
app-frontend/src/app/pages/admin/team/users/users.js
app-frontend/src/app/services/auth/organization.service.js

Allow platform admins to change a user's organization
* Create a platform admin
* Create a user under an organization in that platform
* Change the user's organization by making a `POST` request to `/api/platform/{platformId}/organizations/{newOrganizationId}/members` containing `{userId: <user id>, groupRole: <user role>}`
* Verify that the roles have been updated appropriately - old org roles are deactivated, and the new org role exists
* Verify that the created tests make sense
Closes #3405 
Closes #3406

Allow platform admins to change a user's organization

---

app-backend/api/src/main/scala/platform/Routes.scala
app-backend/datamodel/src/test/scala/com/azavea/rf/datamodel/implicits/Generators.scala
app-backend/db/src/main/scala/com/azavea/rf/database/AccessControlRuleDao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/OrganizationDao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/TeamDao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/UserGroupRoleDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/TeamDaoSpec.scala
app-frontend/src/app/pages/admin/organization/teams/teams.module.js
app-frontend/src/app/services/auth/team.service.js

Hook up all buttons in the action menu of the organization teams list: edit, add to team, and delete
* Give your user platform or org admin:
`insert into user_group_roles (id, created_at, created_by, modified_at, modified_by, is_active, user_id, group_type, group_id, group_role) values (uuid_generate_v4(), now(), 'default', now(), 'default', true, 'auth0|59318a9d2fbbca3e16bcfc92', 'PLATFORM', '31277626-968b-4e40-840b-559d9c67863c', 'ADMIN');`
* Create a new team under your organization and add …

Allow deactivating teams

---

app-frontend/src/app/pages/imports/datasources/list/list.html
app-frontend/src/app/pages/imports/raster/raster.html
app-frontend/src/app/pages/imports/raster/raster.module.js

This PR parameterizes app name on raster and datasource pages under data tab.
* Go to raster and datasources pages under data tab of the app -- check if "Raster Foundry" is still the app name.
* Apply custom `overrides.js` file and check the above two pages -- see if the app name changes to the designated name.
Closes #3410

Parameterize app name on raster and datasource pages.

---

app-frontend/src/app/components/settings/addUserModal/addUserModal.html
app-frontend/src/app/pages/admin/organization/teams/teams.html
app-frontend/src/app/pages/admin/organization/users/users.html
app-frontend/src/app/pages/admin/platform/organizations/organizations.html
app-frontend/src/app/pages/admin/platform/users/users.html
app-frontend/src/app/pages/admin/team/users/users.html
app-frontend/src/app/pages/admin/team/users/users.js

Fix user identifiers in a couple places
* Verify that places where users are shown, identifiers default to name, then fallback to email and finally ID
* Verify that the organization view's "add user" modal now mentions organizations instead of teams.
Closes #3445

Fix text in the organization add user modal

---

app-backend/batch/src/main/scala/com/azavea/rf/batch/landsat8/ImportLandsat8C1.scala

We previously assumed that recent scenes would be
at the top of the csv, so that if we had a run of several rows where the row's date was before the
start date, that indicated we were past the block of rows that we cared about. Sometime recently
though (who knows when), the order seems to have been flipped, so our threshold for rows before
the start date was always happening before we found any rows that we actually cared about. With this
PR, we now check for runs of scenes with dates _greater than the end date_. The downside is that
we now have to traverse the entire csv to get to the rows we care about.
This PR also borrows the eager insertion strategy from Sentinel-2 import, so that if anything goes
wrong we still get to insert some scenes.
Finally, it also gives up on calculating …

Eagerly insert scenes and flip csv date order

---

app-backend/api/src/main/scala/datasource/Routes.scala
app-backend/api/src/main/scala/project/Routes.scala
app-backend/api/src/main/scala/scene/Routes.scala
app-backend/api/src/main/scala/shape/Routes.scala
app-backend/api/src/main/scala/toolrun/Routes.scala
app-backend/api/src/main/scala/tools/Routes.scala
app-backend/db/src/main/scala/com/azavea/rf/database/AccessControlRuleDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/AuthorizationSpec.scala

This PR:
* adds methods in `AccessControlRuleDao` and objects' endpoints for listing user-specific actions on objects
* adds property tests for these new SQL (**Updated on Jun. 4th**)
* changes download scene action check from `VIEW` to `DOWNLOAD`
* Open a sql shell and do the following (**Updated on Jun. 4th**):
```sql
INSERT INTO 
access_control_rules
(id, created_at, created_by, is_active, object_type, object_id, subject_type, subject_id, action_type)
VALUES
(
'eae0b97a-72b1-449a-ab78-73065f66b302',
now(), …
```

Endpoints for listing user-specific actions on objects

---

app-frontend/src/app/components/settings/addUserModal/addUserModal.html
app-frontend/src/app/components/settings/addUserModal/addUserModal.module.js
app-frontend/src/app/components/settings/organizationModal/organizationModal.html
app-frontend/src/app/components/settings/organizationModal/organizationModal.module.js
app-frontend/src/app/components/settings/teamModal/teamModal.html
app-frontend/src/app/components/settings/teamModal/teamModal.module.js
app-frontend/src/app/pages/admin/organization/organization.module.js
app-frontend/src/app/pages/admin/organization/teams/teams.html
app-frontend/src/app/pages/admin/organization/teams/teams.module.js
app-frontend/src/app/pages/admin/organization/users/users.html
app-frontend/src/app/pages/admin/organization/users/users.module.js
app-frontend/src/app/pages/admin/platform/organizations/organizations.html
app-frontend/src/app/pages/admin/platform/organizations/organizations.module.js
app-frontend/src/app/pages/admin/platform/platform.module.js
app-frontend/src/app/pages/admin/platform/users/users.html
app-frontend/src/app/pages/admin/platform/users/users.module.js
app-frontend/src/app/pages/admin/team/users/users.html
app-frontend/src/app/pages/admin/team/users/users.js

This PR updates admin UI permissions and failure messages on platform, organization, and team pages.
~Marked as WIP since platform related pages have not been touched yet.~
**Updates on Jun. 4th:**
* Finish platform related pages and remove WIP tag
~Platform related pages have not been updated yet.~
* Log in as a dev user.
* In a sql shell, update dev user's roles in the public organization, Raster Foundry platform, teams, etc. in the `user_group_roles` table.
* Navigate …

Update admin UI permission and failure messages 

---

app-backend/api/src/main/scala/datasource/Routes.scala
app-backend/api/src/main/scala/project/Routes.scala
app-backend/api/src/main/scala/shape/Routes.scala
app-backend/api/src/main/scala/toolrun/Routes.scala
app-backend/api/src/main/scala/tools/Routes.scala
app-backend/batch/src/main/scala/com/azavea/rf/batch/aoi/UpdateAOIProject.scala
app-backend/db/src/main/scala/com/azavea/rf/database/AoiDao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/Dao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/MapTokenDao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/SceneWithRelatedDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/PropTestHelpers.scala

This PR moves auth logic into an `INNER JOIN` and out of a subquery.
New strings are exercised in the `SceneWithRelatedDaoSpec`
This still needs migrations.
* Log in to the app
* List projects
* Note that you see the correct projects and that you don't see a nice 400 line stack trace from invalid sql

Move authorization query to inner join

---

app-backend/api/src/main/scala/datasource/Routes.scala
app-backend/api/src/main/scala/platform/Routes.scala
app-backend/api/src/main/scala/project/Routes.scala
app-backend/api/src/main/scala/scene/Routes.scala
app-backend/api/src/main/scala/shape/Routes.scala
app-backend/api/src/main/scala/toolrun/Routes.scala
app-backend/api/src/main/scala/tools/Routes.scala
app-backend/api/src/main/scala/user/Routes.scala
app-backend/db/src/main/scala/com/azavea/rf/database/AccessControlRuleDao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/TeamDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/TeamDaoSpec.scala
app-frontend/src/app/components/permissions/permissionsModal.html
app-frontend/src/app/components/permissions/permissionsModal.module.js
app-frontend/src/app/components/scenes/importList/importList.module.js
app-frontend/src/app/index.components.js
app-frontend/src/app/services/auth/permissions.service.js
app-frontend/src/app/services/auth/user.service.js
app-frontend/src/app/services/services.module.js
app-frontend/src/assets/styles/sass/_shame.scss
app-frontend/src/assets/styles/sass/components/_form.scss

This PR adds a barebones, ugly, unstyled permissions modal for adding permissions to first-class objects. It handles:
It's ugly I know I know there are classes in place to target for styling I'm sorry it's so ugly right now.
More importantly:
it doesn't really respect the designs we have, for two reasons. The first is that we didn't know they
existed when I started. The second is that, since our permissions are non-hierarchical and require
support for context-sensitive types of actions (annotating projects, downloading scenes...), the
single permission dropdown didn't really make sense as a strategy for creating grants. There's 
more work to be done here to work out how we're going to get everything tied together, but
this is a first cut.
Also I'm not sure about the `CONFIRM` workflow -- …

Add first cut permissions modal

---

app-backend/api/src/main/scala/Router.scala
app-backend/api/src/main/scala/scene/Routes.scala
app-backend/api/src/main/scala/uploads/Routes.scala
app-backend/common/src/main/scala/Authentication.scala

Adds functionality that was accidentally rebased over
- Create a project
- Attempt to add MODIS scenes, should not fail
- Create a project
- Add a COG scene (use 4 band planetscope) when given the opportunity (remote: http://radiant-nasa-iserv.s3-us-west-2.amazonaws.com/2014/02/06/IP0201402061342550633S03899E/IP0201402061342550633S03899E-COG.tif)
- Browse project/scene - verify it has …

Add COG/MODIS upload handling

---

app-backend/api/src/main/scala/datasource/Routes.scala
app-backend/api/src/main/scala/scene/Routes.scala
app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/Datasource.scala
app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/Scene.scala
app-backend/db/src/main/scala/com/azavea/rf/database/DatasourceDao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/SceneDao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/SceneWithRelatedDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/DataSourceDaoSpec.scala
app-backend/db/src/test/scala/com/azavea/rf/database/SceneDaoSpec.scala
app-frontend/src/app/components/lab/inputNode/inputNode.module.js
app-frontend/src/app/components/scenes/sceneDetailModal/sceneDetailModal.html
app-frontend/src/app/components/scenes/sceneItem/sceneItem.html
app-frontend/src/app/components/scenes/sceneItem/sceneItem.module.js
app-frontend/src/app/pages/projects/edit/edit.module.js
app-frontend/src/app/services/scenes/rasterFoundryRepository.service.js
app-frontend/src/app/services/scenes/scene.service.js

This PR gets datasource names from a reduced datasource object on scenes and adds a
`/scene/<id>/datasource` endpoint for fetching a datasource using scene authorization.
This doesn't solve the problem of what happens if someone only transitively has permission to view
scenes through a project that's shared with them. I'm considering that out-of-scope for this issue.
Also this turned out to be underestimated, since we didn't appreciate the surface area of "where do
we need to get datasource permissions right?".
* Browse scenes and confirm you can still see scene datasources
* Try to run an analysis and note that you get datasources successfully without making a thousand requests for datasources
Closes azavea/raster-foundry-platform#335

Get more datasource information from scenes

---

app-backend/api/src/main/scala/scene/Routes.scala
app-backend/db/src/main/scala/com/azavea/rf/database/Dao.scala
app-frontend/src/app/components/permissions/permissionsModal.html
app-frontend/src/app/components/permissions/permissionsModal.module.js
app-frontend/src/app/components/projects/projectItem/projectItem.controller.js
app-frontend/src/app/components/projects/projectItem/projectItem.html
app-frontend/src/app/components/projects/projectPublishModal/projectPublishModal.html
app-frontend/src/app/components/scenes/importList/importList.module.js
app-frontend/src/app/pages/admin/admin.html
app-frontend/src/app/pages/admin/organization/users/users.html
app-frontend/src/app/pages/admin/platform/organizations/organizations.module.js
app-frontend/src/app/pages/admin/platform/users/users.html
app-frontend/src/app/pages/admin/team/users/users.html
app-frontend/src/app/pages/projects/edit/edit.html
app-frontend/src/app/pages/projects/edit/edit.module.js
app-frontend/src/app/pages/projects/edit/sharing/sharing.html
app-frontend/src/app/services/auth/permissions.service.js
app-frontend/src/assets/styles/sass/_shame.scss
app-frontend/src/assets/styles/sass/components/_modal.scss
app-tasks/rf/src/rf/ingest/sentinel2_ingest.py

This PR fixes what the permissions modal thinks `EVERYONE` means, scoping it
to the user's platform instead of to all users everywhere in the universe (possibly
even using DIFFERENT APPLICATIONS). It also fixes a duplication issue resulting
from how we constructed the auth query.
* list your rasters
* add some permissions
* for everyone!
* for specific entities!
* nothing should be weird
Helps with azavea/raster-foundry-platform#346

Fix creating EVERYONE permissions

---

app-frontend/src/app/components/permissions/permissionsModal.html
app-frontend/src/app/components/permissions/permissionsModal.module.js
app-frontend/src/app/services/auth/user.service.js
app-frontend/src/assets/styles/sass/base/_typography.scss

This PR gets subject name of ACR record based on id in the sharing modal
This is a pure frontend solution to let the modal display subject name instead of type + id.
* Make dev user an admin.
* Go to raster import page and click on the sharing modal button.
* Assign some permissions if you have not done so.
* Check if subject names are displayed instead of the types in the list of granted permission.
Closes #3457  (kind of...)
Closes …

Get subject name in sharing modal.

---

scripts/server

This PR adds a `--quiet` option to `scripts/server` that by default
only prints `api-server` logs instead of every log from every service since the beginning
of time and until the heat death of the universe. Logs from additional services can be
specified by passing service names as arguments after `--quiet`.
Example usage:
```bash
$ ./scripts/server --quiet
...
$ ./scripts/server --quiet nginx-api
```
I think the logs are too loud by a lot on startup, but this also solves a different problem, where you,
for example, want to restart the api server and don't want to kill everything else (like when
the db project has to recompile, and the tile server project doesn't need to care, and you just
want to leave that running, but you `scripts/server`ed and ctrl+c-ing that process will kill …

Add quiet option to scripts/server

---

app-frontend/src/app/components/common/navBar/navBar.controller.js
app-frontend/src/app/pages/admin/organization/organization.module.js
app-frontend/src/app/pages/admin/organization/teams/teams.html
app-frontend/src/app/pages/admin/organization/teams/teams.module.js
app-frontend/src/app/pages/admin/organization/users/users.html
app-frontend/src/app/pages/admin/organization/users/users.module.js
app-frontend/src/app/pages/admin/platform/organizations/organizations.html
app-frontend/src/app/pages/admin/platform/users/users.html
app-frontend/src/app/pages/admin/platform/users/users.module.js
app-frontend/src/app/pages/admin/team/team.html
app-frontend/src/app/pages/admin/team/users/users.html
app-frontend/src/app/pages/admin/team/users/users.js
app-frontend/src/app/services/auth/organization.service.js
app-frontend/src/app/services/auth/team.service.js
app-frontend/src/assets/styles/sass/components/_avatar.scss
app-frontend/src/assets/styles/sass/components/_dropdown.scss
app-frontend/src/assets/styles/sass/pages/_admin.scss

This PR does a bunch of things to polish the admin UI:
- allow platform admins to change organization logos
- remove headers as per design from various admin list pages
- remove non-functional elements — search on orgs, teams and various dropdown options
- use existing search component instead of plain inputs
- make team and org name links to those pages, remove ‘View page’ links and member count links (they went to the same place but the name was previously not a link)
- use a different icon for the dropdown (edit instead of a caret since the button has no text)
- make user avatars the same size whether or not an avatar is available, use existing placeholder class
- move header actions to the right as per design
- unify copy
- allow org and platform admins to change user roles on …

Various front-end cleanup items

---

app-tasks/rf/src/rf/ingest/sentinel2_ingest.py

This PR replaces references to `copied`, which we removed, with `scene`, which is what
we replaced it with.
* check ur python linter

Replace copied with scene

---

app-backend/api/src/main/scala/platform/Routes.scala
app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/User.scala
app-backend/db/src/main/scala/com/azavea/rf/database/OrganizationDao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/PlatformDao.scala

This PR limits the scope of when the API returns email addresses in user lists:
- if a user has proven commonality with the users they're listing, then emails are returned. This covers listing users in a non-default organization, or listing users in teams (see notes)
- if a user hasn't proven commonality with the users they're listing, then emails are not returned. This covers listing users in the default organization, and listing users in a platform
It isn't obvious what should happen with listing users in teams. A team of users not in the public org
can be created on that public organization, in which case, I have no idea what commonality that
proves. It might make sense not to allow creating teams on the public organization for that reason. I'm
not sure.
Also, there's a better …

Show emails only when user proves some commonality with others

---

app-frontend/src/app/pages/projects/edit/edit.module.js
app-frontend/src/app/services/map/map.service.js
docs/architecture/adr-0022-anti-meridian-artifacts.md

Fix warped scene footprints on the anti-meridian
While fixing this, I found a couple other issues that should be handled in another issue:
- When moving the map over the anti-meridian, the search queries only show results for the side of the anti-meridian that the center of the map is on. Anything which actually crosses the anti-meridian is considered to be on the right side of the it for search purposes.
- Thumbnails that cross the anti-meridian are  also broken, being …

Fix anti-meridian artifacts on scene footprints

---

app-backend/common/src/main/resources/reference.conf
app-backend/common/src/main/scala/Config.scala
app-backend/common/src/main/scala/cache/CacheClient.scala
app-backend/common/src/main/scala/utils/CogUtils.scala
app-backend/common/src/main/scala/utils/RangeReaderUtils.scala
app-backend/common/src/main/scala/utils/URIUtils.scala

AWS generates a hmac-sha signature to auth queries, however this signature is based on `METHOD`, time, and other params. It means that `GET` query and `HEAD` query can't have the same signature.
[By default `HttpRangeReader` would send a `HEAD` request](https://github.com/locationtech/geotrellis/blob/master/spark/src/main/scala/geotrellis/spark/io/http/util/HttpRangeReader.scala#L38-L42)
See: https://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html
I suggest to remark in docs that `URL` should be for `GET` request and in all cases we have extra get params in URLs - use only `GET` requests.
* Get a signed URL (for instance: https://raster-prediction-api-dev-andrew.s3.amazonaws.com/uploads/a6009b46-e5ff-42ee-bb07-1f61f2704050/1-x-upload.tif?X-Amz-Algorithm=AWS4-HMAC-SHA2 …

Signed requests should never send a HEAD request

---

Jenkinsfile

Add `RF_DEPLOYMENT_ENVIRONMENT` variable, which is used when checking `desired_vcpus` for batch compute environments.
* see azavea/raster-foundry-deployment#137
Connects azavea/raster-foundry-platform#334

 Add RF_DEPLOYMENT_ENVIRONMENT variable

---

app-frontend/src/app/components/map/mapContainer/mapContainer.module.js
app-frontend/src/app/components/map/mapSearchModal/mapSearchModal.controller.js

This PR adds handling of geographic coordinates (lat long) in the map search.
* Enter coordinates and things that aren't coordinates and make sure that the search detects coordinates properly.
* Make sure the map view changes and goes to where to told it to
Closes #3327

Add support for lat long coordinates in map search

---

app-tasks/rf/src/rf/uploads/modis/create_geotiff.py

This PR uses rasterio's `warp` module to perform the warp instead of `gdalwarp` plus a bunch
of command line options.
Not clear whether we want to set nodata or not. I feel like we probably do, so I added that into the
final translation step in a separate commit, but I can remove if we don't want to for some reason.
* call `warp_tif` on the path to your `combined.tif`, writing output somewhere convenient
* compare results in qgis
Closes #3421

Use rasterio warp module to warp modis tifs

---

app-frontend/src/app/pages/admin/organization/organization.html
app-frontend/src/app/pages/admin/organization/teams/teams.html
app-frontend/src/app/pages/admin/organization/users/users.html
app-frontend/src/app/pages/admin/team/users/users.html
app-frontend/src/assets/styles/sass/_shame.scss
app-frontend/src/assets/styles/sass/components/_project-item.scss
app-frontend/src/assets/styles/sass/pages/_admin.scss

- fixes padding on long project names -- the name does not overlap the buttons now
- editable logos are now indicated even when the user is not hovering as long as the user is authorized to do so
- empty lists in the platform admin section are now hidden and in their place is a call to action item to explain and prompt the user to add the first item
~- [ ] Any new SQL strings have tests
* make sure the things I said I changed were actually changed
Closes #3528 
Closes #3487

More frontend fixes

---

app-frontend/src/app/components/settings/addUserModal/addUserModal.html
app-frontend/src/app/components/settings/addUserModal/addUserModal.module.js
app-frontend/src/app/pages/admin/organization/teams/teams.module.js
app-frontend/src/app/pages/admin/organization/users/users.module.js
app-frontend/src/app/pages/admin/team/users/users.js

This PR fixes the bug so that organization admins are able to add users/themselves to teams.
* Navigate to the following pages and add users to a team, check if it behaves as expected considering the current logged in user's group role
- organization page -> team tab -> add user modal through the pencil dropdown
- team page -> add user button
Closes #3513 
Closes #3509

Fix add user to team bug

---

app-backend/api/src/main/scala/scene/Routes.scala
app-backend/db/src/main/scala/com/azavea/rf/database/SceneDao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/SceneWithRelatedDao.scala

In #3547 the logic for querying scenes was updated to improve
performance; however, this meant that the logic to check for scene
viewing permissions used when checking if a user is authorized to view
the scene's datasource or actions needed to be updated as well since
the rules for viewing public scenes was removed from the ACR table.
This meant if a user tried to use a scene with a public datasource in the lab
or in the color mode options they would see a 403.
This commit renames `authQuery` to be more explicit and also updates
other scene routes that check view permissions to use correct logic.
Closes #3561
~- [ ] Symlinks from new migrations …

Update scene authorization check to use updated logic

---

app-frontend/src/app/pages/admin/organization/organization.html
app-frontend/src/app/pages/admin/organization/organization.module.js
app-frontend/src/app/pages/admin/organization/teams/teams.html
app-frontend/src/app/pages/admin/organization/teams/teams.module.js
app-frontend/src/app/pages/admin/platform/organizations/organizations.html
app-frontend/src/app/pages/admin/platform/organizations/organizations.module.js
app-frontend/src/app/pages/admin/platform/users/users.module.js
app-frontend/src/app/pages/admin/team/team.html
app-frontend/src/app/pages/admin/team/team.js
app-frontend/src/app/pages/projects/list/list.controller.js
app-frontend/src/app/services/auth/organization.service.js
app-frontend/src/app/services/auth/team.service.js
app-frontend/src/assets/styles/sass/pages/_admin.scss

This PR enables admins or super users to edit organization and team names on frontend.
* Navigate to below pages to check if organization or team name editing is enabled and is possible considering your logged in user's group role:
- a platform page that lists organizations
- an organization's main page
- an organization page that lists teams
- a team main page
Closes #3506

Make organization and team names editable for admins

---

app-frontend/src/app/pages/settings/profile/profile.html
app-frontend/src/app/pages/settings/profile/profile.module.js

This PR updates profile info provider on the profile page under settings and directs users to the right place to change profile photo.
* Log in with different provider accounts and check if the profile page under settings shows the corresponding contents.
Closes #3507

Tell users where to update profile photo

---

app-tasks/rf/src/rf/commands/process_upload.py
app-tasks/rf/src/rf/models/base.py
app-tasks/rf/src/rf/uploads/planet/factories.py

Remove unused argument for Planet scene factory, make `client`, a required argument, and also add additional logging at API boundaries. 
At some point the arguments to this function changed such that the default value of `None` was being passed to the Planet scene factory for the API client. The change in this PR moves the `client` to a required argument so that this mistake is harder to make in the future.
```
cbrown@trout:~/Projects/raster-foundry$ …
```

Fix Planet Upload Processing

---

app-backend/api/src/main/scala/project/Routes.scala
app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/Project.scala
app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/User.scala
app-backend/db/src/main/scala/com/azavea/rf/database/ProjectDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/ProjectDaoSpec.scala
app-frontend/src/app/components/projects/projectItem/projectItem.html
app-frontend/src/assets/styles/sass/components/_project-item.scss

This PR modifies the projects list endpoint to include extra user information: id, name, and a url
for the user's profile image. It uses this information in the frontend to display information about
who owns a project that a user can see.
@jfrankl said to take out the user's name because names are long and it might mess things up.
* bring up your server and frontend
* list projects
* confirm it matches designs, within scope of the linked issue
Closes #3526

Display ownership information with projects

---

Jenkinsfile
Jenkinsfile.release

Moves `release/` and `hotfix/` builds into their own `Jenkinsfile` that skips `cibuild` and `cipublish` stages. Instead, existing images are re-tagged with the release tag and pushed to ECR, and the release tag is then threaded through to terraform before running `scripts/infra`. This should cut down build times substantially.
N/A
I played with the idea of keeping a single Jenkins job, adding a `--production` flag to `cipublish` to do the retagging, and …

Separate Staging and production deployment pipelines

---

app-backend/api/src/main/scala/datasource/QueryParameters.scala
app-backend/api/src/main/scala/datasource/Routes.scala
app-backend/api/src/main/scala/project/Routes.scala
app-backend/api/src/main/scala/scene/QueryParameters.scala
app-backend/api/src/main/scala/shape/Routes.scala
app-backend/api/src/main/scala/toolrun/QueryParameters.scala
app-backend/api/src/main/scala/toolrun/Routes.scala
app-backend/api/src/main/scala/tools/QueryParameters.scala
app-backend/api/src/main/scala/tools/Routes.scala
app-backend/api/src/main/scala/utils/QueryParameters.scala
app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/QueryParameters.scala
app-backend/db/src/main/scala/com/azavea/rf/database/Dao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/SceneDao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/SceneWithRelatedDao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/filters/Filterables.scala

This PR updates the below top-level objects' listing filters so that we may filter them just owned by ourselves, shared directly to us, shared to us due to group membership, etc.  It also enables us to filter these objects by a specific group type and id.
This is a backend PR supporting the new search UI frontend and the new admin frontend.
* Make dev user admin of a platform/organization/team.
* Grant view access of a certain top-level object owned by this dev user, say a …

Update top-level objects' listing filters

---

app-backend/migrations/src_migrations/main/scala/128.scala

Migration did not handle multiple polygons on each side of the anti-meridian correctly.
Ran it on staging:
* Verified on staging
Closes https://github.com/azavea/raster-foundry-platform/issues/366

Fix anti-meridian migration

---

app-backend/api/src/main/scala/organization/Routes.scala
app-backend/api/src/main/scala/platform/Routes.scala
app-backend/db/src/main/scala/com/azavea/rf/database/OrganizationDao.scala

Restrict the platform/organizations endpoint to platform admins
Add a new endpoint for searching up to 5 organizations ordered by name
*  Verify that the dev user no longer as permissions to access the platform orgs endpoint, and that the systems user still can.
* Verify that searching the `organizations/search?search={text}` endpoint only yields the public org for the dev user, but the systems user can use it to list any platform
* Verify that the search endpoint returns up to 5 results
Closes #3564 
Depends #3531

Add org search endpoint

---

app-backend/api/src/main/scala/platform/Routes.scala
app-backend/api/src/main/scala/user/Auth0User.scala
app-backend/api/src/main/scala/user/Routes.scala
app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/User.scala
app-backend/db/src/main/scala/com/azavea/rf/database/UserDao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/filters/Filterables.scala
app-backend/db/src/test/scala/com/azavea/rf/database/UserDaoSpec.scala

Restrict platform user endpoint to platform users
Update endpoints still require a full user object.
* Verify that the platform users endpoint is only accessible by platform admins
* Verify that the `users/search?search=searchtext` endpoint works as expected, and only returns users that the requester has permission to view when taking into account platform role, org, team, and user visibility on the platform
* Verify that endpoints that list users return a limited subset of fields
Closes #3565
Depends on #3569

Add user search endpoint

---

app-backend/batch/src/main/scala/com/azavea/rf/batch/notification/NotifyIngestStatus.scala
app-backend/db/src/main/scala/com/azavea/rf/database/PlatformDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/PlatformDaoSpec.scala

This PR fixes the ingest notification bug so that scene owners are notified even if they don't own any project. It also updates the associated property tests.
* Refer to testing instructions https://github.com/raster-foundry/raster-foundry/pull/3525 to make sure if you own a scene but the scene is not in any project, you get the ingest status notification email. (Please make sure the scene is either `INGESTED` or `FAILED` since no notification will be sent in other cases by design)
Closes …

Fix ingest notification bug

---

app-backend/db/src/main/scala/com/azavea/rf/database/Dao.scala

This PR includes a distinct on id in the `countF` in the `Dao` base class so that we
don't double count.
The `countF` is exercised anywhere `PaginatedResponse`s are returned, which happens in
some places in tests already, so we know it's valid sql.
I think larger changes are necessary to test that the count is correct, so I'm skipping that and we can
decide later whether we think it's necessary.
* list your projects and confirm the count matches
* browse for scenes in a small area and confirm the count matches
Closes #3589

Distinct on ids when counting

---

app-backend/batch/src/main/scala/com/azavea/rf/batch/aoi/UpdateAOIProject.scala
app-backend/batch/src/main/scala/com/azavea/rf/batch/export/CheckExportStatus.scala
app-backend/batch/src/main/scala/com/azavea/rf/batch/notification/NotifyIngestStatus.scala
app-backend/common/src/main/scala/notification/Email.scala
app-frontend/src/app/pages/admin/platform/settings/email/email.html
app-frontend/src/app/pages/admin/platform/settings/email/email.module.js

This PR:
- enables sending email notifications for export status and AOI update in batch
- updates frontend so that platform admins are able to set platform host (like `app.rasterfoundry.com`) for links in email body.
* Run migrations if needed
* `./scripts/psql` and do the following to make testing an export in a project and in a tool-run/analysis easier on dev:
```sql
insert into exports
(
id,
created_at,
created_by,
modified_at,
modified_by,
visibility,
export_status, …
```

Export and AOI notifications

---

app-backend/api/src/main/scala/platform/Routes.scala
app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/User.scala
app-backend/db/src/main/scala/com/azavea/rf/database/Dao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/OrganizationDao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/TeamDao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/UserGroupRoleDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/OrganizationDaoSpec.scala
app-frontend/src/app/pages/admin/organization/users/users.html
app-frontend/src/app/pages/admin/organization/users/users.module.js
app-frontend/src/app/pages/admin/platform/organizations/organizations.module.js
app-frontend/src/app/pages/admin/team/users/users.html
app-frontend/src/app/pages/admin/team/users/users.js
app-frontend/src/app/pages/user/organizations/organizations.html
app-frontend/src/app/pages/user/organizations/organizations.js
app-frontend/src/app/pages/user/teams/teams.html
app-frontend/src/app/pages/user/teams/teams.js
app-frontend/src/app/pages/user/user.html
app-frontend/src/app/pages/user/user.js
app-frontend/src/app/services/auth/organization.service.js
app-frontend/src/app/services/auth/team.service.js
app-frontend/src/assets/styles/sass/components/_button.scss

This PR makes frontend and backend changes so that:
* users will know their roles (i.e. ADMIN or MEMBER) when listing organizations and teams they belong to;
* for admins, show invitation, request status on user list page on organization level and on team level, and enable these buttons' actions;
* for admins, make organization de/activation work;
* sort users in organization and team lists by membership status and by group role so that pending approval and pending invitation items show on top and that admin items show before members;
* Fix user profile picture broken bug on profile pages.
~Marked as WIP since acting on membership invitation/request on team level has not been implemented yet.~
- ~[Swagger …

Make org de/activation work. Act on membership request/invitations.

---

app-frontend/src/app/components/projects/projectItem/projectItem.html
app-frontend/src/assets/styles/sass/components/_project-item.scss
app-frontend/src/assets/styles/sass/theme/high-contrast/components/_project-item.scss

- Removes duplicate a tags within project card preview window
- Re-adds the project-title overflow hover effect
**Default theme**
**High-contrast theme**
- rename a project with a long string
- navigate to project card and hover over the title
- the user image and project action buttons should still be visible

cleaned up project card frontend and project title hover bug

---

app-backend/api/src/main/scala/user/Routes.scala
app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/User.scala
app-backend/datamodel/src/test/scala/com/azavea/rf/datamodel/implicits/Generators.scala
app-backend/db/src/main/scala/com/azavea/rf/database/UserDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/UserDaoSpec.scala
app-frontend/src/app/pages/user/settings/connections/connections.controller.js
app-frontend/src/app/services/auth/user.service.js

This PR fixes a bug so that we can add planet token again.
* Go to your profile settings page and set a new planet token. Make sure it works.
* CI 
Closes #3623

Fix add planet token bug

---

app-frontend/src/app/components/colorComposites/colorSchemeDropdown/colorSchemeDropdown.html
app-frontend/src/app/components/colorComposites/colorSchemeDropdown/colorSchemeDropdown.module.js
app-frontend/src/app/components/histogram/nodeHistogram/nodeHistogram.html
app-frontend/src/app/components/histogram/nodeHistogram/nodeHistogram.module.js
app-frontend/src/app/components/lab/colormapModal/colormapModal.html
app-frontend/src/app/components/lab/colormapModal/colormapModal.js
app-frontend/src/app/index.components.js
app-frontend/src/assets/styles/sass/_shame.scss

Add a color map modal that allows the user to define a custom color map manually, by uploading a json file that contains colors, or by pasting a json array of colors
- ~PR has a name that won't get you publicly shamed for vagueness~
* Verify that you can upload an array of color values
* Verify that you can paste an array of color values
* Verify that changing values and colors updates the visible histogram
* Verify that the way buttons add / remove breakpoints makes sense
* …

Add and use color map modal

---

app-backend/api/src/main/scala/scene/Routes.scala
app-backend/api/src/main/scala/scene/ThumbnailQueryParameters.scala
app-backend/common/src/main/scala/utils/CogUtils.scala
app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/QueryParameters.scala

This PR adds an endpoint to scenes for generation of thumbnails from COG overviews
on-the-fly for COG scenes.
I'm reprojecting to make the png. Why am I reprojecting? I don't know why I'm reprojecting. :man_shrugging: 
Also I _think_ partly due to reprojecting the requested thumbnail sizes are approximate.
Not sure how important that is.
* Choose a COG scene (or just upload a scene and process it :sunglasses: )
* Make some authenticated requests for thumbnails of different sizes
* Make some of them more than once to confirm that the second time it's fast because cacheing
Closes #3364

Generate thumbnails from COG scenes

---

app-backend/db/src/main/scala/com/azavea/rf/database/PlatformDao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/SceneWithRelatedDao.scala

This PR default sorts the users returned on the platforms members endpoint. Users on
team members and organization members were already sorted by the same columns used
here.
It also adds explicit ordering to the `id` default sort on scenes, since in the past inconsistent
ordering directions resulted in the index not getting used.
@alkamin claims that the order didn't have anything to do with index use in scene query
performance testing because they were using the index before, and also that there were
indices present in prod and staging that make it so inconsistent ordering should be fine.
I didn't find those indices. The scene ordering is sort of a shot in the dark.
It's not obvious that this was the _preferred_ default ordering aside from its use elsewhere,
but the issue was _very_ …

Add default sort to platform member list

---

app-frontend/src/app/services/scenes/cmrRepository.service.js

This PR removes Tri-Decadal MSS from the search options in the NASA CMR repository. Since
the IDs that come back aren't mappable to Landsat IDs as GCS understands them, there isn't
a way to handle imports successfully for this datasource without a broader refactoring.
Fortunately, that refactoring should be pretty easy (see comment in #3555).
* Confirm that Tri-Decadal MSS isn't one of the options for scenes in the NASA CMR search
* For extra credit, try to create and process uploads for L7 ETM+ and L4 or L5 TM scenes (or
come by my area for proof)
Closes #3556

Remove Tri-Decadal MSS from NASA CMR search options

---

app-frontend/src/app/components/admin/sidebarTeamList/sidebarTeamList.html
app-frontend/src/app/components/admin/sidebarTeamList/sidebarTeamList.js
app-frontend/src/app/index.module.js
app-frontend/src/app/index.routes.js
app-frontend/src/app/pages/admin/organization/settings/settings.html
app-frontend/src/app/pages/user/projects/projects.html
app-frontend/src/app/pages/user/rasters/rasters.html
app-frontend/src/app/pages/user/settings/notification/notification.html
app-frontend/src/app/pages/user/settings/notification/notification.module.js
app-frontend/src/app/pages/user/settings/privacy/privacy.html
app-frontend/src/app/pages/user/settings/privacy/privacy.module.js
app-frontend/src/app/pages/user/settings/settings.html

This PR:
* adds visibility control on user profile settings page
* adds notification control on user profile settings page
* adds optional organization logo element on team list when on user pages
Visibility
*Notification*
* Organizations logos under team list
* Go to user profile settings page, check if visibility is editable
* Go to user profile settings page, check if email visibility is editable
* Add yourself to teams under different organizations. Go to your own pages …

Add some enhancements on admin and user frontend

---

app-frontend/src/app/components/scenes/sceneImportModal/sceneImportModal.controller.js
app-tasks/rf/src/rf/uploads/geotiff/factories.py

This PR escapes pipes when we upload COGs from local files and changes the
image file location for created scenes when we process COGs.
We seemed not to be aware of how much work was already done for the two issues
this closes. We already created scenes directly without upload processing, so we
mainly needed to set the upload status correctly and escape the pipe.
However! In testing, I hypothesized that we should be able to round trip COGs
successfully: uploading a non-COG, processing it to a COG, downloading the scene
with the processed COG, and then local file uploading the downloaded scene
Should Work :tm:. It didn't, because in upload processing to create the COG, the
scene's image was set to the non-COG tif. So there's also a fix in this PR to make
upload/download/upload round …

Polish local COG upload processing

---

app-backend/api/src/main/scala/scene/Routes.scala
app-backend/build.sbt
app-backend/db/src/main/scala/com/azavea/rf/database/ProjectDao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/SceneDao.scala
app-backend/tile/src/main/scala/Router.scala
app-backend/tile/src/main/scala/image/Mosaic.scala
app-backend/tile/src/main/scala/image/MultiBandMosaic.scala
app-backend/tile/src/main/scala/routes/MosaicRoutes.scala
app-frontend/src/app/components/scenes/sceneItem/sceneItem.module.js
app-frontend/src/app/pages/projects/edit/aoi-parameters/aoi-parameters.controller.js
app-frontend/src/app/pages/projects/edit/browse/browse.module.js
app-frontend/src/app/services/map/map.service.js
app-frontend/src/app/services/scenes/cmrRepository.service.js
app-frontend/src/app/services/scenes/rasterFoundryRepository.service.js
app-frontend/src/app/services/scenes/scene.service.js

~This PR reflects the re-scoped requirements in the original card to add frontend support for displaying COG scene thumbnail and put thumbnail on the map before we have tile server support for it.~
This PR supports COG scene browse so that COG scene thumbnails show up on sidebar and COG scene tiles show up on map when a user is browsing before adding any scenes in a project.
* `boundless` is added as an external resolver for `geotool` since it did not stop giving me …

Add COG scene browse support for thumbnail and tiles

---

app-backend/common/src/main/scala/utils/CogUtils.scala
app-backend/tile/src/main/scala/image/Mosaic.scala
app-backend/tile/src/main/scala/image/MultiBandMosaic.scala
app-backend/tile/src/main/scala/image/SingleBandMosaic.scala

Enables single band visualization for COGs
* Add a COG to a Project
* Go to UI and select single band visualization
Closes #3408

Enable Single Band Visualization for COGs

---

app-frontend/src/app/components/scenes/sceneDetailModal/sceneDetailModal.module.js

This PR supports COG tile in scene detail view to reflect the comment in https://github.com/raster-foundry/raster-foundry/issues/3365
* Go to browse COG scenes or look at COG scenes that are already in a project.
* Click on the scene detail view and make sure COG tiles are displayed on the map instead of thumbnails.
* Check other scenes' detail modal -- they should use thumbnails on the map.

Support COG tile in scene detail view.

---

app-frontend/src/app/pages/projects/edit/browse/browse.html
app-frontend/src/app/pages/projects/edit/browse/browse.module.js

This PR prevents searching for scenes in the Raster Foundry repository unless the zoom level
is higher than 8. It's supposed to help us not have so many timeouts in the scene query and
also to keep those really long queries out of the postgres queue.
~Is it the `Raster Foundry` repo for Radiant also? It seems like maybe it should be, I'm not sure whether it is or not.~ Confirmed, it is.
~ I still need to make some kind of changes in `sceneFilterPane.module.js` because state and scene requests live everywhere but it's the end of the day and no one is reviewing this tonight anyway so :man_shrugging: I'll hit it first thing Monday. ~
* Load the app
* Pan around, zoom in and out, and note that you don't fire any requests until zoom is at least 8
Closes #3557

Only search for scenes if zoom level >= 8 when in RF repository

---

app-frontend/src/app/pages/imports/datasources/detail/detail.html
app-frontend/src/app/pages/imports/datasources/detail/detail.module.js
app-frontend/src/app/services/scenes/datasource.service.js

This PR makes it possible to add wavelengths to bands for a datasource.
Also does some basic validation that it's a list of two ints
* Edit a datasource you own
* Add wavelength
* Make it something that isn't in the form `x, y` and observe validation results
* Save changes once it's valid again
* Refresh the page
* Shouldn't be any errors
Closes #3370

Allow updating wavelength from datasource detail view

---

app-backend/db/src/main/scala/com/azavea/rf/database/Dao.scala
app-frontend/src/app/components/scenes/sceneDownloadModal/sceneDownloadModal.html

This PR
- fixes the scene download permission bug so that `PUBLIC` scenes are download-able without further permissions
- shortens the metadata download URL in scene download modal
* Download a public scene and see if it works
* Make sure places other than scenes using `authorize` in `Dao` work as they used to
Closes #3650

Fix scene download permission bug

---

app-frontend/src/app/index.routes.js
app-frontend/src/app/pages/home/home.html

This PR:
- fixes org setting button bug.
- fixes manage account button bug on home page.
* Go to home page and click on "Manage account" button, it should take you to your own account settings page
* Login as an admin. Go to `admin/organization/<organization ID>/projects` and click on setting tab/icon/button, it should take you to organization privacy settings page.
Closes #3675 
Closes #3664

Fix organization setting button bug

---

app-frontend/src/app/services/scenes/datasource.service.js

Logic in the DatasourceService assumed the presence of wavelengths but we don't want it to be required. The PR fixes that.
Trivial, going to merge once CI completes
Closes #3681

Allow saving of bands without wavelength in UI

---

app-tasks/rf/src/rf/ingest/sentinel2_ingest.py

Our ingest definition generation code had a tiny bug that caused bands above index 10 to be mis-indexed
This really can only get tested on staging
Closes #3702

Fix sentinel 2 ingest definition generation to fix missing band

---

app-backend/api/src/main/scala/platform/Routes.scala
app-backend/datamodel/src/test/scala/com/azavea/rf/datamodel/implicits/Generators.scala
app-backend/db/src/main/scala/com/azavea/rf/database/PlatformDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/PlatformDaoSpec.scala
app-backend/db/src/test/scala/com/azavea/rf/database/PropTestHelpers.scala

This PR adds backend support to search for teams a user directly belongs to and has access to due to organization memberships
The frontend is in scope of the modal issue, mutually agreed with @alkamin 
* Create some teams in different organizations you are in
* Add yourself to some of these created teams as members/admins
* `GET api/platforms/<platform ID>/teams/search` should list at most 5 teams you have membership of and have access to due to organization memberships, ordered by team names in an ascending …

Add team search backend support

---

app-frontend/src/app/pages/projects/edit/browse/browse.module.js

This PR fixes browse COG scene tile bug due to the missing `sceneService`.
* Make sure you have COG scenes before proceeding.
* Go to a project and browse for COG scenes.
* Check if COG tiles show up on map upon hovering or checking the checkbox.
Closes #3692

Fix browse COG scene tile bug

---

app-frontend/src/app/pages/projects/edit/annotate/import/import.html

This PR allows importing GeoJSON annotation with blank properties.
* Go to project annotation page
* Upload a GeoJSON file with empty properties
* Make sure you see property selection fields afterwards
* Select default values and make sure the import afterwards works
Closes #3588

Allow importing GeoJSON annotation with blank properties

---

app-backend/batch/src/main/scala/com/azavea/rf/batch/export/CheckExportStatus.scala
app-backend/build.sbt
app-backend/db/src/main/scala/com/azavea/rf/database/UserGroupRoleDao.scala
docs/style/scala.md

This PR makes async exports work for ingested scenes. There were two problems:
- spark couldn't initialize due to a version conflict with a transitive dependency
- email failure caused the `ConnectionIO` to fail, which rolled back anything that happened previously in the transaction, which meant we never got the status update (even though the export succeeded)
I'm adding a separate issue for COG exports, since they're more complicated than fits into the point on
this card.
To prove the transactional nature of `ConnectionIO`s, you can:
- create a `Platform`
- create a `ConnectionIO` to add that platform (call it `platInsertIO`)
- `(platInsertIO flatMap { _ => sql"select * from users".query[Int].unique }).transact(xa).unsafeRunSync`
- verify that the platform wasn't inserted
To get around …

Fix async exports for ingested scenes

---

app-frontend/src/app/services/scenes/datasource.service.js

This PR makes it so that saving new color composites works for datasources.
* Edit a datasource
* Add a color composite
* Save it
* :sunglasses:
* Add a band
* Save the datasource
* :sunglasses:
* Reload the page to prove to yourself that 204s are not a lie
Closes #3694

Only transform band wavelength if it's a string

---

app-backend/build.sbt
app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/Annotation.scala
docker-compose.yml

This PR changes our merge strategy for the API project so that it will keep necessary files
from `META-INF/services` from geotools.
* rebase out the "Stop pretending to be in prod" commit
* `assembly` from the api subproject in your sbt shell
* `./scripts/server --quiet`
* create some annotations and try to export a shapefile
Closes #3666

Fix annotation shapefile export

---

app-frontend/config/webpack/global.js
app-frontend/package.json
app-frontend/yarn.lock

Update auth0 lock so it no longer uses the depricated API
*IMPORTANT CONFIGURATION INFORATION*:
go to https://manage.auth0.com/#/tenant/advance and turn off the legacy lock api
Add all hostanmes to "Web Origins" at
manage.auth0.com/#/applications/{}/settings for the api, otherwise you'll get a
bunch of CORS errors.
I've already done this for dev and staging, but production should have the legacy api turned off when we deploy this.
* Run `yarn` and `yarn dev`
* Verify that …

Update auth0 lock

---

app-backend/tile/src/main/scala/image/MultiBandMosaic.scala

Pulled this from a commit in https://github.com/raster-foundry/raster-foundry/pull/3721/commits/66f680aec70d566af7ad6662cf682355a1d3fde2?utf8=%E2%9C%93&diff=unified&w=1 since it is separate and fixes an issue outside of exports.
Going to merge once CI is done -- this is pretty self-contained and I reviewed this portion of the other PR to verify it works.

Fixes whitebalance issues for multiple scenes in a project

---

app-backend/db/src/main/scala/com/azavea/rf/database/SceneToProjectDao.scala
app-backend/tile/src/main/scala/image/MultiBandMosaic.scala

This fixes an error we saw after the deploy yesterday where the tile server continued to experience match errors on mosaic definitions. The matching strategy was not exhaustive and in some cases scenes that had no ingest location would cause errors in the tile server.
This fixes the problem in two ways:
- Adds an additional filter in `SceneToProjectDao` query to filter out scenes that have not been ingested
- Makes the match more exhaustive and less error prone by allowing ingest location to be `null`/`None`
~- [ ] Any content changes are properly templated using …

Fix Match Error in Project Mosaics

---

app-frontend/src/app/components/settings/addUserModal/addUserModal.html
app-frontend/src/app/components/settings/addUserModal/addUserModal.module.js
app-frontend/src/app/services/auth/organization.service.js

Allow setting a role in the add user modals
Use search endpoint if the user is not a platform admin while adding users to an
organization
Remove example.com email since it isn't helpful
- ~Styleguide updated, if necessary
* Log in as an organization admin
* Verify that you can search for users
* Verify that you can add users as admins
Closes https://github.com/raster-foundry/raster-foundry/issues/3737

Allow setting role when adding a user to an organization or team

---

app-frontend/src/app/components/datasources/datasourceCreateModal/datasourceCreateModal.html
app-frontend/src/app/pages/home/home.controller.js
app-frontend/src/app/pages/home/home.html
app-frontend/src/app/pages/imports/datasources/detail/detail.html
app-frontend/src/app/pages/imports/datasources/detail/detail.module.js

This PR fixes:
- buttons on home page for creating templates and navigating to API token page
- links in datasource creation modal to edit datasource bands and color composites
- button on datasource detail page to check the existence of band definitions to avoid dead end scene import
* Home page -> click on `Create a new template` and `Manage API tokens` buttons, then check if they lead you to right places/modals
* Datasource list page -> click on `New datasource`, then …

Fix broken links and buttons on home page and datasource create modal

---

app-backend/batch/src/main/scala/com/azavea/rf/batch/export/CheckExportStatus.scala
app-backend/tile/src/main/scala/directives/TileAuthentication.scala
app-frontend/src/app/pages/projects/edit/exports/new/new.controller.js
app-frontend/src/app/services/projects/project.service.js

An `if` statement (still unclear why) was causing emails to not be sent when exports either succeeded or failed. This also caused the status update in the database to fail as well so that even successfully exported projects would not be downloadable because emails failed to send.
Two fixes are in this PR for that particular issue:
- unecessary `if` statement is removed (system user never exports projects anyways)
- export status is always updated prior to trying to send emails
One additional change in this PR is to update the frontend to always use "stitched" exports, this is more user-friendly and should be the default in most cases.
~- [ ] Symlinks …

Fix Export and Export Emails

---

app-frontend/src/app/components/common/dateRangePickerModal/dateRangePickerModal.controller.js
app-frontend/src/app/components/common/dateRangePickerModal/dateRangePickerModal.html
app-frontend/src/assets/styles/sass/_shame.scss

This PR enables manual update on date range picker and makes sure calendar selection and preset date range selection are not affected. It enables displaying and editing dates in `MM/DD/YYYY` format.
This PR tries to use jQuery as minimal as possible since the two date input boxes are brought in by a third party library not very accessible to us.
* Go to a project and browse scenes
* Open up date range picker modal and use it
* Make sure: updating date range manually behaves …

Make manual date range update work for scene browse filter

---

app-backend/batch/src/main/scala/com/azavea/rf/batch/landsat8/ImportLandsat8C1.scala
app-backend/batch/src/main/scala/com/azavea/rf/batch/sentinel2/ImportSentinel2.scala
app-backend/common/src/main/scala/utils/Antimeridian.scala

Update the landsat and sentinel importers to split polygons which cross the anti-meridian
* Build batch jar `./sbt batch/assembly`
* import scenes which cross the anti-meridian
`java -cp /opt/raster-foundry/jars/rf-batch.jar com.azavea.rf.batch.Main import_sentinel2 2018-07-03`
`java -cp /opt/raster-foundry/jars/rf-batch.jar com.azavea.rf.batch.Main import_landsat8 2018-07-12`
* Verify that scenes are split over the anti-meridian by browsing to the anti-meridian on the …

Correct ImportLandsat8C1 and ImportSentinel2 data and tile footprint

---

app-frontend/src/app/pages/projects/edit/exports/new/new.controller.js
app-frontend/src/app/pages/projects/edit/exports/new/new.html
app-frontend/src/app/services/scenes/planetRepository.service.js
app-tasks/rf/src/rf/utils/io.py

Fixes two issues:
- Setting the planet token would persist in the service even after updates to the planet token. Originally, I thought this was because we weren't checking for blank strings, but really it was because after updating the credential the old one was still being used
- Fixes link in manage token modal when it isn't set
* Open UI with a user that doesn't have a planet credential set
* Go to browse scenes for planet, click on prompt to manage …

Make planet credentials less persistent in service

---

app-backend/batch/src/main/scala/com/azavea/rf/batch/aoi/UpdateAOIProject.scala
app-backend/batch/src/main/scala/com/azavea/rf/batch/export/CheckExportStatus.scala
app-backend/batch/src/main/scala/com/azavea/rf/batch/notification/NotifyIngestStatus.scala
app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/Platform.scala
app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/User.scala
app-backend/db/src/main/scala/com/azavea/rf/database/PlatformDao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/notification/Notify.scala
app-backend/db/src/test/scala/com/azavea/rf/database/PlatformDaoSpec.scala
app-frontend/src/app/components/settings/addUserModal/addUserModal.module.js

This PR adds support for sending emails to user contact email address if users choose to receive notifications through it (instead of login email). It also fixes a bug in the modal for inviting team users.
Platform email settings and subscriptions:
Dev user has a contact email on file:
Dev user chooses to receive emails through contact email:
Emails sent to dev user's contact email:
* Configure platform email settings and subscriptions
* Update your profile to include a contact email
* Choose either your …

Support sending notifications to user contact email

---

app-backend/api/src/main/scala/project/Routes.scala
app-frontend/src/app/components/projects/projectPublishModal/projectPublishModal.module.js
app-frontend/src/app/index.routes.js
app-frontend/src/app/index.run.js
app-frontend/src/app/pages/projects/edit/sharing/sharing.module.js
app-frontend/src/app/pages/share/share.html

This PR does a few things to enable viewing of the share page of a public project by non-authenticated users:
- adds a `bypassAuth` option to front-end routes that skips authentication
- adds a check for a visibility value of `PUBLIC` on the project GET endpoint that bypasses the authentication and authorization checks when the project is set as public
- sets both `tileVisibility` and `visibility` from the front-end when toggling public/private
* Choose a …

Allow public project share page to be viewed by non-logged in users

---

app-frontend/src/app/components/common/navBar/navBar.html
app-frontend/src/app/components/projects/projectItem/projectItem.html
app-frontend/src/app/pages/projects/edit/exports/new/new.controller.js
app-frontend/src/app/pages/share/share.html
app-frontend/src/app/services/projects/project.service.js
app-frontend/src/assets/styles/sass/base/_helpers.scss
app-frontend/src/assets/styles/sass/components/_avatar.scss
app-frontend/src/assets/styles/sass/components/_button.scss
app-frontend/src/assets/styles/sass/components/_permissions-modal.scss
app-frontend/src/assets/styles/sass/components/_project-item.scss

Avatar default sizes were recently changed. This caused some issues to our project-card alignment. This PR adds some helper classes to avatars so we can have different sized avatars for different needs. I also adjusted the css for avatars in project-cards so sizing the avatar can't break the card any longer.
A change was made to `.btn-square` recently which caused them to longer be square. This PR adds hard-defined widths and heights to this class.
- ~[ ] [Swagger specification](https://github.com/raster-foundry/raster-foundry-api-spec) updated~
- ~[ ] Any content changes are properly templated using `BUILDCONFIG.APP_NAME`~
- ~[ ] Any new SQL strings have tests~
* Look …

fixed avatar sizing and position issues, btn-square is now square

---

app-frontend/config/webpack/global.js
app-frontend/src/app/pages/projects/edit/edit.html
app-frontend/src/app/pages/projects/edit/edit.module.js

This adds an overridable (via global.js or overrides.js by setting the `MAP_CENTER` and `MAP_ZOOM` values in the `BUILDCONFIG`) initial map position for the project editor. This also updates our global.js to center the map on Dar es Salaam.
* See that the initial map position for editing a project with no scene is Dar es Salaam
* If you want, implement an overrides.js file and alter the `MAP_CENTER` or `MAP_ZOOM` parameters of the `BUILDCONFIG` to test …

Add overridable initial map position

---

app-frontend/src/assets/styles/sass/components/_permissions-modal.scss

Adjust component padding
* Verify that the permissions modal no longer as overflow / clipping issues on the select box in both themes
Closes #3778

Fix select in permission modal cutting off text

---

app-backend/api/src/main/scala/exports/Routes.scala
app-backend/batch/src/main/scala/com/azavea/rf/batch/SparkJob.scala
app-backend/batch/src/main/scala/com/azavea/rf/batch/export/CheckExportStatus.scala
app-backend/batch/src/main/scala/com/azavea/rf/batch/export/spark/Export.scala
app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/OutputDefinition.scala
app-backend/db/src/main/scala/com/azavea/rf/database/ExportDao.scala
app-frontend/src/app/components/map/labMap/labMap.module.js
app-frontend/src/app/pages/projects/edit/exports/new/new.controller.js
app-tasks/rf/requirements.txt
app-tasks/rf/src/rf/commands/export.py
app-tasks/rf/src/rf/ingest/sentinel2_ingest.py
app-tasks/rf/src/rf/uploads/geotiff/factories.py
app-tasks/rf/src/rf/uploads/geotiff/io.py
app-tasks/rf/src/rf/uploads/landsat8/io.py
app-tasks/rf/src/rf/utils/io.py

Updates export code to support AST exports, shifts some IO to the python code for more flexibility.
~This is kind of tough to test in the absence of https://github.com/raster-foundry/raster-foundry/pull/3782 so I would suggest merging that first.~
Mered #3782, so testing this should be more straightforward now
* Create an export for an analysis, grab the ID
* Run assembly on the batch jar: `./scripts/console api-server ./sbt` and then `project batch`, …

Add Lab Async Exports

---

app-backend/batch/src/main/scala/com/azavea/rf/batch/export/CreateExportDef.scala
app-backend/batch/src/main/scala/com/azavea/rf/batch/landsat8/ImportLandsat8C1.scala
app-backend/batch/src/main/scala/com/azavea/rf/batch/sentinel2/ImportSentinel2.scala
app-backend/batch/src/test/scala/com/azavea/rf/batch/export/model/ExportDefinitionSpec.scala
app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/InputDefinition.scala
app-backend/db/src/main/scala/com/azavea/rf/database/AccessControlRuleDao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/AnnotationDao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/Dao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/ExportDao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/LayerAttributeDao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/ProjectDao.scala
scripts/test

This PR makes it so that if we don't have any singleton scene nodes, we don't list
every scene in the scenes table. :man_facepalming:
Also it adds a lot of debug logging.
I need to do some cosmetic cleanup, but this is currently deployed to staging, so testable.
* Go to staging like right now
* Create an export for an analysis
* It should succeed in a few minutes (feel free to babysit in batch)

Don't list entire scenes table in export definition creation

---

app-frontend/src/app/components/histogram/histogramBreakpoint/histogramBreakpoint.module.js
app-frontend/src/app/components/lab/diagramContainer/diagramContainer.html
app-frontend/src/app/components/lab/diagramContainer/diagramContainer.module.js
app-frontend/src/app/components/lab/labNode/labNode.html
app-frontend/src/app/components/lab/labNode/labNode.module.js
app-frontend/src/app/redux/actions/histogram-actions.js
app-frontend/src/app/redux/actions/node-actions.js
app-frontend/src/app/redux/histogram-utils.js
app-frontend/src/app/redux/node-utils.js
app-frontend/src/app/redux/reducers.js
app-frontend/src/app/redux/reducers/node-reducer.js
app-frontend/src/assets/styles/sass/_shame.scss

Initialize render definitions before previewing.
Fix highlight for selected nodes (someone removed the style?)
Move createRenderDefinition to histogram-utils
Fix histogram breakpoints when zoomed in or out
* Create a new analysis
* Set the sources
* View / compare nodes before opening the histogram
* While preview is open, open histogram and verify that things don't change
* Verify that histogram breakpoints no longer break when zoomed in or out
Closes #3606
Closes #3258

Fix preview changing when node histogram is opened

---

app-backend/db/src/main/scala/com/azavea/rf/database/SceneDao.scala

This PR corrects scene geometries on insert. It's in response to a recent develop build failure in which
the geotrellis vector testkit helpfully pointed out another way we fail to handle invalid input data.
I wasn't sure how to make this work with the other places where we insert geometries, but also
the other geometries have tended to be considerably less troublesome (shapes, annotations...)
so I think maybe it's fine. I attempted to edit the geometry meta in `GtWktMeta` but postgres
didn't like what I did.
* CI

Correct scene geometry on insert

---

app-frontend/src/app/components/datasources/datasourceDeleteModal/datasourceDeleteModal.html
app-frontend/src/app/components/datasources/datasourceDeleteModal/datasourceDeleteModal.module.js
app-frontend/src/app/components/lab/diagramContainer/diagramContainer.html
app-frontend/src/app/components/map/labMap/labMap.module.js
app-frontend/src/app/components/map/staticMap/staticMap.html
app-frontend/src/app/components/projects/projectItem/projectItem.controller.js
app-frontend/src/app/components/scenes/sceneDetail/sceneDetail.html
app-frontend/src/app/components/scenes/sceneFilterPane/sceneFilterPane.module.js
app-frontend/src/app/components/scenes/sceneImportModal/sceneImportModal.html
app-frontend/src/app/pages/imports/raster/raster.html
app-frontend/src/app/pages/imports/raster/raster.module.js
app-frontend/src/app/pages/projects/edit/exports/new/new.controller.js
app-frontend/src/app/pages/user/settings/connections/connections.html

This PR anchors tiny UI improvements. See the checklist.
* go to staging and remove `btn-square` from the token connection buttons and confirm it looks ok
Closes azavea/raster-foundry-platform#432
Closes https://github.com/raster-foundry/raster-foundry/issues/3815
Closes https://github.com/raster-foundry/raster-foundry/issues/3799
Closes https://github.com/raster-foundry/raster-foundry/issues/3801

UI improvements and frontend scene query fix

---

app-backend/batch/src/main/scala/com/azavea/rf/batch/sentinel2/ImportSentinel2.scala
app-backend/batch/src/main/scala/com/azavea/rf/batch/util/S3.scala
app-tasks/rf/requirements.txt
app-tasks/rf/src/rf/ingest/sentinel2_ingest.py

This PR upgrades boto3 in app-tasks (we were _very_ behind) and sets requester pays on
requests from the java aws s3 sdk.
I tested Sentinel-2 import, testing ingest now
* run Sentinel-2 import -- from the `batch` subproject's console:
```scala
import com.azavea.rf.database.util.RFTransactor.xa
import com.azavea.rf.batch.sentinel2.ImportSentinel2
import java.time.LocalDate
ImportSentinel2(LocalDate.parse("2018-05-15")).run
```
* You shouldn't get access denied almost immediately
* Rebuild batch container
* Re-assemble batch jar
* run an ingest for a Sentinel-2 scene
* You shouldn't get access denied

Enable requester pays for Sentinel-2 bucket access

---

app-backend/db/src/main/scala/com/azavea/rf/database/SceneWithRelatedDao.scala
app-frontend/src/app/components/lab/inputNode/inputNode.module.js
app-frontend/src/app/pages/projects/edit/advancedcolor/advancedcolor.controller.js
app-frontend/src/app/pages/projects/edit/browse/browse.module.js
app-frontend/src/app/pages/projects/edit/edit.module.js
app-frontend/src/app/pages/projects/edit/scenes/scenes.html
app-frontend/src/app/pages/projects/edit/scenes/scenes.module.js
app-frontend/src/app/services/projects/project.service.js

Simplify and fix fetching scenes and scene ordering in the edit controller
* Verify that pagination on the project scene list endpoint now works correctly, instead of using limit/offset pagination
* Verify that the frontend correctly fetches multiple pages of scene ordering
* Verify that the project scene page correctly shows > 30 scenes in a project on the scene list panel
Closes https://github.com/raster-foundry/raster-foundry/issues/3792

Fix pagination on project scenes

---

nginx/Dockerfile.api
scripts/setup

Copy dockerfile over along with srv*/dist*/ wildcard so it always copies at
least one file
the COPY command requires that at least one file is copied over - by copying a file that is known to exist and using a wildcard to fetch the rest, we avoid the error that occurs when trying to copy a non-existent directory.
* Delete your nginx/srv/dist folder
* On another branch, try building the container using `docker-compose build nginx-api`, verify that it fails
* switch to the PR …

Prevent container build failure when copying nginx/srv/dist before it exists

---

app-backend/api/src/main/scala/project/Routes.scala
app-backend/common/src/main/scala/utils/Shapefile.scala
app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/Annotation.scala
app-frontend/src/app/api/annotations.js
app-frontend/src/app/components/projects/annotateSidebarItem/annotateSidebarItem.html
app-frontend/src/app/pages/projects/edit/annotate/annotate.module.js
app-frontend/src/app/pages/projects/edit/annotate/import/import.html
app-frontend/src/app/pages/projects/edit/annotate/import/import.module.js
app-frontend/src/app/redux/actions/annotation-actions.js
app-frontend/src/app/redux/reducers/annotation-reducer.js
app-frontend/src/assets/styles/sass/_shame.scss

This PR fixes annotation shapefile frontend and backend for:
- import:
* read and parse projection from `.prj` and re-project to web mercator before storing in db
* use user specified field names to read and parse properties before storing in db
- export:
* re-project from web mercator to wgs84 and set so in the schema
Annotation export as shapefile projected to `WGS84`
Annotation import as shapefile with field selection and `.prj` reading under the hood
Swagger spec ~and frontend messages upon failures~ will be updated on ~Monday~ Wednesday.
* Draw some annotations …

Fix annotation shapefile export and import

---

docker-compose.swagger.yml
nginx/Dockerfile.api
nginx/Dockerfile.tiler
nginx/etc/nginx/conf.d/api.conf
nginx/etc/nginx/nginx.conf

In addition to upgrading Nginx:
- Add an explicit `error_log` directive
- Revert `sendfile` to its default (`off`)
- Simplify `set_real_ip_from` configuration
- Centralize `limit_req*` configuration
- Update rate limit status code to 429 (default is 503)
First, run `bootstrap` to ensure that the most up-to-date container images are built.
Then, use `server` to ensure that the development environment via Nginx is still operational. For the API that's http://localhost:9100/. The Nginx fronted tile service will be used automatically (just open an ingested project).

Upgrade Nginx to latest stable release

---

nginx/Dockerfile.api

A previous PR (https://github.com/raster-foundry/raster-foundry/pull/3800/) attempted to force creation of the /srv/dist by
copying over a single file into the directory. However, this causes
errors for actually built versions of the nginx container used in
staging/production. Two fixes for setting up an environment were
included in the previous PR so it seems safe to revert this one.

Revert change to COPY in Dockerfile.api

---

app-backend/build.sbt
app-backend/project/Version.scala
app-backend/project/plugins.sbt
app-backend/sonatype.sbt
app-backend/version.sbt

Add [sbt-sonatype](https://github.com/xerial/sbt-sonatype) plugin to support publishing to Maven Central. 
Resolves #3546 
Next, we'll need to refactor artifact naming, add sbt-git, and create gpg signing keys for Raster Foundry. 
See: #3793
We should evaluate the scope of some of the sbt build variables. I think some use of `ThisBuild` and `Global` seems arbitrary.
#3788 provides an explanation as to why we're versioning the artifact as `1.8.0-SNAPSHOT`.
```bash
vagrant@vagrant:/opt/raster-foundry$ docker-compose run --rm --no-deps api-server batch/clean && docker-compose run --rm --no-deps api-server batch/assembly
...
[info] SHA-1: 0362ccf705fcb81e415da038ee4d589373c9efa2
[info] Packaging /opt/raster-foundry/app-backend/batch/target/scala-2.11/rf-batch.jar ...
[info] Done packaging. …
```

Add sbt-sonatype plugin to support publishing to Maven Central

---

app-backend/api/src/main/scala/thumbnail/Routes.scala
app-backend/common/src/main/scala/S3.scala
app-frontend/src/app/services/common/thumbnail.service.js

This PR adds a new endpoint `thumbnails/sentinel` that proxies a thumbnail request in order to 
handle the requester-pays change.
~ [ ] Symlinks from new migrations present or corrected for any new migrations~
I had to modify the URI => Bucket, Key method in `common.S3`. But it's a rather innocuous change that allows us to handle one more URI style.
* Browse for some sentinel and see some thumbnails!

Add proxy for sentinel thumbnails to handle requester-pays

---

app-backend/common/src/main/scala/S3.scala
app-backend/db/src/main/scala/com/azavea/rf/database/ExportDao.scala
app-frontend/src/app/pages/user/settings/connections/connections.html
app-frontend/src/app/services/projects/project.service.js

This PR fixes lab analysis export metadata to use empty `NodeMetadata` instead.
* Create an analysis with NDVI and export
Closes https://github.com/azavea/raster-foundry-platform/issues/438

Fix lab analysis export metadata

---

app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/Scene.scala
app-backend/db/src/main/scala/com/azavea/rf/database/SceneWithRelatedDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/SceneWithRelatedDaoSpec.scala

This PR makes it so that when listing scenes (not for a specific project) we don't query and return the images with each scene.
* Browse for scenes in the Raster Foundry repository and check that no scenes are returned with images
Closes #3787

Don't return scene images in scene list queries

---

app-frontend/src/app/pages/projects/edit/scenes/scenes.html
app-frontend/src/app/pages/projects/edit/scenes/scenes.module.js

This PR passed the current map bounds to the browse mode so that the map view does not change when entering browse mode.
* go to a project
* start browsing for scenes
* notice that the map view does not change

Persist map bounds when entering browse mode

---

app-backend/db/src/main/scala/com/azavea/rf/database/SceneToProjectDao.scala
app-frontend/src/app/pages/projects/edit/scenes/scenes.module.js

This PR uses the doobie streaming API to filter out scenes and stop getting scenes from scenes_to_projects
when the scenes won't contribute to the visible layer.
There's a project called "Landsat only central america" or something that is a fairly deep set of stacks.
It's shared with everyone in staging.
* Go to staging and try to view some tiles for deep stacks
* It might not work 100% first time, but future refreshes of the same layer should succeed, and also if you bump the number of tile servers slightly it should succeed (difficult to compare with prod for the tile servers reason)
Helps with #3766

Only mosaic scenes if they contribute to the visible layer

---

app-backend/db/src/main/scala/com/azavea/rf/database/OrganizationDao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/TeamDao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/UserGroupRoleDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/TeamDaoSpec.scala
app-frontend/src/app/components/settings/addUserModal/addUserModal.module.js

This PR enables auto-accepting team invitations if the user being added is in the same organization as this team. No emails will be sent in this case. 
We would not want to create a migration to deal with existing pending invitations, because, if done correctly, emails have already been sent to those pending users.
* CI since it tests this
* Create a new team or use an existing one
* Find some users in the same organization as the team and add them to this team. Make sure …

Auto accept team invitation if user is in same organization

---

app-backend/db/src/main/scala/com/azavea/rf/database/SceneToProjectDao.scala

This PR switches back to a coveredBy filter from a within filter and quiets logs.
I originally had a coveredBy filter that I thought was the cause of the holes in the resulting tile layers,
eventually figured out that the holes were caused by something else, and never changed the filter back.
Now, we're failing to exit the stream processing early ever (see papertrail -- search "stream?"), which
is likely caused by using the more restrictive within filter instead of the coveredBy filter (see [jts docs](https://locationtech.github.io/jts/javadoc/org/locationtech/jts/geom/Geometry.html#within(org.locationtech.jts.geom.Geometry))).
* you can't unless you have a deep stack locally
* on that note, I tried the staging db locally, and the dev environment hated it
* so we just have to test on …

Use coveredBy geometry filter in scene to project stream

---

app-backend/db/src/main/scala/com/azavea/rf/database/SceneToProjectDao.scala

This PR removes a misleading log statement. See [papertrail](https://papertrailapp.com/groups/4082193/events?q=program%3Astaging%2Ftile-server&focus=966068552857686026).
Apparently we are exiting early from the stream, so that's going well, but the logging message was
incorrect all the time. :man_shrugging: It looked like it should have been correct to me, but it definitely
wasn't.
* look at papertrail above to confirm that this logging statement was a lie

Remove option emptiness check for early stream exit

---

Jenkinsfile
Jenkinsfile.release

When the `apply` subcommand of `infra` is applied, ensure that the Rollbar access token needed to alert the service of a new deployment is available.
See: http://jenkins.staging.rasterfoundry.com/job/Raster%20Foundry/job/raster-foundry/job/PR-3858/3/console

Add Rollbar access token to environment for infra

---

app-backend/batch/src/main/scala/com/azavea/rf/batch/ast/RfmlRddResolver.scala
app-backend/batch/src/main/scala/com/azavea/rf/batch/ast/package.scala
app-backend/batch/src/main/scala/com/azavea/rf/batch/export/spark/Export.scala
app-backend/batch/src/main/scala/com/azavea/rf/batch/ingest/spark/Ingest.scala
app-backend/batch/src/test/resources/export/localJob.json
app-backend/batch/src/test/scala/com/azavea/rf/batch/export/model/ExportDefinitionSpec.scala
app-backend/common/src/main/scala/utils/CogUtils.scala
app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/ExportLayerDefinition.scala
app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/MosaicDefinition.scala
app-backend/db/src/main/scala/com/azavea/rf/database/ExportDao.scala
app-backend/tile/src/main/scala/tool/TileResolver.scala
app-backend/tool/src/main/scala/ast/MapAlgebraAST.scala
app-backend/tool/src/main/scala/maml/MamlAdapter.scala
app-backend/tool/src/main/scala/maml/TileNodes.scala
app-tasks/rf/src/rf/models/base.py
app-tasks/rf/src/rf/uploads/landsat_historical/factories.py
app-tasks/rf/src/rf/uploads/modis/factories.py
docker-compose.yml

This PR makes COGs export-able as project exports. It does not accomplish making them exportable
in ASTs. I'm not sure how to do the second part yet.
It also includes some ancillary fixes, like:
- telling the tile-server about the COURSIER_CACHE
- fixing ingest size bytes parameters that were never deleted for Landsat 4/5 import and MODIS import
~It's a little bit difficult to imagine currently how the AST export will look.~ Not anymore! ~In multiband export, it's fairly~
~easy -- the components of an export are scenes, and scenes have types, and scene types tell us how~
~to get an RDD for them. For AST exports, in the project branch, we rely on the ingested layer in S3~
~pretty heavily. I think we might need to reconsider what AST export definitions look like, but I'm not~
~sure about …

Make COG export work

---

app-frontend/src/app/pages/projects/edit/browse/browse.module.js
app-frontend/src/app/pages/projects/edit/colormode/colormode.controller.js
app-frontend/src/app/pages/projects/edit/colormode/colormode.html
app-frontend/src/app/pages/projects/edit/edit.module.js

Promise chaining was also set up in a way that promises were being executed out of order (branching vs chaining)
-~Styleguide updated, if necessary~
* Create a new project
* add scenes to it
* go to the color mode view directly, do not refresh the page, do not pass go
* Verify that single band and custom color mode options are available as they should be
Closes #3704

Force re-fetching datasources after adding scenes to project

---

app-backend/api/src/main/scala/shape/Routes.scala
app-frontend/src/app/components/vectors/vectorImportModal/vectorImportModal.html

During backend processing, we emit a message that indicates shapefiles should be in EPSG:4326 in the event of a failure. This change set adds similar note to the shapefile upload control so that users have the ability know about the requirement prior to upload.
- After checking out this branch, use `server` to bring up the application
- Navigate to Data > Vector
- Click **Import Shape** and ensure the text matches what's in the PR
Fixes …

Add note about support for EPSG:4326 shapefiles only

---

app-frontend/src/app/components/lab/inputNode/inputNode.html
app-frontend/src/app/components/lab/inputNode/inputNode.module.js

The generic datasource does not have any bands defined on it, and we want the user to still be able to specify bands without backing out and modifying the datasource.
* Change the datasource for a scene / project to be generic (no bands defined)
* Verify that you can still set bands in the lab, and the previews work as expected
Closes #3844

Allow defining band in lab if datasource has none

---

app-frontend/src/assets/styles/sass/components/_button.scss
app-frontend/src/assets/styles/sass/theme/high-contrast/components/_button.scss

Fixes fractions of a pixel causing copy button text in the lab share modal to overflow in the high contrast color them
* Use the overrides webpack config file to change your theme to 'high-contrast' 
* Create an analysis and click the share button on a node once you've set the input nodes
* Verify that the copy buttons no longer overflow and cause the "y" to be on the next line **in Firefox**
Closes #3866

Fix copy button overflow in firefox

---

app-frontend/src/app/pages/projects/edit/scenes/scenes.html
app-frontend/src/app/pages/projects/edit/scenes/scenes.module.js

This PR fixes a bug so that reordering scene items on sidebar reflects the real order you intend them to have.
This fix is actually a workaround due to a bug (that still has not been fixed it seems) in the library we use to help implement reordering.
* Go to a project with some scenes
* Reordering them (especially moving items down one position) should respect the order you have specified.
Closes #3344

Fix scene item sidebar reorder bug on frontend

---

app-frontend/src/app/components/projects/projectAddScenesModal/projectAddScenesModal.html
app-frontend/src/app/components/projects/projectAddScenesModal/projectAddScenesModal.module.js
app-frontend/src/app/components/projects/projectCreateModal/projectCreateModal.controller.js
app-frontend/src/app/components/scenes/importList/importList.module.js
app-frontend/src/app/components/scenes/sceneImportModal/sceneImportModal.controller.js
app-frontend/src/app/components/scenes/sceneImportModal/sceneImportModal.html
app-frontend/src/app/pages/imports/datasources/detail/detail.module.js
app-frontend/src/app/pages/imports/raster/raster.module.js
app-frontend/src/app/pages/projects/edit/scenes/scenes.module.js

This PR adds links directing to raster import status pages (should be either project scene list page or raster import list page) at the last step of scene import modal based on where the modal is initiated.
This PR reflects the re-scoped requirements mentioned in the card it closes since the other parts are currently being handled in a WIP card: https://github.com/raster-foundry/raster-foundry/issues/1602 -- mutually agreed with @alkamin 
* Test scene import originated from …

Link to status page upon successful raster upload

---

app-backend/api/src/main/scala/config/Config.scala
app-backend/api/src/main/scala/exports/Routes.scala
app-backend/api/src/main/scala/exports/package.scala
app-backend/api/src/main/scala/healthcheck/Healthcheck.scala
app-backend/api/src/main/scala/project/Routes.scala
app-backend/api/src/main/scala/scene/Routes.scala
app-backend/api/src/main/scala/shape/Routes.scala
app-backend/api/src/main/scala/thumbnail/Routes.scala
app-backend/api/src/main/scala/token/Token.scala
app-backend/api/src/main/scala/uploads/Credentials.scala
app-backend/api/src/main/scala/uploads/Routes.scala
app-backend/api/src/main/scala/user/Auth0User.scala
app-backend/api/src/main/scala/user/DropboxUser.scala
app-backend/api/src/main/scala/user/Routes.scala
app-backend/api/src/main/scala/utils/Auth0Exception.scala
app-backend/api/src/main/scala/utils/Auth0Util.scala

Remedy the warning messages and use `SuppressWarnings` where a straightforward solution isn't obvious. Also, clean up imports across all files touched.
There is still one **Match instead of partial function** that I was unable to make go away in `scene.Routes.scala:335`.
Execute the following command and confirm the Scapegoat output:
```bash
$ docker-compose run --rm --no-deps api-server api/scapegoat
...
[info] [scapegoat] Removing scapegoat class …
```

Remove Scapegoat errors for API project

---

app-backend/authentication/src/main/scala/Authentication.scala

Remedy the warning messages emitted by Scapegoat. Also, clean up imports across all files touched.
Execute the following command and confirm the Scapegoat output:
```bash
$ docker-compose run --rm --no-deps api-server authentication/scapegoat
...
[info] [scapegoat] Removing scapegoat class directory: /Users/hcastro/Projects/raster-foundry/app-backend/authentication/target/scala-2.11/scapegoat-classes
[info] [scapegoat] setting output dir to …
```

Remove Scapegoat errors for authentication project

---

docs/architecture/adr-0020-access-control-and-organizations.md
docs/architecture/adr-0023-text-array-object-acrs.md

This PR adds an ADR for object-level ACRs in text arrays.
Closes https://github.com/azavea/raster-foundry-platform/issues/436

Add an ADR for object-level ACRs in text arrays

---

app-backend/api/src/main/scala/uploads/package.scala
app-backend/common/src/main/scala/S3.scala
app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/SceneType.scala

Fixes two issues:
1. exports were failing for Avro tiles because SceneType could not be serialized in spark
2. listing tifs during an s3 upload was failing
- Export a project with an avro scene through the UI (grab the ID from the server logs)
- Run the export: `./scripts/console batch "rf export <export-id>"`
- Export a project with a COG scene through the UI (grab the id from the server logs) and run the export
- Export an analysis with an avro scene …

Fix Exports and S3 import

---

app-frontend/src/app/components/scenes/sceneImportModal/sceneImportModal.controller.js
app-frontend/src/app/components/scenes/sceneImportModal/sceneImportModal.html

This PR
- sets `uploadStatus` to `COMPLETE` after finish uploading COG scenes
- triggers a page refresh after clicking `Done` to get a new list of imported rasters
- shows correct input boxes for urls, ids, etc., based on cog or non-cog tab selections
* Import a COG scene and check if `uploadStatus` is set to `COMPLETE` in `PUT` request upon successful upload.
* Import a non-COG scene and check if `uploadStatus` is set to `UPLOADED ` in `PUT` request upon successful upload. …

Set uploadStatus to COMPLETE after a successful COG upload

---

app-frontend/src/app/components/exports/exportAnalysisDownloadModal/exportAnalysisDownloadModal.module.js
app-frontend/src/app/components/map/labMap/labMap.module.js
app-frontend/src/app/components/permissions/permissionModal/permissionModal.html
app-frontend/src/app/components/permissions/permissionModal/permissionModal.js
app-frontend/src/app/pages/lab/browse/analyses/analyses.html
app-frontend/src/app/pages/lab/browse/analyses/analyses.js
app-frontend/src/app/pages/projects/edit/edit.html
app-frontend/src/app/pages/projects/edit/edit.module.js

This PR fixes frontend bugs so that:
- lab export modal fetches a fresh list of exports every time you open it
- lab map's export control gets fresh acting user's dropbox credential every time you use the control
- permission modal's content depends on if the acting user is current object's owner
- permission tab's appearance depends on if the acting user is current object's owner
* For dropbox credential test:
- Delete your dropbox credential from DB.
- Head to lab, create …

Fix lab export modal and dropbox check; Fix permission modal and tab

---

app-backend/api/src/main/scala/uploads/QueryParameters.scala
app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/QueryParameters.scala
app-backend/db/src/main/scala/com/azavea/rf/database/filters/Filterables.scala
app-frontend/src/app/components/scenes/sceneImportModal/sceneImportModal.html
app-frontend/src/app/pages/imports/raster/raster.html
app-frontend/src/app/pages/imports/raster/raster.module.js
app-frontend/src/app/pages/projects/edit/scenes/scenes.html
app-frontend/src/app/pages/projects/edit/scenes/scenes.module.js
app-frontend/src/assets/styles/sass/components/_alert.scss

This PR adds alerts to the imports page as well as the project scene list to inform the user of imports in progress. This should alleviate the sense of confusion that occurred after the import flow was completed without any indication that something happened.
* Upload some scenes (not into a project) see that the message appears on the import page
* Upload some scenes into a project and see that the message appears on the project scene list
Closes #1602

Show imports in progress

---

app-backend/db/src/main/scala/com/azavea/rf/database/SceneDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/SceneDaoSpec.scala

This PR checks scene ingest status before and after a `PUT` request, then determines if to kick off ingest based on it (and how long it has been hanging at `INGESTING`, if this is the case). It updates the associated property test as well to reflect this process.
This still seems relevant/necessary after #3925 🌯 
* `batch/assembly`
* `./scripts/server`
* Add a scene to a project and grab the scene id
* Watch the log and make sure an ingest job is submitted
* `docker-compose build batch`
* `./scripts/console …

Fix scene double ingest bug

---

app-backend/tile/src/main/scala/routes/HealthCheckRoute.scala

Remove non-ASCII characters from health check cache key. `nextString()` generates non-ASCII characters, but `alphanumeric()` does not.
- Run the code in the Scastie project and compare the outputs: https://scastie.scala-lang.org/jslDiv0mTJGDrUKo8qMTeA
- Spin up the tile service (with `server`) and hit the health check endpoint
```bash
$ curl "http://localhost:9101/healthcheck/
```
Fixes https://papertrailapp.com/groups/4082183/events?focus=9694594081973412 …

Fix non-ASCII characters in health check cache key

---

app-backend/api/src/main/scala/exports/Routes.scala
app-backend/api/src/main/scala/healthcheck/Routes.scala
app-backend/api/src/main/scala/project/Routes.scala
app-backend/api/src/main/scala/scene/Routes.scala
app-backend/api/src/main/scala/shape/Routes.scala
app-backend/api/src/main/scala/thumbnail/Routes.scala
app-backend/api/src/main/scala/uploads/Routes.scala
app-backend/api/src/main/scala/user/Auth0User.scala
app-backend/api/src/main/scala/user/Routes.scala
app-backend/authentication/src/main/scala/Authentication.scala
app-backend/batch/src/main/scala/com/azavea/rf/batch/aoi/UpdateAOIProject.scala
app-backend/batch/src/main/scala/com/azavea/rf/batch/export/CheckExportStatus.scala
app-backend/batch/src/main/scala/com/azavea/rf/batch/export/CreateExportDef.scala
app-backend/batch/src/main/scala/com/azavea/rf/batch/landsat8/ImportLandsat8C1.scala
app-backend/batch/src/main/scala/com/azavea/rf/batch/notification/NotifyIngestStatus.scala

In an attempt to clean up imports in Raster Foundry, some imports for
postgres implicits were accidentally removed in the following commits:
- 3d183b
- bb05fd
- a5e3d8
Apparently, at compile time there is no way for the compiler to
know if the implicits are being used so IntelliJ will remove it
when optimizing the imports. This reverts that specific change.
There aren't really great testing instructions - there is a lot of surface area exposed unfortunately and likely bugs that we haven't encountered yet. There is _one_ which I have included here that is known to be fixed.
* Re-assemble batch jar
* Start server and front-end, create a new AOI project. Grab its ID from the URL in the browser.
* Run `./scripts/console batch "rf update-aoi-project <ID>"` which should not error

Add postgres implicit imports back to source

---

Jenkinsfile
app-backend/Dockerfile.build
app-backend/build.sbt
app-backend/project/plugins.sbt
app-backend/sonatype.sbt
app-backend/version.sbt
docker-compose.test.yml
scripts/cibuild
scripts/cipublish

Add support for [sbt-git](https://github.com/sbt/sbt-git) and PGP signed build artifacts. This PR is in support of publishing build artifacts to Maven Central.
Connects #3793 
Resolves #3788 
After this is merged, we need to complete https://github.com/azavea/raster-foundry-platform/issues/447.
First, test the `assembly` stage:
```bash
vagrant@vagrant:/opt/raster-foundry$ docker-compose -f docker-compose.test.yml run --rm build api/assembly
```
Next, define a `.env` file so we can test publishing to the OSSRH:
```bash
PGP_PASSPHRASE=...
PGP_KEY_HEX=...
SONATYPE_USERNAME=...
SONATYPE_PASSWORD=...
```
And finally, publish:
```bash
vagrant@vagrant:/opt/raster-foundry$ docker-compose -f docker-compose.test.yml run --rm build gitSnapshots api/publishSigned
```
See: …

Add support for sbt-git and PGP signed build artifacts

---

app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/InputDefinition.scala

The compiler reports that `|@|` in class `SemigroupalOps` is deprecated. Replace with `mapN`.
Execute the following command and confirm the Scapegoat output:
```bash
$ docker-compose run --rm --no-deps api-server datamodel/scapegoat
...
[info] [info] [scapegoat] 117 activated inspections
[info] [info] [scapegoat] List(.*/datamodel/.*) ignored file patterns
[info] [info] [scapegoat] Analysis complete: 80 files - 0 errors 0 warns 0 infos
[info] [info] …
```

Replace deprecated (a |@| b) with (a, b).mapN

---

app-backend/common/src/main/scala/utils/CogUtils.scala

Fixes a bug where the highest resolution was not being rendered
by the tile server
Before:
After:
* View the same COG with a known resolution to staging + this branch
* Compare highest zoom level

Choose AutoHigherResolution for OverviewStrategy

---

app-backend/backsplash/Dockerfile
app-backend/backsplash/src/main/scala/Server.scala
app-backend/backsplash/src/main/scala/services/HealthCheckService.scala
app-frontend/src/app/services/projects/project.service.js
docker-compose.test.yml
docker-compose.yml

This PR makes routes consistent with the existing tile server for mosaics and adds
a middleware that makes trailing slashes more ergonomic.
* bring up all of your backend services
* note that the config variable TILE_SERVER_LOCATION is in the docker-compose file api-server environment section pointing to backsplash
* try to render some tiles for an avro scene
Closes #3938

Make routes consistent and add autoslash middleware

---

app-backend/api/src/main/scala/scene/Routes.scala
app-tasks/rf/src/rf/ingest/io.py
app-tasks/rf/src/rf/uploads/modis/create_geotiff.py
app-tasks/rf/src/rf/uploads/planet/create_scenes.py
app-tasks/rf/src/rf/uploads/planet/factories.py

This PR makes planet import processing produce COGs instead of scenes that need to be ingested.
I attempted to solve the resolution issue at the same time as I was working on this, but I was unable to.
Work for that will continue under #3972 at some point.
* bring up your server and frontend
* get a planet token and associate it with your user
* find a planet scene you have access to (at least a month old, in california)
* add it to a project
* get the id for the most recently created upload
* `docker-compose build batch`
* `./scripts/console batch 'rf process-upload <upload id>'`
Closes #3658

Make planet uploads COGs

---

app-frontend/src/app/pages/projects/edit/edit.module.js

This PR clears `sceneList`, `orderedSceneIds`, and `sceneLayers` when `sceneCount` becomes 0 in a project, which is the case when a user deletes all scenes from a project.
* Spin up frontend
* Add scenes to a project
* Delete all of them one by one
* Make sure frontend successfully reflects it by deleting them from map, sidebar, and project, without needing to refresh page
Closes #3981

Fix scene item deletion frontend bug

---

app-frontend/src/app/pages/projects/edit/exports/new/new.controller.js
app-frontend/src/app/pages/projects/edit/exports/new/new.html
app-frontend/src/app/services/projects/project.service.js

This PR updates project export frontend to:
* simplify output processing options to just raw and color corrected
* use dropdown instead of secondary select panel
* preserve the old panel just in case we want to bring it back in the future
* Create a new project export. Don't change anything and export. Look at `exportOptions` -- `raw` field should be `false`, which is to indicate `Color corrected`.
* Create a new export. Select options from `Output processing`. Export. …

Simplify output processing options for project export frontend

---

app-backend/common/src/main/scala/utils/CogUtils.scala
app-tasks/rf/src/rf/ingest/io.py

This PR resamples imagery before merging tifs based on the maximum resolution of all the
imagery that's going to get merged. Without setting this, the target pixel size ends up being the pixel
size of the first image in the list, which, for Sentinel-2 imagery, is 6x less resolute than the maximum,
which ruins tiles.
I know there's a `-ps` option for `gdal_merge` that does what I'm doing here in one step, but when
I used that to go directly from JPEG2000 files to a merged tif with a target resolution in a single step,
file size blew up even worse than it's blowing up now.
Testing is hard because it takes forever, but I can show you, but here's what I'm doing:
* add a Sentinel-2 scene to a project
* ingest it
* add it to an analysis
* measure the side length at a high zoom level -- it …

Fix multiband COG creation for Sentinel-2 and Landsat

---

docker-compose.yml

TILE_SERVER_LOCATION was being specified in the `batch` container, when it should have been in `api-server`.
* Bring up the backend and frontend
* Verify that tile request are routing to port 8080

Fix TILE_SERVER_LOCATION environment variable

---

app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/AccessControlRule.scala
app-backend/db/src/main/scala/com/azavea/rf/database/meta/PermissionsMeta.scala
app-backend/db/src/main/scala/com/azavea/rf/database/meta/package.scala

This PR adds data model and meta for object level acr field.
* `./scripts/console api-server ./sbt` -> `project db` -> `console`
* Test that things like below should throw exceptions in your face:
- `ObjectAccessControlRule(SubjectType.All, Some("id"), ActionType.View).toObjAcrString`
- `ObjectAccessControlRule(SubjectType.User, None, ActionType.View).toObjAcrString`
- `ObjectAccessControlRule.unsafeFromObjAcrString("ALL;id;VIEW")`
- …

Add object ACR data model and meta

---

app-backend/backsplash/.dockerignore
app-backend/backsplash/Dockerfile
app-backend/build.sbt
docker-compose.test.yml
docker-compose.yml
nginx/Dockerfile.backsplash
nginx/etc/nginx/conf.d/backsplash.conf
scripts/cipublish

* Add backsplash `Dockerfile`
* Setup backsplash assembly stage
* Build and publish backsplash and nginx-backsplash
Depends on https://github.com/raster-foundry/raster-foundry/pull/3954
The compile time was insane, and the JAR produced is `250MB`.
```bash
[info] SHA-1: be250884bd0d23790cd227b8d976a3784efa4411
[info] Packaging /opt/raster-foundry/app-backend/backsplash/target/scala-2.11/backsplash-assembly.jar ...
[info] Done packaging.
[success] Total time: 1842 s, completed Aug 28, 2018 7:36:31 PM
```
Ensure images build successfully:
```bash
$ git cherry-pick 0d066d6
$ docker-compose -f docker-compose.test.yml run --rm --no-deps build backsplash/assembly
$ docker-compose -f docker-compose.test.yml -f docker-compose.yml build backsplash nginx-backsplash
```

Create and publish backsplash images

---

app-backend/batch/src/main/resources/application.conf
app-backend/batch/src/main/scala/com/azavea/rf/batch/util/conf/Config.scala

This PR removes a bunch of auth0 configuration that we never use in the batch project.
Since those values of the auth0 config were never used, I opted to remove them from the config,
rather than add the environment variables in deployment.
This is probably a good time to revisit #3837, since we couldn't run some async tasks because they
were missing environment variables for configuration that they didn't use. That's a drag!
* `grep` for the removed values in `auth0Config.foo` to prove they're unneeded:
```
james@rf-dev-env ~/r/a/batch> rg "auth0Config."
src/main/scala/com/azavea/rf/batch/notification/NotifyIngestStatus.scala
29:    } yield projects.map(_.owner).distinct.filter(_ != auth0Config.systemUser).map(_.mkString)
182:    if (scene.owner == auth0Config.systemUser) { …
```

Remove auth0 configuration that isn't used

---

app-tasks/Dockerfile
app-tasks/completion.bash

This PR adds tab completion to the rf cli in the batch container.
Completed while waiting on processes working on fixing the COG resolution bug, it's the only part of
that work that accomplishes its goal, so separating and opening a PR for it.
* rebuild batch container
* `rf i<TAB>`
* `rf pro<TAB>`
* etc
Closes #4003

Add tab completion to rf cli

---

app-backend/backsplash/Dockerfile
app-backend/batch/src/main/scala/com/azavea/rf/batch/Main.scala
app-backend/batch/src/main/scala/com/azavea/rf/batch/cogMetadata/HistogramBackfill.scala
app-backend/build.sbt
app-backend/db/src/main/scala/com/azavea/rf/database/LayerAttributeDao.scala
app-frontend/src/app/services/projects/project.service.js
docker-compose.yml

This PR adds a `batch` subproject job for backfilling histograms for COG scenes.
* find a cog scene id from your database
* check whether it has a histogram in the `layer_attributes` table -- `select * from layer_attributes where layer_name = 'the_id' and name = 'histogram';` -- it shouldn't
* reassemble your batch jar
* `./scripts/console batch bash`
* `java -cp /opt/raster-foundry/jars/rf-batch.jar com.azavea.rf.batch.Main cog-histogram-backfill <the scene id>` 
* run the sql query again
* also see if you have some other cog scenes without histograms
* run the command without any parameters
* you should get histograms in the `layer_attributes` table for everything that wasn't in there to begin with
Closes #3901

Add task to backfill COG histograms

---

app-backend/db/src/main/scala/com/azavea/rf/database/ObjectPermissions.scala
app-backend/db/src/main/scala/com/azavea/rf/database/ProjectDao.scala

This PR adds an `ACR` trait to be extended by first class object `Dao`s.
~Marked as WIP since test instructions need to be updated.~
* ~Coming soon ...~
**Updates on Sep 7th:**
* Run migrations in `150.scala` but don't run the first block (line 9 -21) yet, since the `visibility` filter will be implemented in the card after the next of this set of ACR refactors (the next one is property test for `ProjectDao` `acrs`).
* `./scripts/console api-server ./sbt` -> `project db` -> …

Add ACR trait

---

app-backend/datamodel/src/test/scala/com/azavea/rf/datamodel/implicits/Generators.scala
app-backend/db/src/test/scala/com/azavea/rf/database/ProjectDaoSpec.scala
app-backend/db/src/test/scala/com/azavea/rf/database/PropTestHelpers.scala

This PR adds property tests for `ProjectDao` that extends the `ObjectPermissions` trait, which enables the former to use `acrs` for interacting with permissions.
* CI
Closes https://github.com/raster-foundry/raster-foundry/issues/3921

Add property tests for acrs in ProjectDao

---

app-backend/common/src/main/scala/utils/CogUtils.scala
app-backend/common/src/main/scala/utils/GTHack.scala

This PR fixes overviews selection strategy, though requires some help to check it out as there were some problems in reproducing the issue.
Closes https://github.com/raster-foundry/raster-foundry/issues/3997
Related to https://github.com/locationtech/geotrellis/pull/2802
Will be in WIP until it will be fully approved by RF team

Use AutoHigherResolution

---

app-frontend/src/app/components/filters/daterangeFilter/daterangeFilter.html
app-frontend/src/app/components/filters/daterangeFilter/daterangeFilter.module.js
app-frontend/src/app/components/scenes/sceneFilterPane/sceneFilterPane.module.js

Add checkbox for using UTC date boundaries or local
Fix resulting inconsistencies 
UTC:
Local (observe results for April 18th (UTC) in the results):
This component makes the assumption that date ranges are either a UTC date beginning/end or a local, and doesn't check to verify the latter. We don't allow users to set an exact time in the frontend, so this shouldn't be an issue. If the user specifies a datetime that doesn't line up with either, it will default to local and …

Allow user to search scenes using UTC or local time on frontend

---

app-frontend/src/app/pages/projects/edit/scenes/scenes.html
app-frontend/src/app/pages/projects/edit/scenes/scenes.module.js

Add download button to scenes in the scene list view
* Verify the download button works as expected
Closes #2835 
Depends on https://github.com/raster-foundry/raster-foundry/pull/4014 (rebase when it's merged)

Add download button to scene list

---

app-backend/api/src/main/scala/categories/Routes.scala
app-backend/api/src/main/scala/datasource/Routes.scala
app-backend/api/src/main/scala/exports/Routes.scala
app-backend/api/src/main/scala/license/LicenseRoutes.scala
app-backend/api/src/main/scala/project/Routes.scala
app-backend/api/src/main/scala/shape/Routes.scala
app-backend/api/src/main/scala/tags/Routes.scala
app-backend/api/src/main/scala/toolrun/Routes.scala
app-backend/api/src/main/scala/tools/Routes.scala
app-backend/api/src/main/scala/uploads/Routes.scala
app-backend/db/src/main/scala/com/azavea/rf/database/AoiDao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/Dao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/DatasourceDao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/MapTokenDao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/OrganizationDao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/PlatformDao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/ProjectDao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/TeamDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/ProjectDaoSpec.scala

This PR removes a default argument from one of the implementations of `page` in `Dao.QueryBuilder`,
since that for some mysterious reason causes `assembly` to throw the method straight into the
garbage.
Output of decompiling the assembled api-server jar, searching for `page` in `Dao.java`:
```java
*  com.azavea.rf.database.Dao$QueryBuilder$$anonfun$page
public <T> Free<connection.ConnectionOp, List<T>> pageOffset(PageRequest pageRequest, composite.Composite<T> evidence$3) {
fragment.Fragment qual$1 = this.selectF().$plus$plus(package$.MODULE$.Fragments().whereAndOpt(this.filters())).$plus$plus(Page$.MODULE$.apply(pageRequest, Page$.MODULE$.apply$default$2()));
public <T> Free<connection.ConnectionOp, PaginatedResponse<T>> page(PageRequest pageRequest, fragment.Fragment selectF, …
```

Remove default argument from page with ordering method

---

deployment/ansible/roles/raster-foundry.jenkins/tasks/main.yml

Add an additional cron task that cleans up the Jenkins workspace Coursier cache weekly.
I also removed the `useSecurity` resetting via `config.xml` because Jenkins appears to reset it back to `true` after every restart.
- Install dependent Ansible roles
- Execute `ansible-playbook` against the current Jenkins instance
```bash
$ ansible-playbook -i deployment/ansible/inventory/jenkins deployment/ansible/raster-foundry-jenkins.yml
```
- Ensure `Setup weekly …

Add cron task to clean up Coursier cache

---

Vagrantfile
app-backend/backsplash/src/main/scala/Server.scala
app-backend/backsplash/src/main/scala/nodes/ProjectNode.scala
app-backend/backsplash/src/main/scala/services/MosaicService.scala
app-backend/common/src/main/scala/utils/CogUtils.scala
app-backend/db/src/main/scala/com/azavea/rf/database/SceneToProjectDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/SceneToProjectDaoSpec.scala
app-tasks/rf/src/rf/commands/ingest_scene.py
docker-compose.yml

This PR has morphed a bit as various blockers were discovered. Here's what it does:
* Adds the http4s plumbing needed to render single-band tiles
* Adds single-band visualization
* Fixes multi-band COG visualization
* Uses stored histograms for COGs
* Adds COG histograms for scenes after ingest
* Fixes port conflict with backsplash and nginx
Landsat Avro single-band
Landsat Avro multi-band
Planetscope COG single-band
Planetscope COG multi-band
Landsat  COG single-band
COG multi-band
* MultibandMosaicService has been renamed to MosaicService, since it now also supports single-band.
* No special handling of `NODATA` has been performed. I investigated it a bit, and from what I can tell, `withNoDataColor` seems to be applied appropriately, so I'm not sure what's going wrong. There's already …

Implement single-band "identity" visualization + extras

---

app-backend/api/src/main/scala/user/Auth0User.scala
app-backend/api/src/main/scala/user/Routes.scala

This PR updats the `users/me` endpoint so that it returns the user object from db based on the authenticated requesting user's id.
~I will check off the spec item once a PR is made for it.~
**Updated spec in here:**
https://github.com/raster-foundry/raster-foundry-api-spec/pull/45
* Grab a token
* `GET` to `/api/users/me` -- it should return an user object of the requesting user with all fields a user has
Closes #3910

Fix users/me endpoint

---

app-backend/tile/src/main/scala/LayerCache.scala
app-backend/tile/src/main/scala/image/SingleBandMosaic.scala
app-backend/tile/src/main/scala/tool/TileResolver.scala
app-frontend/src/app/components/lab/inputNode/inputNode.module.js
app-frontend/src/app/services/projects/project.service.js

This PR fixes band selection for single band mosaics. The original goal was to fix subtraction, but subtraction appeared to be the only broken op only because x - y = 0 always, so subtracting a band from itself always had worse results than adding or multiplying a band. Division should have had the same issue, but was unchecked.
There's still a "cannot cache object that's too big" error that happens, but you can ignore it. I'm not sure what's getting cached there but it doesn't hurt anything.
The demo image is histograms for a project with avro and cog scenes, up to you if you want to replicate that.
Look on my horrible colormap and despair!
* take a project to the lab (don't try to view it as a project first because there's a missing env variable right now and the tile server will die)
* …

Fix band selection for singleband mosaics

---

app-frontend/src/app/pages/projects/edit/aoi-approve/aoi-approve.controller.js
app-frontend/src/app/pages/projects/edit/aoi-approve/aoi-approve.html
app-frontend/src/app/pages/projects/edit/edit.module.js
app-frontend/src/app/pages/projects/edit/scenes/scenes.html
app-frontend/src/app/pages/projects/edit/scenes/scenes.module.js

Fix AOI approval regression fallout from the scene pagination change
The checkmark button now selects / deselects scenes on the current page instead of all of them
* Create an AOI project, add some scenes, then use the database to make some of them unapproved
* Verify that the messages showing that some scenes await approval now shows
* Verify that approving and rejecting single scenes works, and the scene count on the scene list page updates appropriately
* Verify that you …

Paginate and fix AOI scene approval

---

app-frontend/src/app/pages/projects/list/list.controller.js

Probably missed when moving to paginated scenes
* Verify that there is no longer a JS error when reloading the scene list after creating a new project

Fix misnamed function call in project list controller

---

app-frontend/src/app/components/scenes/sceneImportModal/sceneImportModal.controller.js
app-frontend/src/app/components/scenes/sceneImportModal/sceneImportModal.html

Show an error message instead of hanging
Suggestions on error text are welcome.
* Create a cog import using an invalid s3 url (folder, etc)
Closes #4060

Add error message for failed s3 and cog uploads

---

app-backend/api/src/main/scala/scene/Routes.scala
app-backend/common/src/main/scala/S3.scala
app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/Image.scala
app-frontend/src/app/components/scenes/sceneDownloadModal/sceneDownloadModal.html
app-frontend/src/app/components/scenes/sceneDownloadModal/sceneDownloadModal.module.js

This PR uses the COG image for scene downloads if it's available.
I added to the copy in the issue a bit, since I think it was a little bit misleading about what needed
to happen for a Sentinel-2 scene to be downloadable
* have an ingested Sentinel-2 COG in your database (ingest one if you don't have it)
* browse for scenes
* try to download a non-Sentinel-2 scene (it should be fine)
* try to download a Sentinel-2 scene that hasn't been turned into a COG yet (it should not be fine -- you should get a message about adding it to a project)
* try to download a Sentinel-2 scene that has been turned into a COG (you should have one image available and it should be the COG)
* try to download a non-Sentinel-2 COG (it should also be fine)
Closes #3989

Use COG image if available for scene download

---

app-backend/.dockerignore

Add `backsplash/target` to app-migrations `.dockerignore` to reduce overall image size and prevent build failures that result from generated filenames being too long.
* see http://jenkins.staging.rasterfoundry.com/job/Raster%20Foundry/job/raster-foundry/job/test%252Ftnation%252Ffix-dockerignore/1/console
* Build a …

Add backsplash generated files to app-migrations .dockerignore

---

app-backend/db/src/main/scala/com/azavea/rf/database/Dao.scala

Add logs for successful (debug) and unsuccessful (error) database queries
Query log for an intentional typo
Our logger seems to simply prepend the logging level, and whatever then outputs it to STDOUT adds its own log level (always info) on top of it. That's kinda stupid.
Also noticed that this only adds logging to the default dao functions... there's a lot more. Should I tackle those in this PR?
* Verify that logs work for errors, and are not output for normal statements …

Add database query logging

---

app-frontend/src/app/pages/admin/organization/users/users.module.js

Add a "Remove User" button to users for admins
Admins cannot be removed directly - Remove an admin's role in order to allow removing them from the organization. This is not enforced by the API, but I thought it would be sensible to do here.
* Log in as `systems@rasterfoundry.com`, go to the public org and remove `dev@rasterfoundry.com`
* Log in as `dev@rasterfoundry.com` and verify that things still work (projects, scenes, searching, lab if using old tile server etc)
* Log …

Allow removing users from an organization

---

app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/User.scala
app-backend/db/src/main/scala/com/azavea/rf/database/ProjectDao.scala
app-frontend/src/app/components/permissions/permissionModal/permissionModal.html

This PR:
- scrubs the email from the owner object of projects and instead defaults to the first and last name of the owner. If those are not defined, falls back to "Anonymous"
- puts a requirement within the UI that the user have a first and last name defined to add permissions on their objects
@designmatty @jmorrison1847 Could use some attention/verification for styling and copy
* List projects that are shared with you and notice that the owner object of the returned projects no longer has an email address under the name property
* Test that if you have a first and last name defined that you can share
* Test that if you don't have a first and last name defined that you can not share
Closes https://github.com/azavea/raster-foundry-platform/issues/489

Require first and last name for sharing, scrub email

---

app-backend/db/src/main/scala/com/azavea/rf/database/SceneToProjectDao.scala

This PR adds a filter to remove pending scenes from mosaic definition construction.
* Open a project with some COG or ingested pending scenes, notice that they are not rendered
Closes #4084

Filter out pending scenes from mosaic definitions

---

app-frontend/src/app/components/aoiFilterPane/aoiFilterPane.html
app-frontend/src/app/components/filters/daterangeFilter/daterangeFilter.html
app-frontend/src/app/pages/user/settings/profile/profile.html
app-frontend/src/assets/styles/sass/theme/high-contrast/components/_filter.scss

This PR:
- fixes scene filter pane's date range UTC tooltip bug
- deletes name field from user profile page
- fixes AOI params' datasource display bug
**AOI filter pane**
**User profile**
**Scene date range filter**
* Go to an AOI project and edit AOI parameters, open up the filter pane, notice that there should be no additional divider under datasource dropdown
* Go to browse scenes, open up the filter pane, notice that date range filter contents should display on three separate lines and that the tooltip shows at the bottom of the cursor
* Go to user profile page, notice that the previously not editable name field is gone.
Closes #4111 
Closes #4117 
Closes #4087

Staging frontend bug fix: scene date UTC filter; User profile; AOI datasource filter

---

app-backend/api/src/main/scala/user/DropboxUser.scala
app-backend/project/Version.scala

This PR fixes an infinitely recursive call that was ruining dropbox connection. It also updates the dropbox sdk. It turned out there isn't actually anything wrong with our using the old SDK for what we were using it for, but now we're current, so that's nice I guess.
The actual problem is that for some reason `DummySessionStore.clear()` was being called somewhere in the dropbox connection flow. That was bad because, e.g.:
```scala
@ object Foo {
def bar(): Unit = this.bar
}
defined object Foo
@ Foo.bar
```
It never terminates. I don't know why it worked before then suddenly stopped, but anyway it's fixed now.
* clear your dropbox credential from a user
* unauthorize the raster foundry dev app from your dropbox account
* connect your dropbox account again
* it should succeed and you should …

Fix dropbox dummy session store

---

app-backend/batch/src/main/scala/com/azavea/rf/batch/Main.scala
app-backend/batch/src/main/scala/com/azavea/rf/batch/export/UpdateExportStatus.scala
app-tasks/rf/requirements.txt
app-tasks/rf/src/rf/commands/export.py

This PR fixes project export so that it should work with or without an AOI in the export options.
~This PR currently works. It is marked as WIP since the current python client RF is using is `0.6.0`, which points to the master branch of the spec, and which is not ideal. Per discussions with @notthatbreezy , I will take the below two steps before removing the WIP tag of this PR tomorrow:~
~1. a new release of Python client that points to the newest version of the spec (~1.11~1.12.0) instead of the master branch.~
~2. update the python client version in RF~
* Add an ingested scene to a project
* Create an export of the project (with or without an AOI)
* Grab the export id from db, or server log, or request from browser dev tool, etc
* (Optional) Edit platform settings so that it will send …

Fix project export

---

app-backend/db/src/main/scala/com/azavea/rf/database/ObjectPermissions.scala
app-frontend/src/app/components/scenes/importList/importList.html
app-frontend/src/app/components/scenes/importList/importList.module.js
app-frontend/src/app/index.routes.js
app-frontend/src/app/index.run.js
app-frontend/src/app/pages/admin/platform/projects/projects.html
app-frontend/src/app/pages/imports/raster/raster.html
app-frontend/src/app/pages/imports/raster/raster.module.js
app-frontend/src/app/pages/projects/edit/browse/browse.html
app-frontend/src/app/services/common/pagination.service.js
app-frontend/src/tpl-index.html

- adds a loading indicator that will be shown when transitioning to states with `resolves`. When a `resolves` async call took longer than expected there was no UI indication that anything was happening. With #4126, this can result in a seemingly unresponsive click for over four seconds.
- adds ownership based filtering to the imports list. This behaves similar to the projects filtering. The default filter is `owned` and is not initially forced as a query parameter.
**Updated on Oct. 1st:**
It also fixes:
- scene count on scene browse page
- the display of lower bound value of pagination count component
- the item type on platform projects page's pagination
- `ownership=inherited` case so that `visibility = PUBLIC` is excluded in the filter (except `shape`, which …

Filter imports by ownership

---

app-frontend/src/assets/styles/sass/layout/_navbar.scss

Implements a fix to the navbar inner content alignment which would adjust incorrectly on smaller screens.
**Before**
**After**
* Open a project with a relatively long name
* Resize the browser
* The nav layout should only get wonky when the user dropdown is nearest the project name.
Closes #3936

Fix navbar alignment on smaller screens

---

app-frontend/webpack.config.js

Use first defined HtmlWebpackPlugin definition, merging overrides, global, then env in order.
After changing heapLoad in overrides.js to 'asdf':
Didn't change order of global/env config merging because it may have unintended side effects and we don't override it there anyways.
* Create an overrides file which changes heapLoad to some nonsense string.
* in `tpl-index.html`, change the line to `if(... || true)` so heap tries to load in develop
* Start the frontend, load the …

Change webpack merge strategy to override HtmlWebpackPlugin

---

app-backend/api/src/main/scala/scene/QueryParameters.scala
app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/QueryParameters.scala
app-backend/db/src/main/scala/com/azavea/rf/database/Dao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/SceneWithRelatedDao.scala
app-frontend/src/app/components/scenes/importList/importList.module.js

This PR adds a query parameter so that it, by default, short circuits count for large scene queries, but returns real count of scene for pagination when specified.
* `GET` to `api/scenes?bbox=25.488281250000004,-24.96614015991296,52.9541015625,12.08229583736359&page=0&pageSize=20&sort=acquisitionDatetime,desc&isSceneBrowse=false` should give you the exact count of scenes (more than 100)
* `GET` to the above endpoint but use `&isSceneBrowse=true` or delete this query parameter -- it should give you 100 scenes
* Go to your raster data list. Check if such query parameter is used in requests.
Closes #4125

Fix raster data count for pagination

---

app-backend/db/src/main/scala/com/azavea/rf/database/Dao.scala
app-backend/db/src/main/scala/com/azavea/rf/database/ObjectPermissions.scala
app-frontend/src/app/components/scenes/importList/importList.module.js

This PR adds `visibility != 'PUBLIC'` in the `where` statement when listing first class objects with `ownershipType=shared`. It also flips the cases for `exactCount` qp when listing scenes.
* CI
* Go to your imported rasters. Make sure ownership filter works correctly, with `exactCount=true` sent as query param
* Go to a project and browse scenes. Make sure it returns not exact count of scenes when there are more than 100

Add visibility check to shared ownership type

---

app-backend/batch/src/main/scala/com/azavea/rf/batch/cogMetadata/HistogramBackfill.scala

This PR makes it so a single failed insert in histogram backfill doesn't short-circuit the whole game.
* Give an ingested COG in your database an ingest location of `'bogus'` or something else that won't work
* Assemble batch jar
* From batch container -- `java -cp /opt/raster-foundry/jars/rf-batch.jar com.azavea.rf.batch.Main cog-histogram-backfill that-scene-id`
* It should fail to insert the scene but not be mad at you and it shouldn't end up in `layer_attributes`
* `java -cp /opt/raster-foundry/jars/rf-batch.jar com.azavea.rf.batch.Main cog-histogram-backfill`
* everything should insert successfully except the scene you gave a status of `'bogus'` or whatever you picked to

Improve error tolerance of histogram backfill

---

CHANGELOG.md
app-backend/db/src/main/scala/com/azavea/rf/database/UploadDao.scala
app-tasks/rf/src/rf/commands/process_upload.py

This PR checks for the third job attempt before deciding to update upload status and makes the
"not sending any email" logging message quieter than `info`.
* throw a random exception into upload processing
* run with `AWS_BATCH_JOB_ATTEMPT` set to values below three and values >= 3
* confirm you only see attempts to send emails from the api server if the variable is set to a value >= 3

Make upload notification quieter

---

CHANGELOG.md
app-backend/api/src/main/scala/datasource/Routes.scala
app-backend/db/src/main/scala/com/azavea/rf/database/DatasourceDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/DataSourceDaoSpec.scala

This PR fixes the datasource delete bug and adds property tests for `isDeletable` function in `DatasourceDao`.
* Create two datasources and define bands
* Delete one of them to see if it works
* Import a scene using this other datasource
* Delete this other datasource and check if it works. Check if the scene is also deleted.
Closes #4138

Fix datasource delete bug

---

app-backend/backsplash/src/main/scala/Color.scala
app-backend/backsplash/src/main/scala/MamlAdapter.scala
app-backend/backsplash/src/main/scala/Server.scala
app-backend/backsplash/src/main/scala/color.scala
app-backend/backsplash/src/main/scala/io/Avro.scala
app-backend/backsplash/src/main/scala/io/Cog.scala
app-backend/backsplash/src/main/scala/io/Mosaic.scala
app-backend/backsplash/src/main/scala/nodes/ProjectNode.scala
app-backend/backsplash/src/main/scala/package.scala
app-backend/backsplash/src/main/scala/services/AnalysisService.scala
app-backend/backsplash/src/main/scala/services/MosaicService.scala
app-backend/build.sbt

This adds an initial analysis service that builds on the usage of Project nodes. It does not add the histogram support that is necessary for full integration as that is going to be dealt with in https://github.com/raster-foundry/raster-foundry/issues/4151
There is somewhat of a roundabout way for testing since the lab UI doesn't function without a working histogram endpoint. So the first step is to edit `docker-compose.yml` and set the tile server to the old one:
```
TILE_SERVER_LOCATION=http://localhost:9101
```
* Create a new analysis with a project that has a histogram (if using a COG)
* Copy a tile request URL from the network inspector
* Modify the domain of the request to point to the new tile server (`localhost:8081`) and make request
* Visualization should match
Closes #3905

Add Backsplash Lab Integration

---

CHANGELOG.md
app-backend/backsplash/src/main/scala/io/Cog.scala
app-frontend/src/app/pages/projects/edit/advancedcolor/advancedcolor.controller.js

This PR uses `ColorCorrect.Params.colorCorrect` instead of a bunch of ad hoc color correction to color multiband COG tiles.
holding off on merge even though it's small until changelog changes are in
* view a project with a COG in it
* do advanced color correction to it
* watch it go
* :racing_car: 
Closes #4149

Enable advanced color correction for cogs 

---

CHANGELOG.md
app-backend/api/src/main/scala/datasource/Routes.scala
app-backend/api/src/main/scala/project/Routes.scala
app-backend/api/src/main/scala/scene/Routes.scala
app-backend/api/src/main/scala/shape/Routes.scala
app-backend/api/src/main/scala/toolrun/Routes.scala
app-backend/api/src/main/scala/tools/Routes.scala
app-backend/common/src/main/scala/utils/Shapefile.scala
app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/Annotation.scala
app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/ObjectAccessControlRule.scala
app-backend/db/src/main/scala/com/azavea/rf/database/ObjectPermissions.scala
app-frontend/src/app/components/permissions/permissionModal/permissionModal.js

This PR locks down sharing that's likely to affect huge numbers of users to only users with certain privilege levels. In pursuit of that, it also moves ACR validity checks into authorization and fully rejects requests where some of the ACRs in a list aren't valid.
* sign in as the dev user and note that you can't share with everyone in the sharing modal
* update the dev user in the db to be a super user, refresh the page, and note that then you can
* update the dev user to set them back to not being a super user
* modify the dev user's platform role to be an `'ADMIN'`
* refresh the page and note that you can see `'Everyone'` sharing again
* save some permissions to confirm I didn't ruin that
Closes #4096

Restrict platform / all sharing to platform admins and superusers

---

CHANGELOG.md
app-backend/authentication/src/main/scala/Authentication.scala
app-backend/build.sbt
app-backend/common/src/main/scala/utils/Shapefile.scala
app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/Annotation.scala
app-backend/geotrellis/src/main/scala/PostgresAttributeStore.scala

This PR fixes some formatting errors I introduced in #4166 and sets `scalafmtOnCompile` to `true` for all projects with `commonSettings`, so that it'll run when you compile from `root` or within individual subprojects.
The downside of running on every compile is time -- in my GCP instance that I'm developing on right now, it added 10 seconds to the no-changes compile time for compiling from `root`. I think that's an acceptable cost to avoid the pr / jenkins / what's wrong? / scalafmt commit cycle, but I'm open to removing that configuration change if others disagree.
* make a change that you know scalafmt won't like
* compile
* watch it go away

Fix formatting problems forever

---

CHANGELOG.md
app-backend/build.sbt
app-backend/datamodel/src/main/scala/com/azavea/rf/datamodel/ColorCorrect.scala

Prior to this commit the logic for determining if it was necessary to
clamp was incorrect/not strict enough. If either the minimum or
maximum value in the histogram was between 0 and 255 redistributing
values was not performed. This causes issues when the range of values
includes 0-255, but the maximum greatly exceeds that value.
After this commit both the minimum and maximum of original values must
be between 0 and 255.
* Take the attached tif …

Update heuristic for determining if clamping/normalizing is needed

---

CHANGELOG.md
app-backend/db/src/main/scala/com/azavea/rf/database/ObjectPermissions.scala
app-backend/db/src/test/scala/com/azavea/rf/database/ProjectDaoSpec.scala

This PR fixes the return of first class objects' permission delete action so that it returns the number of rows affected (should be 1, since `acrs` are on object level) instead of an empty array (used to represent granted permissions).
* Open up the permissions modal of a shared project or scene
* Delete one or more permissions and save
* It should succeed and close the modal
Closes #4173

Fix return of ACR delete action

---

CHANGELOG.md
docker-compose.test.yml
docker-compose.yml

This PR tries out using a global `.coursier-cache`, which should help with maven throttling issues.
* `./scripts/console api-server './sbt api/update'` -- it'll go all the way down to the bottom and reload all dependencies
* `./scripts/console tile-server './sbt tile/udpate'` -- it'll have everything available in the cache from `api/update` a minute ago and so only fetch tile dependencies
* clone another copy of rasterfoundry somewhere else
* fetch this branch over there
* `mkdir -p nginx/srv/dist` from its root, `AWS_PROFILE=raster-foundry RF_SETTINGS_BUCKET=<fill this in> ./scripts/bootstrap`
* `./scripts/console api-server './sbt api/update'` -- it shouldn't fetch anything at all since it'll use the cache

Use a global .coursier-cache

---

CHANGELOG.md
docker-compose.test.yml

Adds a missing environment variable for setting the cache location while building the migrations artifact

Add environment variable for cache in migrations

---

CHANGELOG.md
docker-compose.test.yml
docker-compose.yml

This PR makes it so the app no longer maintains a distinct copy of the coursier-cache. Because `app-backend/` is a mounted volume _and_ `$HOME/.coursier-cache` was mounted into `app-backend/.coursier-cache`, each build made an extra copy of the coursier cache, which is about 400mb on my local machine. This PR makes it so we don't pay 400mb / build on a cache. 
* `rm -rf app-backend/.coursier-cache`
* `./scripts/console api-server './sbt api/update'`
* `./scripts/console tile-server './sbt tile/update'`
* `./scripts/console backsplash './sbt backsplash/update'`
* add a `-f "${DIR}/../docker-compose.test.yml` to `scripts/console` to make `build` available
* `./scripts/console build './sbt update'`
* shouldn't fetch any dependencies except for things that don't already have dependencies in …

Move coursier cache outside of app-backed mounted volume

---

CHANGELOG.md
app-backend/tool/src/main/scala/ast/MapAlgebraAST.scala
app-backend/tool/src/main/scala/ast/codec/MapAlgebraOperationCodecs.scala

This PR includes the `pow` node type in the `MapAlgebraAST` codec, which makes analyses including exponents possible to visualize.
It's an MSAVI-2!
I didn't audit for more missing operations. It seems pretty likely that we'd have run into them by now if they were A Thing :tm:.
* Point tile server location to old tile server
* Make an `msavi` json payload with the python function we have for that
* Post it to `api/tool-runs/`
* Try to check out some histograms and/or maps
* It should work (or fail normally on a timeout instead of with the empty histogram box)
Closes #4155

Include pow in MapAlgebraAST codec

---

app-frontend/src/app/pages/projects/edit/annotate/annotate.html
app-frontend/src/app/pages/projects/edit/annotate/annotate.module.js
app-frontend/src/app/redux/reducers/annotation-reducer.js

Adds some extra state to track request status when creating annotations via drawing or importing.
- create an annotation and use the redux dev tools to see the indicator if it disappears too fast
- set your network throttling to offline and try to create an annotation, see the error message
- create some annotations via import and do the same thing as above
Closes #3729

Add activity indicator for creation of annotations

---

app-frontend/src/app/components/datasources/datasourceDeleteModal/datasourceDeleteModal.module.js
app-frontend/src/app/components/datasources/datasourceItem/datasourceItem.html
app-frontend/src/app/components/datasources/datasourceItem/datasourceItem.module.js
app-frontend/src/assets/styles/sass/_shame.scss
app-frontend/src/assets/styles/sass/components/_button.scss

This PR adds frontend support that disables datasource deletion when there is any ACR on the datasource. This check is consistent with the datasource deletion backend.
Datasource deletion backend bug fix is in https://github.com/raster-foundry/raster-foundry/pull/4140
* Create your own datasource
* Go to datasource list page. Try to delete it. The delete button should be enabled.
* Get into a sql shell and do
```sql
UPDATE datasources
SET acrs = ARRAY['ALL;;VIEW']
WHERE id = '<datasource_id>';
```
* Go to datasource list page. Try to delete it. The delete button should be disabled. (Hitting the delete endpoint will also give you 403, which reflects that our backend disables such deletion under this circumstance as well.)
Closes #4142

Frontend support to disable datasource deletion if it has ACRs

---

CHANGELOG.md
docker-compose.yml
scripts/server

This PR updates `scripts/server` so that by default, `./scripts/server` will use the tile server, `./scripts/server --backsplash` will use backsplash.
Paired with @notthatbreezy on this one.
* `./scripts/server` and `./scripts/server --backsplash` and make sure both work as intended

Add additional options for starting development server

---

CHANGELOG.md
app-backend/batch/src/main/scala/aoi/UpdateAOIProject.scala
app-backend/batch/src/main/scala/export/UpdateExportStatus.scala
app-backend/batch/src/main/scala/notification/NotifyIngestStatus.scala
app-backend/batch/src/test/scala/com/azavea/rf/batch/export/model/ExportDefinitionSpec.scala
app-backend/batch/src/test/scala/com/azavea/rf/batch/sentinel2/TileInfoSpec.scala
app-backend/common/src/main/scala/notification/Email.scala
app-backend/datamodel/src/main/scala/Platform.scala
app-backend/datamodel/src/test/scala/com/azavea/rf/datamodel/implicits/Generators.scala
app-backend/db/src/main/scala/notification/Notify.scala
app-backend/tile/src/test/scala/RenderDefinitionSpec.scala
app-backend/tile/src/test/scala/auth/AuthSpec.scala
app-backend/tile/src/test/scala/tool/TileResolverSpec.scala
app-backend/tool/src/test/scala/Generators.scala
app-backend/tool/src/test/scala/ast/CanonicalTools.scala
app-backend/tool/src/test/scala/ast/MapAlgebraASTSpec.scala
app-backend/tool/src/test/scala/ast/codec/MapAlgebraASTCodecSpec.scala
app-frontend/src/app/pages/admin/platform/settings/email/email.html

* Allow setting the "From" name for emails set by a platform
* Some scalafmt changes
* As a platform admin, go to the email settings page and add a name to the "From" field
* Verify that it persists through reloads
* Make sure all the other fields are set up to work on dev and then invite a user to an organization. Verify that the email is set up correctly and the "From" field is used to populate the name for the email
Closes #3677

Add "From" field to platform email notification settings

---

CHANGELOG.md
app-frontend/src/app/pages/admin/organization/users/users.html
app-frontend/src/app/pages/admin/team/users/users.html
app-frontend/src/app/pages/projects/edit/advancedcolor/advancedcolor.controller.js
app-frontend/src/app/services/projects/project.service.js

Add user button no longer shows for non-admins of teams and orgs
Fix undefined function call when selecting project scenes by clicking the map in the advanced color correction view
Add thrown error to function that doesn't seem to be used anywhere and I don't want to spend the time to fix now.
getProjectCorners is called in the layer service, but we don't seem to use that function for projects anywhere. I've added an error that's descriptive just in case it shows up.
* As a …

Fix org/team frontend permissions, undefined function call

---

CHANGELOG.md
app-backend/backsplash/src/main/scala/Server.scala
app-backend/backsplash/src/main/scala/io/Avro.scala
app-backend/backsplash/src/main/scala/io/Cog.scala
app-backend/backsplash/src/main/scala/io/Histogram.scala
app-backend/backsplash/src/main/scala/services/MosaicService.scala
app-backend/datamodel/src/test/scala/com/azavea/rf/datamodel/implicits/Generators.scala
app-backend/db/src/main/scala/ProjectDao.scala
app-backend/db/src/main/scala/SceneToProjectDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/ProjectDaoSpec.scala
app-backend/db/src/test/scala/com/azavea/rf/database/ProjectDatasourcesDaoSpec.scala
app-backend/db/src/test/scala/com/azavea/rf/database/SceneToProjectDaoSpec.scala
app-frontend/src/app/pages/projects/edit/advancedcolor/adjust/adjust.html

This PR adds a `histogram` endpoint off of projects to backsplash.
It doesn't use `MAMLHistogram` from `geotrellis-server` because `MAMLHistogram` is required to produce an `IO[Histogram]`, while our endpoint _must_ produce an `F[Vector[Histogram]]`.
* add a COG scene and an Avro scene to a project in the same datasource (good way to do this is to ingest a Landsat 8 scene near the already ingested Landsat 8 avro scenes in Tunisia or Australia)
* go to advanced color correction
* try to color correct them both
Closes #4153

Add project histogram endpoint to backsplash

---

CHANGELOG.md
app-frontend/src/app/components/projects/projectItem/projectItem.html
app-frontend/src/app/services/projects/project.service.js
app-frontend/src/app/services/settings/status.service.js

Hide project previews with > 30 scenes
Fix routing to project instead of project.scenes
* Create a project with > 30 ingested scenes
* Verify that the preview doesn't show
* Add an uningested scene to it
* Verify that it now shows that it has uningested scenes instead
Closes #4095

Hide project previews with > 30 scenes

---

CHANGELOG.md
app-backend/bridge/build.sbt
scripts/cipublish

This PR includes `common` in the list of artifacts to publish. Given that even `authentication` was published, I don't think it was excluded for any particular reason, so I'm going to go ahead and merge after I update the changelog.
When I tried fetching one of the artifacts in a repl, I got a complaint that it couldn't find `bridge`, so I renamed that to `bridge` and included it as well as `tool` since there's transitive deps of everything. `common`, `tool`, and `bridge` were the only three missing deps when I tried to load `database`
* verify that i spelled `common` correctly

Include common, tool, and bridge in artifacts to publish

---

CHANGELOG.md
app-backend/db/src/main/scala/SceneDao.scala
app-backend/tile/src/main/scala/image/Mosaic.scala
app-backend/tile/src/main/scala/image/MultiBandMosaic.scala
app-backend/tile/src/main/scala/routes/MosaicRoutes.scala
app-frontend/src/app/components/scenes/sceneDetailModal/sceneDetailModal.module.js
app-frontend/src/app/components/scenes/sceneItem/sceneItem.module.js
app-frontend/src/app/pages/projects/edit/browse/browse.module.js
app-frontend/src/app/services/scenes/rasterFoundryRepository.service.js

This PR 
- passes correct RGB band numbers when browsing COG scenes (not added to a project yet) and when visualizing scene in scene detail modal
- turns on color correction with the passed bands when getting COG scene tiles when scenes are not in a project yet
- fixes bands used for generating COG thumbnails
* Get a planet scene id
* Upload it and get the upload id.
* `rf process-upload <upload id>`
* View the scene from scene detail modal
* Check the generated COG thumbnail's color
* Add the scene to a project
Closes #4010

Fix visualization of ingested planet scenes

---

CHANGELOG.md
app-backend/datamodel/src/main/scala/Upload.scala
app-backend/datamodel/src/test/scala/com/azavea/rf/datamodel/UploadSpec.scala
app-backend/db/src/main/scala/PlatformDao.scala
app-backend/db/src/main/scala/UploadDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/DatasourceDaoSpec.scala
app-backend/db/src/test/scala/com/azavea/rf/database/UploadDaoSpec.scala

This PR makes it so that platform admins can set owners who aren't them on upload objects while preserving that power for superusers.
* look at the tests
Closes #4226

Let platform admins set upload owners

---

CHANGELOG.md
app-tasks/rf/src/rf/uploads/landsat_historical/factories.py

This PR sorts the landsat 4 / 5 / 7 bands before merging them.
No I don't understand why `glob.glob` wouldn't sort when what it's emulating does either thanks for asking. If you need me I'll be hiding somewhere where no one can ask me about why I was so sure it sorted.
For a long time I thought "huh that's weird I guess the sensor must be messed up like Landsat 7" and now actually I understand that these data are _great_
* check out the 22725cdb31ab1e8ecfbd89851b89a3646ff088f3
* rebuild batch container
* add a landsat 4 / 5 TM scene over an island that intersects land and water to a project (it's not necessary, but you'll be happy you did)
* `rf process-upload` that upload id
* note that the paths printed are in order from 1 -> 7
* view the scene in your project with atmospheric removal

Fix cogification for historical landsat

---

CHANGELOG.md
app-backend/db/src/test/scala/com/azavea/rf/database/ProjectDaoSpec.scala
app-backend/db/src/test/scala/com/azavea/rf/database/ProjectDatasourcesDaoSpec.scala
app-backend/db/src/test/scala/com/azavea/rf/database/PropTestHelpers.scala

This PR cleans up the deletion test in the `ProjectDaoSpec` in an effort to eliminate a deadlock condition when running tests. What I think was happening is the ConnectionIO resulting from the mess of flatmaps didn't correctly encapsulate the real world (database-side) data dependencies between the IOs, and some things were running simultaneously that needed to run in sequence. Yesterday I was able to replicate the deadlock consistently, and with this change I haven't hit it in several attempts.
I'm separately opening an issue to clean tests up, since the style that I wrote those tests in originally is kind of a drag.
* jenkins

Remove deadlock from delete scenes test in project dao

---

CHANGELOG.md
app-frontend/src/app/services/vendor/intercom.service.js

See title.
* Create a new user on dev and verify that in intercom, it doesn't set the name to the email (all database users have their name set to their email)
Closes #4223

Don't include name in user object sent to intercom if same as email

---

nginx/etc/nginx/conf.d/api.conf
nginx/etc/nginx/conf.d/backsplash.conf
nginx/etc/nginx/conf.d/tiler.conf

This PR fixes some mistakes I made when tweaking the nginx configuration for #4170. I added missing semicolons and changed references to `proxy_settings.conf` to `proxy-settings.conf`
~- [ ] Description of PR is in an appropriate section of the [changelog](https://github.com/raster-foundry/raster-foundry/blob/develop/CHANGELOG.md) and grouped with similar changes if possible~ I didn't update the CHANGELOG because I'm just fixing a mistake.
N/A
Optional. …

Fix nginx proxy-settings directives

---

CHANGELOG.md
app-backend/db/src/main/scala/ProjectDao.scala
app-backend/db/src/main/scala/SceneWithRelatedDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/ProjectDaoSpec.scala
app-backend/db/src/test/scala/com/azavea/rf/database/ShapeDaoSpec.scala

Some old scenes don't have a `scene_type` set in the db because the db has a lot of scenes and we just never went back and filled it in. This made it so that our check for `AVRO` scenes only to kick off ingests prevented us from kicking off ingests for scenes that were going to be `AVRO` scenes that we've had for a while (think old Landsat 8 and Sentinel-2 scenes). This PR adds a test to make sure that we kickoff ingest for those scenes and changes the database filter so that we do so.
The test would only have failed sometimes -- you'd have to get a 
* the testing failure would only happen if you generated a scene with `sceneType = None` and with `ingestStatus = IngestStatus.NotIngested`, so it'd take a minute, but you can at least confirm that we could generate that case
* confirm that …

Improve kicking off scene ingests

---

CHANGELOG.md
app-backend/backsplash/src/main/scala/Server.scala
app-backend/backsplash/src/main/scala/error/ErrorHandling.scala
app-backend/backsplash/src/main/scala/services/AnalysisService.scala
app-backend/backsplash/src/main/scala/services/HealthCheckService.scala
app-backend/backsplash/src/main/scala/services/MosaicService.scala
app-backend/build.sbt

This PR uses an error-handling ADT for backsplash and wraps services in a handler for that type of errors and a translator between "foreign" errors and backsplash errors.
"I was promised magic!" you say, "why do you have to explicitly wrap the services?"
Well for two reasons. Reason 1 is that the example given in the blog post in the linked issue does fancy error-handling on HTTPRoutes, not on an (`Authed`)`HttpService`. Why that matters is that I wasn't sure how to apply middleware to `HttpRoutes`. While they're still `Kleisli`s, I didn't think the story was as clear, especially because...
Reason 2 -- we have errors that don't originate in our code. The database and S3 are two places where we can have errors that we want to catch with our fancy error handler that we _can't_ make extend …

Use error-handling ADT for backsplash errors

---

CHANGELOG.md
app-backend/api/src/main/scala/scene/Routes.scala
app-backend/backsplash/src/main/scala/io/Avro.scala
app-backend/backsplash/src/main/scala/io/Cog.scala
app-backend/backsplash/src/main/scala/io/Histogram.scala
app-backend/batch/src/main/scala/cogMetadata/HistogramBackfill.scala
app-backend/batch/src/main/scala/export/spark/Export.scala
app-backend/common/src/main/resources/reference.conf
app-backend/common/src/main/scala/utils/CogUtils.scala
app-backend/datamodel/src/main/scala/ColorCorrect.scala
app-backend/datamodel/src/main/scala/TiffWithMetadata.scala
app-backend/tile/src/main/scala/image/GlobalSummary.scala
app-backend/tile/src/main/scala/image/MultiBandMosaic.scala
app-backend/tile/src/main/scala/image/SingleBandMosaic.scala
app-backend/tile/src/main/scala/routes/MosaicRoutes.scala
app-backend/tile/src/main/scala/tool/TileResolver.scala

This PR uses tiff metadata to determine what range to normalize imagery to. If the nodata value is zero (looking at you, Planet), it normalizes to the range `[1, 255]` instead of `[0, 255]`, because otherwise it gets confused and thinks there's a bunch of nodata in the middle of the scene. If the nodata value _isn't_ 0, it normalizes to 0 -> 255
* turn your tile server cache off
* visualize a planet cog -- it should not have patches
* visualize a non-planet cog -- it should not have a thick black border
Closes #4053 
Closes #4246

Use metadata to avoid nodata patches

---

CHANGELOG.md
app-tasks/completion.bash
app-tasks/rf/src/rf/cli.py
app-tasks/rf/src/rf/commands/__init__.py
app-tasks/rf/src/rf/commands/reprocess_landsat_h.py
app-tasks/rf/src/rf/uploads/landsat_historical/factories.py

This PR adds a command to `rf` to reprocess the cogs for any Landsat 4 / 5 / 7 tif.
* if you don't have any badly processed landsat 4 / 5 scenes, let me know, and I can give you an ingest location for one and you can add it as a COG with the landsat 4 / 5 tm datasource and manually set its name to the right landsat id
* otherwise:
* rebuild the batch container
* view a badly cog-ified landsat 4 / 5 scene
* add another landsat 4 / 5 scene to the same project nearby
* process that upload
* reprocess the scene that is bad -- `rf reprocess-landsat-h <scene id>`
* view the project with both scenes and switch through some color modes
* the colors in the scenes should look similar in each color mode

Add rf command for reprocessing landsat historical scenes

---

CHANGELOG.md
app-backend/batch/src/main/scala/export/spark/Export.scala
app-backend/datamodel/src/main/scala/QueryParameters.scala
app-backend/db/src/main/scala/filters/Filterables.scala

This PR ensures the batch assembly jar includes json codecs for query parameter classes.
Why did they go away? I don't know. Maybe the code generator in macro paradise got tired. Maybe because everything was used only implicitly, assembly thought we didn't need it. Maybe our deprecated dropbox call caused assembly to get confused, like [this unfortunate soul](https://stackoverflow.com/a/37608677). Anyway, it's fixed. :heart: assembly
* assemble your batch jar on develop
* run the commands in the test script in the linked issue from ammonite, or `scala -cp /abs/path/to/batch-assembly.jar` and just run the non-ammonite parts
* you should get errors when you try to initialize the combined scene query params
* reassemble your batch jar with this branch
* run the same commands
* you should be …

Restore missing classes in batch assembly jar

---

CHANGELOG.md
app-backend/backsplash/src/main/scala/Server.scala
app-backend/backsplash/src/main/scala/auth/Authenticators.scala
app-backend/backsplash/src/main/scala/parameters/PathParameters.scala
app-backend/backsplash/src/main/scala/services/AnalysisService.scala
app-backend/backsplash/src/main/scala/services/MosaicService.scala
app-backend/datamodel/src/test/scala/com/azavea/rf/datamodel/implicits/Generators.scala
app-backend/db/src/main/scala/MapTokenDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/MapTokenDaoSpec.scala
app-backend/db/src/test/scala/com/azavea/rf/database/PropTestHelpers.scala

This PR fills in map token and auth header authentication methods for backsplash.
`/:` is a right-associative path separator -- you can read the match from right to left to understand what the `case` will match, e.g.:
```scala
case req @ _ -> "tools" /: UUIDWrapper(analysisId) /: _ => ...
```
means "ending in literally anything, preceded by a UUID, preceded by "tools", do the following. It's also why the tools match needs to come first, because with the exception of being a project id instead of an analysis id, the project routes matcher is the same
Testing instructions assume you're a cool kid who uses `httpie` because writing out `curl` commands makes me tired.
* get a bearer token
* `http :8081/a-project-id/z/x/y Authorization:'Bearer ...'`
* `http :8081/a-project-id/z/x/y …

Fill in missing auth methods for backsplash

---

CHANGELOG.md
app-backend/db/src/main/scala/filters/Filters.scala

This PR fixes `searchQP` function to make it more secure and escape quotation marks.
* Property tests should pass
* Use search functions on frontend or by sending `?search=<something>` request to endpoints that supplies this query parameter (like search for plat/org/team members, search for orgs/teams/projects/datasources/templates, etc. )
* Send search strings like `'uav%20-%203%20Band'`, `'uav%20-%203%20Band`, `"uav%20-%203%20Band` with quotation marks and make sure it just does not give you matching results rather than giving postgres errors
* Do something similar as mentioned in https://github.com/azavea/raster-foundry-platform/issues/547
Closes https://github.com/azavea/raster-foundry-platform/issues/547
Closes https://github.com/azavea/raster-foundry-platform/issues/530

Fix searchQP

---

CHANGELOG.md
app-frontend/src/app/pages/projects/edit/annotate/annotate.module.js
app-frontend/src/app/redux/reducers/project-reducer.js

This PR fixes a bug in annotation sidebar item click and on annotation item edit when the annotation is from a zipped shapefile upload, so that it takes into consideration of `MultiPolygon` in addition to `Polygon`.
* Go to a project and upload annotations from a zipped shapefile (select right fields to match though)
* Go to annotation list on the sidebar -- clicking on an annotation item on sidebar should pan the map to it
* Click on the annotation item dropdown and select edit -- the shape to be edited should appear on the map. Saving the shape should succeed.
Closes https://github.com/raster-foundry/raster-foundry/issues/4279

Fix annotation edit bug when uploaded from a zipped shapefile

---

CHANGELOG.md
app-frontend/src/app/components/scenes/sceneImportModal/sceneImportModal.controller.js
app-frontend/src/app/components/scenes/sceneImportModal/sceneImportModal.html
app-frontend/src/assets/styles/sass/_shame.scss

This PR updates the scene import modal to let it give user suggestions on S3 path based on guesses generated from user input.
1. `https://` or `http://` paths with `.tif` or `.tiff` file extensions:
2. `https://` or `http://` paths without `.tif` or `.tiff` file extensions:
3. `s3://` path:
4. If it still can't get through:
* Go to scene import page
* Use S3 import option
Closes https://github.com/raster-foundry/raster-foundry/issues/4284

Let import modal guess and suggest S3 path

---

CHANGELOG.md
app-backend/project/ci/repositories
app-backend/project/development/repositories
deployment/ansible/group_vars/all.yml
deployment/ansible/group_vars/nexus.yml
deployment/ansible/inventory/nexus
deployment/ansible/raster-foundry-jenkins.yml
deployment/ansible/raster-foundry-nexus.yml
deployment/ansible/roles.yml
deployment/ansible/roles/raster-foundry.nexus/defaults/main.yml
deployment/ansible/roles/raster-foundry.nexus/meta/main.yml
deployment/ansible/roles/raster-foundry.nexus/tasks/main.yml
deployment/ansible/roles/raster-foundry.nexus/templates/nexus.conf.j2
scripts/cibuild

Adds an Ansible role to provision an instance of Nexus Repo Manager, prepopulated with a Nexus backup from S3. Using Nexus will help speed up dependency downloads and keep us from being throttled by Maven Central.
You can login to the admin console using the `Nexus` credentials on LastPass:
* http://nexus.internal.azavea.com/
* http://nexus.staging.rasterfoundry.com/
Resolves azavea/raster-foundry-platform#519
Resolves azavea/raster-foundry-platform#518
Resolves azavea/raster-foundry-platform#517
I created a private hosted zone for the Jenkins VPC, and added a record for `nexus.rasterfoundry.internal`.
I did this because NAT loopback for `nexus.staging.rasterfoundry.com` didn't work, and I thought it would be beneficial if we ever add Jenkins slave instances.
First, SCP the …

Add Ansible role to install Nexus Repo Manager

---

CHANGELOG.md
app-frontend/src/app/pages/admin/platform/settings/email/email.html
app-frontend/src/app/pages/admin/platform/settings/email/email.module.js

This PR removes form validation for user name in platform email settings. It also enables/disables save button based on the presence of port number. It sets a default value on encryption method if there is no such setting.
* Log in as a platform admin
* Go to platform settings
* Make sure you can specify any string as user name
* Make sure you cannot use `Save` button if there is no port number set
Closes https://github.com/raster-foundry/raster-foundry/issues/4292

Remove form validation for user name in platform email settings

---

CHANGELOG.md
app-frontend/src/app/components/lab/templateItem/templateItem.html
app-frontend/src/app/components/lab/templateItem/templateItem.module.js
app-frontend/src/app/pages/lab/browse/templates/templates.html
app-frontend/src/app/pages/lab/browse/templates/templates.js
app-frontend/src/app/services/analysis/analysis.service.js
app-frontend/src/assets/styles/sass/components/_dropdown.scss

This PR enables template deletion on frontend after checking the operating user's allowed actions on it.
* Log in as user1 and grab `userOneId`
* Create a new template
* Go to template list. Expand the options button and delete the template. It should succeed.
* Log into user2's account and create a template there. Grab the `templateId`.
* In DB, do the following or something similar:
```sql
UPDATE tools SET acrs = ARRAY['USER;<userOneId>;DELETE'] where id = '<templateId>';
```
* Log back in to user1's account
* Go to template list. You should see the template user2 shared with you. Expand the options button and delete the template. It should succeed.
* Check that deletion is not enabled for templates not owned by or shared to you.
Closes …

Enable template deletion on frontend

---

CHANGELOG.md
app-backend/batch/src/main/scala/export/spark/Export.scala

Why didn't scala get mad that I didn't include the type annotation for my
recursive function call? I don't know! I wish it had. Oops. Anyway, the costs of :cowboy_hat_face:

Don't infinitely recurse in exports

---

CHANGELOG.md
app-backend/backsplash/src/main/scala/auth/Authenticators.scala

This PR updates authentication for getting project tiles from backsplash so that it supports viewing public projects.
* `./scripts/server --backsplash`
* Go to a project
* Under `Publish` tab, change `Project Visibility` to `Public`
* Copy `ZXY Tile Layer URL`
* View the tile layer somewhere, like @Lknechtli 's https://lknechtli.github.io/react-map-compare/
Closes https://github.com/raster-foundry/raster-foundry/issues/4285

Support viewing public projects in backsplash

---

app-frontend/config/webpack/global.js
app-frontend/src/app/components/scenes/sceneItem/sceneItem.module.js
app-frontend/src/app/index.bootstrap.js
app-frontend/src/app/index.module.js

Fix favicons
Fix missing styles for scene filter pane components
Fix scene thumbnails for cogs
- ~Description of PR is in an appropriate section of the [changelog](https://github.com/raster-foundry/raster-foundry/blob/develop/CHANGELOG.md) and grouped with similar changes if possible~ cover in anchor pr
The manifest plugin we were using wasn't updated to support webpack 4, but it seems to be handling hashing etc of images fine. I don't think we were actually using the plugin in a way that took advantage of what it was supposed to offer, so no reason …

Fix favicons, missing styles, scene thumbnails for webpack upgrade

---

CHANGELOG.md
app-backend/api/src/main/scala/Router.scala
app-backend/api/src/main/scala/user/Routes.scala
app-backend/authentication/src/main/scala/Authentication.scala
app-backend/db/src/main/scala/UserDao.scala
app-backend/db/src/main/scala/filters/Filterables.scala
app-frontend/src/app/components/common/navBar/navBar.html
app-frontend/src/app/pages/home/home.html
app-frontend/src/app/pages/lab/browse/analyses/analyses.js
app-frontend/src/app/pages/share/share.html
app-frontend/src/app/services/auth/auth.service.js

Populate the user's name fields using multiple fallbacks on the frontend and backend. Avoid using email if anything else is available.
name is populated from the following fallbacks:
1) name if not same as email 
2) nickname if not same as email
3) given name + family name
4) delegated profile name if not same as email
5) delegated profile nickname if not same as email
6) delegated profile given name + family name
7) email
8) id
* Verify that the fallbacks work by creating …

Populate user name field with multiple fallbacks

---

CHANGELOG.md
app-backend/batch/src/main/scala/SparkJob.scala
app-backend/batch/src/main/scala/ast/RfmlRddResolver.scala
app-backend/batch/src/main/scala/export/spark/Export.scala
app-backend/batch/src/main/scala/landsat8/ImportLandsat8C1.scala
app-tasks/rf/src/rf/commands/export.py

This PR separately handles system shutdown for exports, since we somehow wound up with an extra connection pool in a thread somewhere that didn't shutdown after running the spark job.
* assemble batch jar
* create an export of a small area somewhere (project or ast, doesn't matter)
* `rf export <your export id>` from the batch container
* also pick a recent date, and `java -cp /opt/raster-foundry/jars/batch-assembly.jar com.rasterfoundry.batch.Main import_landsat8_c1 <your date>`
* about 9 minutes later you should have a bunch of new landsat scenes
Closes azavea/raster-foundry-platform#557
Closes azavea/raster-foundry-platform#556

Make exports and landsat 8 import start and stop again

---

CHANGELOG.md
app-backend/batch/src/main/scala/export/spark/Export.scala

This PR sets the log level on the spark context when running exports. Every other attempt to affect the log level in spark seemed to be ignored entirely, so this will have to be fine for now. It doesn't affect debug logging during startup... but it _does_ prevent the incredibly verbose `org.apache.http.wire` logs from hitting us, which is _really great_.
Logs from the end of spark context initialization to the end of the export task:
```
2018-11-16 22:18:18 DEBUG ServletHolder:615 - Servlet.init org.apache.spark.ui.JettyUtils$$anon$3@65778079 for org.apache.spark.ui.JettyUtils$$anon$3-313c3917
2018-11-16 22:18:18 INFO  ContextHandler:744 - Started o.s.j.s.ServletContextHandler@58524763{/metrics/json,null,AVAILABLE}
2018-11-16 22:18:18 DEBUG AbstractLifeCycle:177 - STARTED @4370ms …
```

Don't log below WARN when running spark job

---

CHANGELOG.md
app-backend/api/src/main/scala/project/Routes.scala

The annotations shapefile export was being written to an S3 object with the scheme and bucket name included in the object name. Things worked, but object names were misleading.
```
https://rasterfoundry-development-data-us-east-1.s3.amazonaws.com/s3%3A/%2Frasterfoundry-development-data-us-east-1/user-exports/.../annotations/.../annotations.zip
```
This change makes it so that the scheme and bucket name are no longer part of the annotations export object name.
```
https://rasterfoundry-development-data-us-east-1.s3.amazonaws.com/user-exports/.../annotations/.../annotations.zip
```
Fixes https://github.com/azavea/raster-foundry-platform/issues/551
~- [ …

Fix shapefile annotations export

---

CHANGELOG.md
app-backend/common/src/main/scala/S3.scala
app-backend/common/src/main/scala/utils/RangeReaderUtils.scala

This PR makes the s3 client we use in `RangeReaderUtils` tolerate buckets outside of the configured region.
* Get an ingest location for an iserv scene from prod, or use this one: `s3://radiant-nasa-iserv/2014/01/03/IPR201401031604353415N11718W/IPR201401031604353415N11718W-COG.tif`
* do a remote cog import with that s3 path
* it should succeed and you should get tiles
Closes #4315

Enable global bucket access for s3 range reader

---

CHANGELOG.md
app-frontend/src/assets/styles/sass/components/_image.scss
app-frontend/src/assets/styles/sass/components/_list-group.scss
app-frontend/src/assets/styles/sass/components/_searchselect.scss
app-frontend/src/assets/styles/sass/theme/high-contrast/components/_filter.scss
app-frontend/src/assets/styles/sass/theme/un-global-platform/components/_filter.scss

- fixes #4350
- fixes thumbnail loading size issue on list-groups
- fixes flex issue in list-groups for long source names
**1: List group issue, before:**
**1: List group after fix, all themes**
**2: Search select invisble text, before:**
**2: Search select text after fix, all themes:**
* Open project
* Check scene list as they load to check for thumbnail load issue
* Check scene list item that contains a long image source name to make sure buttons don't go on two lines
* Type into the imagery source searchbox. Make sure the typed text is visible

Implements a handful of styling fixes within projects

---

CHANGELOG.md
app-backend/db/src/main/scala/PlatformDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/PlatformDaoSpec.scala

Fix duplicate emails when a user has inactive platform UGRs
* Add an inactive platform UGR to a user with email notifications enabled 
* Add an uningested scene to a project owned by that user
* Ingest the scene
* Verify in logging that only one email is sent
Closes #4005

Only use active UGRs in query for emails to send during ingest

---

CHANGELOG.md
app-backend/api/src/main/scala/project/Routes.scala

This PR changes the API to match what the spec says where the spec has the right idea. I think it's mainly going to be status code changes. It's a companion to https://github.com/raster-foundry/raster-foundry-api-spec/pull/69
* note the exception handling in the test script for the linked PR above and confirm that these changes address those exceptions

Agree with the spec where the spec is correct

---

CHANGELOG.md
app-backend/db/src/main/scala/UserDao.scala
app-backend/db/src/main/scala/util/Email.scala

This PR updates the `unsafeGetUserById` method so that if users are not requesting their own info, the returned other users' email info are protected.
* In order to test that the issue is resolved by this PR, log into an account with `name` field set as the same as `email` field, and no first and last name in `personalInfo` (so that it will fall to the `name` case, where the name is the same as email in DB, which happens to some user records)
* Create a new template
* In DB, change its visibility to `PUBLIC` or modify its `acrs` to share it to another account (directly, through group membership, etc)
* Log into this other account and go the list of templates
* Make sure only email user name (without `@domain`) or `Anonymous` is displayed as owner for that shared template
Closes …

Protect user email

---

backsplash-core/src/main/scala/com/rasterfoundry/backsplash/BacksplashMosaic.scala
backsplash-core/src/main/scala/com/rasterfoundry/backsplash/Implicits.scala
backsplash-core/src/test/scala/com/rasterfoundry/backsplash/BacksplashMosaicSpec.scala
backsplash-core/src/test/scala/com/rasterfoundry/backsplash/GtImplicits.scala

This PR cleans up the implementation of implicit values so that only a single import will be required to bring in available type class instances. Additionally, it adds an alternative set of implicits which provide a JVM-only path for tile resolution

Solve implicit resolution for BacksplashMosaic

---

CHANGELOG.md
app-backend/api/src/main/scala/platform/Routes.scala

This PR updates authorization checks on team and organization member endpoints, so that, in addition to admins, if the acting user matches the user to be removed, the acting user is allowed to decline a team or organization invitation, or to leave a team or an organization.
The original issue changed a tiny bit per the comment in there.
* Log in as a platform admin
* Create an organization
* Add your other account as organization member
* Log in to the other account
* Go to the list of your organizations
* Check if both accept and decline work. If you accepted, you should be able to leave the organization as well.
* Test the team scenario following similar instructions as above and check if it works.
Closes #4327 
Closes #4213

Allow users to decline invitations or leave groups

---

app-frontend/src/app/pages/home/home.html

- ~Description of PR is in an appropriate section of the [changelog](https://github.com/raster-foundry/raster-foundry/blob/develop/CHANGELOG.md) and grouped with similar changes if possible~ regression introduced in this release
* Verify that the "manage account" and "manage api tokens" buttons on the homepage now work

Fix missing state param for user.settings on homepage

---

CHANGELOG.md
app-tasks/completion.bash
app-tasks/rf/requirements.txt
app-tasks/rf/src/rf/cli.py
app-tasks/rf/src/rf/commands/__init__.py
app-tasks/rf/src/rf/commands/reprocess_sentinel.py

Write a script which takes a single scene id to reprocess
```
> $ ./scripts/console batch bash                                                                                         [±feature/lk/remaining-import-fixes ●●]
Starting raster-foundry_postgres_1 ... done
root@47a8ed9c279d:/# rf reprocess-sentinel 1ab221fc-8d6b-4d8b-ae7f-ae1fde7f820d
Starting reprocessing scene: 1ab221fc-8d6b-4d8b-ae7f-ae1fde7f820d
Connected to db
Scene has 11 images
Re-importing sentinel scene: …
```

Add script for reprocessing sentinel scenes

---

backsplash-core/src/main/scala/com/rasterfoundry/backsplash/Implicits.scala
backsplash-core/src/main/scala/com/rasterfoundry/backsplash/PaintableTool.scala
backsplash-core/src/main/scala/com/rasterfoundry/backsplash/ToolStore.scala
backsplash-core/src/main/scala/com/rasterfoundry/backsplash/package.scala

This PR adds a tool store, which is a way to translate between analyses and the types of case class that backsplash-core wants to turn into analysis tiles.
- ~Description of PR is in an appropriate section of the [changelog](https://github.com/raster-foundry/raster-foundry/blob/develop/CHANGELOG.md) and grouped with similar changes if possible~ skipping, since it's not a change, but catch-up
I considered including a dummy example in this PR, but am going to move on to integration instead
* compilation, tragically

Add tool store

---

CHANGELOG.md
app-backend/datamodel/src/main/scala/UserGroupRole.scala
app-backend/db/src/main/scala/UserGroupRoleDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/UserGroupRoleDaoSpec.scala
app-frontend/src/app/components/settings/teamModal/teamModal.html

This PR 
* updates the `users/me/roles` endpoint so that it returns only one `groupName` property
* updates team modal to use this new field on the frontend
Spec is updated in [this PR](https://github.com/raster-foundry/raster-foundry-api-spec/pull/72)
* `GET` to `api/users/me/roles` should return a `groupName` field
* Property test should pass
* Go to your team list. Click on "Create team" button. The modal should have a dropdown with organization names listed for you to specify which organization to add the team to.
Closes #4374

Update get user roles endpoint

---

CHANGELOG.md
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/AnalysisService.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/HealthcheckService.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Main.scala
docker-compose.yml

This PR restores the healthcheck and analysis export routes that were removed by accident during reintegration.
* find a nice bbox to do an analysis quick export
* export an analysis with png or geotiff encoding for that bbox with a zoom (the only thing that shouldn't work is painting anything other than viridis)
* ping the healthcheck endpoint

Restore missing backsplash routes

---

CHANGELOG.md
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Main.scala

This PR adds a timeout middleware that sets a 15-second timeout to services in backsplash.
One way to test this PR:
* Go to `MosaicService` or `AnalysisService`
* Import `scala.concurrent.duration._`, `cats.effect.Timer`
* Add a `timer: Timer[IO]` implicit parameter
* Append below case …

Add timeout middleware to services in backsplash

---

CHANGELOG.md
app-backend/build.sbt

This PR decreases the max classfile name length to 70, because docker was mad.
Observer that #991 cipublish was a disaster:
http://jenkins.staging.rasterfoundry.com/job/Raster%20Foundry/job/raster-foundry/job/develop/
While in the test branch with this change it went fine until it reached a dependency on some steps I skipped:
http://jenkins.staging.rasterfoundry.com/job/Raster%20Foundry/job/raster-foundry/job/test%252Fjs%252Fdecrease-max-classfile-name-length/

Decrease max classfile name length to 70

---

CHANGELOG.md
app-frontend/src/app/pages/share/share.controller.js
app-frontend/src/app/pages/share/share.html

Fix logo import
Add error handling and button to attempt reloading project in case of errors
I wasn't actually able to reproduce the error where the project is not zoomed to correctly after an hour of testing in firefox and chrome, so I'm just fixing these issues for now. Reading through the code, I assume that any issues loading the project due to permissions, network errors, etc will cause the map not to zoom, so this will fix silent failures.
* Load a project share page
* Verify that the RF logo now shows
* Edit the uuid in the navbar so it tries …

Fix logo, error handling on project share page

---

app-tasks/completion.bash
app-tasks/rf/src/rf/cli.py
app-tasks/rf/src/rf/commands/__init__.py
app-tasks/rf/src/rf/commands/ingest_scene.py
app-tasks/rf/src/rf/commands/reprocess_geotiff_to_cog.py
app-tasks/rf/src/rf/ingest/io.py
app-tasks/rf/src/rf/utils/cog.py

Feed the script a list of UUID and it will re-ingest them. Should work for pretty much any avro scene, but we need to test it on staging since I don't want to spend another 6 hours waiting for scenes to ingest locally.
- ~Description of PR is in an appropriate section of the [changelog]~(https://github.com/raster-foundry/raster-foundry/blob/develop/CHANGELOG.md) and grouped with similar changes if possible
```
root@6caf249dcbf6:/# rf reprocess-geotiff-to-cog …
```

Add script to re-ingest a list of landsat 8 / sentinel 2 / planet / user uploaded scenes as cogs

---

CHANGELOG.md
app-backend/.dockerignore
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/BacksplashImage.scala
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/MetricsRegistrator.scala
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/error/Error.scala
app-backend/backsplash-server/src/main/resources/reference.conf
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/AnalysisService.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Authorizers.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Config.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Error.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Main.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/MamlAdapter.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/MosaicService.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/ProjectStoreImplicits.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/ToolStoreImplicits.scala
app-backend/batch/src/test/scala/com/azavea/rf/batch/export/model/ExportDefinitionSpec.scala
app-backend/build.sbt
app-backend/datamodel/src/main/scala/MosaicDefinition.scala
app-backend/datamodel/src/main/scala/SceneToProject.scala
app-backend/db/src/main/scala/SceneDao.scala
app-backend/db/src/main/scala/SceneToProjectDao.scala
app-backend/db/src/main/scala/ToolRunDao.scala
docker-compose.yml

This PR points metrics to a graphite server instead of to stdout, since stdout was going to get pretty noisy.
Choice between graphite and ganglia was based on ease of setup -- ganglia deps were mad at me, so I switched to graphite and everything was fine. They both have ugly dashboards we can access and docker containers for easy setup, so :man_shrugging:
* docker-compose up backsplash
* navigate to `localhost:8090`
* check out your sweet dashboard
* wait a minute (don't make any requests since we're segfaulting like mad right now) and then explore down the `com` / `rasterfoundry` / `backsplash` tree of the metrics browser

Add graphite reporting to metrics

---

CHANGELOG.md
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/BacksplashImage.scala
app-backend/project/Version.scala

This PR upgrades geotrellis-server to 0.14.0-RC1, which includes some work to ensure thread safe gdal usage.
* load up a project page
* you should render tiles without seg faults killing the tile server

Upgrade geotrellis-server

---

CHANGELOG.md
docker-compose.java.yml
scripts/console
scripts/server

Adds some alternative development for working with the API and backsplash servers so we can avoid recompiling projects accidentally when it is unnecessary.
* Run `./scripts/console sbt`
* Assembly fat jars for both API server and backsplash:
```
project backsplash-server
assembly
project api
assembly
```
* Start server: `./scripts/server --backsplash` and make some requests

Add docker-compose file to start services with java

---

CHANGELOG.md
app-backend/build.sbt

#4395 removed the `it` stage from the `tile` subproject so that integration testing (which doesn't depend on any other part of the project) could live on its own. It didn't remove references to it from `build.sbt` though, which we discovered only when trying to assemble the tile server jar in CI. This PR removes `it` references from the `tile` subproject dependency list so that assembly can run again and we can succeed in CI.
* run `tile/assembly`
* it should succeed

Remove references to `it` stage of tile subproject

---

app-tasks/rf/src/rf/commands/reprocess_sentinel.py

Fix sentinel reprocessing by using separate batch jobs for ingests instead of running them in the reprocessing script
- ~Description of PR is in an appropriate section of the [changelog](https://github.com/raster-foundry/raster-foundry/blob/develop/CHANGELOG.md) and grouped with similar changes if possible~ initial change in this release
* I think this is best tested on staging because it requires actually kicking off a batch job in the same env as the script is running in.

Switch to using batch job submission over sequential ingest running

---

app-tasks/rf/src/rf/commands/reprocess_sentinel.py

Fix silly variable naming error in batch reprocess script

---

CHANGELOG.md
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/BacksplashImage.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Main.scala
app-backend/project/Version.scala

With some experimentation, @pomadchin figured out that our threading issues live in gdal C code, and that java synchronization isn't getting us anything (and based on gatling tests is probably just making performance work). Some options around vrt reads and max open datasets are in an upgraded gt-server release, and another option is set in `Main.scala`, to alleviate a lot of our unsafe thread problems.
This PR captures changes from `test/js/set-gdal-options` in a feature branch.
Testing was done with the test branch to determine prevalence of seg faults on initial reads and resulting performance of a few different configurations. No further testing is required.

Set gdal options and upgrade gt-server

---

CHANGELOG.md
app-backend/Dockerfile.backsplash
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/BacksplashImage.scala
docker-compose.yml
scripts/console

This PR takes us from the universe of a large terrifying unknown space for bugs into a universe of a smaller less terrifying unknown space for bugs by going back to gt for tile IO.
Ideally this will be a temporary fix and eventually we'll be able to go back to the features that reading with gdal will get us. Ideally.
* try to view tiles for a project
* it should work

Use gt instead of gdal for raster sources

---

CHANGELOG.md
app-backend/api/src/main/scala/Main.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/AnalysisService.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Authenticators.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Authorizers.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Main.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/MamlAdapter.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/MosaicService.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/ProjectStoreImplicits.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/ToolStoreImplicits.scala
app-backend/db/src/main/scala/util/database.scala
docker-compose.java.yml

This PR removes some execution context pollution that was happening when importing a transactor from the database and also more explicitly names our generated execution contexts for easier identification later.

Remove Implicit Execution Contexts

---

CHANGELOG.md
gatling/src/test/resources/application.conf
gatling/src/test/scala/Config.scala
gatling/src/test/scala/MosaicTmsSimulation.scala
gatling/src/test/scala/TmsUtils.scala
scripts/cigatling

This PR makes it so that we can specify a list of project IDs instead of a single project ID for load testing
purposes.
* create a `jenkins.env` file to use for the load test (I can send you a template)
* `source jenkins.env`
* `./scripts/cigatling`
* you should run a load test without configuration errors
* you should see more than one project in the list of URLs tested against

Support a list of projects in cigatling

---

CHANGELOG.md
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/AnalysisService.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/MosaicService.scala

This PR adds `Fiber` from `cats.effect` to do things similar to green threads for services in Backsplash, so that authorization and other calculations are on different fibers, and that unauthorized requests will cancel the evaluation of calculations early.
* See thread change in visual vm? idk

Use Fiber for threading in Backsplash Services

---

app-tasks/rf/src/rf/ingest/io.py

Urls passed into AWS libraries must not be encoded, but scene.ingestLocation is expected to be encoded.
- ~Description of PR is in an appropriate section of the [changelog](https://github.com/raster-foundry/raster-foundry/blob/develop/CHANGELOG.md) and grouped with similar changes if possible~ reprocess script was added this release
```
INFO:rf.ingest.io:Uploading tif to S3 at s3://rasterfoundry-development-data-us-east-1/user-uploads/auth0|59318a9d2fbbca3e16bcfc92/323c20e1-6 …
```

Only url-encode the url used to update scene, not upload

---

CHANGELOG.md
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/AnalysisService.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/AuthedAutoSlash.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Main.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/MosaicService.scala

This PR adds an AuthedAutoSlash middleware that we can apply to `AuthedService`s.
The first commit removes all of the trailing `/ _` matchers from routes to make sure that without an appropriate autoslash, all the requests for tiles from the frontend will fail. The second commit adds an `AuthedAutoSlash` middleware that fires _before_ the authed service has a chance to complain that it can't find a route with a trailing slash.
You may have noticed that the default AutoSlash has a branch for something about a `scriptName`. I don't know what that is, and when I was logging the values that the middleware was working with ours was always empty, so I don't think it's important to us.
* use the lab
* it should be fine

Add AuthedAutoSlash middleware

---

gatling/.sbtopts
gatling/project/ci/repositories
gatling/src/test/resources/application.conf
gatling/src/test/scala/Config.scala
gatling/src/test/scala/MosaicTmsSimulation.scala
gatling/src/test/scala/TmsUtils.scala

Updates the simulation so that increasing the number of users increases the number of requests per second being made. This makes it a little easier to reason about changes we make and how it affects performance. Uses gatling's idea about `resources` for a web page - these are requests that are made in parallel (as far as I can tell based on logs and documentation) that would normally be assets on the page (like images, css, js, etc.). This fits our needs pretty good I think.

Gatling Simulation Update

---

CHANGELOG.md
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/MosaicImplicits.scala
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/PaintableTool.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/AnalysisService.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/AuthedAutoSlash.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/AuthedTranslateUri.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Error.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/MosaicService.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/ToolStoreImplicits.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/package.scala
app-backend/project/Version.scala

- Fixes histogram generation for analyses
- Fixes rendering tiles for analyses
- Adds missing statistics endpoint to backsplash
* Assemble the backsplash jar
* Create and open an analysis - histograms and rendering should work

Fix Analysis Rendering and Histogram

---

CHANGELOG.md
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/Cache.scala
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/MosaicImplicits.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Authorizers.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Main.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/ProjectStoreImplicits.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/SceneService.scala
app-backend/db/src/main/scala/SceneDao.scala

This PR adds back the scenes mosaic endpoint.
I'm not gonna add a test for the new string I added. Enough time has passed. It's a single tiny string that's exercised in the testing instructions.
* create a project
* browse for ingested scenes
* hover over some and check them out on the map

Restore scene mosaic service

---

Jenkinsfile
README.md
Vagrantfile
deployment/ansible/raster-foundry.yml

It doesn't look like we're using this anymore. The `publish_jars` script was removed in completing https://github.com/azavea/raster-foundry-platform/issues/549/.

Remove references to RF_ARTIFACTS_BUCKET

---

app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/color/Implicits.scala

`NODATA` values are not precluded from GT `map` and `mapDouble` calls. These happen within analysis color correction and we don't compensate by explicitly guarding against such values. As a result, we map `ND` values to one of the colors provided via `RenderDefinition`. This PR guards against ND
1. Run an analysis (make sure not to shoot yourself in the foot with caching)
2. Make sure regions outside of the data aren't colored

Check for NODATA before rendering

---

CHANGELOG.md
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/BacksplashImage.scala
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/MosaicImplicits.scala
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/color/ColorRampMosaic.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/AnalysisService.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/MosaicService.scala

This PR fixes quick export of all kinds. More specifically, it fixes:
- a cache key bug that caused multiband tiles to fail to render if the single band was cached and also caused different images to be stored under the same cache key
- merger of tiles from different tiffs causing ArrayIndexOutOfBoundsExceptions because they weren't the same size when combined in arbitrary bboxes
- overwrite of later tiles in a stream by earlier tiles due to bad cell types in single band renders
* Find a project with two overlapping but not coextensive scenes (like the demo)
* Browse in it to find a bbox where you have data from both scenes and each should contribute
* save that bbox
* get a token
* set viz to single band
* export the project as a png (`http :8081/<project id>/export token==$token …

Repair quick export

---

CHANGELOG.md
app-backend/db/src/main/scala/ObjectPermissions.scala

This PR updates object permission check for lab templates.
* Check all SQL in the comment area of https://github.com/azavea/raster-foundry-platform/issues/593 and make sure they make sense
* SQL for staging has already been run. Not for production though -- we will run that manually
* Run the local development part of SQL against your local DB
* Go to your lab templates page and apply ownership filters -- make sure it works as you would expect
Closes …

Update object permission check for lab templates

---

CHANGELOG.md
app-frontend/package.json
app-frontend/yarn.lock

This PR bumps the version of webpack-dev-server to avoid a vulnerability with the version we are currently using.
* `yarn install`
* `yarn run start` and test out that the local front-end works as expected
Closes #4435

Bump webpack-dev-server version

---

CHANGELOG.md
app-frontend/src/app/components/filters/shapeFilter/shapeFilter.module.js
app-frontend/src/app/services/common/modal.service.js

This PR fixes a bug that resulted from a map size invalidation that triggered a re-render with a new bbox which updated the url which caused a transition which closed the modal before the user could interact with it. This PR solves the issue by allowing the drawing mode change to initiate the full-screen change but requiring an explicit call to toggle the full-screen mode off. It's not the cleanest solution and it may be wise to make the full-screen mode initiation more explicit as well, but I didn't do that in this PR.
* Within the scene browser, draw a new AOI to use as a search filter
* Notice that when you finish drawing the shape, you are able to interact with the modal to save or cancel the drawing
Closes #4467

Add persistent modal option

---

CHANGELOG.md
app-backend/build.sbt
app-backend/project/Dependencies.scala

This PR removes `geotrellis-raster-testkit`dependency since:
* it is not being used
* `http://maven.geotoolkit.org/org/locationtech/geotrellis/geotrellis-raster-testkit_2.11/2.2.0/geotrellis-raster-testkit_2.11-2.2.0.pom` gives 404.
* CI

Remove geotrellis-raster-testkit dependency

---

CHANGELOG.md
app-backend/api/src/main/scala/project/Routes.scala

This PR fixes permission checks for project and project datasource in lab analyses.
* Go to lab, create an analysis from a template
* Select projects and bands for this analysis and make sure it works as expected
* Share the analysis with account B
* Log in with account B and check the analysis being shared
Closes #4448

Fix permission checks on project and datasource for lab analyses 

---

CHANGELOG.md
app-backend/backsplash-server/src/main/resources/logback.xml

This PR makes backsplash respect the RF_LOG_LEVEL environment variable for its own logs and quiets down the `nio1` logs coming out of blaze server a bit.
* Verify configuration matches api server's logback.xml
* Bring up your backsplash server with a less noisy log level than debug and confirm you don't get as many boring logs

Respect RF_LOG_LEVEL environment variable in backsplash

---

CHANGELOG.md
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/MosaicImplicits.scala

This PR binds out of the IOs constructing mosaics in two places, instead of assigning the IO and yielding the IO inside a raster lit. This makes it so that we're constructing a RasterLit out of a Raster[...] instead of an IO[Raster].
* turn your tile caches off
* use the app
* you should get tiles and no warnings about unallowable casts

Make RasterLits out of Rasters instead of IO[Raster]s

---

CHANGELOG.md
app-backend/api/src/main/scala/user/Routes.scala
app-backend/datamodel/src/main/scala/User.scala
app-backend/db/src/main/scala/UserDao.scala

This PR more carefully selects the subset of user fields to return to clients when doing user searches.
* demo
azavea/raster-foundry-platform#609

Encode smaller subset of user fields in search

---

docker-compose.test.yml

Bump app-frontend NodeJS image version from 6 to 10.
Connects #4431 
See CI checks below.

Bump app-frontend NodeJS image version from 6 to 10

---

CHANGELOG.md
scripts/load_development_data

Adds download of imagery as part of development environment setup and resets Azavea specific development environment to be COG Only
I kept existing admin and organizations set up so that when we work on permissions and sharing those things exist. The main thrust of changes was creating a variety of projects, some of which are tied to local files, for easier development and testing.
* Run `./scripts/load-development-data --download`
* Start servers and browse projects and analyses
Closes https://github.com/azavea/raster-foundry-platform/issues/592

Add Image and Local Files to Development Environment Setup

---

CHANGELOG.md
app-backend/datamodel/src/main/scala/Project.scala
app-backend/datamodel/src/test/scala/com/azavea/rf/datamodel/implicits/Generators.scala
app-backend/db/src/main/scala/ProjectDao.scala
app-backend/db/src/main/scala/ProjectLayerDao.scala
app-backend/migrations/src/main/scala/migrations/157.scala
app-backend/migrations/src/main/scala/migrations/Summary.scala
app-backend/migrations/src_migrations/main/scala/157.scala

This PR:
* adds a migration that creates relationship among projects, project layers, and scenes and populates corresponding tables
* fixes a bug in the schema of `project_layers` table
* fixes a bug in `ProjectLayerDao`
* updates `Project` data model
* updates `insertProject` method of `ProjectDao` so that a default project layer is inserted along with it
* Check if the migration makes sense, and make sure it runs successfully
* Make sure that the property tests pass
**Updated 01/17/2019**:
* From within the DB: check that `project_layers` table is …

Add relationship between project layers and scenes

---

app-frontend/src/app/pages/imports/datasources/list/list.html
app-frontend/src/app/pages/imports/raster/raster.html
app-frontend/src/assets/styles/sass/pages/_dashboard.scss

Align the search box and owner filters of the various dashboard pages
- view the following pages:
- Projects
- Data: Rasters
- Data: Vectors
- Data: Datasources
Closes #4507 4188

fixes the alignment of search and owner filter on dashboard pages

---

app-frontend/src/app/components/lab/inputNode/inputNode.module.js
app-frontend/src/app/components/projects/projectSelectModal/projectSelectModal.html

Shows the lab node label in the project select modal.
* Open an analysis
* Open the modal to select a project for an input
Closes #4346

shows name of node when selecting a project for analysis

---

CHANGELOG.md
app-backend/api/src/main/scala/datasource/Routes.scala
app-backend/api/src/main/scala/project/Routes.scala
app-backend/api/src/main/scala/scene/Routes.scala
app-backend/api/src/main/scala/shape/Routes.scala
app-backend/api/src/main/scala/toolrun/Routes.scala
app-backend/api/src/main/scala/tools/Routes.scala
app-backend/db/src/main/scala/ObjectPermissions.scala

Switch from using ownership to permissions when viewing, adding, and removing permissions
* Frontend changes are being worked on for a separate pr
* Verify that users with edit permissions are now authorized to make requests to the permissions endpoints on datasources, projects, scenes, shapes, tools, and tool-runs
Closes #4455

 Allow users with edit permissions on objects to share them

---

CHANGELOG.md
app-backend/api/src/main/scala/project/Routes.scala
app-backend/datamodel/src/main/scala/ProjectLayer.scala
app-backend/db/src/main/scala/ProjectLayerDao.scala

This PR adds endpoints for each CRUDL operation.
It is currently not possible to delete a default layer due to the FK constraint from projects. If we want to allow this or not is probably worth a discussion.
* `GET /api/projects/{someProjectId}/layers` -- it should work and you can grab the layer id from here to further test endpoints
* `GET /api/projects/{someProjectId}/layers/{someLayerId}` -- use the above id if you want
* copy the response and update some fields (name, colorGroupHex, or geometry) and then PUT it back, then GET it again to confirm the changes
* create a project layer with a `POST /api/projects/{someProjectId}/layers`
* `GET` it back to confirm it was successful
* `DELETE` it
Closes #4452

Project layer CRUDL endpoints

---

CHANGELOG.md
app-backend/api/src/main/scala/project/Routes.scala
app-backend/datamodel/src/main/scala/SceneToLayer.scala
app-backend/datamodel/src/main/scala/SceneToProject.scala
app-backend/db/src/main/scala/ProjectDao.scala
app-backend/db/src/main/scala/ProjectScenesDao.scala
app-backend/db/src/main/scala/SceneToLayerDao.scala
app-backend/db/src/main/scala/SceneToProjectDao.scala
app-backend/db/src/main/scala/SceneWithRelatedDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/SceneToLayerDaoSpec.scala
app-backend/migrations/src/main/scala/migrations/158.scala
app-backend/migrations/src/main/scala/migrations/Summary.scala
app-backend/migrations/src_migrations/main/scala/158.scala

This PR:
* adds:
- a migration to populate `scenes_to_layers` table with projects' default layer ids associated with their scenes
- `SceneToLayerDao` and its property tests that mirror the previous `SceneToProjectDao`
- `SceneToLayer` data model
* updates:
- `ProjectDao` so that adding/replacing/deleting scenes from projects will insert/update/delete from both `scenes_to_layers` and `scenes_to_projects` tables (the latter is still preserved since we can't drop the table and the dao yet)
- project endpoints so that it uses both `SceneToLayerDao` and `SceneToProjectDao` (same reason as the above)
**Updated on 01/23/2019:**
It also makes scene ordering consistent when mosaic-ing project scenes together and getting the project scene list
- ~[Swagger …

Add SceneToLayerDao; Update ProjectDao and Project Endpoints

---

CHANGELOG.md
app-frontend/src/app/components/common/itemActionButtons/itemActionButtons.html
app-frontend/src/app/components/common/itemActionButtons/itemActionButtons.js
app-frontend/src/app/components/datasources/datasourceItem/datasourceItem.html
app-frontend/src/app/components/lab/templateItem/templateItem.html
app-frontend/src/app/components/lab/templateItem/templateItem.module.js
app-frontend/src/app/components/permissions/permissionModal/permissionModal.html
app-frontend/src/app/components/permissions/permissionModal/permissionModal.js
app-frontend/src/app/components/projects/projectItem/projectItem.html
app-frontend/src/app/components/projects/projectItem/projectItem.module.js
app-frontend/src/app/components/scenes/importList/importList.html
app-frontend/src/app/components/scenes/importList/importList.module.js
app-frontend/src/app/index.components.js
app-frontend/src/app/index.routes.js
app-frontend/src/app/pages/imports/datasources/list/list.html
app-frontend/src/app/pages/imports/datasources/list/list.module.js
app-frontend/src/app/pages/imports/vector/vector.html
app-frontend/src/app/pages/imports/vector/vector.module.js
app-frontend/src/app/pages/lab/analysis/analysis.html
app-frontend/src/app/pages/lab/analysis/analysis.js
app-frontend/src/app/pages/lab/browse/analyses/analyses.html
app-frontend/src/app/pages/lab/browse/analyses/analyses.js
app-frontend/src/app/pages/lab/browse/templates/templates.html
app-frontend/src/app/pages/lab/browse/templates/templates.js
app-frontend/src/app/pages/projects/edit/edit.html
app-frontend/src/app/pages/projects/edit/edit.module.js
app-frontend/src/app/pages/projects/list/list.html
app-frontend/src/app/services/auth/permissions.service.js
app-frontend/src/app/services/projects/project.service.js

Use object permissions to determine whether a user can share on the frontend
Allows sharing on:
* Projects
* Analyses
* Templates
* Scenes
Added ownership filters, but can't fully share yet due to concerns requiring further investigation:
* Shapes
* Datasources
Leaving shapes and datasources to another issue because they require some thinking about
* Using two separate accounts, Verify that the listed objects are shareable
* Projects
* Analyses
* Templates
* Scenes
* Verify …

Allow object resharing on the frontend

---

CHANGELOG.md
app-backend/api/src/main/scala/project/Routes.scala
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/BacksplashImage.scala
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/HistogramStore.scala
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/MosaicImplicits.scala
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/Parameters.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/AuthedAutoSlash.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Authorizers.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/HistogramStoreImplicits.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Main.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/MosaicService.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/ProjectStoreImplicits.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/ProjectToProjectLayerMiddleware.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/SceneService.scala
app-backend/datamodel/src/main/scala/Project.scala
app-backend/datamodel/src/main/scala/ProjectLayer.scala
app-backend/datamodel/src/test/scala/com/azavea/rf/datamodel/implicits/Generators.scala
app-backend/db/src/main/scala/LayerAttributeDao.scala
app-backend/db/src/main/scala/ProjectDao.scala
app-backend/db/src/main/scala/ProjectLayerDao.scala
app-backend/db/src/main/scala/SceneToProjectDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/ProjectDaoSpec.scala
app-backend/db/src/test/scala/com/azavea/rf/database/SceneToLayerDaoSpec.scala
app-backend/migrations/src/main/scala/migrations/160.scala
app-backend/migrations/src/main/scala/migrations/Summary.scala
app-backend/migrations/src_migrations/main/scala/160.scala

This just reopens #4523 for Jenkins reasons.
This PR adds projectstore evidence to the SceneToLayerDao, moves mosaic fetches for projects from projects to layers, and implements the mosaic TMS endpoint for layers so that testing instructions have anything useful to say.
~[wip] until I figure out what to do about histograms and depends on #4533~ Figured it out! There are only layers -- the defualt `/project id/z/x/y` match has actually been removed from the mosaic service, and requests to it get rewritten in [a new middleware](https://github.com/raster-foundry/raster-foundry/blob/feature/js/add-scenetolayerdao-project-store/app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/ProjectToProjectLayerMiddleware.scala).
* **run migrations** or you might spend a few minutes …

Add scene to layer dao project store evidence

---

CHANGELOG.md
app-backend/build.sbt
app-backend/datamodel/src/main/scala/ToolRun.scala
app-backend/datamodel/src/test/scala/com/azavea/rf/datamodel/implicits/Generators.scala
app-backend/db/src/main/scala/ToolRunDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/ToolRunDaoSpec.scala
app-backend/migrations/src/main/scala/migrations/161.scala
app-backend/migrations/src/main/scala/migrations/Summary.scala
app-backend/migrations/src_migrations/main/scala/161.scala
app-frontend/src/app/services/analysis/analysis.service.js

This PR adds tempate, project, and project layer IDs to tool runs to make some filtering possible that isn't currently.
~Still working on template ID tests because templates don't even have an arbitrary instance omg but backend reviewable as is~
* run migrations
* assemble the api server
* bring up ur servers
* create a new analysis from a template in the frontend
* confirm that the new analysis has the template id filled in in the db
Closes #4530

Add filter fields to tool runs

---

CHANGELOG.md
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/HealthcheckService.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Main.scala
app-backend/build.sbt
app-backend/project/Dependencies.scala
app-backend/project/Version.scala

This PR makes the backsplash healthcheck endpoint actually check health.
I tried making those improvements again this morning, and I'm having no luck. I keep running into diverging implicit expansion in places where I'm basically copying the code from the docs. Given that this fails in the case where we really want it to fail, I'm going to bail on this for now and move on to other pressing issues.
~There are two improvements that I think could reasonably be made --~
1. run the healthchecks in parallel. This is supposedly possible using `HealthCheck.parTupled`, but I had no success with it. I'll try again tomorrow morning.
2. encode the health check failures, rather than "no good", in the `Sick` case. This is supposedly possible [by …

Add improved health check that checks health

---

deployment/ansible/roles/raster-foundry.jenkins/tasks/main.yml
deployment/ansible/roles/raster-foundry.nexus/tasks/main.yml

Add `restart: always` to Nexus Docker Compose service.
I had already tried this solution before, but it looks like I was running the playbook against the internal Nexus instance by mistake, rather than the Raster Foundry Jenkins instance.
Fixes https://github.com/azavea/raster-foundry-platform/issues/607
Execute the playbook and restart the EC2 instance:
```bash
$ ansible-playbook \
-i deployment/ansible/inventory \
-K deployment/ansible/raster-foundry-jenkins.yml \
--key-file=~/.ssh/raster-foundry-stg.pem
```
```bash
$ ssh rfjenkins
ubuntu@ip-172-31-52-80:~$ sudo reboot now
```
See that the Docker Compose service came back up:
```bash
$ ssh rfjenkins
ubuntu@ip-172-31-52-80:~$ docker ps
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS …
```

Add restart: always to Nexus Docker Compose service

---

CHANGELOG.md
app-backend/db/src/main/scala/ProjectLayerDao.scala

This PR allows updating project id on project layers. If you can't update project id, you can't associate a project layer with a project after you make the project. If you can't associate project layers with projects, the join from projects to project layers returns no rows. If the join from projects to project layers returns no rows, the join from the join to scenes to layers returns no rows, so you can't have any imagery served for project layers, which is a drag, because that's where imagery comes from.
:train:
- ~Any new SQL strings have tests~ (no currently existing `ProjectLayerDaoSpec`)
* create a new project
* add a scene to it (it can be already ingested, it doesn't matter)
* you should get tiles

Set project id on new project creation

---

CHANGELOG.md
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Main.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/MosaicService.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/ProjectToProjectLayerMiddleware.scala

This PR rewrites the rest of the mosaic routes to use layers instead of projects.
This will also include some work on getting the project histograms visualizing in the frontend again, since that's been broken for a while and is a really easy way to confirm that the endpoint still "works" in a backwards compatible way (I think it's been broken since backsplash, but possibly longer, since COG histograms didn't exist in the previous tile server).
* `backsplash-server/assembly` in sbt
* browse scenes in a project to get a nice bounding box inside its bounds
* get a token
* `http :8081/<project id>/export zoom==9 bbox==<your bbox> token==<your token without Bearer> > img.png`
* `http :8081/<project id>/export zoom==9 bbox==<your bbox> token==<your token without Bearer> Accept:image/tiff > …

Rewrite all project mosaic routes to project layer routes

---

app-tasks/Dockerfile
app-tasks/rf/requirements.txt

This PR fixes problems with missing `_gdal_array` in gdal 2.4.0, which is what the debian sid repo upgraded to recently. As a result, it fixes some import problems, specifically around MODIS, but possibly in other cases as well.
* rebuild batch container
* bring up ur servers
* create a MODIS upload (add a MODIS scene to a project from the CMR)
* `rf process-upload <that upload id>` from the batch container
* it should work
Closes #4561

Use blessed openjdk gdal container + upgrade requests

---

app-tasks/rf/src/rf/uploads/landsat_historical/factories.py

This PR makes it so that we try to read from `/tmp/...` instead of `//tmp/...` for locally downloaded historical landsat imagery.
- ~Description of PR is in an appropriate section of the [changelog](https://github.com/raster-foundry/raster-foundry/blob/develop/CHANGELOG.md) and grouped with similar changes if possible~ no changelog based on this morning's discussion of "bugs that didn't make it to prod"
Unclear why this ever worked -- maybe changing the container got us different behavior on repeated `/`es to start a filename?
* create an upload for a Landsat 7 scene and for a Landsat 4/5 scene
* process them
* the process should complete successfully

Fix landsat historical local paths construction

---

CHANGELOG.md
app-frontend/src/app/components/pages/project/layers/index.html
app-frontend/src/app/components/pages/project/layers/index.js
app-frontend/src/app/components/projects/projectLayerCreateModal/projectLayerCreateModal.html
app-frontend/src/app/components/projects/projectLayerCreateModal/projectLayerCreateModal.js
app-frontend/src/app/services/projects/project.service.js
app-frontend/src/assets/styles/sass/_shame.scss

This PR adds project layer creation workflow (the modal part) for UI of the project layers list page.
The second UI in the original issue #4541 is moved to another one, which is reflected in the issue comment.
* Go to `http://localhost:9091/v2/project/<project ID>/layers`
* Click on `+ New Layer` and use the modal to create a new project layer. Make sure it works.
* Click on `+ New Layer`, fill in the form in the modal, stop the dev server, click on create, make sure that it …

Add project layer creation workflow on UI

---

CHANGELOG.md
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/ProjectStoreImplicits.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/SceneService.scala
app-backend/db/src/main/scala/SceneDao.scala

This PR includes a geometry filter in trying to read scenes for putting scenes outside of projects on the map with backsplash.
* open the preview modal for a scene while watching your network tab
* you shouldn't see any 500s
Closes #4525

Use geom filter in scene service

---

scripts/cipublish

This is to get around a permissions problem that sometimes happens
when using docker if the `app-lambda/opt` directory is generated via
docker at some point

Use docker-compose for copying files

---

CHANGELOG.md
app-backend/api/src/main/scala/project/QueryParameters.scala
app-backend/api/src/main/scala/project/Routes.scala
app-backend/common/src/main/scala/datamodel/QueryParameters.scala
app-backend/common/src/main/scala/datamodel/Scene.scala
app-backend/common/src/test/scala/com/azavea/rf/datamodel/implicits/Generators.scala
app-backend/db/src/main/scala/ProjectDao.scala
app-backend/db/src/main/scala/ProjectLayerDatasourcesDao.scala
app-backend/db/src/main/scala/ProjectLayerScenesDao.scala
app-backend/db/src/main/scala/SceneWithRelatedDao.scala
app-backend/db/src/main/scala/filters/Filterables.scala
app-backend/db/src/test/scala/com/azavea/rf/database/ProjectLayerDatasourceDaoSpec.scala
app-backend/db/src/test/scala/com/azavea/rf/database/ProjectLayerScenesDaoSpec.scala

This PR adds a few endpoints to handle requests for scenes within project layers. They function similarly to their project level analogs.
- `GET /projects/{projectId}/layers/{layerId}/scenes` to get a list of scenes within a layer
- `PUT /projects/{projectId}/layers/{layerId}/scenes` to replace the list of scenes within a layer
- `POST /projects/{projectId}/layers/{layerId}/scenes` to add scenes to a layer
- `DELETE /projects/{projectId}/layers/{layerId}/scenes` to remove scenes from a layer
- `GET /projects/{projectId}/layers/{layerId}/scenes/datasources` to get a list of distinct datasources for the scenes within a layer
The spec is being updated in another task that involves ensuring it is correct for all layer routes.
* Test each of the new routes using something like curl, postman, …

Add API endpoints for project-layer scenes

---

app-backend/backsplash-export/src/main/resources/log4j.xml
app-frontend/src/app/pages/projects/edit/exports/new/new.html
app-frontend/src/app/pages/projects/edit/exports/new/new.module.js
app-tasks/Dockerfile
app-tasks/rf/src/rf/commands/export.py

This PR updates the python cli for the `batch` container to use the commands from fancy new COG export introduced in #4515. It also updates the project export frontend to send some fields that are necessary for exports to cooperate.
* **note that exports require masks now**
* make a non-dropbox export of a project
* `rf export <export id>` from the `batch` container
* should succeed and write your export where you expected to write it
* update that project in the db to point to a tool run
* run it again
* should succeed and write your export where you expected to write it
* make a dropbox export
* export it
* it should succeed and write your export where you expected to write it

Remove deprecated export interaction

---

scripts/cibuild

Add missing export jar to cibuild process
```
cbrown@trout:~/Projects/raster-foundry/app-tasks/jars$ ls -lh
total 461M
-rw-r--r-- 1 cbrown cbrown 207M Feb 11 08:52 backsplash-export-assembly.jar
-rw-r--r-- 1 cbrown cbrown 255M Feb 11 08:50 batch-assembly.jar
cbrown@trout:~/Projects/raster-foundry/app-tasks/jars$ 
```

Add export jar assembly to CI build process

---

CHANGELOG.md
app-backend/common/src/main/scala/datamodel/Upload.scala
app-backend/common/src/test/scala/com/azavea/rf/datamodel/UploadSpec.scala
app-backend/common/src/test/scala/com/azavea/rf/datamodel/implicits/Generators.scala
app-backend/db/src/main/scala/UploadDao.scala
app-backend/migrations/src/main/scala/migrations/163.scala
app-backend/migrations/src/main/scala/migrations/Summary.scala
app-backend/migrations/src_migrations/main/scala/163.scala
app-tasks/rf/src/rf/commands/process_upload.py
app-tasks/rf/src/rf/models/upload.py
app-tasks/rf/src/rf/uploads/modis/factories.py
app-tasks/rf/src/rf/uploads/planet/factories.py

Allow specifying a layer ID when creating an upload. Specifying a project and layer ID will cause the upload to use the projects/{}/layers/{}/scenes endpoint to add scenes instead of the projects/{}/scenes endpoint.
* Run migrations
* Rebuild your batch container to pull in the updated python scripts
* Upload a small tif to a project
* process the upload using the normal RF script inside the batch container
* Verify that the scene appears in the project
* Upload a second tif to a project
* using psql, set the layer_id to a layer in the project.
* process the upload and verify that it …

Support uploads to project layers on the api

---

CHANGELOG.md
app-backend/db/src/main/scala/ProjectDao.scala
app-backend/migrations/src/main/scala/migrations/164.scala
app-backend/migrations/src/main/scala/migrations/Summary.scala
app-backend/migrations/src_migrations/main/scala/164.scala
app-frontend/src/app/components/pages/project/layers/index.html
app-frontend/src/app/components/projects/layerItem/index.html
app-frontend/src/app/components/projects/projectLayerCreateModal/projectLayerCreateModal.html
app-frontend/src/app/components/projects/projectLayerCreateModal/projectLayerCreateModal.js

This PR:
- adds a migration to update existing default layer color group hex code from `#FFFFFF` to `#738FFC`, which is a `$brand-primary` color
- updates `ProjectDao` to use same color as above when inserting project default layer upon creating a new project
- removes layer re-ordering in layer list UI
- removes layer sorting in layer list UI
- removes layer type drop down in layer create modal UI
* Run migrations
* Go to `v2/project/<projectId>/layers` UI and check if the project default layer's checkbox has a color
* Create a new project, go to …

Fix default layer color group; Remove layer re-ordering

---

CHANGELOG.md
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/MamlAdapter.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/ToolStoreImplicits.scala
app-backend/common/src/main/scala/ast/MamlConversion.scala
app-backend/common/src/main/scala/ast/MapAlgebraAST.scala
app-backend/common/src/main/scala/ast/codec/MapAlgebraLeafCodecs.scala

This PR adds `LayerRaster`s to `MapAlgebraLeaf`s, so we can use layers for evaluating ASTs.
SceneToProjectDao project store implicits weren't removed, because we don't have a good way to rewrite the project source to point to a layer at the point where we're doing that read -- I could cheat and throw in an `unsafeRunSync` but I'd feel pretty gross about it, especially since it'd required `backsplash-core` to depend on the `db` subproject
* reassemble your servers, bring them up
* make an analysis from the `Local File Single Scene` project
* update its execution parameters in the database to:
```json
{
"id": "6278bbbb-1ae2-4244-85cb-624502dc521d",
"args": [
{
"id": "75d675a3-2797-4c19-a289-2099ae26aa1d",
"band": 0,
"type": "layerSrc",
"layerId": "<YOUR DEFAULT LAYER ID>",
"metadata": { …
```

Add layer source and remove scene / COG rasters

---

CHANGELOG.md
app-frontend/src/app/pages/projects/edit/scenes/scenes.html

This change was overwritten a few months ago and this is just putting it back to the intended state. On project scene list, instead of displaying a trash icon, we display the text remove. This will help users understand they're not deleting a scene from the app, but simply removing it from the project.
Closes #2827

replaces trash icon with text: remove

---

CHANGELOG.md
app-backend/api/src/main/scala/project/Routes.scala
app-backend/common/src/test/scala/com/azavea/rf/datamodel/implicits/Generators.scala
app-backend/db/src/main/scala/ProjectLayerScenesDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/ProjectLayerDatasourceDaoSpec.scala
app-backend/db/src/test/scala/com/azavea/rf/database/ProjectLayerScenesDaoSpec.scala
app-frontend/src/app/components/pages/project/layers/index.html
app-frontend/src/app/components/pages/project/layers/index.js
app-frontend/src/app/components/projects/index.js
app-frontend/src/app/components/projects/layerItem/index.html
app-frontend/src/app/components/projects/layerItem/index.js
app-frontend/src/app/components/projects/layerStats/index.html
app-frontend/src/app/components/projects/layerStats/index.js
app-frontend/src/app/services/projects/project.service.js
app-frontend/src/assets/styles/sass/_shame.scss

This PR adds an `rf-layer-stats` component for displaying scene counts for each layer and a route for fetching scene counts for all layers in a project at once.
I opted for a new endpoint that fetches all the counts at once over firing off 50 requests for counts (1 / layer * page size).I did this because it was easy and it gives us an anchor to attach more stats to, should we wish to calculate them.
* reassemble your api server
* bring up your server
* get a project id and navigate to `/v2/project/<id>`
* observe that you have counts of scenes for all the layers that have scenes in them
Closes #4572

Add layer stats to project layers

---

CHANGELOG.md
app-frontend/package.json
app-frontend/src/app/pages/projects/edit/exports/new/new.module.js
app-frontend/yarn.lock
app-tasks/rf/requirements.txt

This PR upgrades gdal-js so it can read jpeg-compressed tiffs.
* `gdal_translate -scale -ot Byte -of GTiff -co COMPRESS=JPEG some-tiff.tiff jpeg-compressed.tiff`
* try to upload your tiff
* observe that gdal-js can read it and understand what's inside
* rebuild your batch container
* process the upload (this uses requests to do api interaction for uploads and scenes)
* observe that you get an obviously lossy compressed image at the end
Closes #3621 
Closes #4577

Upgrade gdal-js and requests

---

app-backend/project/plugins.sbt

Bump [sbt-pgp](https://github.com/sbt/sbt-pgp) to version `1.1.2` to fix the ability to re-run CI builds in same workspace. 
The original problem was caused by [a bug](https://github.com/sbt/sbt/issues/3725) in sbt-pgp where the sbt `overwrite` value was being hardcoded to `false`.
We use sbt-pgp in part of the pipeline to sign and publish build artifacts to Sonatype OSSRH and Maven Central.
Fixes https://github.com/azavea/raster-foundry-platform/issues/615
First, grab the signing private key from the Jenkins server:
```bash
> rbreslow@maiden raster-foundry (feature/jrb/sbt-pgp-1.1.2) $ ssh rfjenkins
ubuntu@ip-172-31-52-80:~$ sudo cp /var/lib/jenkins/.gnupg/secring.gpg .
ubuntu@ip-172-31-52-80:~$ sudo chown ubuntu:ubuntu secring.gpg
```
```bash
> rbreslow@maiden raster-foundry …
```

Bump sbt-pgp to version 1.1.2

---

CHANGELOG.md
app-frontend/src/app/components/pages/project/layer/scenes/scenes/index.js
app-frontend/src/app/components/pages/project/layers/index.js
app-frontend/src/app/components/scenes/sceneImportModal/sceneImportModal.controller.js
app-frontend/src/app/services/projects/project.service.js
app-frontend/src/app/services/scenes/scene.service.js

This PR makes some changes to the import modal and the scene and project services to handle importing imagery directly to layers.
Waiting for #4615 to get merged so that it can be added to the project layer scene list view. As of now, it only is visible as an option for each project layer on the project layers list view.
* Create a layer in a project that is not the default layer
* Upload both COG and non-COG to and see that they end up in the right layer (since one is POSTed by the front-end and the other by the batch job)
Closes #4587

UI for project layer uploads

---

README.md
Vagrantfile

Updates the port mapping table in the README to more accurately represent the Vagrant port mapping. Also, remove the stray reference to `publish-jars` STRTA.
~- [ ] Description of PR is in an appropriate section of the [changelog](https://github.com/raster-foundry/raster-foundry/blob/develop/CHANGELOG.md) and grouped with similar changes if possible~
See rendered version of the `README`. Ensure that references to `publish-jars` are no longer present. …

Fix port mappings and remove publish-jars from README

---

scripts/update

This check wasn't working. `run_database_migrations()` would try to run initialize migrations even if they already were initialized, and then the script would die. I applied a similar fix as in #4626. 
Not sure what the underlying problem is, but it may have to do with the new images we built in https://github.com/azavea/docker-postgis/pull/16.
Run `update` and see that migrations are applied as they should, the first and second times:
```bash
vagrant@vagrant:/opt/raster-foundry$ ./scripts/update
...
Running application database migrations
ERROR:  relation "__migrations__" does not exist
LINE 1: select 1 from __migrations__
^
Starting raster-foundry_postgres_1  ... done
Starting raster-foundry_memcached_1 ... done
[info] Loading settings from plugins.sbt ...
[info] Loading project …
```

Fix run_database_migrations method in scripts/update

---

app-backend/Dockerfile.backsplash
app-backend/Dockerfile.build
app-backend/backsplash-server/Dockerfile
app-backend/backsplash/Dockerfile
docker-compose.java.yml

* Remove duplicate Backsplash Dockerfiles
* Use blessed [azavea/openjdk-gdal](https://github.com/azavea/docker-openjdk-gdal) container image in `app-backend/backsplash-server/Dockerfile`
Resolves #4464 
Build `api` and `backsplash-server` assembly JARs:
```bash
vagrant@vagrant:/opt/raster-foundry$ ./scripts/console sbt
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /opt/raster-foundry/app-backend/project
[info] Loading settings from version.sbt,build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Loading settings from build.sbt ...
[info] Resolving key references (11180 settings) ...
[info] Set current project to root (in build …
```

Swap Backsplash base image

---

CHANGELOG.md
app-frontend/src/app/components/common/index.js
app-frontend/src/app/components/common/listItem/index.html
app-frontend/src/app/components/common/listItem/index.js
app-frontend/src/app/components/pages/project/analysis/index.html
app-frontend/src/app/components/pages/project/analysis/index.js
app-frontend/src/app/components/pages/project/createAnalysis/index.html
app-frontend/src/app/components/pages/project/createAnalysis/index.js
app-frontend/src/app/components/pages/project/index.js
app-frontend/src/app/components/pages/project/layers/index.html
app-frontend/src/app/components/pages/project/layers/index.js
app-frontend/src/app/components/pages/project/project/index.html
app-frontend/src/app/components/pages/project/project/index.js
app-frontend/src/app/components/projects/layerItem/index.html
app-frontend/src/app/components/projects/layerItem/index.js
app-frontend/src/app/components/projects/navbar/index.js
app-frontend/src/app/index.components.js
app-frontend/src/app/index.routes.js
app-frontend/src/app/services/analysis/analysis.service.js
app-frontend/src/assets/styles/sass/_shame.scss
app-frontend/src/assets/styles/sass/base/_helpers.scss

Allow selecting multiple layers and creating analyses for them
The edit views and aoi views are separate issues
* From the layers view:
* use the dropdown menu on a layer to go to the create-analysis view, and verify that the correct layer is listed on the left
* Select multiple layers and use the select bar Create -> analysis menu to go to the create-analysis view
* Load the create-analysis view directly and verify that it uses the default layer
* after selecting and …

Add create-analysis route / components

---

app-frontend/src/app/components/common/listItem/index.html
app-frontend/src/app/components/datasources/datasourceItem/datasourceItem.html
app-frontend/src/app/components/exports/exportItem/exportItem.html
app-frontend/src/app/components/projects/layerItem/index.html
app-frontend/src/app/components/scenes/projectSceneItem/index.html
app-frontend/src/app/components/scenes/sceneItem/sceneItem.html
app-frontend/src/app/components/vectors/shapeItem/shapeItem.html
app-frontend/src/assets/styles/sass/_shame.scss

Fixes #4681
I made a soft attempt at standardizing the html for text overflows throughout at the app. Some changes might not have been needed, but now the code should be near identical in each portion of the app that this technique is used.
* Open v2 projects and check a long named analysis for ellipsis overflowing.

fixes text overflow issue throughout app

---

CHANGELOG.md
app-backend/api/src/main/scala/toolrun/QueryParameters.scala
app-backend/api/src/main/scala/tools/QueryParameters.scala
app-backend/api/src/main/scala/utils/QueryParameters.scala
app-backend/common/src/main/scala/datamodel/QueryParameters.scala
app-backend/db/src/main/scala/filters/Filters.scala
app-frontend/src/app/services/auth/permissions.service.js

Add owner query parameters to tools and tool runs
Support multiple owner query parameters and check that owners are in the list of owners.
* run `api/assembly` in sbt and start your webserver
* Make a query to `api/tools/?owner=default` and observe that it works
* Make a second query to `api/tools/?owner=default&owner={another user id}` and observe that results from both users appear
* repeat the above with `api/tool-runs/?owner=default&owner={another user id}`. You may need to create some fake tool-runs to filter in/out
Closes …

Add owner qp to tools and tool-runs, support multiple owner qps

---

CHANGELOG.md
app-frontend/src/app/components/pages/project/project/index.html
docker-compose.yml

This PR fixes a bug in V2 UI so that it won't show duplicated views (which probably due to a bad merge or rebase lately).
* Use the V2 UI and make sure the views look correct

Fix duplicated V2 UI bug

---

deployment/ansible/raster-foundry.yml
scripts/bootstrap

I uncovered this when working on https://github.com/azavea/raster-foundry-platform/issues/635.
`shellcheck=0.3.7` from Ubuntu 16.04 yields:
```bash
vagrant@vagrant:/opt/raster-foundry$ find ./scripts -type f -print0 | xargs -0 -r shellcheck
In ./scripts/bootstrap line 49:
function generate_sbtopts() {
^-- SC2120: generate_sbtopts references arguments, but none are ever passed.
In ./scripts/bootstrap line 81:
generate_sbtopts
^-- SC2119: Use generate_sbtopts "$@" if function's $1 should mean script's $1.
In ./scripts/bootstrap line 84:
generate_sbtopts
^-- SC2119: Use generate_sbtopts "$@" if function's $1 should mean script's $1.
```
We're running `shellcheck=0.3.3` in the Ubuntu 14.04 CI box right now.
According to the [change log](https://github.com/koalaman/shellcheck/blob/master/CHANGE …

Resolve SC2120/SC2119 in scripts/bootstrap

---

CHANGELOG.md
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/error/Error.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/AnalysisService.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Error.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Main.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/MosaicService.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/SceneService.scala
app-backend/common/src/main/scala/Rollbar.scala

This PR
- adds rollbar reporting to backsplash
- reorganizes error handling so that it doesn't have to be included in every service
- has the rollbar notifier print what it would have sent to rollbar if it's development
I made some sort of ad hoc choices about which errors should be sent to rollbar and which we don't care about. The `BacksplashError`s that don't get sent to rollbar are:
- `RequirementFailedException` (e.g. band 3 does not exist because we rarely do anything useful with it)
- `WrappedDoobieException`
- `WrappedS3Exception`
- `NotAuthorizedException`
- `NoDataInRegionException`
Everything else will be sent to rollbar
* copy one of the NAIP tifs to `data/test-tif.tif`
* create a new project pointing to that scene
* move the scene
* try to view tiles
* observe the server …

Add rollbar to backsplash, move error-handling to routes

---

app-backend/api/src/main/scala/uploads/Routes.scala

This PR strips `Bearer ` from JWTs in the credentials service so that we can upload imagery again. The bug was introduced in #4656 when I changed the results of `extractTokenHeader` and didn't include testing uploads, which changed, as part of the testing instructions.
- ~Description of PR is in an appropriate section of the [changelog](https://github.com/raster-foundry/raster-foundry/blob/develop/CHANGELOG.md) and grouped with similar changes if possible~ staging bug only
* try to upload a tif from a local file
* you shouldn't get stuck
Closes azavea/raster-foundry-platform#645

Strip "Bearer " from tokens in credentials service

---

CHANGELOG.md
app-frontend/config/webpack/global.js
app-frontend/config/webpack/overrides.js.template
app-frontend/src/app/components/lab/templateItem/templateItem.module.js
app-frontend/src/app/pages/lab/browse/templates/templates.html
app-frontend/src/app/pages/lab/browse/templates/templates.js

Filter to platform users by default and show them as being owned by the platform
* Load the templates page and verify that it filters to the expected templates
* add your own user to the PLATFORM_USERS variable's array, restart webpack, and verify that your own templates show up but are shown as owned by the platform
Closes https://github.com/azavea/raster-foundry-platform/issues/640

Add PLATFORM_USERS override variable to webpack overrides

---

CHANGELOG.md
app-frontend/src/app/components/pages/project/createAnalysis/index.js
app-frontend/src/app/components/projects/layerItem/index.js

Use the layer geometry to wrap the tool-run in a mask node
This assumes that if the geometry has a type, it isn't null. Not all valid geometries have features (most of our shapes are polygons for instance)
* Add a valid geometry to a layer 
eg: `update project_layers set geometry = (select extent from projects where id = '{project id}') where id = '{layer id}';
* Using that layer, create a new analysis and verify that it has a mask node in the network panel
* Create a new …

Use layer geometry to add a mask when creating analysis in v2 ui

---

CHANGELOG.md
app-backend/api/src/main/scala/tools/QueryParameters.scala
app-backend/common/src/main/scala/datamodel/QueryParameters.scala
app-backend/common/src/main/scala/datamodel/Tool.scala
app-backend/common/src/test/scala/com/azavea/rf/datamodel/implicits/Generators.scala
app-backend/db/src/main/scala/ToolDao.scala
app-backend/db/src/main/scala/filters/Filterables.scala
app-backend/db/src/main/scala/filters/Filters.scala
app-backend/db/src/test/scala/com/azavea/rf/database/ToolDaoSpec.scala
app-backend/migrations/src/main/scala/migrations/168.scala
app-backend/migrations/src/main/scala/migrations/Summary.scala
app-backend/migrations/src_migrations/main/scala/168.scala

This PR adds `singleSource` to `Tool`s and changes the license field to be a nullable foreign key to licenses.
TODO:
* run migrations
* bring up your servers and frontend
* copy an API query for tools from the frontend
* update some of your tools to have `single_source = true` in the db
* run the API query you copied but with `singleSource=true`
* observe that you only get back those tools where you set that to be the case
Closes #4675

Add license fk and single source to tools

---

CHANGELOG.md
app-frontend/src/app/components/pages/project/createAnalysis/index.html
app-frontend/src/app/components/pages/project/createAnalysis/index.js
app-frontend/src/app/components/pages/project/layer/colormode/index.js

This PR uses the `singleSource` param from #4701 to filter to templates that layers can use for analyses.
I think it's fine that the analysis can't be rendered right now, since execution params aren't saturated? Hydrated? I don't remember what word we picked:
```json
{
"id": "a2816828-3e34-42c4-9085-e681acf8de61",
"args": [
{
"id": "7f8fdbda-fcc0-4ba7-8193-95741abaed78",
"args": [
{
"id": "39c2812f-fa5d-435a-b92a-77cf7995a0ad",
"type": "src",
"metadata": {
"label": "NIR"
}
},
{
"id": "7ceb6ca9-774b-4681-adae-ecb3a1bd2d75",
"type": "src",
"metadata": {
"label": "SWIR2"
}
}
],
"apply": "-",
"metadata": {
"label": "subtract"
}
},
{
"id": "4e19f95e-0240-4c18-8360-89f9f7f14103",
"args": [
{
"id": "39c2812f-fa5d-435a-b92a-77cf7995a0ad",
"type": "src",
"metadata": {
"label": "NIR"
}
},
{
"id": …
```

Use singleSource param to find valid templates for single layer analysis

---

app-backend/db/src/main/scala/Dao.scala
app-backend/db/src/main/scala/SceneWithRelatedDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/SceneWithRelatedDaoSpec.scala

This PR fixes `hasNext` calculations for inexact counts on scenes. It also makes sure that the test for scene pagination confirms that not only do we get the right number of scenes, but that we calculate `hasNext` correctly as well.
- ~Description of PR is in an appropriate section of the [changelog](https://github.com/raster-foundry/raster-foundry/blob/develop/CHANGELOG.md) and grouped with similar changes if possible~ staging only
* tests
* browse for scenes in frontend
* confirm you sometimes get a `load more scenes` button
Closes #4714

Fix calculation of hasNext for scene paginated responses

---

app-backend/backsplash-export/src/main/resources/reference.conf
app-backend/backsplash-export/src/main/scala/com/rasterfoundry/backsplash/ExportConfig.scala
app-backend/backsplash-export/src/main/scala/com/rasterfoundry/backsplash/ExportableInstances.scala
app-backend/backsplash-export/src/main/scala/com/rasterfoundry/backsplash/ExtentOfTiles.scala
app-backend/backsplash-export/src/main/scala/com/rasterfoundry/backsplash/RasterSources.scala
app-backend/backsplash-export/src/main/scala/com/rasterfoundry/backsplash/TileReification.scala
app-backend/backsplash-export/src/main/scala/com/rasterfoundry/backsplash/package.scala
app-backend/backsplash-export/src/test/scala/com/rasterfoundry/backsplash/TilesForExtentTest.scala
docker-compose.yml

This PR contains some attempts to pluck the low hanging fruit related to tiff export performance.
So far:
* In mem caching for raster sources
* Limiting requests to those tiffs which apparently intersect the segment being produced
* Using `parTraverse` to parallelize reads per segment
Creating Project Export
Running Export
Viewing Project Export
* Create an export for a project with multiple scenes
* Rebuild assembly for backsplash export (`./scripts/console sbt`, `project bacskplash-export`, `assembly`)
* Rebuild assembly for batch(`project batch`, `assembly`)
* Note the export ID in the server logs and run the following command in the batch container: (`./scripts/console batch "rf export <export id>"`)
* Download export and inspect with `gdalinfo`, internal tile size should be what is …

Export performance enhancement

---

deployment/ansible/group_vars/all.yml
deployment/ansible/group_vars/jenkins.yml

Update the following dependencies so that they align with the recent Jenkins operating system upgrade to Ubuntu Xenial:
- AWS CLI (this was to get on a more recent version)
- Docker
- Docker Compose (this was to get on a more recent version)
- JDK 8
- Execute the following steps while on the office network with your `raster-foundry-stg.pem` SSH key added to local authentication agent:
```console
$ cd deployment/ansible
$ ansible-galaxy install -f -r roles.yml -p roles
$ ansible-playbook -i inventory/jenkins raster-foundry-jenkins.yml
```
- Ensure that the `ansible-playbook` run applies cleanly.
- Check the output of a [recent](http://jenkins.staging.rasterfoundry.com/job/Raster%20Foundry/job/raster-foundry/job/develop/1188/) `develop` job that was executed after the changes in this branch …

Update Ansible group_vars to reflect Jenkins upgrade

---

CHANGELOG.md
app-frontend/src/app/components/pages/project/layer/aoi/index.js
app-frontend/src/app/components/pages/project/layer/export/index.html
app-frontend/src/app/components/pages/project/layer/export/index.js
app-frontend/src/app/components/projects/aoiDrawToolbar/index.html
app-frontend/src/app/pages/projects/edit/exports/new/new.module.js
app-frontend/src/app/services/projects/export.service.js
app-frontend/src/app/services/vectors/shapes.service.js
app-frontend/src/assets/styles/sass/_shame.scss
app-frontend/src/assets/styles/sass/layout/_sidebar.scss

This PR adds the project layer export creation UI using the new AOI creation component that defines an area for export.
* Go to v2 UI's project layer export list
* Click on `New export` on top
* Create an export on this export create UI with different export targets and resolutions
* Use the AOI definition component
* Make sure they create exports successfully
* Run `rf export <exportID>` command to check that the exports created with this UI works
Closes https://github.com/raster-foundry/raster-foundry/issues/4607

Add Project Layer Export Create UI

---

CHANGELOG.md
app-frontend/src/app/components/common/confirmationModal/confirmationModal.html
app-frontend/src/app/components/pages/project/layer/scenes/scenes/index.js

This PR checks layer AOI existence and routes to AOI creation UI if otherwise, when `Browse` is clicked on layer scene list UI.
* Go to a layer with AOI defined and browse scenes. It should allow you to do so.
* Go to a layer with AOI undefined and browse scenes. A modal should pop up and route you to AOI creation UI. After creating an AOI, it should bring you back to scene list UI. From here, browse for scenes again. It should allow you to do so this time.
Closes …

Enforce project layer AOI existence when browsing for scenes 

---

CHANGELOG.md
app-backend/common/src/main/scala/datamodel/License.scala
app-backend/db/src/main/scala/LicenseDao.scala
app-frontend/src/app/components/lab/templateCreateModal/templateCreateModal.html
app-frontend/src/app/components/lab/templateCreateModal/templateCreateModal.module.js
app-frontend/src/app/components/lab/templateItem/templateItem.html
app-frontend/src/app/components/lab/templateItem/templateItem.module.js
app-frontend/src/app/pages/lab/browse/templates/templates.html
app-frontend/src/app/pages/lab/browse/templates/templates.js
app-frontend/src/app/services/analysis/analysis.service.js

This PR makes it so that templates can be edited and so that licenses and single source options can be specified on templates at creation and edit time.
Does not implement compatible datasources. I don't have any idea what that's supposed to look like and I still don't think we have a good sense of what that constraint looks like. I didn't see compatible datasource in designs.
* reassemble your API server and bring it back up
* filter to templates you own
* edit a template you own
* set a license
* change single source
* update the template
* reopen the modal
* your options should have persisted
Closes #4726 
Closes #4674

Make templates editable

---

app-frontend/src/app/components/pages/project/analyses/analyses/index.js
app-frontend/src/app/redux/node-utils.js

This PR updates the tool run's render definition prior to rendering the tool run in the layer UI.
- ~Description of PR is in an appropriate section of the [changelog](https://github.com/raster-foundry/raster-foundry/blob/develop/CHANGELOG.md) and grouped with similar changes if possible~ Rendering problem was only present in staging
* create an analysis that adds things from a project layer (if there's any subtraction involved, the band selection will force the whole result to 0 right now -- I'm not sure what the plans are to make that different)
* view it
* tile viz should be consistent
Closes #4666

Fetch histogram and update render definition for layer analyses

---

CHANGELOG.md
app-backend/db/src/main/scala/SceneToLayerDao.scala
app-frontend/src/app/components/pages/project/layer/colormode/index.html
app-frontend/src/app/components/pages/project/layer/colormode/index.js

This PR enables the single-band color mode within the project-layer UI.
* Set a layer within a project to use single band mode and change the band and scheme and see that it is visualized correctly
* Ensure that other layers within the project are not affected by those single band options.
Closes #4705

Enable project layer single-band color mode

---

app-frontend/src/app/components/common/listItemWidgets/listItemActions/index.html
app-frontend/src/assets/styles/sass/base/_helpers.scss

Layers dropdown were not clickable in firefox.
- Fixes #4734
**Before**
**After**
For future, don't nest dropdown `ul` inside of `button` tags / the element that toggles opening the dropdown. If you nest the dropdown menu inside the thing that toggles it open, whenever you click on the dropdown, you are technically clicking the toggle, thus closing the dropdown.
* Open in firefox
* Open layer dropdown and click on a link within dropdown

fixes issue with layer menu dropdown on firefox

---

app-backend/build.sbt
app-backend/version.sbt

Remove `version.sbt` file and replace with a default value of `dev` in `build.sbt`.
Closes #4693
After merging, remove https://github.com/azavea/raster-foundry-deployment/wiki/Release-Workflow#bump-version-in-sbt-raster-foundryraster-foundry-only
It looks like the `version` value is used in POM metadata and when packaging JAR artifacts:
```bash
root > api/package
[info] Packaging /opt/raster-foundry/app-backend/api/target/scala-2.11/api_2.11-dev.jar ...
[info] Done packaging.
[success] Total time: 6 s, completed Mar 6, 2019 7:19:22 PM
```
```bash
root > api/publishLocal
[info] Writing Ivy file /opt/raster-foundry/app-backend/api/target/scala-2.11/resolution-cache/com.rasterfoundry/api_2.11/dev/resolved.xml.xml
[info] Wrote /opt/raster-foundry/app-backend/api/target/scala-2.11/api_2.11-dev. …
```

Remove version.sbt

---

CHANGELOG.md
app-backend/api/src/main/scala/project/ProjectLayerRoutes.scala
app-backend/api/src/main/scala/project/Routes.scala
app-backend/common/src/main/scala/datamodel/ProjectLayer.scala
app-backend/common/src/main/scala/datamodel/SplitOptions.scala
app-backend/db/src/main/scala/ProjectLayerDao.scala
app-backend/db/src/main/scala/ProjectLayerScenesDao.scala

Allow splitting project layers by date (day / week) and datasource to aid in creating time series comparisons
- ~Any new SQL strings have tests~ Created this issue: https://github.com/raster-foundry/raster-foundry/issues/4740
Http request made using httpie cli
```
> $ http POST :9091/api/projects/d103408d-c2d1-40fc-a5c8-6b7030671724/layers/bc5f360a-cdb8-4995-abfb-ef47e589dc33/split name='Week Split' colorGroupHex=#eeeeee rangeStart=2017-04-07T00:00:00.000Z rangeEnd=2017-04-20T00:00:00.000Z period=WEEK Authorization:'Bearer {{token}}'
HTTP/1.1 201 Created
X-Powered-By: Express
connection: close …
```

Add endpoint to support splitting layers by date and datasource

---

CHANGELOG.md
app-frontend/src/app/components/common/listItemWidgets/listItemSelector/index.html
app-frontend/src/app/components/pages/project/analyses/analyses/index.html
app-frontend/src/app/components/pages/project/analyses/analyses/index.js
app-frontend/src/app/components/pages/project/analyses/visualize/index.html
app-frontend/src/app/components/pages/project/analyses/visualize/index.js
app-frontend/src/app/components/pages/project/project/index.html
app-frontend/src/app/components/projects/analysisMapItem/index.html
app-frontend/src/app/components/projects/analysisMapItem/index.js
app-frontend/src/app/components/projects/index.js
app-frontend/src/app/components/projects/navbar/index.js
app-frontend/src/app/index.routes.js
app-frontend/src/app/services/analysis/analysis.service.js
app-frontend/src/assets/styles/sass/_shame.scss
app-frontend/src/assets/styles/sass/components/_project-item.scss
app-frontend/src/assets/styles/sass/pages/_dashboard.scss

This PR adds the map visualization part of the analysis data viz UI. It also creates a new analysis map item component containing the map, tiles, analysis info shown in the demo section.
We only support visualizing at most three analysis results per discussions during RRP
* On lab template UI, create some templates with `This template can be run with only one project` checked
* Go to a project's v2 UI
* Add some layers
* Define layer AOIs
* Add some scenes to these layers
* …

Add project analysis data visualization map UI

---

CHANGELOG.md
app-backend/common/src/main/scala/datamodel/ProjectLayer.scala
app-backend/common/src/main/scala/datamodel/SplitOptions.scala
app-backend/db/src/main/scala/ObjectPermissions.scala
app-backend/db/src/main/scala/ProjectDao.scala
app-backend/db/src/main/scala/ProjectLayerScenesDao.scala

This PR explicitly excludes PUBLIC objects from `owner=shared` only for scenes.
* share a project with a user and make it public
* log in as that user
* view projects shared with you
* you should see the project
* get an api token
* `export RF_API_TOKEN=<your api token>`
* `http :9091/api/scenes/ owner==shared Authorization:$RF_API_TOKEN | jq ".count"`
* it shouldn't be in the thousands
Closes #4751

Include shared public projects in "shared with me"

---

app-backend/build.sbt
app-backend/version.sbt

This PR moves the `version := "dev"` definition back to a `version.sbt` file in the context of `ThisBuild`.
See https://github.com/raster-foundry/raster-foundry/pull/4736 for the context of why this definition was moved to `build.sbt`.
What I believe was happening is we were defining the "fallback" version within a scope that takes precedent over `ThisBuild`. When `cipublish` was calling `gitSnapshots` to override the version, it was just being ignored.
**How I figured this out:**
I saw one build on `develop` pass, and it published artifacts named `-dev`. This made me think that the original PR was successful. All the builds after that failed, because they were also trying to publish artifacts named `-dev`.
Fixes https://github.com/azavea/raster-foundry-platform/issues/615
TBD.

Change scope of version = dev to fix failing builds on CI

---

CHANGELOG.md
app-backend/db/src/main/scala/ProjectLayerScenesDao.scala
app-frontend/src/app/components/projects/index.js
app-frontend/src/app/components/projects/layerSplitModal/index.html
app-frontend/src/app/components/projects/layerSplitModal/index.js
app-frontend/src/app/components/projects/projectLayerSecondaryNavbar/index.html
app-frontend/src/app/components/projects/projectLayerSecondaryNavbar/index.js
app-frontend/src/app/services/projects/project.service.js
app-frontend/src/assets/styles/sass/_shame.scss
app-frontend/src/assets/styles/sass/layout/_navbar.scss

This PR:
- updates the layer scene listing endpoint to use the `pageRequest`'s `sort` query parameter as well
- adds frontend support for splitting project layers
Layer options:
Layer splitting modal
Not sure why, but passing in a date to the `datePickerModal` does not seem to make the modal go to the passed in date...
* `api/assembly`
*  Spin up your server and create a project
* Add scenes from multiple days / weeks to one of the layers
* For testing, truncate your …

Add frontend support for splitting layers

---

CHANGELOG.md
app-frontend/src/app/components/common/listItemWidgets/listItemSelector/index.html
app-frontend/src/app/components/common/listItemWidgets/listItemSelector/index.js
app-frontend/src/app/components/histogram/dataVizHistogram/index.html
app-frontend/src/app/components/histogram/dataVizHistogram/index.js
app-frontend/src/app/components/histogram/dataVizStatistics/index.html
app-frontend/src/app/components/histogram/dataVizStatistics/index.js
app-frontend/src/app/components/histogram/histogramBar/index.html
app-frontend/src/app/components/histogram/histogramBar/index.js
app-frontend/src/app/components/histogram/index.js
app-frontend/src/app/components/pages/project/analyses/visualize/index.html
app-frontend/src/app/components/pages/project/analyses/visualize/index.js
app-frontend/src/app/index.components.js
app-frontend/src/app/services/common/graph.service.js
app-frontend/src/assets/styles/sass/_shame.scss
app-frontend/src/assets/styles/sass/base/_helpers.scss

Paired with @Lknechtli on this one. 
~Marked as WIP since it needs some styling and code clean-ups. More to come once all done.~
This PR:
- adds three components: `dataVizHistogram`, `dataVizStatistics`, `histogramBar`
- updates analysis data viz UI to include the histograms
* On lab template UI, create some templates with `This template can be run with only one project` checked
* Go to a project's v2 UI
* Add some layers
* Define layer AOIs **(important)**
* Add some scenes …

Add layer analyses histogram component and UI

---

CHANGELOG.md
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/OgcStore.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Main.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/implicits/OgcImplicits.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/services/WcsService.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/services/WmsService.scala
app-backend/project/Version.scala

This PR adds enough to get map tiles from wcs / wms layers. It leaves one thing on the table to do, which is to use existing histogram fetching and coloring logic to render tiles.
ction of the [changelog](https://github.com/raster-foundry/raster-foundry/blob/develop/CHANGELOG.md) and grouped with similar changes if possible
* add a project with layers as a wms and a wcs source in qgis
* pick one of the layers (ideally one with 4 bands, since histogram logic isn't in place to fetch from the db, so it's really slow for multi-spectral imagery)
* view it
* looooooooook
Closes #4748

Handle other OGC params

---

CHANGELOG.md
app-backend/api/src/main/scala/project/ProjectAnnotationRoutes.scala

Adds support to project annotation listing for using `mapToken` for authentication to support listing annotations on the publish/share page.
* Have a clean development environment (basically ensure that there are no map tokens on the `dfc52922-dfc3-4155-9828-d8dfe9fd0f11` project.
* Testing includes usage of `httpie` (plus [`http-jwt-auth`](https://github.com/teracyhq/httpie-jwt-auth)) and `jq` - so you'll need to install those.
* Get a valid JWT for your development environment and in a shell run: `export JWT_AUTH_TOKEN=<jwt>` 
* Go through the following steps to verify input/output is expected
```
echo '{"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"Point","coordinates":[-80.092243,42.10058]},"properties":{"label":"","description":""}}]}' | http …
```

Add maptoken support to project annotation listing

---

CHANGELOG.md
app-backend/api/src/main/scala/toolrun/Routes.scala
app-frontend/src/app/components/projects/layerSplitModal/index.js
app-frontend/src/app/components/projects/projectLayerSecondaryNavbar/index.js
app-frontend/src/app/pages/lab/analysis/analysis.html
app-frontend/src/app/pages/lab/analysis/analysis.js

This PR uses the `analysis/{id}/actions` endpoint to conditionally allow sharing of analyses from within the lab UI.
There were a bunch of formatting changes, so I've pointed out the functionally new pieces.
Previously, we waited to fetch the analysis permissions until after the page has loaded. For this PR, I moved this async op to the page resolves which saves us from dealing with the promise mechanics inside the controller.
This PR also fixes the split layer modal by adding a call to `this.dismiss()` when the `Create layers` button is pressed.
* For an analysis you own, view it in the lab and ensure you can see the permissions tab at the top of the lab interface as well as the share button on every node that isn't a constant
* For an analysis shared with you with at least edit …

Allow users with edit permissions to share analysis in lab

---

CHANGELOG.md
app-frontend/src/app/components/pages/project/layers/index.js
app-frontend/src/app/components/pages/project/project/index.js
app-frontend/src/app/services/projects/edit.service.js
app-frontend/src/app/services/projects/project.service.js

This PR preserves the state of visible project layers until the project component is destroyed.
This feature is implemented in commit `9380542`. Commit `0b69f2d` only contains reformatting changes using `prettier`.
* Go to V2 project layers list
* Update layer visibility for one or multiple layers by switching on or off the eye icon
* Go to project's nested components (like going to analysis list, going to a specific layer, etc), then go back to layers list. Make sure the …

Preserve state of visible layers

---

app-backend/api/src/main/scala/project/ProjectLayerAnnotationRoutes.scala
app-frontend/src/app/components/common/listItemWidgets/listItemActions/index.html
app-frontend/src/app/components/map/mapContainer/mapContainer.html
app-frontend/src/app/components/map/mapContainer/mapContainer.module.js
app-frontend/src/app/components/pages/share/layers/index.html
app-frontend/src/app/components/pages/share/layers/index.js
app-frontend/src/app/components/pages/share/project/index.html
app-frontend/src/app/components/pages/share/project/index.js
app-frontend/src/app/services/projects/project.service.js
app-frontend/src/app/services/projects/share.service.js
app-frontend/src/app/services/services.module.js
app-frontend/src/assets/styles/sass/components/_map-controls.scss

This PR adds a map control to the share page that allows the user to toggle annotations on and off for all visible layers.
This sets the page size at 100 for annotations. This may need some tuning but I don't have a good sense for what a good default is.
* Create/use a project that has multiple layers and multiple layers with annotations. Make sure the default layer has annotations. It helps if all of the annotations are around the same area.
* Go to the settings for the project and copy the share page URL (keep the project as private so a mapToken is appended to the URL since public projects aren't fully supported for the new share page yet, see #4770)
* Go to the share page and verify that the annotation toggle control is present and not 'on' by default
* Toggle the map annotation …

Allow toggling annotation display on share page

---

CHANGELOG.md
app-frontend/config/webpack/global.js

Switches to using the Raster Foundry swaggerhub
* Load the main page, click on "API Documentation"

Replace docs site with swaggerhub

---

CHANGELOG.md
app-tasks/rf/src/rf/utils/io.py

This PR adds `bucket-owner-full-control` to export uploads to s3 when the destination doesn't include the `DATA_BUCKET` environment variable.
There's some brittleness here -- if someone for some reason includes the `DATA_BUCKET` string in their output destination, they'll be unable to download exports to their bucket -- but that's pretty unlikely and we can tell them not to do that when the time comes.
Why not just always attach bucket-owner-full-control? Attaching bucket-owner-full-control to all of the objects in our buckets is effectively an infrastructure change, which means if we ever change the permissions on the buckets, we'll have to come back here and remember to change it. That seems bad and like we'll almost definitely forget. Leaving boto3 at the default ACL when we're …

Add object ACL when uploading to external buckets

---

CHANGELOG.md
app-backend/api/src/main/scala/project/AnnotationShapefileService.scala
app-backend/project/Dependencies.scala
app-backend/project/Version.scala

This PR updates `jts` dependency to keep it inline with what is used in `geotrellis 2.2.0` to make annotation shapefile import and export work again.
* `api/assembly`
* Spin up the server and frontend
* Go to a project and go under annotation tab
* Draw some annotations
* Click on `...` on top right of sidebar and select `Export`
* In dev tool, make sure `GET api/projects/<project ID>/annotations/shapefile` is successful
* Choose `Shapefile` from the `Export format` …

Fix annotation shapefile import and export

---

CHANGELOG.md
app-frontend/src/app/components/pages/project/analyses/analyses/index.html
app-frontend/src/app/components/pages/project/analyses/analyses/index.js
app-frontend/src/app/components/pages/project/layer/exports/index.html
app-frontend/src/app/components/pages/project/layer/scenes/scenes/index.html
app-frontend/src/app/components/pages/project/layers/index.html
app-frontend/src/app/components/pages/project/layers/index.js
app-frontend/src/assets/styles/sass/layout/_sidebar.scss

Allow zooming to project layers / analyses
Allow selecting multiple layers / analyses and zooming to them as a group
Allow showing / hiding stuff on the map as a selected group
- ~ny new SQL strings have tests~
~Depends on changes in https://github.com/raster-foundry/raster-foundry/pull/4804~ _merged_
~Only the last commit is relevant for this PR~
* Verify that you can select layers, show / hide them, and zoom to the group
* Verify that you can do the same to analyses
Closes #4703

Add more / better zooming actions to project layers and analyses

---

CHANGELOG.md
app-backend/migrations/src/main/scala/migrations/173.scala
app-backend/migrations/src/main/scala/migrations/Summary.scala
app-backend/migrations/src_migrations/main/scala/173.scala
docker-compose.yml

This PR updates the foreign key `layer_id`'s constraint in `uploads` table so that it sets the field to `NULL` when layers are deleted.
* Before running the migration, on V2 UI, upload an image to a layer, then delete this layer. The deletion should fail.
* Go to imported raster data list on frontend. Make sure there is a new import in progress reflected in the status bar.
* Run the migration.
* On V2 UI, delete the layer you uploaded an image to in step 1. Make sure the layer deletion succeeds.
* Go to imported raster data list on frontend. Make …

Set layerId to null when deleting upload records

---

CHANGELOG.md
app-frontend/src/app/components/pages/project/analyses/visualize/index.html
app-frontend/src/app/components/pages/project/analyses/visualize/index.js

Don't overwrite render def if quickedit manual render def flag is set
* Change the render def of a project analysis to something noticeably different, select it, and click visualize
* Verify that the color map is preserved and not overwritten
* Verify that if you create a new analysis from a project layer and don't preview it or change parameters, you can still visualize it (it should show as a solid color, since it has invalid parameters)
Closes #4835

Conditionally overwrite render def on visualize

---

CHANGELOG.md
app-lambda/setup.cfg
app-lambda/tox.ini

This PR updates setups in `app-lambda` so that `flake8` and `pytest` ignores styling checks and tests in dependency code.
- The instructions here are mocking what will happen during the lambda-related parts of `./script/test` and `./script/cipublish`
- Note: if you are testing in a VM, I would suggest deleting the `app-lambda` directory in the VM, and `vagrant rsync` to make sure `app-lambda` directory is up to date
- Build the lambda functions from the root of the directory
```bash
docker-compose -f "docker-compose.test.yml" \
run …
```

Make flake8 and pytest ignore deps in ./opt of app-lambda

---

CHANGELOG.md
app-frontend/src/app/components/pages/share/analyses/index.html
app-frontend/src/app/components/pages/share/analyses/index.js
app-frontend/src/app/components/pages/share/layers/index.html

Fix analysis listing on project share page
* Make a project public, then go to its v2 share page in an incognito browser
* Verify that you can now load the project analysis list
* Verify that if you put the browser in offline mode when navigating from the layer list view to the analyses list view, the only the error message shows, instead of both the error message and the "no analyses" message
* Do the above with the layer list view as well
* Go through other share page …

Fix analysis list on share page for public projects

---

CHANGELOG.md
app-backend/common/src/main/scala/datamodel/ProjectLayer.scala
app-backend/common/src/test/scala/com/azavea/rf/datamodel/implicits/Generators.scala
app-backend/db/src/main/scala/ProjectDao.scala
app-backend/db/src/main/scala/ProjectLayerDao.scala
app-backend/migrations/src/main/scala/migrations/174.scala
app-backend/migrations/src/main/scala/migrations/Summary.scala
app-backend/migrations/src_migrations/main/scala/174.scala

This PR adds `overviews_location` and `min_zoom_level` to `project_layers` table, updates `projectLayer` data model, and updates `ProjectLayerDao`, `ProjectDao`, and affected generators for property tests.
- Make sure both `mg update` and `mg apply` work
- Make sure property tests pass
- `api/assembly`, `backsplash-server/assembly` and then spin up server and frontend
- Make sure creating a new project still works and it creates a default project layer under the hood as usual
- Go to a project's V2 UI, make sure creating a new project …

Add overviewsLocation and minZoomLevel to projectLayers

---

CHANGELOG.md
scripts/console

Self-explanatory
- Run `./scripts/console sbt` and notice that the postgres and memcached containers start up

Make './scripts/console sbt' run with dependencies

---

CHANGELOG.md
app-backend/api/src/main/scala/project/ProjectAnnotationRoutes.scala
app-backend/api/src/main/scala/project/ProjectLayerAnnotationRoutes.scala
app-backend/api/src/main/scala/utils/QueryParameters.scala
app-backend/common/src/main/scala/datamodel/Annotation.scala
app-backend/common/src/main/scala/datamodel/QueryParameters.scala
app-backend/common/src/test/scala/com/azavea/rf/datamodel/implicits/Generators.scala
app-backend/db/src/main/scala/AnnotationDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/AnnotationDaoSpec.scala
docs/swagger/spec.yml

This PR:
- adds an optional `withOwnerInfo` query parameter to annotation query parameters
- enables listing project annotations and project layer annotations with more owner info `ownerName` and `ownerProfileImageUri` if `withOwnerInfo = true`
- adds property tests for the new sql
- Make sure that tests in `AnnotationDaoSpec` pass
- `api/assembly` and then spin up server and frontend
- In the UI, go to a project and create some annotations
- `GET` to `.../api/projects/<project id>/annotations?withOwnerInfo=true` should give you a paginated response of annotations, and for each annotation, it should …

Enable listing annotations with owner info

---

CHANGELOG.md
app-backend/common/src/main/scala/datamodel/ExportOptions.scala
app-backend/common/src/test/scala/com/azavea/rf/datamodel/implicits/Generators.scala
app-backend/db/src/main/scala/ExportDao.scala
app-backend/db/src/main/scala/UploadDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/ExportDaoSpec.scala

Creating export definitions still relied on the scenes to projects relationship and didn't fully support layer sources in analyses. This PR adds that support and adds tests that will help us catch future problems hopefully when the underlying database changes.
- In an existing project, create an export - note the the export ID in the server logs
- After rebuilding `batch` and `backsplash-export` run `./scripts/console batch "rf export <export-id>"`
- Create an export for a new analysis and select a layer or something, run an export job
Closes #4851

Fix Analysis Exports, Add Layer Support

---

app-frontend/src/app/components/projects/layerSplitModal/index.js

See title
- Split a layer with a single datasource and verify that the warning doesn't show up.
Closes https://github.com/raster-foundry/raster-foundry/issues/4858

Fix warning for in split modal for projects with a single datasource

---

CHANGELOG.md
app-backend/db/src/main/scala/ProjectLayerDatasourcesDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/ProjectLayerDatasourceDaoSpec.scala
app-frontend/src/app/components/projects/layerSplitModal/index.js

This PR:
- `SELECT DISTINCT ON (datasource.id)` when pulling datasources of scenes in a layer for layer datasource list endpoint
- updates the property test to test that the resulted datasource list is deduplicated for a layer
- adds an extra check on frontend to deduplicate datasources returned from the api for layer split modal
- Make sure `db/testOnly *ProjectLayerDatasourceDaoSpec` pass
- Reassemble the `jar`s
- Spin up server and frontend
- Go to a project layer with scenes from multiple datasources (V2 frontend), and bring up the layer split modal, check that the …

Deduplicate datasources returned from layer datasource endpoint

---

CHANGELOG.md
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/color/OgcStyles.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/implicits/OgcImplicits.scala

This PR adds a "Raster Foundry" style to OGC layers. It's whatever the database single band options for the project layer happen to be at the time you send a `GetCapabilities` request.
- find a nice project layer with a scene that visualizes well (not MODIS or Sentinel-2)
- add it as a WMS layer to QGIS
- look at the last style available -- it's called Raster Foundry
- look at it
- it should look pretty familiar
Helps with azavea/raster-foundry-platform#682

Add single band options from project layer to OgcStyles

---

CHANGELOG.md
app-backend/db/src/main/scala/MapTokenDao.scala

This PR takes out the filter for any  map tokens that happen to be owned by a user.
There's some other UI bug where we're for some reason firing off two create requests when we try to getOrCreate a map token, but it's in the v1 UI and wasn't immediately obvious, so abandoning.
This might also incidentally fix copying the share url for private projects, or at least locally I was able to visit the share page both with and without a map token (when private / public).
- reassemble your API server
- look at a project
- go to its publish page
- make it private if it's not
- copy its map token
- rejoice
- make it public, then make it private again
- it should still work to copy it
- look at your `GET` requests for map-tokens with the project id filter
- responses should have only the one map …

Don't list all map tokens a user owns

---

CHANGELOG.md
app-backend/migrations/src/main/scala/migrations/175.scala
app-backend/migrations/src/main/scala/migrations/Summary.scala
app-backend/migrations/src_migrations/main/scala/175.scala

This PR adds a migration to cascade the deletion of a project layer so that exports are deleted if any.
- Run migration
- Spin up server and frontend
- Go to a project's V2 UI
- Create a layer and add a scene to it
- Create an export of this image in this layer
- Go to project layer list and delete this layer. Make sure it succeeds.
Closes https://github.com/raster-foundry/raster-foundry/issues/4859

Cascade layer deletion so that exports are deleted

---

CHANGELOG.md
app-lambda/rflambda/fields.py
app-lambda/tests/test_footprints.py

Fix the import lambda splitting footprints that it shouldn't
Add test case for footprints that cross the prime meridian
This will not fix existing scenes, I'm going to work on a migration to fix them which will be run separately. Rather get this on staging and tested ASAP.
- Review code
- Run `./scripts/test` and verify that the lambda tests run / pass
Closes #4903

Prevent splitting polygons which cross the Meridian

---

CHANGELOG.md
app-backend/api/src/main/scala/project/Routes.scala
app-backend/api/src/main/scala/toolrun/Routes.scala
app-backend/db/src/main/scala/ToolRunDao.scala
app-frontend/src/app/components/pages/project/analyses/analyses/index.js
app-frontend/src/app/components/pages/project/settings/publishing/index.html
app-frontend/src/app/components/pages/project/settings/publishing/index.js
app-frontend/src/app/components/pages/share/analyses/index.js
app-frontend/src/app/components/projects/index.js
app-frontend/src/app/components/projects/mapUrlCard/index.html
app-frontend/src/app/components/projects/mapUrlCard/index.js
app-frontend/src/app/services/analysis/analysis.service.js
app-frontend/src/app/services/projects/project.service.js
app-frontend/src/assets/styles/sass/_shame.scss
app-frontend/src/assets/styles/sass/base/_helpers.scss
docs/swagger/spec.yml

Added analyses to the new project publish page and fixed a bunch of bugs with the url generation and copying.
Fix /tool-runs projectLayerId parameter
- Re-assemble your api jar in SBT
- Create a project
- Create three layers on the project
- Create a template which can be used with project layers
- Create 6 analyses on one layer, and 3 analyses on a second
- Verify that when you go to the publish page, each layer lists the number of linked analyses
- Select the layers by clicking anywhere on the list item
- Verify that the urls in the main view make sense, both in the …

Add analyses to v2 project publish page

---

CHANGELOG.md
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/BacksplashMosaic.scala
app-backend/build.sbt
app-backend/common/src/main/scala/datamodel/Metric.scala
app-backend/common/src/main/scala/datamodel/MetricEvent.scala
app-backend/common/src/main/scala/datamodel/MetricRequestType.scala
app-backend/common/src/main/scala/datamodel/QueryParameters.scala
app-backend/common/src/main/scala/datamodel/package.scala
app-backend/common/src/test/scala/com/azavea/rf/datamodel/implicits/Generators.scala
app-backend/db/src/main/scala/MetricDao.scala
app-backend/db/src/main/scala/filters/Filterables.scala
app-backend/db/src/main/scala/filters/Filters.scala
app-backend/db/src/main/scala/meta/CirceJsonbMeta.scala
app-backend/db/src/main/scala/meta/package.scala
app-backend/db/src/test/scala/com/azavea/rf/database/MetricDaoSpec.scala
app-backend/migrations/src/main/scala/migrations/176.scala
app-backend/migrations/src/main/scala/migrations/Summary.scala
app-backend/migrations/src_migrations/main/scala/176.scala
app-backend/project/Dependencies.scala

This PR adds a MetricDao and migration to add a metrics table. Metrics are currently insert only, though you can get one by id if you really want to.
There are a few things I learned in this process that hurt a lot:
1. you basically can't use the `?` or `?|` json operators from doobie, since it thinks you want to fill in parameters, but you don't
2. if you want to use json filters in doobie, you have to _first_ create the json filter (e.g. `'{"projectId":"$projId"}` and _then_ interpolate that into your fragment
3. postgres's string representation of intervals plays terribly with circe, doobie wants to map database json into an array or object, so starting with a `[` is a real disaster
4. `ParsingFailure` is a terrible name for an exception, and getting a `ParsingFailure` out of Postgres …

Add metrics dao and migration

---

CHANGELOG.md
app-backend/migrations/src/main/scala/migrations/177.scala
app-backend/migrations/src/main/scala/migrations/Summary.scala
app-backend/migrations/src_migrations/main/scala/177.scala

This migration fixes scenes which were corrupted before the lambda function in https://github.com/raster-foundry/raster-foundry/pull/4904 was fixed
- ~ Swagger specification updated~
Scene footprints after being fixed on staging
Migration was tested on staging and all fixed scene data_footprints were visually verified in qgis
- Run migration locally and verify that it succeeds without errors
Closes #4909

Add migration to fix split prime meridian scenes

---

CHANGELOG.md
app-backend/db/src/main/scala/AnnotationDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/AnnotationDaoSpec.scala
docs/swagger/spec.yml

This PR updates the single annotation `GET` endpoint so that it includes owner name and profile picture url.
- CI for `AnnotationDaoSpec` should pass
- Reassemble the api jar
- Spin up server and frontend
- Go to a project and create some annotations, grab project ID and one of annotations' ID
- `GET` to `/api/project/<project ID>/annotations/<annotation ID>` should give you owner name and profile url along with annotation info
Closes #4922

Add owner name and profile URL to the return of annotation GET endpoint

---

deployment/ansible/roles/raster-foundry.docker/files/daemon.json
deployment/ansible/roles/raster-foundry.docker/handlers/main.yml
deployment/ansible/roles/raster-foundry.docker/tasks/main.yml
deployment/ansible/roles/raster-foundry.nexus/tasks/main.yml

I already followed rough instructions outlined below to enable user namespace remapping on the Jenkins server:
https://docs.docker.com/engine/security/userns-remap/
This PR resolves permissions issues I encountered with the Nexus service afterwards (because Nexus expects to run as `200:200`).
Closes https://github.com/azavea/raster-foundry-platform/issues/678
I already applied these changes via an `ansible-playbook` run to the Jenkins server. See that the Nexus service is working fine and on the latest version:
http://nexus.staging.rasterfoundry.com
See that `develop` is passing:
http://jenkins.staging.rasterfoundry.com/job/Raster%20Foundry/job/raster-foundry/job/develop/

Add userns_mode to Nexus compose service

---

CHANGELOG.md
app-backend/common/src/test/scala/com/implicits/Generators.scala
app-backend/db/src/main/scala/MapTokenDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/MapTokenDaoSpec.scala

This PR introduces a test to make sure that when we list map tokens for a project we only get one back. It also makes changes necessary to get that to happen, now that I figured out what the problem is in real life.
- look at tests
- share a tool run with a map token
- list map tokens for a project in the frontend
- observe that you don't get extras from tool runs
Closes #4861, again

Don't include all tool run tokens with map tokens for a project

---

CHANGELOG.md
app-backend/akkautil/src/main/scala/Authentication.scala
app-backend/common/src/test/scala/com/implicits/Generators.scala
app-backend/db/src/main/scala/UserDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/UserDaoSpec.scala

This PR enables getting and writing user group roles from JWT claim.
- Get an access token from you know where with or without a role
- Send a request to any RF endpoint, e.g. `/api/projects`
- Make sure this user is added to the `users` table, and corresponding user group roles are added correctly to the `user_group_roles` table
Closes https://github.com/azavea/raster-foundry-platform/issues/700

Get and write group roles from JWT claim

---

CHANGELOG.md
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/Cache.scala

This PR prevents us from throwing string cache keys in the garbage in backsplash.
This is a pretty big oops on my part. I think I just forgot to implement the string cache key method when I updated the cache key builder for handling optional multipolygons.
- fire up your existing tile server
- make some requests
- observe the warning for `Failed to write to cache. Key = `
- reassemble
- kill and revive the tile server
- make requests again
- note that the warning is gone and that the cache is actually working
Closes #4937

Don't throw away string cache keys

---

app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/color/functions/SigmoidalContrast.scala
app-backend/backsplash-export/src/main/scala/com/rasterfoundry/backsplash/BacksplashExport.scala
app-backend/batch/src/main/scala/util/HadoopConfiguration.scala
app-backend/common/src/main/scala/com/rasterfoundry/common/color/SigmoidalContrast.scala

This PR removes a link that doesn't work from cipublish that was making Jenkins sad
- look at the most recent build failure
- confirm this is the right file

Remove scaladoc link

---

CHANGELOG.md
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/BacksplashMosaic.scala
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/MosaicImplicits.scala
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/color/ColorRampMosaic.scala
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/error/Error.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Error.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/implicits/ProjectStoreImplicits.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/services/SceneService.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/services/WmsService.scala

This PR makes MetadataExceptions less stringy by turning them into a class that other
more specific exceptions can inherit from.
I decided that it made more sense to return a 200 with an empty tile than to return a 404, since 404s
look bad in our monitoring dashboards, but requests outside the imagery extent are going to be
extremely common.
- reassemble backsplash-server
- clear your cache
- fire up your servers
- load a tile layer for a project that's in ok shape
- you should not get 500s

Stop returning 500s for tiles outside project extent

---

docs/swagger/spec.yml

This PR updates the spec with the proposed task related functionality.
This proposed spec is meant to be fairly future-proof so there are some features that aren't immediately applicable.
I will put explanations for various aspects of the proposed spec as comments in this PR which should be easier to digest than attempted references to things here.
**I'd suggest looking at the code by commit, as the first commit is limited to formatting changes.**
There are a lot of query parameters. Here are some examples of why these are necessary.
To get the tasks that a user has locked:
```json
lockedBy: '<userId>'
```
When requiring multiple labeling passes (3), get all unlocked tasks that still need to be labeled at least once more:
```json
actionStatus: 'LABELED',
actionMaxCount: 2,
locked: false …
```

Add proposed API spec for tasks

---

CHANGELOG.md
app-backend/api/src/main/resources/application.conf
app-backend/api/src/main/scala/scene/Routes.scala
app-backend/api/src/main/scala/utils/Config.scala
app-backend/db/src/main/scala/SceneDao.scala
app-frontend/src/app/components/scenes/sceneDownloadModal/sceneDownloadModal.html
app-frontend/src/app/components/scenes/sceneDownloadModal/sceneDownloadModal.module.js
app-frontend/src/app/services/scenes/scene.service.js

This PR adds backend and frontend supports to enable downloading sentinel-2 scene metadata files from a requester pays bucket.
- Assemble the api jar
- Spin up servers and frontend
- Add a sentinel scene to a project layer
- Bring up the scene download modal through clicking on the cloud button on scene sidebar item
- Under the metadata section, make sure all files listed can be downloaded (json and xml)
- Look at network traffic, there should be `GET` requests when you click on those download links
- Add a landsat scene to a project …

Fix Sentinel-2 metadata file download

---

CHANGELOG.md
app-backend/batch/src/main/scala/Main.scala
app-backend/batch/src/main/scala/cogMetadata/OverviewBackfill.scala
app-backend/build.sbt
app-backend/common/src/main/scala/AWSLambda.scala

This PR adds a job to the batch jar to kickoff project layer overview generation for existing project layers.
Stream concurrency was chosen sort of at random -- because of Lambda and basically constant scene posts I was a little afraid that we'd swamp the db if I went to like 50 so it's pretty conservative. I'll increase and schedule it if the test in staging takes way too long.
- reassemble your batch jar
- `java -cp /opt/raster-foundry/jars/batch-assembly.jar com.rasterfoundry.batch.Main backfill-layer-overviews`
- Check out the output from this batch job for testing it in staging: (forthcoming)
- Confirm that all staging layers with > 0 and <= 300 scenes have project layer overviews set

Backfill project layer overviews

---

CHANGELOG.md
deployment/ansible/group_vars/all.yml
deployment/ansible/group_vars/jenkins.yml
deployment/ansible/raster-foundry.yml
deployment/ansible/roles/raster-foundry.docker/files/daemon.json
deployment/ansible/roles/raster-foundry.docker/tasks/main.yml
deployment/ansible/roles/raster-foundry.docker/templates/daemon.json.j2

Configure the Docker daemon to support core file sizes of `unlimited` via `daemon.json` configuration overrides. Then, set the `sysctl` `kernel.core_pattern` to a path within `/tmp` on the Docker host.
~- [ ] Swagger specification updated~
This PR is omitting the ability to upload a core dump to S3. Locally, core dumps are centralized in `/tmp` on the Docker host. https://github.com/azavea/raster-foundry-deployment/pull/209 handles centralizing core dumps to S3 in non-local environments (AWS).
- Execute `setup` to ensure that the Ansible changes in …

Add ability to persist container service core dumps

---

CHANGELOG.md
app-backend/datamodel/src/main/scala/ActionType.scala
app-backend/datamodel/src/main/scala/ObjectType.scala
docs/swagger/spec.yml

This PR adds case objects to `ObjectType` to cover all API accessible entities. This includes the addition of members for:
- platform
- organization
- team
- user
- upload
- export
- feed
- maptoken
- license
- tooltag
- toolcategory
- aoi
This PR also adds a `CREATE` member to `ActionType`.
I was going to update the database enums for `object_type` and `action_type` but since we moved ACRs to a column on entities, they haven't been used. I've created https://github.com/raster-foundry/raster-foundry/issues/4994 to address this issue.
- CI

Add all entities as object types

---

CHANGELOG.md
app-backend/common/src/test/scala/com/UploadSpec.scala
app-backend/common/src/test/scala/com/implicits/Generators.scala
app-backend/datamodel/src/main/scala/Upload.scala
app-backend/db/src/main/resources/migrations/V3__Add_keepInSourceBucket_to_uploads.sql
app-backend/db/src/main/resources/migrations/V4__Add_keepInSourceBucket_to_uploads.sql
app-backend/db/src/main/scala/UploadDao.scala
app-tasks/rf/src/rf/models/upload.py
app-tasks/rf/src/rf/uploads/geotiff/factories.py
app-tasks/rf/src/rf/utils/io.py
docs/swagger/spec.yml
scripts/load_development_data

This PR adds a new field `keepInSourceBucket` to the `uploads` table with `false` value by default so that the processed uploaded scene will live in where the `DATA_BUCKET` env variable specifies. If set `true` on upload creation, the processed upload will live within the source bucket as the unprocessed file. (We already name the resulting scene's key as `<user id>/<scene id>/<cog.tif>`.)
- `./scripts/migrate migrate`
- Create two upload records in DB with `files` field containing tif in S3 that is not in the dev data bucket. Set one of them `keep_in_source_bucket` field to true
- Assemble the batch jar. `docker-compose build batch`
- In a batch shell, run `rf process-upload …

Support storing processed uploads in source bucket

---

app-backend/batch/src/main/scala/cogMetadata/OverviewBackfill.scala

This PR pulls the whole stream of project layers to add overviews to and adds better error-handling
so the whole traversal won't fail if one does. It's an effort to prevent failures due to socket read
timeouts that I encountered once it was actually time to backfill the layers. This PR and
`test/js/pull-whole-stream-of-layers` have the same code.
Update:
This "worked" in the sense that the processing didn't die from socket timeouts. It's possible that our staging projects are in general too degenerate to be much use as an indication of how robust the overview generation is, but a _huge_ percentage (92%) of the invocations failed. A lot of these were "the server doesn't support ranged byte reads," which I'm assuming is COGs we've cleaned up. A number of others were running out of memory.
- …

Pull all project layers to list in overview backfill

---

CHANGELOG.md
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/BacksplashImage.scala
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/Cache.scala
app-backend/build.sbt

This PR modifies the raster source cache config to include class constructor arguments. The move to `getRasterSource` with no arguments made it so that all raster sources were cached under the same key, with hilarious (from a certain dark perspective) results.
It also bumps the gdalwarp bindings dependency to a version that doesn't fail in a particular way.
- disable gdal
- view a layer
- view a different layer
- it should work
Closes #5000

Fix RasterSource caching

---

CHANGELOG.md
docs/swagger/spec.yml

This PR adds spec for user scopes CRUD.
Per offline discussions with @notthatbreezy and based on my understanding, we support endpoints to get, create, update, delete user scopes in a `Map(ObjectType, Array[ActionType])`.
Per limitations of swagger 2.0, to model Map or Dictionary properties, the choice we have seems to be using `additionalProperties `: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#model-with-mapdictionary-properties . 
- Not sure if CI runs spec check. If not, paste it in swagger editor and make sure it passes checks.
- Make …

Add spec for user scopes CRUD

---

CHANGELOG.md
app-backend/common/src/main/scala/AWSLambda.scala
app-backend/datamodel/src/main/scala/OverviewInput.scala
app-backend/lambda-overviews/src/main/scala/com/rasterfoundry/lambda/overviews/HttpClient.scala
app-backend/lambda-overviews/src/main/scala/com/rasterfoundry/lambda/overviews/OverviewGenerator.scala

This PR updates the `OverviewInput` case class to take a `minZoomLevel` instead of `pixelSizeMeters`, transforms the zoom level to pixel size in the overview generation function in lambda, and updates the project layer with this zoom level.
- Assemble servers and start them
- Open an `sbt` shell and run the following command to generate a jar for overview generation:
```
project lambdaOverviews
set assemblyOption in assembly := (assemblyOption in assembly).value.copy(includeScala = true)
assembly
```
- Get a refresh token from the UI, …

Use zoom level in OverviewInput for lambda function

---

CHANGELOG.md
app-backend/api/src/main/scala/uploads/Routes.scala
app-tasks/rf/src/rf/uploads/geotiff/factories.py
app-tasks/rf/src/rf/utils/cog.py

- Rebuild api server and batch containers
```
docker-compose build batch
./scripts/console sbt
api/assembly
```
- Create Project - note project id
```
echo '{"name":"NonSpatialDemo","description":"","visibility":"PRIVATE","tileVisibility":"PRIVATE","tags":[],"isAOIProject":false}' | http --auth-type=JWT :9091/api/projects
```
- Create Upload - note upload id, pass in project ID
```
echo '{"files":["s3://rasterfoundry-development-data-us-east-1/TgMEFKAG_400x400.jpg"],"datasource":"b4ca6661-27fa-497e-a85a-2a5632d5fe7c","fileType":"NON_SPATIAL","uploadStatus":"UPLOADING","visibility":"PRIVATE","metadata":{"acquisitionDate":"2019-05-20T20:49:26.348Z","cloudCover":0},"uploadType":"S3","source": …
```

Add Upload Processing for Non-Spatial Data

---

app-backend/build.sbt

Uses a patched version of the gdal warp bindings to enable automatically capturing core dumps when the tile service is stopped.

Bump GDAL warp bindings

---

CHANGELOG.md
app-backend/backsplash-server/src/main/resources/application.conf
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Config.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/services/HealthcheckService.scala
app-backend/build.sbt

Adds a healthcheck that loads some metadata about a tiff. If the tiff location has moved, the healthcheck throws a warning, but does not error out (in case the image is accidentally moved).
This screenshot is a demo of what the logs look like when the image has moved:
It is unclear if this is going to work as far as making sure that servers that pass healthchecks but can't serve tiles no longer do that. It is not possible to reproduce this in development so the only way to test I think is to push it out and test.
- Rebuild servers, start server, go to `localhost:8080/healthcheck`
Closes #4945

Add RasterSource Healthcheck

---

CHANGELOG.md
app-backend/api/src/main/scala/project/ProjectLayerTaskRoutes.scala
app-backend/api/src/main/scala/project/Routes.scala
app-backend/common/src/test/scala/com/implicits/Generators.scala
app-backend/datamodel/src/main/scala/Task.scala
app-backend/db/src/main/resources/migrations/V7__Add_ST_MakeGrid_Function.sql
app-backend/db/src/main/scala/TaskDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/PropTestHelpers.scala
app-backend/db/src/test/scala/com/azavea/rf/database/TaskDaoSpec.scala
docs/swagger/spec.yml

This PR adds an endpoint that generates a grid of tasks for a project layer based on a polygon mask and grid cell size (x and y).
A migration is included that adds a function `ST_MakeGrid`.
The scalacheck parameters (10000m cell size) were chosen to make the test probably take less than 10 seconds with an arbitrary multi-polygon. It's possible that it could take longer but I haven't seen that yet.
- Pick a project layer that has no tasks
- Create a geojson feature with `xSizeMeters` and `ySizeMeters` properties (geojson.io is handy for this) of at least 10000m initially, depending on your polygon size. It's possible to time out the endpoint if the cell size is too small and the polygon is too large.
- `POST /projects/{projectId}/layers/{layerId}/tasks/grid` with the geojson
- Should get …

Task grid endpoint

---

app-backend/db/src/main/scala/TaskDao.scala

This PR updates the list endpoint for tasks so that it uses left join instead (so it will return results if the `task_actions` table does not have matching records).
It is weird that the task endpoints are not on staging. Let's hope this build will add the endpoints in, so that they are accessible to annotate development work.
- `api/assembly`
- Spin up servers and grab a token
- Choose a project layer that has small scene …

Use left join to list tasks

---

CHANGELOG.md
app-frontend/config/webpack/global.js
app-frontend/src/app/components/map/labMap/labMap.module.js
app-frontend/src/app/components/map/mapContainer/mapContainer.module.js
app-frontend/src/app/components/map/staticMap/staticMap.module.js
app-frontend/src/app/components/pages/project/analyses/analyses/index.js
app-frontend/src/app/components/pages/project/analyses/visualize/index.js
app-frontend/src/app/components/pages/share/analyses/index.js
app-frontend/src/app/components/projects/projectItem/projectItem.module.js
app-frontend/src/app/components/scenes/sceneDetailModal/sceneDetailModal.module.js
app-frontend/src/app/pages/lab/analysis/analysis.js
app-frontend/src/app/pages/projects/edit/browse/browse.module.js
app-frontend/src/app/pages/projects/edit/edit.module.js
app-frontend/src/app/pages/share/share.controller.js
app-frontend/src/app/services/map/layer.service.js
app-frontend/src/app/services/projects/project.service.js

~WIP since I need to test the changes. I will work on it later tonight.~
This PR limits max zoom level for backsplash tiles to 23 on frontend.
- Test on frontend map UIs to zoom in to level 23 and higher -- make sure no request is sent when it is higher than 23
Closes #5005

Limit max zoom level for backsplash tiles to 23 on frontend

---

CHANGELOG.md
scripts/update

Removes usage of forklift migrations in `scripts/update`.
- Run `./scripts/update`
Closes #4654

Make scripts/update use flyway migrations

---

app-backend/db/src/main/scala/Dao.scala
app-backend/db/src/main/scala/TaskDao.scala

This PR fixes the count field returned by the task list endpoint so that it reflects the count in the DB.
- `api/assembly`
- Spin up servers and grab a token
- Choose a project layer that has small scene footprint so that task creation is fast
- `POST` to `api/projects/<project ID>/layers/<layer ID>/tasks/grid` with below json:
```json
{
"type": "Feature",
"properties": {
"xSizeMeters": 500,
"ySizeMeters": 500
},
"geometry": "<use_the_extent_field_of_this_project>"
}
```
- `GET` to `api/projects/<project ID>/layers/<layer ID>/tasks` should list tasks. Make sure that the value of the `count` field matches the …

Fix task list endpoint's returned count field

---

app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Main.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/services/HealthcheckService.scala
app-backend/build.sbt
app-backend/datamodel/src/main/scala/Task.scala
docker-compose.yml

It's difficult to tell the difference between service health degradation because we opted into it and service health degradation because something is actually wrong. The reason for this is that we can't actually see the healthcheck responses in anything that monitors service health. This PR adds a log when we voluntarily mark a backsplash service as sick due to its exceeding its request quota.
- ~Description of PR is in an appropriate section of the [changelog](https://github.com/raster-foundry/raster-foundry/blob/develop/CHANGELOG.md) and grouped with similar changes if possible~ internal facing
- set BACKSPLASH_SERVER_REQUEST_LIMIT to something small, like 50, and kill the jitter (set [this](https://github.com/raster-foundry/raster-foundry/pull/5031/files#diff-53eeaa79292eff98ee110b8ba5f …

Log exceeding tile server request quota

---

app-backend/Dockerfile
app-backend/Dockerfile.build
app-backend/api/Dockerfile
app-backend/api/src/main/scala/user/Routes.scala
app-backend/backsplash-server/Dockerfile
app-tasks/Dockerfile
docker-compose.yml

- Use JDK11 in contexts where we're running a JAR
- Update GDAL `2.3.2` references to `2.4`(we were using `2.4` images for `backsplash`)
- Modify `api/Dockerfile` to be Debian based as there are [no Alpine JDK11 images](https://github.com/docker-library/openjdk/issues/272)
- `US_ASCII` -> `US-ASCII` to resolve `java.io.UnsupportedEncodingException: US_ASCII`
It's worth mentioning that, as there aren't any OpenJDK-sanctioned Alpine images for JDK11, the sizes of the containers we build are going to increase. There are [Alpine images](https://github.com/adoptopenjdk/openjdk-docker) maintained by the AdoptOpenJDK group, although they state that they are not yet [TCK compliant](https://en.wikipedia.org/wiki/Technology_Compatibility_Kit).
It's also worth mentioning that they are no longer …

Use JDK11 in contexts where we're running a JAR

---

app-backend/db/src/main/scala/filters/Filters.scala

This PR fixes a typo in the `actionType` QP in the task list endpoint. It surfaced itself when developing collaborators table and activity graphs in Annotate. Going to 🤠 this one once CI is happen.
- We need those parentheses
- 🤠

Fix typo in actionType QP for task list endpoint

---

app-backend/db/src/main/scala/filters/Filters.scala

This bug showed itself when developing the activity graph component in annotate. Discussed with @alkamin  and will 🤠once CI is happy.
- 🤠

Fix actionType QP bug in task list endpoint

---

CHANGELOG.md
app-backend/api/src/main/scala/project/ProjectLayerTaskRoutes.scala
app-backend/db/src/main/resources/migrations/V8__Cascade_delete_task_action.sql
app-backend/db/src/main/scala/TaskDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/TaskDaoSpec.scala

This PR fixes the project layer task delete endpoint and adds a property test for it. It also adds a migration to cascade the deletion of task action records when tasks are deleted.
- CI
- Run migrations
- Point the`feature/asu/use-task-delete-endpoint` branch of Annotate frontend to this branch
- Create a project in annotate
- Label or validate some tasks
- Delete this project from Annotate
- It should work
Closes #5044

Fix project layer task delete endpoint

---

CHANGELOG.md
app-backend/api/src/main/scala/project/ProjectLayerTaskRoutes.scala
app-backend/api/src/main/scala/project/Routes.scala
app-backend/api/src/main/scala/utils/QueryParameters.scala
app-backend/datamodel/src/main/scala/QueryParameters.scala
app-backend/datamodel/src/main/scala/Task.scala
app-backend/db/src/main/scala/TaskDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/TaskDaoSpec.scala
docs/swagger/spec.yml

This PR adds an endpoint to list user activities on tasks for a project layer.
- Test this endpoint by using the frontend support in here: https://github.com/raster-foundry/annotate/pull/271
Closes https://github.com/raster-foundry/annotate/issues/253

Add an endpoint for listing user activity summary on tasks

---

CHANGELOG.md
docs/swagger/spec.yml

`project_id` is not part of what needs to be posted for correct deserialization,
so this PR removes it from the definition of `AnnotationGroupCreate`.
- check `Create` in `AnnotationGroup.scala`
- confirm it doesn't have a project id

Remove project_id from AnnotationGroupCreate

---

app-tasks/rf/src/rf/commands/ingest_scene.py

The metadata generation subprocess can fail if we don't have enough connections in the hikari pool.
This should prevent failures from resulting in a successful ingest job
- [~Swagger specification updated~
We still need to figure out what's causing the database issues.
This should cause the ingests to fail, and they can be tried again
- Deploy to staging and see if database errors which occur during metadata generation result in a failing status.
- Can probably test by kicking off a bunch of ingests at once, or limiting the staging database connections. Any idea how to do the latter?
Closes …

Use subprocess.check_call instead of Popen

---

CHANGELOG.md
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/PaintableTool.scala
app-backend/backsplash-export/src/main/scala/com/rasterfoundry/backsplash/ExportableInstances.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/services/MosaicService.scala
app-backend/project/Dependencies.scala

Upgrades version of geotrellis-server and fixes the organization id used for maml + upgrades it.
- Rebuild servers and interact with a project/layer + tool

Update version of gt-server and maml used

---

app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Main.scala
app-backend/db/src/main/scala/util/database.scala

This PR addresses two problems that were causing a proliferation of JVM threads. The first it addresses is that the Hikari configuration wasn't using fixed thread pools for transactions. In practice this meant that under heavy load (e.g. at zoom level 30), the number of transactions it needed to run exceeded the number of cached threads available, so it would increase them basically without bound until it got really angry. The second it addresses is that the implicit context shift in the `Main` for backsplash was a `def` instead of a `val`. What this meant is that we frequently created new context shfits. Testing instructions will provide evidence for both of these claims.
We still explode on overzoomed Landsat 8 imagery (and presumably overzoomed Sentinel-2? I don't know, I haven't …

Make tile server threadpool configuration more sane

---

CHANGELOG.md
nginx/etc/nginx/nginx.conf

Capture `X-Amzn-Trace-Id` in Nginx access logs to help connect request and response timings between the application load balancer and Nginx.
Resolves #5065 
- Run `./scripts/server`
- Make a request using a [mock trace identifier](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-request-tracing.html#request-tracing-syntax):
```bash
http GET 'http://localhost:8081/healthcheck' \
'X-Amzn-Trace-Id':'Self=1-67891234-12456789abcdef012345678;Root=1-67891233-abcdef012345678912345678;CalledFrom=app'
```
- See that the trace identifier is captured in the Nginx access logs:
```bash
nginx-backsplash_1        | 172.28.0.1 - - "GET /healthcheck HTTP/1.1" 200 60 0.59 "-" "HTTPie/1.0.2" "Self=1-67891234-12456789abcdef012345678;Root=1-67891233-abcdef012345678912345678;Call …
```

Capture X-Amzn-Trace-Id in Nginx access logs

---

app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/services/WmsService.scala

Tiles are currently being cropped to remove NoData areas. The result is that partially colored tiles can sometimes get stretched by clients (like QGIS) which expect returned images to range over the entire extent being requested. This is why the tiled view is susceptible to stretching and the regular view isn't (i.e. the regular view expects imagery for *just* the requested extent whereas the tiled view requests extents along a predefined grid that may/may not be backed by imagery).
This PR simply ensures that tiles are always padded out to the appropriate size for the given request. It is likely a bandage rather than an ideal solution, but it should suffice to move us beyond the artifacts currently being seen.
The correct imagery is on top. Note the stretching on the right side and on …

Pad tiles to avoid QGIS stretching

---

CHANGELOG.md
app-tasks/rf/src/rf/commands/ingest_scene.py
app-tasks/rf/src/rf/ingest/io.py
app-tasks/rf/src/rf/models/base.py
app-tasks/rf/src/rf/utils/cog.py
app-tasks/rf/src/rf/utils/io.py
scripts/load_development_data

Handle errors during scene ingests and roll back scene changes if the ingest fails.
Add a little bit of documentation in the python scripts
Run migrations when loading development data
The ingest might fail due to available database connections. Fixing that is a separate issue, and it's actually a good sign that this PR is handling the fail correctly if that returns a non-zero exit code
- Rebuild your batch jar
- Rebuild your batch container with `docker-compose build batch`
- start your API server
- Create a new project, add an uningested scene to it
- Open a shell on your batch container with …

Handle scene ingest errors

---

CHANGELOG.md
app-backend/datamodel/src/main/scala/Task.scala
app-backend/db/src/main/scala/TaskDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/PropTestHelpers.scala
app-backend/db/src/test/scala/com/azavea/rf/database/TaskDaoSpec.scala
docs/swagger/spec.yml

This PR rewrites functions behind the user task activity summary endpoint and adds more test cases.
- New property tests in CI should pass
- Reassemble jars
- Spin up servers
- Point annotate to this branch
- Create a project in annotate (it is suggested to update team IDs in local env before hand)
- Add user A and B to both label and validate teams
- Log in to annotate with user A. Label some tasks
- Log in to annotate with user B. Validate some tasks.
- Log in to annotate with an admin account
- Go to this project's dashboard. Dashboard's collaborators display should be broken, but will be fixed very soon. Open up network traffic and filter to `summary` endpoint. Make sure …

Rewrite user task activity summary endpoint and add more test cases

---

app-tasks/rf/src/rf/commands/ingest_scene.py

Set scene status to failed instead of reverting
Simple, merging and testing for quicker deploy

Set the scene status to failed when it fails instead of reverting

---

CHANGELOG.md
app-backend/api/src/main/scala/utils/QueryParameters.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/services/WmsService.scala
app-backend/datamodel/src/main/scala/Annotation.scala
app-backend/datamodel/src/main/scala/QueryParameters.scala
app-backend/datamodel/src/main/scala/Task.scala
app-backend/db/src/main/resources/migrations/V9__Add_taskId_to_annotations.sql
app-backend/db/src/main/scala/AnnotationDao.scala
app-backend/db/src/main/scala/TaskDao.scala
app-backend/db/src/main/scala/filters/Filterables.scala
app-backend/db/src/test/scala/com/azavea/rf/database/AnnotationDaoSpec.scala
app-backend/db/src/test/scala/com/azavea/rf/database/PropTestHelpers.scala
app-backend/db/src/test/scala/com/azavea/rf/database/TaskDaoSpec.scala
app-tasks/rf/src/rf/commands/ingest_scene.py
app-tasks/rf/src/rf/ingest/io.py
app-tasks/rf/src/rf/models/base.py
app-tasks/rf/src/rf/utils/cog.py
app-tasks/rf/src/rf/utils/io.py
docs/swagger/spec.yml
scripts/load_development_data

This PR adds `taskId` to annotations so that they can be explicitly linked to tasks. This also adds `taskId` as a query parameter.
There was a `task` QP in the spec that wasn't implemented so I updated it to reflect the new name of the QP.
- If you have tasks in your dev db, grab an id from one.
- If you don't have tasks in your dev db, drop the foreign key constraint: `alter table annotations drop constraint "annotations_task_id_fkey";`
- Create some annotations if you don't have any in your db
- Update annotations with the task id from a task
- Send some requests with the `taskId` param (test with non-existent IDs too) and see that it returns what you'd expect
Closes #5072

Add taskId to annotations

---

CHANGELOG.md
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/services/WmsService.scala
app-backend/db/src/main/scala/TaskDao.scala
app-backend/project/Dependencies.scala

Users of RF WMS will generally just use the default parent layer. This is problematic as things currently stand because most imagery that will be viewed via WMS is multiband and the current default behavior is to display the first band in greyscale. This PR adds a bit of logic to examine the bandcount and select the appropriate behavior. RGB (3 bands), RGBA (4 bands), and greyscale (any other number of bands, of which only the first will be displayed) should now be supported by default in `GetMap` requests.
- Select any 3 band or 4 band image sources in RF
- Access the default 'parent' layer via a WMS client
- Are the cones in your eyes excited or just the rods?
- Cones are the ones that see color
Closes #5075

Update gt-server for rgb(a) WMS

---

CHANGELOG.md
app-backend/api/src/main/scala/Main.scala
app-backend/build.sbt
app-backend/project/plugins.sbt

We were missing _any_ logs from the scala backend because `slf4j-nop` was being included in dependencies which seemed to be nooping any logging we had configured. This PR makes sure that `slf4j-nop` is excluded from our dependencies.
- Assemble Jars
- Start server and make sure that the backsplash banner prints and `Server Started` prints for the API server

Fix Missing Logs

---

.gitignore
app-backend/datamodel/src/main/scala/Annotation.scala
app-backend/db/src/main/scala/AnnotationDao.scala
app-backend/db/src/main/scala/StacExportDao.scala
app-backend/db/src/main/scala/TaskDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/AnnotationDaoSpec.scala
app-backend/db/src/test/scala/com/azavea/rf/database/PropTestHelpers.scala
app-backend/db/src/test/scala/com/azavea/rf/database/StacExportDaoSpec.scala
app-backend/db/src/test/scala/com/azavea/rf/database/TaskDaoSpec.scala

This PR:
- adds a method in `TaskDao` to select tasks filtered by a list of statuses from a project layer, so that their geometries can be combined to create the AOI of the the Label STAC **Item**
- adds two method in `AnnotationDao`:
* one for generating STAC compliant label **data** for detection project, by spatially filter annotations by tasks with specified statuses (legacy detection projects' annotations don't have `task_id` field populated)
* one for generating STAC compliant label **data** feature collection for single or multi-class classification project, by selecting annotations by task IDs with specified statuses and transforming the resulted classes to key-value pairs in the properties field in each GeoJSON Feature
- ~Swagger specification …

Update AnnotationDao and TaskDao for STAC export builder

---

CHANGELOG.md
app-backend/db/src/main/resources/migrations/V11__Add_rastersource_metadata.sql

Adds some metadata for scenes to track some information about scenes to help with tile serving
- Run migrations and test tile serving and scenes endpoint by browsing to the data page and one of the development projects

Add metadata fields for scenes

---

.github/PULL_REQUEST_TEMPLATE.md

We have missed adding indices to tables a few times when they are queries a lot. This updates the PR template to remove reference to the style guide (not maintained) and adds a checkbox for updating indices on new tables and queries if necessary.

Update PR template to include checking for needing indices

---

app-backend/batch/src/main/resources/application.conf
app-backend/batch/src/main/scala/stacExport/LabelCollectionBuilder.scala
app-backend/batch/src/main/scala/stacExport/LayerCollectionBuilder.scala
app-backend/batch/src/main/scala/stacExport/StacCatalogBuilder.scala
app-backend/batch/src/main/scala/stacExport/WriteStacCatalog.scala
app-backend/batch/src/main/scala/util/conf/Config.scala
app-backend/db/src/main/scala/TaskDao.scala

This PR enables writing STAC export to RF S3 data bucket that respects the internal structure of the catalog.
```
Exported Catalog:
|-> Layer collection
|   |-> Scene Collection
|   |   |-> Scene Item
|   |   |-> Scene Item
|   |   |-> (One or more scene items)
|   |-> Label Collection
|   |   |-> Label Item (Only one)
|   |   |-> Label Data in GeoJSON Feature Collection
|-> (One or more Layer Collections)
```
- ~Any new SQL strings …

Write STAC export to S3

---

CHANGELOG.md
docs/architecture/adr-0027-annotate-project-STAC-export.md

This PR adds an ADR for documenting decisions made on MVP features of exporting Raster Foundry/Annotate label data and scenes in STAC-compliant catalogs.
[Rendered](https://github.com/raster-foundry/raster-foundry/blob/feature/asy/adr-stac-export/docs/architecture/adr-0027-annotate-project-STAC-export.md)
Comments on the shared google doc has already been addressed.
- Make sure the ADR makes sense
Closes https://github.com/azavea/raster-foundry-platform/issues/800

ADR for label STAC export

---

CHANGELOG.md
app-backend/common/src/main/scala/com/rasterfoundry/common/color/ColorCorrect.scala

Use uByteConstantNoDataCellType for color corrected imagery instead of the original tile's celltype
- assemble backsplash-server
- Create a project and import two scenes which a) overlap and b) have a nodata value other than 0
https://github.com/azavea/raster-foundry-platform/issues/822 lists a project with two such scenes
- Verify that the project mosaics the two scenes without a gap or transparency where there should be data
- Verify that all the other development scenes mosaic / render correctly
Closes https://github.com/azavea/raster-foundry-platform/issues/822

Correctly mosaic tiles which have a no-data value other than 0

---

CHANGELOG.md
app-backend/api/src/main/scala/utils/QueryParameters.scala
app-backend/batch/src/main/scala/stacExport/WriteStacCatalog.scala
app-backend/datamodel/src/main/scala/QueryParameters.scala
app-backend/db/src/main/scala/ProjectDao.scala
app-backend/db/src/main/scala/filters/Filterables.scala
app-backend/db/src/test/scala/com/azavea/rf/database/StacExportDaoSpec.scala
docs/swagger/spec.yml

This PR:
- adds projectId and layerId QPs to STAC export list endpoint (support annotate frontend)
- updates STAC export location to use the S3 prefix instead of the absolute location of the `catalog.json` (support annotate frontend)
- updates values for `label:task`, `label:property`, and `label:classes` of the label item
- `./scripts/load_development_data --download` (this includes the `Florence - AL` project for local testing)
- `./scripts/console`:
* `api/assembly`
* `batch/assembly`
```json
{
"name": "AL Project Test 1", …
```

Add projectId and layerId QPs to STAC export list endpoint and more

---

app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/BacksplashImage.scala
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/MosaicImplicits.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/implicits/RenderableStoreImplicits.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/services/SceneService.scala
app-backend/batch/src/main/scala/Main.scala
app-backend/batch/src/main/scala/cogMetadata/RasterSourceMetadataBackfill.scala
app-backend/build.sbt
app-backend/common/src/main/scala/com/rasterfoundry/common/MosaicDefinition.scala
app-backend/common/src/main/scala/com/rasterfoundry/common/SceneToLayer.scala
app-backend/datamodel/src/main/scala/Scene.scala
app-backend/datamodel/src/main/scala/com/rasterfoundry/datamodel/RasterSourceMetadata.scala
app-backend/datamodel/src/main/scala/package.scala
app-backend/db/src/main/scala/RasterSourceMetadataDao.scala
app-backend/db/src/main/scala/SceneDao.scala
app-backend/db/src/main/scala/SceneToLayerDao.scala
app-backend/db/src/main/scala/meta/CirceJsonbMeta.scala
app-backend/db/src/main/scala/meta/package.scala

This PR was more important when we thought storing metadata on scenes was going
to be super important for improving WMS performance. This started with creating
a new `RasterSourceWithMetadata`; however, adding a new type of `RasterSource`
and verifying its correctness was a quite a bit of work and there are two reasons
why this PR stops short of implementing `RastersourceWithMetadata`:
1. [Two](https://github.com/raster-foundry/raster-foundry/issues/5142) [bugs](https://github.com/raster-foundry/raster-foundry/issues/5141) in the current WMS implementation made it really difficult to verify
the correctness of `RasterSourceWithMetadata` as far as memory consumption and rendering
different CRSes (implementing the `reproject` correctly in this new `RasterSource` was
especially difficult with …

Add Metadata Serialization for Scenes and Backfill Command

---

CHANGELOG.md
nginx/etc/nginx/includes/proxy-settings.conf

Requests to Backsplash, without tuning `proxy_connect_timeout`, get killed when the `proxy_read_timeout` threshold trips:
With `proxy_connect_timeout` tuned to `5s`:
I think this is a step in the right direction. However, the [timeouts](https://github.com/azavea/raster-foundry-deployment/blob/26efbcf83d6080ee0b1ff29fba3243eb71d338bc/core/terraform/backsplash.tf#L48) for the Backsplash target groups are `3s` (HTTP) and `5s` (HTTPS), so this shouldn't impact how quickly an ECS health check fails.
Connects https://github.com/azavea/raster-foundry-platform/issues/802
- Checkout `develop`
- Bring up a local instance of Raster Foundry:
```
export AWS_PROFILE=raster-foundry
export RF_SETTINGS_BUCKET=rasterfoundry-development-config-us-east-1
./scripts/bootstrap
./scripts/update …
```

Tune proxy_connect_timeout to make Nginx fail faster

---

CHANGELOG.md
app-backend/batch/src/main/scala/cogMetadata/HistogramBackfill.scala
app-tasks/rf/src/rf/models/scene.py

This PR fixes the python codecs for scenes. They were missing `metadataFields`.
- bring up your servers
- choose an uningested Sentinel-2 scene from your database. I chose `fe40bad5-d5dd-4720-a014-2fa7c35161d9`
- `./scripts/console batch 'rf ingest-scene fe40bad5-d5dd-4720-a014-2fa7c35161d9'`
- it should fail with the error that Rollbar reported (view logs from the links in Rollbar)
- `./scripts/console batch 'rf ingest-scene fe40bad5-d5dd-4720-a014-2fa7c35161d9'`
- it should complete successfully

Include metadataFields in python scenes model

---

CHANGELOG.md
app-backend/backsplash-export/src/main/scala/com/rasterfoundry/backsplash/TileReification.scala

Export definitions that request more bands for export than are available in the source imagery result in an obscure error being thrown during the export process. Ideally, we could prevent this from happening during the export generation process; however, since we can't at the moment this PR adds a check for band count mismatch during export and raises an easier to parse exception.
```
cbrown@trout:~/projects/raster-foundry$ ./scripts/console batch "java -jar /opt/raster-foundry/jars/backsplash-export-assembly.jar -d file:///opt/data/export-test.json"
[main] INFO  - Beginning tiff export to file:///dev/null.
[main] INFO  - Minimum Tile: 1136, 1519
[main] INFO  - Maximum Tile: 1137, 1519
[main] INFO  - Columns: 2, Rows: 1
[main] INFO  - Retrieved MAML AST at TMS (14, 1136, 1519): …
```

Check Band Count During Export

---

CHANGELOG.md
app-backend/batch/src/main/scala/stacExport/LabelCollectionBuilder.scala
app-backend/batch/src/main/scala/stacExport/LayerCollectionBuilder.scala
app-backend/batch/src/main/scala/stacExport/SceneCollectionBuilder.scala
app-backend/batch/src/main/scala/stacExport/StacCatalogBuilder.scala
app-backend/batch/src/main/scala/stacExport/WriteStacCatalog.scala

Convert absolute links to relative links where possible
run `aws s3 --profile raster-foundry sync s3://rasterfoundry-development-data-us-east-1/stac-exports/96ef477f-f835-4aa6-826c-b1060fac88fc/ ./stac-exports/` to see exported stac 
- `./scripts/load_development_data --download`
- `./scripts/console`:
* `api/assembly`
* `batch/assembly`
```json
{
"name": "Test Stac Export",
"layerDefinitions": [
{
"projectId": "7e584c31-f5d1-4a02-9428-e83006642375",
"layerId": "1a8c1632-fa91-4a62-b33e-3a87c2ebdf16"
}
], …
```

use relative links for non-self links

---

CHANGELOG.md
app-backend/batch/src/main/scala/stacExport/SceneCollectionBuilder.scala
app-backend/batch/src/main/scala/stacExport/WriteStacCatalog.scala
app-backend/datamodel/src/main/scala/MLProjectType.scala
app-backend/db/src/main/scala/AnnotationDao.scala
app-backend/db/src/main/scala/ProjectDao.scala

This PR fixes:
- chip classification project label data export
- scene item `datetime` field value for both project types
- `api/assembly`
- spin up servers
- bring up annotate and point it to this branch
- log in annotate as the dev user
- create a chip classification project
- label some tasks
- go to the `Exports` tab and create an export of the labeled tasks
- go to Florence Alabama project and create an export of the validated tasks
- `java -cp /opt/raster-foundry/jars/batch-assembly.jar …

Fix chip classification STAC data export and scene item datetime field for both project types

---

CHANGELOG.md
app-backend/batch/src/main/scala/stacExport/SceneCollectionBuilder.scala
app-backend/batch/src/main/scala/stacExport/WriteStacCatalog.scala

This PR makes it so that items in scene collections don't have the collection id prepended to their relative paths. It's an attempt to address an error encountered in #5147 (see [comment](https://github.com/raster-foundry/raster-foundry/issues/5147#issuecomment-530311524))
will link to logs once I get the test branch up
- from the repo root `mkdir -p data/stac`
- download the STAC export I just created: `aws --profile raster-foundry s3 cp --recursive s3://rasterfoundry-staging-data-us-east-1/stac-exports/a7142852-08bd-47e9-8f6f-74f21b7deceb ./data/stac/`
- fire up a docker container with python (good chance this'll be in your docker cache already) and install `stac_validator`
```bash
$ docker run --rm -it -v (pwd)/data:/opt/data --entrypoint bash python:3.7
$ pip install stac_validator …
```

Fix scene item relative links in scene collection

---

CHANGELOG.md
app-backend/api/src/main/scala/project/ProjectLayerTaskRoutes.scala
app-backend/api/src/main/scala/utils/QueryParameters.scala
app-backend/datamodel/src/main/scala/QueryParameters.scala
app-backend/datamodel/src/main/scala/Task.scala
app-backend/db/src/main/scala/TaskDao.scala
docs/swagger/spec.yml

This PR adds a `format` query parameter to the task list endpoint to list tasks union by status, in order to support speeding up the load of the task map in annotate.
It also adds a user name fallback in the task user summary endpoint so that collaborators table's user names are populated.
- Assemble the api jar
- Spin up frontend and get a token, Florence project's ID and default layer ID
- `GET` to `api/projects/<project ID>/layers/<layer ID>/tasks?format=summary` should return a `FeatureCollection` of all available tasks with geometries unioned by statuses
- `GET` to `api/projects/<project ID>/layers/<layer …

Add a query parameter to list tasks union by status

---

CHANGELOG.md
app-frontend/src/app/components/scenes/sceneDetailModal/sceneDetailModal.html

Expose scene id in the scene detail modal
Users shouldn't have to open the network tab of their dev tools to find a scene id.
- View a scene detail modal and verify that the id is visible

Add scene id to scene detail modal

---

CHANGELOG.md
app-backend/api/src/main/scala/scene/Routes.scala
app-backend/batch/src/main/scala/cogMetadata/HistogramBackfill.scala
app-backend/common/src/main/scala/utils/CogUtils.scala
docker-compose.yml

CogUtils histogram generation is old and flawed, replace it with RasterSource histograms
- Create a new scene with the `PSScene4Band-20180205_171853_103d-analytic_sr.tif` image in your `data` folder. Verify that the scene renders
- Use scenes from https://app.staging.rasterfoundry.com/projects/edit/4a298fe2-ac20-4377-90eb-fc6a7e3a9584/scenes?page=1 and verify that they are now colored correctly (use the staging systems user to get the urls, these are client scenes)
- Use a couple other cogs that have acted up in the past and verify that they generate histograms correctly
Closes #5166

Use RasterSource to generate better histograms for cogs

---

CHANGELOG.md
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/color/ColorRampMosaic.scala

Remove coercion to 0 nodata value
Before:
After
- Switch a bunch of projects that have a non-zero nodata value for the underlying data to single band mode and verify that they show up correctly.
Closes #5132
Depends on #5169

Fix single band color ramp nodata values

---

CHANGELOG.md
Jenkinsfile
Jenkinsfile.release
scripts/cipublish

This PR removes all remnants of API spec publishing to S3.
Connects https://github.com/azavea/raster-foundry-platform/issues/814
See this Slack conversation where it was determined we are no longer relying on spec.rasterfoundry.com: https://azavea.slack.com/archives/C089LBS6S/p1568744948022300

Remove API spec publishing

---

CHANGELOG.md
app-frontend/src/app/services/scenes/cmrRepository.service.js

This PR makes MODIS Aqua UUID a valid UUID and also the ID of the MODIS Aqua datasource in the database.
:sunglasses:
- confirm you can create an upload with the MODIS Aqua datasource from the frontend
- or just watch the gif
- or check that the uuid is a valid uuid in the only change
- your call

Fix the datasource id for MODIS aqua

---

CHANGELOG.md
app-backend/api/Dockerfile
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/services/HealthcheckService.scala
app-backend/common/src/main/scala/com/rasterfoundry/common/BacksplashConnectionFactory.scala
app-backend/db/src/main/scala/util/database.scala
app-backend/project/Dependencies.scala
docker-compose.yml

This fixes a problem where the healthcheck failures did not allow for
distinguising between a timeout and an actual error (like not being
able to connect to the database).
There wasn't a _great_ way to propagate the cause of failures to the healthcheck - so now we return a 500 and exception.
In cases where there is a timeout we get a nice error message with the nature of the timeout.
This is what it looks like when it times out:
```
cbrown@trout:~/projects/raster-foundry-deployment$ time http :8081/healthcheck
HTTP/1.1 503 Service Unavailable
Connection: keep-alive
Content-Length: 36Content-Type: application/json
Date: Wed, 18 Sep 2019 18:29:49 GMTServer: nginx
Strict-Transport-Security: max-age=15552000; preload
X-Content-Type-Options: nosniff
{
"errors": [
"cache"
],
"result": "sick"
} …
```

Upgrade `sup` and identify timeouts vs errors

---

CHANGELOG.md
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/BacksplashImage.scala
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/MosaicImplicits.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Config.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/implicits/RenderableStoreImplicits.scala
app-backend/common/src/main/resources/reference.conf
app-backend/common/src/main/scala/com/rasterfoundry/common/MosaicDefinition.scala
app-backend/common/src/main/scala/com/rasterfoundry/common/SceneToLayer.scala
app-backend/common/src/main/scala/utils/CogUtils.scala
app-backend/db/src/main/scala/Config.scala
app-backend/db/src/main/scala/SceneDao.scala
app-backend/db/src/main/scala/SceneToLayerDao.scala
app-tasks/rf/src/rf/uploads/landsat_historical/factories.py
docker-compose.yml

This PR enables multitiff imagery rendering for more datasources.
It however doesn't work1 Landsat 4/5/7 it turns out aren't stored as COGs, so they'll always require some processing. MODIS also isn't stored as a COG.
However! This doesn't need to be catastrophic. We can change what upload processing / ingest means for Sentinel-2 / the other datasources so that we don't have to do quite as much work and we'll still get better import performance.
For Sentinel-2 this means gdal_translate to make the internal tiling scheme have smaller tiles. For the others, this means adding overviews at all. They already have internal tiling, but that's not enough --
```bash
$ gdalinfo /vsicurl/https://storage.googleapis.com/gcp-public-data-landsat/LT05/01/004/027/LT05_L1TP_004027_19850918_20170218_01_T1/LT …
```

Add MultiTiff image rendering for more datasources

---

CHANGELOG.md
app-backend/api/src/main/scala/Main.scala
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/MosaicImplicits.scala
app-backend/backsplash-server/src/main/resources/application.conf
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Config.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Main.scala
app-backend/batch/src/main/scala/stacImport/ReadStacFeature.scala
app-backend/db/src/main/scala/util/database.scala
app-backend/db/src/test/scala/com/azavea/rf/database/DBTestConfig.scala
app-backend/http4s-util/src/main/scala/com/rasterfoundry/http4s/xray/UdpClient.scala
app-backend/http4s-util/src/main/scala/com/rasterfoundry/http4s/xray/XRayTracingContext.scala

In debugging some issues with a hanging application under load and doing additional load tests I adjusted some of execution contexts/context shifts in the application. Mostly with an aim to do the following:
- Use defaults where possible since it's unclear if our changes were having a net-positive effect
- Fix up any errors being seen during the load tests -- mostly this happened around doobie transactions and the UdpClient failing to initialize under load
- Follow guidelines and best practices around execution contexts for Doobie execution contexts
Additional notes in https://github.com/azavea/raster-foundry-platform/issues/849 provide some context
I don't have a good sense for what testing here should involve, so exercising the servers I think seems appropriate.
- Reassemble Servers
- …

Use Default Execution Contexts, Adjust Doobie Execution Contexts

---

app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/BacksplashImage.scala
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/BacksplashMosaic.scala
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/MosaicImplicits.scala
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/package.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/MamlAdapter.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/implicits/OgcImplicits.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/implicits/RenderableStoreImplicits.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/services/MosaicService.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/services/SceneService.scala

In the first pass of adding tracing to backsplash tracing contexts were added to `BacksplashImage` - in a few cases this wasn't ideal as the nesting for mosaics weren't 100 percent and also we couldn't add tracing to a few areas of the response cycle. This PR removes tracing context from images and adds it to mosaic. Most methods on images already took a tracing context as an argument, the difference now is that we can use child contexts from the mosaic tracing context to better group traces.
Still mostly focused on project layer mosaics since that's where most requests come in.
- Get a JWT token and export it to your environment: `export JWT_TOKEN=<>`
- Assemble backsplash, start it up
- Make a request for a tile that has multiple underlying scenes:
`http …

Add TracingContext to BacksplashMosaic

---

app-backend/api/src/main/scala/scene/Routes.scala
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/BacksplashMosaic.scala
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/HistogramStore.scala
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/MosaicImplicits.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/implicits/HistogramStoreImplicits.scala
app-backend/datamodel/src/main/scala/Datasource.scala
app-backend/datamodel/src/main/scala/Scene.scala
app-backend/db/src/main/scala/DatasourceDao.scala
app-backend/db/src/main/scala/SceneDao.scala
app-backend/db/src/main/scala/util/Cache.scala
app-backend/http4s-util/src/main/scala/com/rasterfoundry/http4s/TracedHTTPRoutes.scala

Adds datasource, scene caching for selects by ID. Also adds the referrer to traces as an explicit annotation.
Missing from Cache:
```
13:42:45.689 [FutureNotifyListener] DEBUG com.rasterfoundry.database.util.Cache$ - Cache Miss for Key: Scene:533fdfa0-0f76-49d8-8114-e9326d6c91ad:Datasource
```
Next Request:
```
13:45:24.247 [FutureNotifyListener] DEBUG com.rasterfoundry.database.util.Cache$ - Cache Hit for Key: Scene:533fdfa0-0f76-49d8-8114-e9326d6c91ad:Datasource
```
Referer:
This actually became less important after we reduced the number of queries since we are reusing the `AuthObject` results for scenes and not requesting scenes multiple times by ID.
- Re-assemble servers
- Get JWT token and export it in environment: `export JWT_AUTH_TOKEN=<token>`
- Request thumbnail twice - see cache …

Add Datasource + Scene Caching

---

app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/MosaicImplicits.scala
app-backend/backsplash-server/src/main/resources/logback.xml
app-backend/db/src/main/scala/util/database.scala
docker-compose.yml

A few things happening here:
- setting `autocommit` to false in `hikari` aligns that setting with `doobie`
- adds leak detection to `hikari` for 30 seconds
- enables debug logging for hikari
- changes `parTraverse`'s to `traverse` since that was a little heavy
- Assemble and browse the application

Various Changes Related to Troubleshooting

---

CHANGELOG.md
app-backend/http4s-util/src/main/scala/com/rasterfoundry/http4s/TracedHTTPRoutes.scala

This PR includes instance metadata in traces from backsplash.
Check out this [trace](https://console.aws.amazon.com/xray/home?region=us-east-1#/traces/1-5d93c1db-1f69c9fa25c206c809ac9361)
- while `test/js/include-instance-metadata-in-traces` is in staging, make some requests
- check out the annotations for your requests and make sure they include a TaskARN
Closes #5176

Add task metadata to tracing tags

---

CHANGELOG.md
app-backend/batch/src/main/scala/stacExport/LabelCollectionBuilder.scala
app-backend/batch/src/main/scala/stacExport/LayerCollectionBuilder.scala
app-backend/batch/src/main/scala/stacExport/SceneCollectionBuilder.scala
app-backend/batch/src/main/scala/stacExport/StacCatalogBuilder.scala
app-backend/batch/src/main/scala/stacExport/StacExtent.scala
app-backend/batch/src/main/scala/stacExport/StacItemBuilder.scala
app-backend/batch/src/main/scala/stacExport/WriteStacCatalog.scala
app-backend/build.sbt
app-backend/project/Dependencies.scala

This PR:
- updates gt-server version
- updates the shape of the field `extent` in STAC Collections to match [the spec](https://github.com/radiantearth/stac-spec/blob/v0.8.0-rc1/collection-spec/collection-spec.md#extent-object)
- adds `stac_version` field for STAC items
- adds `stac_extensions` for the label items in the export
- adds `label:asset` field for `StacLink`, and populates this field with keys in the map of assets in label items.
```json
{
"name": "florence al test 1", …
```

Upgrade STAC version in export builder

---

app-backend/batch/src/main/scala/stacExport/LabelCollectionBuilder.scala
app-backend/batch/src/main/scala/stacExport/LayerCollectionBuilder.scala
app-backend/batch/src/main/scala/stacExport/SceneCollectionBuilder.scala
app-backend/batch/src/main/scala/stacExport/StacCatalogBuilder.scala
app-backend/batch/src/main/scala/stacExport/StacItemBuilder.scala
app-backend/batch/src/main/scala/stacExport/WriteStacCatalog.scala

This PR:
I will change the base of this PR to develop once its base is merged. 
```json
{
"name": "florence al test 1",
"layerDefinitions": [
{
"projectId": "7e584c31-f5d1-4a02-9428-e83006642375",
"layerId": "1a8c1632-fa91-4a62-b33e-3a87c2ebdf16"
}
],
"taskStatuses": ["LABELED", "VALIDATED"]
}
```
- Grab the above export record's ID
- `java -cp /opt/raster-foundry/jars/batch-assembly.jar com.rasterfoundry.batch.Main …

Refine STAC export builder

---

CHANGELOG.md
app-backend/build.sbt
app-backend/http4s-util/src/main/scala/com/rasterfoundry/http4s/TracedHTTPRoutes.scala
app-backend/project/plugins.sbt

This PR makes sure that `http4sUtil` also gets published. Oops.
- ci

Include http4sUtil in aggregate so it gets sent to sonatype

---

CHANGELOG.md
app-backend/api/src/main/scala/stac/Routes.scala
app-backend/batch/src/main/scala/stacExport/WriteStacCatalog.scala
app-backend/build.sbt
app-backend/datamodel/src/main/scala/StacExport.scala
docs/swagger/spec.yml

Allow the user to download the entire catalog zipfile in an http link
[catalog.zip](https://github.com/raster-foundry/raster-foundry/files/3718225/catalog.zip)
```json
{
"name": "florence al test 1",
"layerDefinitions": [
{
"projectId": "7e584c31-f5d1-4a02-9428-e83006642375",
"layerId": "1a8c1632-fa91-4a62-b33e-3a87c2ebdf16"
}
],
"taskStatuses": ["LABELED", "VALIDATED"]
}
```
- Grab the above export record's ID
- `java -cp …

Add signed zip download link to stac exports

---

CHANGELOG.md
app-backend/batch/src/main/scala/stacExport/LabelCollectionBuilder.scala
app-backend/batch/src/main/scala/stacExport/SceneCollectionBuilder.scala

This PR uses ids for STAC item file names instead of `item.json`.
- assemble batch jar
- Create and run a STAC export following instructions in #5202 (or rerun an existing STAC export)
- sync its file location
- confirm that nothing is called `item.json` anymore: `find -name item.json` should return nothing from where you synced the export locally
- confirm that nothing links to `item.json` anymore `rg item.json` should return nothing from where you synced the export locally (if you don't have `rg` / ripgrep, use `ag` or whatever other searcher you use) 
Closes #5214

Use ids for item URIs

---

CHANGELOG.md
app-backend/batch/src/main/scala/stacExport/LabelCollectionBuilder.scala
app-backend/batch/src/main/scala/stacExport/SceneCollectionBuilder.scala
app-backend/batch/src/main/scala/stacExport/WriteStacCatalog.scala
app-backend/db/src/main/scala/TaskDao.scala

This PR makes it so that we don't print `null` for `label:overview` or other properties on label items, so we don't URL encode scene ingest locations, and so we can run STAC exports without specifying task statuses.
Nevermind all this -- just not printing any `null`s is fine
~This wound up being messier than we expected. It's not obvious to me that we want _never_ to print `null` anywhere, but we also only invoke the printer once, at the end of the universe: https://github.com/raster-foundry/raster-foundry/blob/develop/app-backend/batch/src/main/scala/stacExport/WriteStacCatalog.scala#L75. This means it's difficult to use a custom `Printer` for just this one case: https://github.com/circe/circe/blob/master/modules/core/shared/src/main/scala/io/circe/Printer.scala#L32. Separately, [as of …

STAC bug fixes

---

app-backend/batch/src/main/scala/stacExport/LabelCollectionBuilder.scala
app-backend/batch/src/main/scala/stacExport/SceneCollectionBuilder.scala
app-backend/batch/src/main/scala/stacExport/WriteStacCatalog.scala
app-backend/project/Dependencies.scala

Updates `geotrellis-server` to get multi-scene histogram fix and also adds collection link to exported STAC items.
~- [ ] Swagger specification updated~
~- [ ] New tables and queries have appropriate indices added~
```
{
"id": "0b176a97-49eb-44e7-a775-c0405e873c59",
"stac_version": "0.8.0-rc1",
"links": [
{
"href": "s3://rasterfoundry-development-data-us-east-1/stac-exports/aa9b5613-dc55-4512-87ca-0f4fa2277672/1a8c1632-fa91-4a62-b33e-3a87c2ebdf16/2de43c83-ccb9-4279-963b-1290a2014b63/0b176a97-49eb-44e7-a775-c0405e873c59/0b176a97-49eb-44e7-a775-c0405e873c59.json",
"rel": "self",
"type": "application/json",
"title": "Label item 0b176a97-49eb-44e7-a775-c0405e873c59", …
```

Add Collection Links and Fix Histograms in Multi Scene Analyses

---

CHANGELOG.md
app-backend/db/src/main/scala/TaskDao.scala

Fixes a bug where the task summary method on the Dao was generating incorrect SQL
- Re-assemble everything, get a JWT and export it to `JWT_AUTH_TOKEN`, start servers
- Request: `http --auth-type=JWT ":9091/api/projects/7e584c31-f5d1-4a02-9428-e83006642375/layers/1a8c1632-fa91-4a62-b33e-3a87c2ebdf16/tasks?format=summary&status=LABELED"`
- See that it works

Use fragment combinators for filters in task summary

---

CHANGELOG.md
app-backend/batch/src/main/scala/cogMetadata/RasterSourceMetadataBackfill.scala
app-backend/common/src/main/scala/com/rasterfoundry/common/color/ColorCorrect.scala

Log counts for failing / successful metadata back-fills instead of failing
- build your batch jar `./sbt batch/assembly`
- build your batch container `docker-compose build batch`
- in psql, change a few scene ingest locations to invalid locations:
```
update scenes set ingest_location = 's3:///rasterfoundry-production-data-us-east-1/invalid_upload_location.tif' where id in (select id from scenes where scene_type = 'COG' and ingest_location is not null and crs is null limit 10);
```
- run the rastersource-metadata-backfill job in your batch container: `./scripts/console batch "java -cp …

Fix scene metadata backfills

---

CHANGELOG.md
app-backend/batch/src/main/scala/stacExport/WriteStacCatalog.scala

This PR makes the extension of label item asset on write the same as [the extension in the asset link](https://github.com/raster-foundry/raster-foundry/blob/85b119663d0a86fbf230dd39ae8294071eb3040c/app-backend/batch/src/main/scala/stacExport/Utils.scala#L157) for the label item. I'm sure you can imagine why that would be important.
Discovered because `pystac` was mad at me about the path. Thanks, pystac!
- make sure they match

Fix file extension

---

CHANGELOG.md
app-backend/db/src/main/scala/AnnotationDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/AnnotationDaoSpec.scala

Clip annotations to the task boundaries
RF annotations:
Stac export geojson results:
- build your Api / batch jars
- point your annotate frontend at your local server by changing `.env.local` to look like this:
```
ENABLE_GTM_HISTORY="false"
REACT_APP_AUTH_DOMAIN=raster-foundry-dev.auth0.com
REACT_APP_AUTH_CLIENT_ID=544Cz1V8tqezMCbyN8mNJmlzOpd8H4ex
REACT_APP_AUTH_AUDIENCE=http://localhost:9091/api/
REACT_APP_API_URL=http://localhost:9091/api
REACT_APP_TILE_URL=http://localhost:8081
REACT_APP_LABEL_TEAM_ID=40bdf3a9-7da0-4b4d-9cfa-918430f67357
REACT_APP_VALIDATION_TEAM_ID=e36f5155-cd86-43d1-9942-a8eaeba11ca6
```
Team IDs may …

Add semantic segmentation project stac exports

---

CHANGELOG.md
app-backend/db/src/main/resources/migrations/V19__add_index_to_annotation_task_id.sql

This PR adds an index to the `task_id` foreign key on annotations. Without this index, deleting tasks took a really long time. With this index, it's basically instantaneous even for large numbers of tasks.
Currently applied in prod -- you need a lot of annotations to really see the difference so that's the only realistic setting for testing unfortunately
- make sure the migration runs (I also did this)
- extra credit: create an annotation project in production with a smallish grid size
- delete all of its tasks
- it should be really fast
Closes raster-foundry/annotate#313

Add index to annotations task_id column

---

app-backend/batch/src/main/scala/cogMetadata/RasterSourceMetadataBackfill.scala
docker-compose.yml

Prevent rastersource metadata backfill from fork-bombing itself
- install visualvm if you don't have it
- build your batch jar / container
- in psql, run `update scenes set crs = null;` to make it so all ingested scenes get backfilled
- run 
```
./scripts/console batch "java -Dcom.sun.management.jmxremote.rmi.port=9040 -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=9040 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=localhost -cp /opt/raster-foundry/jars/batch-assembly.jar com.rasterfoundry.batch.Main rastersource-metadata-backfill 8" 
```
Change the 8 at the end to any number of threads that you want
- open visual vm and connect to …

Add configurable metadata backfill threads

---

CHANGELOG.md
app-backend/db/src/main/scala/TaskDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/TaskDaoSpec.scala

This PR makes it so that when we try to create STAC exports for task statuses without labels, we succeed instead of failing with an unrecoverable deserialization error. Also it adds a test to ensure we can't break that particular function in the future.
Important changes are the [new test](https://github.com/raster-foundry/raster-foundry/pull/5256/files?utf8=%E2%9C%93&diff=split&w=1#diff-a0c18aff8467804d0c25aee7929df7b2R852) and [hlist -> case class conversion](https://github.com/raster-foundry/raster-foundry/pull/5256/files?utf8=%E2%9C%93&diff=split&w=1#diff-1f9a76a8eb4f5dc4dbeb3b5db72aab64R515-R518). Everything else is whitespace.
Because we're doing aggregation, Postgres is perfectly happy to give us a row of `NULL`s back and doesn't think this is inconsistent with the filter we asked …

Fix STAC exports with no tasks returned from filter

---

CHANGELOG.md
app-backend/common/src/main/scala/com/rasterfoundry/common/color/ColorCorrect.scala

This PR clips values below the 2nd and above the 98th percentiles in source rasters before normalizing values to 0-255 for RGB visualization. This is done to have better default rendering for imagery that includes very bright areas (clouds, snow) and/or dark areas (water, shadows). The examples in the demo section below show this visualization.
Visualization from this PR:
Visualization from Production:
Histogram adjustment with QGIS (goal is to be close to this in RF):
We're not quite as bright as QGIS - but I think that is _alright_
In general I think things look better and the logic added doesn't seem too onerous/clever. Because this is done on a per-scene basis, projects with many scenes from a number of different days will still look a little off. I think some additionally clever …

Stretch histograms

---

CHANGELOG.md
app-tasks/rf/src/rf/utils/footprint.py

This PR fixes two things:
- when a scene has a simple footprint, it doesn't try to iterate over the polygon, which python/shapely reasonably say isn't iterable
- when an upload to be processed has a nodata value in its dataset metadata, uses that value to figure out the nodata mask instead of deciding everything is 0. I don't know how many more times I'm going to learn that lesson.
- if you haven't done so in a while, assemble api, backsplash-server
- bring up servers + frontend
- create an upload for a scene that doesn't have a crazy footprint with many little data islands and holes
- process it -- `./scripts/console batch 'rf process-upload UPLOAD-ID`
- it should succeed
- create an upload for a scene that _does_ have a crazy footprint with many little …

Fix upload processing for simple footprints

---

CHANGELOG.md
docs/swagger/spec.yml

This PR removes one endpoint that doesn't exist and fixes some spelling
This wasn't a full audit, but there were some things I noticed were incorrect while going through work to prep for Groundwork.
- ci

Clean up some spec problems

---

CHANGELOG.md
app-backend/build.sbt
app-backend/common/src/main/scala/com/rasterfoundry/common/color/ColorCorrect.scala
app-backend/datamodel/src/main/scala/Scope.scala
app-backend/datamodel/src/main/scala/User.scala
app-backend/datamodel/src/test/scala/ScopeSpec.scala
app-backend/project/Dependencies.scala

This PR adds a datamodel for scopes and a bunch of canned policies to make our lives easier.
I left out permissions around project layers on purpose. I also left out permissions for the user endpoints, since all of those endpoints are things that users read about/do to themselves anyway.
I maybe missed more stuff, but I think that it's the case that everything anyone would want to do in the main application is covered here. Regular users explicitly don't have the ability to edit uploads, since that's a system process.
- run tests
- ensure that correct permission relationships are captured by ascending user -> team admin -> organization admin -> platform admin scale
Closes #5259

Add scopes datamodel

---

CHANGELOG.md
scripts/cipublish

Since dependencies are not pinned in `app-lambda/requirements.txt`, new versions of dependencies would accumulate under `/opt` while the old versions were not cleared out.
This PR cleans the `/opt` folder before installing dependencies.
I don't think the lack of a cache will increase build times, since, even if they already exist, it appears that pip tries to download dependencies each time.
Resolves https://github.com/azavea/raster-foundry-platform/issues/878
I had performed a directory listing of `/var/lib/jenkins/workspace/r_Foundry_raster-foundry_develop/app-lambda/opt` to demonstrate that 10+ versions of various dependencies, like `boto3`, had accumulated. Unfortunately, I cleared the folder out and lost my console session so I can't demonstrate what it was like before.
This Jenkins …

Clear Python Lambda function pip cache

---

CHANGELOG.md
app-backend/datamodel/src/main/scala/Scope.scala
app-backend/datamodel/src/test/scala/ScopeSpec.scala
app-backend/db/src/main/resources/migrations/V20__update_user_scopes.sql

This PR does the following:
- adds encoders and decoders for `RasterFoundryPlatformAdmin` and `RasterFoundryUser`
- adds a migration that attaches appropriate user scopes to `scopes` field in the `users` table based on `user_group_roles`:
* it first changes the `scopes` column default to an empty `jsonb` string
* it then updates all values in this `scopes` column to empty `jsonb` string
* based on `user_group_roles`: platform admin, organization admin, team admin, member (no matter what group type), it populates the field according to active (`is_active=true`) and approved (`membership_status='APPROVED'`) user group role in this listed order. Upon each update of a record, it only updates the field when the `scopes` field is empty, so that lower role does not overwrite higher role.
- …

Add a migration to attach user scopes

---

.gitignore
CHANGELOG.md
docker-compose.test.yml
scripts/cipublish

This PR adds a `panrec` step to cipublish to ship typescript interfaces to the artifacts bucket. The test branch `test/js/generate-ts-stubs-in-ci` also includes its changes and tests whether it succeeds.
[Check it out](https://console.aws.amazon.com/s3/buckets/rasterfoundry-global-artifacts-us-east-1/ts-stubs/?region=us-east-1&tab=overview)
- ci / look at the link

Generate typescript stubs in CI

---

CHANGELOG.md
app-backend/datamodel/src/main/scala/Scope.scala
app-backend/datamodel/src/test/scala/ScopeSpec.scala

This PR fixes and tests decoding a mix of canned scopes and actions.
I originally had it set up to try to `decode[Scope]` again if the `ScopedAction` decode failed... but that created a flaky test that sometimes passed and sometimed hit a stack overflow. Oops! Anyway that's fixed now.
- ci is sufficient

Fix decoding mix of canned scopes and actions

---

CHANGELOG.md
app-backend/akkautil/src/main/scala/Authentication.scala
app-backend/datamodel/src/main/scala/Scope.scala
app-backend/db/src/main/scala/UserDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/UserDaoSpec.scala

This adds support for attaching scopes to users when they're created from a JWT. If for some reason the JWT does not include a scope we give them `NoAccess` and assume that something broke in the creation of the JWT.
The rule added to Auth0 :sweat: is the following:
```javascript
function (user, context, callback) {
var path = 'https://app.rasterfoundry.com;scopes';
if (context.clientId === configuration.annotateApplicationID) {
context.idToken[path] = 'groundworkUser';
} else {
context.idToken[path] = 'platformUser';
}
callback(null, user, context);
}
```
This has a setting (in Auth0) that checks if the connection is coming from the annotation application, if it is, then it attaches a canned policy of `groundworkUser` else assumes the user is a regular platform user. So everyone should …

Add scopes from JWT for new users

---

CHANGELOG.md
app-backend/db/src/main/resources/migrations/V21__groundwork_projects.sql

This PR adds a migration for the liberation of Groundwork projects from the Raster Foundry projects domain.
- Any content changes are properly templated using `BUILDCONFIG.APP_NAME`
- ~Any new SQL strings have tests~ many new SQL strings, but not time to test them yet since they're... run by sql
I believe that I've added sufficient indices for fast project deletion to still work. i can't add the foreign key to annotation projects to `tasks` yet (unless we're planning to make a new tasks table?) without making it nullable, so I think that should happen as part of #5281.
I had to change the name of the `order` field because `order` is a reserved word.
- run the migration
Closes #5280

Add migration for annotation projects

---

CHANGELOG.md
app-backend/api/src/main/scala/uploads/Routes.scala
app-backend/common/src/main/scala/S3.scala
app-backend/datamodel/src/main/scala/Upload.scala
app-backend/db/src/main/scala/UploadDao.scala
docs/swagger/spec.yml

This PR adds a `signed-url` route to uploads to request a location on S3 to send PUT http requests to.
- assemble api server
- get a bearer token for the dev user and set it to `$RF_TOKEN`
- get a signed url for the upload in the dev database `http :9091/api/uploads/6d7e3416-2975-4281-9929-251ab8d60e60/signed-url Authorization:$RF_TOKEN`
- `cat <some file> | http PUT 'YOUR SIGNED URL'`
- download the file and confirm that it matches what you `PUT`
Closes #5288

Add signed PUT url endpoint to uploads

---

CHANGELOG.md
app-backend/batch/src/main/scala/Main.scala
app-backend/batch/src/main/scala/projectLiberation/Job.scala
app-backend/db/src/main/resources/migrations/V22__make_teams_optional.sql
app-backend/db/src/main/scala/Dao.scala

For too long annotation projects have toiled under the heel of a datamodel we built for an entirely different purpose. No longer! Today, annotation projects raise their voices in unison and demand new tables and equal footing with their platform project brethren! etc. It's late and I'm not committed to this joke.
Anyway, this PR adds a batch job that creates annotation projects from existing projects that are marked as annotation projects.
Why a batch job instead of a migration? Three reasons. Reason 1: I'm going to break staging for annotate to some extent when I move tasks to annotation projects. However, when we _create_ new projects in staging, they'll still become old projects until the switchover is complete in the annotation UI. That means we'll probably have to run the job more …

Liberate annotation projects

---

CHANGELOG.md
app-frontend/config/webpack/overrides.js.template
app-frontend/src/app/services/auth/auth.service.js

This PR allows redirect to an arbitrary custom url on logout.
TODO added to azavea/raster-foundry-platform#926 to make sure at deployment time that the redirect is set -- this might get hotfixed though in which case that'll become unnecessary
- copy overrides.js.template to overrides.js
- copy helpDocs.json.template to helpdocs.json
- set LOGOUT_REDIRECT_URL to something other than `''`
- start up frontend and servers
- login
- logout
- you should end up at whatever you set LOGOUT_REDIRECT_URL to
Closes azavea/raster-foundry-platform#934

Redirect to custom url from buildconfig

---

CHANGELOG.md
app-backend/api/src/main/scala/project/ProjectLayerTaskRoutes.scala
app-backend/common/src/test/scala/com/implicits/Generators.scala
app-backend/datamodel/src/main/scala/Task.scala
app-backend/db/src/main/resources/migrations/V24__update_task_annotation_project_id.sql
app-backend/db/src/main/resources/migrations/V27__update_task_annotation_project_id.sql
app-backend/db/src/main/resources/migrations/V28__add_index_to_task_annotation_project_id.sql
app-backend/db/src/main/scala/TaskDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/AnnotationDaoSpec.scala
app-backend/db/src/test/scala/com/azavea/rf/database/PropTestHelpers.scala
app-backend/db/src/test/scala/com/azavea/rf/database/TaskDaoSpec.scala

This PR adds a migration to add a `annotation_project_id` field to `tasks` table and populates this field with `id`s of `annotation_projects` project. 
```
$ ./scripts/migrate migrate
[RF-API] Running migrations with docker-compose
Starting raster-foundry_postgres_1 ... done
Flyway Community Edition 5.2.4 by Boxfuse
Database: jdbc:postgresql://database.service.rasterfoundry.internal/ (PostgreSQL 9.6)
Successfully validated 33 migrations (execution time 00:00.450s)
Current version of schema "public": 23
Migrating schema "public" to version 24 - update task annotation project id
Successfully applied 1 migration to schema "public" (execution time …
```

Add a migration to add annotation project id to tasks

---

.gitignore
app-backend/build.sbt
app-backend/datamodel/src/main/scala/AnnotationLabel.scala
app-backend/db/src/main/scala/util/AnnotationLabelDao.scala

* Add model for AnnotationLabel. AnnotationLabelWithClasses is what we want to be sending to/from the API, AnnotationLabel is used internally for deserializing stuff from the database.
* Implemented the insert and list dao functions.
* Disable compiler option that seems to be breaking metals/bloop
- Verify that it compiles and the queries make sense

Add AnnotationLabel model and dao

---

CHANGELOG.md
app-backend/batch/src/main/scala/projectLiberation/Job.scala
scripts/cibuild

This PR makes the annotation project migration async job tolerant of more kinds of errors than it was previously.
- ~Any new SQL strings have tests~ nope
~Has been run against staging / copy of prod db, mainly needs to be CI'ed after CI gets un-nuked~
- run it against a copy of the prod db and verify that everything that goes wrong is explicable and we have a plan for it
Closes azavea/raster-foundry-platform#952

Handle more classes of errors in annotation project migration

---

CHANGELOG.md
app-backend/akkautil/src/main/scala/CommonHandlers.scala
app-backend/datamodel/src/main/scala/Scope.scala
app-backend/datamodel/src/test/scala/ScopeSpec.scala

This PR makes scope resolution follow rules for resolving scoped actions for a given domain and action. If two scoped actions have the same domain and action, the following rules are applied:
- if one has a limit and the other doesn't, prefer the one without a limit
- if both have limits, prefer the higher limit
- confirm changes make sense
- I wanted local testing instructions but annotate pointing to local rf seems kind of broken right now, so :man_shrugging:
- we could push this to a test branch to prove things, but I think the changes are small enough and easy enough to reason about that I don't think that's necessary
Closes #5315

Make scope resolution smarter about limits

---

CHANGELOG.md
app-backend/api-it/src/test/resources/endpoint-scopes.csv
app-backend/api/src/main/scala/annotation-project/AnnotationProjectTaskRoutes.scala
app-backend/api/src/main/scala/annotation-project/Routes.scala
app-backend/api/src/main/scala/project/ProjectAnnotationRoutes.scala
app-backend/api/src/main/scala/project/ProjectLayerAnnotationRoutes.scala
app-backend/db/src/main/scala/AnnotationLabelDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/AnnotationLabelDaoSpec.scala

This PR:
After discussions with @alkamin , the list endpoint for annotations in a task is not paginated in this PR.
- `db/testOnly *AnnotationLabelDaoSpec` should pass
- `GET` to `/api/annotation-projects/<projectId>/tasks/<taskId>/labels` should list labels from this task
- `DELETE` to `/api/annotation-projects/<projectId>/tasks/<taskId>/labels` should remove labels from this task
- Make sure the scopes and acrs are in place. Grab an id of a project that you are an owner of, GET to `/annotation-projects/:id/actions` should be `[*]`
- Change to an account that is a member of a team that has access to this project. Make sure …

Add annotation label list and delete Dao methods, endpoints, tests; Add annotation project list action endpoint

---

CHANGELOG.md
app-backend/api-it/src/test/resources/endpoint-scopes.csv
app-backend/api/src/main/scala/annotation-project/AnnotationProjectPermissionRoutes.scala
app-backend/api/src/main/scala/annotation-project/Routes.scala
app-backend/api/src/main/scala/token/Token.scala
app-backend/api/src/main/scala/user/Auth0User.scala
app-backend/api/src/main/scala/user/Routes.scala
app-backend/datamodel/src/main/scala/User.scala
app-backend/db/src/main/scala/AnnotationProjectDao.scala
app-backend/db/src/main/scala/UserDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/UserDaoSpec.scala
docker-compose.yml

This PR adds a share endpoint to annotation projects that enables sharing with only an email address.
- ~Swagger specification updated~ nope!
We chose explicitly now to worry about user merging -- so if a user who is shared with via email signs in socially... they won't have access to the same stuff. We're opting not to worry about that for now. Automatic merging is an option, but it relies on yet another rule, and rules proliferation is frankly already fairly scary for us. :man_shrugging:  So we're ignoring this problem until it's something that someone asks us to care about.
- assemble API
- get your dev db in order -- `./scripts/load_development_data --download` :tada:
- bring up api, frontend
- get a bearer token for the dev user
- `export JWT_AUTH_TOKEN=<your token, without the …

Add special share endpoint for possibly non-existent users

---

CHANGELOG.md
app-backend/api-it/src/test/resources/endpoint-scopes.csv
app-backend/api/src/main/scala/user/Routes.scala
app-backend/datamodel/src/main/scala/Scope.scala
app-backend/db/src/main/scala/AnnotationProjectDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/AnnotationProjectDaoSpec.scala
docs/swagger/spec.yml

Add endpoint for fetching user account limitations and usage
```
> $ http --auth-type=jwt :9091/api/users/me/limits                                                                                                                                                         
HTTP/1.1 200 OK
X-Powered-By: Express
connection: close
content-encoding: gzip
content-type: application/json
date: Mon, 24 Feb 2020 22:15:23 GMT
server: nginx
strict-transport-security: max-age=15552000; preload
transfer-encoding: chunked
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
[
{
"action": "create",
"domain": "annotationProjects",
"limit": 10.0,
"objectId": null,
"used": 1.0
},
{
"action": "create",
"domain": "uploads",
"limit": null,
"objectId": null,
"used": 0.0
},
{ …
```

Add /user/me/limits endpoint

---

CHANGELOG.md
app-backend/api/src/main/scala/utils/QueryParameters.scala

Putting this one up just for consistency.
- assemble jars and spin up servers
- create a stac export with the below:
```json
{
"name": "test",
"owner": null,
"license": {
"license": "proprietary",
"url": ""
},
"taskStatuses": [],
"annotationProjectId": "<your annotation project ID>"
}
```
- get `/stac?annotationProjectId=<your annotation project ID>` should give you the export you created for this annotation project

Make STAC export query param consistent

---

CHANGELOG.md
app-backend/db/src/main/scala/UploadDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/UploadDaoSpec.scala

This PR updates UploadDao and the UploadDaoSpec so that the update method updates the values of `generateTasks` and `annotationProjectId` along with all the other fields.
- Create an upload
- Update the upload with a different value for `generateTasks` and `annotationProjectId` and see that they are reflected in the DB
Closes #5329

Make upload PUT update all fields

---

CHANGELOG.md
app-backend/api-it/src/test/resources/endpoint-scopes.csv
app-backend/api/src/main/scala/annotation-project/AnnotationProjectPermissionRoutes.scala
app-backend/api/src/main/scala/annotation-project/Routes.scala
app-backend/datamodel/src/main/scala/User.scala
app-backend/db/src/main/scala/AnnotationProjectDao.scala
app-backend/db/src/main/scala/UserDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/UserDaoSpec.scala

List endpoint returns a thin user model, containing id, email, and picture
```
> $ http :9091/api/annotation-projects/3dc49c06-cf04-4ca7-b9c7-c711154b0aee/share --auth-type=jwt
X-Powered-By: Express
connection: close
content-encoding: gzip
content-type: application/json
date: Thu, 27 Feb 2020 16:30:01 GMT
server: nginx
strict-transport-security: max-age=15552000; preload
transfer-encoding: chunked
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
[
{
"email": "rf+public+member@rasterfoundry.com",
"id": "auth0|5b1edbfaa76b70216925b6a1",
"profileImageUri": "https://s.gravatar.com/avatar/abb56c6bc743d26ec4e040d86f9d167a?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Frf.png"
}
]
```
Decided to return the user profile pic anyways, since if they …

Add routes for listing/deleting users an annotation project is shared with

---

CHANGELOG.md
app-backend/batch/src/main/scala/groundwork/CreateTaskGrid.scala
app-tasks/Dockerfile
app-tasks/rf/requirements.txt
app-tasks/rf/src/rf/commands/process_upload.py
app-tasks/rf/src/rf/uploads/geotiff/create_bands.py
app-tasks/rf/src/rf/uploads/geotiff/factories.py

This PR makes sure that we don't try to generate tasks for an annotation project until after we've added the scenes to its project. 
- follow the testing instructions from #5324 
- they should work _the first time_

Generate tasks after adding scenes to projects

---

CHANGELOG.md
app-backend/api/src/main/scala/annotation-project/AnnotationProjectPermissionRoutes.scala
app-backend/db/src/main/scala/AnnotationProjectDao.scala

This PR fixes bugs where:
- deleting permissions for the only user an annotation project had been shared with went down an exceptional path (from `replacePermissions`'s perspective)
- deleting all of the permissions for a project returned a surprise 404 because of the `completeWithOneOrFail` directive
Fixes an issue I encountered while testing raster-foundry/annotate#681
- share with exactly one user using the `share` endpoint
- try to delete permissions you added for that user
- it should succeed

Fix permission deletion

---

CHANGELOG.md
app-backend/db/src/main/scala/UploadDao.scala

Fix 403 when testing scope limits for new users
- Delete all uploads for your user
- start the annotate frontend, point it at your local server (make sure to set the `REACT_APP_RGB_DATASOURCE` variable to a 3 band datasource
- build your api jar off develop and start the server
- verify that you can't create an upload and get a 403 response
- build your api jar off this branch and restart the server
- verify that you can now create an upload instead of getting a 403
Closes https://github.com/raster-foundry/annotate/issues/673

Fix null returned when summing user uploaded bytes if user has no uploads

---

CHANGELOG.md
app-backend/api/src/main/scala/annotation-project/AnnotationProjectPermissionRoutes.scala
app-backend/api/src/main/scala/user/Auth0User.scala
app-backend/db/src/main/scala/ObjectPermissions.scala
app-backend/db/src/test/scala/com/azavea/rf/database/ProjectDaoSpec.scala

This PR makes a few changes to how exceptional cases are handled when sharing annotation projects with users by email:
- It checks for a user's prior existence in Auth0 by email before trying to create a user with that email address. If a user exists, it proceeds with that `Auth0User`.
- it stops error-ing when trying to add a permission to a list of ACRs that is already present. Instead, it returns the existing list, since the db already reflects the state indicated by the user's request
- it makes potential errors in `replacePermissions` explicit in the type so that it'll at least be obvious where errors are coming from if we run into more exceptional cases in the future
This doesn't really change what happens in error cases -- but it does fix what occurs in several previous unexpected …

Improve error-handling with sharing by email

---

app-backend/api-it/src/test/resources/endpoint-scopes.csv
app-backend/api-it/src/test/scala/ScopeSpec.scala
app-backend/datamodel/src/main/scala/Scope.scala
app-tasks/rf/src/rf/uploads/geotiff/factories.py
app-tasks/rf/src/rf/utils/cog.py

This PR fixes two issues that came up in user testing:
1. Users were unable to download scenes from the UI because scopes were incorrectly added for projects when it should have been scenes
2. Task grid generation failed because the grid being generated did not make any sense for the CRS of the generated COG. The conversion of the task size pixels to task size meters assumed the tiff was in a projection whose unit was meters. This lead to task size grids being generated that were _way_ too small that would cause the database to crash.
- Rebuild batch container and make sure your API server is up-to-date
- Create a project, copy its ID:
```
export JWT_AUTH_TOKEN=<JWT TOKEN FROM UI>
echo '{"name":"new-project-4326","description":"a new …
```

Fix Minor Scopes Issue and Fix Non Web Mercator Task Grid Generation

---

CHANGELOG.md
app-backend/api/src/main/scala/annotation-project/AnnotationProjectPermissionRoutes.scala
app-backend/api/src/main/scala/datasource/Routes.scala
app-backend/api/src/main/scala/project/Routes.scala
app-backend/api/src/main/scala/scene/Routes.scala
app-backend/api/src/main/scala/shape/Routes.scala
app-backend/api/src/main/scala/toolrun/Routes.scala
app-backend/api/src/main/scala/tools/Routes.scala
app-backend/db/src/main/scala/ObjectPermissions.scala

This PR adds a method in `ObjectPermissions` trait to check if the ACR list to be replaced is compliant with the operating user's limit on the scoped actions of a specific domain. It appends such checks on the current endpoints where we perform permission replacement.
- Edit your testing user's share action limit on annotation project to 0
- `PUT` to `/api/annotation-projects/<projectId>/permissions` with a positive-length list of `ObjectAccessControlRule`s
- The endpoint should not allow you to …

Make permission replacement obey same scope rules

---

CHANGELOG.md
app-backend/batch/src/main/scala/groundwork/CreateTaskGrid.scala
app-backend/db/src/main/resources/migrations/V35__update_make_grid_to_clip_cell_to_project_bound.sql
scripts/server

This PR updates the `ST_MakeGrid` function so that each cell for the task grid is a result of applying  `ST_Intersection` on the calculated `newSector` and the passed in geometry `bound_polygon`  (which, for task grid creation, is the project footprint under the hood).
- run migrations
- Make your testing user's scope `"groundworkUser;platforms:admin;"`
- Grab the id of project `Local File Single Scene`
- `POST` to `api/annotation-projects` with the following:
```json
{
"name": "GW|Local File Single …
```

Clip task cell to project footprint

---

app-frontend/src/app/components/scenes/sceneImportModal/sceneImportModal.controller.js

This fixes a bug introduced when we added a new required field to `api/uploads/`
- Create a project in the frontend
- Try to upload some imager
Closes #5326

Add missing field to upload POST in Frontend

---

CHANGELOG.md
app-tasks/rf/requirements.txt

Because that's what Jenkins wants all of a sudden?
Somehow, running the exact same step from `cibuild` to build the batch container locally... doesn't reproduce the issue, even with `--no-cache`. I'm baffled and sitting here with :crossed_fingers: .
- ci
Closes azavea/raster-foundry-platform#984

Make app-tasks python3.7 compatible

---

app-tasks/rf/requirements.txt

When we upgraded `pyproj` something incompatible was introduced that caused an exception to be thrown when the planet library was imported
CI
Closes #5353

Update planet dependency to avoid syntax bug on import

---

.gitignore
CHANGELOG.md
app-backend/batch/src/main/scala/groundwork/CreateTaskGrid.scala
app-backend/common/src/test/scala/com/implicits/Generators.scala
app-backend/datamodel/src/main/scala/AnnotationProject.scala
app-backend/datamodel/src/main/scala/AnnotationProjectStatus.scala
app-backend/db/src/main/resources/migrations/V36__annotation_project_status.sql
app-backend/db/src/main/scala/AnnotationProjectDao.scala
app-backend/db/src/main/scala/meta/EnumMeta.scala
app-backend/db/src/test/scala/com/azavea/rf/database/AnnotationProjectDaoSpec.scala
app-tasks/rf/src/rf/commands/process_upload.py
app-tasks/rf/src/rf/models/annotation_project.py

Add a more informative status field to annotation projects
Migrate from the ready field to a status field
Set statuses correctly in upload processing
Statuses as set by raising exceptions in the appropriate sections of the upload batch process:
Error handling does not encompass larger scale batch issues (unable to contact API, etc), since we don't have a good way of handling that right now. This should be handled in a later issue
- build your batch jar
- build your batch container
- run migrations
- start the API server, etc.
- start the annotate frontend on the accompanying annotate branch
- create a project with a small upload to make things to quickly
- find the upload id in your database: `select id from uploads where annotation_project_id = '<annotation_project_id>';`
- run the batch …

Hook up async tasks to new AnnotationProject.status field

---

CHANGELOG.md
app-backend/batch/src/main/resources/application.conf
app-backend/batch/src/main/scala/Main.scala
app-backend/batch/src/main/scala/groundwork/Config.scala
app-backend/batch/src/main/scala/groundwork/CreateTaskGrid.scala
app-backend/batch/src/main/scala/groundwork/NotifyIntercom.scala
app-backend/batch/src/main/scala/groundwork/types.scala
app-backend/build.sbt
app-backend/project/Dependencies.scala
app-tasks/rf/src/rf/commands/process_upload.py
app-tasks/rf/src/rf/utils/io.py

This PR starts the work to notify users in intercom when their projects are ready.
~It's in Scala because _my god_ that's a complicated datamodel. I'll show a response. It's _huge_. I don't want to remember over time what values are present in this thing in python so instead I'm making the values I'm grabbing from the response json super explicit and we can add more as necessary.~ It turns out that the endpoint we're interacting with is a lot less complicated, but I didn't rewrite it in python after learning that. This is reusable in other batch jobs now, which has value as well. Also, hilariously, there's [no python sdk](https://developers.intercom.com/building-apps/docs/sdks-plugins) anyway.
~This might also move out of `batch` someday if we need it elsewhere but for now I'm thinking it …

Notify users in intercom when their annotation projects are ready

---

CHANGELOG.md
app-backend/batch/src/main/resources/application.conf
app-backend/batch/src/main/scala/groundwork/Config.scala
app-backend/batch/src/main/scala/groundwork/CreateTaskGrid.scala
app-tasks/rf/src/rf/commands/process_upload.py
docker-compose.yml

This PR updates the `CreateTaskGrid` job and `process_upload.py` to:
- use a link to somewhere that exists in the Groundwork application instead of to the Raster Foundry API
- ask users to reach out in Intercom first, _or_ by email, since we clearly have in app chat capabilities
- lazy version: look at the link, look at the way it's being templated, think for a minute about whether that's a more useful link than a link to somewhere in the RF API (the notification machinery has already been tested and you can visually confirm these are all just string changes)
- non-lazy version:
- bring up local annotate pointing to local rf
- assemble batch jar
- build the batch container
- bring up your rf servers / frontend
- create a project in local annotate
- process the upload
- you should get a …

Link to somewhere in Groundwork, not to RF API

---

CHANGELOG.md
app-backend/akkautil/src/main/scala/Authentication.scala
app-backend/api/src/main/resources/application.conf
app-backend/api/src/main/scala/utils/Config.scala
app-backend/db/src/main/scala/AnnotationLabelDao.scala
app-backend/db/src/main/scala/AnnotationProjectDao.scala
app-backend/db/src/main/scala/Dao.scala
app-backend/db/src/main/scala/TaskDao.scala
app-backend/db/src/main/scala/TileLayerDao.scala
app-backend/db/src/main/scala/UserDao.scala
scripts/load_development_data

* Add env variables for setting sample project
* Make Annotation project deletion only delete user owned resources
* Mess around with some dao stuff
* add options for creating / uploading db dumps to the `load_development_data` script
When creating a project to use as a sample project, you'll need to set `visibility="PUBLIC"` on the associated RF project. This RF project is not replicated across users, and any changes to it will affect the sample project on every user.
Labels are not copied right now, but tasks, label classes, label class groups, annotation project are.
- in your RF repo, run `./scripts/bootstrap --env` to fetch the latest `.env` file from s3
- in your annotate repo, use the following `env.local` values: (Yes, they changed)
``` …
```

Copy sample project when user is created

---

CHANGELOG.md
app-backend/db/src/main/scala/TaskDao.scala

It's really easy to accidentally change a task status on a sample project. This ignores them.
- reset your dev database and make sure you have the latest version
- on `dev@rasterfoundry.com`, edit the sample project by labeling a few tasks
- create a new account, and verify that the sample project doesn't have any labeled tasks

Don't copy a couple fields on sample project tasks

---

CHANGELOG.md
app-backend/common/src/main/resources/reference.conf
app-backend/db/src/main/scala/Config.scala
app-backend/db/src/main/scala/SceneToLayerDao.scala
docker-compose.yml

This PR buffers scene data footprints by 5% when deciding whether they intersect with the search polygon. The reason for this is that the footprint calculation in upload processing is not great it turns out and ends up skewed pretty frequently, and this is a quicker fix than figuring out how/why it's skewed.
The strategy proposed in the issue wasn't actually possible, since we don't have the raster source information until after we determine the intersecting scenes.
Data loss for The Bad Tif :tm: still occurs at zoom 22:
We can do a larger buffer (10%?) to push that down further, but with the band-aid in place it might be more worthwhile to figure out what's going on in footprint calculation.
- assemble api, backsplash-server
- bring up server
- process The Bad Tif :tm: if you don't have …

Buffer TMS grid polygon by 5% to find scenes

---

CHANGELOG.md
app-backend/db/src/main/scala/SceneToLayerDao.scala

This PR moves intersection buffering on scenes from the scene footprint (which could be an arbitrarily complex geometry) to the scene footprint extent (which is a rectangle). It makes The Bad Tif :tm: correctly visible through at least zoom 29, which is far more than enough
Skipping the caching idea, since we dramatically simplified the max complexity of the geometry we're buffering, and this is still supposed just to be a band aid
- watch the gif
- make sure you agree the small code change does what i say it does
Closes #5358 again :disappointed:

Move buffering from footprint to tms extent

---

CHANGELOG.md
app-backend/datamodel/src/main/scala/AnnotationProject.scala
app-backend/db/src/main/resources/migrations/V40__Add_task_summary_to_annotation_project.sql
app-backend/db/src/main/resources/migrations/V41__Add_gin_index_to_task_summary.sql
app-backend/db/src/main/scala/AnnotationProjectDao.scala
app-backend/db/src/main/scala/Dao.scala
app-backend/db/src/main/scala/filters/Filterables.scala
app-backend/db/src/test/scala/com/azavea/rf/database/TaskDaoSpec.scala

This PR:
- adds a new field `task_status_summary` to the `annotation_projects` table to store task status distribution for annotation projects
- adds a database trigger on `INSERT`/`UPDATE`/`DELETE` operations on `tasks` table so that `task_status_summary` in `annotation_projects` table is in sync
- adds back the old `authQuery` logic so that the `counts` field should work the same as before
- fixes a bug in the calculation of `hasNext` field in `Dao`
- ~Swagger specification updated~ (There is no spec for annotation project set of endpoints)
- Tests are updated to test the new trigger and new column, so CI should pass
- Run …

Add task summary field to annotation projects table; Add DB trigger for operations on tasks table

---

CHANGELOG.md
app-backend/api-it/src/test/resources/endpoint-scopes.csv
app-backend/api/src/main/scala/Router.scala
app-backend/api/src/main/scala/annotation-project/AnnotationProjectTaskRoutes.scala
app-backend/api/src/main/scala/annotation-project/Routes.scala
app-backend/api/src/main/scala/tasks/Routes.scala
app-backend/datamodel/src/main/scala/PaginatedGeoJsonResponse.scala
app-backend/db/src/main/scala/AnnotationProjectDao.scala
app-backend/db/src/main/scala/TaskDao.scala
app-backend/db/src/main/scala/filters/Filterables.scala
app-backend/db/src/test/scala/com/azavea/rf/database/TaskDaoSpec.scala

This PR adds an endpoint to grab a list of tasks in projects, subject to task query params and annotation project query params. ~Currently it compiles, is untested, and the behavior might be wrong, _a triple threat_.~
I also had to make some pretty huge (in surface area) changes to the `AnnotationProjectDao`, since there was inconsistent handling of the table name alias. In some cases, we referred to the table as `ap.`, and in others we didn't. In particular, the `Filterable` instance for its query parameters used `ap.`, which made the `tableName` value worthless. Now, everything uses `annotation_projects.` instead, since `Dao` constructs column names as `tableName.fieldName`. This would be scary, but tests pass, so we know all the methods work.
Pagination is applied to the annotation …

Get a task for any project, subject to constraints

---

CHANGELOG.md
app-backend/datamodel/src/main/scala/AnnotationProject.scala
app-backend/db/src/main/scala/meta/CirceJsonbMeta.scala
app-backend/db/src/test/scala/com/azavea/rf/database/TaskDaoSpec.scala

This PR updates the type of `taskStatusSummary` field of `AnnotationProject` so that it is of type `Option[Map[String, Int]]` with a default value `None`.
- ~Swagger specification updated~(there is no spec for annotation project related endpoints)
- Property tests should pass
- `./scripts/console sbt`
- `api/assembly`
- `./scripts/server`
- Pull down branch from this GW PR: https://github.com/raster-foundry/annotate/pull/817
- Follow steps in [here](https://github.com/raster-foundry/annotate/wiki/Point-to-Raster-Foundry-l …

Update type of task status summary in annotation project data model

---

CHANGELOG.md
app-backend/batch/src/main/scala/stacExport/StacFileIO.scala
app-backend/batch/src/main/scala/stacExport/Utils.scala
app-backend/batch/src/main/scala/stacExport/WriteStacCatalog.scala
app-backend/build.sbt
app-backend/db/src/main/scala/TaskDao.scala

This PR fetches and includes imagery in STAC exports adjacent to the scene items it's imagery for.
It also removes a bunch of S3 interaction so we don't end up duplicating everything in the universe anymore, now that there's non-json flying around.
~wip because no joke I can't figure out how to write a file omg I just want to take bytes from s3 and put them on disk :sob: :sob: :sob:~
- label your sample project in local Groundwork some
- create an export for it
- grab the most recent id from `stac_exports`
- `./scripts/console batch 'java -cp /opt/raster-foundry/jars/batch-assembly.jar com.rasterfoundry.batch.Main write_stac_catalog <your id>'`
- download the zip file on s3 somewhere, e.g. -- `mkdir catalog && aws --profile raster-foundry s3 cp <export location> …

Include imagery in STAC exports

---

CHANGELOG.md
app-backend/db/src/main/scala/TaskDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/TaskDaoSpec.scala

This PR calls `deleteLock` in the task status expiration function so that it actually does the thing that we care most about :man_facepalming: 
Testing with `testOnly db/TaskDaoSpec -- -z "expire"`
Without the change:
```
Message: List("2080bf31-2f0d-4ca0-9a39-8da95d0aaa2e") did not equal List() All tasks reverted to not being locked by anyone
...
*** 1 TEST FAILED ***
```
With the change:
```
[info] All tests passed.
```
- tests
Closes raster-foundry/annotate#848

Delete locks in task expiration function

---

app-backend/akkautil/src/main/scala/Authentication.scala

This PR fixes an error that happens when simultaneous requests come from a new user. Before this commit an error would be thrown because the same user would try to be created multiple times and this would violate uniqueness constraints.
After this PR the various stages of checking for an existing user and creating a new one are separated out into their own transactions. This allows us to catch when a uniqueness constraint has been violated and re-request the user given an ID from the database.
I _wanted_ to use `exceptSqlState` from `doobie`, but I couldn't because a lot of logic was in a _single_ transaction. After an error in a transaction, postgres ignores subsequent SQL statements. I tried relaxing the commits within a transaction, but this lead to different race conditions since …

Handle simultaneous user creation that throws errors

---

CHANGELOG.md
app-backend/api/src/main/scala/annotation-project/Notifications.scala

This PR sets the width of the gif and banner image explicitly so that the SVG doesn't end up hilariously huge.
I can't see the svg in my email at all so I don't know what's wrong there. However, @aaronxsu could see the svg in his email, and when I copy the notification out to an html file everything cooperates, so maybe it's fine.
- see email instructions for #5383 for longer form instructions
- invite a user who doesn't exist for an email address you control
- look at the email
- the Groundwork logo should be a reasonable size

Explicitly set width of imagery in email

---

CHANGELOG.md
app-backend/api/src/main/scala/annotation-project/Notifications.scala

This PR:
- removes the gif from the new user sharing email
- makes the email pretty (thanks @designmatty )
~It will accumulate small changes that don't require verification so we don't have to open a bunch of different PRs to get those sorts of changes in.~ there were no more small changes that fit this pattern
- assemble api server
- bring up local rf
- start local annotate pointed to local api server
- share with a user who doesn't exist whose email you can see
- observe how pretty and Obi Wan-less the email is
Closes raster-foundry/annotate#839

Remove gif from new user sharing email

---

CHANGELOG.md
app-backend/db/src/main/scala/TaskDao.scala

This PR makes task status expiration no longer care about the most recent action, and instead just always go down the [chain of being](https://en.wikipedia.org/wiki/Great_chain_of_being), with `Validated` at the top and `Unlabeled` at the bottom.
I'm having trouble thinking of a way to test this behavior in an automated fashion, since our test transactor rolls back and I don't have ideas other than `.transact(xa)` for getting a parallel instance.
- expiration test still passes
- you confirm visually that you can't come up with a way that the resulting function call here can result in cycling task statuses from multiple copies of backsplash doing expiration at the same time
Closes raster-foundry/annotate#851

Make task status reversion dumber

---

CHANGELOG.md
app-backend/db/src/main/scala/TaskDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/TaskDaoSpec.scala

This PR includes `LABELED` and `VALIDATED` tasks in the scope of what locks get automatically expired.
We didn't previously know this was a possible place they could get stuck :thinking: 
- CI
- inspect status regression logic

Expire stale locks on labeled and validated tasks as well

---

CHANGELOG.md
app-backend/api/src/main/scala/annotation-project/Notifications.scala

This PR updates the copy in the invitation email body.
- assemble api server
- bring up local rf servers
- start local annotate pointed to local api server
- share with a user who doesn't exist whose email you can see
- make sure the email body has the updated copy
Closes https://github.com/raster-foundry/annotate/issues/848

Update email invitation copy

---

CHANGELOG.md
app-backend/db/Dockerfile.migrations
app-backend/project/Dependencies.scala
docker-compose.dev.yml
docker-compose.test.yml
docker-compose.yml

Bump the container images used to provide a PostGIS enabled PostgreSQL service in development. Ensure that they provide PostgreSQL 12.x and PostGIS 3.x.
~- [ ] Swagger specification updated~
~- [ ] New tables and queries have appropriate indices added~
~- [ ] Any new endpoints have scope validation and are included in the integration test csv~
- The changes in this PR depend on the changes in https://github.com/azavea/raster-foundry-deployment/pull/250.
- I updated the version of Flyway because the previous version was emitting a warning regarding lack of PostgreSQL 12 support. I did not update to the most up-to-date version of Flyway (6.4).
- Bring up the local …

Add development support for PostgreSQL 12.x/PostGIS 3.x

---

CHANGELOG.md
app-backend/api-it/src/test/resources/endpoint-scopes.csv
app-backend/api/src/main/scala/Router.scala
app-backend/api/src/main/scala/campaign/CampaignPermissionRoutes.scala
app-backend/api/src/main/scala/campaign/CampaignProjectRoutes.scala
app-backend/api/src/main/scala/campaign/Routes.scala
app-backend/api/src/main/scala/utils/QueryParameters.scala
app-backend/common/src/test/scala/com/implicits/Generators.scala
app-backend/datamodel/src/main/scala/AnnotationProject.scala
app-backend/datamodel/src/main/scala/Campaign.scala
app-backend/datamodel/src/main/scala/ObjectType.scala
app-backend/datamodel/src/main/scala/QueryParameters.scala
app-backend/datamodel/src/main/scala/Scope.scala
app-backend/db/src/main/resources/migrations/V42__Add_campaigns.sql
app-backend/db/src/main/scala/AnnotationProjectDao.scala
app-backend/db/src/main/scala/CampaignDao.scala
app-backend/db/src/main/scala/ObjectPermissions.scala
app-backend/db/src/main/scala/ProjectDao.scala
app-backend/db/src/main/scala/filters/Filterables.scala
app-backend/db/src/test/scala/com/azavea/rf/database/AnnotationProjectDaoSpec.scala
app-backend/db/src/test/scala/com/azavea/rf/database/CampaignDaoSpec.scala

This PR:
Done in this issue but not in code of this PR:
-~Any content changes are properly templated using `BUILDCONFIG.APP_NAME`~
- `./scripts/load_development_data --download`
- Assemble api server. Spin up servers and frontend. Log in as the dev user and grab a token
- `export TOKEN=<your bearer token>`
- List campaigns. It should include 1 campaign, since an example campaign is included in the updated pgdump
```bash
curl --location --request GET 'http://localhost:9091/api/campaigns' \
--header "Authorization: Bearer ${TOKEN}" 
```
- Create a campaign:
```bash
curl --location --request POST 'http://localhost:9091/api/campaigns' \
--header "Authorization: Bearer ${TOKEN}" \
--data-raw '{
"name": "New Campaign",
"campaignType": "SEGMENTATION" …
```

Support campaigns

---

CHANGELOG.md
app-backend/api/Dockerfile
docker-compose.test.yml
docker-compose.yml

This PR downgrades all the jdk containers to Java 8. It _should_ fix what happens when posting scenes, like what happened in [this error](https://my.papertrailapp.com/groups/4082193/events?focus=1192887760147595269&q=program%3Astaging%2Fapi-server&selected=1192887760147595269). At least it fixed it in the tile server when we downgraded.
:crossed_fingers: 
- grep for `jdk11`
- confirm that it's _gone_

Downgrade all the jdk containers

---

CHANGELOG.md
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Authorizers.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Cache.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Main.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/services/AnnotationProjectMVTService.scala
app-backend/build.sbt
app-backend/db/src/main/scala/AnnotationProjectDao.scala
app-backend/db/src/main/scala/MVTLayerDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/MVTLayerDaoSpec.scala
app-backend/project/Dependencies.scala

This PR adds a service to serve vector tiles for labels and tasks in annotation projects. It doesn't actually fetch the vector tiles from the db yet though but I want coffee before I write anything else and that's a good time for Jenkins to hang out and do stuff.
- ~Any new endpoints have scope validation and are included in the integration test csv~ no scope checking in tile server
The tasks mvts are returning all of their data. The label mvts are just returning geometry + class name + color hex code, since I'm going through a join and don't know what related info to fetch. If we need more stuff, it's not that hard to get it.
The tests don't have any expectations about results because I don't know what kind of expectations we can create about byte arrays. Maybe that something should be a …

Add routes for MVT layers for tasks and labels

---

CHANGELOG.md
app-backend/common/src/main/scala/utils/CogUtils.scala

This PR updates the overview selection math to respect the new value returned by `RasterSource.resolutions`. The previous type had a height and width, as does `CellSize`, but the implications of doing height and width math with `GridExtent`s are very different from doing height and width math with `CellSize`s. This is a change that we requested but I forgot to track it down when doing the gt upgrade. It also adds some more debug logging that will help us in case this fails in the future. It shouldn't for anything that has overviews, since 256x256 << 400000 and that's where gdal by default stops adding overviews to things, but at least it'll be a little bit easier to tell what happened if it does.
- download the tif from the linked issue (see `Closes:`)
- bring up Groundwork pointed to …

Fix overview size calculation math for new GT

---

CHANGELOG.md
app-backend/batch/src/main/scala/stacExport/Utils.scala
app-backend/batch/src/main/scala/stacExport/WriteStacCatalog.scala
docker-compose.yml

This PR removes the only self link that I found from the `WriteStacCatalog` batch job.
download this: `s3://rasterfoundry-development-data-us-east-1/stac-exports/1dd96375-2d13-4ec7-94b7-3310dc8efa50/catalog.zip` and grep for `self` / `Self` ( I don't know whehter it would have been capitalized but they're both gone)
- assemble batch / api (api only if you haven't recently -- there's nothing new there)
- bring up memcached + postgres
- bring up local annotate pointed to local rf
- while watching your network tab, create an export in annotate and grab its id from the response
- run this command:
```bash
java \
-Dcom.sun.management.jmxremote.rmi.port=9040 \
-Dcom.sun.management.jmxremote=true \
-Dcom.sun.management.jmxremote.port=9040 \ …
```

Don't write self link to catalog root in stac export

---

CHANGELOG.md
app-backend/api/src/main/scala/user/PseudoUsernameService.scala
app-backend/common/src/test/scala/com/implicits/Generators.scala
app-backend/datamodel/src/main/scala/PseudoUsernameType.scala
app-backend/datamodel/src/main/scala/TileLayer.scala
app-backend/datamodel/src/main/scala/TileLayerQuality.scala
app-backend/db/src/main/resources/migrations/V49__add_quality_to_tile_layers.sql
app-backend/db/src/main/scala/TileLayerDao.scala
app-backend/db/src/main/scala/meta/EnumMeta.scala
app-backend/project/plugins.sbt

This PR adds a nullable field to `tiles` table -- `quality`. It also updates the corresponding data model, dao methods, and property test generators.
-~ Any new SQL strings have tests~
- Make sure the type of the new field makes sense to you
- Make sure the migration runs for you

Add image quality to tile layers

---

CHANGELOG.md
app-backend/api/src/main/scala/utils/QueryParameters.scala
app-backend/common/src/test/scala/com/implicits/Generators.scala
app-backend/datamodel/src/main/scala/Campaign.scala
app-backend/datamodel/src/main/scala/Continent.scala
app-backend/datamodel/src/main/scala/QueryParameters.scala
app-backend/datamodel/src/main/scala/TileLayerQuality.scala
app-backend/db/src/main/resources/migrations/V50__add_continent_to_campaigns.sql
app-backend/db/src/main/scala/CampaignDao.scala
app-backend/db/src/main/scala/filters/Filterables.scala
app-backend/db/src/main/scala/meta/EnumMeta.scala
app-backend/db/src/test/scala/com/azavea/rf/database/CampaignDaoSpec.scala

This PR adds a nullable `continent` column to `campaigns` table. A QP is added for this field on the `GET` request to `api/campaigns`. It also updates the data model, dao methods, enum meta, and property tests.
- Make sure the new column name and type make sense

Add a continent column to campaigns

---

CHANGELOG.md
app-backend/common/src/main/scala/com/rasterfoundry/common/color/ColorCorrect.scala

This relaxes assumptions about if an image needs to be rescaled. Before this commit there needed to be a minimum value of `0` and a maximum value of `255` to _not_ clip and stretch.
Now, if the values of a band are between `0` and `255` the image is not rescaled. This covers cases where there may not be a fully white or black pixel in the image.
Before this fix
After this fix
- On `develop` - upload a byte raster with really white areas and watch the image get blown out
- Re-assemble tile server from this PR's branch and restart service
- See that the image improved
Closes #5357

Adjust clipping logic to ignore byte rasters

---

CHANGELOG.md
app-backend/api/src/main/scala/campaign/Routes.scala
app-backend/api/src/main/scala/user/Routes.scala
app-backend/datamodel/src/main/scala/Campaign.scala
app-backend/db/src/main/resources/migrations/V52__add_ready_status_and_children_count_on_campaigns.sql
app-backend/db/src/main/scala/CampaignDao.scala
app-backend/db/src/main/scala/meta/CirceJsonbMeta.scala
app-backend/db/src/test/scala/com/azavea/rf/database/CampaignDaoSpec.scala

This PR:
- adds `children_count` field to campaigns and adds a DB trigger on `campaigns` table, so that each time an `INSERT` or a `DELETE` is performed on the table, it updates the `children_count` field of the corresponding campaign
- adds `is_ready` field to campaigns and adds a DB trigger on `annotation_projects` table, so that each time an `UPDATE` is performed and if the `campaign_id` field is not empty, plus there is a `status` change, it updates the aggregated status on the `campaigns` table of the corresponding campaign
- CI should pass since DB triggers are tested there
Below should …

Add campaign children count and status flag

---

CHANGELOG.md
app-backend/build.sbt
app-backend/common/src/test/scala/com/implicits/Generators.scala
app-backend/db/src/main/scala/TaskDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/TaskDaoSpec.scala

Y'all know what's next right
Anyway, this PR adjusts the task unlocking logic to accomplish three things:
- tasks get automatically unlocked regardless of what their current status is
- if tasks aren't in progress (labeling or validation), then we don't alter their status when we unlock them
- if tasks _are_ in progress, we get their most recent task action stamp and use its `fromStatus`. if there's no action, we revert to unlabeled (how it got into a locked state in progress with no task actions is an exercise for future us if it happens :crossed_fingers: )
The bulk of the changes are in the test to make sure that we respect the previous status unless we don't need to https://github.com/raster-foundry/raster-foundry/pull/5414/files#diff-a0c18aff8467804d0c25aee7929df7b2R1240
I used optics …

Make task unlocker even smarter

---

CHANGELOG.md
app-backend/api/src/main/scala/campaign/CampaignProjectRoutes.scala
app-backend/api/src/main/scala/campaign/Routes.scala
app-backend/api/src/main/scala/utils/QueryParameters.scala
app-backend/datamodel/src/main/scala/Campaign.scala
app-backend/datamodel/src/main/scala/QueryParameters.scala
app-backend/db/src/main/resources/migrations/V53__add_is_active_to_campaigns.sql
app-backend/db/src/main/scala/CampaignDao.scala
app-backend/db/src/main/scala/filters/Filterables.scala
app-backend/db/src/test/scala/com/azavea/rf/database/CampaignDaoSpec.scala

This PR adds an `is_active` field in the `campaigns` table to support archiving and unarchiving.
- Run migration
- Assemble the api jar, spin up servers
- Log in with the dev account and grab a token
- Test the following request, adjust the `isActive` QP to either `true` or `false`, and make sure it works:
```bash
curl --location --request GET 'http://localhost:9091/api/campaigns?isActive=true' \
--header 'Authorization: Bearer <your token>' \
```
- Make sure that property tests cover the related dao method in the above request, plus, dao methods for …

Enable archiving campaigns

---

CHANGELOG.md
app-backend/db/src/main/scala/util/Page.scala

This PR makes it so that sorting is enabled for the `children_count` field in `campaigns` table, and    for the `captured_at` field in the `annotation_projects` table.
- Make sure you have loaded the development data lately (because there are sample campaign associated with sample project)
- Assemble the api server jar and spin it up
- Log in to frontend as dev user and grab a token
- `docker-compose logs -f --tail 0 postgres`
- Make sure after making the following request, there is a `ORDER BY …

Enable sorting by childrenCount and capturedAt

---

CHANGELOG.md
app-backend/common/src/test/scala/com/implicits/Generators.scala
app-backend/datamodel/src/main/scala/AnnotationLabel.scala
app-backend/db/src/main/resources/migrations/V54__add_description_to_labels.sql
app-backend/db/src/main/scala/AnnotationLabelDao.scala

This PR adds a `description` field to `annotation_labels` table and updates it related data models, dao methods, and generators for property tests. This is to support adding label level descriptions by users.
- Make sure the new field makes sense

Add description field to annotation label

---

CHANGELOG.md
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Main.scala
app-backend/common/src/test/scala/com/implicits/Generators.scala
app-backend/db/src/main/scala/TaskDao.scala

This PR makes it so that the task unlocker includes the previous note when a task is reverted to `FLAGGED`. It also makes it so the tile server doesn't fall down if the scheduled task fails. What an oversight! 😞 
It's not clear to me why the test was passing before. There should have been a `FLAGGED` reversion in those tests somewhere... which should have failed. I'm a little bit confused.
- look at the changes and think about them, since I'm not sure how to make the failure exist in a test
Closes #5418

Include note when reverting to flagged

---

CHANGELOG.md
app-backend/api-it/src/test/resources/endpoint-scopes.csv
app-backend/api/src/main/scala/campaign/Routes.scala
app-backend/db/src/main/scala/CampaignDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/CampaignDaoSpec.scala

This PR adds an endpoint  `/campaigns/{id}/clone-owners` that returns a list of users who own clones for a given campaign.
The endpoint is a little dumb and does not de-duplicate
- Verify that CI passes and that the tests are sufficient and sensible
- If you want, create a campaign and hit the endpoint, verify you an empty list back. Add some clones and verify that the endpoint returns the owners of those clones

Add endpoint to list owners of clones of campaign

---

CHANGELOG.md
app-backend/api/src/main/scala/campaign/Routes.scala
app-backend/api/src/main/scala/user/PseudoUsernameService.scala
app-backend/api/src/main/scala/user/Routes.scala
app-backend/common/src/test/scala/com/implicits/Generators.scala
app-backend/datamodel/src/main/scala/Campaign.scala
app-backend/datamodel/src/main/scala/User.scala
app-backend/db/src/main/scala/AnnotationProjectDao.scala
app-backend/db/src/main/scala/UserDao.scala

This PR updates the campaign clone endpoint and user bulk create endpoint so that:
- when a user `A` clones a campaign from one of the existing campaigns owned by `B`, the existing campaign owner `B` will have:
- `VIEW` access to the cloned campaign
- `VIEW` and `ANNOTATE` accesses to the cloned campaign projects
- when a user `A` creates more users (`BCD...`) in bulk that are owners of the cloned campaigns:
- user `A` will have:
- `VIEW` access to the cloned campaigns
- `VIEW` and `ANNOTATE` accesses to all the cloned campaign projects
- the users `BCD...` will have:
- `VIEW` and `ANNOTATE` accesses to all the cloned campaign projects
- ~Any content changes are properly templated using …

Update campaign clone endpoint; update user bulk create endpoint

---

.bintray/.credentials
.gitignore
Jenkinsfile
Jenkinsfile.central
app-backend/build.sbt
app-backend/project/plugins.sbt
app-backend/version.sbt
docker-compose.test.yml
docker-compose.yml
scripts/cipublish

Make the following changes in-order to align the release signing / publishing workflow with that of GeoTrellis [satellite](http://github.com/geotrellis/geotrellis-server) [projects](http://github.com/geotrellis/maml):
- Replace usage of `sbt-release` with direct invocations of `sbt-sonatype` [commands](https://github.com/xerial/sbt-sonatype#commands)
- Replace `gitSnapshots` and `version.sbt` file flow with a `version` variable in `sharedSettings`
- Replace usage of `sbt-pgp` with `sbt-gpg`—use GnuPG within container image so that the builds no longer require state on build executor
- Remove `sbt-bintray` which was blocking the new workflow with `publish`
In addition, the [signing subkey](https://github.com/azavea/operations/blob/master/doc/GPG.md#signing-subkeys) was renewed out-of-band. …

Upgrade to sbt-gpg and GnuPG 2+

---

CHANGELOG.md
app-backend/api/build.sbt
app-backend/batch/build.sbt
app-backend/batch/src/main/scala/healthcheck/HealthCheck.scala
app-backend/build.sbt
app-backend/db/build.sbt
app-backend/project/plugins.sbt

This PR upgrades sbt assembly. For some reason our assembly merge strategy isn't even being applied, but upgrading sbt changes some order, so it makes the S3RangeReaderProvider visible to the service loader. That's a deeply unsatisfying outcome to this debugging adventure, so I'm opening a second issue to figure out why our merge strategy doesn't seem to be applied at all. It's pretty weird! But this fixes the immediate problem.
This makes the S3RangeReaderProvider visible to the service loader, but the GDALRasterSourceProvider is still not available. The only place where that might matter is in the raster source metadata backfill batch job, which we don't need to run anymore, so I think that's acceptable. I didn't bother removing that here because I wanted the changes to be as small as …

Upgrade sbt-assembly

---

app-backend/api/src/main/scala/user/Routes.scala

This PR updates the user bulk create endpoint, so that the cloned campaigns are shared to the created users with `VIEW` action, when `grantAccessToChildrenCampaignOwner` is set to `true` in the request body.
- Make sure you have loaded the most recent dev db dump. Run migrations if you have not done it in a while. …

Update user bulk create endpoint for ACRs

---

app-backend/db/src/main/scala/meta/CirceJsonbMeta.scala

This PR makes circejsonbmeta not throw if the json is the wrong type. I don't know what it will do in practice, but that seems good and should let doobie handle what to do with errors instead of just plain exploding.
upstreamed from work in azavea/franklin#286
- ci

Don't throw in circejsonbmeta

---

CHANGELOG.md
app-backend/api-it/src/test/resources/endpoint-scopes.csv
app-backend/api/src/main/scala/campaign/Routes.scala
app-backend/build.sbt
app-backend/common/src/test/scala/com/implicits/Generators.scala
app-backend/db/src/main/resources/migrations/V57__add_breadcrumb_tables_for_project_copying.sql
app-backend/db/src/main/scala/AnnotationLabelClassDao.scala
app-backend/db/src/main/scala/AnnotationLabelClassGroupDao.scala
app-backend/db/src/main/scala/AnnotationLabelDao.scala
app-backend/db/src/main/scala/AnnotationProjectDao.scala
app-backend/db/src/main/scala/CampaignDao.scala
app-backend/db/src/main/scala/package.scala
app-backend/db/src/main/scala/types.scala
app-backend/db/src/test/scala/com/azavea/rf/database/CampaignDaoSpec.scala

This PR makes it so that we can copy labels and label classes from children campaigns' projects to their parents campaigns' projects (matching on `capturedAt` date).
Ooh boy is this brittle. It depends on our using the `capturedAt` field in a particular way to indicate special kinds of projects, which Feels Bad :tm:. 
- verify that test in `CampaignDaoSpec` makes sense
- see if you can come up with anything else I could assert about it -- it makes me a bit nervous that it's just a length check

Copy child campaign projects' labels to parent campaigns projects

---

CHANGELOG.md
app-backend/api-it/src/test/resources/endpoint-scopes.csv
app-backend/api/src/main/scala/campaign/Routes.scala
app-backend/datamodel/src/main/scala/Task.scala
app-backend/db/src/main/scala/CampaignDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/AnnotationLabelClassDaoSpec.scala
app-backend/db/src/test/scala/com/azavea/rf/database/AnnotationLabelDaoSpec.scala
app-backend/db/src/test/scala/com/azavea/rf/database/CampaignDaoSpec.scala
app-backend/db/src/test/scala/com/azavea/rf/database/StacExportDaoSpec.scala

This pr adds the endpoint `/campaigns/{lesson_campaign_id}/random-review-task` which returns a task of type `Review` when possible.
There are some conditions on getting a task back:
- if a user has already validated a parent task, the endpoint will not return a review task for it
- if a parent task has already been validated 3 times, the endpoint will not return a review task for it
It just occurred to me while writing out this PR that maybe we don't need to check for the number of times a task has been validated since that could be controlled by only creating a certain number of review tasks and if they are all validated, they would not be returned. Thoughts?
- Verify that the tests are sensible
- CI

Implement endpoint for campaign random review task

---

app-backend/db/src/main/scala/CampaignDao.scala

`select *, annotation_projects.campaign_id ...` is changed to `select tasks.*, annotation_projects.campaign_id ...` in this PR, since the former selects all columns from `tasks` and `annotation_projects`, plus `annotation_projects.campaign_id`, and that mapping is based on types, so the annotation project ID would naturally be piped into our new data model (`annotation_projects.id` and `annotation_projects.campaign_id` are both `UUID`s), so, yea.
- 🤷‍♂️

Fix bug in drawing random review task from a campaign

---

CHANGELOG.md
Jenkinsfile
Jenkinsfile.central
app-backend/build.sbt

- Define `version` in [`ThisBuild`](https://www.scala-sbt.org/1.x/docs/Scopes.html#Scoping+by+the+subproject+axis) scope so that we can override it in Jenkinsfile.central
- Use sbt-sonatype [3.x workflow](https://github.com/xerial/sbt-sonatype#publishing-your-artifact)
See that snapshot publishing still works: http://jenkins.staging.rasterfoundry.com/job/Raster%20Foundry/job/raster-foundry/view/change-requests/job/PR-5438/6/console
See that the 1.42.0 release was successful: http://jenkins.staging.rasterfoundry.com/job/Raster%20Foundry%20Release%20Pipelines/job/Raster%20Foundry%20Maven%20Central%20Release%20Pipeline/95/console
Resolves #5433

Fix Maven Central release pipeline hanging behavior

---

app-backend/api/src/main/resources/application.conf
app-backend/api/src/main/scala/user/Auth0User.scala
app-backend/api/src/main/scala/user/Routes.scala
app-backend/api/src/main/scala/utils/Config.scala
app-backend/build.sbt
app-backend/datamodel/src/main/scala/User.scala
app-backend/project/Dependencies.scala
nginx/etc/nginx/conf.d/api.conf

This updates the bulk create endpoint to use the Auth0 import user's job so that we can create a larger amount of users without being rate-limited.
I was able to pretty consistently create 50 users at a time with this setup. Anything more than that and I would hit a 20 second timeout (that we have set in akka). So we probably want to limit the frontend to that amount.
A new environment variable is required for server startup. There is a related PR incoming in the deployment repository for that.
- Pull down an updated `.env` because there is now a new setting
- Assemble the API server
- Rebuild the `nginx-api` container: `docker-compose build nginx-api`
- Save the following `json` in a file:
```
{
"count": 50,
"peudoUserNameType": "POKEMON",
"organizationId": …
```

Refactor bulk create user endpoint to use Auth0's bulk endpoint

---

CHANGELOG.md
app-backend/db/src/main/scala/CampaignDao.scala

This PR limits returned tasks from the random tasks endpoint to tasks in projects in campaigns that share a parent but that are not owned by the requesting user.
This is _really_ hard to test, given the number of things that need to be produced to create a test case. I think it should be tested in practice instead of in an automated way. Also, the testing pain here makes me concerned in a broader sense.
- 😢

filter to a list of candidate campaigns

---

CHANGELOG.md
app-backend/db/src/main/resources/migrations/V58__add_cascade_delete_to_breadcrumbs.sql
app-backend/db/src/main/scala/CampaignDao.scala

This PR adds two optimizations discovered in testing:
- the random task endpoint should only return _unlocked_ tasks
- the `label_class_history` table shouldn't block deletes of annotation projects
- good to go with CI unless underlying cleanup goals change
Closes azavea/raster-foundry-platform#1054

Cleanup behemoth task queries

---

CHANGELOG.md
app-backend/api/src/main/scala/user/Auth0User.scala
app-backend/common/src/main/scala/utils/CogUtils.scala

Simplifies histogram generation when a COG is POSTed by always using the smallest overview to calculate histograms.
- Take a tiff and upload it to a project
- Verify that it does not time out
Closes #5443

Construct histogram from smallest overview

---

CHANGELOG.md
app-backend/api/src/main/scala/campaign/Routes.scala
app-backend/common/src/test/scala/com/implicits/Generators.scala
app-backend/datamodel/src/main/scala/Campaign.scala
app-backend/datamodel/src/main/scala/User.scala
app-backend/db/src/main/resources/migrations/V59__add_resource_link_to_campaigns.sql
app-backend/db/src/main/scala/CampaignDao.scala
app-backend/db/src/main/scala/UserDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/CampaignDaoSpec.scala

This PR adds support for campaign resource links -- a URL that points to some documentation resource for campaigns. This includes:
- a migration to add a text field `resource_link` to the campaigns table
- updates to campaign data-models
- updates to the campaign copy method so that a consumer can opt-in to copying the resource link to cloned campaigns
- updates to the expected structure of `Campaign.Clone` and `UserBulkCreate` to include a new field: `copyResourceLink: Boolean` which defaults to `false`. This allows requests to `/campaigns/{id}/clone` and `users/bulk-create` to specify if the resulting campaign copies should copy the resource link
- updates to the campaign tests to verify that the resource link is only copied when desired
- Ensure that the added test makes sense
- CI

Add support for campaign resource links

---

CHANGELOG.md
app-backend/db/src/main/scala/AnnotationLabelDao.scala
scripts/load_development_data

This PR:
- fixes the `--create` flag behavior in `load_development_data`
- makes it so that the copied back labels from child annotation projects get the correct label classes associated with them
- to be sent separately because speaking in code is hard

Copied back labels should have classes

---

app-backend/db/src/main/scala/CampaignDao.scala

This PR makes a small adjustment so that only tasks with a status of `LABELED` are returned.
Prior to this, the query works properly to return a child task of tasks that still need a review, but the query missed on ensuring that the child task returned was not one that was already validated.
I attempted to modify tests to test this but it turned out to be harder than I thought and maybe not worth it given time constraints.
The query should make more sense now...
🤷‍♂️

Make campaign task endpoint returns only labeled tasks

---

CHANGELOG.md
app-backend/api/src/main/scala/user/Routes.scala
app-backend/db/src/main/scala/AnnotationProjectDao.scala
app-backend/db/src/main/scala/CampaignDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/CampaignDaoSpec.scala

This PR updates the user bulk create endpoint so that **all** child campaign owners have access to all child campaigns (and annotation projects), no matter in which batch the users are added in.
- CI should test our use case, so take a close look to the property tests

Update user bulk create endpoint to fix ACR assignment

---

CHANGELOG.md
app-backend/api/src/main/scala/annotation-project/AnnotationProjectPermissionRoutes.scala
app-backend/datamodel/src/main/scala/ActionType.scala
app-backend/datamodel/src/main/scala/User.scala
app-backend/db/src/main/scala/AnnotationProjectDao.scala
app-backend/project/plugins.sbt

This PR adds a new `ActionType.Validate` and updates the annotation project share endpoint:
- the endpoint now takes two other optional params, `actionType` and `silent` - the former specifies if to `ActionType.Annotate` or `ActionType.Validate`; the latter specifies if to send email notification to new user or send intercom message to existing user
- if `ActionType.Annotate` is passed to `actionType` param, the endpoint removes any existing `ActionType.Validate` permission for the user with the specified email; if `ActionType.Validate`, it adds `ANNOTATE` and `VALIDATE`
- `actionType` and `silent` params are optional, so when posting, it is ok to ignore these two fields and just post the `email` field -- this will work like just assigning users to `ANNOTATE` and send notifications, which …

Update annotation project share for validation use case

---

CHANGELOG.md
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/BacksplashGeotiffReader.scala
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/BacksplashImage.scala
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/MosaicImplicits.scala
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/Parameters.scala
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/RenderableStore.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/MamlAdapter.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/implicits/RenderableStoreImplicits.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/services/MosaicService.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/services/SceneService.scala
app-backend/common/src/main/scala/com/rasterfoundry/common/color/ColorCorrect.scala
app-backend/common/src/main/scala/utils/CogUtils.scala

There are two fixes for bugs that were uncovered last week.
First - the tiff overview tag parsing now matches what is in GeoTrellis. This prevents accidentally identifying per dataset masks as overviews that can be rendered which introduced some rendering bugs.
Second - this adds a parameter to tile requests that allows for disabling auto color correction. This prevents image distortion when a user has already applied some corrections to their imagery and does not want the server to apply any changes.
With color correction enabled: 
With color correction disabled via query parameter:
- Upload a COG that you'd like to compare before/after disabling color correction
- Go to the "publish" page of the project you uploaded the COG to, make project public, and copy the ZXY URL
- Strip off any …

Add Parameter to Disable Color Correction and Fix Tag Parsing

---

CHANGELOG.md
app-backend/db/src/main/scala/ProjectDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/ProjectDaoSpec.scala

This PR updates the insert method for `ProjectDao` so that the single-band related settings from `Project.Create` are applied to the default project layer as well, since backsplash reads the mosaic definitions from layers in the `layerStore` (which makes sense).
- assemble your api jar
- grab a token and run the following to create a single band project:
```
curl --location --request POST 'http://localhost:9091/api/projects' \
--header 'Authorization: Bearer <your token>' \ …
```

Apply single band settings to project default layer on project create

---

CHANGELOG.md
app-backend/api-it/src/test/resources/endpoint-scopes.csv
app-backend/api/src/main/scala/annotation-project/AnnotationProjectTaskRoutes.scala
app-backend/api/src/main/scala/annotation-project/Routes.scala
app-backend/datamodel/src/main/scala/User.scala
app-backend/db/src/main/scala/AnnotationProjectDao.scala
app-backend/db/src/main/scala/TaskDao.scala

This PR makes changes to the backend to further support validation. From the issue:
- a new endpoint for a task that handles validation:` /annotation-projects/{id}/tasks/{id}/validate` that takes a POST request which contains the feature-collection of labels for that task.
- requires the current status of the task to be one of LABELED, VALIDATION_IN_PROGRESS, or VALIDATED. The end statuses (LABELED and VALIDATED) are included here because sometimes the DB and the front-end are not perfectly in-sync and this seems like a bad time to be overly specific. This endpoint should require a ActionType.Validate permission for the project
- updates the existing labeling endpoint `/annotation-projects/{id}/tasks/{id}/labels` so that the POST is only applied if the status of the task is one of …

Validation specific endpoint

---

CHANGELOG.md
app-backend/api/src/main/scala/user/PseudoUsernameService.scala
app-backend/datamodel/src/main/scala/PseudoUsernameType.scala

This PR adds three more categories of user-names to the `PseudoUsernameService`:
- `MoonsOfJupiter`
- `AnimalAstronauts`
- `EarthNames`
This still adds UUID segments to the usernames and keeps the old categories around for deployment independence.
- Use the corresponding PR in another repo to test this

Add more username types for bulk-creation

---

CHANGELOG.md
app-backend/api/src/main/scala/scene/Routes.scala
app-backend/batch/src/main/scala/cogMetadata/HistogramBackfill.scala

`GDALRasterSource` handles URIs in a slightly different manner and requires that we decode ingest location.

URL decode ingest location for new scenes

---

CHANGELOG.md
app-backend/http4s-util/src/main/scala/com/rasterfoundry/http4s/TracedHTTPRoutes.scala

This PR includes user ids in trace tags. ~I think since everything's running through our fancy request wrapper that this will get them into xray also, but I'll want to test in staging to be sure. I'm waiting a bit so I don't interrupt QA.~ [verified](https://console.aws.amazon.com/xray/home?region=us-east-1#/traces/1-5f459f1d-5bea70bad639fac48b137604/raw)
Please don't ask me how long it took me to debug why I wasn't seeing the user id after the first commit
- check out the linked trace from when I pushed a `test/` branch a minute ago above (or you can find it [here](https://console.aws.amazon.com/xray/home?region=us-east-1#/traces/1-5f459f1d-5bea70bad639fac48b137604/raw)) and look for `user_id` in the annotations
- extra credit for local if you're feeling like it:
- assemble backsplash …

Include user_id in trace tags

---

CHANGELOG.md
app-backend/build.sbt
app-backend/notification/src/main/scala/com/rasterfoundry/notification/intercom/NotifyIntercom.scala

This PR fixes two things in sending Intercom notifications:
- it doesn't bother attempting to decode the response as json
- it fixes the logging dependencies so that logs actually get printed
Separately, I fixed a configuration value in the dev `.env`, staging tfvars, and production tfvars.
What was wrong was:
- our configuration value was wrong, since someone deleted the Intercom admin user whose ID we were using
- that meant that we couldn't decode the response as the json we expected
- and sttp for some reason throws a NPE in that case (lol)
I don't know if the batch job should exit with an error status if notification fails. It's unclear to me the extent to which we think this error is ignorable.
- pull the env down again: `RF_SETTINGS_BUCKET=rasterfoundry-development-config-us-east-1 …

Don't panic if intercom API interaction fails

---

app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/BacksplashImage.scala
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/MosaicImplicits.scala

This PR preempts reading any imagery if an image's data footprint doesn't have an area 3.9x the size of the pixel area at the requested zoom level. I chose 3.9 because it's slightly below 4, and if an image can fill a 2x2 pixel grid, then _I guess_ we should bother rendering it (I'm not sold on this argument at all / I think the threshold could be higher). Arguably this should just be a configurable value.
For one of the sample NAIP images in Nebraska, I'm consistently timing out in the first zoom levels where I attempt to read. In both higher and lower zooms it's fine. I have no idea why but I've done so little that I feel like it has to be unrelated to what I've done here.
- assemble backsplash
- fire up your servers
- set `tile_visibility = 'PUBLIC'` for project …

Return empty tiles for low zooms when appropriate

---

CHANGELOG.md
app-backend/batch/src/main/scala/stacExport/WriteStacCatalog.scala

This PR sends successful notifications with a link to exports for the linked project when exports succeed, or two kinds of messages
with an invitation to contact us if exports fail.
- assemble batch and servers `./sbt`, then `;batch/assembly;api/assembly;backsplash-server/assembly`
- start your servers and also bring up groundwork
- create an export for a groundwork project with the network tab open and grab the export's id
- `./scipts/console batch bash`
- `java -cp /opt/raster-foundry/jars/batch-assembly.jar com.rasterfoundry.batch.Main write_stac_catalog <your export id>`
- when it's done, you should have a nice message in Groundwork waiting for you 
Closes raster-foundry/annotate#655

Send notifications on export success or two kinds of errors

---

CHANGELOG.md
app-backend/api/src/main/scala/scene/Routes.scala
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/BacksplashImage.scala
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/package.scala
app-backend/batch/src/main/scala/cogMetadata/HistogramBackfill.scala
app-backend/batch/src/main/scala/cogMetadata/RasterSourceMetadataBackfill.scala
app-backend/build.sbt
app-backend/common/src/main/scala/BacksplashGeotiffReader.scala
app-backend/common/src/main/scala/utils/CogUtils.scala
app-backend/db/src/main/scala/SceneDao.scala

This PR makes it so that we spin off fetching GeoTiff info for new COGs that have been posted into a separate thread that doesn't block the server's response. It picks up the `Blocker` added in #5465 and uses it to get the GeoTiffInfo and moves the GDALRasterSource calls out of that blocker and back into the default execution context (but still wrapped in `F`).
- Here's a nice json for you -- save it in `scene.json`
```json
{
"id": null,
"visibility": "PRIVATE",
"tags": [],
"datasource": "e4d1b0a0-99ee-493d-8548-53df8e20d2aa",
"sceneMetadata": {},
"name": "Test scene",
"owner": null,
"tileFootprint": null,
"dataFootprint": null,
"metadataFiles": [],
"images": [],
"thumbnails": [],
"ingestLocation": "s3://rasterfoundry-development-data-us-east-1/cog-pa_m_4208063_sw_17_1_20150727.tif", …
```

Add GeoTiff info on COG post

---

CHANGELOG.md
app-backend/api/src/main/scala/annotation-project/AnnotationProjectTaskRoutes.scala
app-backend/db/src/main/scala/TaskDao.scala
docker-compose.yml
docs/swagger/spec.yml

This PR moves the wait for the task grid into a blocker. This way it doesn't really matter how big the task grid area is, you'll get a response pretty quickly and later the server will finish what it's up to.
The log message for tasks having been inserted shows up in the transactor pool, so I think it's probably the case that the fixed
thread pool in use in `AnnotationProjectTaskRoutes` creates four threads that largely just hang out and wait on db responses. I think that's probably fine.
Also, I picked a fixed thread pool because that's what we do for scenes, but maybe since these threads are just going to be hanging out waiting for database IO it should be a cached thread pool. (Unlike the scenes work, where we're doing more work to read data from S3 and calculate histograms, etc.) I …

Return before task grid is ready

---

CHANGELOG.md
app-backend/common/src/test/scala/com/implicits/Generators.scala
app-backend/datamodel/src/main/scala/LabelVoteType.scala
app-backend/datamodel/src/main/scala/Task.scala
app-backend/datamodel/src/main/scala/TaskReviewStatus.scala
app-backend/db/src/main/resources/migrations/V61__add_review_status.sql
app-backend/db/src/main/scala/MVTLayerDao.scala
app-backend/db/src/main/scala/TaskDao.scala
app-backend/db/src/main/scala/meta/CirceJsonbMeta.scala
app-backend/db/src/main/scala/meta/EnumMeta.scala
app-backend/db/src/test/scala/com/azavea/rf/database/PropTestHelpers.scala
app-backend/db/src/test/scala/com/azavea/rf/database/TaskDaoSpec.scala

This PR:
- improves type of `reviews` field on `tasks`
- adds `review_status` field, which is optional, to `tasks`
- updates the method for getting task grid as MVT layer to include only `LABEL` type of tasks
- adds a DB trigger so that `review_status` on `LABEL` tasks will update based on changes in `reviews` field on the corresponding `REVIEW` tasks.
- Make sure the tests make sense

Add review status to tasks; Update MVTLayerDao

---

CHANGELOG.md
app-backend/api/src/main/scala/campaign/CampaignProjectRoutes.scala
app-backend/api/src/main/scala/campaign/Routes.scala
app-backend/db/src/main/scala/AnnotationProjectDao.scala

This PR makes the routes for listing annotation projects and getting an annotation project _behind `/campaigns/id/projects`_ use campaign authorization instead of annotation project authorization.
I opted for "instead of" rather than "in addition to" because I thought the desired behavior on the detail route if you're authorized for the project but not the campaign was pretty unclear. I can be talked into changing it to "in addition to" though.
I had a lot of trouble testing locally. When I create a user in the dev tenant locally I end up getting a bunch of 500s from the API server, which made it really tough to get a second user to log in as to make things work.
- inspection I guess. You should be able to verify that:
Closes raster-foundry/annotate#972

Use campaign authorization for annotation projects in /campaign/ routes

---

CHANGELOG.md
app-backend/api/src/main/scala/scene/Routes.scala

GeoTiffRasterSources and GDALRasterSources have different ideas about encoded URLs. This PR (which I'm opening on behalf on @notthatbreezy because he's busy) uses the non-decoded URL to get all the scene metadata. It fixes a broken production situation where no one can see scenes that they upload since 1.52.0.
I just ran this upload based on the deployed staging branch
- do an upload in staging GW
Closes #5491 
Closes raster-foundry/annotate#1037

Use non-decoded URLs for the GeoTiffRasterSource

---

CHANGELOG.md
app-backend/api-it/src/test/resources/endpoint-scopes.csv
app-backend/api/src/main/scala/annotation-project/AnnotationProjectTaskRoutes.scala
app-backend/api/src/main/scala/campaign/Routes.scala
app-backend/api/src/main/scala/utils/QueryParameters.scala
app-backend/datamodel/src/main/scala/QueryParameters.scala
app-backend/db/src/main/scala/TaskDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/TaskDaoSpec.scala

This PR:
- adds a `/api/campaigns/<campaignId>/tasks` endpoint that accepts all the task query parameters
- removes the `format=summary` query parameter for task lists, since we no longer use it now that we have the MVT endpoint
- confirm tests make sense
Closes raster-foundry/annotate#976

Allow listing tasks for campaigns

---

CHANGELOG.md
app-backend/batch/src/main/scala/stacExport/DatabaseIO.scala
app-backend/batch/src/main/scala/stacExport/ExportData.scala
app-backend/batch/src/main/scala/stacExport/Utils.scala
docker-compose.yml

This PR makes it so that we can see the exported task statuses in our label items.
This should help us in the future if we get confused about geometries. I was confused about whether the geometry in the STAC export was supposed to refer just to the labeled tasks, but the Groundwork UI doesn't specify any statuses so we're exporting all the tasks.
- create a STAC export with your local Groundwork
- `./scripts/console batch "java -cp /opt/raster-foundry/jars/batch-assembly.jar com.rasterfoundry.batch.Main write_stac_catalog <your export ID>"
- download the export (you can find it with a search for `under prefix` in the logs)
- examine the label item's `groundwork:taskStatuses` property
- set a specific status in the db -- `update stac_exports set task_statuses = '{ "LABELED" }' where id = …

Include task statuses in STAC label items

---

CHANGELOG.md
app-backend/api-it/src/test/resources/endpoint-scopes.csv
app-backend/api/src/main/scala/annotation-project/AnnotationProjectPermissionRoutes.scala
app-backend/api/src/main/scala/campaign/CampaignPermissionRoutes.scala
app-backend/api/src/main/scala/campaign/Notifications.scala
app-backend/api/src/main/scala/campaign/Routes.scala
app-backend/api/src/main/scala/project/Routes.scala
app-backend/api/src/main/scala/scene/Routes.scala
app-backend/api/src/main/scala/utils/IntercomNotifications.scala
app-backend/db/src/main/scala/CampaignDao.scala

This PR adds simple sharing endpoints for campaigns. It abstracts the sharing functionality into an `IntercomNotifications` trait that we can re-use, but it doesn't abstract the procedure to actually do the sharing, so there's a lot of copy-pasta.
- I think tests are fine? I think we'll have a better idea of how this works once we need to use it
Closes raster-foundry/annotate#973

Add simplified sharing endpoints for campaign

---

CHANGELOG.md
app-backend/api/src/main/scala/utils/QueryParameters.scala
app-backend/common/src/test/scala/com/implicits/Generators.scala
app-backend/datamodel/src/main/scala/QueryParameters.scala
app-backend/db/src/main/scala/filters/Filterables.scala
app-backend/db/src/test/scala/com/azavea/rf/database/PropTestHelpers.scala

This PR adds support for the `campaignId` query parameter on the `listStacExport` endpoint. It appears as though the database is already setup with support for campaign IDs, so all that was required here was passing parameters through.
First time PRing against this project in a while. Might be good to double check that I'm making all and only necessary changes.
Run tests or try adding a `campaignId` query parameter on a STAC list request.
Closes https://github.com/raster-foundry/annotate/issues/975 (not sure how to close in another repo)

Accept campaignId query parameter on listStac endpoint

---

CHANGELOG.md
app-backend/api/src/main/scala/campaign/Routes.scala
app-backend/datamodel/src/main/scala/AnnotationLabelClassGroup.scala
app-backend/datamodel/src/main/scala/Campaign.scala
app-backend/db/src/main/resources/migrations/V63__add_campaigns_to_label_class_groups.sql
app-backend/db/src/main/scala/AnnotationLabelClassGroupDao.scala
app-backend/db/src/main/scala/AnnotationProjectDao.scala
app-backend/db/src/main/scala/CampaignDao.scala

This PR optionally associates `AnnotationLabelClassGroup`s with `Campaign`s and makes `AnnotationProject` associations optional as well. Additionally, campaign-associated `AnnotationLabelClassGroup`s are now returned via `/campaign` endpoints
These changes are largely covered by existing tests
Closes https://github.com/raster-foundry/annotate/issues/988

Associate label class groups with campaigns

---

CHANGELOG.md
app-backend/datamodel/src/main/scala/Campaign.scala
app-backend/db/src/main/resources/migrations/V64__add_campaign_status_trigger.sql
app-backend/db/src/main/scala/CampaignDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/CampaignDaoSpec.scala

This adds two fields to campaigns when they're returned from the database:
- task status summary: an aggregation of task status summaries from all annotation projects that belong to a campaign
- image count: the number of annotation projects that belong to a campaign
The summary is updated via a trigger which is fired any time that the summary of an annotation project is updated. This is adapted from the trigger already present on annotation projects for updating summary fields
The image count is obtained via a join from the select for annotation projects. This is a left outer join in order to preserve any nulls (campaigns without any annotation projects). All nulls are replaced with a `0`.
~- [ ] New tables and queries have appropriate indices added~
~- [ ] Any content changes are …

Add task status summaries and image counts to campaigns

---

CHANGELOG.md
app-backend/.scalafmt.conf
app-backend/api-it/src/test/resources/endpoint-scopes.csv
app-backend/api/src/main/scala/annotation-project/AnnotationProjectTaskRoutes.scala
app-backend/api/src/main/scala/annotation-project/Routes.scala
app-backend/api/src/main/scala/utils/QueryParameters.scala
app-backend/common/src/test/scala/com/implicits/Generators.scala
app-backend/datamodel/src/main/scala/QueryParameters.scala
app-backend/datamodel/src/main/scala/TaskStatus.scala
app-backend/db/src/main/resources/migrations/V65__Add_split_to_task_statuses.sql
app-backend/db/src/main/scala/MVTLayerDao.scala
app-backend/db/src/main/scala/TaskDao.scala
app-backend/db/src/main/scala/filters/Filters.scala
app-backend/db/src/test/scala/com/azavea/rf/database/PropTestHelpers.scala
app-backend/db/src/test/scala/com/azavea/rf/database/TaskDaoSpec.scala

This PR allows users to split a task into four tasks while keeping annotations.
I checked `ReadTasks` scope because it would be a serious drag to need write permissions or someone with more authority in order to split tasks while working on something. I can be talked into `CreateTasks` but I'm not 100% sure what permissions look like for people who've had projects shared with them.
- test as part of raster-foundry/annotate#1057
Helps with raster-foundry/annotate#347

Allow users to split tasks with the API

---

app-backend/batch/src/main/scala/removeScenes/RemoveScenes.scala
app-backend/db/src/main/resources/migrations/V67__add_fk_indices_in_scene_delete_tree.sql

This PR changes the scene delete query from a self join to a `delete where id in (...)`. the self join worked fine locally but with the size of the staging table (which is smaller than the prod table) took... a number of hours for a single week. Using the list of ids, Sentinel-2 scene deletion for a month took a few minutes, and Landsat 8 took about a minute.
It also includes the changes from #5507 to take down migration 67 since it was 100% redundant 😢 
- ~Description of PR is in an appropriate section of the [changelog](https://github.com/raster-foundry/raster-foundry/blob/develop/CHANGELOG.md) and grouped with similar changes if possible~ not user-facing
- assemble batch jar
- bring up database and memcached
- delete some landsat 8 scenes to make sure the sql syntax is correct: …

Improve scene delete query

---

CHANGELOG.md
app-backend/api/src/main/scala/Main.scala
app-backend/api/src/main/scala/Router.scala
app-backend/api/src/main/scala/annotation-project/AnnotationProjectPermissionRoutes.scala
app-backend/api/src/main/scala/campaign/CampaignPermissionRoutes.scala
app-backend/api/src/main/scala/user/Auth0User.scala
app-backend/db/src/main/scala/AnnotationProjectDao.scala

This PR makes it so that we only ever create a single `IntercomNotifier`, which does enough to resolve implicits that we don't get a null pointer exception when we share with existing users.
**hide whitespace changes in review** scalafmt got way too excited
There's still some kind of issue with `akka-streams` and an unsubscribed response entity that I'm working out, but this at least solves the immediate problem of "always error".
I believe this will also require some frontend changes to report the information about which email addresses had unsuccessful shares, but I don't think we know what that should look like or if that's information that we will want that we're not worried about exposing to users. Since the errors were the result of NPEs for existing users only, I don't think there …

Only create one intercom notifier

---

CHANGELOG.md
app-backend/api/src/main/scala/user/Routes.scala
app-backend/db/src/main/scala/CampaignDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/CampaignDaoSpec.scala

This PR adds the campaign count and campaign share count to the limits endpoint. It also adds property tests to the new dao method.
I'd recommend hiding the white space changes when reviewing.
- New property tests should pass
- `GET` to `/api/users/me/limits` should include campaign count and campaign share account entries
Closes https://github.com/raster-foundry/groundwork/issues/1125

Add campaign to limits endpoint

---

CHANGELOG.md
app-backend/api-it/src/test/resources/endpoint-scopes.csv
app-backend/api/src/main/scala/annotation-project/AnnotationProjectTaskRoutes.scala
app-backend/api/src/main/scala/annotation-project/Routes.scala
docs/swagger/spec.yml

Rewriting labels currently requires `DELETE` + `POST`. This changes the `POST` to a `PUT` and transactionally handles deletion/overwrite
`POST`s will need to be changed to `PUT`s in groundwork
- Run integration tests
- Throw a `PUT` at the new endpoints
Closes #1105

Make label addition idempotent

---

CHANGELOG.md
app-backend/datamodel/src/main/scala/AnnotationProject.scala
app-backend/datamodel/src/main/scala/Campaign.scala
app-backend/project/Dependencies.scala

This PR upgrades GeoTrellis to 3.5.1. This release has already been tested via a snapshot.
I'd push a test branch but staging is messy right now (or maybe not anymore?), so I think we should rely on the previous test with the snapshot
This PR also includes two small convenience fixes based on work in gkeeper -- namely, that `Campaign.Create`s don't have an encoder, and that there's no easy conversion from `AnnotationProjectWithRelatedAndLabelClassSummary` to `AnnotationProject`
- trust the last test
Closes #5508

Upgrade gt to 3.5.1

---

CHANGELOG.md
app-backend/api/src/main/scala/annotation-project/AnnotationProjectTaskRoutes.scala

this PR removes the check to make sure that the user attempting to unlock the task is the person who locked it. That made sense in a world where we trusted that locks would always be deleted, but in a world where sometimes locks linger for extended periods despite our repeated efforts to stymie that behavior, it's important for users working on a labeling project to be able to unlock each others' tasks.
- get rid of the condition attached to disabling the unlock button in Groundwork (just set [this](https://github.com/raster-foundry/groundwork/blob/develop/src/pages/BasicProjectDetails/Overview/TaskMap/Menu.tsx#L188) to false)
- bring up groundwork locally pointing to local RF servers **on the RF `develop` branch**
- pick a user id for someone who isn't the dev user and lock a task in one …

Remove unnecessary authorization check from unlocking tasks

---

CHANGELOG.md
app-backend/datamodel/src/main/scala/Scope.scala
app-backend/datamodel/src/test/scala/ScopeSpec.scala

This PR updates Groundwork user scopes so that annotation project creation is unlimited and campaign creation has a limit of 10 campaigns. It also adds unit tests expressing this expectation.
- Run tests
Closes raster-foundry/groundwork#1136

Add and test unlimited project / 10 campaign scopes

---

CHANGELOG.md
app-tasks/rf/src/rf/models/annotation_project.py

This PR makes our python data-model aware of the existence of the `campaignId` field so that it doesn't get blown away during upload processing.
- TKTK
Closes #XXX

Update annotation_project.py with campaignId

---

CHANGELOG.md
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Main.scala
app-backend/common/src/main/resources/reference.conf
app-backend/db/src/main/scala/Config.scala
app-backend/db/src/main/scala/TaskDao.scala

Two things were causing the task unlocking to behave abnormally:
- the way we were getting the advisory lock meant that sometimes a transaction could be waiting on a lock almost indefinitely
- the task unlocker failed when the "from status" of the most recent task action was the same as the current status when labeling/validating in progress
To fix the lock acquiring we switched to a `pg_try_advisory_xact_lock` which attempts to get a lock, if it can't then it returns false and the rest of the unlocking is skipped. If it can acquire a lock then it holds the lock until the transaction is complete.
To fix the "from status" issue we filter out previous actions where the from status was equal.
Tested in staging

Update Unlocking Behavior

---

CHANGELOG.md
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/middleware/RequestRewriteMiddleware.scala

This used to be in nginx, but we stopped deploying the
nginx sidecar container recently and this needs to happen
in application code now.
See that the same tile loads either with or without the tiles prefix
- see demo

Add rewrite for `/tiles/` prefixed tile requests

---

CHANGELOG.md
app-backend/api-it/src/test/resources/endpoint-scopes.csv
app-backend/api/src/main/scala/tasks/Routes.scala
app-backend/common/src/main/resources/reference.conf
app-backend/common/src/test/scala/com/implicits/Generators.scala
app-backend/datamodel/src/main/scala/TaskSession.scala
app-backend/datamodel/src/main/scala/TaskSessionType.scala
app-backend/db/src/main/resources/migrations/V67__Add_task_session.sql
app-backend/db/src/main/scala/Config.scala
app-backend/db/src/main/scala/TaskSessionDao.scala
app-backend/db/src/main/scala/meta/EnumMeta.scala
app-backend/db/src/test/scala/com/azavea/rf/database/TaskSessionDaoSpec.scala

This PR adds the following for task sessions
- Assemble backend, run migration, spin up frontend and backend, grab a token
- From the DB, grab a task's ID that has `UNLABELED` status
- Create a task session:
```
curl --location --request POST 'http://localhost:9091/api/tasks/<task_id>/sessions' \
--header 'Authorization: Bearer <your_token>' \
--data-raw '{
"sessionType": "LABEL_SESSION"
}'
```
- List task sessions for this task
```
curl --location --request GET 'http://localhost:9091/api/tasks/<task_id>/sessions' \
--header 'Authorization: Bearer <your_token>' \
```
- Get details of a session:
```
curl --location --request GET …
```

Add TaskSession data model and basic endpoints

---

.gitignore
CHANGELOG.md
app-backend/api-it/src/test/resources/endpoint-scopes.csv
app-backend/api/src/main/scala/tasks/Routes.scala
app-backend/db/src/main/scala/TaskDao.scala
app-backend/db/src/main/scala/TaskSessionDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/PropTestHelpers.scala
app-backend/db/src/test/scala/com/azavea/rf/database/TaskDaoSpec.scala
app-backend/db/src/test/scala/com/azavea/rf/database/TaskSessionDaoSpec.scala

This PR adds an endpoint for getting a random task session with the same QPs on the previous random task endpoint.
- Run migrations, assemble apis, spin up server, grab a token
- Grab an annotation project id
**START OF ATTENTION: `curl` command updated**
- Replace the `<id>` and `<token>` in the following. It should return a random task's session:
```
curl --location --request GET 'http://localhost:9091/api/tasks/random-session?status=UNLABELED&annotationProjectId=<annotation project ID>' \
--header 'Authorization: Bearer <your token>'
```
**END OF ATTENTION: `curl` command updated**
- Look at the new property test. Make …

Support random task session

---

CHANGELOG.md
app-backend/common/src/test/scala/com/implicits/Generators.scala
app-backend/datamodel/src/main/scala/AnnotationLabelClass.scala
app-backend/datamodel/src/main/scala/AnnotationLabelClassGroup.scala
app-backend/db/src/main/scala/AnnotationLabelClassDao.scala
app-backend/db/src/main/scala/MVTLayerDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/AnnotationLabelClassDaoSpec.scala
app-backend/db/src/test/scala/com/azavea/rf/database/AnnotationLabelClassGroupDaoSpec.scala

- adds `annotation_task_id` and `label_class_id` to the MVT data for labels
- removes `isActive` from the create case classes for label classes and groups
- This will be best tested by an accompanying PR

Include more label MVT fields

---

CHANGELOG.md
app-backend/datamodel/src/main/scala/AuthResult.scala
app-backend/db/src/main/scala/AnnotationProjectDao.scala

This PR makes it so that the default `.authorize` function on annotation projects uses campaign authorization if the project is in a campaign.
It's pushed as a `test/` branch -- you can see that it's working if you load up the deploy preview for https://github.com/raster-foundry/groundwork/pull/1195 and look at one of the multi-image campaigns. All the `/actions` requests are successful, while on `develop`, they all fail
(as long as 
- load up the deploy preview for the linked Groundwork PR above
- open your network tab
- navigate to a multi-image campaign
- all the `/actions` requests should be successful
- load up the single image campaign
- you should be able to see the MVT layers
Closes raster-foundry/groundwork#1155

Always authorize annotation projects via campaign

---

CHANGELOG.md
app-backend/api/src/main/scala/annotation-project/Routes.scala
app-backend/db/src/main/scala/TaskDao.scala

This PR fixes one thing I missed in #5536 -- in the random task endpoint, we don't get projects with `.authorize`, we call the `authQuery` directly. Since annotation projects in campaigns aren't shared directly, this was correctly not finding any authorized projects when the annotationProjectId query parameter was included.
This PR changes the project id listing so that it checks all of:
- directly authorized projects for the user
- project ids in the requested campaign if the user is allowed to view that campaign
- the requested project id if it exists and the user is allowed to see its parent campaign
- test with raster-foundry/groundwork#1195

Cover all the bases on random task project listing and actions requests

---

CHANGELOG.md
app-backend/api/src/main/scala/campaign/Routes.scala
app-backend/api/src/main/scala/utils/QueryParameters.scala
app-backend/datamodel/src/main/scala/QueryParameters.scala
app-backend/datamodel/src/main/scala/Task.scala

This PR adds a QP to the random task fetching endpoint for campaigns to assign ACRs. 
- Follow instructions here: https://github.com/azavea/earthrise-ibm/pull/37
Closes https://github.com/azavea/earthrise-ibm/issues/7

Assign ACRs in campaign random task endpoint

---

CHANGELOG.md
app-backend/api-it/src/test/resources/endpoint-scopes.csv
app-backend/api/src/main/scala/campaign/CampaignProjectRoutes.scala
app-backend/api/src/main/scala/campaign/Routes.scala
app-backend/datamodel/src/main/scala/AnnotationProject.scala
app-backend/datamodel/src/main/scala/LabelClassSummary.scala
app-backend/db/src/main/scala/AnnotationLabelDao.scala
app-backend/db/src/main/scala/AnnotationProjectDao.scala
app-backend/db/src/main/scala/CampaignDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/AnnotationLabelDaoSpec.scala
app-backend/db/src/test/scala/com/azavea/rf/database/CampaignDaoSpec.scala
app-backend/db/src/test/scala/com/azavea/rf/database/PropTestHelpers.scala

This PR adds an endpoint for getting label class group summary on campaign level.
- property tests should pass
- GET to `/api/campaigns/{campaignId}/label-class-summary` should return summary if you have labels created using campaign level classes
Closes https://github.com/raster-foundry/groundwork/issues/1164

Endpoint for campaign label class group summary

---

CHANGELOG.md
app-backend/batch/src/main/scala/stacExport/DatabaseIO.scala
app-backend/batch/src/main/scala/stacExport/ExportData.scala
app-backend/batch/src/main/scala/stacExport/StacFileIO.scala
app-backend/batch/src/main/scala/stacExport/Utils.scala
app-backend/batch/src/main/scala/stacExport/WriteStacCatalog.scala
app-backend/batch/src/main/scala/stacExport/v2/CampaignExport.scala

This PR makes it so that in v1 STAC exports, if we don't have a `project` that backs the annotation project (as is the case with SpaceNet projects), we fall back to creating a source item from the tile layers linked to the annotation project.
It doesn't do the same in campaign exports yet. Similar changes are necessary, but I'll get to them in the morning. With the v1 changes as a model, campaign export changes should be a breeze.
I didn't create a tile json for the item. I think it might be valuable to change the role to something other than data though, since that will maybe help differentiate the types of source assets for people who have project-less and project-ful exports.
- assemble batch, api-server, backsplash, bring up rf and groundwork -- from `sbt` shell in `app-backend`, …

Make RF project-less annotation projects exportable

---

CHANGELOG.md
app-backend/akkautil/src/main/scala/Authentication.scala
app-backend/akkautil/src/main/scala/CommonHandlers.scala
app-backend/api-it/src/test/scala/ScopeSpec.scala
app-backend/api/src/main/resources/application.conf
app-backend/api/src/main/scala/annotation-project/Routes.scala
app-backend/build.sbt
docker-compose.test.yml

This PR does four important things:
1. exposes the SCOPE_IT_API_HOST in the docker-compose file, in case you think that might be what's going horribly wrong with the scopes tests
2. memoizes the result of JWT verification for 1 minute at a time
3. adds retrying to JWT verification, so that when we randomly fail due to a read timeout in seemingly 0 seconds (something something java sockets) we can try again (up to10 times)
computers were a mistake
why do this now? `develop` builds are failing and I don't want to be debugging this problem during / right before the planned maintenance window next week. It's stressful enough debugging flaky CI without that kind of time pressure.
- CI
Closes #5529

Make authentication in testing a bit more resilient

---

CHANGELOG.md
app-backend/db/src/main/scala/ProjectLayerScenesDao.scala

This PR gets the exterior ring of the scene footprint union before passing anything off to the `ST_MakeGrid` function. Locally, it worked _fine_, so probably it won't cause the db to explode again? But I'm including upload testing in the next release issue, which will eventually reference this PR.
We tested with a Sentinel-2 COG that previously wound up with holes, and it doesn't anymore.
- paired / demoed
Closes #1203

get exterior ring of scene footprints

---

CHANGELOG.md
app-backend/batch/src/main/scala/groundwork/CreateTaskGrid.scala

This PR updates the `run()` method in `CreateTaskGrid` class of GroundWork batch job, which handles intercom message sending in the end, so that it sends a link to the campaign's image overview UI if a project/image within it is successfully processed. If the processed project is not associated with any campaign, it will send the project overview URL instead.
- Push up a test branch
- When the test branch is deployed to staging, open up GroundWork staging
- Create a campaign using the campaign creation …

Use campaign URL in intercom message when applicable

---

CHANGELOG.md
app-backend/db/src/main/scala/ProjectLayerScenesDao.scala

This PR updates the query used to generate the data footprint that is passed to the ST_MakeGrid UDF.
Previously, a data_footprint with inner-rings due to NODATA (regardless of correctness) would cause tasks to also have those holes.
This PR ensures all interior rings are removed from the (multi)polygon data footprint before it is passed to ST_MakeGrid.
I can share with you the project generated with a proper grid using the test branch associated with this PR

Add multi-polygon safe inner ring removal to grid process

---

CHANGELOG.md
app-backend/db/src/main/scala/AnnotationLabelClassGroupDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/AnnotationLabelClassGroupDaoSpec.scala

To promote annotation projects to campaigns, we need to copy the label class groups to the campaigns we create. However, we can't edit the campaign id on label class groups currently, so that's impossible. This PR fixes that.
- use raster-foundry/gkeeper#13 to bundle an annotation project to a campaign while the test/ branch for this PR is deployed

Make campaign id editable for label class groups

---

CHANGELOG.md
app-backend/db/src/main/scala/AnnotationProjectDao.scala

This PR updates the annotation project `GET` endpoint so that:
- if it has a `campaignId`, it returns label class summary based on the label group(s) attached to the campaign
- otherwise, it returns the label class summary based on label group(s) attached to the project
- A `test` branch should be live on staging now, so follow the instructions here https://github.com/raster-foundry/groundwork/pull/1265 to test
- Then manually go to `/app/project-list` in GW and select a project not attached to any …

Update annotation project GET endpoint

---

CHANGELOG.md
app-backend/db/src/main/resources/migrations/V70__cascade_delete_class_group_on_campaign_delete.sql

This PR adds a migration to update the constraints on `annotation_label_class_groups` table, so that when a campaign is deleted, the corresponding label class groups are also deleted, which will make campaign deletion happy.
- ~ Any new SQL strings have tests~
- `./scripts/migrate migrate` should work
- `./scripts/psql` and then `\d annotation_label_class_groups`, it should show the updated constrains on the `campaign_id` field of this table
- connect GW frontend to RF backend, and delete a campaign that has class definition -- it …

Add migration to cascade delete label class group on campaign deletion

---

CHANGELOG.md
app-tasks/rf/src/rf/utils/io.py

This PR updates the upload method from boto3 that we use to upload a processed scene to S3 after cogification.
- I pushed a `test` branch of this change to staging, which we may use directly to test this PR. If by the time of review, staging is overwritten, feel free to push a test branch again.
- Grab a large geotif on S3 (>5GB?). If you don't have one handy, I'd suggest using the ingest location attached to this scene: `38c78971-2bd9-4160-ae3e-9bee3d1cded8` in prod DB.
- Go to RF staging, select …

Update boto3 file upload method to support uploading large COG after processing

---

CHANGELOG.md
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/BacksplashImage.scala
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/MosaicImplicits.scala
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/Parameters.scala
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/RenderableStore.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/MamlAdapter.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/implicits/RenderableStoreImplicits.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/services/MosaicService.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/services/SceneService.scala
app-backend/common/src/main/scala/com/rasterfoundry/common/color/ColorCorrect.scala

This PR:
- removes the `disableAutoCorrect` QP
- simplifies the color correction logic in backsplash
- I pushed a `/test` branch up so staging should reflect the changes in this PR; feel free to push `test/asu/simplify-color-correct` again in case staging is overwritten
- Go to GroundWork staging -- make sure the recent images show up just fine
- Upload the image in question in [here](https://azavea.slack.com/archives/C089LBS6S/p1613585378118400?thread_ts=1613573510.106100&cid=C089LBS6S) in GW and make …

Simplify backsplash color correct

---

CHANGELOG.md
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/BacksplashImage.scala
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/MosaicImplicits.scala
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/Parameters.scala
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/RenderableStore.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/MamlAdapter.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/implicits/RenderableStoreImplicits.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/services/MosaicService.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/services/SceneService.scala
app-backend/datamodel/src/main/scala/Task.scala
app-backend/db/src/main/scala/TaskDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/TaskDaoSpec.scala
scripts/cibuild

This PR:
- restores the `disableAutoCorrect` param, since our color correction darkened some client imagery
- lets tasks with parents through in two methods in TaskDao, since split tasks have parents
`test/` branch incoming
- Create a spacenet campaign
- open a task
- split it
- label a split-result task
- Confirm the campaign level validation button is enabled and takes you to a split-result task to validate
- download an image or two (not single band since that's unaffected) from the [Slack thread](https://azavea.slack.com/archives/C089LBS6S/p1615305867067800?thread_ts=1615298602.064900&cid=C089LBS6S)
- create lessons with the images you've downloaded
- view the tiles in the lesson
- view the imagery in QGIS
- compare, they should be very similar and the tiles in the lesson shouldn't be …

Restore disableAutoCorrect param and remove superfluous task filtering

---

CHANGELOG.md
app-tasks/rf/requirements.txt
app-tasks/rf/src/rf/utils/cog.py
app-tasks/rf/src/rf/utils/footprint.py

This PR updates the upload processing task to skip the cogification if the uploaded image is already a cog. 
update: added the `strict=True` falg to cog validation, which will return false for cogs that don't have overviews 
- To make this work, I needed to install `rio-cogeo` which required updating rasterio from 1.1.6 to 1.1.7
- If the upload image is already a cog (and therefore cogification is skipped), I added a statement to the log indicating so
- I changed the format that we specify the web mercator crs in `footprint.py` to avoid some deprecation warnings from pyproj
1. start the server: `./scripts/server`
2. export a JWT auth token `export JWT_AUTH_TOKEN=[the token]`
3. Test non-cog input:
- create upload json file:
`upload-non-cog.json`
```
{
"uploadStatus": "uploaded", …
```

Skip cogification if upload is already a cog

---

CHANGELOG.md
app-backend/api/src/main/scala/annotation-project/Routes.scala
app-backend/api/src/main/scala/campaign/CampaignProjectRoutes.scala
app-backend/api/src/main/scala/campaign/Routes.scala
app-backend/api/src/main/scala/utils/QueryParameters.scala
app-backend/datamodel/src/main/scala/AnnotationProject.scala
app-backend/datamodel/src/main/scala/QueryParameters.scala
app-backend/db/src/main/resources/migrations/V71__add_is_active_to_annotation_projects.sql
app-backend/db/src/main/resources/migrations/V72__add_index_to_is_active_on_annotation_project.sql
app-backend/db/src/main/scala/AnnotationProjectDao.scala
app-backend/db/src/main/scala/TaskDao.scala
app-backend/db/src/main/scala/filters/Filterables.scala
app-backend/db/src/test/scala/com/azavea/rf/database/AnnotationProjectDaoSpec.scala
app-backend/db/src/test/scala/com/azavea/rf/database/CampaignDaoSpec.scala
app-tasks/rf/src/rf/models/annotation_project.py

This PR:
- adds a migration to add `is_active` field to `annotation_projects`
- updates data model, dao methods, and added QP as a result of adding this field
- makes campaign delete async
- makes annotation project delete async
- adds property tests for the QPs on annotation project and on campaign
- updates data model of annotation project in our cogification workflow
- Push up a `test` branch
- Follow instructions in https://github.com/raster-foundry/groundwork/pull/1341 should cover it

Make campaign and annotation project deletion async

---

CHANGELOG.md
app-tasks/rf/src/rf/utils/footprint.py

This PR changes how we construct the projections before calculating the footprints.
Somehow, _somehow_, that was the explanation for why the footprints got all wonky.
mobbed, no review
- mobbed, no testing
Closes raster-foundry/groundwork#1347

Fix bad footprint projection

---

CHANGELOG.md
app-backend/batch/src/main/scala/stacExport/WriteStacCatalog.scala
app-backend/batch/src/main/scala/stacExport/v2/CampaignExport.scala

Closes [raster-foundry-platform #1221](https://github.com/azavea/raster-foundry-platform/issues/1221)
This PR changes the campaign STAC export to use tile layers in image assets href whether or not the annotation project is connected to a scene. 
Run an export on preloaded development data and confirm that image hrefs point to tile layers rather than s3 urls
- create export:
```
echo '{                                                                                                                 
"name": "sample  export",
"taskStatuses": [],
"license": {
"license": "proprietary",
"url": null
},
"campaignId": "8d5f36b7-83a5-4115-975b-278bbc059c09"
}' | http --auth-type=jwt POST :9100/api/stac/ …
```

Export tileurls for campaigns

---

scripts/update

The update script was using the system `sbt`, rather than the one local to the repo. This could result in Java version issues.
- ~~[ ] Description of PR is in an appropriate section of the [changelog](https://github.com/raster-foundry/raster-foundry/blob/develop/CHANGELOG.md) and grouped with similar changes if possible~~
- ~~[ ] Swagger specification updated~~
- ~~[ ] New tables and queries have appropriate indices added~~
- ~~[ ] Any content changes are properly templated using `BUILDCONFIG.APP_NAME`~~
- ~~[ ] Any new SQL strings have tests~~
- ~~[ ] Any new endpoints have scope validation and are included in the integration test csv~~
- Run `./scripts/update` and ensure it succeeds

Use correct version of sbt in scripts/update

---

CHANGELOG.md
app-backend/batch/src/main/scala/stacExport/v2/CampaignExport.scala
app-backend/db/src/main/scala/AnnotationLabelDao.scala
app-backend/db/src/main/scala/AnnotationProjectDao.scala

This PR fixes a bug in campaign STAC exports so that:
- the label data has class name information
- the label stac time has class names
- Assemble batch jar, rebuild batch service, spin up servers
- Connect local Groundwork to your local RF servers
- In a campaign with class definition and labels, start an export, and grab the export ID
- Open a batch bash shell while servers are running, run `java -cp /opt/raster-foundry/jars/batch-assembly.jar com.rasterfoundry.batch.Main write_stac_catalog <export …

Add classes to campaign export label STAC item and label data

---

CHANGELOG.md
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/services/SceneService.scala
app-backend/common/src/main/scala/com/rasterfoundry/common/color/ColorCorrect.scala
app-backend/db/src/main/scala/MVTLayerDao.scala

This PR fixes three things:
- it expands the coordinate space for MVTs from 256 to 4096 coords -- this is the default, and the 256 was leftover from performance testing. I believe that the reduced coordinate space is responsible for some visual artifacts I've encountered while testing with complex labels, and also the size of the coordinate space had no impact on performance when I tested.
- it skips normalization when the min/max for the histogram breaks are in the 0 - 255 range
- it turns color correction back on for scene thumbnails, since without color correction we got the fuzzy chaos imagery
Thumbnail of non-byte raster:
Byte raster vis:
compare byte raster vis to prod:
I don't have a good demo for the MVT coordinate space, but you can verify the claim about the default here: …

Fix color correction for byte rasters and scene thumbnails, and MVT coordinate space

---

CHANGELOG.md
app-backend/api/src/main/scala/Main.scala
app-backend/api/src/main/scala/utils/Config.scala
app-backend/api/src/main/scala/utils/IntercomNotifications.scala
app-backend/batch/src/main/scala/groundwork/Config.scala
app-backend/batch/src/main/scala/groundwork/CreateTaskGrid.scala
app-backend/batch/src/main/scala/groundwork/NotifyIntercom.scala
app-backend/batch/src/main/scala/groundwork/dbIO.scala
app-backend/batch/src/main/scala/stacExport/WriteStacCatalog.scala
app-backend/build.sbt
app-backend/datamodel/src/main/scala/UserIntercomConversation.scala
app-backend/db/src/main/resources/migrations/V73__Add_users_intercom_conversations.sql
app-backend/db/src/main/scala/UserIntercomConversationDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/UserIntercomConversationDaoSpec.scala
app-backend/notification/src/main/scala/com/rasterfoundry/notification/intercom/IntercomConversation.scala
app-backend/notification/src/main/scala/com/rasterfoundry/notification/intercom/Model.scala
app-backend/notification/src/main/scala/com/rasterfoundry/notification/intercom/NotifyIntercom.scala

This PR supports intercom communications by having conversations with customers:
- add migration, data model, dao methods, and tests for previous conversation IDs and for new conversation IDs
- add intercom endpoint calls for creating a conversation and for replying to conversations
- in places where we dispatch intercom notifications, hook up the above two to work together:
- create task grid
- upload processing
- stac exports
All system messages appear in one conversation
- Run migration
- Assemble api jar and batch jar, rebuild batch service if need be
- In a batch shell, make sure running …

Support Intercom conversations

---

CHANGELOG.md
app-backend/api/src/main/scala/Main.scala
app-backend/api/src/main/scala/Router.scala

This PR puts all of our rejection handling in one place and also uses the default rejection handler in addition to the custom RF one.
The upshot of that is that common sense handling like "include the CORS headers if needed" is free. I opted to move all of that into `Main` instead of into the `Router` because it's consistent with how `Backsplash` organizes things -- now the `Router` is only responsible for assembling routes, and `Main` is responsible for things like CORS and middlewares.
- use raster-foundry/groundwork#1394 to test
Closes azavea/raster-foundry-platform#402

Put all rejection handling in one place

---

CHANGELOG.md
app-backend/api/src/main/scala/annotation-project/AnnotationProjectTaskRoutes.scala

This PR checks that tasks users are interested in interacting with are in the project that the route says.
- assemble API server
- get a token with your dev user -- `echo '{"refresh_token": "the-dev-user-refresh-token"}' | http :9000/api/tokens | jq .id_token`
- `export JWT_AUTH_TOKEN=that-token`
- try this request -- `http --auth-type=jwt :9000/api/annotation-projects/6e35b51e-4d67-4cb0-bf23-ca265ef49b24/tasks/3279f4ba-455f-421d-b822-3acb5c502e5b`
- you should get a 403
- check that that task isn't in that project
- verify that all the routes in `AnnotationProjectTaskRoutes` that invoke methods just from `TaskDao` with the `taskId` have the similar authorization
Closes raster-foundry/groundwork#1360

Authorize based on task <-> project combination

---

CHANGELOG.md
app-backend/akkautil/src/main/scala/CommonHandlers.scala
app-backend/api/src/main/scala/uploads/Routes.scala
app-backend/datamodel/src/main/scala/Upload.scala
app-backend/db/src/main/scala/UploadDao.scala

This PR updates the upload create and update endpoints to enforce stricter storage quota checks.
- Follow steps in https://github.com/raster-foundry/groundwork/pull/1406 to test
Closes https://github.com/raster-foundry/raster-foundry/issues/5565

Make upload limit check stricter

---

app-backend/api/src/main/scala/annotation-project/AnnotationProjectTaskRoutes.scala
app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/MosaicImplicits.scala
app-backend/datamodel/src/main/scala/AnnotationLabel.scala

This PR uses `parTraverseN` from cats-effect to prevent huge mosaics from trying to parallelize over every contained scene. Here's a quick snapshot of why that's bad:
That single request also created nearly 600 `raster-io` threads. Woops!
Those spikes up to almost 4gb of heap usage on a nearly 7gb heap are from a single request. Here's the same request with the capped parallelism:
And even requesting the whole layer at the same zoom (so there are several requests trying to use the cached threadpool at the same time) my max thread number is still < 300.
Anyway, this should prevent the kind of resource-based crash we recently saw.
- assemble backsplash
- bring up API server and backsplash
- get a bearer token for dev using either the refresh token in lastpass or by copying it from dev tools …

Use parTraverseN to control mosaic parallelism

---

app-backend/common/src/test/scala/com/implicits/Generators.scala
app-backend/datamodel/src/main/scala/AnnotationLabel.scala
app-backend/db/src/main/resources/migrations/V74__add_session_to_label.sql
app-backend/db/src/main/resources/migrations/V75__add_index_to_annotation_labels.sql
app-backend/db/src/main/scala/AnnotationLabelDao.scala
app-backend/db/src/main/scala/MVTLayerDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/AnnotationLabelDaoSpec.scala
app-backend/db/src/test/scala/com/azavea/rf/database/CampaignDaoSpec.scala

This PR:
- updates the `annotation_labels` table with two new columns `is_active` and `session_id`
- updates the data model of `AnnotationLabel` and its related so that the current frontend data model won't need to change
- updates the dao methods so that they list `is_active = true` labels when appropriate
- updates property tests so that they take these fields into consideration
- Run migrations
- Assemble servers, connect GW frontend to your local RF servers
- In a campaign, make sure the label and validate UIs still let you label, confirm, reopen, validate tasks and submit …

Add sessionId and isActive to AnnotationLabel 

---

CHANGELOG.md
app-backend/api/src/main/scala/tasks/Routes.scala
app-backend/db/src/main/scala/AnnotationLabelDao.scala
app-backend/db/src/main/scala/Dao.scala

This PR introduces a new query builder for all Daos called the `GroupQueryBuilder`. It lets us add filters to grouped queries in an abstract way. Currently, the only type of query it supports is an unlimited list. The reason for this is that it's only currently used to fix an [especially painful label query](https://azavea.slack.com/archives/C011W71JPM0/p1622151830009700?thread_ts=1622151615.008600&cid=C011W71JPM0), where we had a `GROUP BY` in a subquery to avoid collisions with the querybuilder logic, or at least that's my theory for why we had that.
Applying this change manually to a query from slow query logs took total time from ~1.5 seconds to < 1 ms.
- tests are fine

Repair slow annotation label query

---

CHANGELOG.md
app-backend/api/src/main/scala/tasks/Routes.scala
app-backend/datamodel/src/main/scala/TaskSession.scala
app-backend/db/src/main/resources/migrations/V76__add_previous_session_to_sessions.sql
app-backend/db/src/main/scala/AnnotationLabelDao.scala
app-backend/db/src/main/scala/TaskSessionDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/AnnotationLabelDaoSpec.scala
app-backend/db/src/test/scala/com/azavea/rf/database/TaskSessionDaoSpec.scala

This PR updates the task session complete endpoint so that it disables the labels from the previous sessions of the same task and promotes the current task session.
- CI should pass as new property tests were added for the dao methods
- Follow steps here: https://github.com/raster-foundry/raster-foundry/pull/5522 to create a task session of task `A`, post some labels to the task and `complete` the task session. Make sure the labels are posted to the task and the session and the labels are set to `is_active = true`
- Create a new session …

Update Session complete endpoint

---

CHANGELOG.md
app-backend/db/src/main/resources/migrations/V77__index_label_class_group_fk.sql

One query that slows down under load is the query for label classes within a group. It turns out we didn't index that foreign key. With as many classes as there are in prod, this can slow down under load.
The query plan for the query currently deployed uses a `SEQ SCAN` on the table to filter for the group. After I applied this index, it uses an index scan instead.
- I can show the query plans

Index the label class group fk

---

CHANGELOG.md
app-backend/db/src/main/scala/ProjectDao.scala
app-backend/db/src/main/scala/TaskDao.scala

This PR sets `is_active` appropriately when splitting tasks.
There's an open question about task splits still, which is -- what happens with the task session? Do the new labels still get associated with the current task session? Does the labeling session post-split continue on the next task? Not clear to me! Anyway, this solves the immediate problem and we should talk about the rest later.
I think we'll have to get `is_active` and session stuff from the previous task eventually, but I'm skipping that for now to make things work again.
- with the develop branch:
- assemble api server
- start servers, GroundWork
- create an object detection project or use one you already have (it's easiest to see the manifestation of the error with object detection)
- draw labels in four corners of one of …

Set is_active when splitting tasks

---

CHANGELOG.md
app-backend/db/src/main/resources/migrations/V78__index_label_class_in_labels_to_classes_join.sql

This PR adds a migration for an index on the label class id in the `annotation_labels_annotation_label_classes` table.
Dropped a query from > 700ms to 78ms
- run the query from the linked issue in metabase
- see that it's fast now (if you choose "table" view from the dropdown, you can copy the json out really easily for tatiyants.com/pev)
Helps with azavea/raster-foundry-platform#1263

Index label classes in labels <-> classes join

---

CHANGELOG.md
app-backend/db/src/main/scala/CampaignDao.scala

This PR filters tasks to those in the campaign requested in the random task endpoint. Without this filter, this section of the query was running its aggregation on the whole tasks table https://github.com/raster-foundry/raster-foundry/blob/develop/app-backend/db/src/main/scala/CampaignDao.scala#L298-L307
This change improved my test query from 2.5s to 232ms, which still isn't ideal but is enough of an improvement that it should keep the database happier.
I'm a little confused about the relationships here -- for some reason it doesn't matter to the tests if I join via `t1` or `t2` in the changed section. That said, I think the cases exercised by the tests are sufficient to show that it actually doesn't matter, instead of this being a weird artifact of something we did.
- tests
Helps with …

filter tasks by campaign in random review task query

---

CHANGELOG.md
app-backend/api-it/src/test/resources/endpoint-scopes.csv
app-backend/api/src/main/scala/campaign/Routes.scala
app-backend/datamodel/src/main/scala/CampaignPerformance.scala
app-backend/datamodel/src/main/scala/PaginatedGeoJsonResponse.scala
app-backend/datamodel/src/main/scala/PaginatedResponse.scala
app-backend/datamodel/src/main/scala/com/rasterfoundry/datamodel/PageRequest.scala
app-backend/db/src/main/scala/AnnotationDao.scala
app-backend/db/src/main/scala/CampaignDao.scala
app-backend/db/src/main/scala/SceneWithRelatedDao.scala
app-backend/db/src/main/scala/TaskDao.scala
app-backend/db/src/main/scala/TaskSessionDao.scala
app-backend/db/src/main/scala/util/Page.scala
app-backend/db/src/test/scala/com/azavea/rf/database/CampaignPerformanceSpec.scala

This PR adds performance endpoints for campaign labeling and validating.
One surprising change here was changing types in `Page` and `PaginatedResponse`. According to `doobie`, the `limit` and `offset` parameters expected `bigints`, while we were passing `Int`s. I think maybe this doesn't make a difference in real life when running queries, but because so many of our queries are _run_ instead of just _typechecked_, we didn't notice until now (or something changed with doobie and postgres between when we started with doobie and now). Anyway, I don't think this will make a practical difference?
These queries are typechecked instead of property tested because the amount of setup necessary to get a realistic test with pagination and multiple users and expectations over aggregations and sorts …

Add performance endpoints

---

CHANGELOG.md
app-backend/api-it/src/test/resources/endpoint-scopes.csv
app-backend/api/src/main/scala/tasks/Routes.scala
app-backend/datamodel/src/main/scala/AnnotationLabel.scala
app-backend/db/src/main/scala/AnnotationLabelDao.scala
app-backend/db/src/main/scala/TaskSessionDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/TaskSessionDaoSpec.scala

This PR adds label CRUD endpoint related to task sessions.
- Assemble backend, run migration, spin up frontend and backend, grab a token
- From the DB, grab a task's ID that has UNLABELED status
- Grab some label classes from one of your campaign that has the task from step 2
- Create a task session with the task ID you grabbed from the last step
```
curl --location --request POST 'http://localhost:<your port number>/api/tasks/<task id>/sessions' \
--header 'Authorization: Bearer <your_token>' \
--data-raw '{
"sessionType": "LABEL_SESSION"
}'
```
- List active labels of this …

Add CRUD for task session labels

---

CHANGELOG.md
app-backend/api-it/src/test/resources/endpoint-scopes.csv
app-backend/api/src/main/scala/annotation-project/AnnotationProjectTaskRoutes.scala
app-backend/api/src/main/scala/annotation-project/Routes.scala
app-backend/common/src/test/scala/com/implicits/Generators.scala
app-backend/datamodel/src/main/scala/Task.scala
app-backend/db/src/main/scala/TaskDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/TaskDaoSpec.scala

This PR:
- adds a data model and an endpoint for updating task status and action only
- adds dao methods and property tests for this new endpoint
- updates endpoint for adding label, so that when next status is provided in the label request, use the new dao method to update task status and action
- CI should pass as new tests are added in this PR
- Use instructions in: https://github.com/raster-foundry/groundwork/pull/1529 to test changes in action
Closes https://github.com/azavea/raster-foundry-platform/issues/1278

Add endpoint to update task status and action only

---

CHANGELOG.md
app-backend/api-it/src/test/resources/endpoint-scopes.csv
app-backend/api/src/main/scala/tasks/Routes.scala
app-backend/db/src/main/scala/TaskSessionDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/TaskSessionDaoSpec.scala

This PR adds an endpoint `api/tasks/{id}/session/active` to return the active session of a task.
- CI should pass as new property tests were added for the dao method
- Assemble backend, run migration, spin up frontend and backend, grab a token
- From the DB, grab a task's ID that has UNLABELED status
- Get an active session of the task. It should return an empty response
```
curl --location --request GET 'http://localhost:<your port number>/api/tasks/<task_id>/sessions/active' \
--header 'Authorization: Bearer <your_token>'
```
- Create a task session
```
curl --location --request POST 'http://localhost:<your port …
```

Add endpoint to get active task session

---

CHANGELOG.md
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Main.scala
app-backend/db/src/main/scala/TaskDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/TaskDaoSpec.scala

This PR:
First CI failure is the demonstration that the test cooperates
Search "Failing row contains" in CloudWatch logs in the backsplash container to see that this replicates the production failure.
The `task unlocking respects most recent status` test ensures that I didn't ruin the other task status logic while fixing the flagged task logic.
- tests are fine
Closes #5605

Fix bad logic for getting most recent note in task status regression

---

CHANGELOG.md
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/services/AnnotationProjectMVTService.scala

This PR adds a `no-cache` directive to the task MVT response and a `max-age=60` directive to the label MVT response. In conjunction with raster-foundry/groundwork#1593, it helps make sure the project overviews are significantly more up-to-date.
We have to do this kind of testing for now because of internal caching in mapbox-gl -- the GroundWork PR maaaaybe addresses that? it's a bit unclear.
ON STAGING
- find an annotation project project with some unlabeled tasks
- choose one of them (remember where it is)
- label it and confirm
- click the x
- reopen the project overview --  your task will not have a new status 😡
On this branch locally
- assemble backsplash, bring up servers
- bring up local GroundWork
- do the same thing
- note that when you reopen the task map, your task has a _new …

Add cache control to label and task MVT routes

---

CHANGELOG.md
app-backend/akkautil/src/main/scala/Authentication.scala
app-backend/datamodel/src/main/scala/auth/AuthorizedToken.scala
scripts/update

This PR makes a few changes to setup instructions and interaction with Auth0.
The setup instructions change was to remove the directory navigation from `scripts/setup`. After #5602, it's no longer correct to switch to `app-backend` to assemble things.
The Auth0 interaction changes make it so that:
- we don't get a `NullPointerException` when we have JWTs that are missing a specific claim
- we can get exchange refresh tokens for bearer tokens using the ROP flow documented in azavea/raster-foundry-platform#1306 (the response is a different shape in that setting)
- tested extensively as part of azavea/raster-foundry-platform#1295

Setup improvements

---

CHANGELOG.md
README.md
app-backend/api/src/main/scala/uploads/Credentials.scala
app-backend/api/src/main/scala/uploads/Routes.scala
app-backend/datamodel/src/main/scala/Upload.scala
app-tasks/rf/src/rf/uploads/geotiff/factories.py
app-tasks/rf/src/rf/utils/cog.py
scripts/process-upload

Maintain the original filename when generating COGs.
- ~[ ] Swagger specification updated~
- ~[ ] New tables and queries have appropriate indices added~
- ~[ ] Any content changes are properly templated using `BUILDCONFIG.APP_NAME`~
- ~[ ] Any new SQL strings have tests~
- ~[ ] Any new endpoints have scope validation and are included in the integration test csv~
COGs now have a S3 URI like: `s3://<bucket>/user-uploads/<user_id>/<scene_id>/<original_filename>`. For example:
```
$ aws s3 ls 's3://rasterfoundry-development-data-us-east-1/user-uploads/auth0|59318a9d2fbbca3e16bcfc92/0d7b3e29-2dae-48f0-b8a0-e2d1659852ad/'
2021-08-11 15:42:15   17976459 382.tif
```
- `sbt "project api" assembly`
- `./scripts/server`
- Grab a test TIF from the Groundwork UAT folder …

Use original filename for COG

---

CHANGELOG.md
app-backend/batch/src/main/scala/stacExport/v2/CampaignExport.scala
app-backend/common/src/test/scala/com/implicits/Generators.scala
app-backend/datamodel/src/main/scala/AnnotationLabel.scala
app-backend/db/src/main/resources/migrations/V80__add_confidence_to_labels.sql
app-backend/db/src/main/resources/migrations/V80__add_score_to_labels.sql
app-backend/db/src/main/scala/AnnotationLabelDao.scala
sbt

This PR adds a nullable `confidence` field to labels. It also updates STAC exports to use the label extension URI instead of the shorthand, since [technically the shorthand isn't allowed anymore](https://github.com/radiantearth/stac-spec/blob/master/CHANGELOG.md#v100-rc4---2021-05-11). It also updates the `sbt` launcher, which we kind of should do every once in a while, but which doesn't seem to make much of a difference for anything right now.
I tested with GroundWork to make sure that the labeling interactions and label MVT layer are all still fine. I did not test with other apps. However, given that this doesn't touch any of the more complex data management stuff (just adds a nullable field to serialization / deserialization) and that the field isn't required to be present during …

Add confidence to labels

---

CHANGELOG.md
app-backend/backsplash-server/src/main/resources/application.conf
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Config.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/Main.scala
app-backend/backsplash-server/src/main/scala/com/rasterfoundry/backsplash/services/HealthcheckService.scala

This PR extends the healthcheck timeout in backsplash from 3 to 10 seconds. 10 seconds isn't a magic / perfect number, but it's at least longer than the ALB healthcheck, which we want to be the case so that whether the load balancer can receive a timely response from the tile server determines service health.
I verified that the healthcheck parallelism was cooperating by adding prints at the start and end of each healthcheck and got these logs:
```
backsplash_1              | Checking db health
backsplash_1              | Checking cache health
backsplash_1              | Done checking db health
backsplash_1              | Done checking cache health
```
So that part is at least cooperating 🤔
This doesn't affect healthcheck speed, but it should get us fewer false positives
- compare the …

Extend healthcheck to 10 seconds in service

---

CHANGELOG.md
app-backend/api-it/src/test/resources/endpoint-scopes.csv
app-backend/api/src/main/scala/annotation-project/Routes.scala
app-backend/common/src/test/scala/com/implicits/Generators.scala
app-backend/datamodel/src/main/scala/AnnotationLabel.scala
app-backend/db/src/main/scala/AnnotationLabelDao.scala
app-backend/db/src/main/scala/MVTLayerDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/AnnotationLabelDaoSpec.scala

This PR:
- adds a new route to annotation projects called `hitl`, which exposes whether any labels in that project have _scores_ attached to them as a boolean
- adds label scores to the label MVT layer when present
Here's what it enables:
https://user-images.githubusercontent.com/5702984/131262186-6aea69ca-6ba8-47da-8ffd-b1932433f72c.mp4
The `hitl` boolean information _could_ live on the projects themselves, but I opted against that for now to avoid having to worry about how messing that query would affect other parts of applications that consume annotation projects. This way if I get the query wrong or it turns out to be more costly than I expect (it shouldn't! it's an "exists" query on an indexed column) most things won't have to care, and if we want to Do This For Real™️ we can update …

Expose human-in-the-loop info on annotation project routes and MVT labels layer

---

CHANGELOG.md
app-backend/batch/src/main/scala/stacExport/v2/CampaignExport.scala
app-backend/batch/src/main/scala/stacExport/v2/newtypes.scala

This PR:
- updates the imagery item's COG asset `href` so that it is a relative path to a locally downloaded image
- updates the tile field of these imagery assets to be more descriptive instead of IDs
- updates the IDs of each imagery item so that they are the same as the annotation project ID
- adds a map to collect `projectId -> S3 ingest location` along the way of collecting resources and uses this map to download COG images before packing all together
- A `test/fix-cog-asset-link` branch is …

Fix STAC export image item's asset href and links

---

CHANGELOG.md
app-backend/batch/src/main/scala/stacExport/WriteStacCatalog.scala
app-backend/batch/src/main/scala/stacExport/v2/CampaignExport.scala
app-backend/batch/src/main/scala/stacExport/v2/README.scala
app-backend/datamodel/src/main/scala/StacExport.scala
app-backend/db/src/main/resources/migrations/V82__add_expiration_to_stac_exports.sql
app-backend/db/src/main/scala/StacExportDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/StacExportDaoSpec.scala

This PR updates the STAC export code to ship exports with COGs to a special prefix. That prefix matches what's configured in azavea/raster-foundry-deployment#290.
It also:
- updates the generated README to describe what assets are present
- makes logs a little less noisy
- escapes `|` characters in project names, since they were breaking the markdown table
- Download the catalog at `s3://rasterfoundry-development-data-us-east-1/stac-exports/cog-exports/41336b2c-2467-44e4-a04b-061ee0adb85c/catalog.zip` and unzip it
- check out its README -- it should look nice
- put its README in something that renders markdown (either preview in VSCode or throw it into a gist or something) and confirm that the project names' pipes appear in the right column
- note that its path is at …

Ship COG exports to special prefix for expiration

---

CHANGELOG.md
app-backend/batch/src/main/scala/stacExport/v2/CampaignExport.scala
app-backend/datamodel/src/main/scala/StacExport.scala

This PR fixes a few small bugs related to pro export:
- includes the asset types in the export object after signing
- includes the expiration in the export object after signing
- makes sure that we still write the item when we don't have a COG asset
I can demo this since I have a nice export lying around locally that goes fast
- assemble servers and batch
- bring up servers
- bring up GroundWork pointed to local
- create an export and process it
- refresh the STAC list and look at the network tab -- the `/stac` response should include expiration and export asset types
- download your export -- even though it doesn't have a COG you should still have an item
Closes #5624

Pro export polish

---

CHANGELOG.md
app-backend/api/src/main/resources/application.conf
app-backend/api/src/main/scala/user/Auth0User.scala
app-backend/api/src/main/scala/user/Routes.scala
app-backend/api/src/main/scala/utils/Config.scala
app-backend/datamodel/src/main/scala/User.scala
scripts/test

This PR adds `isAltConnection` field to the `UserBulkCreate` case class, which is consumed by the user bulk create endpoint. Depending on this field, the API will use different Auth0 connection configs read from the environment to insert new users in bulk.
- More to come
Closes https://github.com/azavea/raster-foundry-platform/issues/1382

Add connection config to user bulk create

---

CHANGELOG.md
app-backend/batch/src/main/scala/stacExport/WriteStacCatalog.scala
app-backend/batch/src/main/scala/stacExport/v2/CampaignExport.scala
app-backend/common/src/main/scala/S3.scala

This PR switches the `putObject` method of the zipped STAC catalog export to the multipart upload method from the java s3 sdk.
- Review this one first: https://github.com/azavea/raster-foundry-deployment/pull/294
- Push a `test/` branch up to trigger a staging deploy for this PR
- Go to https://develop--raster-foundry-annotate.netlify.app/app and log in with your Azavea Google Account
- Ping me to share you a campaign with a lot of images and bump you to PRO account on staging
- Create a STAC export and select to download with images
- …

Switch to multipart upload for STAC export

---

CHANGELOG.md
nginx/etc/nginx/templates/default.conf.template

This PR updates the `client_max_body_size` config for the `/api/annotation-projects/<id>/tasks/<id>/labels` endpoint so that the POST body has a larger upper-bound of 10MB. 
- [See here](https://azavea.slack.com/archives/CDB8M6W7M/p1650396170835869) for a demo of posting large amount of labels to a task on staging, as this change has been applied on staging through a `test` branch.
Closes https://github.com/azavea/raster-foundry-platform/issues/1393

Update nginx config to allow larger payload for label endpoint

---

.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
app-backend/api-it/src/test/resources/endpoint-scopes.csv
app-backend/api/src/main/scala/Router.scala
app-backend/api/src/main/scala/hitl-jobs/Routes.scala
app-backend/api/src/main/scala/utils/QueryParameters.scala
app-backend/common/src/test/scala/com/implicits/Generators.scala
app-backend/datamodel/src/main/scala/HITLJob.scala
app-backend/datamodel/src/main/scala/HITLJobStatus.scala
app-backend/datamodel/src/main/scala/QueryParameters.scala
app-backend/db/src/main/resources/migrations/V83__Add_hitl_jobs_table.sql
app-backend/db/src/main/scala/HITLJobDao.scala
app-backend/db/src/main/scala/filters/Filterables.scala
app-backend/db/src/main/scala/meta/EnumMeta.scala
app-backend/db/src/test/scala/com/azavea/rf/database/HITLJobDaoSpec.scala

This PR adds CRUD API endpoints for `hitl-jobs`.
- Pair to test all new endpoints.
https://github.com/azavea/foss4g-2022-hitl-groundwork-rastervision/issues/1

Add HITL Job CRUD endpoint

---

CHANGELOG.md
app-backend/api-it/src/test/resources/endpoint-scopes.csv
app-backend/api/src/main/scala/tasks/Routes.scala
app-backend/common/src/test/scala/com/implicits/Generators.scala
app-backend/datamodel/src/main/scala/Task.scala
app-backend/db/src/main/resources/migrations/V85__add_priority_to_task.sql
app-backend/db/src/main/scala/CampaignDao.scala
app-backend/db/src/main/scala/HITLJobDao.scala
app-backend/db/src/main/scala/TaskDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/TaskDaoSpec.scala

This PR:
- adds `priority_score` field to `tasks`
- updates the related data models and dao methods
- adds an endpoint to get a hitl prioritized task
- will walk through in pairing
Closes https://github.com/azavea/foss4g-2022-hitl-groundwork-rastervision/issues/9

Update task; Add an endpoint to get prioritized task

---

app-hitl/Dockerfile
app-hitl/hitl/run_hitl.py
app-hitl/hitl/utils.py
app-hitl/requirements.txt
docker-compose.yml

- Updates the Dockerfile to pull from the hitl-specific image on docker hub
- Mounts the `data` dir in RF into the container (this is useful for accessing sample data for testing)
- Installs `rtree` for spatial joining
- Adds a utils file with a function for clipping/joining labels to the task grid
The contents of `hitl/run_hitl.py` are still just placeholders
- Create a folder called `hitl` in `data`
- Move the sample files: `hitl-tasks.json` and `hitl-predictions.geojson` int `data/hitl`
- run `docker-compose build batch-hitl` to build the container
- run `docker-compose run batch-hitl python hitl/run_hitl.py FAKE_PROJECT_ID` to test out merging the two sample files
- You should see the following output:
```
✔ ~/files/rf/raster-foundry [sk/use-hitl-image|⚑ 8]
15:27 $ docker-compose run …
```

Use HITL specific image from dockerhub

---

CHANGELOG.md
app-backend/api/src/main/scala/annotation-project/AnnotationProjectTaskRoutes.scala
app-backend/db/src/main/scala/AnnotationLabelDao.scala
app-backend/db/src/main/scala/HITLJobDao.scala
app-backend/db/src/test/scala/com/azavea/rf/database/AnnotationLabelDaoSpec.scala
app-hitl/hitl/src/hitl/commands/run_hitl.py
app-hitl/hitl/src/hitl/utils/get_hitl_input.py
app-hitl/hitl/src/hitl/utils/notify_intercom.py
app-hitl/hitl/src/hitl/utils/persist_hitl_output.py
docker-compose.yml

This PR:
- fixes a bug in listing HITL jobs when the requesting user is a super-user
- uses model files from previous job if there is any
- updates job status
- notifies through Intercom of the job status with link to project
- Assemble your local API server jar
- Start your local API server
- Delete all existing HITL job records from `hitl_jobs`
- Spin up GW frontend
- POST to create a new HITL job with the campaign and project with validated labels
- `docker-compose build batch-hitl`
- `./scripts/console batch-hitl "hitl run <your hitl job ID>"` to run the entire job for the first time
- The job should run …

Notify through Intercom of HITL job

---

CHANGELOG.md
app-hitl/hitl/src/hitl/utils/post_process.py

This pr fixes a bug in which only tasks that have include labels get moved into the labeling category. No, after running the first round of a hitl job, all tasks that were not validated in the first round of human labeling will be moved to "labeled".
after running the hitl job, all tasks should be either labeled or validated
This may be a little hard to test because to really test it you need to generate at least one task that has been predicted on but does nat have any predicted labels within it. I have found that if you just draw a couple buildings, there is inevitably buildings in every grid cell, which is why this bug didn't show up until I did some significant labeling of cars. 
- create a new project
- go in and label something very small and specific on a few tasks
- run the hitl …

Move all tasks from unlabeled to labeled after prediction

---

app-hitl/hitl/src/hitl/commands/run_hitl.py

This PR tweaks a couple of params that control the prediction behavior in HITL jobs:
- higher denoise_radius discards noisy predictions and makes polygonization faster
- lower stride allows pixels to be visited multiple times, improving results
N/A
N/A
- Run as before

Update HITL prediction params to improve prediction quality and performance

---

CHANGELOG.md
app-hitl/hitl/requirements.txt
app-hitl/hitl/src/hitl/commands/run_hitl.py
app-hitl/hitl/src/hitl/rv/active_learning.py
app-hitl/hitl/src/hitl/rv/predict.py
app-hitl/hitl/src/hitl/rv/train.py
app-hitl/hitl/src/hitl/utils/merge_labels.py
app-hitl/hitl/src/hitl/utils/post_process.py

This PR
- Fixes https://github.com/azavea/foss4g-2022-hitl-groundwork-rastervision/issues/24
- By updating `geopandas` from version `0.9.0` to `0.10.2`.
- Makes it so that training and prediction params are loaded from a file on S3.
- File location: `s3://rasterfoundry-staging-hitl-output-us-east-1/config/params.json`.
- This will allow us to modify these params without needing to make changes to this repo.
- This is a temporary measure; eventually, we should let GW users set these params via the GW UI.
Other changes:
- Some parameter values have been changed. Most significantly:
- `chips_per_task` has been increased from 20 to 40.
- `fpn_channels` has been increased from 64 to 128 i.e. we're using a slightly bigger model.
- We now start with ImageNet-pretrained weights in the first …

Load params from file on S3 and fix bug with empty predictions
